### ISSUE TITLE
Adding bidder with environment variables

### ISSUE THREAD

**Issue by holms** [prebid/prebid-server#1028]
I'm actually really struggling with documentation of configuring prebid-server. I mean there's no docs at all, this is all we have: https://github.com/prebid/prebid-server/blob/master/docs/developers/configuration.md which says "go to source code to figure out what you need".

In this case I've tried to contact rubicon and appnexus for comments how enable their bidders in configuration, and they seems to be only answering questions when they are  related to prebid.js

I'd like to specify rubicon and appnexus bidders through environment variables. I'm using Kubernetes in here to host prebid-server. Attaching custom config file would be a huge pain in clustered docker environment. I see that there are one flag for enabling rubicon, but enabling appnexus requires dictionary of params, which seems to be valid for prebid.js only, while in docs i've found that  prebid-server configuration  of bidders is the same as prebid.js config. So I'm not really sure how is it the same... Two different language, different data structures, different classes in code. Anyone could please guide me a bit in here?

**Comment by hhhjort** [comment]
Probably be good to confirm that you are asking about the Go version rather than the Java version, the below assumes Go.

The appnexus bidder should work right out of the box (no configuration needed). The basic formula is PBS should start up in a workable state without any configuration being done by the host at all. Those adapters that need configs specific to a host, such as rubicon's, start out in the disables state and need to be enabled via configs. Everything else starts enabled and needs to be disabled.

For setting configs via environment variables, the convention is to start with `PBS_` and then add the config option (in all caps). You can code dive to better understand the option, but on startup PBS will dump all the configs to the log. You may need to pass the arguments `-logtostderr -v 1` in order to see the logs. All periods (`.`) will be replaced by underscores (`_`).

**Comment by holms** [comment]
@hhhjort oh what a nice info. In docs I recall that to enable appnexus and rubicon bidder I need to ask them for some parameters? 

‘’’
Rubicon

Contact your Rubicon Project account manager to get set up with a login and cookie-sync URL to run your own Prebid Server.

You will be given instructions, including the available endpoints.’’’

http://prebid.org/prebid-server/developers/pbs-bidder-info.html

Btw I’m using go version of prebid-server


Maybe these instructions for prebid.js?

**Comment by hhhjort** [comment]
Yes, for Rubicon you need to get per host config parameters to make the adapter work properly, thus the Rubicon adapter defaults to disabled when you start up PBS with no configuration.

Appnexus will run properly with the defaults supplied, if you need to make any changes to the Appnexus default, you would already know what you need to change.

That is to start PBS. On a per request basis, each bidder called in a request will need to be provided its bidder parameters. This is something that is done by the publisher making the request, not the host running PBS. Bidder parameters, among other things, identify who is to be paid if an ad is successfully delivered through PBS. So by nature must be custom to the publisher, and require the publisher to have a relationship with the bidder.

**Comment by holms** [comment]
Interesting. Thank you for this, as from docs for me it wasn’t obvious at
all. One last question before closing down the ticket... so prebid-server
is pretty much like gateway for prebid.js. How do you secure yourself, so
that only yours prebid.js would use this server? I mean, it’s public for
everyone right?

-- 
Roman Gorodeckij

**Comment by bretg** [comment]
> so prebid-server is pretty much like gateway for prebid.js.

It's more like a server-side version of PBJS. The use cases where Prebid Server is indispensable are mobile app and AMP where running PBJS is impossible.

> How do you secure yourself, so that only yours prebid.js would use this server?

Currently you can't in the open source version.

Both PBS-Go and PBS-Java have the ability to get the requesting account ID out of site.publisher.id or app.publisher.id. PBS-Go has the ability to reject accounts that configured on an exclude list.

PBS-Java will soon have both this and exclude-by-default with a list of valid accounts.

If you're setting up a PBS-Go that's intended to be private, you'll need to have a change in your private fork. If you're up to it, you could port the soon-to-be-released PBS-Java pull request into PBS-Go. The approach is straight-forward.

1) We're adding a new config entry:
```
settings:
    enforce-valid-account: true
```
2) If set to true, the incoming request must have an account ID (site.publisher.id/app.publisher.id) that exists in the accounts table.

**Comment by bretg** [comment]
Also, FWIW, there are instructions for setting up PBS-Java in AWS at https://github.com/rubicon-project/prebid-server-java/blob/master/docs/build-aws.md
