### ISSUE TITLE
Fix unreliable tests

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#103]
Travis builds are failing intermittently. Some sample output of the failures is below.

```
ok  	github.com/prebid/prebid-server	0.078s
body {"account_id":"","tid":"","cache_markup":0,"sort_bids":0,"max_key_length":0,"secure":0,"timeout_millis":0,"ad_units":[{"code":"first-tag","is_top_frame":0,"sizes":[{"w":300,"h":250}],"bids":[{"bidder":"audienceNetwork","bid_id":"random-id-from-pbjs-0","params":{"placementId":"987654321_999998888"}}],"config_id":""},{"code":"second-tag","is_top_frame":0,"sizes":[{"w":300,"h":250}],"bids":[{"bidder":"audienceNetwork","bid_id":"random-id-from-pbjs-1","params":{"placementId":"987654321_66775544"}}],"config_id":""}],"is_debug":false,"app":null,"device":null,"user":null,"Start":"0001-01-01T00:00:00Z"}
--- FAIL: TestFacebookBasicResponse (0.01s)
	facebook_test.go:273: Should not have gotten an error: context deadline exceeded
&{ [{div-adunit-1 0xc4203c2800 <nil> <nil>  0 1001 0  0 [] <nil> []}] 0xc420331860 <nil> 0xc420080d00 0xc4202a6280 0 1 0 [] 0 [] [] [] 0xc4201dd180 <nil> []}
body {"account_id":"","tid":"","cache_markup":0,"sort_bids":0,"max_key_length":0,"secure":0,"timeout_millis":0,"ad_units":[{"code":"first-tag","is_top_frame":0,"sizes":[{"w":300,"h":600},{"w":300,"h":250}],"bids":[{"bidder":"rubicon","bid_id":"random-id-from-pbjs-0","params":{"zoneId":8394,"siteId":283282,"accountId":7891}}],"config_id":""},{"code":"second-tag","is_top_frame":0,"sizes":[{"w":300,"h":600},{"w":300,"h":250}],"bids":[{"bidder":"rubicon","bid_id":"random-id-from-pbjs-1","params":{"zoneId":8395,"siteId":283282,"accountId":7891}}],"config_id":""}],"is_debug":false,"app":null,"device":null,"user":null,"Start":"0001-01-01T00:00:00Z"}
Request {"id":"","imp":[{"id":"second-tag","banner":{"w":300,"h":600,"format":[{"w":300,"h":600},{"w":300,"h":250}],"ext":{"rp":{"size_id":10,"alt_size_ids":[15],"mime":"text/html"}}},"ext":{"rp":{"zone_id":8395}}}],"site":{"domain":"nytimes.com","page":"https://www.nytimes.com/2017/05/04/movies/guardians-of-the-galaxy-2-review-chris-pratt.html?hpw\u0026rref=movies\u0026action=click\u0026pgtype=Homepage\u0026module=well-region\u0026region=bottom-well\u0026WT.nav=bottom-well\u0026_r=0","publisher":{"ext":{"rp":{"account_id":7891}}},"ext":{"rp":{"site_id":283282}}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30","ip":"25.91.96.36"},"user":{"buyeruid":"need-an-actual-fb-id"},"at":1,"source":{"fd":1}}
Request {"id":"","imp":[{"id":"first-tag","banner":{"w":300,"h":600,"format":[{"w":300,"h":600},{"w":300,"h":250}],"ext":{"rp":{"size_id":10,"alt_size_ids":[15],"mime":"text/html"}}},"ext":{"rp":{"zone_id":8394}}}],"site":{"domain":"nytimes.com","page":"https://www.nytimes.com/2017/05/04/movies/guardians-of-the-galaxy-2-review-chris-pratt.html?hpw\u0026rref=movies\u0026action=click\u0026pgtype=Homepage\u0026module=well-region\u0026region=bottom-well\u0026WT.nav=bottom-well\u0026_r=0","publisher":{"ext":{"rp":{"account_id":7891}}},"ext":{"rp":{"site_id":283282}}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30","ip":"25.91.96.36"},"user":{"buyeruid":"need-an-actual-fb-id"},"at":1,"source":{"fd":1}}
Request {"id":"","imp":[{"id":"first-tag","banner":{"w":300,"h":600,"format":[{"w":300,"h":600},{"w":300,"h":250}],"ext":{"rp":{"size_id":10,"alt_size_ids":[15],"mime":"text/html"}}},"ext":{"rp":{"zone_id":8394}}}],"site":{"domain":"nytimes.com","page":"https://www.nytimes.com/2017/05/04/movies/guardians-of-the-galaxy-2-review-chris-pratt.html?hpw\u0026rref=movies\u0026action=click\u0026pgtype=Homepage\u0026module=well-region\u0026region=bottom-well\u0026WT.nav=bottom-well\u0026_r=0","publisher":{"ext":{"rp":{"account_id":7891}}},"ext":{"rp":{"site_id":283282}}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30","ip":"25.91.96.36"},"user":{"buyeruid":"need-an-actual-fb-id"},"at":1,"source":{"fd":1}}
Request {"id":"","imp":[{"id":"second-tag","banner":{"w":300,"h":600,"format":[{"w":300,"h":600},{"w":300,"h":250}],"ext":{"rp":{"size_id":10,"alt_size_ids":[15],"mime":"text/html"}}},"ext":{"rp":{"zone_id":8395}}}],"site":{"domain":"nytimes.com","page":"https://www.nytimes.com/2017/05/04/movies/guardians-of-the-galaxy-2-review-chris-pratt.html?hpw\u0026rref=movies\u0026action=click\u0026pgtype=Homepage\u0026module=well-region\u0026region=bottom-well\u0026WT.nav=bottom-well\u0026_r=0","publisher":{"ext":{"rp":{"account_id":7891}}},"ext":{"rp":{"site_id":283282}}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30","ip":"25.91.96.36"},"user":{"buyeruid":"need-an-actual-fb-id"},"at":1,"source":{"fd":1}}
Error in rubicon adapter: context deadline exceededError in rubicon adapter: context deadline exceededFAIL
```

Expected: Unit tests always pass or fail reliably.

**Comment by hhhjort** [comment]
This error is from a timer set before any facebook "requests" are made. The timeout is only 1 millisecond, which would be crazy if we were not calling a dummy server. The dummy server returns 2 bid responses in this test, with one response delayed by 20 milliseconds. We will not report an error unless both bids error out, in which case we are reporting the error associated with the last erroring bid response. Unfortunately the earlier error message is discarded.

Do we have any context on the intermittent failure? Do we ever see it happen on a known unloaded system? My suspicion is the 1 millisecond timeout is too aggressive, and the second bid call (which is the one that is not delayed) is not happening until after the timeout on a busy system occasionally. If this is the issue, we may be able to resolve it by upping the timeout to 5 milliseconds. This will add 4 milliseconds to the runtime of the test, but that doesn't seem to be a bad price to pay.

**Comment by dbemiller** [comment]
That's an option.

I don't know enough about the fake server code... but in some languages, it's also possible to "fake" time in some way. For example, a JS library sinon offers [fake timers](http://sinonjs.org/releases/v3.2.0/fake-timers/) which lets you advance time programatically.

In Java that's not possible, so you'd have to refactor the code so that "the time" is passed into the methods you're trying to test. See something like [this guy's suggestion](https://stackoverflow.com/a/5622222).

I'm not sure if there's an idiomatic way to do this in Go... and I haven't looked at the code surrounding these tests, so I'm not sure how easy or hard it is to refactor. It's some food for thought, though.

**Comment by hhhjort** [comment]
The time handling is fine, and does something similar to that suggestion. A timeout threshold is set to "now" + 1 millisecond, and this threshold is then used for the bid requests. One bid response is set with code to delay it by 20 milliseconds, the second response has no delay. My theory is the timing is too tight for a busy system. Unless part of the test is that the response from the dummy server should come in within the 1 millisecond timeout. But then there should be a test to directly target that, rather than test the response comes back within 1 millisecond - time to execute some other code.

This is why I asked for context. I have not been able to reproduce the issue myself. If there is some pattern we can see in when it does and does not fail, that would be a clue if my assumption is correct. Also without having any idea on how to reproduce, I cannot test if my suggestion will fix anything.

**Comment by dbemiller** [comment]
I wish :(... but no, I haven't seen anything which leads me to believe it's reproducible.

I think you're very likely right that the timeouts are the root of the issue, though.

**Comment by mkendall07** [comment]
We could always just increase the suspected timeout a bit to something more reasonable (100ms) and see if the issue goes away.

**Comment by hhhjort** [comment]
If we want to set the timeout to 100ms, we need to up the delay to be larger than that. Do remember that this is a dummy server and no connections are going over the net for this test. Going from 1 to 5 should hopefully resolve the issue.

**Comment by mkendall07** [comment]
@hhhjort can you open a PR for this?

**Comment by hhhjort** [comment]
Pull request created:
Facebook fix test (fixes issue #103) #135

**Comment by dbemiller** [comment]
This popped up again in [this build](https://travis-ci.org/prebid/prebid-server/jobs/282374329)

```
--- FAIL: TestFacebookBasicResponse (0.03s)
	facebook_test.go:275: Should not have gotten an error: context deadline exceeded
body {"account_id":"","tid":"","cache_markup":0,"sort_bids":0,"max_key_length":0,"secure":0,"timeout_millis":0,"ad_units":[{"code":"first-tag","is_top_frame":0,"sizes":[{"w":320,"h":480}],"bids":[{"bidder":"lifestreet","bid_id":"random-id-from-pbjs-0","params":{"slot_tag":"slot123.123"}}],"config_id":"","media_types":null,"instl":0},{"code":"second-tag","is_top_frame":0,"sizes":[{"w":320,"h":480}],"bids":[{"bidder":"lifestreet","bid_id":"random-id-from-pbjs-1","params":{"slot_tag":"slot122.122"}}],"config_id":"","media_types":null,"instl":0}],"is_debug":false,"app":{"bundle":"AppNexus.PrebidMobileDemo"},"device":{"ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E8301","ip":"111.111.111.111","make":"Apple","model":"x86_64","connectiontype":1,"ifa":"6F3EA622-C2EE-4449-A97A-AE986D080C08"},"user":null,"sdk":null,"Start":"0001-01-01T00:00:00Z"}
```

**Comment by hhhjort** [comment]
Don't see anything that should invalidate my previous investigation. Is this in any way repeatable, or is this just the first random occurrence since my fix?

I may have to make a PR to add more debugging around this if it is random and persists.

**Comment by dbemiller** [comment]
Jus the first random occurrence since your fix (that I've seen so far)

**Comment by dbemiller** [comment]
One silly, easy option came to mind:

We could refactor the Adapters' `Call()` implementations into three methods: `buildRequest()`, `doRequest()`, and `makeBids(serverResponse)`.

Since `doRequest()` would only be ~5 lines long, we could still get high unit test coverage by specifically testing `buildRequest()` and `makeBids(serverResponse)`. Then the unit tests wouldn't need to fuss with mock servers or timeouts, which should fix these issues.
