### ISSUE TITLE
C2S/S2S which is more general?

### ISSUE THREAD

**Issue by mobsmartJP** [prebid/prebid-server#1032]
Hi.
I am currently working on headerbidding and my tech team wants to know which is more general (in Japan if you know) between C2S and S2S?
We know both methods of connections has pros and cons but just wanted know...

Thank you.

**Comment by mobsmartJP** [comment]
Also, if % is available, please let me know.

Thank you.

**Comment by hhhjort** [comment]
WIth S2S, you will have to do usersyncs on your server, as PBS won't have access to any of the client's cookies. Its primary advantage is probably lower latency, in requesting bids before the page starts loading. This is most powerful in the case where the server can prefetch ads, for example in a long form video stream you know when the ad breaks are and can fetch bids ahead of time.

**Comment by bretg** [comment]
Client-Side header-bidding is still more common for web scenarios. Server-side is the only way to support mobile apps and AMP. 

There are additional testing features being built to be able to get better data about client-vs-server. When solid data is available, we'll post it on prebid.org. Hopefully next year.
