### ISSUE TITLE
Some of the default usersync endpoints aren't working properly

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#1038]
@Kevin-P-Kerr  triplelift usersync gives only:
https://eb2.3lift.com/sync?gpdr=0&cmp_cs=
It needs something to tell triplelift where to send the uid to.

@sa1omon  gamoshi doesn't seem to redirect properly.

@unrulydevelopers  unruly seems to be an iframe type rather than redirect

**Comment by sa1omon** [comment]
@hhhjort Hi,
We have released a fix for this issue a few hours ago. 
If you checked it just now and it still doesn't work, can you give me more details about what is not working properly?
Thank you.
