### ISSUE TITLE
Accept account argument on AMP requests

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1040]
The one scenario where Prebid Server can't get account ID is AMP. That could become a problem if [stored request IDs aren't globally unique](https://github.com/prebid/prebid-server/issues/1024).

The proposed solution is to have Prebid Server look for the optional `account` parameter on the /amp endpoint, treating it as site.publisher.id if present. 

If the `account` param is empty on the AMP request, it should be ignored.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go by @danielguedesb.
