### ISSUE TITLE
I2I: Prebid server native preprocessor for Prebid mobile banner native

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/prebid-server#1041]
## Problem

Prebid Universal creative needs to know the type of asset to render Prebid Mobile Banner Native. PUC fetches the content from Prebid cache to render the creative. In case of Prebid mobile native, the object returned looks like below. In this response, there is no way to identify asset with id 0 that it it main image or icon. As per native spec 1.2 https://www.iab.com/wp-content/uploads/2017/04/OpenRTB-Native-Ads-Specification-Draft_1.2_2017-04.pdf, Image Response Object has optional type attribute which helps in identifying whether it is main image or icon. Same goes for other assets as well. 
```
// Sample Native Bid Response
{
  "ver": "1.2",
  "assets": [
    {
      "id": 0,
      "img": {
        "url": "https://vcdn.adnxs.com/p/creative-image/7e/71/90/27/7e719027-80ef-4664-9b6d-a763da4cea4e.png",
        "w": 300,
        "h": 250,
        "ext": {
          "appnexus": {
            "prevent_crop": 0
          }
        }
      }
    },
    {
      "id": 1,
      "title": {
        "text": "This is an RTB ad"
      }
    },
    {
      "id": 2,
      "data": {
        "value": "AppNexus"
      }
    }
  ],
  "link": {
    "url": "https:/..."
  },
  "eventtrackers": [
    {
      "event": 1,
      "method": 1,
      "url": "https://ny..."
    }
  ]
}
```

### Option 1
Prebid server needs to preprocess the native response before storing in Prebid cache. Native Preprocessor will check whether type is returned or not, if not it will get the type from original bid request by comparing asset id's and then store the response in Prebid cache.

This preprocessing will only be done for Prebid mobile banner native use case. Prebid mobile native bid request will have a flag to enable preprocess

While rendering creative in Mobile device, Prebid universal creative will have a mapping of assets as per IAB native spec 1.2 to identify type and render the creative.

```
// IAB Native spec 1.2 asset mapping
const nativeAssets = {
  'image': {
    1: 'image',
    3: 'icon'
  },
  'body': {
    ...
  }
}

const nativeMapping = {
  "title": "hb_native_title",
  "body": "hb_native_body",
  "body2": "hb_native_body2",
  "privacyLink": "hb_native_privacy",
  "privacyIcon": "hb_native_privicon",
  "sponsoredBy": "hb_native_brand",
  "image": "hb_native_image",
  "icon": "hb_native_icon",
  "clickUrl": "hb_native_linkurl",
  "displayUrl": "hb_native_displayurl",
  "cta": "hb_native_cta",
  "rating": "hb_native_rating",
  "address": "hb_native_address",
  "downloads": "hb_native_downloads",
  "likes": "hb_native_likes",
  "phone": "hb_native_phone",
  "price": "hb_native_price",
  "salePrice": "hb_native_saleprice"
}
``` 

### Option 2
To go one step further, Prebid server can store just the targeting information in Prebid cache instead of bid response. By doing this, Prebid universal creative has to just search and replace the targeting key value in native display style returned by ad server.

## Open Questions
1. What to do if type is not present in Bid request ? Should we just ignore the bid ?

**Comment by bretg** [comment]
Sorry Jaimin - I'm missing too much background to weigh in. I don't see how PUC supports native, and the prebid.org page on this doesn't clear things up. http://prebid.org/dev-docs/show-native-ads.html

Can you outline the flow here?

1) SDK collects native arguments and initiates auction
2) PBS receives response
3) ...


As a matter of general principle though, we should try to minimize the amount of targeting going back to the ad server. If your option 2 can result in just passing a cache URL through ad server targeting variables, I'm all for it.

**Comment by jaiminpanchal27** [comment]
@bretg 
Overview of Prebid mobile native with Prebid server and Prebid universal creative
1) Prebid mobile SDK makes a native request to Prebid server
2) Prebid server talks to bidders and gets the response back
**Solution will sit here**
3) Prebid server stores the response in Prebid cache
4) Prebid server sends the bid response back to Prebid mobile
5) Prebid mobile makes ad server call with targeting key value pairs
```
"hb_bidder": "appnexus",
"hb_bidder_appnexus": "appnexus",
"hb_cache_id": "a2a42cb8-246e-4254-b85a-e9afc397b9ba",
"hb_cache_id_appnexus": "a2a42cb8-246e-4254-b85a-e9afc397b9ba",
"hb_env": "mobile-app",
"hb_env_appnexus": "mobile-app",
"hb_pb": "0.00",
"hb_pb_appnexus": "0.00"
```
6) Ad server loads Prebid Universal creative
7) PUC fetches the native details from Prebid cache
8) PUC writes the markup on mobile device


Problem with above is, Prebid server response does not return type of asset in bid response. With this feature we intent to add type of asset in bid response before storing it in cache.

**Comment by bretg** [comment]
Context is clear now - thanks Jaimin.

Now the questions are:

1) You mention that "Prebid mobile native bid request will have a flag to enable preprocess". What flag is that?

2) What's the difference between option 1 and 2 above? I guess I get option 2, but would be concerned about supporting different types of mobile clients - I suppose if the pre-processing flag is on, then we know the client is ready to receive just targeting values? For Option 1, where in the modified bid response would you store type? I don't understand the grey box that starts with "// IAB Native spec 1.2 asset mapping"

**Comment by jaiminpanchal27** [comment]
@anwzhang Can you update on question 1

For question 2, If mobile clients maybe a concern then we can go with option 1. 
To give more details to grey box. As per IAB spec, type is integer field. PUC will get the bid response from bid cache but would not know what type means. 

For example if prebid cache returns,
```
...
"assets": [
    {
      "id": 0,
      "type": 1
      "img": {
        "url": "https://vcdn.adnxs.com/p/creative-image/7e/71/90/27/7e719027-80ef-4664-9b6d-a763da4cea4e.png",
        "w": 300,
        "h": 250,
        "ext": {
          "appnexus": {
            "prevent_crop": 0
          }
        }
      }
    },
...
``` 
PUC would need to know whether type is main_image or icon. Hence the mapping object in Prebid universal creative is needed. Second object is this http://prebid.org/dev-docs/show-native-ads.html#2-add-native-ad-units
Types can be seen [here](https://www.iab.com/wp-content/uploads/2017/04/OpenRTB-Native-Ads-Specification-Draft_1.2_2017-04.pdf) on Page 39

**Comment by anwzhang** [comment]
@bretg As stated, Prebid Mobile will pass in a flag with native request to have prebid server to return assets with types. I haven't look into the details, but this will be done after Prebid Server implementation.

**Comment by bretg** [comment]
1) I'd still like to see what specific flag will be passed. Suggestion: `ext.prebid.options.nativepreprocessing: true`. Defaults to false.

2) I'm not fond of making PUC any bigger. We already get pressure on its size. Please come up with a proposal to either A) minimize the number of bytes needed in the PUC   or   B) split out native into a separate (no-longer-universal) creative.

**Comment by jaiminpanchal27** [comment]
1) We are safely trying to add types in bid response if `request.App` property exists and mediaType is native. If the concern here is that the request is not a mobile device and App property exists then also above will not harm response in any way. 
I have asked @anwzhang to have a look at it and take the call

2) We decided to update native-trk.js and hence not increasing the size of creative.js
