### ISSUE TITLE
Rhythmone adapter fails

### ISSUE THREAD

**Issue by Austinb** [prebid/prebid-server#1062]
Using rhythmone in the prebid.js header bidding works as expected but fails when switching to the prebid server with missing optional params. According to the documentation at https://github.com/prebid/Prebid.js/blob/master/modules/rhythmoneBidAdapter.md only the param `placementId` is required however the prebid server is expecting both `path` and `zone` to also exist (https://github.com/prebid/prebid-server/blame/master/static/bidder-params/rhythmone.json).  Is there a reason these params are required on the server end but not when passing via the prebid.js library?

**Comment by hhhjort** [comment]
@dineshkumarjayaram : can you comment?
