### ISSUE TITLE
Sonobi Adapter fails validation

### ISSUE THREAD

**Issue by Austinb** [prebid/prebid-server#1063]
When running the sonobi bidder code in client header bidding (prebid.js) the bidder works as expected.  However when switching to the prebid server the sonobi adapter fails with the following error:
```
Invalid request: request.imp[0].ext.sonobi failed validation.
TagID: TagID is required
```
In the prebid.js docs at https://github.com/prebid/Prebid.js/blob/master/modules/sonobiBidAdapter.md there is no mention of this setting `TagID` in the bidder params. Is this something we need to get from sonobi?
​

**Comment by hhhjort** [comment]
@JonGoSonobi : Can you comment on this?
