### ISSUE TITLE
Issue with HTTP event-based update using amp_endpoint

### ISSUE THREAD

**Issue by Austinb** [prebid/prebid-server#1065]
The url being created for the amp HTTP request when doing event-based updates is incorrect.  The code at https://github.com/prebid/prebid-server/blob/master/stored_requests/events/http/http.go#L97 just blindly appends the `?last-modified=` query string to the end of the url that is passed.  This works fine for the normal endpoint but creates an invalid url when using the default example for pulling in amp updates found at https://github.com/prebid/prebid-server/blob/master/docs/developers/stored-requests.md#caches-and-event-based-updating. 

The normal updates url used for the event based updating is `https://server/path/?last-modified=2019-10-10T01:36:16Z` which is fine. However the amp update url used ends up being `https://server/path/?amp=true?last-modified=2019-10-10T01:36:17Z` which is an invalid url. 

I am new to GO so I am unsure the best way to check for existing query params in a string and appending properly so I have not attempted to make a PR for this issue.

**Comment by Austinb** [comment]
Yea should probably be fixed though since amp updates using the example do not work.

**Comment by SyntaxNode** [comment]
Agreed. Don't worry about the stale bot.

**Comment by Austinb** [comment]
Added a PR for this one while I was working on another one.  Please advise any changes in the PR.
