### ISSUE TITLE
Port currency fix from PBS-Java

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1067]
There's a currency conversion issue in PBS. We've fixed this in PBS-Java with https://github.com/rubicon-project/prebid-server-java/pull/457

Here are the requirements and some test cases:

1) the client only ever specifies one entry in the `cur` array: the one expected by their adServer
If there are more than one cur specified, use the first and warn.

2) This cur value must be sent to each adapter

3) PBS must try to convert bid responses to the first currency in the array

4) if PBS can't convert a bid, then it should error with "unable to covert bid currency XYZ to desired ad server currency ABC."

Test cases:

1) ad-server-currency is USD. (whether defined in the `cur` field or in the config is the same behavior)
2) bidderA bids are in EUR. they get converted to USD
3) bidderB bids are in GBP. they get converted to USD
4) bidderC bids are in USD. no conversion needed

**Comment by benjaminch** [comment]
Hey @bretg !

Sorry about that but would it be possible to explain what are `the client` and the `core server` here? 

Cheers !

**Comment by bretg** [comment]
- `client`: browser or app
- `core server`: the part of PBS that receives the request, does the DB lookup, and prepares the openrtb for the bidder modules. i.e. everything that's not a bidder module

**Comment by hhhjort** [comment]
@bretg : Do we see a real need to provide the option to be a string rather than an array? In the Go version, it would take significant number of cycles to check for the possible existence of singe string. It also breaks the openrtb 2.5 spec to provide a single string.
