### ISSUE TITLE
Version in ad request

### ISSUE THREAD

**Issue by Niksok** [prebid/prebid-server#1080]
Hello! Can you help me? It is possible to send in ad request current version of installed prebid-server? Which is specified in git tag, for now it is 0.86.0.

**Comment by SyntaxNode** [comment]
It's not currently possible because the compiled binary isn't aware of the version number / git tag.  That is something we can certainly explore. I'm curious, what would you use the version for?

**Comment by Niksok** [comment]
Ok, thank you for answer. Version in ad request would be very helpful to check the moment when publisher switch to another version of lib
