### ISSUE TITLE
Get Renderer Config

### ISSUE THREAD

**Issue by rimalex** [prebid/prebid-server#1083]
Hello together,

I'm looking for the possibility to get the Renderer Config trough Prebid Server (in /openrtb2/auction)

I saw this information in Prebid Client Response, but I can't find it in Prebid Server:
<img width="1090" alt="Bildschirmfoto 2019-10-21 um 21 37 24" src="https://user-images.githubusercontent.com/56094189/67237200-18f5d780-f44b-11e9-8594-00ace2b184ff.png">

Thank you guys!

**Comment by SyntaxNode** [comment]
Hi. Is your request specific to video? If so, please see if https://github.com/prebid/prebid-server/issues/1075 is the same as what you're looking for.
