### ISSUE TITLE
Prebid Server Example Not Returning Ads

### ISSUE THREAD

**Issue by nicholasstark** [prebid/prebid-server#1090]
I'm setting up a Prebid Server sandbox on my machine. I'm using the example code/objects from the PBS project. When I make a call to the auction to get a sample ad, I'm expecting to get back the sample 'hello world' object found at http://prebid.org/prebid-server/endpoints/openrtb2/auction.html but instead I'm a very small data object (listed below) that is missing critical things like the bid and bid.adm. Anyone have any ideas? Thanks.

The Endpoint URL: http://localhost:8000/openrtb2/auction

The Post Data Object:

{ "id": "some-request-id", "site": { "page": "prebid.org" }, "imp": [ { "id": "some-impression-id", "banner": { "format": [ { "w": 300, "h": 250 }, { "w": 300, "h": 600 } ] }, "ext": { "appnexus": { "placementId": 10433394 } } } ], "tmax": 5000 }

The Return Object:

{ "id": "some-request-id", "ext": { "responsetimemillis": { "appnexus": 120 }, "tmaxrequest": 5000 } }
<img width="1116" alt="Screen Shot 2019-10-28 at 9 51 11 AM" src="https://user-images.githubusercontent.com/5413879/67701942-17a63c80-f96e-11e9-9acc-07d0ada6eb7d.png">

Tags: prebid, prebid.js, prebid server

**Comment by SyntaxNode** [comment]
The sample request is hitting the real AppNexus servers. It appears the placement id from the docs has since expired. Please use the following sample request for now. Note the new format sizes and placement id. I'll update the docs soon to match:

```
{
    "id": "some-request-id",
    "site": {
        "page": "prebid.org"
    },
    "imp": [{
        "id": "some-impression-id",
        "banner": {
            "format": [{
                "w": 600,
                "h": 500
            }, {
                "w": 300,
                "h": 600
            }]
        },
        "ext": {
            "appnexus": {
                "placementId": 12883451
            }
        }
    }],
    "tmax": 500
}
```
