### ISSUE TITLE
Facebook AudienceNetwork does not respect multisize, only uses main size

### ISSUE THREAD

**Issue by andyblackwell** [prebid/prebid-server#1093]
When making a mobile web request with the audienceNetwork bidder, if the valid size only exists in the multisize config, the request is ignored.

audienceNetwork I believe only supports 300x250 and 320x50 banners, so if the main size is 336x280 and 300x250 is set in multisize it **should** still bid, but does not.

from the source, it's just taking the first available size, rather than validating the sizes in the list
https://github.com/prebid/prebid-server/blob/0.86.0/adapters/audienceNetwork/facebook.go#L239-L240
and maybe this bit of code that validates that one size? though I'm not seeing this error.
https://github.com/prebid/prebid-server/blob/0.86.0/adapters/audienceNetwork/facebook.go#L155-L159

here's an example debug request with other bidders removed:
```
{
    "targeting": {},
    "debug": {
        "httpcalls": {
            "audienceNetwork": []
        },
        "resolvedrequest": {
            "id": "cb_amp_eb_300x250",
            "imp": [{
                "id": "cb_amp_eb_300x250",
                "banner": {
                    "format": [{
                            "w": 336,
                            "h": 280
                        },
                        {
                            "w": 300,
                            "h": 250
                        },
                        {
                            "w": 320,
                            "h": 50
                        }
                    ]
                },
                "tagid": "/118772816/cb_amp_eb_300x250",
                "secure": 1,
                "ext": {
                    "audienceNetwork": {
                        "placementId": "1995140980753520_2428735337394080"
                    },
                }
            }],
            "site": {
                "domain": "www.cinemablend.com",
                "page": "https://www.cinemablend.com/news/2475160/men-in-black-international-reportedly-had-some-serious-behind-the-scenes-drama",
                "publisher": {
                    "id": "28df1f1e-bfc2-466b-94e1-31e92ffe1a21"
                },
                "ext": {
                    "amp": 1
                }
            },
            "device": {
                "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
                "ip": "209.116.32.50"
            },
            "test": 1,
            "at": 1,
            "tmax": 1000,
            "source": {
                "tid": "b9c97a4b-cbc4-483d-b2c4-58a19ed5cfc5"
            },
            "ext": {
                "prebid": {
                    "cache": {
                        "bids": {},
                        "vastxml": null
                    },
                    "targeting": {
                        "pricegranularity": {
                            "precision": 2,
                            "ranges": [{
                                "min": 0,
                                "max": 20,
                                "increment": 0.1
                            }]
                        },
                        "includewinners": true,
                        "includebidderkeys": true,
                        "includebrandcategory": null,
                        "durationrangesec": null
                    }
                }
            }
        }
    }
}
```

**Comment by bretg** [comment]
I think AppNexus may have originally written this adapter back in the early days of PBS. The contributors list seems to confirm that. @hhhjort ?

**Comment by hhhjort** [comment]
That is probably true. It was from before I joined the team.

**Comment by bretg** [comment]
Ok, looking for someone who can fix this. @lovell perhaps?

**Comment by lovell** [comment]
I'm unable to help with this, sorry.

**Comment by SyntaxNode** [comment]
There's a rather large refactor currently going on in https://github.com/prebid/prebid-server/pull/1064. If this is still an issue after that goes in, I'll work with my team to get eyes on it. We've been a bit busy, sorry.

**Comment by andyblackwell** [comment]
Is it possible to give this a label that prevents auto-closing the issue, like “bug” or something?

**Comment by SyntaxNode** [comment]
Is addressed by https://github.com/prebid/prebid-server/pull/1164

**Comment by SyntaxNode** [comment]
@andyblackwell Does the fix solve your issue? It has been deployed to AppNexus/Xandr servers.

**Comment by andyblackwell** [comment]
it probably solves this issue, yeah. I merely found this bug when trying to figure out why web requests weren't working at all for audience network. Though since they announced the other day that they are completely retiring bidding on web requests, and only supporting app bidding, I won't really be able to test it out myself. Given that, I'll close this one out.
