### ISSUE TITLE
Issue with rubicon and default requests file

### ISSUE THREAD

**Issue by Austinb** [prebid/prebid-server#1096]
We have implemented some default aliases (https://github.com/prebid/prebid-server/blob/master/docs/developers/default-request.md) on our PBS to allow us to easily have the same bidder used multiple times on a prebid request where we are unable to modify the request actually being sent.  It works fine except when we try to add an alias for `rubicon`.  We set the defaults.json file as below and the server starts up fine but when you try to make a stored request call the server responds with `Invalid request: request.ext.prebid.aliases.rubicon1 refers to unknown bidder: rubicon`.  None of the other PBS supported bidders have issues with aliasing them in anyway.  

Is this an issue this an issue with the default request parsing and implementation or an issue specifically with the rubicon adapter? I just pulled the latest code from the master branch and tried it and still the same error as before.

Edit: This unknown rubicon adapter happens regardless if `rubicon` is passed as one of the bidders or not.  Example: if an impression for a mobile app uses just `appnexus `the response still comes back from our PBS as `Invalid request: request.ext.prebid.aliases.rubicon1 refers to unknown bidder: rubicon`

Example defaults.json:
```json
{
  "tmax": 500,
  "ext": {
    "prebid": {
      "aliases": {
        "districtm": "appnexus",
        "rubicon1": "rubicon"
      }
    }
  }
}
```

pbs.yaml snippet:
```yaml
default_request:
    type: "file"
    file:
        name: /path/to/defaults.json
    alias_info: false
```

**Comment by bretg** [comment]
Have you enabled the Rubicon bidder in your server? It's off by default because you need to work with Rubicon Project to get an Exchange API login.

Assuming that you have enabled Rubicon, assigning to @hhhjort for PBS-Go and @rpanchyk to verify PBS-Java.

**Comment by Austinb** [comment]
@bretg we were not.  Will contact them to make sure we have everything setup from their side and reopen this issue if there is still a problem.  Was unaware of the bidder setup docs at https://github.com/prebid/prebid-server/tree/master/docs/bidders.
