### ISSUE TITLE
Prebid Server: change how IP addresses are determined using XFF header

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1106]
It's come to our attention that Prebid Server isn't processing the X-Forwarded-For (XFF) HTTP header quite right.

Currently, it's taking the leftmost entry from the comma-separated list, but sometimes that leftmost entry is a 'private' IP (e.g. NAT) that's not useful for geo-targeting purposes. A better algorithm would be:

1) First, use the True-Client-IP header if it's present
2) Else, parse the comma-separated IP values in XFF and loop through them
    1a) compare the value against the [private network table](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses)
    1b) if the address matches a private network pattern, skip it and go on to the next one
3) in this way, set device.ip to the leftmost IP address that's not a private address.

**Comment by dimention** [comment]
We have this problem, the determined IP is private, and it is sent to SSPs, that don't bid on it.

**Comment by rpanchyk** [comment]
Implemented for PBS-Java in PR https://github.com/rubicon-project/prebid-server-java/pull/515

**Comment by bretg** [comment]
Reviewed in PBS committee today and added reference to `True-Client-IP`

**Comment by SyntaxNode** [comment]
This was recently implemented in PBS-Go along with IPv6 support.
