### ISSUE TITLE
Prebid Server No-Bid Response return code

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1116]
Prebid Server currently sets OpenRTB response.nbr=2 (invalid) when there are no bids. This causes unnecessary concern in publishers who are trying to troubleshoot bid density, leading them to think there may be an error.

Since Prebid Server may have several underlying bidders, each with different reasons for not bidding. So we propose changing this scenario so that PBS sets nbr=0 (unknown) at the top level.

When a someone wants to troubleshoot why they're not getting bids from a particular bid adapter, they should just turn on debugging (debug: 1).

**Comment by SyntaxNode** [comment]
Sounds good to me. I see nbr=2 mentioned as an example in the OpenRTB spec, so perhaps that where it originally came from. Do you think this would break anyone today possibly relying on that nbr=2 behavior?

**Comment by bretg** [comment]
My take: I don't think changing nbr=2 to the more appropriate 0 should be considered a breaking change. It's still a 'no bid response', just a more accurate description of why there was no bid.

**Comment by SyntaxNode** [comment]
In PBS-Go, the nbr response is set to 2 (invalid) when there are no valid impressions in the request. Otherwise, nbr is always set to 0. 

@bretg @hhhjort Thoughts? Is this a proper case to send back an nbr of 2, or should PBS just always return an nbr of 0?

**Comment by bretg** [comment]
The feedback I got is that nbr=2 confuses people because it makes them think their request was malformed.

**Comment by SyntaxNode** [comment]
Gotcha. I think we'll leave the logic as is in PBS-Go since we only set NBR=2 when the request is indeed malformed (no valid bidders). I haven't heard of any published complaints on this behavior, but will revisit if something comes up in the future.
