### ISSUE TITLE
Unsupported bidder

### ISSUE THREAD

**Issue by alejandrofcarrera** [prebid/prebid-server#1117]
After struggling with [various problems](https://github.com/prebid/prebid-server/issues/1112) in connecting PBJS and PBS. I'm getting several bugs when I run the endpoint `/auction?pbjs_debug=true`. Some of the bidders are not being recognized even when I am sending the parameters correctly and I have checked that each identifier is adequate as well as the required parameters. I have done it on the endpoint `/bidders/params`. Also `sovrn` is not including if a bid was returned or not...

Bidders in the request and status:

* openx: Failing
* appnexus: No bid
* pubmatic: No bid
* sovrn: No response ?
* 33across: Failing
* triplelift: Failing
* yieldmo: Failing
* sharethrough: Failing
* emx_digital: Failing

Request:

```curl 'https://.../auction?pbjs_debug=true' -H 'authority: ...' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'origin: https://...' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36' -H 'content-type: text/plain' -H 'accept: */*' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'referer: https://.../prebid/fill_server.html' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: es-419,es;q=0.9,en;q=0.8,it;q=0.7,ig;q=0.6,pt;q=0.5' --data-binary '{"account_id":"1","tid":"507511e8-3295-4ac3-942a-cbef5a67c45c","max_bids":0,"timeout_millis":60000,"cache_markup":0,"url":"https://.../prebid/fill_server.html","prebid_version":"2.40.0","ad_units":[{"code":"/6938/IM_EN_site/IM_EN_Leaderboard_Default","mediaTypes":{"banner":{"sizes":[[728,90]]}},"bids":[{"bidder":"openx","params":{"unit":"540655194","delDomain":"XXX-com-d.openx.net"},"bid_id":"1887858f1620ab"},{"bidder":"appnexus","params":{"placementId":15333996},"bid_id":"27e9d46352dac5"},{"bidder":"pubmatic","params":{"publisherId":"158008","adSlot":"IM_EN_Leaderboard_1_Default@728x90"},"bid_id":"3d2ecf4481323c"},{"bidder":"sovrn","params":{"tagid":"603555"},"bid_id":"41b39616e910a3"},{"bidder":"33across","params":{"siteId":"d9lxhUxfar6ykpaKkGJozW","productId":"siab"},"bid_id":"513a3fbb4ec14f"},{"bidder":"triplelift","params":{"inventoryCode":"XXX_com_RON_HDX"},"bid_id":"631b30a725329c"},{"bidder":"yieldmo","params":{"placementId":"2289904657554376222"},"bid_id":"7ffff6fbbdf1ef"},{"bidder":"sharethrough","params":{"pkey":"y2G3PFWKWY2Xp1xjkNMw1PSF"},"bid_id":"89fe280a35d04e"},{"bidder":"emx_digital","params":{"tagid":"80084"},"bid_id":"9456f4e4ae522f"}],"sizes":[{"w":728,"h":90}],"transactionId":"5440d87b-a4c5-46bb-a0c1-652f02e344d7"}],"is_debug":true,"site":{"publisher":{"id":"1"},"page":"https://.../prebid/fill_server.html"},"device":{"w":2560,"h":920}}' --compressed```

Response:

```{"tid":"507511e8-3295-4ac3-942a-cbef5a67c45c","status":"no_cookie","bidder_status":[{"bidder":"openx","error":"Unsupported bidder"},{"bidder":"appnexus","response_time_ms":16,"no_cookie":true,"no_bid":true,"usersync":{"url":"https://ib.adnxs.com/getuid?https://.../setuid?bidder=adnxs&gdpr=&gdpr_consent=&uid=$UID","type":"redirect"},"debug":[{"request_uri":"http://ib.adnxs.com/openrtb2","request_body":"{"id":"507511e8-3295-4ac3-942a-cbef5a67c45c","imp":[{"id":"/6938/IM_EN_site/IM_EN_Leaderboard_Default","banner":{"format":[{"w":728,"h":90}],"w":728,"h":90},"secure":1,"ext":{"appnexus":{"placement_id":15333996}}}],"site":{"domain":"...","page":"https://.../prebid/fill_server.html"},"device":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","ip":"82.158.243.121","h":920,"w":2560},"user":{},"at":1,"tmax":60000,"source":{"fd":1,"tid":"507511e8-3295-4ac3-942a-cbef5a67c45c"}}","status_code":204}]},{"bidder":"pubmatic","response_time_ms":30,"no_cookie":true,"no_bid":true,"usersync":{"url":"https://ads.pubmatic.com/AdServer/js/user_sync.html?predirect=https://.../setuid?bidder=pubmatic&gdpr=&gdpr_consent=&uid=","type":"iframe"},"debug":[{"request_uri":"http://hbopenbid.pubmatic.com/translator?source=prebid-server","request_body":"{"id":"507511e8-3295-4ac3-942a-cbef5a67c45c","imp":[{"id":"/6938/IM_EN_site/IM_EN_Leaderboard_Default","banner":{"format":[{"w":728,"h":90}],"w":728,"h":90},"tagid":"IM_EN_Leaderboard_1_Default","secure":1}],"site":{"domain":"...","page":"https://.../prebid/fill_server.html","publisher":{"id":"158008","domain":"..."}},"device":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","ip":"82.158.243.121","h":920,"w":2560},"user":{},"at":1,"tmax":60000,"source":{"fd":1,"tid":"507511e8-3295-4ac3-942a-cbef5a67c45c"}}","status_code":204}]},{"bidder":"sovrn","response_time_ms":23,"no_cookie":true,"usersync":{"url":"https://ap.lijit.com/pixel?redir=https://.../setuid?bidder=sovrn&gdpr=&gdpr_consent=&uid=$UID","type":"redirect"},"debug":[{"request_uri":"http://ap.lijit.com/rtb/bid?src=prebid_server","request_body":"{"id":"507511e8-3295-4ac3-942a-cbef5a67c45c","imp":[{"id":"/6938/IM_EN_site/IM_EN_Leaderboard_Default","banner":{"format":[{"w":728,"h":90}],"w":728,"h":90},"tagid":"603555","secure":1}],"site":{"domain":"...","page":"https://.../prebid/fill_server.html"},"user":{}}","response_body":"{"id":"507511e8-3295-4ac3-942a-cbef5a67c45c"}","status_code":200}]},{"bidder":"33across","error":"Unsupported bidder"},{"bidder":"triplelift","error":"Unsupported bidder"},{"bidder":"yieldmo","error":"Unsupported bidder"},{"bidder":"sharethrough","error":"Unsupported bidder"},{"bidder":"emx_digital","error":"Unsupported bidder"}]}```

Thanks in advance

**Comment by alejandrofcarrera** [comment]
Just to be sure, i tested with the latest version of PBJS for non-production (it includes all the bidders and modules by default) and a custom version with the specific bidders with same results. [Here](https://remnant.s3.eu-west-3.amazonaws.com/prebid/fill_server.html) (to provide a way to test easily) the test website is deployed. Adx is always winning but this message `WARNING: Prebid Server returned error: 'Unsupported bidder'` is 90% times showed.

**Comment by SyntaxNode** [comment]
We'll take a look soon, sorry the delay. We've been a bit a busy.

**Comment by alejandrofcarrera** [comment]
> We'll take a look soon, sorry the delay. We've been a bit a busy.

Anything new ? We are a little bit stuck because this huge issue.

**Comment by SyntaxNode** [comment]
This looks like you're submitting an auction to the legacy endpoint. You want to use the OpenRTB 2.5 endpoint at `/openrtb2/auction`. The legacy auction endpoint uses a deprecated Prebid custom model and is only still in the codebase until a few other folks migrate off. Look for that to be removed sometime in 2020 (crosses fingers).

**Comment by alejandrofcarrera** [comment]
Dear @SyntaxNode, i changed the endpoint and it is working perfectly. Now i noticed an issue about PBJS with 33accross through PBS but i am gonna put this issue on their side.

Thanks for the tip. We were stuck a lot and we didn't know it what was happening. 🤦‍♂
