### ISSUE TITLE
Payloads exceeding max size for Prebid's Cache

### ISSUE THREAD

**Issue by ah-tappx** [prebid/prebid-server#1149]
Hello,
We have noticed that when we return ads which include base64-encoded images Prebid Cache throws an error like the following:

`{"errors":{"prebid":[{"code":999,"message":"Prebid Cache call to http:\/\/prebid-cache-v1\/cache returned 400: POST \/cache element 0 exceeded max size: Payload size 53383 exceeded max 40960\n"}`

We have seen that this maximum payload size doesn't seem to be fix since we have received similar messaged with different max values:

`"Prebid Cache call to http://prebid-cache-sqajdharzc.eu-central-1.elasticbeanstalk.com/cache returned 400: POST /cache element 0 exceeded max size: Payload size 176195 exceeded max 10240\n"`

We would like to know the dimension of this issue, when can we expect to see this behaviour, if there are any plans on fixing this and how should we handle this for the moment.

Thank you

**Comment by SyntaxNode** [comment]
To be clear, these are calls directly to Prebid Cache or is it going through Prebid Server?

**Comment by ah-tappx** [comment]
Those are responses that some of our publishers are receiving when they send requests through PrebidJS or Prebid Mobile to our Prebid Server adapter. I assume this error happens when Prebid tries to cache our response, and the error is thrown back to the client.

**Comment by SyntaxNode** [comment]
Gotcha. Makes sense. The max payload size is configurable by the server host. The max for appnexus/xandr is 40960 and appears to be 10240 for elasticbeanstalk.

Is it common to include base-64 encoded image creatives?

**Comment by ah-tappx** [comment]
Many of our partners have campaigns that include base64 encoded creativities. I don't know how extended is this practice but surely it will happen in the future.

**Comment by SyntaxNode** [comment]
What do you propose the new limit be?

**Comment by ah-tappx** [comment]
I am just a user of this service so I don't think that I should propose any limit or configuration values, mainly because I don't know anything of your server's specs. The only thing I can say at this point is that I'm seeing payloads as big as 70500 bytes. Do you think you can tune your server in order to work with this?

**Comment by SyntaxNode** [comment]
Sure. I was looking for guidance in how large of payloads you've been seeing. Thank you for that. We'll chat about the issue and update here later this week.
