### ISSUE TITLE
Cookie propagation from prebid.js to DSP on every call

### ISSUE THREAD

**Issue by johndpknt** [prebid/prebid-server#1163]
Hello Team,

I was building a functionality where my cookie has to travel every time from client to DSP through prebid-server.

I don't see a way to achieve this. can anyone suggest me if this is possible ??

thanks in advance

**Comment by bretg** [comment]
@johndpknt - each adapter is already allowed to have a user ID cookie:

- each adapter supplies a usersync URL
- PBJS calls /cookie_sync which drops usersync pixels
- so within a few pages, the browser gets an ID for each supported adapter placed within the host company's 'uids' cookie, which is a match table
- once a usersync has succeeded for each adapter, that ID is passed through to it on user.buyeruid

**Comment by johndpknt** [comment]
@bretg Thank you very much for the response. 

Understood the steps mentioned by you. But I want to propagate the cookies on every call to the bidder. as the bidder set some cookies specific to every call and impression. and doesn't have the capability to maintain a mapping at their end for uids to details lookup.

Those parameters essentially help them for targeting and retargeting web users. 

Is there a facility or way I can pass the cookie from client to bidder, knowing the fact that bidder and prebid-server might be on different domains??

thanks in advance

**Comment by SyntaxNode** [comment]
I don't think so.

Are they using Prebid.js? Perhaps there could be a way to take their cookie value and place it into the OpenRTB bid request within the browser.

**Comment by bretg** [comment]
> Is there a facility or way I can pass the cookie from client to bidder, knowing the fact that bidder and prebid-server might be on different domains??

Well, if you have control over the page, you can set bidder-specific parameters in the Prebis.js s2sConfig:

```
pbjs.setConfig({
  s2sConfig: {
     ...
     extPrebid: {
         MYBIDDER: {
             foo: VALUE_READ_FROM_FIRST_PARTY_COOKIE
         }
     }
  }
});
```
Then I believe this will be available to your server-side adapter that can be read and passed through to your endpoint.

Does that help?
