### ISSUE TITLE
Prebid Server Long Form Video Deal Support Changes 

### ISSUE THREAD

**Issue by camrice** [prebid/prebid-server#1174]
Below is a work in progress write up of the intended changes.

# Deal Support

## Overview

Bids that contain deals may need to be updated with a bidder defined prefix and priority level. This will be reflected in the `hb_pb_cat_dur` value in the resulting `adPod`. The field `hb_pb_cat_dur`is usually formed with `{price bucket}_{industry code}_{duration}`. With this feature, `hb_pb_cat_dur` will instead be formed by `{bidder prefix}{deal priority}_{industry code}_{duration}` if all conditions are met.

Example:

Original:

```
"adPods": [
    {
        "podid": 1,
        "targeting": [
            {
                "hb_pb": "15.00",
                "hb_pb_cat_dur": "15.00_food_30s",
                "hb_cache_id": "420d7329-30e8-4c4e-8eaa-fe937172e4e0"
            }
        ],
        "errors": null
    }
],
```

Modified:

```
"adPods": [
    {
        "podid": 1,
        "targeting": [
            {
                "hb_pb": "15.00",
                "hb_pb_cat_dur": "tier7_food_30s",
                "hb_cache_id": "420d7329-30e8-4c4e-8eaa-fe937172e4e0"
            }
        ],
        "errors": null
    }
],
```

In order for the modification to occur, there are a few pieces that need to be setup. The configuration must contain a `dealTier` object that holds the `prefix` and `minDealTier` values. The request to Prebid Server must also enable this feature through the `SupportDeals` field. Note that in order for ImpBus to return the deal priority for resulting bids, deals must be configured for the target campaign outside of Prebid Server.

## Prebid Configuration

The prefix and minimum deal tier must be defined in the Prebid configuration in order for the key to be updated. These are set per bidder in a `dealTier` object.

| Field                | Type      | Description                                                                                                     |
| -------------------- | --------- | --------------------------------------------------------------------------------------------------------------- |
| dealTier             | 'Object'  | Contains prefix and minimum deal tier values                                                                    |
| dealTier.prefix      | 'String'  | The prefix string that is added to `hb_pb_cat_dur`. Must be non-empty.                                          |
| dealTier.minDealTier | 'Integer' | The minimum deal priority value (inclusive) that must be met for modification to occur. Must be greater than 0. |

Example:

```
[
    {
        "params": {
            "dealTier": {
                "prefix": "tier",
                "minDealTier": 5
            },
            "placementId": 12345678
        },
        "bidder": "bidder_name"
    }
]
```

## Video Request

The request for the video endpoint contains a new boolean field: `SupportDeals`. If omitted, the default value for `SupportDeals` is `false`. The field exists in the top level of the request.

Example:

```
{
    ...
    "supportdeals": true,
    ...
}
```

## Example Modification of `hb_pb_cat_dur`

For this example, assume there is a Prebid configuration as follows:

```
[
    {
        "params": {
            "dealTier": {
                "prefix": "firstprefix",
                "minDealTier": 5
            },
            "placementId": 12345678
        },
        "bidder": "bidder1"
    },
    {
        "params": {
            "dealTier": {
                "prefix": "secondprefix",
                "minDealTier": 8
            },
            "placementId": 12345678
        },
        "bidder": "bidder2"
    }, 
]
```

Also assume the following result for the auction:

| Impression | Winner  | Original `hb_pb_cat_dur` | Bid Deal Priority |
| ---------- | ------- | ------------------------ | ----------------- |
| 1          | bidder1 | 10.00_movies_30s         | 6                 |
| 2          | bidder2 | 10.00_medicine_30s       | 7                 |

Due to the deal priorities received, only the `hb_pb_cat_dur` for `"bidder1"` will be updated, as shown in this example response:

```
"adPods": [
    {
        "podid": 1,
        "targeting": [
            {
                "hb_pb": "10.00",
                "hb_pb_cat_dur": "firstprefix6_movies_30s",
                "hb_cache_id": "420d7329-30e8-4c4e-8eaa-fe937172e4e0"
            },
            {
                "hb_pb": "10.00",
                "hb_pb_cat_dur": "10.00_medicine_30s",
                "hb_cache_id": "420d7329-30e8-4c4e-8eaa-fe937172e4e0"
            }
        ],
        "errors": null
    }
],
```

**Comment by bretg** [comment]
Don't see that this has been ported yet to PBS-Java. Opened a low-pri ticket internally.

**Comment by bretg** [comment]
Cancelling due to pending video endpoint deprecation
