### ISSUE TITLE
GDPR TCF 2.0 support in prebid-server

### ISSUE THREAD

**Issue by PubMatic-OpenWrap** [prebid/prebid-server#1177]
## Type of issue
Query

## Description
When prebid-server will start supporting TCF 2.0? What is the plan?

**Comment by bretg** [comment]
We're just wrapping our heads around it now. You can expect an intent-to-implement by mid-February. Don't plan on code release until March.

We welcome community contributions to product definition as well as code.

The first strategic decision we need to make is whether we're going to try to tweak the current approach (https://github.com/rubicon-project/prebid-server-java/blob/master/docs/developers/PrebidServerJava_GDPR_Requirements.pdf), or whether we're going to redesign.

What we do know is that the platform will allow the host company to configure behavior like it currently does: defining bidders and accounts that are exempt from the rules. But we haven't figured out the absurdly complicated "legitimate interest" rules in TCF2 and how that should impact the server.

**Comment by bretg** [comment]
Here's a link to the draft doc -- https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#

**Comment by bretg** [comment]
@SyntaxNode and @hhhjort - please note that the 'vendorExceptions' behavior has been changed (simplified) based on community feedback (and from @jaiminpanchal27 )

See the Prebid.js use cases at https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.hvcv9vpkupch -- the scenarios and interpretations will be the same for Prebid Server config.

**Comment by bretg** [comment]
TCF2 support for Purpose 1 has been available since the end of March. Remaining functionality still under development, with the plan to deliver in the next few weeks. See the doc referred above for more information.
