### ISSUE TITLE
Sample ad not working

### ISSUE THREAD

**Issue by matthieularere** [prebid/prebid-server#1180]
Hi,

I've tried to run the sample request but I don't have any response in it while if I call the appnexus placementId in prebid.js I do have a creative returned. So I made a test implementation page which call prebid-server using prebid client : 
[link to my test implementation](https://debug.mediasquare.fr/debug/s2s/test.html?pbjs_debug=true)

as you can see, appnexus placement id 12883451 is called by both prebid-server and prebid-client. Checking the prebid-server response I can see in debug that appnexus 
`"responsebody":""  `
I guess it means that appnexus did not reply anything ?
And from this part : 
`"responsetimemillis":{"appnexus":32}`
I understand that while rubicon was supposed to be called by prebid-server, it did not.

Do you have any idea why appnexus does not reply with a creative in prebid-server and why rubicon does not seem to be called at all ?

Thanks,
Matthieu

**Comment by SyntaxNode** [comment]
I visited the sample page you linked and am able to see a creative returned by AppNexus. I am located in the US. I'm guessing you're from Europe since the example page is a `fr` domain. If that's the case, please verify that your GDPR consent is passing through correctly.
