### ISSUE TITLE
VideoBidRequest user.Ext does  not copy consent to OpenRtb.user.ext

### ISSUE THREAD

**Issue by neririchter** [prebid/prebid-server#1185]
It seems that We don't pass GDPR consent from the videoBidRequest to openRtb request

 In file uilts.go inside  function "cleanOpenRTBRequests" it tries to extract the GDPR consent from function "extractConsent" inside file gdpr.go while it tried to pull the consent from the user.ext of the open rtb request

but when you look at function mergeData at the video_auction class we do not construct a user.ext in the openrtb bid request.

**Comment by SyntaxNode** [comment]
@camrice @jmaynardxandr Can you please take a look?

**Comment by camrice** [comment]
There will be a PR for this today. This will update it so that in the video request, if `User.GDPR.ConsentRequired` is set to `true`, then the value of `User.GDPR.ConsentString` is copied to the OpenRTB Bid Request under `User.Ext.Consent`.

**Comment by camrice** [comment]
PR for this issue: https://github.com/prebid/prebid-server/pull/1189

**Comment by SyntaxNode** [comment]
PR is under review. Removed stale label.

**Comment by SyntaxNode** [comment]
PR is still under review. We waited to update the docs and verifying the fix will not break current usages.

**Comment by SyntaxNode** [comment]
The PR has been merged and released on the AppNexus servers. Does that resolve the issue for you, @neririchter?

**Comment by neririchter** [comment]
Yes, thanks!
