### ISSUE TITLE
33across bids error out with an schain

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-server#1196]
Requests that include an schain always result in a server side error from 33across. 

eg 

Request payload {"id":"b453ab5d-c2f0-4b9d-9054-711979739136","source":{"tid":"b453ab5d-c2f0-4b9d-9054-711979739136","ext":{"schain":{"ver":"1.0","complete":1,"nodes":[{"asi":"cafemedia.com","sid":"57ace524496a1786252b7233","hp":1}]}}},"tmax":2000,"imp":[{"id":"AdThrive_Sidebar_9_desktop","ext":{"brightroll":{"publisher":"adthrive"},"grid":{"uid":380},"33across":{"siteId":"cggK7W_Lur6ikfaKlId8sQ","productId":"siab"}},"banner":{"format":[{"w":300,"h":250},{"w":300,"h":600},{"w":320,"h":50},{"w":160,"h":600},{"w":336,"h":280},{"w":300,"h":50},{"w":320,"h":100},{"w":250,"h":250},{"w":120,"h":240},{"w":1,"h":1},{"w":300,"h":420}]}}],"test":0,"ext":{"prebid":{"targeting":{"includewinners":true,"includebidderkeys":false}}},"site":{"publisher":{"id":"72409f4d-9858-41ac-bf45-be255b82de89"},"page":"https://firstquarterfinance.com/?threshold=gold4"},"device":{"w":1920,"h":959},"user":{"ext":{"eids":[{"source":"adserver.org","uids":[{"id":"redacted","ext":{"rtiPartner":"TDID"}}]}]}},"regs":{"ext":{"us_privacy":"1---"}}}

returns

{"id":"b453ab5d-c2f0-4b9d-9054-711979739136","seatbid":[{"bid":[{"id":"bc30e38e-baab-4d64-82f6-4dc09d3be4ab","impid":"AdThrive_Sidebar_9_desktop"," ... ","ext":{"errors":{"33across":[{"code":4,"message":"Server responded with failure status: 400. Set request.test = 1 for debugging info."}]},"responsetimemillis":{"33across":23,"brightroll":15,"grid":359},"tmaxrequest":2000}}

**Comment by SyntaxNode** [comment]
@bretg Do you have contacts at 33 Across to contact about this?

**Comment by thomas-33across** [comment]
@patmmccann 
The issue is because in the request payload, ext.schain.ver that cause the issue, 33Across internally will mark the version, please remove the ext.schan.ver from your payload.

Thank you

```json
{
  "id": "b453ab5d-c2f0-4b9d-9054-711979739136",
  "source": {
    "tid": "b453ab5d-c2f0-4b9d-9054-711979739136",
    "ext": {
      "schain": {
        "ver": "1.0",
        "complete": 1,
        "nodes": [
          {
            "asi": "cafemedia.com",
            "sid": "57ace524496a1786252b7233",
            "hp": 1
          }
        ]
      }
    }
  },
  "tmax": 2000,
  "imp": [
    {
      "id": "AdThrive_Sidebar_9_desktop",
      "ext": {
        "brightroll": {
          "publisher": "adthrive"
        },
        "grid": {
          "uid": 380
        },
        "33across": {
          "siteId": "cggK7W_Lur6ikfaKlId8sQ",
          "productId": "siab"
        }
      },
      "banner": {
        "format": [
          {
            "w": 300,
            "h": 250
          },
          {
            "w": 300,
            "h": 600
          },
          {
            "w": 320,
            "h": 50
          },
          {
            "w": 160,
            "h": 600
          },
          {
            "w": 336,
            "h": 280
          },
          {
            "w": 300,
            "h": 50
          },
          {
            "w": 320,
            "h": 100
          },
          {
            "w": 250,
            "h": 250
          },
          {
            "w": 120,
            "h": 240
          },
          {
            "w": 1,
            "h": 1
          },
          {
            "w": 300,
            "h": 420
          }
        ]
      }
    }
  ],
  "test": 0,
  "ext": {
    "prebid": {
      "targeting": {
        "includewinners": true,
        "includebidderkeys": false
      }
    }
  },
  "site": {
    "publisher": {
      "id": "72409f4d-9858-41ac-bf45-be255b82de89"
    },
    "page": "https://firstquarterfinance.com/?threshold=gold4"
  },
  "device": {
    "w": 1920,
    "h": 959
  },
  "user": {
    "ext": {
      "eids": [
        {
          "source": "adserver.org",
          "uids": [
            {
              "id": "redacted",
              "ext": {
                "rtiPartner": "TDID"
              }
            }
          ]
        }
      ]
    }
  },
  "regs": {
    "ext": {
      "us_privacy": "1---"
    }
  }
}
```

**Comment by patmmccann** [comment]
Ver is required, we have to put it there

https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md

**Comment by patmmccann** [comment]
@thomas-33across what do you suggest? we cannot remove a required field from our PBS call because PBS does not support passing different schains to different bidders at this time.

**Comment by bretg** [comment]
FYI - bidder-specific schains is supported in PBS-Java. Adding @SyntaxNode for prioritization within PBS-Go.

**Comment by thomas-33across** [comment]
@patmmccann we had a ticket to work on allowing the `ver` to be send in the request.  I can let you know once we release the change.  Thank you

**Comment by thomas-33across** [comment]
@patmmccann this issue had been resolve in our end, you should be able to send us request with `ver` in the schain object

**Comment by patmmccann** [comment]
Thanks for your quick action!
