### ISSUE TITLE
Appnexus UserSync failure

### ISSUE THREAD

**Issue by mrdck** [prebid/prebid-server#1197]
Hi,

I've tried to setup and run prebid-server to perform sample auction and cookie sync. Whenever I try to perform User sync on Appnexsus bidder I get this message ```The bidder name provided is not supported by Prebid Server```. I've tried to debug it to see why this message is appearing. It seems like `adnxs` is not supported in PBS. 

`setuid?bidder=adnxs&gdpr=1&gdpr_consent=123&uid=0`

This are my params for setuid, I've tried with real gdpr_consent string as well as with fake one.

I will appreciate any guidance about setting up appnexsus and solving issue with user syncing.

**Comment by moteus** [comment]
I think bidder name have to be `appnexus`

**Comment by mrdck** [comment]
> I think bidder name have to be `appnexus`, also, not sure that pbs accept request with malformed consent string

Does it mean that I have to override some configs for appnexsus? This url is what I received after calling cookie_sync endpoint and executing user syncs in browser. I did not change anything in config. I've tried with real consent string and I still receive the exactly same message.

**Comment by moteus** [comment]
Sorry, my foult. Its really adnx. I just deal with requests and there appnexus name

**Comment by mrdck** [comment]
> Sorry, my foult. Its really adnx. I just deal with requests and there appnexus name

I changed `bidder=adnxs` into `bidder=appnexsus` and it seems like it is passing. But I achived it by chaning this param in request in my browser not in PBS. Does it mean that I need to do something with PBS to make it work?

**Comment by rewddd** [comment]
Today I tried to setup prebid-server to test appnexsus locally before integrating with it. Unfortunately I also run into similar issue as described above. It looks like something is misconfigured. Can anyone guide me how to setup appnexsus integration properly on local machine? Is there something that has to be done before running prebid server? I've tried to run prebid-server without any changes in config. Auction is passing correctly for appnexsus (only with test set on 1) and cookie sync is failing due appnexsus does not exists in prebid server (alias does not exists).

**Comment by mrdck** [comment]
> curl 'http://localhost:8000/setuid?bidder=adnxs&gdpr=1&gdpr_consent=BONV8oqONXwgmADACHENAO7pqzAAppY&uid=0' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'Sec-Fetch-User: ?1' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-Mode: navigate' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7' --compressed

**Comment by mrdck** [comment]
This is CURL request that I'm sending to my prebid-server, it is what I receive from /cookie_sync request. `curl --request GET \
  --url 'http://localhost:8000/setuid?bidder=adnxs&gdpr=1&gdpr_consent=BONV8oqONXwgmADACHENAO7pqzAAppY&uid=0' \
  --header 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  --header 'accept-encoding: gzip, deflate, br' \
  --header 'accept-language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7' \
  --header 'cache-control: no-cache' \
  --header 'connection: keep-alive' \
  --header 'pragma: no-cache' \
  --header 'sec-fetch-mode: navigate' \
  --header 'sec-fetch-site: none' \
  --header 'sec-fetch-user: ?1' \
  --header 'upgrade-insecure-requests: 1' \
  --header 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'`

**Comment by SyntaxNode** [comment]
I could not reproduce the `The bidder name provided is not supported by Prebid Server` error against a locally running instance using the default config or against the production AppNexus servers. The specific error comes from setuid.go line 112 which looks like it can only be missing if the AppNexus user sync url is overridden with an empty string.

You might receive an error `The gdpr_consent string prevents cookies from being saved` with the gdpr consent string your using. You're using one copied from our unit tests, and while it is valid it doesn't give consent to the AppNexus bidder. If you get that error, you can use this consent string which gives consent to AppNexus (and for simplicity... and GDPR vendors up to and including 35): `BOwEHdIOwEHdIADACHENAO7pqzACN_____8`.

**Comment by mrdck** [comment]
I was able to went through User Sync process for appnexus, without any errors thanks for your help!
