### ISSUE TITLE
Prebid Server Event Updates

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1202]
Followup to #800 

We've found that passing a full URL through the hb_winurl targeting variable is sometimes truncated by the ad server. When that happens, event tracking doesn't work.

As a result, we're changing the design to store win urls in PBC so passing them through the ad server isn't necessary.

1) Store the win event url in PBC block as 'wurl'

If events are supported by the account, when posting to PBC, PBS should add the 'wurl' attribute as the WIN_EVENT_URL (same value as imp[].ext.prebid.events.win)

```
{
    "adm": "BODY",
    "width": 300,
    "height": 250,
    "wurl": WIN_EVENT_URL
}
```

2) Support Timestamp and BidderCode in event URLs

- Look for ext.prebid.auctiontimestamp on the OpenRTB request, and if present, validate that it's a long integer, then add it to the event URLs as the 'ts' parameter. If not present, generate a long int timestamp for use in the event URL.
- Pass the auctiontimestamp back in the openrtb response ext.prebid.auctiontimestamp
- Update win and imp event URLs to include the timestamp (ts) and biddercode (bidder) parameters

A full description of how Prebid supports event tracking is at https://docs.google.com/document/d/1ry0X4C2EV-R0pMrm1IQk9BstxaT395UCl3KKqTGa5c8/edit#

**Comment by rpanchyk** [comment]
Implemented in PBS-Java in https://github.com/rubicon-project/prebid-server-java/pull/631
