### ISSUE TITLE
Force https over creative delivery

### ISSUE THREAD

**Issue by gchicoye** [prebid/prebid-server#1205]
Hi everybody,

I'm running a test page with Prebid Server.
[Test Page](https://test.cleoma.fr/pbserver/testv1.html)

The issue I'm facing is that the ad delivered by Appnexus is in http and not https. As consequence, I can't display it. I don't have this issues on a classic client side integration.

How can I fix that?

Thanks!

**Comment by SyntaxNode** [comment]
Hold tight. I'll check it out.

**Comment by SyntaxNode** [comment]
Hold tight. I'll check it out.

**Comment by hhhjort** [comment]
Looking at your example, it appears you aren't setting the `secure` flag in the imp? That is probably the issue.

**Comment by gchicoye** [comment]
> Looking at your example, it appears you aren't setting the `secure` flag in the imp? That is probably the issue.

How can I do that with such implementation? 
I might have missed something into the documentation... Sorry about that, but I'm losing my hair about this ;)

**Comment by SyntaxNode** [comment]
Through PrebidJS you should add the following to your config:
```
pbjs.setConfig({
  s2sConfig: {
    secure: 1
  }
});
```

Don't worry. You didn't miss anything in the documentation. We realize now this flag was never added to the docs. @jaiminpanchal27 is working on a PR to fix that.

Sorry for the hair loss. :)

**Comment by gchicoye** [comment]
Thanks a lot for your precious help, everything is working fine now :):)
