### ISSUE TITLE
Bid Response Extension question

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#1206]
Noticed that Bid response from Prebid (https://prebid.adnxs.com/pbs/v1/openrtb2/auction) contains the following ext fields. Whats this fields used for ? Do you have any documentation on this?
bidResponse.seatbid.bid.ext.prebid.type
bidResponse.ext.responsetimemillis.brightroll

Sample:
                    "ext": {
                        "prebid": {
                            "type": "banner"
                        }
                    }
                }
            ],
          }
    ],
    "ext": {
        "responsetimemillis": {
            "brightroll": 83
        },
        "tmaxrequest": 2000
    }

**Comment by smithaammassamveettil** [comment]
@bretg  Is there any documentation on Prebid doc explaining about the above fields?I couldnt find any.

**Comment by smithaammassamveettil** [comment]
@hhhjort Can someone please provide the above requested info

**Comment by moteus** [comment]
I think `tmaxrequest` is a `tmax` from the request and `responsetimemillis.brightroll` is how long the `brightroll`  respose to the request.
But this is my thoughts so please correct me if I am wrong

**Comment by smithaammassamveettil** [comment]
Is there any documentation available? One of our clients is looking for documentation

**Comment by hhhjort** [comment]
I don't recall if it exists in our `docs/ ` tree off the top of my head. But the quick answer is `responsetimemills` is the number of milliseconds it took to process the request for a bidder, which can give you some insight on how well the bidder is doing and if you can reduce the timeout value without losing demand from a bidder. The `tmaxrequest` is the timeout in milliseconds on the request, and thus how long PBS was willing to wait for a bidder to respond.

So in your example above, it took brightroll only 83 milliseconds to respond, but the request allowed for 2000 milliseconds (2 seconds)

**Comment by smithaammassamveettil** [comment]
Is these two extensions always present for all bid responses through Prebid Server?

**Comment by hhhjort** [comment]
I believe so, yes.

**Comment by SyntaxNode** [comment]
There is mention of the the bid response ext object in the docs. Please check out http://prebid.org/prebid-server/endpoints/openrtb2/auction.html and navigate to the "Bidder Response Times, "Bidder Errors", and "Debugging" sections.

@MartianTribe: Seems that we have a chance is make this more visible and perhaps better communicate what all possible values in the ext object are.

FYI: The source code for the ext response is at https://github.com/prebid/prebid-server/blob/6a26430d7e6516cd5e3c80bfa89f8738a8211dd8/exchange/exchange.go#L54

**Comment by smithaammassamveettil** [comment]
Thanks for providing this info. It looks helpful
