### ISSUE TITLE
Optional pricegranularity.ranges parameter is enforced on openrtb2/video endpoint

### ISSUE THREAD

**Issue by joshuahaertel** [prebid/prebid-server#1215]
# Observed Behavior
Sending `"pricegranularity": {}` to the `openrtb2/video` endpoint results in a 500 error with the `empty granularity definition supplied` error message, while omitting `pricegranularity` appears to work.

# Expected Behavior
According to http://prebid.org/prebid-server/endpoints/openrtb2/video.html the `ranges` value isn't necessary. Regardless, `{}` should be just as valid as not sending anything.

# Suggested Fix
Instead of returning the error here:
https://github.com/prebid/prebid-server/blob/fd78c23caef9986556b8558443a7e0cb91831a3a/openrtb_ext/request.go#L152

Use the same default value used when nothing is passed in: https://github.com/prebid/prebid-server/blob/fd78c23caef9986556b8558443a7e0cb91831a3a/openrtb_ext/request.go#L111

It might not be a bad idea to make sure the same thing happens when `null` is passed in.

**Comment by SyntaxNode** [comment]
@camrice Can you please take a look at this?

**Comment by camrice** [comment]
This change sounds good to me. It will be more in line with the documentation. Let me bring this up with the team here.

**Comment by SyntaxNode** [comment]
@joshuahaertel This has been implemented and released. Does this resolve your concern?

**Comment by joshuahaertel** [comment]
Yes, it works great. Thank you!
