### ISSUE TITLE
Issue with Usersync request from Prebid Server to Brightroll DSP

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#1216]
Problem:
We have noticed many of the user sync Urls coming from Appnexus Prebid server to Brightroll DSP is missing '&' after us_privacy field.
Attaching below the user sync request received from you:

[10/Mar/2020:12:26:07 -0400] "GET //pr-bh.ybp.yahoo.com/sync/appnexusprebidserver/?gdpr=0&euconsent=&us_privacy=url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID HTTP/1.1" 

I have verified the user sync url, which we have configured in config.go file is correct and having & after us_privacy field and before 'url' field
https://github.com/prebid/prebid-server/blob/master/config/config.go#L498

Can you please check at your end why it is happening?

Thanks
Smitha

**Comment by smithaammassamveettil** [comment]
@bretg , @hhhjort , @SyntaxNode  Can someone please take a look at this?

**Comment by SyntaxNode** [comment]
Taking a look.

**Comment by SyntaxNode** [comment]
This is due to a typo in the AppNexus config. Everything in this repo looks good. I'll get this rolled out tomorrow. Thank you for reporting it and sorry for the error.

**Comment by smithaammassamveettil** [comment]
Thanks for the update @SyntaxNode. Is this released now?

**Comment by SyntaxNode** [comment]
Yes, it is.

> curl --request POST \
  --url https://prebid.adnxs.com/pbs/v1/cookie_sync \
  --header 'content-type: application/json' \
  --data '{"bidders": ["brightroll"]}'

> {"status":"no_cookie","bidder_status":[{"bidder":"brightroll","no_cookie":true,"usersync":{"url":"https://pr-bh.ybp.yahoo.com/sync/appnexusprebidserver/?gdpr=0&euconsent=&us_privacy=&url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID","type":"redirect"}}]}

**Comment by smithaammassamveettil** [comment]
Thanks for fixing it. We will check at our end then

**Comment by smithaammassamveettil** [comment]
I can see url coming with & now. Thanks
[11/Mar/2020:19:21:48 -0400] "GET //pr-bh.ybp.yahoo.com/sync/appnexusprebidserver/?gdpr=0&euconsent=&us_privacy=&url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID HTTP/1.1"
