### ISSUE TITLE
Changing setDefaultUsersync with env_var?

### ISSUE THREAD

**Issue by holms** [prebid/prebid-server#1223]
I'm actually puzzled how should I change this default with environment variable?  That `s=` parameter is different for each client of BiderIx. Using kubernetes in here. Of course I've could just override a config file for a pod, but maintaining config file changes for future version of pbs would be a bit painful. 
```
	setDefaultUsersync(cfg.Adapters, openrtb_ext.BidderIx, "https://ssum.casalemedia.com/usermatchredir?s=184932&cb="+url.QueryEscape(externalURL)+"%2Fsetuid%3Fbidder%3Dix%26gdpr%3D{{.GDPR}}%26gdpr_consent%3D{{.GDPRConsent}}%26uid%3D")
```

**Comment by SyntaxNode** [comment]
Prebid Server will look at environment variables for overrides. In this specific case, the key is `PBS_ADAPTERS_BIDDERIX_USERSYNC_URL`. You can specify this in your Kubernetes config map as well if you'd like.

**Comment by holms** [comment]
@SyntaxNode Hmm, I really wouldn't find this myself in anyway. Many thanks. Seems to be it's nowhere stated that usersync urls also can be changed. Trying to avoid config maps as much as I can :)

**Comment by SyntaxNode** [comment]
Agreed. We have our sights set on improved docs.
