### ISSUE TITLE
Can't connect to prebid server

### ISSUE THREAD

**Issue by sgagnier-l3g3media** [prebid/prebid-server#1235]
At https://prebid.adnxs.com/

Can't get to the interface.

Don't know where to report either.

**Comment by SyntaxNode** [comment]
Exactly what error are you seeing?

**Comment by sgagnier-l3g3media** [comment]
Bad Request

Error parsing headers: 'limit request headers fields size'

**Comment by sgagnier-l3g3media** [comment]
Clearing all site data, I've been able to login. Tried on many browsers before without success. Something hanging somewhere though.

**Comment by SyntaxNode** [comment]
Looks like the usersync cookie got too large for the admin site. I created a ticket internally to look into it. Using a private browsing / incognito mode should also work.
