### ISSUE TITLE
Support DNT header like Limit Ad Tracking

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1262]
Rounding off the privacy policies in PBS, we need to support looking for the "Do-Not-Track" HTTP header and OpenRTB fields:

- If the "DNT" http header has a value of "1"
- or if device.dnt has a value of "1"

Then follow the same anonymization rules as for device.lmt defined in https://github.com/prebid/prebid-server/issues/833

In addition, when the DNT:1 HTTP header is seen, /cookie-sync and /setuid should immediately give up with HTTP 204.

**Comment by SyntaxNode** [comment]
I had the impression that DNT was only about user syncing. Can you point me to a clear legal definition / opinion on DNT?

I'd also like to have this be configurable by the host.

**Comment by bretg** [comment]
After discussing in committee, we determined that the DNT header isn't well-supported, and Prebid Server doesn't currently require support. From wikipedia: “DNT is not widely adopted by the industry, with companies citing the lack of legal mandates for its use, as well as unclear standards and guidelines for how websites are to interpret the header. Thus, it is not guaranteed that enabling DNT will actually have any effect at all. The W3C disbanded its DNT working group in January 2019, citing insufficient support and adoption. Apple discontinued support for DNT the following month.”
