### ISSUE TITLE
Privacy update: removing user.ext.eids

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1272]
I posted a [PBS Privacy FAQ](https://prebid.org/faq/prebid-server-faq.html#how-does-prebid-server-support-privay-signals) entry on prebid.org and realized that we had missed some other places where there are user IDs: user.ext.eids and user.ext.digitrust

In short, wherever we remove user.buyeruid, we should also remove user.id, user.ext.eids, and user.ext.digitrust

Request changes:

1) Mobile ‘Limit Ad Tracking’ flag (and DNT HTTP header)
If PBS receives ‘device.lmt’ flag in the OpenRTB request, it should also remove user.id, user.ext.eids, and user.ext.digitrust

2) GDPR TCF1 and TCF2
Wherever user.buyeruid is removed, also remove user.id, user.ext.eids, and user.ext.digitrust

3) COPPA
If regs.coppa is set to ‘1’ on the OpenRTB request, also remove user.id, user.ext.eids, and user.ext.digitrust

4) CCPA
If regs.ext.us_privacy is parsed to find that the user has opted-out of a “sale”, also remove user.id, user.ext.eids, and user.ext.digitrust

**Comment by SyntaxNode** [comment]
Sounds good to me. We'll work on this next week for PBS-Go.

**Comment by SyntaxNode** [comment]
This is complete in PBS-Go and PBS-Java.
