### ISSUE TITLE
BidResponse validations

### ISSUE THREAD

**Issue by benjaminch** [prebid/prebid-server#1288]
Hello Team !

I was wondering wether PBS is doing any kind of bid responses validation prior running the auction.
For example, checking:
- that `badv` is respected by the `adomain`
- creative size is allowed
- `secure` is repected by the ad markup
- etc

Unless I am mistaken I didn't found any checks of this kind (but for currency) in the code base.
Is expected? Would you be open to a PR addressing it?

Cheers ! :)

**Comment by SyntaxNode** [comment]
Hi.

There is some level of bid response validation, but I think you're right in that it doesn't cover those scenarios. Sounds interesting to me (especially if you're volunteering to do the work), so long as we have config options to give the host control over the behavior and metrics to understand how often the validations are failing. I'll discuss this with the team and advise.

**Comment by benjaminch** [comment]
Hi @SyntaxNode !

Thanks ! Indeed, I would be interested doing it :)
This is also the opportunity to maximise chances the winning bid will be accepted by the publisher and not gonna be rejected for a `dumb` reason which would have been easily spotted earlier in the pipe (and let place another bid maybe).

Let me know :)

Cheers !

**Comment by patmmccann** [comment]
Hi @benjaminch 

Great idea! 

A couple comments: adomain isn't actually all that common on client side bid responses; is it more reliable out of pbs? 

Appnexus has an allow smaller sizes boolean in their adapter, careful not to invalidate smaller sizes

This could really expand to video well, mime types and durations could be validated

**Comment by bretg** [comment]
These are good ideas, but I'd like to discuss the design before diving in.

We've discussed implementing hooks for plugging in/configuring modules that could contain functionality like this. In that model, these could fall under a "bidresponse hook".

We might someday diverge on exactly which validations should be done in PBS and how sophisticated those validations should be. So I'd like to see us either modularize the validations or make them quite configurable.

The next question will be: is there a way to signal the bidder that PBS has rejected their bid?

**Comment by bretg** [comment]
We discussed in Prebid Server committee and determined that each proposed validation needs to be fleshed out. e.g.

- badv is respected by the adomain
  - should adomain be normalized? e.g. if badv includes "foo.com", and domain is "www.foo.com", should that trigger a rejection?
- creative size is allowed
  - we believe there are scenarios where bidders can return special sizes (e.g. 1x1)
- secure is respected by the ad markup
  - What's involved here - scanning the adm for 'http:' and rejecting? Maybe also 'http%3A' ?

When PBS rejects a bid because it fails a validation there's not currently a notification path to inform them.

Looking for a volunteer to detail the proposed validations.

**Comment by bretg** [comment]
We discussed this in the committee today. In the interest of moving the ball forward, here's a straw:

Meta-requirements

1) each validation should be optional at the host company level
2) there should be account level overrides where reasonable
3) PBS-core validations should not yet support blocked advertisers, domains or categories. That's exchange functionality that we haven't yet designed.

Creative size validation

1) global config: settings.validations.banner-creative-size: true/false
2) global config: settings.validations.banner-creative-allowed-sizes: 1x1, 2x2
3) account config: new 'validations' database column that returns a JSON block. The 'banner-creative-allowed-sizes' attribute lets the account override the global banner-creative-allowed-sizes
4) when validation is on, only the banner mediatype is in scope
5) if the validation throws out the bidResponse:
5a) The bidResponse is removed from consideration and an error added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse rejected: size WxH"}
5b) PBS should log two metrics: validation-err.bidder.BIDDER.size and validation-err.account.ACCOUNT.size
5c)  This information should be made available to analytics adapters as well

Secure Markup

1) global config: settings.validations.secure-markup: true/false.
2) no account config for this feature
3) when validation is on, all mediatypes are in scope
3a) for banner, bidResponse.adm is scanned. Validation fails if it contains http:' or 'http%3A'
3b) for native, ??
3c) for video, the VAST in bidResponse.adm is scanned. Validation fails if it contains http:' or 'http%3A'
4) the validation for each imp is only active if imp[].secure=1
5) if the validation throws out the bidResponse:
5a) The bidResponse is removed from consideration and an error added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse rejected: insecure creative insecure context"}
5b) PBS should log two metrics: validation-err.bidder.BIDDER.secure and validation-err.account.ACCOUNT.secure
5c)  This information should be made available to analytics adapters as well

**Comment by SyntaxNode** [comment]
Sounds good. A few comments:

> global config: settings.validations.banner-creative-size: true/false
> global config: settings.validations.secure-markup: true/false

I'd like to propose a "preview" config mode as well, or perhaps just define this behavior for when the config is set to "false", where the validation is performed and reflected in metrics but is not enforced. This will give hosts a good idea of the consequence of enabling the validation.

> PBS should log two metrics: validation-err.bidder.BIDDER.size and validation-err.account.ACCOUNT.size
> PBS should log two metrics: validation-err.bidder.BIDDER.secure and validation-err.account.ACCOUNT.secure

Do the metrics need to be scoped to the bidder? This is a request-level validation with possible account level overrides. The cardinality is high for bidder scopes, so I'd like to avoid that if possible.

I can see account scoped metrics being useful to understand which account is responsible for the errors. However, the cardinality is extremely high for accounts and could easily overwhelm metric servers. I'm fine adding it as an option, but I'd like to keep it disabled by default.

**Comment by SyntaxNode** [comment]
Discussed by Prebid Server Committee.

Creative size validation
- We believe some adapters treat the creative size as a maximum value and may return any size smaller, not just 1x1 or 2x2. Therefore, a list of specifically allowed sizes may not work. Should we consider the validation option of "no longer than" where the creative must not exceed the height or width allowed?

Secure Markup
- Native is still an unknown. Further research is required. For the other formats, we may want the validation to fail if there is any http:' or 'http%3A' (as proposed) but also that there must be a match on https:' or 'https%3A'. This will ensure urls without protocols defined are not considered secure.

**Comment by benjaminch** [comment]
Hey @SyntaxNode !

Sorry for the delay here. Indeed, for creative size validation, I believe the easiest way to achieve this validation is to check if creative size in inside the bid request size rectangle or not (any size inside the rectangle works but the weirds ones eventually by checking a ratio of what so ever).
Regarding HTTPS, I thing you are right and several checks must be done before rejecting (trying multiple encodings and so on based on the field).

Cheers

**Comment by SyntaxNode** [comment]
PBS-Go supports two styles of metrics. There is a 'flat' style which we support for Influx and a 'labeled' style which we support for Prometheus.

For the flat style, PBS-Go currently standardizes on the format of `adapter.BIDDER.*` and `account.ACCOUNT.BIDDER.*`. We also recently added privacy metrics in the format of `privacy.request.*`. To maintain these patterns, I propose the following metric names:
- `adapter.BIDDER.response.validation.size.err`
- `adapter.BIDDER.response.validation.secure.err`
- `account.ACCOUNT.response.validation.size.err`
- `account.ACCOUNT.response.validation.secure.err`

I don't see a need to sub-correlate account validations with the bidder name, since this validation logic is not bidder specific.

For the labeled style, PBS-Go currently standardizes on the format of `adapter_ACTION{bidder}` and `account_ACTION{account}. To maintain this pattern, I propose the following metric names:
- `adapter_request_validation_size` with labels adapter=BIDDER and success=true or false.
- `adapter_request_validation_secure` with labels adapter=BIDDER and success=true or false.
- `account_request_validation_size` with labels account=ACCOUNT and success=true or false.
- `account_request_validation_secure` with labels account=ACCOUNT and success=true or false.

Due to the high cardinality of account metrics, those will be disabled by default in PBS-Go and can be enabled with the existing config `metrics.disabled_metrics.account_adapter_details`, unless we'd like to have the option of enabling account validation metrics only in which case I'm good with adding a separate config flag.

Thoughts?

**Comment by bretg** [comment]
Thanks @SyntaxNode - description updated with the 'flat' metrics, with the addition of "warn" in addition to "err" metrics. e.g. adapter.BIDDER.response.validation.size.**warn**

> Due to the high cardinality of account metrics, those will be disabled by default in PBS-Go

Sounds fine.

**Comment by SyntaxNode** [comment]
@benjaminch The spec is now complete. Are you interested in implementing it?

**Comment by benjaminch** [comment]
Hey @SyntaxNode ! Yes, with pleasure :)
Just to be sure, to which spec are you referring to? I guess it's this one but just want to make sure.

> We discussed this in the committee today. In the interest of moving the ball forward, here's a straw:
> 
> Meta-requirements
> 
> 1. each validation should be optional at the host company level
> 2. there should be account level overrides where reasonable
> 3. PBS-core validations should not yet support blocked advertisers, domains or categories. That's exchange functionality that we haven't yet designed.
> 
> Creative size validation
> 
> 1. global config: settings.validations.banner-creative-max-size: skip/enforce/warn (default skip)
> 2. account config: new 'validations' account config that returns a JSON block. The '{banner-creative-max-size:skip}' attribute lets the account override whether the check is made for them
> 3. when validation is on, only the banner mediatype is in scope
> 4. validation rules: determine maxHeight and maxWidth across all imp.banner.sizes. If the bid response is larger in either height or width, validation fails
> 5. if the validation status is "enforce":
>    5a) The bidResponse is removed from consideration and an error added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse rejected: size WxH"}
>    5b) PBS should log two metrics: adapter.BIDDER.response.validation.size.err and account.ACCOUNT.response.validation.size.err
>    5c)  This information should be made available to analytics adapters as well
> 6. Else if validation status is "warn":
>    6a) error added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse creative size warning: size WxH larger than AdUnit sizes"}
>    6b) PBS should log two metrics: adapter.BIDDER.response.validation.size.warn and account.ACCOUNT.response.validation.size.warn
> 
> Secure Markup
> 
> 1. global config: settings.validations.secure-markup: skip/enforce/warn.
> 2. no account config for this feature
> 3. the validation for each imp is only active if imp[].secure=1
> 4. when validation is on, all mediatypes are in scope
>    4a) for banner, bidResponse.adm is scanned. Validation fails if it contains 'http:' or 'http%3A' and does not contain either 'https:' or 'https%3A'
>    4b) native is skipped for now until someone can define the appropriate validation
>    4c) for video, the VAST in bidResponse.adm is scanned. Validation fails if it contains http:' or 'http%3A' and does not contain either 'https:' or 'https%3A'
> 5. if the validation mode is "enforce":
>    5a) The bidResponse is removed from consideration and an error added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse rejected: insecure creative in secure context"}
>    5b) PBS should log two metrics: adapter.BIDDER.response.validation.secure.err and account.ACCOUNT.response.validation.secure.err
>    5c)  This information should be made available to analytics adapters as well
> 6. if the validation mode is "warn":
>    6a) an error is added to the debug array response.ext.errors.BIDDER[] with something like { "source": "pbs validation", "message": "bidResponse rejected: insecure creative in secure context"}
>    6b) PBS should log two metrics: adapter.BIDDER.response.validation.secure.warn and account.ACCOUNT.response.validation.secure.warn

**Comment by SyntaxNode** [comment]
> Hey @SyntaxNode ! Yes, with pleasure :)

Fantastic!

> Just to be sure, to which spec are you referring to? I guess it's this one but just want to make sure.

Yes. Bret has kept that spec updated as discussions progressed.

**Comment by SyntaxNode** [comment]
@benjaminch Are still planning on implementing this feature?

**Comment by benjaminch** [comment]
Hey @SyntaxNode !

I am so sorry, I did not had much time those days ... Yes I am still whiling to work on this one of course. I won't be able to start anything before the end of the year / begin of January though :(
If you need / want to move quicker on this one, I would of course understand if anyone else pick it.

Cheers

**Comment by bretg** [comment]
We implemented and released this in PBS-Java in "warn" mode and have found that both validations are indeed firing somewhat often. But without some logging of the offending bid responses, we can't dig into what's actually happening.

So, adding logging requirements:

- When a metric is fired for a warning or enforcement for secure creatives (e.g. adapter.BIDDER.response.validation.secure.err), also log 1% of the triggering bid responses to the server log with the message "BidResponse validation (warn/enforce): bidder BIDDER response triggers secure creative validation. account=ACCOUNT, referrer=REFERRER, adm=AD_MARKUP
- When a metric is fired for a warning or enforcement for creative size (e.g. adapter.BIDDER.response.validation.size.err), also log 1% of the triggering bid responses to the server log with the message "BidResponse validation (warn/enforce): bidder BIDDER response triggers creative size validation. account=ACCOUNT, referrer=REFERRER, max imp size=WxH, bid response size= WxH

**Comment by ShriprasadM** [comment]
@SyntaxNode: Do we have any plans here for

1. Implementing advertiser blocklisting at PBS level?
2. Add advertising blocklisting functionality, controlled by the host through configuration in PBS-go

**Comment by bretg** [comment]
@ShriprasadM - what's your use case? 

The plans for blocking are three-fold:

1) improve the account-configuration infrastructure
2) implement a series of internal interfaces ("hooks") to support modules
3) build a "blocking" module that takes advantage of the above

In the meantime, bidders that require bcat/badv are doing it directly in their adapter config.

**Comment by ShriprasadM** [comment]
Thanks @bretg  for an update!

I am looking for #1 and #2 support in PBS. would like to know, when are we planning around it and release it.

**Comment by bretg** [comment]
> when are we planning around it

For PBS-Java these are both Q1 items. 

There are no timelines for PBS-Go. 

You haven't shared your use case, but if you need blocking for a particular bidder sooner, it needs to be built into the adapter directly

**Comment by ShriprasadM** [comment]
@bretg Thanks for an update!

My use case here is: I want to build the default post-filtering modules in PBS. If an adaptor is not having that capability, the adaptor can opt for the default post-filtering module. It would be controlled via account  level configuration

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.239.0.
