### ISSUE TITLE
Don't Close Stale Issues With A Bot

### ISSUE THREAD

**Issue by mannzer** [prebid/prebid-server#1293]
According to the Project Principles documented at http://prebid.org/principles.html there is the guidance to be 

"Collaborative: Foster a community of contribution."

Closing issues with a bot for inactivity means many if not most issues will simply be ignored, and is therefore most likely not worth anyone's time or effort to even report. This behavior actively discourages community participation. 

Please reconsider in the light of your stated principles.

**Comment by SyntaxNode** [comment]
We're very much committed to a community of collaboration and contribution. I'm sorry you view the stalebot as a violation of this principle. The intent of the stalebot is to help us clean up inactive conversations and provide inactivity warnings to give authors a reminder to revisit issue. When issues are closed, they are still visible on GitHub and can certainly be reopened if needed. 

Is there an issue you noticed that shouldn't have been closed but was by the stalebot?

**Comment by SyntaxNode** [comment]
We'll discuss this tomorrow. Can you please provide examples of issues which were simply ignored?

**Comment by bretg** [comment]
I agree that we've fallen behind on issues, and marking them stale after one week is pretty aggressive. Here's a PR that raises the stale period to 2 months, and then 3 more weeks as stale before closing -- basically 3 months. In addition, there are lots of labels that can be used to make things permanently unstale, e.g. 'pinned'.

Besides this and a re-affirmation to get to issues in a more timely manner, will this suffice?

**Comment by bretg** [comment]
Ironic that the issue about aggressive stale bot has been stale-botted. Anyhow, we have a PR open to dramatically increase the time period here.

**Comment by bretg** [comment]
We've bumped the stale and close levels:
- Pulls: daysUntilStale: 7, daysUntilClose: 30
- Issues: daysUntilStale: 30, daysUntilClose: 60
