### ISSUE TITLE
Prebid video - Override parameters inside createImpressionTemplate

### ISSUE THREAD

**Issue by neririchter** [prebid/prebid-server#1295]
It seems that when using stored imps, the function of: "createImpressionTemplate" inside Video_auction class overrides all parameters except a few params:

func createImpressionTemplate(imp openrtb.Imp, video *openrtb.Video) openrtb.Imp {
	imp.Video = &openrtb.Video{}
	imp.Video.W = video.W
	imp.Video.H = video.H
	imp.Video.Protocols = video.Protocols
	imp.Video.MIMEs = video.MIMEs
	return imp
}
but if I wish to use for example Imp.video.playbackmethod or any other video parameters i can not.
not from the stored imps and not from the request itself, because its been override.

**Comment by SyntaxNode** [comment]
Can you please take a look at this?
@camrice @jmaynardxandr @VeronikaSolovei9

**Comment by VeronikaSolovei9** [comment]
Initial bug fix PR: https://github.com/prebid/prebid-server/pull/1297

**Comment by neririchter** [comment]
I am a bit confused when you say we don't support stored impressions in video endpoint, because if I take a look at the server documentation I am required to create pod configId that is a stored imp, and as part of the stored imp, an empty video object is been stored.
and I understand we must validate those 4 params but we can not block other openRtb params from passing to adapters.

**Comment by VeronikaSolovei9** [comment]
@neririchter pod id is a config id where we store only extension part of impression(in most cases bidder related parameters), not the entire impression. Video object validation is now happening in `validateVideoRequest` function and it validates only MIMEs and Protocols. Video.W and Video.H are optional. I agree, passing other video related parameters make sense.

**Comment by neririchter** [comment]
@VeronikaSolovei9 understood, thank you for the detailed response.

**Comment by SyntaxNode** [comment]
@neririchter Does PR #1297 resolve all of your concerns? If so, can we please close the issue?

**Comment by neririchter** [comment]
@SyntaxNode yes, thank you, this PR, resolve all my concerns
