### ISSUE TITLE
Submitting primaryadserver !=1 returns empty array

### ISSUE THREAD

**Issue by johnli2210** [prebid/prebid-server#1298]
According to docs: ```includebrandcategory.primaryadserver``` should take one of two values, 1: freewheel or 2: GAM. 

Passing 1 is OK; but submitting 2 returns an empty object ```{"adPods":[]}```.

**Comment by SyntaxNode** [comment]
@camrice Can you please take a look at this?

**Comment by camrice** [comment]
In this case, is the `publisher` also being submitted with the `includebrandcategory`? For example, we use `"dfp"` as the publisher when using GAM as the primary ad server. However, looking at the documentation, this is not mentioned. When the `primaryadserver` is set to 2 or GAM, then the `publisher` field is required. We will be creating a ticket with the docs team to make note of this.

**Comment by MartianTribe** [comment]
The docs have been updated. This issue can be closed.
