### ISSUE TITLE
Consumable: Possibly incorrect usersync VENDOR_ID

### ISSUE THREAD

**Issue by djcsdy** [prebid/prebid-server#1299]
I’m doing some work on behalf of Consumable and I came across this code:
https://github.com/prebid/prebid-server/blob/93b8a0edb8e418f4e360469d6d136995ddf45dc1/adapters/consumable/usersync.go#L10

This... doesn’t look quite right? :-)

We are not sure if this value should be changed or what it should be changed to. Any advice gratefully received.

Thanks.

**Comment by SyntaxNode** [comment]
Good spotting. I think their vendor id is actually 591. I'll reach out to their devs.

**Comment by djcsdy** [comment]
Thanks @SyntaxNode. I am working on behalf of Consumable so it will probably be me who makes the change.

I assume your contact at Consumable is David Naffis. If you CC me (daniel@velope.tv) when you contact him that should help speed things along.
