### ISSUE TITLE
prebid.adnxs.com update schedule?

### ISSUE THREAD

**Issue by dtbarne** [prebid/prebid-server#1315]
How often is the production site for prebid.adnxs.com updated? We had our bidder merged into master, but I'm not seeing it available under https://prebid.adnxs.com/pbs/v1/info/bidders and I'm just curious when I can expect it to become available so we can let our publishers know.

Thanks!

**Comment by SyntaxNode** [comment]
Xandr doesn't commit to a formal release schedule for `prebid.adnxs.com`. That being said... we typically release weekly on Wednesdays or Thursdays.
