### ISSUE TITLE
Only US_Privacy  with cookie sync results into error

### ISSUE THREAD

**Issue by GeneGenie** [prebid/prebid-server#1317]
When publisher has only us_privacy resolved in browser 
following structure is sent to /cookie_sync  endpoint : 
`
{"uuid":"e2ec2029-114c-478e-aac1-59b9dbb55a35","bidders":["adtelligent"],"account":"1","us_privacy":"ADVADDS"}
`

And GDPR always sets to 1 during parsing this request, here:
https://github.com/prebid/prebid-server/blob/master/endpoints/cookie_sync.go#L175
Which results in  following passback url: 
`/setuid?bidder=adtelligent&gdpr=1&gdpr_consent=&uid=SYNCED_UID` 
which is handled as error since gdpr must always be with consent string. 

Is it by design, or should I extend all cookie_sync passbacks with us_privacy_consent macros and handle it?! 

**UPD:**  actually it is gdpr=1   even without us_privacy being sent
Thanks

**Comment by SyntaxNode** [comment]
Right. I was going to comment that this isn't actually related to us_privacy.

The flow of the code may be a bit funky here. The idea is that the `usersyncIfAmbiguous` flag actually means "GDPR is not required". The default value is `true`. Our intention is for this flag to be set to `false` for European traffic where GDPR is always required.

I'm guessing you're hitting a European server which is forcing `gdpr=1`. That is the intended behavior.

Would you prefer this is handled as an error as it is here?:
https://github.com/prebid/prebid-server/blob/master/endpoints/cookie_sync.go#L170

**Comment by SyntaxNode** [comment]
@GeneGenie did that answer your question?

**Comment by SyntaxNode** [comment]
Closed due to inactivity and the answer being provided.
