### ISSUE TITLE
Refine Prebid Server TCF2 user ID support

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1326]
The committee has refined the Prebid Server support for TCF2 originally defined in issue #1177 

The full document is https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#

This issue tracks the following changes:

1. Remove the previously implemented enforcement for Purpose 4.
2. Replace it with Requirements 19 and 20:

```
19) User IDs must be stripped from a given vendor’s auction when any of these is true:
- GDPR is in-scope and the consent string is empty or malformed
- User has not provided legal basis for any Purpose 2,3,4,5,6,7,8,9, or 10.
User IDs are defined to be: user.buyeruid, user.id, user.ext.eids, user.ext.digitrust, device.ifa, device.macsha1, device.macmd5, device.dpidsha1, device.dpidmd5, device.didsha1, and device.didmd5.

20) If the host company has opted not to enforce a purpose in the local Prebid Server,
that configuration should not be considered in the legal basis determination for stripping
User IDs in the above requirement. i.e. if Prebid Server config says to ignore enforcement
of Purpose 2 or 7, that configuration should not automatically cause User IDs to always
be passed. 
```
3. Update the "basic enforcement" fallback to check for LITransparency for the case of Purpose 2

**Comment by SyntaxNode** [comment]
Could you please elaborate on this change:

> Passing User IDs into an auction
> Any Purpose 2-10. User IDs are important for more than personalizing ads - they can be used in frequency capping, building profiles, counting unique users, etc. So Prebid Server should pass User IDs through the auction if any of Purposes 2-10 pass the legal basis test.

and explain how it relates to Purpose 2 conducting auctions?

**Comment by bretg** [comment]
Added a refinement of the definition of user ID: "User IDs are defined to be: user.buyeruid, user.id, user.ext.eids, user.ext.digitrust, device.ifa, device.macsha1, device.macmd5, device.dpidsha1, device.dpidmd5, device.didsha1, and device.didmd5."

**Comment by bretg** [comment]
Done on PBS-Java

**Comment by SyntaxNode** [comment]
This is in-progress on PBS-Go.
