### ISSUE TITLE
404 of page http://prebid.org/examples/pbjs_demo.html

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-server#1330]
When working on the sample request from https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md

**Comment by SyntaxNode** [comment]
@MartianTribe

**Comment by StarWindMoonCloud** [comment]
Any update here? It's been one week

**Comment by StarWindMoonCloud** [comment]
@SyntaxNode any comment about @MartianTribe 's reply?

**Comment by MartianTribe** [comment]
Like I said, that page has been deleted. If you are getting to it from a link on our site, let me know which page the link is on and I'll fix it. The examples we have available are here: 

[Basic example](http://prebid.org/dev-docs/examples/basic-example.html)

The only server example we have at this time is [here](http://prebid.org/dev-docs/examples/use-prebid-with-appnexus-ad-server.html)

Let me know if you need anything else.

**Comment by StarWindMoonCloud** [comment]
Given questions answered, I'll close the issue here
