### ISSUE TITLE
Add source.tid and site.publisher.id to requests

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1337]
We found that Prebid Server is not passing source.tid to bidder adapters on AMP requests, and at least one bidder requires them.

All request types should have a source.tid. If the incoming request doesn't have one, Prebid Server should generate a random UUID.

Also, we should be passing site.publisher.id as the resolved account ID. Here's an updated account resolution algorithm. Step 4 is the new part.

1. look in site.publisher.id
2. look in app.publisher.id
3. if AMP, look for the 'account' parameter on the query string
4. When we've finally resolved the account ID, make sure it's set in site.publisher.id or app.publisher.id (whichever is appropriate)

**Comment by SyntaxNode** [comment]
Ok. So, if the `site` exists but doesn't have a publisher.id, try to get it from the AMP query string. Some for flow for the `app`. I believe we verify a request can't have both `site` and `app`, so cross referencing isn't a concern.

**Comment by bretg** [comment]
Done in PBS-Java

**Comment by SyntaxNode** [comment]
Available in PBS-Go starting with version 0.127.0.
