### ISSUE TITLE
Amp creative size

### ISSUE THREAD

**Issue by Hamper** [prebid/prebid-server#1338]
I'm trying to use prebid-server for amp ads like this
```html
<amp-ad 
  type="doubleclick"
  width="300" 
  height="250" 
  data-slot="/19968336/header-bid-tag-0"
  rtc-config={"urls":["https://[somedomain]/openrtb2/amp?tag_id=amp.test"]}
>
```
with request like
```json
{
    "id": "some-request-id",
    "site": {
        "page": "www.somedomain.com/amp"
    },
    "ext": {
        "prebid": {
            "targeting": {
                "pricegranularity": {
                    "precision": 2,
                    "ranges": [{
                        "max": 20.00,
                        "increment": 0.10
                    }]
                }
            }
        }
    },
    "imp": [
        {
            "id": "some-impression-id",
            "banner": {
                "format": [
                    {
                        "w": 300,
                        "h": 250
                    }
                ]
            },
            "ext": {
                "appnexus": {
                   "placementId": 13144370
                }
            }
        }
    ]
}
```

And in this case, if I get some bid from prebid server I also get safe frame from google but this iframe have 1x1 size. If I manually change iframe size in developer tools to something like 300x250 I see normal ad. Also if I change amp-ad to amp-embed I see ad but amp-embed must be alias of amp-ad.

What's wrong with my setup?

**Comment by SyntaxNode** [comment]
I've asked my friends on the PrebidJS side to take a look at this question. Hopefully you'll get some guidance here soon.

**Comment by bretg** [comment]
@Hamper - what size is the creative in the ad server? Are you getting an error on the console log like "Targeting key hb_size not found to resize creative"?

The instructions at https://prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html are missing the 1x1 size  note, but another important part is that you're passing hb_size into the creative:
```
ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
```

1) creative then calls ucTag.renderAd(document, ucTagData);
2) which calls transformAuctionTargetingData to map (amongst others) hb_size to 'size'
3) then it calls renderAmpOrMobileAd(targetingData.cacheHost, targetingData.cachePath, targetingData.uuid, targetingData.size, targetingData.hbPb);
4) eventually it should call resizeIframe(sizeArr[0], sizeArr[1]);

If this doesn't help figure out it out, please post the body of the creative that you have in the ad server.

**Comment by Hamper** [comment]
Issue resolved, we just forgot to enable safeframe, universal creative don't resize unsafe frames
