### ISSUE TITLE
How to set request.test?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-server#1341]
While playing with auction endpoint (https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md) against audienceNetwork, I got "message": "Server responded with failure status: 400. Set request.test = 1 for debugging info."
But could not figure out how to set it, tried HTTP parameter and config.go, not working

Sadly, couldn't you find a doc for how to set

**Comment by SyntaxNode** [comment]
The `request.test` is referring to a property of the OpenRTB request. You'll find it defined in the [OpenRTB 2.5 spec](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf).

Here's an example request with it set:
```
{
    "id": "some-request-id",
    "test": 1,
    "site": {
        "page": "prebid.org"
    },
    "imp": [{
        "id": "some-impression-id",
        "banner": {
            "format": [{
                "w": 600,
                "h": 500
            }, {
                "w": 300,
                "h": 600
            }]
        },
        "ext": {
            "appnexus": {
                "placementId": 12883451
            }
        }
    }],
    "tmax": 500
}
```

**Comment by StarWindMoonCloud** [comment]
Got, thank you @SyntaxNode
