### ISSUE TITLE
Where to set PREBID_SERVER_CONFIGURATION_ID for self hosting prebid server

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-server#1345]
From client integration document, one needs PREBID_SERVER_CONFIGURATION_ID for creating ad unit like below:
BannerAdUnit bannerAdUnit = new BannerAdUnit("PREBID_SERVER_CONFIGURATION_ID", 300, 250);
http://prebid.org/prebid-mobile/pbm-api/android/code-integration-android.html

But after searching through prebid-server code and documents, one couldn't find where to set this config, please advise

**Comment by SyntaxNode** [comment]
Does that answer your question @StarWindMoonCloud?

**Comment by bretg** [comment]
In case it helps, the SDK's job is to generate OpenRTB for Prebid Server. The OpenRTB identifies "stored request IDs", which are used on the Prebid Server side to pull in details needed for auction like bidders, bid params, targeting, caching, etc.

1) link the app to your PBS account. This will need a storedrequest with the same ID. It contains ext.prebid config like cache and targeting params.
```
// get this ID from your Prebid Server host provider
PrebidMobile.setPrebidServerAccountId("1234");
```
2) create the ad slot with a storedrequest ID provided by the PBS host. The PREBID_SERVER_CONFIGURATION_ID defines which bidders and bid parameters are relevant for this ad slot.
```
// get PREBID_SERVER_CONFIGURATION_ID from your Prebid Server host provider
BannerAdUnit bannerAdUnit = new BannerAdUnit("PREBID_SERVER_CONFIGURATION_ID", 300, 250);
```
The openrtb generated might be:
```
{
  "id": "random-uuid",
  "app": {
        "bundle": "AppNexus.PrebidMobileDemo",
        "ext": {
            "prebid": {
                "version": "0.2.0",
                "source": "prebid-mobile"
            }
        },
        "publisher": {
            "id": "1234" // from PrebidMobile.setPrebidServerAccountId("1234");
        },
        "ver": "1.0"
  },
  "imp": [
    {
      "id": "random-uuid",
      "banner": {
         "format": [
            {
                "h": 250,
                "w": 300
            }
        ]
      },
      "ext": {
        "prebid": {
          "storedrequest": {     // this pulls in the bidders and params for the first ad slot
            "id": "PREBID_SERVER_CONFIGURATION_ID"
          }
        }
      }
    }
  ],
  "ext": {
    "prebid": {
	"storedrequest": {   // this maps to the "top-level" stored request
          "id": "1234"  // from setPrebidServerAccountId(). Pulls in global behavior (cache, targeting)
	}
    }
  }
}
```

**Comment by StarWindMoonCloud** [comment]
Thank you guys, quite helpful. 
I have a similar question, how about accountId, client needs it
http://prebid.org/prebid-mobile/pbm-api/android/prebidmobile-object-android.html

It should be some s2sconfig to me after some research from below doc
http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-Server-to-Server

But how to config prebid server accordingly?

**Comment by StarWindMoonCloud** [comment]
Thank you @bretg, your explanation helps a lot. Do you have a full config example with accountId?

**Comment by bretg** [comment]
> full config example with accountId

Please describe what actual problem you're running into.

Here's how accountId works:
- The Prebid Server host company decides whether account ID is required. They establish a database table containing account details like default price granularity, GDPR settings, etc.
- Get your account ID from the Prebid Server host company
- Specify the accountId in PBJS via s2sConfig.accountId - this is set in site.publisher.id
- Specify the accountId in SDK via the setPrebidServerAccountId() function - this is set in app.publisher.id
- Prebid Server looks up the specified account in its database and rejects the request if necessary.

If you're trying to set up your own Prebid Server, it's fair to say that documentation is thin there. @SyntaxNode - do we have an references for how to set up the DB query for PBS-Go? We ought to consider publishing an example full config.

**Comment by StarWindMoonCloud** [comment]
Thank you @bretg for the further explanation, we are working on self-hosting and did feel documentation was thin, moreover, we are doing in-app integration.

So I should take "app.publisher.id" here, but this is a per bid parameter to me, one example is the audienceNetwork bidder
https://developers.facebook.com/docs/audience-network/overview/in-house-mediation/server-to-server/server-setup

But it's saying global setting here.
http://prebid.org/prebid-mobile/pbm-api/android/prebidmobile-object-android.html

**Comment by StarWindMoonCloud** [comment]
any further comments about my last one? @SyntaxNode @bretg

**Comment by bretg** [comment]
If you're setting up your own Prebid Server, then you're going to:

1) define your own set of publisher IDs
2) set up your own Prebid Server database populated with these accounts (probably by integrating this DB with another internal system)
3) your database will also contain "stored requests". Just think of these as "#includes" which get merged into the Prebid OpenRTB at the appropriate place. You want to have control of these pieces in a DB that you can change rather than having them hard-coded in the app. As described above, there are two different kinds for app:

a) "top level stored requests" - following up on the example ORTB above, this might be an example of the "stored request ID 1234" record in your DB -- it's merged into the incoming ORTB request and sets the cross-adunit params.

```
{
    "cur": [
        "EUR"
    ],
    "ext": {
        "prebid": {
            "cache": {
                "bids": {}
            },
            "targeting": {
                "includewinners": true,
                "includebidderkeys": true,
                "mediatypepricegranularity": {
                    "banner": {
                        "ranges": [
                            {
                                "max": 5,
                                "min": 0,
                                "increment": 0.01
                            },
                            {
                                "max": 8,
                                "min": 5,
                                "increment": 0.1
                            },
                            {
                                "max": 30,
                                "min": 8,
                                "increment": 1
                            }
                        ],
                        "precision": 2
                    }
                }
            }
        }
    }
}
```

b)  other stored requests correspond to adunits within the app. These contain the bidders and bid params. If facebook is one of the bidders you use, that's where their info goes. Say this is the DB entry for "PREBID_SERVER_CONFIGURATION_ID" referenced above

```
{
    "ext": {
        "audienceNetwork": {
            "placementId": "PlacementFromFacebook",
            "publisherId": "PublisherFromFacebook"
        },
        "bidderA": {.   // other bidders
            "key1": "val1"
        }
    }
}
```

4) instruct the app developers to place your publisher ID in the Prebid SDK with setPrebidServerAccountId() and the AdUnits with BannerAdUnit()

5)  The [audienceNetwork Prebid Server bid adapter](https://github.com/prebid/prebid-server/tree/master/adapters/audienceNetwork) will take the parameters passed to it from the stored request. That adapter's job is to create the OpenRTB needed for Facebook's endpoint you're seeing in their documentation. You don't have to make it yourself.

**Comment by StarWindMoonCloud** [comment]
totally got your point @bretg , really appreciate the great effort!
Hopefully, the documentation will get better as well.
