### ISSUE TITLE
How to use multiple prebid cache servers with prebid server

### ISSUE THREAD

**Issue by kanchika-automatad** [prebid/prebid-server#1351]
We are using multiple prebid servers with load balancer and a single prebid cache server to deal with high traffic. Is there any way we can increase the number of prebid cache servers while keeping the stored cache synced across all cache servers

**Comment by SyntaxNode** [comment]
Yes, absolutely. We run multiple Prebid Cache servers at Xandr. To keep the stored cache in sync, you'll need to use a third party store instead of the default in memory store. We support aerospike,  azure tables, cassandra, memcache, and redis.

**Comment by bretg** [comment]
@kanchika-automatad - did this answer your question? Basically Prebid Cache is just a thin layer that sits on top of something else like one of the technologies mentioned above.
