### ISSUE TITLE
PreferDeals Flag

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1355]
Exploring the idea of providing more control over how PBS picks the overall winner when it returns ad server targeting. While it's true that PBS always sends the top bid from each bidder in the OpenRTB, some clients can't or don't look at those values, particularly AMP.

Currently, the hb_pb/hb_bidder/hb_adid/etc winning targeting values are determined by the highest bid value. Not the highest value after granularity quantizing, but the highest actual bid. If the targeting isn't in `includebidderkeys` mode, it means that a deal won't get returned unless it has the highest CPM. Which means basically that pubs who've implemented Send-Top-Bids can miss deal bids.

Proposal:
- PBS supports a new request flag: `ext.prebid.targeting.preferdeals: true` to have Prebid Server choose the highest value deal before choosing the highest value non-deal.
- No need for an account setting, since the flag is mostly relevant for AMP and SDK -- storedrequests can be created that have `preferdeals:true`.

**Comment by bretg** [comment]
Approved by PBS committee

**Comment by hhhjort** [comment]
Should this be on the `imp.ext` level? I just realized this is different from all the other targeting parameters that are on the request level.

**Comment by bretg** [comment]
Good Q. Spoke with a publisher on this -- we think that keeping the flag at the request level is fine.

**Comment by bretg** [comment]
Updated the issue to reflect the global, rather than per-imp, nature of this flag.

**Comment by bretg** [comment]
Released with PBS-Java 1.66. Docs updated.
