### ISSUE TITLE
Prebid mobile cookie-syncs example?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-server#1363]
Wondering how cookie-syncs can be done for android prebid integration
https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#cookie-syncs

I was not able to do so after trying out and looking into prebid mobile code, thus opened an issue there https://github.com/prebid/prebid-mobile-android/issues/200. 

But the community there is not active to me, wanna try luck here as well.

**Comment by bretg** [comment]
There's no such thing as /cookie-sync in Android or iOS environment.

**Comment by StarWindMoonCloud** [comment]
oops, then how shall we pass down payload like buyeruids @bretg ? Just couldn't find a way from prebid mobile so far.

**Comment by bszekely1** [comment]
There is no need to pass buyeruids for Android or iOS integrations as Bret mentioned above. In-App traffic takes advantage of Device IDs not cookie IDs. Prebid SDK should pass this automatically to Prebid Server: https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java#L826

**Comment by bretg** [comment]
This is related to https://github.com/prebid/prebid-mobile-android/issues/200. Closing this issue.
