### ISSUE TITLE
Audience Network Bid Adapter: ingest bidder token

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#1369]
## Type of issue

Feature Request

## Description

The Audience Network Exchange requires a browser based identity token (cookie user ID) according to their [Server-to-Server documentation](https://developers.facebook.com/docs/audience-network/overview/in-house-mediation/server-to-server/integration#pass-identity) (even on in-ap traffic) provided by user @StarWindMoonCloud  in [issue 200](https://github.com/prebid/prebid-mobile-android/issues/200).

The goal of this ticket is to define a standard protocol to express the required identity token for the Audience Network Bid Adapter to pick up and pass to their exchange. On the desktop side (prebid.js) or even AMP, there is already a field to signal the browser based user ID (user.buyeruid).

## Proposed Design

The origins of this issue is specific to in-app traffic coming from Prebid SDK, where prebid.js and AMP are out of scope. To reduce custom changes for individual bidders or one off solutions, the proposal below is to leverage the existing Prebid SDK featureset of First Party Data to communicate signaling.

**Predefined First Party Data**
Key name: "fbBidderToken"
Value: "user bidder token"

First party data attribute will be passed in the user.ext.data field.

**Example call to PBS**
```
{
    "ext": {
        "prebid": {
            "storedrequest": {
                "id": "12345678"
            },
            "targeting": {

            },
            "cache": {
                "bids": {

                }
            }
        }
    },
    "user": {
        "ext": {
            "data": { 
                "fbBidderToken": ["xxxxx-xxxx-xxxxx"]
            }
        }
    },
    "device": {
        "osv": "13.2.3",
        "make": "Apple",
        "devtime": 1592234797,
        "pxratio": 3,
        ...
    },
    "imp": [{
        "ext": {
            "prebid": {
                "storedrequest": {
                    "id": "1123456"
                }
            }
        },
        "id": "sdlkafjasdl;kj",
        "banner": {
            "format": [{
                "h": 812,
                "w": 375
            }]
        }
    }],
    "source": {
        "tid": "3838823r79237ewr8"
    },
    "id": "83B02D14-8AFD-442A-9BD5-11973587FDDB",
    "app": {
        "ext": {
            "prebid": {
                "source": "prebid-mobile",
                "version": "8.5.1"
            }
        },
        "publisher": {
            "id": "12345"
        },
        "bundle": "abcdef"
    }
}
```

**PBS Changes**
On the PBS side, the Audience Network bid adapter should read this signal and supply it to the FB endpoint as `user.buyeruid`.

**Open Questions**
* Is bidder token required for our Audience Network integration in PBS?
    * If it is not required, will supplying the bidder token help lift CPMs?
    * If not required, what impacts are there not supplying the bidder token?
* Will publishers be required integrate with Facebook's SDK to retrieve this ID?
    * If so, is this the only reason a publisher would add the FB SDK just to retrieve the ID?

## Other information

[PBS issue 1363](https://github.com/prebid/prebid-server/issues/1363)
[Prebid SDK Android issue 200](https://github.com/prebid/prebid-mobile-android/issues/200)

**Comment by SyntaxNode** [comment]
> Is bidder token required for our Audience Network integration in PBS?

Yes. The Audience Network adapter will return an error if bidder token is not passed in as the `user.buyeruid`. 

> Will publishers be required integrate with Facebook's SDK to retrieve this ID?

I'm not familiar with the Mobile SDK. I've asked those who are and will report back the answer here.

> On the desktop side (prebid.js) or even AMP, there is already a field to signal the browser based user ID (user.buyeruid).

Why can't the Mobile SDK populate this field as well?

**Comment by bszekely1** [comment]
> On the desktop side (prebid.js) or even AMP, there is already a field to signal the browser based user ID (user.buyeruid).

Why can't the Mobile SDK populate this field as well?

> > Is bidder token required for our Audience Network integration in PBS?
> 
> Yes. The Audience Network adapter will return an error if bidder token is not passed in as the `user.buyeruid`.
> 
> > Will publishers be required integrate with Facebook's SDK to retrieve this ID?
> 
> I'm not familiar with the Mobile SDK. I've asked those who are and will report back the answer here.
> 
> > On the desktop side (prebid.js) or even AMP, there is already a field to signal the browser based user ID (user.buyeruid).
> 
> Why can't the Mobile SDK populate this field as well?

The Mobile SDK can populate if given the ID, however the proposal is to not make a custom change in Prebid SDK just to accommodate one bidder. Cookie IDs are not a thing for in-app traffic. Yes, it's possible we can expose an attribute to pass an ID that populates user.buyeruid where any bidder can read it, however we can muddy the water if lets say another bidder wants to pass an ID there, we have a battle of who puts what ID where and who gets access to read it. Changes on the prebid SDK side are not so simple as pushing a new javascript file. If we leverage the existing toolset (First Party Data), publishers can jam whatever they want in there, and adapters can read it, so long as we come up with a protocol.

**Comment by hhhjort** [comment]
Since this is specific to Audience Network, and each bidder adapter defines its own set of parameters it needs, why don't we just add this as a new adapter parameter for the Audience Network? This keeps us from polluting the namespace in the openrtb request.

Also, is it a concern if the facebook ID leaks into other bidders? If it is in the adapter parameters, it is automatically hidden from all other adapters.

**Comment by bszekely1** [comment]
> Since this is specific to Audience Network, and each bidder adapter defines its own set of parameters it needs, why don't we just add this as a new adapter parameter for the Audience Network? This keeps us from polluting the namespace in the openrtb request.

The ID is specific to the user, not context of inventory. We don't have a precedence of replacing bidder param values dynamically. 

> Also, is it a concern if the facebook ID leaks into other bidders? If it is in the adapter parameters, it is automatically hidden from all other adapters.

If we pass an ID in the `user.buyeruid` any bid adapter can read it. This is OpenRTB. My point above still stands that this is user specific.

**Comment by SyntaxNode** [comment]
> Will publishers be required integrate with Facebook's SDK to retrieve this ID?

Yes. It's currently a requirement from Facebook.

> If so, is this the only reason a publisher would add the FB SDK just to retrieve the ID?

It's one of two reasons, the other being that Facebook requires their SDK to be used by the publisher's app to render winning Facebook creatives. Ideally, this would be phased out by Facebook or perhaps Facebook could release a lighter version of the SDK that only has the bidder token retrieval and rendering code.

**Comment by SyntaxNode** [comment]
> If we pass an ID in the user.buyeruid any bid adapter can read it. This is OpenRTB. My point above still stands that this is user specific.

That's a good point. The adapter was built targeting a specific use case a bit too much. I agree a change it needed.

**Comment by bszekely1** [comment]
If the Facebook SDK is required for rendering, how would this work for Prebid SDK? Would there need to be new line items for Facebook? This would require a deeper conversation on Friday's Server PMC call. I will also raise it in the Mobile PMC.

**Comment by hhhjort** [comment]
> The ID is specific to the user, not context of inventory. We don't have a precedence of replacing bidder param values dynamically.
> 

We have to dynamically update the request being generated somehow to include user data. Or there some technical limitations that makes updating this location easier than updating bidder parameters?

Ideally facebook would implement some sort of cookiesync machinery so that they could get the correct `user.buyeruid` filled out just like every other adapter.

Hold on, we should just use that existing machinery to fill that out, no code changes required, you could implement this today.

`{
  "user": {
    "ext": {
      "prebid": {
        "buyeruids": {
          "audienceNetwork": "xxxxx-xxxx-xxxxx"
        }
      }
    }
  }
}`

This is existing functionality designed to make server to server scenarios work.

**Comment by bszekely1** [comment]
> > The ID is specific to the user, not context of inventory. We don't have a precedence of replacing bidder param values dynamically.
> 
> We have to dynamically update the request being generated somehow to include user data. Or there some technical limitations that makes updating this location easier than updating bidder parameters?
> 
> Ideally facebook would implement some sort of cookiesync machinery so that they could get the correct `user.buyeruid` filled out just like every other adapter.
> 
> Hold on, we should just use that existing machinery to fill that out, no code changes required, you could implement this today.
> 
> ```
> {
>   "user": {
>     "ext": {
>       "prebid": {
>         "buyeruids": {
>           "audienceNetwork": "xxxxx-xxxx-xxxxx"
>         }
>       }
>     }
>   }
> }
> ```
> 
> This is existing functionality designed to make server to server scenarios work.

this would require a new object in the Prebid SDK for cookie IDs. Having to add new logic in the Prebid SDK to send the cookie ID via this framework is sub-optimal. What we can do is have a reserved name space in the First Party Data object to translate to the buyer UID object. Something we can think about.

**Comment by hhhjort** [comment]
> > Hold on, we should just use that existing machinery to fill that out, no code changes required, you could implement this today.
> > ```
> > {
> >   "user": {
> >     "ext": {
> >       "prebid": {
> >         "buyeruids": {
> >           "audienceNetwork": "xxxxx-xxxx-xxxxx"
> >         }
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > This is existing functionality designed to make server to server scenarios work.
> 
> this would require a new object in the Prebid SDK for cookie IDs. Having to add new logic in the Prebid SDK to send the cookie ID via this framework is sub-optimal. What we can do is have a reserved name space in the First Party Data object to translate to the buyer UID object. Something we can think about.

How is putting a value in `user.ext.prebid.buyerids.audienceNetwork` more difficult than putting the same value in `user.ext.data.fbBidderToken[0]`? You have to have to get the value into the SDK somehow. You could extend this by making the SDK responsible for storing all the cookie syncs instead of having PBS do that, but I was just suggesting storing the facebook value since apparently you already have that via other means and they aren't playing nicely with the normal cookie sync process.

**Comment by bszekely1** [comment]
> > > Hold on, we should just use that existing machinery to fill that out, no code changes required, you could implement this today.
> > > ```
> > > {
> > >   "user": {
> > >     "ext": {
> > >       "prebid": {
> > >         "buyeruids": {
> > >           "audienceNetwork": "xxxxx-xxxx-xxxxx"
> > >         }
> > >       }
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > > This is existing functionality designed to make server to server scenarios work.
> > 
> > 
> > this would require a new object in the Prebid SDK for cookie IDs. Having to add new logic in the Prebid SDK to send the cookie ID via this framework is sub-optimal. What we can do is have a reserved name space in the First Party Data object to translate to the buyer UID object. Something we can think about.
> 
> How is putting a value in `user.ext.prebid.buyerids.audienceNetwork` more difficult than putting the same value in `user.ext.data.fbBidderToken[0]`? You have to have to get the value into the SDK somehow. You could extend this by making the SDK responsible for storing all the cookie syncs instead of having PBS do that, but I was just suggesting storing the facebook value since apparently you already have that via other means and they aren't playing nicely with the normal cookie sync process.

I probably didn't explain my thought properly. We can place cookie IDs in `user.ext.prebid.buyerids.<bidder name>`, however i was reluctant to just make a new property in the Prebid SDK specific for cookies. We can use a reserved namespace in First Party Data to translate the data into `user.ext.prebid.buyeruids.*`. It's not clear that cookies will be a thing in SDK. The translation can occur either in Prebid SDK or in PBS. I say PBS as an option because less is more with Prebid SDK.

**Comment by StarWindMoonCloud** [comment]
Thank you guys for working on it, really appreciate the feature request and look forward to hearing updates from Server PMC

**Comment by bszekely1** [comment]
I am closing this ticket for a bit to avoid having something open for a long time. We are going to take this action item in the Prebid Mobile side. No work needed for now.

**Comment by StarWindMoonCloud** [comment]
@bszekely1 please share the corresponding Prebid Mobile issue

**Comment by bszekely1** [comment]
There isn't a new ticket assigned yet. There is an old PR that exists however there was not action on it since 2017 so i closed it some time ago here: https://github.com/prebid/prebid-mobile-ios/pull/38

Both the Magnite and Xandr teams are doing research into the above PR. A ticket will be coming when more information is concluded on the research.

**Comment by StarWindMoonCloud** [comment]
@bszekely1 do we have any new ticket created?
Furthermore, about the fact that Facebook SDK is required for rendering, is Facebook SDK still a must for the new solution?
