### ISSUE TITLE
Pass DNT Header into OpenRTB

### ISSUE THREAD

**Issue by curlyblueeagle** [prebid/prebid-server#1372]
Does Prebid Server not read the DNT Header from the client request and set it in ORBT?

**Comment by bretg** [comment]
No, Prebid Server doesn't look for the DNT header. See https://github.com/prebid/prebid-server/issues/1262

Do you have evidence that anyone cares about it anymore? The committee did not think it's really a thing. Modern privacy mechanisms (CCPA, GDPR, LMT, COPPA) are all supported.

**Comment by curlyblueeagle** [comment]
We are surprised to see dnt fields populated in ortb requests to our
exchange from our partners using Prebid Server. And we noticed this is not
supported anywhere in the code. So wanted to check with you to figure out
the discrepancy.

We use DNT in addition to GDPR and CCPA.

**Comment by bretg** [comment]
Do you have any evidence that this flag is valid? The committee's last discussion determined that it's obsolete and not supported on Safari. We would prefer not to implement, test, and document unnecessary privacy flags. Prebid Server is not going to make a dent in the overall problems with DNT. https://www.zdnet.com/article/why-do-not-track-is-worse-than-a-miserable-failure/

**Comment by curlyblueeagle** [comment]
Understood.

We use the DNT signal in addition to US Privacy for CCPA compliance. Our lawyer interpreted the following section in CCPA to mean that we had to support DNT as equivalent to a "do not sell my info" signal from the user. 
> California Consumer Privacy Act Regulations, March 2020, § 999.315. Requests to Opt-Out, a, d and g.

We see 5-10% of requests to our exchange sending us a DNT enabled signal. Given that users are setting this in their browser and passing it to us we feel it prudent to take it into consideration for CCPA compliance as described in the section I referenced above.

**Comment by bretg** [comment]
We'll discuss again in committee with your data and perspective. Thanks.

**Comment by curlyblueeagle** [comment]
Thank you, appreciate it.

**Comment by bretg** [comment]
@curlyblueeagle - we discussed today.

> We are surprised to see dnt fields populated in ortb requests to our
exchange from our partners using Prebid Server. And we noticed this is not
supported anywhere in the code. 

Its true, PBS **doesn't** look for the DNT header and pass it through. Several bidder adapters have logic in this area -- perhaps your adapter does something?

We determined that we'd be fine just reading the DNT header and passing it through device.dnt. We're less comfortable taking enforcement action.

Is that the request?

**Comment by curlyblueeagle** [comment]
@bretg Our adapter doesn't do anything further related to DNT. Not sure even if the adapter has access to anything besides the ORTB struct at that point. 

We will be happy if prebid server just reads and passes DNT via device.dnt. We do not require enforcement action on your part. We will take care of that on our end. Thank you.

**Comment by bretg** [comment]
I've created an internal ticket for PBS-Java. @SyntaxNode, you'll cover PBS-Go?

**Comment by SyntaxNode** [comment]
> I've created an internal ticket for PBS-Java. @SyntaxNode, you'll cover PBS-Go?

Yes. I've an internal ticket for PBS-Go.

**Comment by SyntaxNode** [comment]
This is complete in PBS-Go.

**Comment by bretg** [comment]
Done in PBS-Java.
