### ISSUE TITLE
Two endpoints in config.go for Adtelligent adapter

### ISSUE THREAD

**Issue by AndriyPavlyuk** [prebid/prebid-server#1389]
You have two different endpoints for Adtelligent adapter:

v.SetDefault("adapters.adtelligent.endpoint", "http://hb.adtelligent.com/auction")

v.SetDefault("adapters.adtelligent.endpoint", "http://ghb.adtelligent.com/pbs/ortb")

Looks like a bug.

**Comment by SyntaxNode** [comment]
Agreed. Looks like we mixed a merge conflict. I'll fix it.

**Comment by AndriyPavlyuk** [comment]
Thank you!
