### ISSUE TITLE
TCF1 Global Vendor List fallback feature

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1391]
We discussed in the Prebid Server committee today that the IAB is going to obsolete the TCF1 Global Vendor List (GVL) soon.

If the IAB endpoint starts returning 404 for all TCF1 GVL versions, all Prebid Server requests containing TCF1 consent strings would be anonymized before the auction: user IDs removed and IP address rounded.

The proposal discussed:

1) Allow the host company to optionally add a default TCF1 GVL file. The idea is that this would be the latest version.
2) If this is specified and the TCF1 GVL endpoint returned a 404 for the requested version within the past hour, fallback to the default GVL. Check every hour for the file.
3) If there's no default GVL configured, then anonymize as usual.
4) Log metrics when the fallback occurs so we can track the frequency

**Comment by bretg** [comment]
Here's the potential problem:

1) let's say the last version of the TCF1 GVL is version 220.
2) someone filled out their CMP with reference to version 200.
3) The IAB turns off the TCF1 GVL endpoint

Is it valid to parse a TCF1 string built with reference to GVL v200 against v220? Theoretically a vendor could have changed a Legal Basis or added/removed a Purpose that the User hasn't confirmed.

**Comment by bretg** [comment]
Worked with Magnite and Xandr folks. While not perfect for the reason noted above, this functionality is warranted as an optional feature for Prebid Server hosts due to the concern about real-world pubs not having time to switch fully to TCF2 on the IAB's timelines, this feature offers a softer landing. 

Differences between GVL versions are considered minimal risk: they've been locked for some time, and vendors are ultimately responsible for following the appropriate rules.

**Comment by SyntaxNode** [comment]
Discussed and accepted by Prebid Server Committee.

**Comment by bretg** [comment]
This has been implemented in PBS-Java 1.41

**Comment by SyntaxNode** [comment]
This is implemented in PBS-Go as of 0.124.1.
