### ISSUE TITLE
Make host company GVL ID optional

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1393]
A Prebid Server host company currently must have a GVL ID in order to support setting cookies (Purpose 1) when GDPR is supported and in-scope. If they don’t have a GVL ID, it assumes the user does not consent to the host company setting a cookie on their device

We discussed in committee adding a configuration to disable this check to support first party entities.

Make the GVL ID check optional:
1. If the GVLID is configured, run the checks in /cookie_sync and /setuid. Otherwise skip them.
2. This essentially makes the checks off-by-default.
3. If not specified, log a warning on startup: "gdpr.host-vendor-id not specified -- will skip host company GDPR checks"

**Comment by patmmccann** [comment]
This seems to be coming up in publisher questions, eg https://redditadops.slack.com/archives/C9B6S6QAU/p1606389562094100

**Comment by bretg** [comment]
This will be released in PBS-Java in January.

Would welcome community help for PBS-Go.

**Comment by bsardo** [comment]
I forgot to mention that I'm currently working on this for PBS-Go.

**Comment by muuki88** [comment]
Thanks @patmmccann for pointing this out. And thanks @bsardo for working on this :heart:

**Comment by SyntaxNode** [comment]
This behavior has already been implemented in PBS-Go for some time. Added a warning in PBS-Go 0.140.0 to match the spec.

**Comment by hhhjort** [comment]
It occurs to me there is a possible counter case. A PBS host with little current connection to the EU, but still wants to honor the GDPR, but doesn't want to register a GVL ID. Perhaps someone testing prebid server to ensure it will be worth their while before going to the trouble of setting up a GVL ID. In this case, they should choose a non-zero, unused GVL ID so that they won't cookie GDPR users before they are ready to properly support this feature.

**Comment by bretg** [comment]
Released in PBS-Java 1.52

> Perhaps someone testing prebid server to ensure it will be worth their while before going to the trouble of setting up a GVL ID

@hhhjort - not understanding your observation here. With this feature, host companies have the option to skip setting a GVL ID entirely or if they want, they can set a fake one. Are you suggesting we should document these options for their consideration?

**Comment by hhhjort** [comment]
I am undecided if it needs more documentation than being mentioned here. It is a very corner case, a host that wants to respect GDPR on block themselves from setting cookies when this replies. Was more verifying that all possible configurations are possible, and realizing this one is only covered if you use a non-zero invalid ID.

**Comment by bretg** [comment]
Closing with approval from @hhhjort
