### ISSUE TITLE
How is the Rubicon adapter enabled in prebid-server?

### ISSUE THREAD

**Issue by jxlarrea** [prebid/prebid-server#1405]
Already contacted my account manager and waiting for their info regarding endpoints. In the meantime, I'd like to enable the adapter in prebid-server for testing purposes.

**Comment by bretg** [comment]
You've done the right thing.

The account manager will get approval, then provide the endpoint login info.

**Comment by jxlarrea** [comment]
> You've done the right thing.
> 
> The account manager will get approval, then provide the endpoint login info.

Thank you, but how do I enable it in prebid-server once I get the endpoint info? I assume I'd have to set some environment variables but there's no documentation whatsoever. Could you please point to the right direction?

**Comment by bretg** [comment]
You'll get the instructions from the account team, but it will be something like this:

```
    "adapters": {
        "rubicon": {
            "disabled": false,
            "endpoint": "http://exapi-REGION.rubiconproject.com/a/api/exchange.json?tk_sdc=REGION",
	    "usersync_url": "https://pixel.rubiconproject.com/exchange/sync.php?p=PARTNERCODE&gdpr={{.GDPR}}&gdpr_consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}",
            "XAPI": {
                "Username": "GET_FROM_RUBICON",
                "Password": "****",
                "tracker": "SAME_AS_USERNAME"
            }
        }
    },
```
