### ISSUE TITLE
tests ignore expected message field. When not ignored, tests actually fail. Currently tests pass when they should not.

### ISSUE THREAD

**Issue by draksler** [prebid/prebid-server#1406]
tests in TestBadRequests in auction_test.go (and a few others) are ignoring the expected message field due to the `gr.description != ""` condition. 
If the condition is removed, and the messages are actually validated, the tests fail.

**Comment by SyntaxNode** [comment]
Nice find. I'm looking into this. I don't know why a condition like `gr.description != ""` exists at all.

**Comment by SyntaxNode** [comment]
We're working to fix this. Looks like there are two tests which aren't running and should. The other failures with removing that condition are due to unclear setup. This was probably our first pass at json based tests.

**Comment by SyntaxNode** [comment]
The test setup in that package is a mix of json and code configuration. It's really difficult to follow. @guscarreon has rewritten them in a much cleaner style with all setup expressed in the json files, as we do for other parts of the code. I'll close this ticket when https://github.com/prebid/prebid-server/pull/1450 is merged.

**Comment by SyntaxNode** [comment]
The test setup in that package is a mix of json and code configuration. It's really difficult to follow. @guscarreon has rewritten them in a much cleaner style with all setup expressed in the json files, as we do for other parts of the code. I'll close this ticket when

**Comment by SyntaxNode** [comment]
`auction_test.go` has been completely refactored to resolve this issue.
