### ISSUE TITLE
Mitigate race conditions in Adapters

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#141]
In this project's short lifetime, we've already started to see how easy it is to introduce race conditions (#122, #140).

This is a problem, because:
1. The project has no automated way to catch them. Only code review & comments.
2. Adapters are run in their own goroutine, so segfaults crash the entire process.

Programmers make mistakes, and anything which isn't caught automatically will happen in the future. As this project becomes more active, this will become a bigger issue.

There are a few options for how we can mitigate these issues.
1. Copy every object we send into the Adapters' goroutines, so that data races aren't possible.
2. Add "good adapter citizen" tests which run on _all_ adapters, and make sure they don't mutate shared state.
3. Change the Types we send into `Adapter.Call()` so that adapters _can't_ mutate things they're not allowed to. For example, make the PBSRequest state private and expose methods which only return immutable data.

Anyone have preferences, or other ideas?

**Comment by mkendall07** [comment]
I like option 3. Although 2 is probably also a good idea. 1 seems a bit heavy handed. That's all I got. no new ideas.

**Comment by dbemiller** [comment]
There's also some overlap here with #150.

If the PBS external API changes to accept openRTB requests, then the `pbsrequest` type will go away, and the adapter API will _have_ to change.

**Comment by dbemiller** [comment]
#356 should (I hope) make Travis catch many of these. If we still find that we're running into problems, we can look into ways to improve the design farther.
