### ISSUE TITLE
OMSDK signaling support

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#1415]
## Type of issue

The Open Measurement Software Development Kit (OM SDK) is designed to facilitate third party viewability and verification measurement for ads served to mobile app environments without requiring multiple Ad Verification Service Providers (Measurement Provider) Software Development Kits (SDKs). As more DSPs and Publishers are seeking to enable transactions with OMSDK support to allow a seamless integration with viewability and brand safety partners, allowing publishers to signal the OM parameters is becoming more relevant. 

OM SDK is developed and managed by the Open Measurement Working Group (OMWG).

For more information about the OMSDK and the OMWG: https://iabtechlab.com/omsdk

## Goals

* Extended the OpenRTB Source extension to support two new Open measurement signals
* Pass the above new signals to Bid Adapters

## Proposed Design

Open Measurement contains three optional fields, one of which is already supported in OpenRTB, called `api` in the `imp[ ].banner` object. The value passed in this field to express OM is a new addition, value 7. For Bid Adapters who are not able to read value 7 should gracefully be able to ignore it.

Bid requests will include two new fields to identify the partner integration. OpenRTB 2.x and 3.0 will carry these fields in different objects, but the field names and types are the same in both protocols. Given Prebid Server supports OpenRTB 2.x, there is no desire at the moment to support the 3.x location. 

OM signals can be sent directly in the ad request JSON object or signaled in a stored request.

### Fields

Attribute | Type | Description
-- | -- | --
omidpn | string | Identifier of the OM SDK integration. This is the same as the "name" parameter of the OMID Partner object.
omidpv | string | Version of the OM SDK integration. This is the same as the "versionString" parameter of the OMID Partner object.

### OpenRTB 2.x Location
The two above fields will be added to an extension object within the bid request. There are several options for the extension object to use. This section lists three possibilities for full OMSDK signaling

BidRequest.Source.Ext
The object BidRequest.Source describes the source of the OpenRTB 2.x bid request. Adding "omidpn" and 'omidpv' to Source.Ext would be appropriate if certification applies to all placements in the bid request.

```
"source" {  
  "ext": {  
    "omidpn": "MyIntegrationPartner",  
    "omidpv": "7.1"  
   }  
},  
"imp" [{  
  "banner": {  
    "api": [7]  
  }  
}] 
```

### Out of Scope

* Native will be out of scope for now until further research is performed
* Bid Response api object

### Prebid SDK Changes
Prebid SDK will need two new items added in the request payload or use PBS stored requests.

**Comment by SyntaxNode** [comment]
PBS makes most of the information in the OpenRTB request directly available to adapters. It will only remove information intended for other adapters or information that is invalid and considered a warning instead of an error, such as malformed CCPA consent strings and private IP addresses.

Many bidders accept OpenRTB 2.5 requests and their adapter pass on the request as-is with some additional information. I can confirm this is at least the case for the AppNexus/Xandr adapter.

No action is needed within Prebid Server.


will add information or enforce extra validation. There

**Comment by bszekely1** [comment]
I was able to confirm on the Java side as well. Closing this issue. Thanks for the follow up.
