### ISSUE TITLE
win rate

### ISSUE THREAD

**Issue by StarWindMoonCloud** [prebid/prebid-server#1416]
win rate is an important metric for bidder performance evaluation. 
There are two types of win rate, one is among the prebid server bidders, let's say prebid server win rate; the other is the ad server win rate (or final win rate)

For prebid server win rate, one can implement a similar function as RecordAdapterRequest after winningBids (e.g. RecordAdapterWinner), at least doable
For ad server win rate, probably need external analytics, but couldn't find a good one, there are some for prebid JS though http://prebid.org/overview/analytics.html

Not sure this has ever been discussed, would like to have an issue for suggestions or maybe feature request

**Comment by bretg** [comment]
@StarWindMoonCloud - I think this request is already covered by the analytics interface. https://dev.prebid.org/prebid-server/developers/pbs-build-an-analytics-adapter.html

Note that 'ad server win rate' would require the 'events' feature that's implemented in PBS-Java, but not PBS-Go.

**Comment by bretg** [comment]
Am demoting this to a question as I believe the feature already exists.

@danielguedesb has offered to look into porting the event system from PBS-Java to PBS-Go

**Comment by SyntaxNode** [comment]
@danielguedesb has opened PR https://github.com/prebid/prebid-server/pull/1467 to add auction callback events to PBS-Go. That feature is being tracked by issue https://github.com/prebid/prebid-server/issues/1015.

Have we answered your question?

**Comment by SyntaxNode** [comment]
The PR from @danielguedesb to support events in PBS-Go has merged. The feature is available starting in 0.132.0. I'm not sure there's full feature parity yet, but we'll continue to keep track on https://github.com/prebid/prebid-server/issues/1015.
