### ISSUE TITLE
User-sync with AMP pages

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/prebid-server#1423]
Hi everyone!

Can someone tell me how the user-sync mechanism works in an AMP environment?

Context:
I am debugging the page https://www.casaegiardino.it/consigli/fornetto-ad-aria-come-scegliere-i-modelli-migliori-in-commercio.php/amp where we are connected as a PBS bidder via prebid.adnxs.com/pbs/v1/openrtb2/amp

According to http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#user-sync the publisher must set the iframe like
```
<amp-iframe width="1" title="User Sync"
  height="1"
  sandbox="allow-scripts"
  frameborder="0"
  src="https://PROVIDED_BY_APPNEXUS/load-cookie.html?endpoint=appnexus&max_sync_count=5">
  <amp-img layout="fill" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" placeholder></amp-img>
</amp-iframe> 
```

And then what happens? I guess the mechanism described in http://prebid.org/prebid-server/developers/cookie-syncs.html is the same for AMP. But in that case I would see my bidder user-sync endpoint being called in the network panel of the page (https://ssbsync.smartadserver.com/api/sync). The thing is ... I don't see anything.

Thank you for shedding some light here!

**Comment by bretg** [comment]
Note that there are over 70 adapters supported in Prebid Server, now with a max_sync_count of 5, you're only going to see 5 at a time -- any given bidder (e.g. smartadserver) may take a few page reloads to see.

There's not currently a way to prioritize a given bidder's sync, but that's a good idea. Happy to take a PR at https://github.com/prebid/prebid-universal-creative/blob/master/src/cookieSync.js

FWIW, I drafted some additional cookie-sync docs at https://dev.prebid.org/prebid-server/developers/pbs-cookie-sync.html

**Comment by mlapeyre3** [comment]
Hey @bretg thank you for the detailed answer !
I will follow-up https://github.com/prebid/prebid-universal-creative/issues/113 then and I close this issue :)
