### ISSUE TITLE
Request publisher ID value 

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#1425]
Hi Prebid Team,

Currently we are working to integrate the publisher DailyMail to Brightroll.
Can you please let us know what will be the publisher_id value going to pass in dailymail bid request 
I mean the site.publisher.id field in OpenRTB bid request for Dailymail bid requests. 

Thanks
Smitha

**Comment by SyntaxNode** [comment]
Hi Smitha,

This is really a question for Brightroll and not one that we as the Prebid Server project team can answer.

Brightroll lists `dsp-supply-prebid@verizonmedia.com` as their contact information for their adapter. Please email them directly for questions about how to onboard publishers.

Thank You
