### ISSUE TITLE
Integration Type and Channel

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1428]
Our hosted Prebid Server has been getting more complicated with events, analytics, special cases, and additional business models. We'd like to propose some changes to support distinguishing between various traffic sources and business arrangements.

# Integration Type

In support of analytics and billing, Rubicon's fork of PBS-Java supports a concept called "integration type". It's a host-company-specific set of values used to indicate the source of the request, which is turn is used in events and billing calculations. For example, we use one value for our "fully managed service" offering, and other value for our "hosted service" offering, which have different financial characteristics.

Example use cases:
- host company getting PBS traffic from their own managed PBJS: "mpbjs" (managed)
- host company getting PBS traffic from their a publisher-managed PBJS: "shpbjs" (self-hosted)
- host company getting PBS traffic from a 3rd-party managed PBJS: "3pbjs"

We'd like to take this feature out of our private fork and formalize it with the community. Here's what it impacts:

1) Account configuration can define a default `integration` 
2) OpenRTB requests can contain `ext.prebid.integration`. Allowed values are dependent on the host company.
3) The `integration` value is added to event URLs generated by Prebid Server and is available to analytics adapters.

# Channel

Also in support of analytics, we'd like to formalize a value that defines how the request came in. It's not used by PBS-core, but is available to analytics adapters. Valid values could vary by host company, but for example:

- pbjs
- app
- amp
- s2s

Proposal:

1. Channel is an object that contains a name (required) and a version (optional)
2. Update the PBJS pbsBidAdapter to pass ext.prebid.channel: {name: "pbjs", version: "4.1"} unless overridden by s2sConfig.extPrebid
3. PBS gets the channel name out of the request if it's there
4. If the channel isn't present:
    4a. set channel name to 'amp' if the request came in on /openrtb2/amp
    4b. set channel name to 'app' if the request contains an 'app' object
    4c. otherwise leave channel blank. Analytics adapters can default if they'd like.

**Comment by albertmolinermrf** [comment]
Would it be possible to make the proposal the default behaviour, but allow the ability to:

1. Skip the addition from Prebid.js (i.e., not pass anything at all).
1. Pass any channel name from Prebid.js.

**Comment by bretg** [comment]
@albertmolinermrf - I think we can cover both of your requests in one go -- s2sConfig supports 'extPrebid' which corresponds to the ext.prebid portion of the OpenRTB -- the pbsBidAdapter should check to see if someone already set extPrebid.channel -- if so, don't change it.

1. extPrebid.channel: {}
2. extPrebid.channel: {name: "whatever"}

**Comment by bretg** [comment]
Done in PBS-Java 1.43

**Comment by AlexBVolcy** [comment]
@bretg I am working on this issue now for PBS Go, and I had a question regarding the proposal for Channel. Here's the section I have a question on:

If the channel isn't present:
4a. set channel name to 'amp' if the request came in on /openrtb2/amp
4b. set channel name to 'app' if the request contains an 'app' object
4c. otherwise leave channel blank. Analytics adapters can default if they'd like. 

The question I have with the above is that the Channel type can be configured by the host, and if that's the case, how can we know for bullets 4a/4b that the host allowed 'amp' and 'app' to be channel types? Thanks!

**Comment by AlexBVolcy** [comment]
@bretg 

And a follow up question I have is that there is some integration type terminology used for account level CCPA and GDPR config and I was just wondering if this terminology is just a coincidence and is referring to a different concept than what is being mentioned in this issue? 

And do we still want to use the same terminology for this issue, or will that cause some confusion to have the phrase Integration Type be used in multiple places? 

Thanks!

**Comment by bretg** [comment]
> Channel type can be configured by the host, and if that's the case, how can we know for bullets 4a/4b that the host allowed 'amp' and 'app' to be channel types?

If think you're refering to the statement "Valid values could vary by host company"? 

This just means that if the host company has non-standard values, they need to tell their clients what they are and how to pass them. The defaults supported by PBS are amp and app, but if the client (or stored request) specifies a value, these defaults won't come into play.

> integration type terminology used for account level CCPA and GDPR config

Yup, this is why 'integration' exists!  We had several pubs, for instance, that wanted to turn off GDPR processing for AMP because AMP CMPs were non-existent for a long time.

**Comment by bretg** [comment]
For the record, Mansi noticed an inconsistency in the implementation:

> Account configuration can define a default integration and **whether or not it can be overridden at the request level**

I've removed the bolded clause from above. This is minor feature that could be added later if needed

**Comment by AlexBVolcy** [comment]
This feature was implemented here https://github.com/prebid/prebid-server/pull/2037 and here https://github.com/prebid/prebid-server/pull/2111

These features were merged in PBS Go 0.186.0 and 0.197.0
