### ISSUE TITLE
Proposal: Built In Adapter Aliases

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#1429]
This proposal is to include built-in adapter aliases in Prebid Server.

### What We Have Today
Hosts may currently configure adapter aliases using the default request feature. There are two limitations with this approach:

1. There is no "default" default request in the open source repository. If a publisher wants their alias to be included, they'll need to reach out to each host individually and ask for that configuration. To add further complication, we don't have a list of known hosts to provide to publishers as a starting point.

2. Aliases currently use the exact same code and configuration. If there is a specialized url to use for the alias, there's no way for a host to configure that using a default request.

We've seen a few new adapter requests which copies/pastes the original adapter to form an alias. This isn't ideal since it creates more code to maintain or (perhaps more realistically) to be forgotten about when there are updates made to the "core" adapter. We need to provide a better path forward.

### Out Of Scope
Publishers may configure adapter aliases today within their OpenRTB request for each auction or configure aliases within their stored requests. This behavior will be unaffected by this proposal.

### Proposal
Introduce enhanced adapter alias support such that aliases are part of the code. While it makes sense for aliases to inherit the configuration from the "core" adapter, we should add the ability to override some or all of the config. This would allow aliases to use a different endpoint url, a different user sync cookie, or restrict the supported auction types (app, site, banner, video, etc...).

An adapter alias would be defined in the hardcoded default configuration in `config/config.go` as follows:
```
v.SetDefault("adapters.alias.endpoint", "http://foo.com/openrtb")
v.SetDefault("adapters.alias.aliasOf", "appnexus")
```

This allows the alias to be treated the same as any other adapter from a configuration standpoint. The adapter alias may not be removed by a host (just like a "core" adapter), but may be disabled through the config either using environment variables or a yaml file.

The adapter alias would be present in the `/info` calls almost exactly as default request aliases do today, except that the info may be overwritten with configuration along the lines of:
```
v.SetDefault("adapters.alias.maintainer.email", "foo@bar.com")
v.SetDefault("adapters.alias.maintainer.capabilities.app", "banner, site")
```
Prebid Server will enforce that capabilities from the "core" adapter may be restricted, but not expanded. If the adapter is written to not support `site` requests, as an example, then an alias can't magically decide to change that. However, if a "core" adapter supports `native` ads and the alias doesn't want to for some reason, it has the ability to remove that capability.

Adapter construction logic would need to change to accomodate n-number of aliases, where each alias is its own instance created from its own config. I don't believe this would be a problem as no (very few?) adapters keep static state. I'm thinking of a new `Registerer` interface adapter packages would provide to wrap the calls we have today in `newAdapterMap`. Something like:
```
package router

type Registerer interface {
    Register(string, config.Adapter)
}

registrars := map[openrtb_ext.BidderName]adapters.Registerer{
    openrtb_ext.BidderAppnexus: &appnexus.Registerer{}

...

package appnexus

type Registerer struct {}
func (Registerer) Register(bidderName string, config config.Adatper) {
    return NewAppNexusAdapter(config.Endpoint, config.PlatformID)
}
```

We would implement this new pattern for all adapters as part of this work. Perhaps it's even better in some cases to refactor the existing `NewXXAdapter` methods into the `Registerer` interface.

A similar approach will be taken with `NewXXSyncer` methods, although I'm unsure if we need to allow for aliases to define their own GDPR vendor ids.

### Pleasant Side Effects

We've had a few discussions about supporting a generic OpenRTB adapter and this approach would enable that use case. Prebid Server is *not* a proxy, so this isn't a feature publishers would use. If an adapter is literally just forwarding the OpenRTB request and response, it may make more sense to be an alias of a new generic `openrtb` adapter. Hosts may also configure their own generic adapter aliases to perhaps forward to other services.

**Comment by albertmolinermrf** [comment]
I suffer some level of confusion about the implications of the word "alias". Please correct if the following is wrong.

The same concept is going to apply in these cases:

1. A bidder that does not support multisize placements (e.g. Pubmatic more than a year ago) needs one object per placement with a distinct name in `imp.ext` of the bid request. Names are then aliased in `ext.prebid.aliases`. Let's call this business alias.
1. A bidder that uses another bidder's platform (e.g. DistrictM with Appnexus') shares not only the code of the adapter but its configuration as well. Let's call this platform alias.
1. Two bidders that use the same software but different infrastructure share the adapter code but not their configuration. Let's call this software alias.

When metrics are generated (perhaps only in Prebid Server Java and not Prebid Server Go, I don't know; sorry if I'm pulling the subject out of its general scope), aliases are resolved in order to join all stats of bidders regardless of the name used in the bid request. If this happens for all the types of aliases described above, the metrics of two bidders with a software alias are going to be mixed, which does not seem reasonable.

In fact, as metrics can be used to detect malfunctions by means of alarms, to me the ideal generation should allow to:

- Join all the metrics of business aliases.
- Separate all the metrics of software aliases.
- Join some metrics (those that describe interactions with the platform, like the response time or the amount of timeouts) and separate some others (those that describe interactions with the business, like the bids received or the prices) of platform aliases.

**Comment by bretg** [comment]
Good call out @albertmolinermrf 

Adding metadata about what "type" an alias is carries extra complexity and documentation. How about we recognize "request aliases" (defined in ext.prebid.aliases) and "configured aliases" (defined in server config files). For metrics, we would resolve "request aliases" to the base bidder code, but leave "configured aliases" alone.

> Join some metrics

If you're willing to split out which metric gets what treatment, we can look over the list. I suspect that PBS-Go and -Java have diverged somewhat on operational metrics -- would be nice to get a handle on the diffs.

**Comment by albertmolinermrf** [comment]
> If you're willing to split out which metric gets what treatment, we can look over the list. I suspect that PBS-Go and -Java have diverged somewhat on operational metrics -- would be nice to get a handle on the diffs.

This is the behaviour **I believe** applies to metrics generated upon bid requests in Prebid Server Java 1.40.0:
-  `adapter.<bidder-name>.(openrtb2-web|openrtb-app|amp|legacy).tcf.<metric-name>` are not resolved.
- All the other `adapter.<bidder-name>.*` are resolved  with the aliases configured in YAML files, using `UNKNOWN` as `<bidder-name>` if the alias is not declared there (even for "request aliases").

You proposal for metrics to resolve "request aliases" automatically and keep "configured aliases" separate seems to me a good trade-off between functionality and effort.

Just for the record, though, I find it could make sense if these metrics got aggregated for different bidders sharing the same platform:
- `adapter.<bidder-name>.request_time`
- `adapter.<bidder-name>.requests.badinput`
- `adapter.<bidder-name>.requests.badserverresponse`
- `adapter.<bidder-name>.requests.timeout`
- `adapter.<bidder-name>.requests.unknown_error`

These should be not be aggregated for different bidders even if they share the same platform:
- `adapter.<bidder-name>.no_cookie_requests`
- `adapter.<bidder-name>.prices`
- `adapter.<bidder-name>.bids_received`
- `adapter.<bidder-name>.(banner|video|audio|native).adm_bids_received`
- `adapter.<bidder-name>.(banner|video|audio|native).nurl_bids_received`
- `adapter.<bidder-name>.requests.type.(openrtb2-web|openrtb-app|amp|legacy)`
- `adapter.<bidder-name>.requests.gotbids`
- `adapter.<bidder-name>.requests.nobid`
- `adapter.<bidder-name>.(openrtb2-web|openrtb-app|amp|legacy).tcf.userid_removed`
- `adapter.<bidder-name>.(openrtb2-web|openrtb-app|amp|legacy).tcf.geo_masked`
- `adapter.<bidder-name>.(openrtb2-web|openrtb-app|amp|legacy).tcf.request_blocked`
- `adapter.<bidder-name>.(openrtb2-web|openrtb-app|amp|legacy).tcf.analytics_blocked`

**Comment by bretg** [comment]
Also, I propose that the /info/bidders endpoint be modified to show built-in aliases as well

**Comment by SyntaxNode** [comment]
> Also, I propose that the /info/bidders endpoint be modified to show built-in aliases as well

This is already supported by PBS-Go today for aliases defined in the default request. They include an "aliasOf" field. I agree to keep that behavior and include it in the spec.
