### ISSUE TITLE
Deal Support : What is the purpose of using `winningBidsByBidder`  in case of  exchange.applyDealSupport

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#1442]
1. As `winningBidsByBidder` holds the winning bids by a bidder for the given impression.
2. Here, I would like to understand the scenario/sample bid request  where we can get multiple bids from the same bidder for the same impression
3. In case of long-form video, how we can reproduce this scenario where we can get multiple bids from the same bidder for the same impression

Another question
4. As we are using `winningBidsByBidder` in case of deal support, what will happen in the following case?

  `
   Imp3 -> Bid31 <- P1 (val = 3)  (Deal)
`
`
   Imp3 -> Bid32 <- P1 (val = 4)  (non-deal)
 `

- `Imp3` got 2 bids `Bid31` and `Bid32` from same partner `P1`. 
- `Bid31` is associated with `Deal` with price = 3
- `Bid32` is normal  non-deal Bid with price = 4 
- As per `winningBidsByBidder` logic, auction will select `Bid32`. Because `Bid32` price is higher than `Bid31`
- In this case we will not be consider deal associated `Bid31` 

Should we consider this deal?

**Comment by camrice** [comment]
@ShriprasadM Sorry this issue was missed. Right now, the deal support does not include prioritizing deals, so this case would be missed if the deal bid does not win the impression slot. I will raise this to the team to create a plan to resolve this.

**Comment by camrice** [comment]
Hi @ShriprasadM, the team was wondering if the `preferDeals` flag in the request resolves the issue you raised here.
https://github.com/prebid/prebid-server/pull/1528

**Comment by ShriprasadM** [comment]
Thanks, @camrice  for an update. I think the `preferDeals` parameter will handle this scenario. 

I can see this was merged after my question. Hence, I was not able to catch it
