### ISSUE TITLE
Deal Support :  response.seatbid[i].bid.dealPriority; Is it standard oRTB response 

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#1445]
1. As per the implementation added in https://github.com/prebid/prebid-server/pull/1183/files , `adapters/bidder.go` 
2. It is mentioned in the comment that for  `dealPriority ` - 
_TypedBid.DealPriority will become "response.seatbid[i].bid.dealPriority" in the final OpenRTB response._
3. Can someone point to oRTB specification, where the "response.seatbid[i].bid.dealPriority" is mentioned as standarized parameter ?

**Comment by SyntaxNode** [comment]
@camrice Can you please address this question?

**Comment by camrice** [comment]
Hi @ShriprasadM, thank you for pointing this out. The comment for the `DealPriority` field is incorrect and should be updated. It is not a standard OpenRTB field for bids nor is it returned in the final response. It is only used internally to Prebid Server for the deal prefixes. I will update the comment to make it accurate.

**Comment by ShriprasadM** [comment]
Thank you @camrice

**Comment by SyntaxNode** [comment]
@camrice @ShriprasadM Can this issue been closed? Has it been fully addressed?

**Comment by ShriprasadM** [comment]
@SyntaxNode Yes we can close this issue
