### ISSUE TITLE
Major protocol change -- move bidders to imp[].ext.prebid.bidder

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1478]
The Prebid Server Committee proposes fixing a design flaw from the original Prebid Server:

Request bidder data is currently in **imp[].ext.BIDDER**. This makes bidder code validations difficult because there may be other attributes in imp[].ext

We propose beginning to shift bidder data to **imp[].ext.prebid.bidder.BIDDER**. PBS-Go already supports this. Once PBS-Java supports it, we would do the following:

1) update PBJS's pbsBidAdapter to place bidder data in the revised location
2) update documentation for storedrequests and storedresponses so host companies start placing the bidder data in the revised location
3) wait a year and see whether there's stomach to start warning about the original location 
4) wait another year and consider dropping the original location. It will probably take at least that long for people to get off older versions of PBJS.

**Comment by SyntaxNode** [comment]
For now, I opened https://github.com/prebid/prebid-server/pull/1479 to add a special case in PBS-Go for parsing imp[].ext.context for the first party data feature and not as a bidder. As a consequence, PBS-Go does will not allow 'context' as a bidder/adapter name.

**Comment by laurb9** [comment]
Our mobile team also pointed out the proposed new ext `imp[].ext.skadn` which, if approved, will need similar treatment. https://github.com/InteractiveAdvertisingBureau/openrtb/blob/c1cec6089b880e5c76c2d9647367a526e4f7d747/extensions/community_extensions/skadnetwork.md

**Comment by bretg** [comment]
This has been done in PBS-Java now. We'll wait a couple of months and then update the PBJS PBS bidadapter to make use of it.

**Comment by SyntaxNode** [comment]
Discussed in the Prebid Server Committee we will be changing the PBJS side to use the new location starting in version 7.0.

**Comment by bretg** [comment]
Discussed in committee. We'll leave this issue open until the debug/warning/error messages are updated in both platforms.

**Comment by bretg** [comment]
This warning doesn't exist in PBS-Java. Closing.
