### ISSUE TITLE
Analytics Interface: Request is null for amp

### ISSUE THREAD

**Issue by Hamper** [prebid/prebid-server#1480]
I use filesystem logs, but for amp endpoint `Request` object is always null.
```js
{
    "type": "/openrtb2/amp",
    "Status": 200,
    ...
    "Request": null,
    "AuctionResponse": {
        ...
    },
    "AmpTargetingValues": {},
    "Origin": ""
}
```

**Comment by bretg** [comment]
Need more detail @Hamper. 

Please make sure you understand how Prebid+AMP works -- https://docs.prebid.org/prebid-server/use-cases/pbs-amp.html

1. You need to pass a [stored request ID](https://docs.prebid.org/prebid-server/features/pbs-storedreqs.html) on the `tag_id` parameter
2. This ID needs to exist as a stored request on your server
3. You can request extra debugging in the /openrtb2/amp interface by adding `&debug=1` to the query string

If this doesn't help, please provide a test /openrtb2/amp request that's not working along with the definition of the matching stored request ID on your server.

**Comment by Hamper** [comment]
AMP endpoint works, this question is about analytics module. If I enable filesystem logic (`PBS_ANALYTICS_FILE_FILENAME="/test.log"`) Request object in log file always nil even if AuctionResponse have valid bid, and no any other fields with data like user-agent, ip (like data in Device field of ordinary bid request).

**Comment by bretg** [comment]
@SyntaxNode - do you have evidence that analytics adapters in PBS-Go receive AMP requests?

**Comment by SyntaxNode** [comment]
I don't personally use the PBS-Go analytics package. It seems like something isn't wired properly. I'll take a look.
