### ISSUE TITLE
Question: Video Support for Prebid Server

### ISSUE THREAD

**Issue by curlyblueeagle** [prebid/prebid-server#1487]
Hello, I am seeing contradictory docs about support for video. According to this page https://docs.prebid.org/formats/video.html only Prebid.js supports video and not Prebid Server. Can someone please confirm that Prebid Server does support video?

**Comment by SyntaxNode** [comment]
That's a very outdated comment. Prebid Server supports video. Are you looking for outstream or instream using SSAIs?

**Comment by curlyblueeagle** [comment]
Ah gotcha. We are looking to support both instream and outstream. Is that possible in Prebid Server?

**Comment by SyntaxNode** [comment]
Sure is!

Outstream auctions are run through the `/openrtb2/auction`. There are some video examples at the endpoint doc: 
https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html

Instream auctions are done through a specialized endpoint designed for SSAI integration. Take a look at this doc: https://docs.prebid.org/prebid-server/use-cases/pbs-lfv.html

**Comment by bretg** [comment]
"Short form" (e.g. pre-roll) instream video is supported by the /openrtb2/auction endpoint as described in the 2nd diagram here -- https://docs.prebid.org/prebid-server/use-cases/pbs-pbjs.html

The "long form" video support is about ad pods.

Thanks for pointing out the old doc -- will get that updated.

**Comment by bretg** [comment]
Doc updated. Can we close this @curlyblueeagle ?

**Comment by curlyblueeagle** [comment]
Yes you may close this. Thank you.
