### ISSUE TITLE
Appnexus keywords params Not consistent with client side

### ISSUE THREAD

**Issue by ghost** [prebid/prebid-server#1499]
This isn't necessarily a bug but would be nice to have the same format for params that client-side uses. Currently server-side requires it to be an array while the client-side does not.

**Comment by SyntaxNode** [comment]
The AppNexus `keywords` parameter accepts an array to match Prebid.JS as of PBS-Go 0.255.0..

We've match all other parameters as closely as we can between JS and Server. We can't achieve perfect parity because the data models are different.
