### ISSUE TITLE
Create Auction endpoints which are OpenRTB-compliant

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#150]
The `/auction` endpoint accepts JSON in a custom data structure.

But usually, it's a good idea to follow standards unless there's really good reason to do otherwise.  There's the current [OpenRTB 2.5](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf) spec, as well as an [OpenRTB 3.0](https://iabtechlab.com/wp-content/uploads/2017/09/OpenRTB-3.0-Draft-Framework-for-Public-Comment.pdf) one coming soon-ish.

Would anyone object if we versioned the endpoint and began to follow the standard?

**Comment by mkendall07** [comment]
@anwzhang @nhedley for comment

**Comment by mkendall07** [comment]
@pdezwart as well

**Comment by nhedley** [comment]
Chatted with @dbemiller briefly offline about this. Given that we can put all the custom mobile parameters (ex. `cache_markup`, `sort_bids`, `max_key_length`) in the `ext` field on the request and we can add impression specific custom fields to another `ext` field for stuff like `config_id`, it seems like a reasonable change to me. 

Would definitely be helpful to see what the new request might look like. Additionally the versioning is definitely necessary from a mobile standpoint (I'm not sure when we'd be able swap over completely since its a breaking change).

**Comment by dbemiller** [comment]
Gist with ideas for the PBSRequest => openRTB transition is [here](https://gist.github.com/dbemiller/68aa3387189fa17d3addfb9818dd4d97). I haven't been through the openrtb response spec yet... but figured I'd post this now to get feedback on the request side.

The biggest issue I see is the format of the configs. Since they're saved in the database, I'd need to think more carefully about how we migrate them.

**Comment by hhhjort** [comment]
Limiting bids per ad unit ... wouldn't it be possible by having a config that didn't assign a placement_id or the bidder's equivalent for that particular bidder? The bidder extensions live inside the impression object, which should correspond one-to-one with an AdUnit if I understand things properly.

**Comment by dbemiller** [comment]
We actually talked about since my last comment... I haven't posted an update here. A reasonable compromise is to make a small break from the spec:

>  At most, only one of wseat and bseat should be used in the same request. Omission of both implies no seat restrictions.

In PBS, we could interpret "omission of both" to mean:

> If imp.ext[bidderCode] exists, then they are allowed to bid.

This is probably ok because the `wseat` and `bseat` in the OpenRTB spec really has _two_ ways to say "no seat restrictions." The other one is `bseat: []`.

So... if publishers really want "no seat restrictions," they could use an empty `bseat` array that instead.

**Comment by dbemiller** [comment]
These exist now... implemented in #196.

Bugs can be filed as new issues. Any enhancements known in the near future is logged under "OpenRTB Support" issues.
