### ISSUE TITLE
LFV: Introduce deal priority and if deal tier satisfied information in prebid's oRTB response bid extension 

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#1503]
As we have recently closed the https://github.com/prebid/prebid-server/issues/1445 with Documentation comment update.
I can see that in actual PBS response deal priority is not  coming inside `response.seatbid[i].bid.ext.dealpriority` 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/9314645/93455430-f76ecb80-f8f9-11ea-82a2-f3d315ce0d9f.png">

Can we build the workflow such that 

1. we can get deal priority  in `response.seatbid[i].bid[j].ext.prebid.dealpriority`  (int value)
2. if bid satisfied the deal tier in `response.seatbid[i].bid[j].ext.prebid.dealTierSatisfied` (true/false)

Sample response will look like 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/9314645/93462026-43723e00-f903-11ea-8530-60b7203affba.png">

**Comment by ShriprasadM** [comment]
Any updates on this ?

**Comment by ShriprasadM** [comment]
@SyntaxNode  / @camrice  : Can you update on this ?

**Comment by SyntaxNode** [comment]
@ShriprasadM We'll look at this soon. Thank you for the detailed documentation.

**Comment by ShriprasadM** [comment]
Thank you @SyntaxNode  for an update

**Comment by camrice** [comment]
We began tracking this internally. These fields are definitely useful to add. I tested out an initial implementation as well. I will tag this when a PR is created.

**Comment by ShriprasadM** [comment]
Thanks, @camrice for update

**Comment by camrice** [comment]
@ShriprasadM Yeah that would be great! Thank you for that. Feel free to open the PR when possible.

**Comment by ShriprasadM** [comment]
@camrice / @SyntaxNode : Added required change in https://github.com/prebid/prebid-server/pull/1558. Please review and merge.

**Comment by ShriprasadM** [comment]
@camrice / @SyntaxNode / @bsardo : I think we can close this issue now
