### ISSUE TITLE
Question: Prebid server video duration

### ISSUE THREAD

**Issue by neririchter** [prebid/prebid-server#1508]
I have a question,
I have noticed that prebid receive a request then split it to several imp base on the pod duration and the DurationRangeSec list

for example an DurationRangeSec: [15, 30]
and the AdPodDurationSec is : 2m

prebid will send a request to all adapters with 15s request duration, but then when the VAST that returns is 14s duration, prebid still says in the response:

    "adPods": [
        {
            "podid": 1,
            "targeting": [
                {
                    "hb_pb": "20.00",
                    "hb_pb_cat_dur": "20.00_15s",
                    "hb_cache_id": "3353b88c-d831-4caf-90a4-4623335adee2"
                }
            ],
            "errors": null
        }

but the duration is 14 seconds in the VAST inside the cache and not 15 seconds as prebid saying, is there any reason for that? is it because of the integration with FW and DFP? or should we implement a fix in the duration result to show the "real" VAST duration?

Thanks

**Comment by bretg** [comment]
Changed the title to video duration since this seems to be about video length, not how long it's cached in PBC

**Comment by neririchter** [comment]
is there any updates if this is the expected behavior?

**Comment by SyntaxNode** [comment]
@neririchter I've escalated this question to our video team.

**Comment by camrice** [comment]
For this `DurationRangeSec`, this is used for `hb_pb_cat_dur` and providing a min/max for accepted durations. Rounding the creative duration for the `hb_pb_cat_dur` generation helps with de-duplicating bids. So the behavior is as expected where the creative in the cache should not have any modification to the duration, but the key duration should be rounded. This is also in the documentation for the Video endpoint here:

https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-video.html#pod-duration-range

> Using the values above, a ten second bid would be rounded to 15 seconds and an eighteen second bid would be rounded to 30 seconds.

It is possible to add more values to `DurationRangeSec` to get more granular values for `hb_pb_cat_dur`, but this is not ideal. I will raise discussion to see if it's possible to add a feature where the creative duration is used in the key if it is accepted by the `DurationRangeSec` check.

**Comment by camrice** [comment]
Apologies for the long delay. After discussion, it seems we are not looking to add the true creative duration to the key value. The main reason that the duration in the keys is rounded is due to integration with Freewheel and DFP. Rounding the duration here allows for less objects to be created on the ad server by using duration buckets instead. In this case, it is ideal to use the DurationRangeSec to add more possible duration values to the key generation.

**Comment by neririchter** [comment]
thanks, @camrice for the explanation.

**Comment by camrice** [comment]
No problem!
