### ISSUE TITLE
auction endpoint and native imp

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1517]
Hi,

I am trying to use the auction endpoint to run a prebid-server native call. But I am facing an issue interpreting the response. Indeed, the documentation (https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#native-request) says :
`the assets object’s id field must not be defined`
Ok, fine, so I don't add them in my request. Here is the native part of my openrtb request : 
`native : {
	request: "{"assets": [{"required": 1, "title": {"len": 80}}, {"required": 1, "data": {"type": 2}}, {"required": 0, "img": {"type": 3, "w": 150, "h": 50}}, {"required": 0, "img": {"type": 1, "w": 150, "h": 50}}, {"required": 0, "data": {"type": 1}}], "context": 1, "plcmttype": 1, "eventtrackers": [{"event": 1, "methods": [1]}]}"
	ver: "1.2"
}`

Then I receive my response from prebid-server (I removed the tracking url to make it readable) :
`adm: "{"ver":"1.2","assets":[{"id":0,"title":{"text":"Nintendo Ultra 64"}},{"id":1,"data":{"value":"Le 25 décembre, si un cadeau ressemble à une 32 bits, ne riez pas, c'est peut-être le vôtre."}},{"id":4,"data":{"value":"Nintendo"}}],"link":{"url":"http://someurl.com"},"eventtrackers":[{"event":1,"method":1,"url":"http://sometrackingurl.com"}]}"`

In the assets, I have two "data" with two different values. How am I suppose to link one data with its corresponding type ? If I did set the ids myself I could be sure which object is id=1 and which other is id=4. Sure I can make a guess based on the order of my list of assets in the request as it seems the response id's are based on that, but it's a guess, it's not documented and might be wrong for other requests. 

Did I miss something in the way to interpret this response ? Would it be possible to add the matching type in each data object ?

Thanks

**Comment by mansinahar** [comment]
@matthieularere-msq you can provide asset IDs in the request and if you have provided them, Prebid Server will respect them rather than assigning it's own asset IDs. Prebid Server will only assign asset IDs if the request doesn't have asset IDs assigned. I am not sure why the documentation explicitly says not to assign it but I will check on that and update it as needed. Thanks for calling it out :)

**Comment by bretg** [comment]
Docs updated.
