### ISSUE TITLE
GDPR + CONSENT_STRING to load-cookie.html 

### ISSUE THREAD

**Issue by amaurybrisou** [prebid/prebid-server#1534]
Hello,

On this page of the documentation, http://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#amp-rtc-and-gdpr

it says we can call /cookie_sync through load-cookie.html page sending gdpr and consent_string query parameters.

Has anyone ever implemented this feature in an AMP page ? I can't figure out how to append gdpr and consent_string to the amp-iframe src attribute.

Thank you all !

**Comment by bretg** [comment]
@amaurybrisou - see https://github.com/prebid/prebid-universal-creative/issues/114

**Comment by bretg** [comment]
BTW - you're right that the prebid.org is incorrect. We will update this as part of https://github.com/prebid/prebid-universal-creative/pull/123

**Comment by bretg** [comment]
This new version of the Prebid Universal Creative (1.9) has been released. See the load-cookie-with-consent.html option in https://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages
