### ISSUE TITLE
RFC: Require https option

### ISSUE THREAD

**Issue by laurb9** [prebid/prebid-server#1540]
Should all the bidder endpoint defaults be over https ?
Given that bidders can generate their own endpoints, should there be a global option to require bidder connections over https and refuse to make unencrypted connections ?
Should this option be controlled by GDPR ?

GDPR language is a bit dense to me but It sounds like sending plain text data could be construed as not protecting transmitted data.
https://gdpr.eu/article-32-security-of-processing/
> In assessing the appropriate level of security account shall be taken in particular of the risks that are presented by processing, in particular from accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or **access to personal data transmitted**, stored or otherwise processed.

**Comment by bretg** [comment]
Discussed in Prebid Server committee. 

We will be reaching out to a couple of legal teams for consideration on GDPR -- it's unclear whether server-to-server communication is in scope. 

Depending on the results of that conversion we'll reach out to bid adapters to ask them to consider providing HTTPS endpoints.

**Comment by bretg** [comment]
Discussed with legal and the committee. The consensus is that HTTPS is good but not without cost and not clearly required in a server-to-server environment. We're going to advise bid adapters that HTTPS may be required someday.

If desired, we could track which adapters support HTTPS to their endpoint and add it as a piece of metadata to the docs. e.g. `pbs_https:true`.

**Comment by SyntaxNode** [comment]
Hosts can override the default settings. I'd like to propose a 'useshttps' attribute (not thrilled with the name) be added to the /info/bidders endpoint, dynamically set by Prebid Server depending on the actual url configured. The docs idea sounds good too to help provide guidance, but we'll need to clarify it's a default setting and ultimately depends on the host.

I've added a note to the new "how to build a bidder" docs (https://github.com/prebid/prebid.github.io/pull/2495) which encourages HTTPS use.

**Comment by SyntaxNode** [comment]
@laurb9 @bretg Can this issue be closed?

**Comment by bretg** [comment]
Discussed in PBS committee today. 

We agreed to update the /info/bidders/BIDDER output to add an attribute "uses-https": true/false

PBS will sniff the bidder's endpoint. if it starts with https, then uses-https will be true, else false.

**Comment by SyntaxNode** [comment]
Available starting in PBS-Go 0.148.0.

**Comment by bretg** [comment]
This is done in PBS-Java as well.
