### ISSUE TITLE
New NoBid Prebid Server Adapter

### ISSUE THREAD

**Issue by redaguermas** [prebid/prebid-server#1544]
New Prebid server adapter for NoBid.

**Comment by bretg** [comment]
@redaguermas - what's the intent of this issue? We don't build adapters -- that's the job of each bidder. Instructions at https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html

Once developed for PBS-Go, we will port adapters to PBS-Java.

**Comment by redaguermas** [comment]
This was part the instructions to commit to Prebid server.

**Comment by bretg** [comment]
The only part that mentions opening an issue is

```
Prebid Server bid adapters must follow all required conventions defined in the Module Rules. Not doing so could lead to delays in approving your adapter for inclusion in Prebid Server. If you’d like to apply for an exception to one of the rules, make your request in a new Prebid Server issue.
```

No harm no foul.
