### ISSUE TITLE
Draft PBS Adapter Community Note

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1555]
DRAFT

A number of announcements for the PBS Adapter Community:

## Currency Support Unit Tests

There have been a number of problems recently with currency conversions. It's important that bid adapters do the right thing when it comes to currency:

1) If your bidder supports multiple currencies, pass the request.cur field to your endpoint.
2) If your bidder only ever bids in USD or EUR, that's fine. PBS will convert your bid to the request currency.
3) But it can't do this if bid adapter doesn't label the currency of the bid.
4) You should have a unit test that verifies what happens if the request currency is something unknown, e.g. AAA -- make sure the bid currency is written to the bidresponse object.

## Module Rules

If you haven't looked at them recently, please review the [module rules](https://docs.prebid.org/dev-docs/module-rules.html). Some of the rules don't apply to Prebid Server adapters, but many do. In particular, Prebid Server reviewers will be paying attention to the following conventions:

- bid floors - adapters should pass imp[].bidfloor and bidfloorcur to their endpoint and abide by the floor. Adapters must be aware they may run for requests with different currencies. If your endpoint supports floors being defined only in a single currency, you will soon have a [currency conversion utility function](https://github.com/prebid/prebid-server/issues/1482) available.
- First Party Data - while not implemented in PBS-Go, we want adapters to be aware of the First Party Data conventions at https://docs.prebid.org/prebid-server/features/pbs-fpd.html . Once PBS-Go does support these conventions, we'll expect adapters to use them instead of having bidder-specific params for first party data.
- video parameters - bid adapters must prefer the standard imp[].video source for video parameters over video params in their bidder-specific section.
- We may at some point in the future require that all endpoints support secure HTTP. 
- Reliably getting a low-volume of test bids is still a consistent problem for many adapters. Prebid Server host companies need to verify integration and config is correct. Please review and/or provide test information in your BIDDER.md file in https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders .
- In coming a Prebid.js release, [bid metadata](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#bid-response-metadata) will be required, specifically advertiserDomains and mediaType. We recommend making sure your server-side adapter sets these values or Prebid.js may throw away the bid.

## AMP+UserSyncing
There's evidence that iframe-based usersyncs don't perform well in the AMP environment. See https://github.com/prebid/prebid-server/issues/1509
As a result, in the coming months we will allow bid adapters to supply both image and iframe usersyncs https://github.com/prebid/prebid-server/issues/1554

## Bidder Documentation and Consistency with Prebid.js Adapters

Most of you have seen the new [Prebid Server Bid adapter list](https://docs.prebid.org/dev-docs/pbs-bidders.html), which is dynamically generated from the BIDDER.md files at https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders

There are several modules that have a different set of parameters supported on Prebid Server vs Prebid.js. This is not ideal - Publishers want to be able to switch requests from client-side to server-side to test the impact. Please make sure your adapter documentation highlights any differences in parameters. And please work towards minimizing those differences.

**Comment by SyntaxNode** [comment]
I've called out these notes specifically in the new "how to build an adapter" doc: https://github.com/prebid/prebid.github.io/pull/2495

**Comment by bretg** [comment]
Email sent to the adapter community
