### ISSUE TITLE
Add verizon id to verizon adapter

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-server#1582]
Since https://github.com/prebid/Prebid.js/pull/5786 ; theere seems to be a large opportunity for the Brightroll / Verizon adapter to ingest its own id.

**Comment by bretg** [comment]
Adding @oath-jac, @Aadeshp, @smithaammassamveettil as the contributors of these modules.

**Comment by slimkrazy** [comment]
Hey folks, 

This adapter will already send up the Verizon ID as the eid objects are automatically included in the same openRTB field that Verizon's SSP expects.

**Comment by patmmccann** [comment]
I'm a little confused here, it doesn't seem like this adapter uses any id fields and that is reflected in its documentation

**Comment by slimkrazy** [comment]
Hey @patmmccann,

VM SSP ingests user identity values using the existing convention of placing an array of `eid` objects within the `user.ext` object. This data is automatically populated by prebid server core logic as documented [here](https://docs.prebid.org/dev-docs/modules/userId.html#prebid-server-adapters) so the Verizon Media adapter does not need to do anything as the data simply passes through to our openRTB endpoint.
