### ISSUE TITLE
Still no support for AppNexus AST adapter?

### ISSUE THREAD

**Issue by cwbeck** [prebid/prebid-server#159]
Is the AppNexus AST adapter going to be supported?

**Comment by dbemiller** [comment]
Ah... I think there's some confusion. `appnexus` is the official Appnexus adapter. The reasons for `appnexusAst` in JS are historical.

In the Prebid.JS 1.0 release, they'll be deleting the old `appnexus` adapter and renaming `appnexusAst` to `appnexus` to avoid confusion.
