### ISSUE TITLE
Question: Multi-Imp requests

### ISSUE THREAD

**Issue by curlyblueeagle** [prebid/prebid-server#1604]
@SyntaxNode In a prior PR you had suggested for 33Across adapter to handle multi-imp requests by breaking them up into multiple http requests https://github.com/prebid/prebid-server/pull/1557#discussion_r520008392

We are in the process of implementing this suggestion. However, I have a question for you. How would Prebid Server handle the individual bid responses and associate them with the incoming mult-imp bid request? The adapter will of course pass the Imp ID in each of the bid response during `MakeBids`. Will this be sufficient? Does the adapter need to do anything more?

**Comment by bretg** [comment]
Not sure how this works technically. @SyntaxNode ?

**Comment by SyntaxNode** [comment]
@curlyblueeagle Yes, that will be sufficient.

Prebid Server will call your adatper's `MakeBids` method once for each response received and combine the bids from all of those calls together as a single OpenRTB Seat Bid for your adapter. I recommend you perform end-to-end testing to make sure it looks right when all is said and done, but I don't anticipate any problems.

FYI: The code for this behavior is found in `exchange/bidder.go` in the `requestBid` method if you'd like to explore the logic further. Look for the `for i := 0; i < len(bidResponse.Bids); i++ {` loop.

**Comment by curlyblueeagle** [comment]
@SyntaxNode Thanks! 

We did an end-to-end test and all looks well. So I am going to close this issue since my question was answered.
