### ISSUE TITLE
Question about static folder and its contents

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server#1618]
Hi,

Thanks for your effort on prebid server and the rich high level documentation :+1: :heart: 

On my path to figure out what SSP specific parameters need to be set in the `ext` property I found that some have documented this on the regular prebid.org dev docs (e.g. [appnexus bid adapter|https://docs.prebid.org/dev-docs/bidders/appnexus.html]), but quite a few haven't. In a pull request I saw  changes in the `static/bidder-params`. 

Is this the official parameter documentation for bidders? Is there some other documentation that explains what are the contents in this `static` folder and what they represent?

Thanks in adavance,
Muki

**Comment by SyntaxNode** [comment]
The `static/bidder-params` content used by Prebid Server to validate the parameters on behalf of the bidder and reject the request if validation fails. If this validation fails, the bidder adapter is never called. This information is also exposed on the `bidders/params` endpoint for the purpose of third party configuration services/UIs.

The dev docs hosted at docs.prebid.org is also open source in the https://github.com/prebid/prebid.github.io repository and is intended to be human readable, including extra context of what the adapter supports, more descriptions around the bidder parameters, and examples.

I recently updated the [new bidder doc](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html) which explains this a bit better too.

**Comment by muuki88** [comment]
Thanks @SyntaxNode for the quick reply. I'll take a look at the new docs and see if I can figure things out.

Off topic: GitHub [just released _discussions_](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/), which aim to be a replacement for issues that are questions like this :smile:

**Comment by SyntaxNode** [comment]
> GitHub just released discussions, which aim to be a replacement for issues that are questions like this 😄

That would be fantastic! I'll take a look. Thank you.
