### ISSUE TITLE
Bid response validation and metrics

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1630]
PBS-Java currently checks the following fields are present on a bid response:
- bidId
- impid
- price
- crid
- price > 0 unless dealid specified, in which case price can be 0
- currency

However, for video, we're also checking that either `adm` or `nurl` are specified. 

We're not checking for adm or nurl in the case of banner or native, which seems odd. Is there any scenario where a bid response is valid without a creative body? 

The OpenRTB 2.5 standard doesn't list adm as a required field, but in Prebid, I don't see a way for creatives to show without either adm or nurl.

If PBS host companies turn on enforcement of secure markup validation as defined in https://github.com/prebid/prebid-server/issues/1288, adm will be required.

**Comment by jamescooper-blis** [comment]
OpenRTB supports retrieving the admark on the win. In this mode, bid.adm must be empty.

See section 4.3.1 in https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf

**Comment by bretg** [comment]
Perhaps, Prebid doesn't support this scenario.

The creative must be supplied with the bid because there's no mechanism to go back to the bidder to retrieve a creative in any scenario: client-banner, server-banner, client-video, server-video, SDK, and AMP -- all of them require that some Prebid component cache the creative (or VAST wrapper)

**Comment by bretg** [comment]
I'd like to propose an approach for bid validation.

Issue #1288 defines the following:

- adapter.BIDDER.response.validation.secure.{warn,err}
- adapter.BIDDER.response.validation.size.{warn,err}

But for the rest of these noted above (bidid, impid, price, etc) I propose we take the following approach:

1) log 1% (configurable) of errors found
2) create a metric adapter.BIDDER.response.validation.other.err

When we see a spike in `other.err`, we can go to our logs and see what's up.

**Comment by bretg** [comment]
Discussed in PBS committee. We agreed that metrics are more expensive than highly sampled logs, so the general approach of "sampled logs + aggregated metric" is a good approach. The host company can set alerts on the metric which will direct them to dig in the log entries.

Specifically, we discussed that the response validation metric could be aggregated across bidders:

```
responses.validation.secure.{warn,err}
responses.validation.size.{warn,err}
responses.validation.other.err
```

The suggestion is a host-level config: 
```
metrics.adapters.aggregate-verbose-metrics: true
```
These metrics response validation metrics would be the first that fall into the "verbose-metrics" category. When metrics.adapters.aggregate-verbose-metrics is true, log them as:
```
responses.validation.secure.{warn,err}
responses.validation.size.{warn,err}
responses.validation.other.err
```
When metrics.adapters.aggregate-verbose-metrics is true, log them as:
```
adapter.BIDDER.response.validation.secure.{warn,err}
adapter.BIDDER.response.validation.size.{warn,err}
adapter.BIDDER.response.validation.other.err
```

**Comment by bretg** [comment]
Merged with https://github.com/prebid/prebid-server/issues/2685
