### ISSUE TITLE
Change GVL URL

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1632]
Received the email below from the IAB.

We need to update the TCF GVL vendor list from `vendorlist.consensu.org` to `vendor-list.consensu.org`

---------- Forwarded message ---------
From: IAB Europe <framework@iabeurope.eu>
Date: Mon, Dec 21, 2020 at 5:08 AM
Subject: Domain name change for GVL resources
To: <ap@prebid.org>
Cc: <phil@mediavine.com>, <tkershaw@magnite.com>

Dear TCF CMPs and Vendors,The Tech Lab Privacy & Rearc Commit Group and TCF Framework Signals Working Group have approved a change to the domain name used for all Global Vendor List (GVL) resources. 

The background for the change is that despite TCF v1 consent strings no longer being valid, 100s of millions of requests for v1 GVL resources are still being received every day, at a considerable cost to the TCF Managing Organisation. **CMPs and Vendors have until February 28th 2021 to update the domain used for GVL resources from: vendorlist.consensu.org to vendor-list.consensu.org (a single hyphen ‘-’ added).** 

The new domain GVL resources can be accessed as follows:GVL: https://vendor-list.consensu.org/v2/vendor-list.json Translations: https://vendor-list.consensu.org/v2/purposes-fr.jsonArchives: https://vendor-list.consensu.org/v2/archives/vendor-list-v60.jsonCMPs and Vendors can switch to the new domain at any time before February 28th 2021.The vendorlist.consensu.org domain will be decommissioned on March 1st 2021.The technical specification has been updated to reflect the new resources and can be found here.

**Comment by bretg** [comment]
PBS should not attempt to retrieve TCF GVL v1 and just use the fallback.

We should set a date by which PBS will remove TCF1 parsing code.

**Comment by rpanchyk** [comment]
We've added a config option in PBS-Java `gdpr.vendorlist.vN.deprecated`, which will drop to fallback if true
https://github.com/prebid/prebid-server-java/blob/master/docs/config-app.md#gdpr

**Comment by SyntaxNode** [comment]
There's an equivalent setting in PBS-Go `gdpr.tcf1.fetch_gvl`.

> We should set a date by which PBS will remove TCF1 parsing code.

Yes, please. From the Xandr side, our usage of TCF1 is low enough that we're ready to remove whenever.

**Comment by rpanchyk** [comment]
GVL URL changed in PBS-Java since 1.53 release.
https://github.com/prebid/prebid-server-java/releases/tag/1.53.0 in PR https://github.com/prebid/prebid-server-java/pull/1086

**Comment by SyntaxNode** [comment]
This is included in the PBS-Go 0.144.0 release.

We now emit a deprecation warning for our `gdpr.tcf1.fetch_gvl` config flag and will remove it in our next release. The removal means we will always use the hardcoded fallback and no longer give the option to make external GVL 1 requests.

Let's discuss removing TCF1 support completely at the next Prebid.org Server Committee meeting.

**Comment by bretg** [comment]
Released with PBS-Java 1.53
