### ISSUE TITLE
Update Brightroll adapter json config

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#1634]
Hi,

We would need to make a small update in the Brightroll adapter json config 
Need to remove the value "IAB13" from "bcat" section for account id "dailymail" 

The updated config json can be found here 
https://docs.google.com/document/d/14-jMJjBvWaftCNkeN8Dx60eJrwgpaw-CAr5M7mfnESM/edit?usp=sharing

Can you please let me know the ETA for applying this change? 

Thanks,
Smitha

**Comment by SyntaxNode** [comment]
@smithaammassamveettil Please contact hosting companies directly for updates to their installations, or if your change applies to all hosts open a PR to make it the default.

If this request is for the Xandr/AppNexus host, please send the request to prebid-server@xandr.com. A lot of folks are off for the rest of the year, so I wouldn't expect a reply until next week.
