### ISSUE TITLE
Not getting bid response from server

### ISSUE THREAD

**Issue by soman** [prebid/prebid-server#1643]
I have setup prebid server with go on my personal server. But I'm not getting any response from server.
But when I hit the url 'http://198.199.90.116:8000/openrtb2/amp?tag_id=11111' then I'm getting bid response.

rtc-config: http://198.199.90.116:8000/openrtb2/amp?tag_id=11111
cache url: http://198.199.90.116:2424/cache?uuid=3db5d935-3971-459d-8113-cd75b820d423

Test page:
http://198.199.90.116/amp_demo.html

I will be very happy if someone guide me what I'm doing wrong. 

Note:
During setup I have followed the following docs:
https://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html
https://docs.prebid.org/prebid-server/use-cases/pbs-amp.html
https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-amp.html
https://docs.prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html

Thanks,

**Comment by SyntaxNode** [comment]
I can confirm your Prebid Server setup looks correct and functioning properly. Therefore, there must be an issue with your AMP setup. I don't have experience using the "urls" directly with a custom server, but I found this in the [AMP docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md):
```
Note that all URL strings must be secure (i.e. start with HTTPS).
```

Your server is not using HTTPS, so I recommend to start there.

**Comment by soman** [comment]
At first, thanks a lot @SyntaxNode.
Now I'm getting response from prebid server and also passing target response during dfp ad call.

But now I'm facing new issue and that is error occurred during creative called.

New test page: https://www.adgrid.io/test-pages/amp-ad/test.html


General script code for creative:
<script src="https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
`<script>
  var ucTagData = {};
  ucTagData.adServerDomain = "";
  ucTagData.pubUrl = "%%PATTERN:url%%";
  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
  ucTagData.hbPb = "%%PATTERN:hb_pb%%";

  try {
    ucTag.renderAd(document, ucTagData);
  } catch (e) {
    console.log(e);
  }
</script>` 

Error screenshot:
[https://www.adgrid.io/test-pages/amp-ad/amp-ad-creative-error-for-general.jpg](url)



Pubmatic script code for creative:
`<script src='//ads.pubmatic.com/AdServer/js/pwt/%%PATTERN:pwtpubid%%/%%PATTERN:pwtprofid%%/%%PATTERN:pwtverid%%/pwt.js'></script><script>window.PWT.renderOWCreative(document,{pwtecp:'%%PATTERN:pwtecp%%',pwtbst:'%%PATTERN:pwtbst%%',pwtcid:'%%PATTERN:pwtcid%%',pwtcurl:'%%PATTERN:pwtcurl%%',pwtpcapth:'%%PATTERN:pwtcpath%%',pwtsid:'%%PATTERN:pwtsid%%',pwtpid:'%%PATTERN:pwtpid%%' })</script>`

Pubmatic error screenshot:
[https://www.adgrid.io/test-pages/amp-ad/amp-ad-creative-error-for-pubmatic.jpg](url)
