### ISSUE TITLE
Can't find Error log files in a Prebid Server instance

### ISSUE THREAD

**Issue by nmpina28** [prebid/prebid-server#1652]
### Type of issue

Can't find any error log files in running PBS instance. It seems that all types of errors and warnings are returned directly in the response to a request made to PBS.

### Description
My team and I have a Docker container running an instance of a PBS image. We copied to the inside of the container some valid and invalid stored-imps and stored-requests.
Then we use postman or a browser to test some requests made client-side to check if responses were as expected. The endpoint used was the /openrtb2/auction and the tests were

- For Postman, we've created valid OpentRTB 2.5 requests and send them. These requests had valid and invalid stored-imps and stored-requests implemented so we could check and validate the errors returned in the responses
- For the Browser, we've created a testing page and we use the prebidServer adapter from Prebid.js to create the request that will be sent to our PBS instance

Since there are some errors I would expect to find some log files with these errors. But I've searched inside the container and I couldn't find anything resembling error log files

### Expected results
The errors returned in the response are the expected ones (Invalid JSON for some stored-imps and invalid type for some bidders parameters) amongst others.

### Questions

- PBS supports the error logging or some kind of reporting? If so what is the location of these files? And how it works (recycling time, maximum size per file,...)
- PBS only handles and returns errors via response? Only has errors that can be triggered by requests?
- I know that when I am building an instance of PBS if there's any problem it shows in the console but this is different. Is there any kind of reporting implemented on PBS?
-  Is there any class or method created that I can check to understand if some kind of logging is being made?

Thank you,

Nelson

**Comment by SyntaxNode** [comment]
Hi Nelson,

You're right. PBS does not log request specific errors except for when the request causes an adapter to panic. The full request body and error messages are included in the response back to the caller if the request enables the debug flag or has a test auction flag. We consider errors such as an incorrect stored request id to be the "fault" of the caller, not the server, and thus does not emit server logs for these events.

There are several backends for retrieving stored request data. Personally, I most often use the database backend and that will log errors if queries fail or if there are connectivity issues. I don't have much experience with the file based backend and don't recall what errors it logs. I think you indicate that you're happy with the level of logging on your local machine, so then this becomes a question of how to access that information on the server. Do I have that right?

If so, you'll need to hookup a log aggregation service such as ELK, Splunk, SumoLogic, etc.. to the standard output of PBS. This a common solution which gives hosts flexible control over how to integrate the logs.

If you're looking to add logs, I support expanding PBS' logging capabilities provided the new logs turned off by default and provide sampling rate options (simply a random chance if the log will be emitted). A good way to code that up is likely through an analytics adapter. Just please be prepared for scrutiny over concurrency support when writing an analytics adapter.

> PBS supports the error logging or some kind of reporting? If so what is the location of these files? And how it works (recycling time, maximum size per file,...)

PBS logs to standard out. We expect hosts to use a third party service for aggregation and retention.

> PBS only handles and returns errors via response? Only has errors that can be triggered by requests?

Correct, unless the request causes an adapter to panic. Of course, we do gracefully handle errors throughout the application such as with stored request syncs and gvl retrievals.

> I know that when I am building an instance of PBS if there's any problem it shows in the console but this is different. Is there any kind of reporting implemented on PBS?

This sounds like you're looking for log aggregation and retention. Do I have that right?

> Is there any class or method created that I can check to understand if some kind of logging is being made?

You can write an analytics adapter within the `/analytics` package.

**Comment by nmpina28** [comment]
Hi,

First of all, I want to thank you for your fast reply and for your time. 
So, after reading your answer and to summarize things I can conclude the following:

1.  PBS doesn't have an error logging feature that stores the errors in files. For that, I have to use some log aggregation and retention service, like Splunk,... Like you said: _"PBS logs to standard out. We expect hosts to use a third party service for aggregation and retention."_
2.  All the errors that can be produced by a request will be sent in the response back to the client but only if the request enables the debug flag or has a test auction flag 
3.  The errors are mainly caused by requests? Unless, when the request causes an adapter to panic. In this case, the error is handled internally and not stored on files or displayed in the console. 
4.  If I understood correctly, you said all the internal errors are handled, so there's no need for error logging or console output
5.  To answer your question: _"I think you indicate that you're happy with the level of logging on your local machine, so then this becomes a question of how to access that information on the server. Do I have that right?"_ **Yes**, but I don't really have a logging system in my local machine unless I build an analytics adapter, right?

So, I'll need to hookup a third-party service for the aggregation to the standard output of PBS and check for errors (like Splunk, ...). Any internal errors or errors not caused by requests are handled and not register.

I think I understand correctly your explanation, right?

Once again, thank you for your most complete answer. Truly helpful as always

Cheers,

Nelson

**Comment by SyntaxNode** [comment]
1. Correct.
2. The debug or test flags are required for detailed information such as the actual payload sent to and received from bidders. I think bidder errors would always be included.
3. By "handled internally" I mean that we have code to prevent hard crashes (unless where we missed something) and write those events to the log for the host to be aware of.
4. Same answer as 3. That wasn't exactly what I meant here.
5. On your local machine you can run PBS directly in the console to view the logs, or pipe it to a file. If you want the full request to be included in the logs, I believe you need to build that. If you just want this for local machine development, adding a log entry somewhere protected by a feature flag might be fine too.

**Comment by nmpina28** [comment]
Hi SyntaxNode,

Thank you for your fast answer. In point:  

1.  You confirmed my questions about the PBS requests and how errors are handled. 
2. You confirmed that I'll always need those flags. And you're correct, all the bidders' errors are included in the response to the client
3. Correct. The errors are console logged. But are they file logged?
4. OK.
5. you say that I can run PBS directly in the console (I've done it) to view the logs, all the errors logged are displayed in the console, but my question, and I think you've already answered it, is if this errors (not produced by requests) are registered in files and could grow without control, in some folder, ex: /var/log/... Or they are only for console output and deleted when the instance of PBS stops running. I believe that you said that no file logging exists.

I really don't need to log locally, in files on the host, the errors produced by requests, for that I think your suggestion is great, to use a service for aggregation and retention.

Thank you for clarifying my questions.

Cheers,

Nelson

**Comment by SyntaxNode** [comment]
> is if this errors (not produced by requests) are registered in files and could grow without control, in some folder, ex: /var/log/... Or they are only for console output and deleted when the instance of PBS stops running. I believe that you said that no file logging exists.

They are only logged to the console output. Indeed, there is no file logging.

> I really don't need to log locally, in files on the host, the errors produced by requests, for that I think your suggestion is great, to use a service for aggregation and retention.

Perfect.

> Thank you for clarifying my questions.

Absolutely. Happy to help.

**Comment by nmpina28** [comment]
Thank you, Scott. For now, I think all my questions are answered.

I'll close the ticket. 

Cheers,
Nelson
