### ISSUE TITLE
InfluxDB error

### ISSUE THREAD

**Issue by gchicoye** [prebid/prebid-server#1655]
Hello,

Using Docker-Compose, I'm trying to connect my Prebid Server container to an InfluxDb container in order to track activities. However, although the influxDB seems to be in place, I get the following errors:  

```
prebid-server_1  | 2021/01/14 10:51:07 unable to send metrics to InfluxDB. err=Post "influxdb/write?consistency=&db=&precision=&rp=": unsupported protocol scheme ""
prebid-server_1  | 2021/01/14 10:51:07 got error while sending a ping to InfluxDB, trying to recreate client. err=Get "influxdb/ping": unsupported protocol scheme ""
```

Is there something I'm missing here?

Thanks!

Gabriel

**Comment by SyntaxNode** [comment]
The `unsupported protocol scheme ""` part of the error makes me thing you're not including the `http://` or `https://` prefix for your InfluxDB server.

**Comment by gchicoye** [comment]
Indeed, this solved the issue!
Thanks!
