### ISSUE TITLE
Change Bid Ext Response Behavior

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#1676]
## Issue

PBS currently redirects the `seatbid.bid.ext` response from adapters to `seatbid.bid.ext.bidder`. This decision was made years ago and we've lost the original context. We suspect this was done to avoid conflicts with `seatbid.bid.ext.prebid` which PBS uses to output important information such as targeting keys. 

This behavior is causing a problem with new official OpenRTB specifications which define industry standard use of `ext` fields, such as `seatbid.bid.ext.skadn`. We discussed avoiding special cases and prefer to change the underlying behavior.

## Proposal

PBS will no longer emit `seatbid.bid.ext.bidder`. It will keep everything in `seatbid.bid.ext` as is, except for writing `seatbid.bid.ext.prebid`. If the bid ext already has a `prebid` object defined, it will be entirely overwritten. Bid adapters don't have access to write to `seatbid.bid.ext.prebid` today, so we don't consider this part of the breaking behavior.

## Impact

We verified there is no impact to Prebid.js or the Prebid SDKs for IOS and Android. It's possible, although we think unlikely, that non-Prebid clients are using this field. Since we have no way to verify for certain, we're willing to take the chance with this breaking change.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.151.0

**Comment by bretg** [comment]
Released with PBS-Java 1.68
