### ISSUE TITLE
Hardcoded alias on server side

### ISSUE THREAD

**Issue by Niksok** [prebid/prebid-server#1682]
Hello! 
Maybe my question will be a duplicate, but it is not clearly for me - how to add new bid adapter with unique bidder name, but with the same functionality as the some existed adapter. For client side bid adapter i can set spec.aliases in the adapter code, and it would be great if there would be any way to make the same on server side.

**Comment by Niksok** [comment]
I have found only districtm alias for appnexus, may be i need to make the same, but it seems more like exception, not a right way.

**Comment by SyntaxNode** [comment]
Hi.

We're working towards hardcoded server side aliases which make use of the config, such that no code is required. This is tracked and discussed in a separate issue: https://github.com/prebid/prebid-server/issues/1429

The first part of that work was to update the adapter creation process. This was completed last month. Right now, we're using our time to focus on identity features (user sync enhancements and first part data). We plan to finish work on aliases in the coming weeks.

Until then, if you'd like to add a hardcoded alias I recommend following the pattern used by https://github.com/prebid/prebid-server/pull/1635. That will allow us to easily refactor into the full solution. Xandr will add the DistrictM alias when the full solution is in place.

**Comment by SyntaxNode** [comment]
@Niksok Does this answer your question?

**Comment by SyntaxNode** [comment]
I'm closing this issue. Please follow https://github.com/prebid/prebid-server/issues/1429 for updates.
