### ISSUE TITLE
Lost in PBS - How to Setup SSL ?

### ISSUE THREAD

**Issue by Sor3nt** [prebid/prebid-server#1686]
I looking around, google hours, read the given Documentation but still i have more questions then answers ^^

Issue: Unable to locate informations for SSL Setup.

Can someone pls point me to the Documentation for the SSL Configuration ?

**Comment by SyntaxNode** [comment]
**Are you referring to configuring PBS to accept SSL connections?** If so, we do not intend for PBS to be directly exposed to the Internet. You should run it behind a reverse proxy, like Nginx, and terminate SSL at that layer.

If you'd like to customize your own fork or submit a PR to provide an option for hosting with SSL, you'll want to start in  `server/server.go` in func `runServer`. The call to `server.Serve` starts an HTTP listener. Go also provides a `server.ServeTLS` to start an HTTPS listener.

**Are you referring to configuring SSL certificates to connect to bidders?** If so, PBS is hardcoded with the certificates from Ubuntu 18.04 TLS. PBS also supports custom certificates for connecting to bidders and fetchers with the `certificates_file` configuration value. Specify a path to your own file containing SSL certificates and PBS will load them for external connections.

**Comment by SyntaxNode** [comment]
@Sor3nt Does this answer your question?

**Comment by Sor3nt** [comment]
Yes, thank u :)
