### ISSUE TITLE
Failed to fetch Vendor-List (context deadline exceeded)

### ISSUE THREAD

**Issue by Sor3nt** [prebid/prebid-server#1687]
I receive always the same message when i start the server

`vendorlist-fetching.go:138] Error calling GET https://vendor-list.consensu.org/v2/archives/vendor-list-v75.json. Cookie syncs may be affected: context deadline exceeded`

so far i understand is "context deadline exceeded" related to a timeout value.

Unforgently i can not find any documentation about the timeout settings.

Where do i need to adjust these timeout ?

**Comment by SyntaxNode** [comment]
The settings related to fetching the GVL are:

**gdpr.timeouts_ms.init_vendorlist_fetches**: Timeout for the initial GVL fetch, expressed in milliseconds. This is what you're seeing when the application starts.

**gdpr.timeouts_ms.active_vendorlist_fetch**: Timeout for the subsequent GVL fetches while PBS is running, expressed in milliseconds.

The error message sounds a bit more dire than it is in reality. If fetching a GVL fails, PBS will try again later after loaded.

**Comment by SyntaxNode** [comment]
@Sor3nt Did this answer your question?

**Comment by Sor3nt** [comment]
perfect, thank u
