### ISSUE TITLE
Latest docker image for prebid-server not built

### ISSUE THREAD

**Issue by bmanth60** [prebid/prebid-server#1691]
Hi All,

I was trying to deploy the latest prebid-server release in my container environment and found out that there was no docker image for 0.145.0. The [prebid-server dockerhub page](https://hub.docker.com/r/prebid/prebid-server) returns a 404 message for me:

![image](https://user-images.githubusercontent.com/5578150/106650937-5438ee80-6548-11eb-8a8f-d28f6d9028c1.png)

So I was assuming that there was a build process that added the git tag and pushed the latest docker image: https://github.com/prebid/prebid-server/issues/171

I was wondering if there was any way to get access to the dockerhub page so I can follow the tags that are being created?

Thanks!

**Comment by SyntaxNode** [comment]
Hi,

You have the correct url: https://hub.docker.com/r/prebid/prebid-server. I can access that project home page fine from my machine. Perhaps there's an issue on DockerHub's side? I'm not really not sure what to advise on the 404 for the home page.

I can confirm there was an issue publishing the 0.145.0 image to DockerHub. Looks to be an intermittent issue. Can you wait until we build 0.146.0 this week, or do you need us to rebuild/republish 0.145.0?

**Comment by bmanth60** [comment]
Oh, thanks for the quick reply! I can wait for the next build. Hmm... yeah that is just something wrong with me then.
