### ISSUE TITLE
Question: ext object in request root object

### ISSUE THREAD

**Issue by jamescooper-blis** [prebid/prebid-server#1696]
I would like to add a custom ext object to the root bid request json. For example

```
{
    "device": { ... },
    "user": { ... },
    "ext": { "my_custom_field": "..." }
}
```

I notice that Smaato's adapter does pretty much the same thing:
https://github.com/prebid/prebid-server/blob/3b9f61aec86aed9a69316c45310664cf17ef0290/adapters/smaato/smaato.go#L132

My question is:
 - Is adding a 'ext' object to the request root object acceptable?
 - Do I not have to make a copy of `request *openrtb.BidRequest` (Smaato don't seem to, but I thought I'd ask anyway)
 - If adding a root-level 'ext' object is acceptable, should I add another sub-object to it with my bidder's name, e.g.
    `"ext": { "mybidder": { "my_custom_field": "..." }}`
 
Putting this info into the `imp` object is that useful for our use-case.

Any guidance here would be appreciated.

**Comment by bretg** [comment]
> would like to add a custom ext object to the root bid request json

You can add anything you'd like to the JSON that's heading to your endpoint. You could change it to OpenRTB 3.0. You could use a protocol other than OpenRTB. That's the point of having a separate bid adapter.

The version of the bidrequest you receive is custom to your bidder anyhow -- it's been stripped of reference to other bidders.

> Putting this info into the imp object is that useful for our use-case

Sorry, not following the question here.

**Comment by jamescooper-blis** [comment]
> 
> 
> > would like to add a custom ext object to the root bid request json
> 
> You can add anything you'd like to the JSON that's heading to your endpoint. You could change it to OpenRTB 3.0. You could use a protocol other than OpenRTB. That's the point of having a separate bid adapter.
> 
> The version of the bidrequest you receive is custom to your bidder anyhow -- it's been stripped of reference to other bidders.
> 

Great, ok. I new to this, and golang. I was concerned about having to make a copy of the `request` passed to `MakeRequests` as I think I read somewhere that this memory is shared across all adapters.

> > Putting this info into the imp object is that useful for our use-case
> 
> Sorry, not following the question here.

There's a typo, it should have read 'not that useful'

**Comment by SyntaxNode** [comment]
> Is adding a 'ext' object to the request root object acceptable?

Yes. As @bretg mentioned, there are no restrictions from PBS on what content the adapter sends to the bidding server.

> Do I not have to make a copy of request *openrtb.BidRequest (Smaato don't seem to, but I thought I'd ask anyway)

You do not. The bid request object passed to the adapter is already a shallow copy. Setting the `ext` field to a new byte array is not a problem. Just be aware this bid request object is also passed to MakeBids, so if you make a change to it in MakeRequests the MakeBids method no longer has access to the original request. This usually isn't a concern.

**Comment by jamescooper-blis** [comment]
@SyntaxNode Thanks for your help!
