### ISSUE TITLE
Accommodate Apple iOS LMT bug

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#1699]
## Type of issue

Intent to implement

## Description

Apple introduced a bug in iOS 14.0 that persisted until 14.2 improperly setting LMT = 1 in all scenarios. The impact to this bug is an increase LMT=1 traffic for those iOS versions. This ticket is to resolve the bug, moving future LMT logic to PBS core. The Prebid SDK is not able to keep up to date with the changes fast enough, plus any devices with an older version Prebid SDK (prior to 1.8.1) and newer versions of iOS will exhibit problems.

Below is the current LMT behavior matrix with the associated Prebid SDK change to always pass LMT in version 1.20:

<img width="767" alt="Screen Shot 2021-02-09 at 1 35 25 PM" src="https://user-images.githubusercontent.com/49168870/107431741-e155e780-6af4-11eb-8f72-9caf08028bcd.png">

Below is the future behavior matrix of LMT as it pertains to Prebid SDK, assuming the change in PBS for LMT logic and Prebid SDK changing to always pass LMT in PBS:

<img width="777" alt="Screen Shot 2021-02-09 at 1 35 35 PM" src="https://user-images.githubusercontent.com/49168870/107431758-e7e45f00-6af4-11eb-8ec2-e8db2cab70f9.png">

## Goals

- Move LMT logic to PBS for iOS versions where Apple LMT behavior is in flux

## Proposed Design

- If PBS receives a request with the following attributes: app object exists, device.os = “iOS”(lower case value before matching), device.osv = “14.0" or “14.1” the following requirements apply:
    - If device.ifa = null or “” (empty string) or “00000000-0000-0000-0000-000000000000”, set device.lmt = 1
    - Else, set device.lmt=0, if not already set,  in the request to bid adapters
- Else if  PBS receives a request with the following attributes: app object exists, device.os = “iOS”, device.osv = “14.2” or greater the following requirements apply:
    - If device.ext.atts = 0 or 3, set device.lmt = 0, if not already set, in the request to bid adapters. ATTS 0 and 3 are "unspecified" and "authorized" respectively
    - Else if device.ext.atts = 1 or 2, set device.lmt = 1, if not already set, in the request to bid adapters. ATTS 1 or 2 are "restricted" and "denied" respectively
- Else, use device.lmt in the request

PBS should set any LMT changes **BEFORE** applying LMT anonymization.

### Prebid SDK Changes
Prebid SDK will need to start passing LMT again for all iOS versions as logic will be moved server-side in PBS.

### Prebid Server OpenRTB Changes

none

## Other information

https://github.com/prebid/prebid-mobile-ios/issues/348
https://github.com/prebid/prebid-mobile-ios/issues/351

**Comment by bretg** [comment]
Unfortunate, but understandable. I'm ok with this.

For the record, PBS already enforces LMT. When device.lmt=1:

- Mask take off the last byte of the IPv4 address and the last 2 bytes of IPv6 addresses
- Remove user.id and user.buyeruid (and soon user.ext.eids)
- Remove the request.device.ifa attribute
- Round the request.device.geo. {lat,lon} to two decimal places

**Comment by bszekely1** [comment]
Let me update the requirements stating the LMT change applies BEFORE applying LMT settings.

**Comment by SyntaxNode** [comment]
@bszekely1 Should the `device.os = “iOS”` be case sensitive? I'm not sure how the os is commonly represented for iOS devices. Perhaps a case insensitive compare would be a bit safer?

**Comment by bszekely1** [comment]
> 1 - Should the device.os = “iOS” be case sensitive? I'm not sure how the os is commonly represented for iOS devices. Perhaps a case insensitive compare would be a bit safer?

I pulled it off from a request from a simulator and from a real device, both seem to be true to the same case, but to be on the safe side, I would agree Lcasing makese sense. I don't see a world where iOS and ios are different operating systems. 

> 2 - Is device.idfa is a typo of device.ifa? I think the field is commonly referred to as IDFA but the actual type in OpenRTB is ifa.

Good catch, it is `ifa`. Let me correct it.

> 3 - For the case of iOS 14.2 or greater, I think you have a typo in the atts values. The value 1 is not represented and the value 3 is duplicated.

Another good catch. Let me correct it.

> 4 - Is it safe to assume iOS version numbers are always in the format of major.minor, or should we account for full semantic versioning in the backend?

yes, Apple releases are in the format major.minor as seen in the link below:
https://developer.apple.com/documentation/ios-ipados-release-notes

**Comment by bszekely1** [comment]
When Apple mandates pubs integrate into ATTS, we will have to change the logic slightly to read for version 14.5 (likely the next version they will start) to set LMT = 1 when it's unspecified. This was dictated by Apple. Until then unspecified is treated as authorized until then.

**Comment by SyntaxNode** [comment]
Available in PBS-Go starting with 0.149.0.

**Comment by bretg** [comment]
Released with PBS-Java 1.58

**Comment by bretg** [comment]
Another issue with these requirements has been discovered due to a difference in the way PBS-Go and PBS-Java implemented them. 

In PBS-Go, this has been implemented as an override, ignoring the words "if not already set" as highlighted below. PBS-Java, however, pays attention to the words "if not already set" and does not override `lmt`.

It seems like from the description (and a recent query) that the expectation is that PBS will override an incoming lmt value, but I would like someone in the mobile world to confirm the correct interpretation. These are the words from above:

1. If PBS receives a request with the following attributes: app object exists, device.os = “iOS”(lower case value before matching), device.osv = “14.0" or “14.1” the following requirements apply:
    1a. If device.ifa = null or “” (empty string) or “00000000-0000-0000-0000-000000000000”, set device.lmt = 1
    1b. Else, set device.lmt=0, **if not already set**, in the request to bid adapters
2. Else if PBS receives a request with the following attributes: app object exists, device.os = “iOS”, device.osv = “14.2” or greater the following requirements apply:
    2a. If device.ext.atts = 0 or 3, set device.lmt = 0, **if not already set**, in the request to bid adapters. ATTS 0 and 3 are "unspecified" and "authorized" respectively
    2b. Else if device.ext.atts = 1 or 2, set device.lmt = 1, **if not already set**, in the request to bid adapters. ATTS 1 or 2 are "restricted" and "denied" respectively
3. Else, use device.lmt in the request

The only scenario where `lmt` is **overridden** is 1a. Is that correct or not?

**Comment by YuriyVelichkoPI** [comment]
@bretg 

> The only scenario where lmt is overridden is 1a. Is that correct or not?

Right, it is related to the bug in iOS “14.0" and “14.1”. SDK may send incorrect values in `lmt` because of iOS. So the server should help here. 

If `ifa` is not valid, it means that the user didn't allow us to track him, so need to override `lmt` to 1 even if it is 0. 

In all other cases, SDK should provide proper `lmt` value based on the ATT framework. So I'm not pretty sure why we have this **if not exists**. 

I think that if PBS java overrides the `lmt` in any case, it shouldn't harm because, for now, the rules are the same in the SDK and server.

**Comment by bretg** [comment]
We have a publisher who seems to expect PBS to override `lmt` in scenario 2a.

> Based on this GitHub issue, I expect PBS to ignore device.lmt = 1  as the request includes device.ext.atts = 3, device.os = "iOS and device.osv >= "14.2" -- but when I make the same PBS request with the test flag enabled, I can see that PBS is not sending the device.ifa value to bidders e.g.

PBS-Go does override, PBS-Java does not. Who is correct?

**Comment by YuriyVelichkoPI** [comment]
It is very strange that `device.lmt = 1` and `device.ext.atts = 3` at the same time. 

Here you can see that if atts is available the lmt will be 0 for atts==3.

https://github.com/prebid/prebid-mobile-ios/blob/63a3e68fa45f5267fa42c52e4edeabf73e5f6066/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMDeviceInfoParameterBuilder.m#L105

Let me check tho older versions.

**Comment by bretg** [comment]
The PB SDK version the pub is using is 1.12.1

**Comment by YuriyVelichkoPI** [comment]
I see that the earlier behavior is different (v 1.12.2). 

The `atts` is set based on ATT but `lmt` is set based on deprecated and buggy `isAdvertisingTrackingEnabled` without taking into consideration the `atts` value.

So yes `lmt` value can be incorrect, and the server should rewrite it based on `atts` value even if it is present in the bid request. The `atts` is more reliable. 

In addition, I've checked the behavior on my phone with iOS 16.1.1. And as you can see on the attached screenshot, the `isAdvertisingTrackingEnabled` returns an incorrect value due to the ATT. 

<img width="1737" alt="Screenshot 2022-12-02 at 19 27 11" src="https://user-images.githubusercontent.com/21169695/205351390-d25d906f-6fa8-4d48-bf11-997c2652333c.png">

So the server should override `lmt` because old SDK versions send the incorrect value from the deprecated iOS property.

**Comment by bretg** [comment]
Ok, so this is an official change to the requirements as written - we'll update PBS-Java to drop the phrase "if not already set" in all three locations

If PBS receives a request with the following attributes: app object exists, device.os = “iOS”(lower case value before matching), device.osv = “14.0" or “14.1” the following requirements apply:
1a. If device.ifa = null or “” (empty string) or “00000000-0000-0000-0000-000000000000”, set device.lmt = 1
1b. Else, set device.lmt=0, in the request to bid adapters
Else if PBS receives a request with the following attributes: app object exists, device.os = “iOS”, device.osv = “14.2” or greater the following requirements apply:
2a. If device.ext.atts = 0 or 3, set device.lmt = 0, in the request to bid adapters. ATTS 0 and 3 are "unspecified" and "authorized" respectively
2b. Else if device.ext.atts = 1 or 2, set device.lmt = 1, in the request to bid adapters. ATTS 1 or 2 are "restricted" and "denied" respectively
Else, use device.lmt in the request

**Comment by YuriyVelichkoPI** [comment]
I'm not sure that everything is correct with item 2. 

By default, tracking is off, and users should opt-in to turn it on. So the "unspecified" is rather 0 for `lmt`.

The IAB's spec for SKAdNetwork makes the same assumption: 
https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/community_extensions/skadnetwork.md#dnt-lmt-and-app-tracking-transparency-guidance

So the `lmt` should be 1 only if `atts` is 3. 

Need to review the history of the policy one more time.

**Comment by bretg** [comment]
Are you sure @YuriyVelichkoPI  - atts:3 means "authorized", right? Which means lmt should be 0 (i.e. not limited)

**Comment by YuriyVelichkoPI** [comment]
> Are you sure @YuriyVelichkoPI - atts:3 means "authorized", right? Which means lmt should be 0 (i.e. not limited)

Sure. Sorry about that. I've updated the previous message.

**Comment by bretg** [comment]
ok, thanks @YuriyVelichkoPI - 

 Ok, so this is an official change to the requirements as written - we'll update PBS-Java to drop the phrase "if not already set" in all three locations

1. If PBS receives a request with the following attributes: app object exists, device.os = “iOS”(lower case value before matching), device.osv = “14.0" or “14.1” the following requirements apply:
- 1a. If device.ifa = null or “” (empty string) or “00000000-0000-0000-0000-000000000000”, set device.lmt = 1
- 1b. Else, set device.lmt=0, in the request to bid adapters
2. Else if PBS receives a request with the following attributes: app object exists, device.os = “iOS”, device.osv = “14.2” or greater the following requirements apply:
- 2a. If device.ext.atts = 3, set device.lmt = 0, in the request to bid adapters. ATTS 3 is "authorized"
- 2b. Else if device.ext.atts = 0, 1 or 2, set device.lmt = 1, in the request to bid adapters. ATTS 0, 1, and 2 are "unspecified", "restricted" and "denied" respectively
3. Else, use device.lmt in the request

**Comment by bretg** [comment]
The revision released with PBS-Java 1.106.

@SyntaxNode - there was an update to the requirements here that PBS-Go should be aware of:
- dropped the phrase "if not already set" in all three locations. I think Go already did it this way
- shift ATTS 0 from 2a to 2b -- this is new.

**Comment by mansinahar** [comment]
This is done in PBS Go as well and will be part of `0.255.0`
