### ISSUE TITLE
Problem installing on FreeBSD

### ISSUE THREAD

**Issue by hypper89** [prebid/prebid-server#17]
Hello. 

    I have a problem when i try to build in FreeBSD. 

vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go:20: cpuUsage.Get undefined (type Cpu has no field or method Get)vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go:30: cpuUsage.Get undefined (type Cpu has no field or method Get)vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go:49: l.Get undefined (type LoadAverage has no field or method Get)vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go:55: m.Get undefined (type Mem has no field or method Get)vendor/github.com/cloudfoundry/gosigar/concrete_sigar.go:61: s.Get undefined (type Swap has no field or method Get)vendor/github.com/cloudfoundry/gosigar/sigar_unix.go:23: cannot use stat.Ffree (type int64) as type uint64 in assignment

**Comment by asweeney86** [comment]
It looks like https://github.com/cloudfoundry/gosigar is missing FreeBSD support.  We can fix this by  adding support to the gosigar project or investigating a package/way to obtaining resource information.

**Comment by hypper89** [comment]
I think it would be more simple to just remove the go-sigar dependency and replace it with gopsutil. I have searched and found this solution. I don't know if this is a reliable thing to do. 

Thank you for the response.
