### ISSUE TITLE
Rubicon DISABLED by default

### ISSUE THREAD

**Issue by thomasdseao** [prebid/prebid-server#1701]
Hello,

I just start a Prebid Server on my own server.
But i would like to use Rubicon Adapter, but when i try it, the server return me : 
`Invalid request: Bidder "rubicon" has been disabled on this instance of Prebid Server. Please work with the PBS host to enable this bidder again.`

And when i send get request on http://localhost:8000/info/bidders/rubicon : 
`{"status":"DISABLED","maintainer":{"email":"header-bidding@rubiconproject.com"},"capabilities":{"app":{"mediaTypes":["banner"]},"site":{"mediaTypes":["banner","video"]}}}`

Do you know how can i enable rubicon ?

Thanks

**Comment by matthieularere-msq** [comment]
Hi,

For rubicon you need to contact them so they provide you credentials and endpoints for openrtb and user sync.

**Comment by thomasdseao** [comment]
Thanks @matthieularere-msq for infos !
