### ISSUE TITLE
debug without test: 1

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1703]
Hi,

When adding the parameter test: 1 in the openrtb request send to pbs, the impression is ignored by the ssps as it's just a test. 
Is there any other way than using this test parameter to get the object ext.debug in pbs response ? So I could get it on a live sample for a debugging purpose ? 

Thanks

**Comment by SyntaxNode** [comment]
Yes. You may use the debug flag in the `request.ext.prebid` section. Please see more info in our docs:
https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#debug-flag

**Comment by matthieularere-msq** [comment]
Thanks, that's exactly what I was looking for.
