### ISSUE TITLE
cookie sync ok but no buyeruidsent to bidder

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1709]
Hi,

I have a strange behavior with one specific publisher for one specific bidder. On this publisher, buyeruid is never sent to bidder rubicon even though endpoint cookie_sync was called right before to check cookie for this bidder and sync url was sent. I checked the consent string and rubicon's vendor id was allowed.
With other publishers I don't have this issue and buyerid is sent in the payload to rubicon

So my question would be : what could avoid buyeruid to be sent to bidder even thought it's in the uids cookie ? I suspect something related with the consent string but it looks ok to me. For instance, here one of the consent string where this issue happens :

CPAavcCPAavcCAGABCFRBKCsAP_AAH_AAAqIHFNf_X_fb3_j-_59_9t0eY1f9_7_v-0zjgeds-8Nyd_X_L8X5mM7vB36pq4KuR4Eu3LBAQdlHOHcTUmw6IkVqTPsbk2Mr7NKJ7PEinMbe2dYGH9_n9XT_ZKY79_____7__-_____7_f__-__3_vp9V---wOJAIMBAUAgAEMAAQIFCIQAAQhiQAAAABBCIBQJIAEqgAWVwEdoIEACAxAQgQAgBBQgwCAAQAAJKAgBACwQCAAiAQAAgAEAIAAEIAILACQEAAAEAJCAAiACECAgiAAg5DAgIgCCAFABAAAuJDACAMooASBAPGQGAAKAAqACGAEwALgAjgBlgDUAHZAPsA_ACMAFLAK2AbwBMQCbAFogLYAYEAw8BkQDOQGeAM-EQHwAVABWAC4AIYAZAAywBqADZAHYAPwAgABGAClgFPANYAdUA-QCGwEOgIvASIAmwBOwCkQFyAMCAYSAw8Bk4DOQGfCQAYADgBzgN_CQTgAEAALgAoACoAGQAOAAeABAACIAFQAMIAaABqADyAIYAigBMgCqAKwAWAAuABvADmAHoAQ0AiACJgEsAS4AmgBSgC3AGGAMgAZcA1ADVAGyAO8AewA-IB9gH6AQAAjABQQClgFPAL8AYoA1gBtADcAG8AOIAegA-QCGwEOgIqAReAkQBMQCZQE2AJ2AUOApEBYoC2AFyALvAYEAwYBhIDDQGHgMiAZIAycBlwDOQGfANIAadA1gDWQoAEAYQaBIACoAKwAXABDADIAGWANQAbIA7AB-AEAAIKARgApYBT4C0ALSAawA3gB1QD5AIbAQ6Ai8BIgCbAE7AKRAXIAwIBhIDDwGMAMnAZyAzwBnwcAEAA4Bv4qA2ABQAFQAQwAmABcAEcAMsAagA7AB-AEYAKXAWgBaQDeAJBATEAmwBTYC2AFyAMCAYeAyIBnIDPAGfANyHQWQAFwAUABUADIAHAAQAAiABdADAAMYAaABqADwAH0AQwBFACZAFUAVgAsABcADEAGYAN4AcwA9ACGAERAJYAmABNACjAFKALEAW4AwwBkADKAGiANQAbIA3wB3gD2gH2AfoBGACVAFBAKeAWKAtAC0gFzALyAX4AxQBuADiQHTAdQA9ACGwEOgIiAReAkEBIgCbAE7AKHAU0AqwBYsC2ALZAXAAuQBdoC7wGEgMNAYeAxIBjADHgGSAMnAZUAywBlwDOQGfANEgaQBpIDSwGnANYAbGPABAIqAb-QgZgALAAoABkAEQALgAYgBDACYAFUALgAYgAzABvAD0AI4AWIAygBqADfAHfAPsA_ACMAFBAKGAU-AtAC0gF-AMUAdQA9ACQQEiAJsAU0AsUBaMC2ALaAXAAuQBdoDDwGJAMiAZOAzkBngDPgGiANJAaWA4AlAyAAQAAsACgAGQAOAAigBgAGIAPAAiABMACqAFwAMQAZgA2gCGgEQARIAowBSgC3AGEAMoAaoA2QB3gD8AIwAU-AtAC0gGKANwAcQA6gCHQEXgJEATYAsUBbAC7QGHgMiAZOAywBnIDPAGfANIAawA4AmACARUA38pBBAAXABQAFQAMgAcABAACKAGAAYwA0ADUAHkAQwBFACYAFIAKoAWAAuABiADMAHMAQwAiABRgClAFiALcAZQA0QBqgDZAHfAPsA_ACMAFBAKGAVsAuYBeQDaAG4APQAh0BF4CRAE2AJ2AUOApoBWwCxQFsALgAXIAu0BhoDDwGMAMiAZIAycBlwDOQGeAM-gaQBpMDWANZAbGVABAA-Ab-A.YAAAAAAAAAAA

**Comment by bretg** [comment]
@matthieularere-msq - more details would help: do you have a test page? Which Prebid Server are you using?

Using these test pages it looks ok
- http://sneezy.aws.rubiconproject.com/rp-eng-soln/prebid/prebid_server_test_14062.html?pbjs_debug=true -- Rubicon's Prebid Server (PBS-Java)
- http://sneezy.aws.rubiconproject.com/rp-eng-soln/prebid/prebid_server_test_14062_apn.html?pbjs_debug=true --AppNexus' Prebid Server (PBS-Go)

The rubicon ID is seen to flow through to the endpoint. e.g.
```
user\":{\"buyeruid\":\"KKZNME4Z-25-2XLN\"}
```

Your TCF string isn't valid according to https://iabtcf.com/#/

**Comment by matthieularere-msq** [comment]
@bretg 

You can test it live yes. Though I first need to explain that prebid-server in called server side and not client side. We made a prebid-client bidder to hide the prebid-server process, so here is the way it works : 
- prebid-client calls mediasquare bidder's endpoint (https://pbs-front.mediasquare.fr/msq_prebid) with some tag id
- this endpoint builds an openrtb request based on the params received and send it to prebid-server plus call the pbs cookie_sync. Then replies with the ssps responses and the cookie urls to sync
- prebid client has its bids and can calls the cookies urls to sync (depending on its configuration, one or more of the syncs urls can be calls).

So if you want to test, you can : 
- alter your host to make  dns pbs-front.mediasquare.fr point to ip 37.187.164.66 (that's the only live host right now with the appropriate debug options)
- go on this page : https://www.programme-tv.net/?pbjs_debug=true (debug mode to active the mediasquare bidder debug response)
- check for networks calls to msq_prebid
- in the response, you'll get a json. It contains various objects. What's interesting here is "cookies" which contains all the urls to sync with in order to do cookie matching. 
If you want to see the calls sent to rubicon, you can have a look at debug.responses.ext.debug.httpcalls.msqRubiconClassic.requestbody
(only this bidder is in this debug response)

You can check that after you ran the cookie sync url for rubicon - and the msq_prebid endpoint no longer has it in its cookies object - the requestbody sent to msqRubiconClassic don't have the buyeruid set. And this happens only on this publisher. For example do the same test on https://www.20minutes.fr/?pbjs_debug=true and you'll see buyeruid. That's the reason why I suspect there is some conditions in pbs that makes the buyeruid empty for some reason, and my initial idea is that's consent string related but it's just an assumption.

About the consent string, it seems like somehow github alter it as the one in my post is not the one I copied.  Attached is the correct consent string :
[consent.txt](https://github.com/prebid/prebid-server/files/6002297/consent.txt)

**Comment by bretg** [comment]
This is a complicated setup. Can I post directly to your PBS or is that blocked by networking? What version of prebid server have you set up? Go or Java? Is it up-to-date?

One thing I noticed that's different between the sites is that 20minutes.fr (the one that sends buyeruid) passes in regs.ext.gdpr:1 for me coming from the US, while programme-tv.net (the one that doesn't) doesn't pass any regs.ext.gdpr for me. I don't see anything in the rubicon adapter that suppresses buyeruid, so my initial take is does seem likely to be GDPR related. But I'm not as familiar with the Go version of PBS. Do you have it configured to enforce GDPR by default? That would do it. Though it would effect all bidders. I don't see requests for other bidders, so can't tell if their IDs are going out.

My hunch is that if you could pass regs.ext.gdpr:0 to PBS, you'd see buyeruid. That would at least prove it's GDPR-related.

**Comment by matthieularere-msq** [comment]
Hi @bretg 

It's pbs-go 0.148.0
By default direct call to PBS is blocked by firewall, but for debuging purpose and as I removed this server from production as long as we need to make test, you can call http://pbs-front-01.mediasquare.fr:8000/ to reach PBS

 updated my endpoint's debug to add the requests sent to all bidders.
I also tried with gdpr set to 0 just as you asked and indeed the result prove it's GDPR-related.

Here is what I did to test:
- with full gdpr
`curl -b cookies_pbs -c cookies_pbs -X POST -d '{"codes":[{"owner":"prisma","code":"programme-tv.net_rg_atf_mban_desktop","adunit":"Banniere-Haute_6033a2f7ecf45","bidId":"2039608f585a2fe","auctionId":"f948141a-2e62-405a-8e49-1eb226714330","transactionId":"a41a19f4-854c-4ae9-809c-afbd100ab47c","mediatypes":{"banner":{"sizes":[[728,90],[970,90],[970,250],[1000,90],[1000,200],[1800,1000]]}}},{"owner":"prisma","code":"programme-tv.net_rg_atf_pave_desktop","adunit":"Pave-Haut_6033a2f7f01b2","bidId":"21b37d0518cd22f","auctionId":"f948141a-2e62-405a-8e49-1eb226714330","transactionId":"d0a17cdd-0d3f-4d8b-8f6e-d6c1e4ddc773","mediatypes":{"banner":{"sizes":[[300,250],[300,600],[120,600],[160,600]]}}}],"referer":"https%3A%2F%2Fwww.programme-tv.net%2F%3Fpbjs_debug%3Dtrue","gdpr":{"consent_string":"CPAavcCPAavcCAGABCFRBKCsAP_AAH_AAAqIHFNf_X_fb3_j-_59_9t0eY1f9_7_v-0zjgeds-8Nyd_X_L8X5mM7vB36pq4KuR4Eu3LBAQdlHOHcTUmw6IkVqTPsbk2Mr7NKJ7PEinMbe2dYGH9_n9XT_ZKY79_____7__-_____7_f__-__3_vp9V---wOJAIMBAUAgAEMAAQIFCIQAAQhiQAAAABBCIBQJIAEqgAWVwEdoIEACAxAQgQAgBBQgwCAAQAAJKAgBACwQCAAiAQAAgAEAIAAEIAILACQEAAAEAJCAAiACECAgiAAg5DAgIgCCAFABAAAuJDACAMooASBAPGQGAAKAAqACGAEwALgAjgBlgDUAHZAPsA_ACMAFLAK2AbwBMQCbAFogLYAYEAw8BkQDOQGeAM-EQHwAVABWAC4AIYAZAAywBqADZAHYAPwAgABGAClgFPANYAdUA-QCGwEOgIvASIAmwBOwCkQFyAMCAYSAw8Bk4DOQGfCQAYADgBzgN_CQTgAEAALgAoACoAGQAOAAeABAACIAFQAMIAaABqADyAIYAigBMgCqAKwAWAAuABvADmAHoAQ0AiACJgEsAS4AmgBSgC3AGGAMgAZcA1ADVAGyAO8AewA-IB9gH6AQAAjABQQClgFPAL8AYoA1gBtADcAG8AOIAegA-QCGwEOgIqAReAkQBMQCZQE2AJ2AUOApEBYoC2AFyALvAYEAwYBhIDDQGHgMiAZIAycBlwDOQGfANIAadA1gDWQoAEAYQaBIACoAKwAXABDADIAGWANQAbIA7AB-AEAAIKARgApYBT4C0ALSAawA3gB1QD5AIbAQ6Ai8BIgCbAE7AKRAXIAwIBhIDDwGMAMnAZyAzwBnwcAEAA4Bv4qA2ABQAFQAQwAmABcAEcAMsAagA7AB-AEYAKXAWgBaQDeAJBATEAmwBTYC2AFyAMCAYeAyIBnIDPAGfANyHQWQAFwAUABUADIAHAAQAAiABdADAAMYAaABqADwAH0AQwBFACZAFUAVgAsABcADEAGYAN4AcwA9ACGAERAJYAmABNACjAFKALEAW4AwwBkADKAGiANQAbIA3wB3gD2gH2AfoBGACVAFBAKeAWKAtAC0gFzALyAX4AxQBuADiQHTAdQA9ACGwEOgIiAReAkEBIgCbAE7AKHAU0AqwBYsC2ALZAXAAuQBdoC7wGEgMNAYeAxIBjADHgGSAMnAZUAywBlwDOQGfANEgaQBpIDSwGnANYAbGPABAIqAb-QgZgALAAoABkAEQALgAYgBDACYAFUALgAYgAzABvAD0AI4AWIAygBqADfAHfAPsA_ACMAFBAKGAU-AtAC0gF-AMUAdQA9ACQQEiAJsAU0AsUBaMC2ALaAXAAuQBdoDDwGJAMiAZOAzkBngDPgGiANJAaWA4AlAyAAQAAsACgAGQAOAAigBgAGIAPAAiABMACqAFwAMQAZgA2gCGgEQARIAowBSgC3AGEAMoAaoA2QB3gD8AIwAU-AtAC0gGKANwAcQA6gCHQEXgJEATYAsUBbAC7QGHgMiAZOAywBnIDPAGfANIAawA4AmACARUA38pBBAAXABQAFQAMgAcABAACKAGAAYwA0ADUAHkAQwBFACYAFIAKoAWAAuABiADMAHMAQwAiABRgClAFiALcAZQA0QBqgDZAHfAPsA_ACMAFBAKGAVsAuYBeQDaAG4APQAh0BF4CRAE2AJ2AUOApoBWwCxQFsALgAXIAu0BhoDDwGMAMiAZIAycBlwDOQGeAM-gaQBpMDWANZAbGVABAA-Ab-A.YAAAAAAAAAAA","consent_required":true},"debug":true}' http://pbs-front-01.mediasquare.fr/msq_prebid`
The response is in file curl_with_full_consent.json from the attached archive
- with gdpr set to 0 : 
`curl -b cookies_pbs -c cookies_pbs -X POST -d '{"codes":[{"owner":"prisma","code":"programme-tv.net_rg_atf_mban_desktop","adunit":"Banniere-Haute_6033a2f7ecf45","bidId":"2039608f585a2fe","auctionId":"f948141a-2e62-405a-8e49-1eb226714330","transactionId":"a41a19f4-854c-4ae9-809c-afbd100ab47c","mediatypes":{"banner":{"sizes":[[728,90],[970,90],[970,250],[1000,90],[1000,200],[1800,1000]]}}},{"owner":"prisma","code":"programme-tv.net_rg_atf_pave_desktop","adunit":"Pave-Haut_6033a2f7f01b2","bidId":"21b37d0518cd22f","auctionId":"f948141a-2e62-405a-8e49-1eb226714330","transactionId":"d0a17cdd-0d3f-4d8b-8f6e-d6c1e4ddc773","mediatypes":{"banner":{"sizes":[[300,250],[300,600],[120,600],[160,600]]}}}],"referer":"https%3A%2F%2Fwww.programme-tv.net%2F%3Fpbjs_debug%3Dtrue","gdpr":{"consent_string":"CPAavcCPAavcCAGABCFRBKCsAP_AAH_AAAqIHFNf_X_fb3_j-_59_9t0eY1f9_7_v-0zjgeds-8Nyd_X_L8X5mM7vB36pq4KuR4Eu3LBAQdlHOHcTUmw6IkVqTPsbk2Mr7NKJ7PEinMbe2dYGH9_n9XT_ZKY79_____7__-_____7_f__-__3_vp9V---wOJAIMBAUAgAEMAAQIFCIQAAQhiQAAAABBCIBQJIAEqgAWVwEdoIEACAxAQgQAgBBQgwCAAQAAJKAgBACwQCAAiAQAAgAEAIAAEIAILACQEAAAEAJCAAiACECAgiAAg5DAgIgCCAFABAAAuJDACAMooASBAPGQGAAKAAqACGAEwALgAjgBlgDUAHZAPsA_ACMAFLAK2AbwBMQCbAFogLYAYEAw8BkQDOQGeAM-EQHwAVABWAC4AIYAZAAywBqADZAHYAPwAgABGAClgFPANYAdUA-QCGwEOgIvASIAmwBOwCkQFyAMCAYSAw8Bk4DOQGfCQAYADgBzgN_CQTgAEAALgAoACoAGQAOAAeABAACIAFQAMIAaABqADyAIYAigBMgCqAKwAWAAuABvADmAHoAQ0AiACJgEsAS4AmgBSgC3AGGAMgAZcA1ADVAGyAO8AewA-IB9gH6AQAAjABQQClgFPAL8AYoA1gBtADcAG8AOIAegA-QCGwEOgIqAReAkQBMQCZQE2AJ2AUOApEBYoC2AFyALvAYEAwYBhIDDQGHgMiAZIAycBlwDOQGfANIAadA1gDWQoAEAYQaBIACoAKwAXABDADIAGWANQAbIA7AB-AEAAIKARgApYBT4C0ALSAawA3gB1QD5AIbAQ6Ai8BIgCbAE7AKRAXIAwIBhIDDwGMAMnAZyAzwBnwcAEAA4Bv4qA2ABQAFQAQwAmABcAEcAMsAagA7AB-AEYAKXAWgBaQDeAJBATEAmwBTYC2AFyAMCAYeAyIBnIDPAGfANyHQWQAFwAUABUADIAHAAQAAiABdADAAMYAaABqADwAH0AQwBFACZAFUAVgAsABcADEAGYAN4AcwA9ACGAERAJYAmABNACjAFKALEAW4AwwBkADKAGiANQAbIA3wB3gD2gH2AfoBGACVAFBAKeAWKAtAC0gFzALyAX4AxQBuADiQHTAdQA9ACGwEOgIiAReAkEBIgCbAE7AKHAU0AqwBYsC2ALZAXAAuQBdoC7wGEgMNAYeAxIBjADHgGSAMnAZUAywBlwDOQGfANEgaQBpIDSwGnANYAbGPABAIqAb-QgZgALAAoABkAEQALgAYgBDACYAFUALgAYgAzABvAD0AI4AWIAygBqADfAHfAPsA_ACMAFBAKGAU-AtAC0gF-AMUAdQA9ACQQEiAJsAU0AsUBaMC2ALaAXAAuQBdoDDwGJAMiAZOAzkBngDPgGiANJAaWA4AlAyAAQAAsACgAGQAOAAigBgAGIAPAAiABMACqAFwAMQAZgA2gCGgEQARIAowBSgC3AGEAMoAaoA2QB3gD8AIwAU-AtAC0gGKANwAcQA6gCHQEXgJEATYAsUBbAC7QGHgMiAZOAywBnIDPAGfANIAawA4AmACARUA38pBBAAXABQAFQAMgAcABAACKAGAAYwA0ADUAHkAQwBFACYAFIAKoAWAAuABiADMAHMAQwAiABRgClAFiALcAZQA0QBqgDZAHfAPsA_ACMAFBAKGAVsAuYBeQDaAG4APQAh0BF4CRAE2AJ2AUOApoBWwCxQFsALgAXIAu0BhoDDwGMAMiAZIAycBlwDOQGeAM-gaQBpMDWANZAbGVABAA-Ab-A.YAAAAAAAAAAA","consent_required":false},"debug":true}' http://pbs-front-01.mediasquare.fr/msq_prebid`
The response is in file curl_consent_but_gdpr_false.json from the attached archive
You can also find the cookie value used as file cookies_pbs in the attached file.

So when regs.ext.gdpr:1 for this consent string, PBS does not send the buyeruid to rubicon.

[test_gdpr.zip](https://github.com/prebid/prebid-server/files/6022148/test_gdpr.zip)

**Comment by bretg** [comment]
I've confirmed that rubicon is appropriately linked to GVLID 52 in PBS-Go. I'm wondering if this could be related to aliases.

You're defining the following aliases:
```
"msqRubiconBrand":"rubicon",
"msqRubiconClassic":"rubicon",
```
@hhhjort confirms that PBS-Go should inherit the GVLID from the 'parent', which in this means that msqRubiconBrand should be linked to rubicon, which is linked to GVLID 52.

However, we should test this. @matthieularere-msq can you try setting up a bid directly to 'rubicon' -- i.e. try it without using an alias and see if buyeruid is sent.

**Comment by matthieularere-msq** [comment]
Hi @bretg ,

It would not make that much sense considering that the same aliases are used on other publishers without troubles. The examples I gave previously with 20minutes.fr can show that

**Comment by bretg** [comment]
@matthieularere-msq - I don't know what else to do. I feel pretty certain it's not an adapter issue. I'm going to have to ask a PBS-Go person to take a look, but this is a difficult environment to debug. Please provide sample PBS JSON (so we don't have to deal with your front end) and confirm that http://pbs-front-01.mediasquare.fr:8000/ is the place to post it.

**Comment by matthieularere-msq** [comment]
Hi @bretg 

I confirm you can send requests to http://pbs-front-01.mediasquare.fr:8000/openrtb2/auction

Here are two PBS JSON that are interesting, the requests are exactly the same except but their consent string. One was taken from the publisher where rubicon does not have buyeruid (programme-tv.net) and the other one is from 20minutes where rubicon does have buyeruid.

uids cookie value is the following in both case (can be found in my previous attached file too) : 
`uids=eyJ0ZW1wVUlEcyI6eyJhZG54cyI6eyJ1aWQiOiI1MTYyODM5NDYxNzc2MzE1NzE5IiwiZXhwaXJlcyI6IjIwMjEtMDMtMDRUMTY6MjY6MjIuMTU5NTYwNDg5KzAxOjAwIn0sInJ1Ymljb24iOnsidWlkIjoiS0NHN0lDU0wtMU0tREw1UiIsImV4cGlyZXMiOiIyMDIxLTAzLTA1VDA5OjA1OjU0LjU0Nzk1MTkzMSswMTowMCJ9LCJzbWFydGFkc2VydmVyIjp7InVpZCI6IjY1ODMzNTEyNDgzMjk4MTczNDkiLCJleHBpcmVzIjoiMjAyMS0wMy0wNFQxNjoyMDoxMC4zOTk0NDA4NjQrMDE6MDAifX0sImJkYXkiOiIyMDIxLTAyLTE4VDE2OjE5OjQ1LjM1MDk5NDg2OCswMTowMCJ9`

As the only difference is the consent string, I guess it should mean that the issue is with the consent string from programme-tv.net
Though if I decode it I can't see where anything is set to false that could disallow rubicon to get the buyeruid.

[pbs_json.zip](https://github.com/prebid/prebid-server/files/6039279/pbs_json.zip)

**Comment by bretg** [comment]
This is much easier to work with, thanks. Found an interesting thing ... when I paste the consent from pbs_consent_20minutes.json into pbs_consent_programmetv.json it works.

The thing that stands out about the consent in pbs_consent_programmetv.json is that it's very large. My hunch is that there's a limit to how large a consent string PBS-Go is supporting.

@SyntaxNode - please take a look?

**Comment by SyntaxNode** [comment]
There are no restrictions on consent string length in PBS-Go.

The consent string in the `pbs_consent_20minutes.json` file declares vendor legitimate interest for Rubicon (ID: 52), but the consent string in the `pbs_consent_programmetv.json` does not.

**Comment by matthieularere-msq** [comment]
Hi @SyntaxNode

When I check the consent string from `pbs_consent_programmetv.json` in https://iabtcf.com/#/decode and check "vendor consents" id 52 is set to true. So how would vendor legitimate interest be relevant while vendor consent is ok ? If the user did consent the purposes, legitimate interest is not required as the purpose is already filled.

Here is how vendor id 52 is configured in https://vendorlist.consensu.org/v2/vendor-list.json :

`52":{"id":52,"name":"The Rubicon Project, Inc. ","purposes":[1],"legIntPurposes":[2,7,10],"flexiblePurposes":[2,7,10],"specialPurposes":[1,2],"features":[],"specialFeatures":[1],"policyUrl":"https://www.rubiconproject.com/rubicon-project-yield-optimization-privacy-policy/","overflow":{"httpGetLimit":128},"cookieMaxAgeSeconds":31536000,"usesNonCookieAccess":false}`
legitimate purposes are 2, 7 and 10 and they also are flexibles which should means that they could granted either by consent or by legitimate interest.

Rubicon already confirmed me that they do consider this consent as valid for there own use.

Thanks

**Comment by hhhjort** [comment]
Seems to be a problem with publisher restrictions and a bug in PBS-Go. Rubicon declares flexible on 2,7, and 10, with legitimate interest being primary. Publisher restrictions state Rubicon is governed by type 1 (must have consent). Seems we were a little over-strict, and the code requires that Rubicon not only have consent, but declare the purpose as primary (rather than legitimate interest). The relevant code is `gdpr/impl.go:183 checkPurpose()` and should not be too difficult to fix.

**Comment by bretg** [comment]
Thanks for looking into this @hhhjort !  A gentle reminder that we developed a full truth table for testing this complicated thing...

https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.yi2g72nzg1zj
See "Truth Tables for Full Enforcement Scenarios"
