### ISSUE TITLE
Where is the create table file for postgresql store_request ?

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1711]
Hello,

I installed the Prebid Server and connect it to postgresql server for store_request.
The problem is that i don't find the init script to create the tables for postgresql.

Do you know where i can find it ?

Thanks

**Comment by bretg** [comment]
The answer is that we don't dictate any particular schema. 

https://docs.prebid.org/prebid-server/features/pbs-storedreqs-go.html shows that the DB approach is configurable:
```
stored_requests:
  postgres:
    host: localhost
    port: 5432
    user: db-username
    dbname: database-name
    query: SELECT id, requestData, 'request' as type FROM stored_requests WHERE id in %REQUEST_ID_LIST% UNION ALL SELECT id, impData, 'imp' as type FROM stored_imps WHERE id in %IMP_ID_LIST%;
```

If this were your query, the minimum schema would be
- id
- requestData

But of course you might want to add a primary key, an account ID, create/update timestamps, etc. Whatever your internal data requirements are.

I'll take an item to describe this a little more on https://docs.prebid.org/prebid-server/hosting/pbs-hosting.html

**Comment by mouchii** [comment]
Thanks for informations
