### ISSUE TITLE
Pass Global Privacy Control header to bidders

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1712]
We've discussed the latest Global Privacy Control (GPC) with privacy lawyers and would like to start simply by passing the HTTP header along to bidders. 

Per https://globalprivacycontrol.github.io/gpc-spec/, the header is `Sec-GPC`

All PBS needs to do is copy the Sec-GPC HTTP header from the original request through to the bidder endpoints.

**Comment by viveknarang** [comment]
Hi @bretg I wanted to bring to your attention [this approach](https://github.com/prebid/prebid-server/pull/1789/files#diff-9901dba73134efb17928d7f25f4569f684ab511119f10a691ce7d7fc657ca535R138-R142) as passing the header to adapter servers in the HTTP headers isn't mentioned in the PBS specifications as suggested by @SyntaxNode [here](https://github.com/prebid/prebid-server/pull/1789#discussion_r630518613)

I will really appreciate it if you can provide some guidance here. Thanks in advance.

**Comment by SyntaxNode** [comment]
@viveknarang I misunderstood this proposal. I originally thought we needed to pass this flag to bidder adapters, but we do indeed need to pass it to bidder requests as a header. We're good here.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.161.0.

**Comment by viveknarang** [comment]
@SyntaxNode I will be happy to implement this in the Java version if no one else is already working on it. Please let me know. Thanks!
