### ISSUE TITLE
store_requests and accounts_account tables

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1713]
Hello,

I would like to know when this tables will be fill ?
Because i refresh my page with prebidjs connected to my prebid server, display ads, but nothing is fill in database ...

I don't understand, could you please explain me ?

Thanks

**Comment by bretg** [comment]
As noted in https://docs.prebid.org/prebid-server/hosting/pbs-hosting.html

```
Note that there aren’t any open source tools for populating this database. Each PBS host company establishes their own methods of populating data from their internal systems.
```
i.e. this is where you integrate your internal systems on your own. It's fine to start off with just manual DB inserts.
