### ISSUE TITLE
Prebid Server - Adapter who is just a gateway

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1720]
Hello,

If i would like that in prebid.js configuration, the bidder was mine (with my name) and call my prebid-server adapter who call many ssp, it is possible ?
(To be clear, In prebid.JS i will set bidder: 'mybidder' and in mybidder adapter i will call my prebid server who will call many ssps)

Any solution to do that simply ? (All the adapters of SSP i need already exist)

Thanks

**Comment by mansinahar** [comment]
@mouchii If I understand correctly, you want to be able to get bids from SSPs that are supported by Prebid Server via Prebid.js, correct? If so, you can just have your request going to Prebid.js be confgured to use the Prebid Server adapter with the bidders (SSPs) you'd like to get bids from.

You can read more about how to use Prebid Server with Prebid.js [here](https://docs.prebid.org/prebid-server/use-cases/pbs-pbjs.html).

**Comment by mouchii** [comment]
Hi Mansinahar,

Thanks for your reply.
The problem is that i would like to have my own Prebid.JS adapter. (I don't want that publishers set the ssps list...)

**Comment by matthieularere-msq** [comment]
Hi,

That's what I did with my Prebid.js adapter. But I don't have an easy solution for you as it required to create an extra component hosted server side. The idea is : 
- Prebid.js adapter behave like any normal adapter, quite a simple one, calling some endpoints for bidding and cookie sync
- You create a server side application for you adapter's endpoints. This application generates an openrtb requests sent to prebid-server based on the request received.

**Comment by mouchii** [comment]
Hi,

Thanks for your reply.
Yes i think this type of solution is the best one.

I think about a similar solution, i think of create the openrtb request in my adapter and send it to the prebid server itself with ssps ... 

This is a little bit wobbly, but it will work ...

Thanks again.

**Comment by mansinahar** [comment]
> Hi Mansinahar,
> 
> Thanks for your reply.
> The problem is that i would like to have my own Prebid.JS adapter. (I don't want that publishers set the ssps list...)

@mouchii I see. In that case yeah you can do either of the two things above mentioned by you and @matthieularere-msq.

I will close this out for now but feel free to re-open if there's anything else you need help with :)

**Comment by mouchii** [comment]
Hi @matthieularere-msq ,

Just a question, how do you manage the user_sync endpoint ?

**Comment by matthieularere-msq** [comment]
I made it part of my bidding endpoint which contains two objects: one with the bids, one with the urls to sync with. I made it this way so my adapter does not have to call two endpoints but only one, as `getUserSyncs` is executed after `interpretResponse` and only if valid bid was found.

**Comment by mouchii** [comment]
Thanks for your reply.
I understand well how you manage that, but i can not do that, i need to keep openrtb format in input/output of requests.
I don't understand why in my pbs, when i call the cookie_sync endpoint i got a "status: no_cookie" response... So you think that if i setting up new endpoint in PBS where i just reply the list of URLS of gateway's SSP, it will be work ?

**Comment by matthieularere-msq** [comment]
I can't tell you what's going on with your cookie_sync call without more details. I depends on what you already have your uids cookie and the payload sent to the endpoint.

I also don't understand how you expect your adapter to work in terms of ssps params as you said `I don't want that publishers set the ssps list` but your approach seems to require it to be made client side.

I would recommand you to "play" with PBS first. Make some tests using the existing pbs adapter, make sure it works and then try to replicate this based on what you need. Before building your own adapter, you need to plan its architecture which with such a use-case requires to understand how to interact with PBS endpoints.

**Comment by mouchii** [comment]
It is due to GDPR, when i enable it, no sync bidders url is return.

This is simple, it is exactly like you, the only difference is that i remove your adapter endpoint application, i create the request directly in my adapter and send it to prebid server itself...

Yes i know that, i already played with it :), it is just that i prefer to have a experienced feedback on it.

**Comment by sultanboss** [comment]
Hi @mouchii 

I am also interested to build something like that. I am not sure where to start. Do you think you can provide us some instructions as well as a code example?

Thanks!
