### ISSUE TITLE
AMP first party data v2

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1727]
The original implementation for AMP first party data was pretty complicated. Upon revisiting it, I'm thinking it was also incorrect in that it mixed GAM targeting with PBS FPD. So I'd like to significantly simplify. However, would like community members with AMP experience to weigh in.

## Assumptions
- The AMP "TGT" macro is resolved from json.targeting. Because these values are also utilized by GAM, there cannot be any additional structure imposed on this object.
- Dynamic values (e.g. user IDs or segments) are not supported in AMP. When they are, we will revise this spec.
- We could add additional fields to pass static data through the AMP call, but it's easier to just store them in the storedrequest database.
- Adding global first party data fields to the AMP storedrequests keyed to the stored request ID is feasible
- No one started making use of the original FPD implementation. No need for backwards compatibility.

## Requirements
1. The AMP openrtb in the stored request must be able to carry global site data.
2. The stored request must also be able to define bidder permissions either with ext.prebid.data.bidders or ext.prebid.bidderconfig.
    - It's ok if both kinds of permission are specified: i.e. every entry in ext.prebid.bidderconfig[].bidders would also need to be in ext.prebid.data.bidders or it will be ignored.
3. Some fields defined in the stored request will be overridden by values coming in on the query string:
    - curl overwrites site.page
    - account overwrites site.publisher.id if it's valid
4. Read the targeting attribute on the AMP query string. Add all key-value-pairs found there to imp[].ext.data.
5. PBS must adhere to privacy rules as for other interfaces:
    - Follow COPPA anonymization rules
    - Follow usp_privacy anonymization rules
    - Follow TCF1 anonymization rules
    - Follow TCF2 rules

## Examples

Here's an amp-ad tag that passes targeting data to GAM:
```
<amp-ad width="300" height="50"
    type="doubleclick"
    data-slot="/1111/amp_test"
    data-multi-size-validation="false"
    rtc-config='{"vendors": {"prebidrubicon": {"REQUEST_ID": "blah"}}}'
    json='{ "targeting": {"gam-key1": "val1","gam-key2": "val2"}}' >
  </amp-ad>
```
This ends up calling the PBS AMP endpoint with something like:

GET /openrtb2/amp?tag_id=blah&w=300&h=250&ow=&oh=&ms=&slot=%2F1111%2Famp_test&targeting=%7B%22gam-key1%22%3A%22val1%22%2C%22gam-key2%22%3A%22val2%22%7D&...

Which would wind up being merged into the storedrequest openrtb imp like this:
```
{
  ...
  "imp": [
    ...
    "ext": {
       "data": {
           "gam-key1": "val1",
           "gam-key2": "val2"
       }
    }
  ]
}
```

**Comment by mjwhaley** [comment]
@bretg This seems to make complete sense and a logical path forward. The bidder permissions would need to cover what keys to pass and to which bidders.

**Comment by bretg** [comment]
@mjwhaley - FYI, bidder permissions aren't currently quite so surgical. See [setBidderConfig](https://docs.prebid.org/dev-docs/publisher-api-reference.html#setConfig-fpd) documentation.

**Comment by bretg** [comment]
This is done in PBS-Java

**Comment by VeronikaSolovei9** [comment]
@bretg if imp.ext has "data" already - should we throw an error, replace existing or add new field to existing "data"?

**Comment by bretg** [comment]
@VeronikaSolovei9 - merge please.

The definition of "merge" was discussed in a recent committee meeting:

- Deep merge, with incoming request values taking precedence if they exist on both sides.
- Deep merge means arrays are replaced, not merged. Even arrays of objects.

**Comment by VeronikaSolovei9** [comment]
Thank you! Will add this change.

**Comment by VeronikaSolovei9** [comment]
Hi Bret @bretg,
currently to make this feature available, we just need to enable FPD processing for AMP endpoint. Everything else is already supported. 
Now in code we have this check: 
```
if r.RequestType == metrics.ReqTypeORTB2Web || r.RequestType == metrics.ReqTypeORTB2App {
		//Extract First party data for auction endpoint only
		resolvedFPD, fpdErrors := firstpartydata.ExtractFPDForBidders(r.BidRequestWrapper)

...
```
which means FPD processing is disabled intentionally. 
I just want to confirm we want to enable FPD for AMP endpoint.

**Comment by VeronikaSolovei9** [comment]
Bret,
Yes, it's confusing, sorry about it. This is not a special form, it's only one `if` case in code that will enable FPD processing for AMP. In current implementation FPD is a part of auction processing that is common for `amp` and `auction` endpoints. 
If we enable it for amp it will support everything that is already supported in auction endpoint. 

This is why I need your help to confirm what differences will be in `amp` FPD processing. 

Here are the requirements from above with comments. 

> The AMP openrtb in the stored request must be able to carry global site data.

Yes, amp stored request is a full opentrb request and can carry user, site or app global data

>The stored request must also be able to define bidder permissions either with ext.prebid.data.bidders or ext.prebid.bidderconfig.

Yes, this can be added to stored request too

>It's ok if both kinds of permission are specified: i.e. every entry in ext.prebid.bidderconfig[].bidders would also need to be in ext.prebid.data.bidders or it will be ignored.

Amp request will be processed in the same way we now process auction requests

>Some fields defined in the stored request will be overridden by values coming in on the query string:
>curl overwrites site.page

Not sure i understand what is this. Is this something applicable to PBS?

>account overwrites site.publisher.id if it's valid

I belive this is a part of common auction logic, should be there already, I'll confirm with the team

>Read the targeting attribute on the AMP query string. Add all key-value-pairs found there to imp[].ext.data.

This is already done. Current FPD processing doesn't do anything with `imp.ext` 

>PBS must adhere to privacy rules as for other interfaces:
>Follow COPPA anonymization rules
>Follow usp_privacy anonymization rules
>Follow TCF1 anonymization rules
>Follow TCF2 rules

This should also be a part of common auction logic, I'll confirm with the team.

It looks like everything is already in place. 
I may miss something. If so, please help me to understand what is missing.

**Comment by bretg** [comment]
Discussed in committee. Agreed that we need to define the behavior when the query string is too long.

The proposal is that if the targeting is not valid JSON (e.g. query string too long), ignore it and don't merge to imp.ext.data

**Comment by VeronikaSolovei9** [comment]
Thank you for the answers, it's now all clear to me. 
I was confused by "curl overwrites site.page" and  it appears this is query param, not terminal command :)
I'm going to put a PR shortly with FPD available for `amp` endpoint and a with a fix for "if the targeting is not valid JSON (e.g. query string too long), ignore it and don't merge to imp.ext.data"
Thank you!
