### ISSUE TITLE
Beachfront: Empty array returned from endpoint should result in 204 response

### ISSUE THREAD

**Issue by muncha** [prebid/prebid-server#1728]
As per email from Karen Lim <karen.lim@xandr.com>:

Reaching out regarding Status 200 with empty responsebody being returned for Gourmet Ads’ bid request. Wondering if it is possible for Beachfront to return Status 204 instead of 200 with error since this isn’t an error but an empty response using [https://github.com/prebid/prebid-server/blob/master/adapters/beachfront/beachfront.go#L488]? Thank you!

**Comment by muncha** [comment]
I'll put in a PR for this today. I'm not sure if I really should have made an issue for it, as I can't assign it to myself.

**Comment by SyntaxNode** [comment]
Thank you for looking into the issue. I think the key is for Beachfront to not return an error if there are no bids.

**Comment by muncha** [comment]
Yep, that works as far as not throwing an error , but changing the response code that is reported seems a bit trickier than I naively assumed. I'm going to get with the maintainer of that endpoint and see If I can get a 204 instead of the current response.

**Comment by muncha** [comment]
Beachfront is setting up an optional parameter on the endpoint that will send the 204.

**Comment by SyntaxNode** [comment]
@muncha I believe this work is complete. May we close this issue?

**Comment by muncha** [comment]
Yes please.

**Comment by muncha** [comment]
I've got it
