### ISSUE TITLE
Modular Architecture for Prebid Server

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1734]
Prebid Server (PBS) started as a simple server that just obtained header bids from a list of other server endpoints and forwarded the results back to the client.

Through the years, feature functionality has grown: currency conversion, events, privacy support, targeting options, first party data, etc. PBS host companies can turn off these features from server config, but they still bear the cost of additional server resources to host the unused features.

There's a long-term vision that PBS becomes the center of an ecosystem similar to what Prebid.js has become: many optional modules, perhaps even overlapping or mutually exclusive such as geo-lookup vendors or multiple brand protection modules.

As the server gets more and bigger features, it may not make sense for all companies hosting PBS to bear the cost and complexity of hosting and configuring all features.

To summarize, the high level goal of the project is to encourage a larger ecosystem of Prebid Server optional functionality without unduly burdening host companies. The most important component of this goal is a useful, consistent, and well-documented set of interfaces for extending server functionality. Some existing functionality may eventually be pulled out into modules (e.g. geo-lookups), but that refactoring will take time.

It is not intended that every future feature must be a module. There will be small features embedded directly in PBS-core, and perhaps even large complex features (e.g. Programmatic Guaranteed) that might not work well as a series of modules.

See https://docs.google.com/document/d/1QgQbIL06dsQQw-Qmw_JClXNsbjDmYQ09gU7iu6iox_M/edit# for the in-progress requirements document.

**Comment by bretg** [comment]
Update: this project is underway

**Comment by SyntaxNode** [comment]
Core functionality implemented in PBS-G0 0.238.0. OpenRTB Blocking Module implemented in PBS-Go 0.239.0.
