### ISSUE TITLE
Document what PBS-core removes from ext.prebid

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1736]
A new aspect of the multi-bid feature has been requested in https://github.com/prebid/prebid-server/issues/1715

```
14. Bid adapters should know how many bids they're allowed to submit.
i.e. they should have access to ext.prebid.multibid, but of course only
the entry that involves them.
```

I'd like to make sure that PBS-Java and PBS-Go are aligned when it comes to what's removed from ext.prebid before sending to bid adapters. 

PBS-Java removes:

- request.ext.prebid.schains
- request.ext.prebid.data
- request.ext.prebid.bidderconfig
- leaves only corresponding bidder for:
    - request.imp[].ext.BIDDER
    - request.ext.multibid[].bidder:BIDDER

Other fields that should probably be removed:
- request.ext.prebid.aliases (for other bidders)
- request.ext.prebid.bidadjustmentfactors
- request.ext.prebid.cache
- request.ext.prebid.targeting
- request.ext.prebid.adservertargeting
- request.ext.prebid.multibid (for other bidders)

**Comment by bretg** [comment]
Discussed in Prebid Server committee. @SyntaxNode to confirm what happens in PBS-Go

**Comment by SyntaxNode** [comment]
It looks like we're aligned (or will be in the near future) with removal of data `request.ext.prebid`.

PBS-Go currently removes:
- request.ext.prebid.schains

PBS-Go will remove the following with the implementation of First Party Data:
- request.ext.prebid.data
- request.ext.prebid.bidderconfig
- leaves only corresponding for bidder request.ext.prebid.bidders.<BIDDER_PARAMS>

**Comment by SyntaxNode** [comment]
@bretg I think we can close this issue. You've documented this information in https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#prebid-server-ortb2-extension-summary and we'll fix any gaps in https://github.com/prebid/prebid-server/issues/2321.
