### ISSUE TITLE
Pass host company config info to bid adapters

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1739]
We discussed in Prebid Server committee a desire from some adapters to know which cluster of Prebid Servers is sending requests to their endpoints. 

The proposal is that PBS should start sending identifying information that will be sent to each bid adapter, where they can determine what's relevant for their endpoint
- `external-url` on ext.prebid.server.externalurl
- `gdpr.host-vendor-id` on ext.prebid.server.gvlid
- `datacenter-region` on ext.prebid.server.datacenter

Since datacenter location is not a standard and this info is for debugging and reporting, we're not proposing any syntax or valid values here.

The committee agreed that it makes sense to place the host company info on both the JSON body and in a configuration data structure available to bid adapters.

**Comment by grossjo** [comment]
Should there be consistency on data centre regions?  Maybe something like ISO country codes, or is there need for more granularity in places like the US?

**Comment by bretg** [comment]
I don't think standardizing on datacenter values is practical. There are often multiple datacenters in the US (east/west), and the particular country isn't really that important. For instance, Magnite currently uses 6 datacenters, all based out of Amazon regions. But we may shift to 'bare metal'  hosting at some point, and the "Europe-Central" might move from Germany to the Netherlands for instance. Or US-East from Virginia to wherever.

However, if there's a standard I'm not aware of, we'll discuss in committee.

**Comment by bretg** [comment]
released with PBS-Java 1.88

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.229.0.
