### ISSUE TITLE
Trouble monitoring Prebid Server to respond to GET on / endpoint

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1749]
Hello,

I would like to monitore my prebid server response (http code 200).
A call is made every 10s.

Something is strange, two/three times per hour, the server reply in 3s instead of 30ms normaly.

Someone already got this problem ?

Thanks

**Comment by bretg** [comment]
- What version of PBS are you running?
- Are you running PBS in AWS? 
- There's not really a / endpoint. You might want to monitor /auction, /setuid, /info/bidders, etc.
- To verify that it's not a network problem, you might want to set up a ping to run in parallel and see if you see network delays at the same time

**Comment by SyntaxNode** [comment]
@mouchii Are you still encountering this problem? If so, could you please provide the additional information requested?

**Comment by mouchii** [comment]
Hi,

I got the version 0.149.0. This is hosted in dedicated server, exposed in proxy mode behing nginx.
I try to monitor /info/bidder/XXXX and the / endpoints, but the result is the same.

Take a look on my grafana charts : 
https://pasteboard.co/JWl8qlD.png

I don't understand what's happened, it is very strange...

**Comment by mouchii** [comment]
I just tried to monitor directly on the go server port and now it reply in few ms...
Someone know that using Nginx in proxy mode can be a problem ? How do you host the prebid server ? Do you expose directly the go server ?

**Comment by mouchii** [comment]
https://github.com/gotify/server/issues/288

**Comment by SyntaxNode** [comment]
Nice find!

For what it's worth, we also run PBS behind an nginx proxy. So you're in good company. We haven't run across this specific issue before.
