### ISSUE TITLE
Influxdb metrics are scaling with number of containers

### ISSUE THREAD

**Issue by bastianb-yl** [prebid/prebid-server#1771]
Hi, i have a bit of a weird problem.

We used to run prebid server on an EC2 instance, but switched to AWS Fargate, beause our traffic got more dynamic. Since then the metrics of prebid server are moving according to the number of tasks (containers) in the cluster. If i double the amout of containers, the metrics go down to ba half. Is that normal?

**Comment by SyntaxNode** [comment]
What exactly do you mean by "metrics go down". Are you referring to the number of metrics collected or their value? If it's the latter, which metrics are you observing the problem with?

**Comment by bastianb-yl** [comment]
No no, i mean the chart just drops..

For example, i have two metrics:
- prebidserver.account.customer1.openx.requests.nobid.meter
- prebidserver.account.customer1.openx.requests.gotbids.meter

Let's say the first is about 40 and the second roundabout 10. And i like 10 containers running prebid server in the cluster. Now i add 10 more container and the charts drop to 20 and 5.

<img width="400" alt="945366578" src="https://user-images.githubusercontent.com/51324700/112016768-4dccf900-8b2d-11eb-8561-25e337d38acb.PNG">

**Comment by SyntaxNode** [comment]
Gotcha. I would expect some metrics such request latency would go down with more clusters to spread the load, but clearly request counts should not.

Let's first double check all instances are correctly configured to talk to the same InfluxDB node or that your queries are aggregating correctly across several nodes.

InfluxDB has the possibility of data loss if the app is having trouble connection to InfluxDB. Do the PBS logs reveal any connection issues?

**Comment by bastianb-yl** [comment]
All containers are created automatically by fargate using the same image. So they are all configured the same. Logs show no connection problems.

What you mean by "queries are aggregating correctly across several nodes"? InfluxDB is installed on just one EC2 instance and not in multiple container. The setup with the containers only applies to PBS, but InfluxDB has only one node.
So multiple identical PBS containers sending metrics to one InfluxDB installation.

The only thing i can think of is, that for some reason InfluxDB thinks it gets redundant data and ignores some of it.

**Comment by SyntaxNode** [comment]
I've never experienced this issue with our InfluxDB servers. I suspect it's related to the accumulation behavior, perhaps related to redundant data filtering as you've suggested or perhaps an issue with your queries. Our InfluxDB queries using Grafana look something like this:

```
SELECT sum("m1") FROM prebidserver.account.customer1.openx.requests.gotbids.meter WHERE $timeFilter GROUP BY time(60s)
```

**Comment by SyntaxNode** [comment]
I'm closing this issue since I believe it is related to InfluxDB configuration. If you suspect a PBS-Go bug and have new information to share, you are welcomed to re-open this ticket or submit a new one.
