### ISSUE TITLE
Authorization leak through headers

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/prebid-server#1776]
If "test" is specified in the call to PBS, the debug info coming back contains all headers sent to the endpoints.

e.g. There can be a basic authentication key exposed. Even though it's not the actual user/password it feels like not something that should be publicly exposed.

**Comment by bretg** [comment]
Thanks for the bug report @bjorn-lw

**Comment by SyntaxNode** [comment]
Good catch. We missed that the Rubicon adapter makes use of the authorization header.

Are you ok with us keeping the header debugging feature and replacing the content of the auth header with a literal `<HIDDEN BY PREBID SERVER>` value?
