### ISSUE TITLE
usersync_if_ambiguous -> default_value. require default_value to be configured by host.

### ISSUE THREAD

**Issue by Jobeso** [prebid/prebid-server#1783]
Hey Prebid Team,
I updated our self hosted prebid-server from 0.138.0 to 0.153.0. Since that change I see an impression drop of 80%. Rolling back this update seems to be a temporary fix.

The drop is not os related and is an issue on iOS and Android. Also, it's not EEA related, also happens for countries outside of the EU. All bidders are effected except for OpenX.

I checked the changelogs between the versions but didn't see any breaking changes. Did I miss anything there? How would you approach debugging this?

Thanks in advance for your help.

**Comment by SyntaxNode** [comment]
HI @Jobeso,

That's no good. We didn't intend to introduce a breaking change, but it seems something slipped by us. Sorry for that. Let's figure it out and fix it.

These sort of issues are almost always related to privacy policies. We tweaked some of the GDPR settings at the start of the year to better align with the specs. I suspect one of these changes had unintended side affects.

To start, what are your GDPR settings? Specifically: `gdpr.enabled`, `gdpr.host_vendor_id`, and `gdpr.usersync_if_ambiguous`.

**Comment by Jobeso** [comment]
Hey @SyntaxNode,
thanks for the quick answer. I suspect that whatever is breaking might only be for our setup so I suppose rather a mistake from our side.

We run a rather basic setup with no huge modifications of the default values. This is true for your above mentioned flags as well, we do not set them explicitly, default values seem to be the following and they did not change from 0.138.0 to 0.153.0.

```
gdpr.enabled: true
gdpr.host_vendor_id: 0
gdpr.usersync_if_ambiguous: false
```

It's a bit hard for me to find documentation on these to understand what's missing from our end. I found your [comment](https://github.com/prebid/prebid-server/pull/1775#issuecomment-808525543) and this [discussion](https://github.com/prebid/prebid-server/issues/1393) that explains this kinda but I'm still struggling with understanding what we should change here. 

With our prebid-server we only enable bidding for our own app (iOS & Android). We gather the consent with a cmp and the consent string is automatically added with prebid-mobile to the requests.

I really appreciate the work you and your team are doing and thanks for your help with this issue.

**Comment by SyntaxNode** [comment]
Thank you sharing your GDPR configuration. I've identified the issue as an unintended side effect of [this change](https://github.com/prebid/prebid-server/pull/1656).

Prior to this change, Prebid Server would not enforce GDPR if the host vendor id was left at the default 0 value. If that's the functionality you want, the modern equivalent is setting `gdpr.enabled` to `false` (the default is `true`). I suspect this was the result of an over emphasis on the cookie syncing aspect of GDPR regulations. We've been focusing this year on correcting those missteps.

So, what does this have to do with requests which don't include GDPR information? There is another setting `gdpr.usersync_if_ambiguous` which defaults to `false`. The name is absolutely misleading and it's on our list to fix (or we always welcome community PRs :) ).  A more accurate name might be something like `skip_gdpr_when_missing`. If a request doesn't specify the `regs.ext.gdpr` flag and `usersync_if_ambiguous` is set to `false` (this is the default), Prebid Server will treat the request as having `regs.ext.gdpr = 1`.

I think we should leave `gdpr.enabled` set to `true` by default and change `gdpr.usersync_if_ambiguous` to now default to `true`. What do you think?

**Comment by bretg** [comment]
We met in committee on Friday and agreed to move forward with these related changes:

1) drop usersync_if_ambiguous in favor of gdpr.default-value
2) Make gdpr.default-value a required config value - instead of having an overall default, host companies will need to explicitly choose a value.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.164.0.

Starting with this release, `usersync_if_ambiguous` is replaced with `default_value` and requires a host (or dev) provided value for PBS to start.

**Comment by bretg** [comment]
PBS-Java never supported the usersync_if_ambiguous flag, and already supported/documented `default_value`. Closing this issue.

**Comment by SyntaxNode** [comment]
> We met in committee on Friday and agreed to move forward with these related changes:
> 
> 1. drop usersync_if_ambiguous in favor of gdpr.default-value
> 2. Make gdpr.default-value a required config value - instead of having an overall default, host companies will need to explicitly choose a value.

This issue was kept open and tagged with PBS-Java to address item 2 of your notes from April 19.

**Comment by bretg** [comment]
PBS-Java 1.71 requires `gdpr.default-value`
