### ISSUE TITLE
Problems with a incorrect size

### ISSUE THREAD

**Issue by prebidtappx** [prebid/prebid-server#1793]
Hi
A few hours ago we encountered strange behavior with one of our users. From what we have observed, our client sends prebid server requests focused on the app, but a site object is returned with a 1x1 size. What can be the cause of this behavior?

**Comment by SyntaxNode** [comment]
Could you please elaborate on the details of "but a site object is returned with a 1x1 size"? .. and please provide sample (anonymized) requests and responses please.

**Comment by prebidtappx** [comment]
Hi, yes!!
It is very strange, we have this publisher that only have app inventory for IOS, but we are receiving the response that we attach on this message. The normal behavior is a correct size and with app object instead the site object.

[1x1-error.txt](https://github.com/prebid/prebid-server/files/6276711/1x1-error.txt)

**Comment by SyntaxNode** [comment]
Thank you for providing additional information. This looks to me like an issue with the MobileSDK generating an incorrect bid request.

The sample request is for Xandr's bidding server. If you suspect this is a Xandr specific problem, please close this issue and email us directly at prebid-server@xandr.com.

**Comment by prebidtappx** [comment]
Hi! We are going to write to prebid-server@xandr.com.
I close the issue in this place.
Thanks for all.
