### ISSUE TITLE
Support client analytics indicator

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1800]
We're running into issues with trying to coordinate between client and server analytics -- who's responsible for logging the auction event. Those avid readers of this forum will be aware we've made a number of changes making this part of the system more complex -- all towards the end of trying to make sure analytics events are logged in only one place.

Still, our Product team is pushing even more complicated and fragile scenarios, so I'm driven to propose an explicit signal between client and server to let server analytics adapters know explicitly about the state of client-side analytics.

The proposal is to add an object that can be created client-side like this:

- ext.prebid.analytics: {rubicon: { client-analytics: true }}

PBS-Core just needs to make this available to the analytics adapters so they can handle the messages as appropriate.

1) loop through ext.prebid.analytics object
2) if there's an unknown "adapter", log a warning and ignore
3) otherwise, before calling analytics adapter ABC, remove any object not belonging to that adapter code.
4) No other validations are done, not even the existence of another attribute -- each analytics adapter can have its own signaling protocol.

**Comment by SyntaxNode** [comment]
Seems good to me. Just to clarify, the `adapter: "rubicon"` mention in the original post is for the analytics adapter and not the bid adapter.
