### ISSUE TITLE
GDPR configuration to transfer UIDs

### ISSUE THREAD

**Issue by gchicoye** [prebid/prebid-server#1801]
Hi everybody,

I'm struggling configuring GDPR module.
I'm running the lastest PBS release (0.155) on a Kubernetes cluster. I've got a GPDR vendorId (965)

I'm doing some tests on /openrtb2/auction endpoint, with the following cookie implemented in header.
```
uids=eyJ0ZW1wVUlEcyI6eyJhZG54cyI6eyJ1aWQiOiI3ODU1NjA2NDQ0NDIxMTU2NDI0IiwiZXhwaXJlcyI6IjIwMjEtMDItMDlUMTM6MTc6MDEuNjQzNjY3MDU3WiJ9LCJvcGVueCI6eyJ1aWQiOiJkNWM3ZDVkZS1hOTNmLTAyOTktMDAzMC0xMWNhN2VlOTIyZjkiLCJleHBpcmVzIjoiMjAyMS0wMi0wOVQxMzoxNzowMS40OTcwMDY5ODVaIn0sInNtYXJ0YWRzZXJ2ZXIiOnsidWlkIjoiNTQ0MjQ0NzA2NDI5NDY1MTk5MSIsImV4cGlyZXMiOiIyMDIxLTAyLTA5VDEzOjE3OjAxLjgyNTI4Njc2NloifX0sImJkYXkiOiIyMDIxLTAxLTA4VDA4OjE4OjE4Ljg5MTI0OTE1M1oifQ==;
```

- Configuration 1 - GDRP disabled

My config is 
```
  PBS_GDPR_ENABLED: "false"
  PBS_GDPR_HOST_VENDOR_ID: "965"
  PBS_GDPR_AMP_EXCEPTION: "false"
  PBS_GDPR_USERSYNC_IF_AMBIGUOUS: "false"
```

In debug for the Appnexus call, I can see the following extract 
```
"user":{
  "buyeruid":"7855606444421156424",
  "ext":{
    "consent":"CPDd6MVPDd6MVAHABBENBSCsAP_AAH_AAAAAHnNf_X__b3_j-_59_9t0eY1f9_7_v-0zjhfds-8N2f_X_L8X42M7vF36pq4KuR4Eu3LBIQdlHOHcTUmw6okVrTPsbk2Mr7NKJ7PEinMbe2dYGH9_n93TuZKY7__8___z__-__v__7_f_r-3_3_vp9X---_e_V399xLv9cDygCTDUvgAsxLHBkmjSqFECEK4kOgFABRQjC0TWEDK4KdlcBHqCBgAgNQEYEQIMQUYsAgAAAgCSiICQA8EAiAIgEAAIAVICEABGwCCwAsDAIABQDQsQIoAhAkIMjgqOUwICJFooJ5KwBKLvY0whDKLACgUf0VGAiUIIFgAA.f_gAD_gAAAAA",
...
``` 

- Configuration 2 - GDRP disabled

My config is 
```
  PBS_GDPR_ENABLED: "true"
  PBS_GDPR_HOST_VENDOR_ID: "965"
  PBS_GDPR_AMP_EXCEPTION: "false"
  PBS_GDPR_USERSYNC_IF_AMBIGUOUS: "false"
```

In debug for the Appnexus call, I can see the following extract, buyeuid is not mentioned although the the consent string gives all authorization, including for my VendorId (965)
```
"user":{
  "ext":{
    "consent":"CPDd6MVPDd6MVAHABBENBSCsAP_AAH_AAAAAHnNf_X__b3_j-_59_9t0eY1f9_7_v-0zjhfds-8N2f_X_L8X42M7vF36pq4KuR4Eu3LBIQdlHOHcTUmw6okVrTPsbk2Mr7NKJ7PEinMbe2dYGH9_n93TuZKY7__8___z__-__v__7_f_r-3_3_vp9X---_e_V399xLv9cDygCTDUvgAsxLHBkmjSqFECEK4kOgFABRQjC0TWEDK4KdlcBHqCBgAgNQEYEQIMQUYsAgAAAgCSiICQA8EAiAIgEAAIAVICEABGwCCwAsDAIABQDQsQIoAhAkIMjgqOUwICJFooJ5KwBKLvY0whDKLACgUf0VGAiUIIFgAA.f_gAD_gAAAAA",
...
``` 

I don't know what to do at that stage!

Thanks a lot,

Gabriel

**Comment by SyntaxNode** [comment]
This may be a side affect of an issue fetching the GVL. Do you see the following entry in your container logs:
```
Error calling GET https://vendor-list.consensu.org/v2/archives/vendor-list-v82.json. Cookie syncs may be affected: context deadline exceeded
```

**Comment by gchicoye** [comment]
> This may be a side affect of an issue fetching the GVL. Do you see the following entry in your container logs:
> 
> ```
> Error calling GET https://vendor-list.consensu.org/v2/archives/vendor-list-v82.json. Cookie syncs may be affected: context deadline exceeded
> ```

Indeed, I've got this error... What could be the fix for this?

**Comment by gchicoye** [comment]
Hi,

Actually, I've added some timeouts, now it looks like working well :):)
```
  PBS_GDPR_TIMEOUTS_MS_ACTIVE_VENDORLIST_FETCH: "2000"
  PBS_GDPR_TIMEOUTS_MS_INIT_VENDORLIST_FETCHES: "2000"
```
