### ISSUE TITLE
Allow gzip compress for BidRequest backend communication with bidders

### ISSUE THREAD

**Issue by josepowera** [prebid/prebid-server#1812]
Some exchanges/DSPs have implemented support for compressed json BidRequest. This change could be system level, since it would be useful for many bidders in order to reduce bandwidth / latency from Prebid Server to DSP bidServer.  This option would have to be enabled per bidder.

Same goes for BidResponse from DSP back to Prebid Server.  In this case Prebid Server can decide based on  Content-Encoding: gzip header.

Is there any settins already available to enable this?  (this is similar to gzip handler to compress BidResponse from PrebidServer back to browser)

**Comment by bretg** [comment]
This is a good call @josepowera . We'll discuss in this week's PBS committee meeting.

**Comment by bretg** [comment]
We discussed today. The team agrees this is a worthwhile effort. We'll tackle it in three parts:

1) support compression on requests coming into PBS, with a length limit (any input from the community on the max size welcome)
2) support a bidder-config for outgoing requests. We may initially only support gzip.
3) verify that PBS bid adapter can send compressed requests

**Comment by bretg** [comment]
Proposing that we make the length limit configurable with a default of 50KB uncompressed. That seems like more than enough.

**Comment by SyntaxNode** [comment]
> Proposing that we make the length limit configurable with a default of 50KB uncompressed. That seems like more than enough.

PBS-Go (and likely PBS-Java) already include a configurable maximum request size with a default of 256KB. I'd like us to use the same configuration value for uncompressing compressed payloads, unless someone has a good reason for having separate values? We could always lower the default value is 256KB is too high.

**Comment by bretg** [comment]
Discussed in committee:
- start with gzip. Ignore deflate. We would like to support Brotli.
- the default length limit is still open, but we're leaning towards 256KB

**Comment by albertmolinermrf** [comment]
Marginally related: PBS-Java allows to [request compression from bidders](https://github.com/prebid/prebid-server-java/issues/288).

**Comment by rpanchyk** [comment]
@bretg how many bidders are planned to support compressed `BidRequest`s ?
Just want to clarify, if not so many of them - would it it be better to add only bidder-specific config? Something like we have for Conversant - `adapters.conversant.generate-bid-id`.

**Comment by bretg** [comment]
This fell through the cracks. Yes, I think there should be a bid adapter-level config that lets PBS know that the endpoint accepts certain encoding. e.g. 
```
adapters.CODE.endpoint-compression: gzip
```
For the record, this is different than the existing `http-client.use-compression` config in PBS-Java -- that just tells the endpoint the response can be encoded.

**Comment by bretg** [comment]
Released with PBS-Java 1.90

**Comment by shahbaztariq** [comment]
@bretg is there any ETA for this to be implemented in PBS-Go? There is increasing demand for this feature.

**Comment by bretg** [comment]
No timeline for Go at this point @shahbaztariq - community PRs welcome.

**Comment by AlexBVolcy** [comment]
@shahbaztariq I've begun work on this feature, I'll be able to give a better ETA next week.

**Comment by AlexBVolcy** [comment]
@shahbaztariq I'm working on this feature, I'll have an ETA for it next week.

**Comment by josepowera** [comment]
I think I have oversimplified original issue.   After quick look at PR (https://github.com/prebid/prebid-server/pull/2347), I see also, that this or another Issue should handle compressed response received from Bidder (DSP) back to prebid server.  Is that already handled by default httpclient in PBS?

**Comment by shahbaztariq** [comment]
@josepowera that is correct, a gzipped response is already handled by the default httpclient. There is a configuration that allows the httpclient to _not_ handle gzip responses but this is only when you want to handle the uncompression yourself.

**Comment by josepowera** [comment]
Thx.. Should Accept-Encoding: gzip header be added to http request to bidder if Compress is enabled?  (similar to https://protocol.bidswitch.com/standards/data-format.html)

Otherwise bidder (DSP) will have to decide if bidresponse can be compressed only based on if bidRequest was gzipped / PBS server version

**Comment by shahbaztariq** [comment]
@josepowera no. If you add that header manually, then you have to deal with the uncompression manually.

The httpclient will by default add that header in. 

As per this SO answer: https://stackoverflow.com/a/38954490

Also further information here: https://go.dev/src/net/http/transport.go#L182

Gzipping responses is standard (or atleast widely adopted). So the default httpclient will add the gzip header indicating to the bidder that if they wish to they could send a gzipped response and we'd handle it fine.

This issue is asking for the bid *request* to be gzipped. This has to enabled on the bidder (DSP) side as this doesn't follow any particular standard.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.224.0.
