### ISSUE TITLE
Mismatched type for Prebid Server

### ISSUE THREAD

**Issue by YOzaz** [prebid/prebid-server#182]
Configuration (sample):
```js
pbjs.setConfig({
	bidderTimeout: PREBID_TIMEOUT,
	enableSendAllBids: true,
	s2sConfig: {
		accountId: 'e7445f8d-ee19-4a94-a234-a271cb3e6bc0',
		enabled: true,
		bidders: ['facebook', 'pulsepoint', 'rubicon'],
		timeout: PREBID_TIMEOUT
	} 
});

pbjs.addAdUnits([{
	code: "div-gpt-ad-1418309082456-0",
	sizes: [
		[728, 90],
		[970, 250]
	],
	bids: [{
		bidder: "rubicon",
		params: {
			accountId: "14346",
			siteId: "154972",
			zoneId: "738672",
			sizes: "[2,57]"
		}
	}]
}]);
```
Result with `?pbjs_debug=true` - no call is made:
```
MESSAGE: CALLING S2S HEADER BIDDERS ==== facebook,pulsepoint,rubicon
MESSAGE: Mismatched type for Prebid Server : rubicon : accountId. Required Type:function () { [native code] }
MESSAGE: Mismatched type for Prebid Server : rubicon : siteId. Required Type:function () { [native code] }
MESSAGE: Mismatched type for Prebid Server : rubicon : zoneId. Required Type:function () { [native code] }
```
Help?

P.S. `prebid.js build 0.32.0`.

**Comment by dbemiller** [comment]
hey @YOzaz ... could you open this on the [Prebid.JS](https://github.com/prebid/Prebid.js) board?

If the server never receives a request, then then there's not much that this project can do about it.

**Comment by YOzaz** [comment]
Will do, thanks!

**Comment by YOzaz** [comment]
Found it. Prebid Server requires parameters to be as of integer, but official docs say it must be wrapped in quotes (string). Client side bidding works either way, but ideally adapter should accept string as well:
https://github.com/prebid/prebid-server/blob/master/static/bidder-params/rubicon.json#L8
