### ISSUE TITLE
IndexExchange bidder isn't working?

### ISSUE THREAD

**Issue by smartbidder1** [prebid/prebid-server#183]
When trying to get ads with indexExchange server bidder, I am getting no-bid, even after cookie sync. (tried 100 times)
when trying to get ads with the same placement ID and publisher ID with the JS bidder, I am always getting ads.

Server bid Params:
"bidder":"indexExchange",
      "params":{  
         "id":"2",
         "siteID":"179681"
      }
Server bid Response:
`{"tid":"9fa92356-47cb-4edd-930a-f7bb98b95d60","status":"OK","bidder_status":[{"bidder":"indexExchange","ad_unit":"doNotChange","response_time_ms":12,"no_bid":true,"debug":[{"request_uri":"http://appnexus-us-east.lb.indexww.com/transbidder?p=184932","request_body":"{\"id\":\"9fa92356-47cb-4edd-930a-f7bb98b95d60\",\"imp\":[{\"id\":\"doNotChange\",\"banner\":{\"format\":[{\"w\":300,\"h\":250}],\"w\":300,\"h\":250},\"tagid\":\"doNotChange\",\"secure\":1}],\"site\":{\"domain\":\"ultimate-guitar.com\",\"page\":\"https://www.ultimate-guitar.com/\",\"publisher\":{\"id\":\"179681\"}},\"device\":{\"ua\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36\",\"ip\":\"207.118.9.184\"},\"user\":{\"id\":\"2107298810938209085\",\"buyeruid\":\"WeyOv7lQJL4AADkpCfAAAABw%26240\"},\"at\":1,\"tmax\":1000,\"source\":{\"fd\":1,\"tid\":\"9fa92356-47cb-4edd-930a-f7bb98b95d60\"}}","status_code":204}]}]}`

JS bid URL: https://as-sec.casalemedia.com/cygnus?v=7&fn=cygnus_index_parse_res&s=179681&r=%7B%22id%22%3A%22246919881%22%2C%22site%22%3A%7B%22page%22%3A%22https%3A%2F%2Fwww.ultimate-guitar.com%2F%22%7D%2C%22imp%22%3A%5B%7B%22id%22%3A%221%22%2C%20%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%20%7B%22sid%22%3A%222_1%22%2C%22siteID%22%3A179681%7D%7D%5D%7D&pid=pb0.25.0
JS bid Response:
`cygnus_index_parse_res({"seatbid":[{"bid":[{"crid":"8668408","adomain":["vultr.com"],"adid":"8668408","impid":"1","cid":"1901418","id":"1","ext":{"dspid":105,"pricelevel":"_4","advbrandid":214517,"advbrand":"Vultr Holdings"},"adm":"<iframe src=\"https://a240.casalemedia.com/ifnotify?c=8444F8&r=EC63D02F&t=5A003E41&u=V2V5T3Y3bFFKTDRBQURrcENmQUFBQUJ3&m=07e6b1585fb1a67a0a078f1b157e9213&wp=6&aid=8EA8C040786A0C9D&tid=F582&s=2BDE1&cp=0.06&n=www.ultimate-guitar.com&pr=xx&sid=379c&epr=246919881\" width=\"0\" height=\"0\" frameborder=\"0\" scrolling=\"no\" style=\"display:none;\" marginheight=\"0\" marginwidth=\"0\"></iframe>\n    <div style=\"text-align: center;\">\n       <script type=\"text/javascript\">\n           adroll_width = 300;\n           adroll_height = 250;\n           adroll_a_id = \"SV2SF2P76NFIPN7N5SDPHX\";\n           adroll_s_id = \"ISRFVJ4CYZEJLCRYPCOWW4\";\n           adroll_c_id = \"MKPW6JTMURCVDDC6WM6KR5\";\n           adroll_render_link = false;\n           adroll_ext_network = \"index\";\n           adroll_subnetwork = \"r\";\n           adroll_ad_payload = \"__HIAg8BkwHaAf3IAfkAAY2QTWjTYACG08-uniaIN0_Kdm1JvqT5KVrp1qU_mX8rrW0RY36-dJ-kqbbJot7E024KHnReRIabP0xFqJtHB3bYfFHw5BAF2UH0oAfxIChGELx48Pw-Lzw8b6nxeL_YlI8cnCiWjqblRj0_Xecma8ca7O5-vqoUc0qtUSrnKsV8daLA1YSZKbE_lZeFaqMgl8uF8qHDJaVSmZRlIUM-nty3bHRsG5uomx1mX848WbjWVA6sQZoRGBpyqj-LXWTjnqtC1UU9Vx7sBFvvPz28NP_zy-rag5V3z16tjChPj4fU3tR2bwF5ST-ikox29l7XcxzstFSeEZlg_rHv-ynPdnFbc1Gy5WFX66aMTju4HjapbC648ehf481EsJgLni8hmjc0XguGg0T8ckjt39gRBL9NXt_6_GHx_rf-6h-T4PtgdNuFZTSHzY6juiRzNfhxhU7xkMTGNqkxBDXJFNK8pFumYEmMxolsGrIShKaeNkQug20SG_9PENRDKrF1m4DGJrWnd-a011LnBFVQGahG6jp2kPk3HwHNdQJORMEJaIfUxd4pAs6HsdGvWQI2oj-ts5YmWTwn8gbDQV40GNqUBJPVeZplGZqA4ZJ5ztHa2CAgfEPtwkkaipYuIQ2JhiggyOskPr1ORu7c7aIoXwu5UXySmA0p8ML4BaxjDEqW5v-pYCi9Lvk\";\n           adroll_url_macro = \"ultimate-guitar.com\";\n           adroll_cpm_macro = \"WgA-QQAAAADh4IS8qL3BxquQiFxff6jLNMv_HA\";\n           adroll_c_macro = \"\";\n           adroll_imp_macros = undefined;\n           adroll_win_notif = \"index-winners-eu-west-1-rtb.adroll.com/win/index?c=EDF7UYGFJJGJNOIKSSCFF7;bid=27853944882346095040826299410739556;payload=__HIAuQAARXSO67jVACA4auRWAA7YAPnym-fNEh24mccx_EjfjTW8Tt2_LZjJxsY0bGFsIDRTINgA0xHQzdCQkJ0NKwAcWn_6iv-90_05eUbLCIztMkYCjIxThEMjHEs2bAJGTEYSeLYM_r89bu__vz70_ff_fvPTz9__PDHL799-OoZ_yjsRNbxJVFVJVU_KnvL2ooi-yx-f8HTmAAkBQiaBDjcAJx9TWewpOME8Ne4rbt5Sl9RjR5tg5bx__Lsvrz7HIaywuWQrxYZcRmpcFnFcT5xst3S9rmthEEwNxek6Fi4T2pcvfU2vT8PHd47Ye3BYXAx0ycZkKig6qNIbSdWwAhqLzdmaiooMrBV7NVJ5snIz0R5oXlOJBwZa7lsVbaFJGgrBY0FaI8FRkyzplroXxUYN9uLW_bR1Syx0EvjGsEYsUca3PrWibF-cqyh2Y9nmCCNw30r2EdCeA1SEfWH_ApnEfbyTkVnqw7Mq-IcQDPdyUg2R4me23rF3-gUdKPSPXPMeApaU-K7e18CzXPtsumnLe44m_PKjrx4uxkPAupG-LiDAeX0mXzgzFRuC6OkMoecTCJaRNqywaVqV2JzZb14fYyTaKVCcM3DQb6Be2MkjRjFuHSnXdFjGHSwy5mSS9RF27cJ0iKjIC6Maq41F1jUZYx5-SzlmA3jqpzITW7y2kb3ppAJJXkNhwwwBbApY8oTfRYD25IfPlPOF_OhZ8VaOOxaHWxJ76uV33mqqO9hJ861L9SHtb2O0qBYxR6lenWacwKzpHBjCLq52w8iXlM7SR3cJgEIw3Gt4cXzSUKFxJQdURkVKS-ynpzUo3kQVKRkzppQHTcy8phIN_ekEG0JppH2a9deGphHu9OZwt4gDq8a5zTorlLQc1Sg0o9JRsSWyzPBmJaqQpfOn5UToRaXPL8fx8oY8KM5szGLlNZbZtrx7lbNYR08aBSP1nIn9C59A52_vWy0W_WcntkP0_hr8PIt9x8;price_cpm_dollars=\";\n       </script>\n       <script type=\"text/javascript\">\n           var _url_info =\n                ('https:' == 'https:'\n                    ? {adserver_hostname:\"s.adroll.com\", protocol:\"https://\"}\n                    : {adserver_hostname:\"a.adroll.com\", protocol:\"http://\"}\n                );\n\n           (function () {\n               document.write('<scr'+'ipt type=\"text/javascript\" src=\"' + _url_info.protocol + _url_info.adserver_hostname + '/j/rolling.js\"></scr'+'ipt>');\n           }());\n       </script>\n       <script type=\"text/javascript\" src=\"https://q.adrta.com/aa.js?cb=f0Cw7uExxCsEbjIMss591SwujsCvHenih6bru7QibjE=#ar;paid=ar;avid=DUKHAKVYIJASHDUBG4V7RE;caid=EDF7UYGFJJGJNOIKSSCFF7;plid=HZFPMBHIQ5FYXDLX4CVWY3;siteId=ultimate-guitar.com;kv1=300x250;publisherId=184163;kv2=https%3A%2F%2Fwww.ultimate-guitar.com;kv3=0b3fa9f6486c14268c10d97d3b603310;kv4=31.154.177.226;kv7=CmgnFR4;kv11=27853944882346095040826299410739556\"></script><noscript><img src=\"https://adrta.com/i?clid=ar&paid=ar&avid=DUKHAKVYIJASHDUBG4V7RE&caid=EDF7UYGFJJGJNOIKSSCFF7&plid=HZFPMBHIQ5FYXDLX4CVWY3&siteId=ultimate-guitar.com&kv1=300x250&publisherId=184163&kv2=https%3A%2F%2Fwww.ultimate-guitar.com&kv3=0b3fa9f6486c14268c10d97d3b603310&kv4=31.154.177.226&kv7=CmgnFR4&kv11=27853944882346095040826299410739556\"></noscript>\n    </div>\n    "}],"seat":"1"}],"cur":"USD","id":"246919881"});`

**Comment by smartbidder1** [comment]
@anwzhang @nhedley @pdezwart

**Comment by mkendall07** [comment]
agreed. @smartbidder1 can you include a curl example to prebid server?

**Comment by smartbidder1** [comment]
@mkendall07 @dbemiller sure no problem.
`curl 'http://appnexus-us-east.lb.indexww.com/transbidder?p=184932' -H 'Pragma: no-cache' -H 'Origin: http://www.ultimate-guitar.com' -H 'Accept-Encoding: plain' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' -H 'Content-Type: text/plain' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://www.ultimate-guitar.com' -H 'Connection: keep-alive' --data-binary '{"id":"07b42ebe-e291-49d7-ac58-a8135eef5e90","imp":[{"id":"doNotChange","banner":{"format":[{"w":300,"h":250}],"w":300,"h":250},"tagid":"doNotChange","secure":1},{"id":"doNotChange","banner":{"format":[{"w":300,"h":250}],"w":300,"h":250},"tagid":"41","secure":1}],"site":{"domain":"ultimate-guitar.com","page":"http://www.ultimate-guitar.com","publisher":{"id":"179683"}},"device":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36","ip":"3.195.23.190"},"user":{"id":"2107298810938209085","buyeruid":"WeyOv7lQJL4AADkpCfAAAABw%26240"},"at":1,"tmax":1000,"source":{"fd":1,"tid":"07b42ebe-e291-49d7-ac58-a8135eef5e90"}}' --compressed`

If I will do the same request from the JS endpoint for the same placement, I will always get ads.

**Comment by smartbidder1** [comment]
anyone? @dbemiller @mkendall07

**Comment by dbemiller** [comment]
@smartbidder1 The URL on that curl request belongs to Index... so `prebid-server` isn't involved at all.

**Comment by smartbidder1** [comment]
This is the URL that is configured on the index adapter, I just took the request from the debug field.
even when doing the request from the actual prebid-server through appnexus, there are no ads.

**Comment by dbemiller** [comment]
Well... that makes sense. If a curl to Index returns no ads, then prebid-server's request to Index will return no ads too. 

> If I will do the same request from the JS endpoint for the same placement, I will always get ads.

Can you screenshot the request made to Index from chrome's dev tools? There's got to be _something_ different about it, if Index returns ads.

**Comment by smartbidder1** [comment]
Sure no problem, here is a Live demo:
```<script type='text/javascript'>


var pbjs = pbjs || {}; pbjs.que = pbjs.que || []; 
var PREBID_TIMEOUT = 5600; 
var adUnits = [{"code": "just_a_test", "sizes": [[300, 250], [300, 600]], "bids": [{"bidder":"indexExchange","params":{"id":"4","siteID":"179683"}}]}]; 

</script>
<script type="text/javascript" src="prebid.js" async></script>
<script>   
	var googletag = googletag || {};
	googletag.cmd = googletag.cmd || [];
	googletag.cmd.push(function() {
	    googletag.pubads().disableInitialLoad();
	    googletag.pubads().collapseEmptyDivs(true);
	});
	
	pbjs.que.push(function() {
        pbjs.addAdUnits(adUnits);
        pbjs.requestBids({
            bidsBackHandler: sendAdserverRequest
        });
    });

	pbjs.que.push(function() {
	    pbjs.enableAnalytics({
	        provider: 'cmv2'
	    });
	});

    function sendAdserverRequest() {
        if (pbjs.adserverRequestSent) return;
        pbjs.adserverRequestSent = true;
                pbjs.setTargetingForGPTAsync();
				var bidresp = pbjs.getBidResponses();
				console.log(bidresp);


				var winningBids = pbjs.getHighestCpmBids();
				if (winningBids.length > 0)
					console.log('we have a winner');
				console.log(winningBids[0]);
    }

    setTimeout(function() {
        sendAdserverRequest();
    }, PREBID_TIMEOUT);
	

</script>
<body>

<div id="just_a_test"></div>
</body>```

**Comment by smartbidder1** [comment]
and a screenshot from my PC:
![image](https://user-images.githubusercontent.com/30568117/33566182-d85ab78a-d927-11e7-9b9d-bafbd45c400d.png)

**Comment by dbemiller** [comment]
I personally haven't... but I can see from the Influx monitoring that others are.

I'll poke around with your demo page this afternoon and see if I can figure out what's going on.

**Comment by smartbidder1** [comment]
@dbemiller I totally agreed and understand what you say, thank you for taking the time and effort to investigate this issue.
If there are partners (or rumors about partners) that managed to get ads from index or have live working case that I can check out it would be great.

Maybe you can take a look at the influx stats to see if they are sending the requests differently maybe? and custom params?

**Comment by smartbidder1** [comment]
anything yet?

**Comment by mkendall07** [comment]
@smartbidder1 please context indexExchange if you have issues with their bidder.

**Comment by dbemiller** [comment]
@smartbidder1 sorry about that, but no... someone at our company _did_ say they had an Index page which worked, but it wasn't working for me when I tested it, so I didn't pass it along. I should have responded though so I didn't keep you waiting.

The best I can say is that the influx metrics do make it clear that Index is making non-zero bids for some publishers. Those are just metrics, though, so there's not enough detail to see how they're being called.

I'm afraid mkendall is right... I think your best bet is to contact indexExchange in this case.

**Comment by yacota** [comment]
@smartbidder1 any update on this ? Did you manage to solve this problem ?

**Comment by sahilwaliaceo** [comment]
@smartbidder1  what is cmv2 in this code?

> 	pbjs.que.push(function() {
> 	    pbjs.enableAnalytics({
> 	        provider: 'cmv2'
> 	    });
> 	});
