### ISSUE TITLE
cookie sync always returns empty result

### ISSUE THREAD

**Issue by aaronwh** [prebid/prebid-server#1832]
Hi, I have set up a prebid server, and it is able to return bids for a set of 10 adapters on an AMP page.

However, the user syncing doesn't seem to be set up right, and I cannot figure out what I am missing.

My AMP iframe pings my modified load-cookie.html (rebuilt from the prebid universal adapter project) which pings my prebid server, but it never returns anything but: 

{"status":"no_cookie","bidder_status":[]}

If I hit load-cookie.html with the pre baked rubicon or appnexus endpoint, things work as I expect. Therefore I think the issue is somehow in my prebid server set up.  Is there something I need to configure to make this work?  Sorry to post this here but I can't think of anywhere else to ask, and have been looking at the server code, previous issues, git log, documentation, etc to no avail.

**Comment by SyntaxNode** [comment]
That does seem odd. Perhaps it's the modified load-cookie.html. Could you please share with us the request being made in the browser to the cookie sync endpoint?

**Comment by bretg** [comment]
Also, please let us know if you're using PBS-Go or PBS-Java. There are a few differences in cookie-sync configuration between them.

**Comment by aaronwh** [comment]
Thanks! I am using prebid-go, and I was able to get make some progress by setting the following config on the prebid server:

gdpr.usersync_if_ambiguous: true

After I set this, when I hit the load-cookie endpoint, I see in the console log (and network tab) what appears to be user syncing happening.  Does this mean that user sync is working?

FYI the load-cookie.html is here:

https://www.wikihow.com/x/load-cookie.html?endpoint=wikihow&max_sync_count=5

I am wondering if usersync_if_ambiguous=false means that it would have worked if i passed gdpr=0 to the load-cookie.html page, but I could have sworn I tried that before without any luck.

I also tried passing a list of bidders like so:

https://www.wikihow.com/x/load-cookie.html?endpoint=wikihow&max_sync_count=5&bidders=verizonmedia,pubmatic

But this doesn't seem to work.  Is this what I'm supposed to do?

At any rate, thank you so much!

**Comment by bretg** [comment]
Note that Pubmatic's usersync in PBS-Go is an iframe which doesn't work in AMP. We changed this in PBS-Java to the redirect version of their usersync and had better results. https://github.com/prebid/prebid-server-java/blob/master/src/main/resources/bidder-config/pubmatic.yaml

You could work with Pubmatic to find out what string you can configure for your needs. Imagine they would want you to pass a code other than p=159706.

**Comment by SyntaxNode** [comment]
> I am wondering if usersync_if_ambiguous=false means that it would have worked if i passed gdpr=0 to the load-cookie.html page, but I could have sworn I tried that before without any luck.

Yes. If `usersync_if_ambiguous` is set to `false` then you need to either specify `gdpr` as `0` for the sync to work or provide a TCF2 consent string granting cookie sync permission to the host gvl id and the gvl ids for each of the bidders you're trying to sync.

If you are thinking to yourself this is confusing, you're right. We recently decided to deprecate and remove `usersync_if_ambiguous` and replace it with a more straightforward `default_value` which has no default, it will have to be configured for PBS to start. Expect to see a PR for this shortly.

> I also tried passing a list of bidders 

That is the correct way to pass a list of bidders. I checked your test page and can confirm it is working correctly.

There is an aspect to the cookie sync algorithm for both PBS-Go and PBS-Java that you may be overlooking in your tests. If the user sync is already present in the cookie, Prebid Server will not attempt to re-sync until the existing sync expires. I recommend to either clear your cookies right before performing a test or use incognito mode to avoid cookie storage.

**Comment by aaronwh** [comment]
Thank you so much for the help, this is all extremely helpful! I think it all works fine now.
