### ISSUE TITLE
Proposal: PBS to break out imp.video.h/w

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1833]
It came to our attention that Prebid.js a non-standard way of dealing with video player size.

- The Prebid AdUnit is defined with mediaTypes.video.playerSize: [w,h]
- The pbsBidAdapter just forwards this to PBS as imp[].video.playerSize. 
- PBS passes this through to server-side bid adapters

The proper way to do this in OpenRTB is to set  imp[].video.h and imp[].video.w. 'playerSize' is not part of the spec. Seems hard to believe no one noticed this before now.

But anyhow, I propose that we implement logic in PBS-core:

1) if imp[].video.w isn't specified then set imp[].video.w from imp[].video.playerSize[0] (if it's a number)
2) if imp[].video.h isn't specified then set imp[].video.h from imp[].video.playerSize[1] (if it's a number)
3) leave imp[].video.playerSize in there for now. Maybe we'll remove it someday.

**Comment by bretg** [comment]
Discussed in PBS committee. Turns out imp[].video.playerSize is rejected by the OpenRTB validation layer.

1) There's a PBJS pull request already in place to fix this. But of course the installed base will be passing playerSize for years to come.
2) Magnite is going to experiment to see whether video performance is affected by handling this situation. We'll report back to the group.

In the meantime, we won't do anything on this as an open source project until we have some data.

**Comment by bretg** [comment]
So Magnite added an experiment to a fork of PBS-Java for this. Basically it allows imp[].video.playerSize as valid OpenRTB during the validation step, converting it to w/h and then deleting it. Yeah, class hack.

This solved the problem seen by the synacor bidder - they're bidding now. Didn't see a significant overall change in results across other bidders. Still, it makes sense that bidders ought to be able to know the player size. I propose that Prebid as a whole should support video better by making this unfortunate exception more general.

**Comment by bretg** [comment]
Discussed in committee:
- the underlying fix will be in PBJS 4.40
- given that this seemingly affects only one bidder, we would rather not propagate an OpenRTB hack if we don't need to. Host Companies may prefer to use this as leverage to get pubs to upgrade to PBJS 4.40 rather than take on the processing cost of the extra logic.
- @bszekely1 will confirm whether SDK ever passes playerSize. We tend to think this is controllable by the host company in the stored request.

**Comment by bszekely1** [comment]
Confirming Prebid SDK passes the OpenRTB size `imp[].video.w / h`.

**Comment by bretg** [comment]
Ok, then we won't release the hack to open source. Magnite will leave it in their fork until the affected bidder's pubs are upgraded to 4.40, and then we'll get remove it.

If anyone else would like to have these changes that enable synacormedia to bid on video, let me know - we can send you the diffs.
