### ISSUE TITLE
Schain is not sent to SSP

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1836]
Hello everybody,

I got a problem with my prebid server, when my prebid js send request to it with schain (I can see it in development console), this schain is not forwarded to SSP.

When i active test mode, i can see the request to SSPs, and schain parameter is not in request.

Do you know why ?

Thanks

**Comment by bretg** [comment]
Please provide more information. This works for me. e.g. here's a request defining source.ext.schain. Sending this to either PBS-Go or PBS-Java results in the schain being sent to Rubicon.

```
{
            "id": "1001-amp",
            "imp": [
                {
                    "id": "some-impression-id",
                    "banner": {
                        "format": [
			    {	"w": 468,
				"h": 60
			    },
                            {
                                "w": 300,
                                "h": 600
                            },
                            {
                                "w": 300,
                                "h": 250
                            }
                        ]
                    },
                    "secure": 1,
                    "ext": {
                        "rubicon": {
                            "siteId": 113932,
                            "zoneId": 535510,
                            "accountId": 1001,
			    "inventory": {
                                "rating": [ "5-star" ],
                                "prodtype": [ "tech", "mobile" ]
                            },
                            "visitor": {
                                    "ucat": [ "new" ],
                                    "search": [ "iphone" ]
                            }
                        }
                    }
                }
            ],
	    "source": {
		"ext": {
		    "schain": {
			"ver":"1.0",
			"complete": 1,
			"nodes": [
			  {
			    "asi":"directseller.com",
			    "sid":"00001",
			    "rid":"BidRequest1",
			    "hp":1
			  }
			]
		    }
		}
	    },
            "site": {
                "domain": "rubiconproject.com",
                "page": "www.rubiconproject.com"
            },
            "device": {
                "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36",
                "ip": "174.57.47.200"
            },
            "test": 1,
            "ext": {
                "prebid": {
                    "cache": {
                        "bids": {}
                    },
                    "targeting": {
                        "pricegranularity": "med"
                    }
                }
            }
        }
```

Could be the bidder's server-side adapter isn't forwarding the schain? Which one are you working with?

**Comment by mouchii** [comment]
To be clear, i would like to force schain in bid request inside a server side adapter.
Do you think is it possible ?

**Comment by mouchii** [comment]
Yes, I would like to inject an schain from prebid server.

**Comment by bretg** [comment]
You have two options:

1) If the schain is global across all bidders, you can set up the default request to contain source.ext.schain -- see https://docs.prebid.org/prebid-server/features/pbs-default-request.html

2) If the schain is specific to some bidders and the request is app or AMP, you could add source.ext.schain to the contents of the stored requests DB/file.

**Comment by mouchii** [comment]
Thank you Bretg for informations.

Do you know if it is possible to add custom schain inside an adapter ?

**Comment by bretg** [comment]
> possible to add custom schain inside an adapter

Inside an adapter definitely not. 

Maybe you're looking for the "bidder-specific schain" feature? https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#supply-chain-support

In the OpenRTB request, you can define ext.prebid.schains with bidder-specific details.

**Comment by bretg** [comment]
@mouchii - does the bidder-specific schain feature solve your need here?

**Comment by bretg** [comment]
@mouchii - Please re-open this issue if bidder-specific schain doesn't resolve this issue.
