### ISSUE TITLE
OMSDK Signaling support

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#1860]
## Type of issue
Proposal

## Overview
[Open Measurement SDK](https://iabtechlab.com/standards/open-measurement-sdk) (OMSDK for short) provides publishers and buyers a method to easily execute 3rd party viewability and verification code in an open source framework for mobile apps. In modes where Prebid SDK relies on the ad server to render ads for mobile environments, Pebid SDK will provide OMID signaling to Bid Adapters by way of the OpenRTB PBS call for demand.

Publishers or host providers can pass the OMID signals to PBS either directly to PBS from the SDK or using a stored request, however there are two challenges with passing signals either directly to PBS or using stored requests:

- OMID requires a version number that can change (sub-optimal for passing from SDK due to keeping track of the latest version)
- OMID packages are broken out by partner, appName and platform (iOS vs Android) that is difficult to do with the freeform nature of stored requests (this would effectively lock stored requests to be one for iOS and one for Android)

To help facilitate the setup and transmission of OMID signaling, this proposal is to rely on PBS to assist in populating the OM partner name and partner  version based on a supplied appName.

## Proposed Design

- This feature should be added a PBS module
- Prebid SDK should fetch, at some cadence (daily or weekly?) the [latest certified list of OMSDK package list](https://complianceomsdkapi.iabtechlab.com/compliance/latest) to store for real-time mapping
- Publishers or host providers can pass the app name in `ext.prebid.omid.appName` the name of the app for that top level stored request
- Prebid Server would look in for the presence of `ext.prebid.omid.appName` with combination of the PBS call's `device.os` name to derive the OMID signals
    - PBS should use the appName and os to lookup in the [OMSDK package list](https://complianceomsdkapi.iabtechlab.com/compliance/latest), decorating the top level request with `source.ext.omidpn` derived from the list's matching `partnerName` and the `source.ext.omipv`derived from the list's matching `partnerVersion`
    
    
    Example IAB OMID entry

```
    {
      "certificationStatus": "Active",
      "certificationProcess": "2",
      "lastCertifiedDate": 20201013,
      "lastUpdateDate": 20201013,
      "libraryVersion": "1.3.0",
      "partnerVersion": "afma-sdk-i-v7.64.0",
      "platform": "iOS",
      "_id": "5f7357caeacae200042f4db8",
      "companyName": "Google",
      "partnerName": "Google",
      "appName": "Google GMA SDK",
      "certifications": [
        {
          "creativeType": "htmlDisplay",
          "adSessionType": [
            "html"
          ]
        },
        {
          "creativeType": "video",
          "adSessionType": [
            "html"
          ]
        },
        {
          "creativeType": "nativeDisplay",
          "adSessionType": [
            "javascript"
          ]
        }
      ]
    }
```

Stored Request entry:

```
{
    "ext": {
        "prebid": {
        	"omid":{
        		"appname":"Google GMA SDK"
        	},
            "targeting": {
                "includebidderkeys": true, 
                "includewinners": true, 
                "pricegranularity": "med"
            }
        }
    }
}
```

Decorated PBS request with iOS traffic:

```
{
	"imp" : [{
		...
	}],
    "source": {
        "ext": {
            "omidpn": "Google", 
            "omidpv": "afma-sdk-i-v7.64.0"
        }
    }
}
```

**Comment by bretg** [comment]
Perfect job for a module.

We've been trying to standardize on all lowercase extensions -- please update from ext.prebid.omid.appName to ext.prebid.omid.appname

I'm out of my league here, but this dynamic lookup seems optimistic. What does "afma-sdk-i-v7.64.0" indicate? To a naive eye, it looks like it's a statement that v7.64.0 is compiled into the mobile app. But since it's dynamic, that's not necessarily true. The hosted file could change but the app could stay the same, right?

**Comment by bszekely1** [comment]
The partner version number will need to be dynamic. Since this is the case, we cannot ever store these in the PBS DB. The API fields can be stored in the PBS DB. This solution will not work.
