### ISSUE TITLE
PBS does not allow twin adunits codes

### ISSUE THREAD

**Issue by hnkhandev** [prebid/prebid-server#1866]
When we want certain bidders to request only video format (for ex. outstream) and others to request only banner format, you must use twin adunits codes (https://docs.prebid.org/dev-docs/adunit-reference.html#twin-adunit-codes). The problem is when you set up PBS and try to send the requests, it does not allow you to because the openrtb 2.5 spec states that imp ids must be unique. 

PBS spits out this error: Invalid request: request.imp[0].id and request.imp[1].id are both "yyyy". Imp IDs must be unique.

How can we get around this? Multi format is not an option as per our requirements because we want to limit some bidders to x format and others to y which is why twin adunits must be used.

**Comment by bretg** [comment]
This was discussed in committee last week. PBS will not support duplicate imp[].ids -- this is against OpenRTB. Rather, we're going to open an issue on the PBJS side so the pbsBidAdapter does the right thing here. Will close this issue when the PBJS issue is opened.

**Comment by bretg** [comment]
Opened https://github.com/prebid/Prebid.js/issues/6910. Closing this.
