### ISSUE TITLE
Investigate debug warning on invalid OpenRTB

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1874]
Currently both PBS-Go and PBS-Java silently drop invalid OpenRTB. This was discussed in PBS committee and we agreed that it would be better if PBS could warn about invalid OpenRTB when in debug mode.

- @SyntaxNode to look into what it would take in PBS-Go to make this happen
- @rpanchyk to look into what it would take in PBS-Java to make this happen

**Comment by SyntaxNode** [comment]
I believe this behavior is the result of a common approach to json parsing where unrecognized fields are ignored.

This is technically challenging for PBS-Go to implement, to the extent where I don't think it's worth it. The Go json deserializer does not have the option to track unrecognized fields to use for warnings. A custom deserializer could be to be written to track unknown fields, but that's a lot of work and is further complicated by the use of a third party library for the OpenRTB data model. We could also do a separate json parsing pass to capture the unrecognized fields, but I'm concerned about the performance of such an approach.

This is technically challenging for PBS-Java too. @rpanchyk will investigate, but seems to be leaning towards not implementing this request.

**Comment by rpanchyk** [comment]
Technically it is possible but it will consume CPU/memory resources at each call which can be significant.

**Comment by bretg** [comment]
The committee agreed this feature would be more computationally expensive than is deemed worthwhile.
