### ISSUE TITLE
GumGum throwing error in P4.42.0

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#1875]
GumGum, has suddenly started throwing this error in P4.42.0 and stopped working in effect for S2S:

no config changes, no params changes etc taken place, just moved 4.41.0 to 4.42.0

![DevTools_-_cheftalk_com_ads_final_-2](https://user-images.githubusercontent.com/8503167/120637856-51eb9000-c467-11eb-8933-d544752a908e.png)

**Comment by spormeon** [comment]
Ummm, actually doing it in 4.41.0 as well now, maybe a gumgum server problem?

**Comment by SyntaxNode** [comment]
The message indicates a bad response from their server, so I don't think it's related to the PBJS request. Thank you for letting us know. We'll reach out to Gum Gum for assistance.

**Comment by spormeon** [comment]
its back fixed by the looks of it now
