### ISSUE TITLE
Remove lifestreet adapter

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1876]
We received notification from the lifestreet team that they no longer wish to support their PBS adapter.

We have email from Yulia and Michael at lifestreet, but adding the GitHub handle to make sure everyone knows we're going to remove the adapter 

^^ @Lifestreet

**Comment by SyntaxNode** [comment]
I appreciate the confirmation, but am sad to see them leave. I'm targeting removal in PBS-Go 0.163.0.

**Comment by SyntaxNode** [comment]
Removed in PBS-Go 0.163.0.

**Comment by bretg** [comment]
Removed with PBS-Java 1.68
