### ISSUE TITLE
How solve it? gdpr.default_value

### ISSUE THREAD

**Issue by dougrhis** [prebid/prebid-server#1897]
![Captura de Tela 2021-06-19 às 22 07 25](https://user-images.githubusercontent.com/9891463/122659130-cfdbb680-d14a-11eb-965d-bb782d1e831c.png)

**Comment by SyntaxNode** [comment]
We made a change in 0.164.0 based on community feedback. The `gdpr.usersync_if_ambiguous` config has been removed and replaced with `gdpr.default_value` which has no default. A value must be specified for Prebid Server to start up. Please see the discussion in https://github.com/prebid/prebid-server/issues/1783 for more context.

This change was called out in the [release notes of 0.164.0](https://github.com/prebid/prebid-server/releases/tag/v0.164.0), but we're only really started putting useful release notes a little bit ago - so I understand if you didn't check there first.

Here's the relevant excerpt from the release notes:

> The `gdpr.usersync_if_ambiguous` config option has been removed in this release. We heard your feedback that this was confusing and that the default value causes side affects which are hard to identify, especially during development. In its place, we've added a `gdpr.default_value` string config which Prebid Server uses if `regs.ext.gdpr` is absent from the request. *There is no default value. Prebid Server will not start until this value is configured as either `"0"` or `"1"`.*

**Comment by dougrhis** [comment]
Hi,
Thanks for the feedback, I'm not able to set the value gdpr.default_value=1, where I do the proper configuration can you help me please?

**Comment by SyntaxNode** [comment]
You can either set the `PBS_GDPR_DEFAULT_VALUE` environment variable or create a pbs.yaml file that looks something like this:
```
gdpr:
  default_value: "0"
```

**Comment by dougrhis** [comment]
Thanks for the reply, fixed the error, but another one appeared 
`(E0620 08:16:38.276053 56597 vendorlist-fetching.go:114] Error calling GET https://vendor-list.consensu.org/v2/vendor-list.json. Cookie syncs may be affected: context deadline exceeded),`
 but when accessing the JSON it is accessible, do you know what it can be?

**Comment by SyntaxNode** [comment]
This looks like an issue with the timeouts for retrieving the GDPR Global Vendor Lists. The default is 0, which should mean there is no timeout enforced. Seems like I'll need to verify that behavior. For now, please configure timeouts (expressed in integer milliseconds) which make sense for your network. The values are:

ENV:
```
PBS_GDPR_TIMEOUTS_MS_INIT_VENDORLIST_FETCHES
PBS_GDPR_TIMEOUTS_MS_ACTIVE_VENDORLIST_FETCH
```

YAML:
```
gdpr:
  timeouts_ms:
    init_vendorlist_fetches: 5000
    active_vendorlist_fetch: 5000
```

Init is for when the application first starts. That's very likely what you're describing. Active is for when the application is running an encounters a new GVL version it doesn't have cached in memory.

**Comment by dougrhis** [comment]
Thank you very much, it worked perfectly!

**Comment by bretg** [comment]
@SyntaxNode - any config doc updates to make as a result of this thread? Or can we close this out?

**Comment by SyntaxNode** [comment]
@bretg I'd like to much a doc update next week as a result. Let's leave this open until that PR is available.

**Comment by bretg** [comment]
This was part of PBS-Java 1.71

**Comment by bretg** [comment]
@SyntaxNode - did the docs update ever happen?

> Just curious why doest it take so long to fetch it..

@swifter87 - have you tried timing a command line fetch?

```
time curl "https://vendor-list.consensu.org/v2/archives/vendor-list-v111.json"
```

**Comment by swifter87** [comment]
@bretg It shows me - 0.154 total

**Comment by swifter87** [comment]
Got it. Thanks for the explanation @SyntaxNode

**Comment by shahinrahbariasl** [comment]
Hey @bretg , @SyntaxNode , I'v been running into issues regarding the timeout for downloading the vendor list.
```
Error calling GET https://vendor-list.consensu.org/v2/archives/vendor-list-v177.json. Cookie syncs may be affected: context deadline exceeded
```
I did run into this before and based on https://github.com/prebid/prebid-server/issues/1687 I increased the timeouts to 10s and that worked. But now even 40s timeout fails sometimes. Should we try to implement 0 timeout or a better retry mechanism? Our other idea is to download the list separately and update PBS to try to read the list from that location as well (if it exists). Any thoughts?

**Comment by bretg** [comment]
@shahinrahbariasl - This is not a PBS problem. It's a network problem. I recommend setting up a simple script on a machine near your Prebid Server to check the latency between your PBS and the IAB's list.

```
❯ while (true)
do
time curl https://vendor-list.consensu.org/v2/archives/vendor-list-v177.json | grep total
sleep 1
done
```

**Comment by shahinrahbariasl** [comment]
@bretg agreed. As a temp workaround I set the timeout to a very high number (like 3 min) and that worked for now.

**Comment by foreza** [comment]
> @bretg I'd like to much a doc update next week as a result. Let's leave this open until that PR is available.

Bumping for original issue as I'm trying to setup some tests for my team. :)
Was playing around, ran into the same issue (requiring the `gdpr.default_value` to be set), and ended up here.

**Comment by bretg** [comment]
Adding @SyntaxNode for the docs update

**Comment by SyntaxNode** [comment]
PBS-Go has a new readme which clarifies this requirement.
