### ISSUE TITLE
Transmit ext info from ad response to publisher

### ISSUE THREAD

**Issue by Niksok** [prebid/prebid-server#1922]
Hello!
Is there a way to convey some ext info from the ad response to the publisher?
Maybe it is possible to set additional targeting keys?

Something like in this client side PR https://github.com/prebid/Prebid.js/pull/7179

**Comment by SyntaxNode** [comment]
Prebid Server does not have the ability for an adapter to specify a custom targeting key. PBS-Java allows publishers to specify custom targeting keys to be resolved from the OpenRTB data structures but this feature is not yet present in PBS-Go, please see https://github.com/prebid/prebid-server/issues/1167 for further details.

Adapters may transmit any ext info they would like in their bid.ext response which will be sent to the publisher as `seatbid.bid[].ext` in the Prebid Server response. Please note, any values in `ext.prebid` from the bidder will be overwritten with Prebid Server specific information.

**Comment by Niksok** [comment]
Ok, thank you for response. May i make pull request with modified prebidServerBidAdapter module? To support transmit bid[].ext.bidder[<bidderName>] data in this module?

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pulls/6939 allows anything in the meta field to flow through. To quote Bret in Slack:  "the server-side adapter needs to set .Bids[].Bid.Ext.Prebid.Meta.MediaType . If it does, and PBJS is recent enough (4-5 months, could pin the version if needed), then the data will pass through to the PBJS client-side request object"

**Comment by bretg** [comment]
If the field you're wanting to pass through doesn't belong in Bids[].Bid.Ext.Prebid.Meta, you could submit a PBJS PR to read Bids[].Bid.Ext and put it somewhere (BidResponse.pbsBidExt?)

**Comment by Niksok** [comment]
But if my endpoint response has field seatbid[].bid[].ext.prebid.meta, this value is overrided in this line But if my endpoint response has field seatbid[].bid[].ext.prebid.meta, this value is overridden in this line 1. Or i am false and it will work fine? I see that on test files it work, but when i start prebid-server local  and test it - i see that bid[].ext.prebid is realy overridden and my prebid.meta is lose.

**Comment by bretg** [comment]
@SyntaxNode or @hhhjort - please take a look? The idea here is that we want the "Setting Metadata" example to work as documented in https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html

**Comment by hhhjort** [comment]
Looks like we do indeed drop all the `bid.ext.prebid.meta` fields. Our structs define the `meta` object with certain fields, but it seems we don''t actually reference it anywhere. We simply overwrite the provided `bid.ext.prebid` with the one we make at `exchange/exchange.go:922` in `(e *exchange) makeBid(...)`. We should unmarshal the incoming prebid object and at least keep the meta object inside.

**Comment by bretg** [comment]
@rpanchyk - please confirm the PBS-Java behavior here

**Comment by SyntaxNode** [comment]
Implemented in the upcoming PBS-Go 0.177.0. Leaving open for @rpanchyk to confirm PBS-Java behavior.

**Comment by rpanchyk** [comment]
PBS-Java keeps original `seatbid.bid.ext.prebid.meta` and passes it in response to publisher.

**Comment by bretg** [comment]
Ok, I think we're good here. Closing. @Niksok, please re-open with details if this hasn't solved the issue. Thanks.
