### ISSUE TITLE
Handling requests containing both app and site

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1947]
It's a valid use case in PBJS post-bid to define something like:

```
pbjs.setConfig({ app: { bundle: "org.prebid.mobile.demoapp", domain: "prebid.org" }
```

However, Prebid Server reject any request containing both "site" and "app" which is specifically forbidden by ORTB2.5. 

We propose that PBS accept this scenario and drop `site` if both `site` and `app` are present, adding a  warning to the debug trace.

**Comment by SyntaxNode** [comment]
I am not keen on Prebid Server accepting an invalid OpenRTB request and altering the request to make it conform. As a counter proposal for this case, let's have Prebid.js perform the transformation you are describing before sending the request.

**Comment by bretg** [comment]
> let's have Prebid.js perform the transformation

Understood that this would be a preferable solution, but keep in mind that changes to PBJS take literally years to propagate out to all publishers.

That said, any pub affected by this issue would have adequate incentive to upgrade. So it might be ok to go this way.

**Comment by hhhjort** [comment]
I think we should do the change in Prebid.js in any case, to push the visibility back into the prebid server adapter at least. Silently dropping data makes debugging hard, if the code exists in the PBJS adapter, at least someone can trace the change happening there. If it takes too long for publishers to update, we could consider mirroring the change in PBS, perhaps with a config flag so hosts that prefer to enforce the OpenRTB standard can do that, and hosts that wish accommodate the bad PBJS  behavior can also do that.

**Comment by SyntaxNode** [comment]
Discussed in the Prebid Server Committee. We would prefer for this to be implemented in PBJS and to use this as an incentive for publishers to update their PBJS versions if they encounter the issue. There was also the suggestion for the error message from PBS to specify the minimum version of PBJS which addresses this situation.

**Comment by bretg** [comment]
Opened a PBJS issue. Closing this one.
