### ISSUE TITLE
Cookie_sync - prefer iframe over pixel when both are available

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1971]
We got a request from a publisher that Prebid Server should be able to prefer iframe syncs over redirect syncs. Currently the choice of which is used is based on the order of the configuration per-bidder.

A better solution would be to have the /cookie_sync endpoint prefer iframes when both are available and allowed. I can't imagine that many pubs or bidders would prefer redirects when both are allowed.

**Comment by SyntaxNode** [comment]
If we change PBS to always prefer iframe, that would remove a feature we have today where bidders decide in their user sync config which endpoint takes precedence if both are available.

I like what @hhhjort suggested in the PMC meeting, to give this option to the publisher.

We could implement a `preferiframe` bool or a more generic `prefer` string enum with values of `iframe` and `redirect`. This could be an argument to /cooke_sync and also included in the server side account config.

**Comment by SyntaxNode** [comment]
Discussed and decided at the Prebid Server Committee to remove the adapter default configuration and hardcode it to iframe. All adapters have so far chosen iframe as their default so there is no negative impact or breaking changes.

Publishers may continue to use filters on user sync requests to define their preference for iframe or redirect.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.205.0.

**Comment by bretg** [comment]
Closing this, as it will be done soon with https://github.com/prebid/prebid-server/issues/2173
