### ISSUE TITLE
Support audio in Prebid Server

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1972]
Conversant expressed interest in exploring what it would take to get PBS to support OpenRTB audio.

This issue tracks what work items would be needed to accomplish this. It would be good to have publishers weigh in and help prioritize features like audio ad podding. Our proposal is that any audio pod support would wait for OpenRTB 2.6.

Initial Requirements
1) PBS should allow bidders to define audio as a supported media type.
    - PBS-Go already allows 'audio' as a mediatype option in the bidder.yaml file. PBS-Java may not be doing the mediatype check.
2) PBS should confirm that the bid response mediatype was in the original imp
    - This is not currently being done for other mediatypes. Up for discussion.
3) The PBS mediatypepricegranularity feature should support audio
4) hb_format could take the value "audio"
5) Documentation should be updated with examples

**Comment by patmmccann** [comment]
There appears to be several test cases of working audio? Is it possible many users are already live ? https://github.com/prebid/prebid-server/blob/d384e91bf99f886927a2bd412fd439502a1de088/adapters/ix/ixtest/exemplary/simple-audio.json

**Comment by SyntaxNode** [comment]
PBS has audio support today, but it's not widely used and we're not sure if we need to add special support.

**Comment by bretg** [comment]
We've determined that this is just a docs issue. Wherever on docs.prebid.org the formats are listed, audio needs to be added along with banner, video, and native.

**Comment by bretg** [comment]
Updated the docs with https://github.com/prebid/prebid.github.io/pull/4123 . Note that audio pods are still not supported, but that will be done with the ORTB 2.6 pod support. 

Closing this issue.
