### ISSUE TITLE
PBS-core to suppress warning about $0 bids that aren't deals

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1973]
Related to Issue #1937 

Discussed in committee today. We agreed that the `"Bid "%s" does not contain a positive (or zero if there is a deal) 'price'"` warning should only be emitted to the client response in debug mode.

PBS-core should drop non-deal bids that are $0 or less during the bid validation step after emitting this warning to the client when in debug mode. In the metrics, this validation error should be lumped together with other types of invalid bid responses.

**Comment by bretg** [comment]
released with PBS-Java 1.77

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 2.6
