### ISSUE TITLE
gdpr.default_value is required and must be specified

### ISSUE THREAD

**Issue by mikael-lundin** [prebid/prebid-server#1992]
I was following the instructions on how to start prebid server on my local machine, but I always got this error while trying to start the server:

```
F0909 08:45:18.859190    3112 main.go:37] Configuration could not be loaded or did not pass validation: validation errors (1 error):
  1: gdpr.default_value is required and must be specified
exit status 1
```
I remidied this by setting a default value in the config under the bind env like so:
```
	v.BindEnv("gdpr.default_value")
	v.SetDefault("gdpr.default_value", 0)
```
Am I missing any step that is undocumented in how to start the server or are there any other issues? :D ( I might just be stupid as well )

I also tried to start the server using the dev container hoping that it was set as an env variable there but to no avail.

**Comment by mikael-lundin** [comment]
oh, and `./validate.sh` doesn't pick this up either.

**Comment by SyntaxNode** [comment]
You may set the `default_value` value in your VS Code environment variables:
```
"configurations": [{
        "name": "Workspace",
        "type": "go",
        "request": "launch",
        "mode": "auto",
        "program": "${workspaceFolder}",
        "env": {
            "PBS_GDPR_DEFAULT_VALUE": "0"
        },
        "args": []
    }
]
```

or create a `pbs.yaml` file:

```
gdpr:
  default_value: "0"
```

or if you want to edit the code, you need to remove the `v.BindEnv("gdpr.default_value")` and replace it with `v.SetDefault("gdpr.default_value", "0")`.

**Comment by SyntaxNode** [comment]
> oh, and `./validate.sh` doesn't pick this up either.

There is no need for the `default_value` to be configured when running the tests via `./validate.sh`.

**Comment by mikael-lundin** [comment]
aah, awesome, thanks! While I still have you on the line are there any way to get logs out of the server when running it locally? I'm trying to see the issues that I might have with my adapter but it's just not sending requests to the adserver and I would like to see why. :)

**Comment by mikael-lundin** [comment]
Never mind! :D I figured out how it worked!! ;D

**Comment by egsk** [comment]
> You may set the `default_value` value in your VS Code environment variables:
> 
> ```
> "configurations": [{
>         "name": "Workspace",
>         "type": "go",
>         "request": "launch",
>         "mode": "auto",
>         "program": "${workspaceFolder}",
>         "env": {
>             "PBS_GDPR_DEFAULT_VALUE": "0"
>         },
>         "args": []
>     }
> ]
> ```
> 
> or create a `pbs.yaml` file:
> 
> ```
> gdpr:
>   default_value: "0"
> ```
> 
> or if you want to edit the code, you need to remove `v.BindEnv("gdpr.default_value")` and replace it with `v.SetDefault("gdpr.default_value", "0")`.


It might be worth mentioning in the installation documentation, isn't it?
