### ISSUE TITLE
EEACountriesMap is not getting populated

### ISSUE THREAD

**Issue by pm-isha-bharti** [prebid/prebid-server#1999]
Currently in GDPR flow, when the GDPR signal is ambiguous, we check for the default GDPR value. For finding the default GDPR value we check if the country present in the request belongs to the EEA countries list or not. If yes, then GDPR is applied for that request. But in the current code, this country checking logic is not working, as `EEACountriesMap` is not getting populated.

Code where we check whether the country present in the request belongs to EEA countries or not: 
https://github.com/prebid/prebid-server/blob/48fcdfb3fe864044b18575b14cbb671dff89b94f/exchange/exchange.go#L336

Code where we populate `EEACountriesMap` from the `EEACountries`
https://github.com/prebid/prebid-server/blob/48fcdfb3fe864044b18575b14cbb671dff89b94f/config/config.go#L516

I think in the above code we wanted to populate `EEACountriesMap` instead of `NonStandardPublisherMap` and the length check in the `for` loop should be for `EEACountries`. Do we want to do something like this? 

> `for i := 0; i < len(c.GDPR.EEACountries); i++ {
		c.GDPR. EEACountriesMap[c.GDPR.EEACountries[i]] = s
}`

Please let me know if my understanding is correct?

Thanks

**Comment by SyntaxNode** [comment]
> Please let me know if my understanding is correct?

I believe your understanding is correct. This looks like a bug. I opened a PR to fix it.
