### ISSUE TITLE
PBS Version In Response Header

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#2010]
## Type Of Issue
Proposed Enhancement

## Description
A complimentary feature to https://github.com/prebid/prebid-server/issues/1818, allows publishers to inspect from the response headers for which version of PBS handled their bid request. Useful for monitoring/logging, especially during a deployment where multiple versions running simultaneously and the response from the version endpoint may not be accurate. This is useful for hosts to monitor deployment progress and issues.

## Proposal
PBS creates a header in the response to a bid request with the PBS version, ex:
```
x-prebid: pbs-go/0.178.0
```

**Comment by bretg** [comment]
Discussed in PBS committee. No objections.

**Comment by bretg** [comment]
Released with PBS-Java 1.79

**Comment by SyntaxNode** [comment]
implemented in PBS-Go 0.190.0
