### ISSUE TITLE
where PBS get the currency from to send in requets?

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#2050]
We are seeing some weird going on, the prebid server requests are going out with currency GBP,  we use the "currency module" to convert bids into GBP for sending to the ad server.  We have nowhere else set in code to request in GBP:

How is prebid server setting these as GBP?  Its messing up one of our bidders i.e. IX, as they expect USD and we are expecting bid requests go out as USD anyway and be "converted" by the currency module on their way back in and for targeting
![Inbox__24_378_messages__1_256_unread_-_Connection_Logging_Enabled_](https://user-images.githubusercontent.com/8503167/137816092-b6c01ddc-80a2-48f4-aea1-5cf7e32ffdd3.png)

**Comment by spormeon** [comment]
your picking it up from where the currency module params are defined i.e this sends cur: GBP, where as it's not, thats the adServerCurrency and requests should go out USD
currency: {
						'adServerCurrency': "GBP",
						'granularityMultiplier': 1,
						'conversionRateFile': 'https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json',
                       
If I change to this cur gets set:USD
currency: {
						'adServerCurrency': "USD",
						'granularityMultiplier': 1,
						'conversionRateFile': 'https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json',

**Comment by spormeon** [comment]
so is it prebid js or prebid server that picks up and sends the adServerCurrency   from the currency module?

**Comment by bretg** [comment]
Are you asking how to force the PBJS prebidServerBidAdapter to produce $.cur=USD even though the desired currency is GBP? And the reason this is desired is to workaround a bid adapter currency problem?

Looking at the code, unfortunately I don't see a way to override the pbsBidAdapter behavior.

Someone could patch a copy of PBJS with something like s2sConfig.currencyOverride. Or we could just get the root problem addressed.

**Comment by kizzard** [comment]
Hi everyone, just to clarify, this is not so much a bug in the IX adapter - it just requires some additional configuration on our end to allow non USD bidding (typically this is negotiated during initial setup), and this requirement will be going away, hopefully in the next month or so and should no longer pose a problem.

**Comment by bretg** [comment]
Closing this ticket with reference to https://github.com/prebid/Prebid.js/issues/7597
