### ISSUE TITLE
Is the any metrics document of prebid-server golang？

### ISSUE THREAD

**Issue by yuanjize** [prebid/prebid-server#2069]

**Comment by mansinahar** [comment]
@yuanjize Unfortunately no, at this time we don't have any documentation for metrics but it'd definitely be good to have them so thanks for creating this issue. We will look at adding them unless you want to volunteer ;) 

For now, you should be able to find all the metrics that Prebid Server exports here: https://github.com/prebid/prebid-server/blob/master/metrics/go_metrics.go#L15 and if you have any questions about any of those metrics or what they mean, we're happy to answer them.

**Comment by yuanjize** [comment]
> 

Thanks

**Comment by SyntaxNode** [comment]
I'm going to close this issue. Please follow https://github.com/prebid/prebid-server/issues/1191 for config docs. It's on our list. We're currently focusing on feature development.
