### ISSUE TITLE
SChain OpenRTB Backwards Compatibility

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#2080]
# Problem

The location of the SChain object was changed in OpenRTB 2.5 from previous versions. PBS (at least PBS-Go) only supports the OpenRTB 2.5 location since that's the version of the spec PBS implements. Here's the relevant quote from the [SChain Specification](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md):

> The SupplyChain object should be included in the BidRequest.Source.ext.schain attribute in OpenRTB 2.5 or later. For OpenRTB 2.4 or prior, the BidRequest.ext.schain attribute should be used.

The lifecycle of extensions was recently discussed in the IAB Programmatic Working Group and it was called out that while the newer locations are preferred, software should also fall back to previous locations. 

# Proposal

Enhance PBS to look for SChain objects at both the current OpenRTB 2.5 `BidRequest.Source.ext.schain` location and fallback to the older `BidRequest.ext.schain` location if not found. If both are defined, The OpenRTB 2.5 location will be used.

**Comment by bretg** [comment]
It's fine to conform to this recommendation, but for the record, it unclear to me that PBS will ever see $.ext.schain -- the PBJS module sets it in $.source.ext.schain, and PBS host companies can control where it's set in stored requests.

**Comment by bretg** [comment]
Discussed in PBS committee. Xandr has a publisher calling PBS directly with the ORTB2.4. 

The proposal is:
if $.source.ext.schain doesn't exist but $.ext.schain does, PBS would copy the latter to the former so that all bidders will see it in the ORTB2.5 location.

**Comment by bretg** [comment]
Done in PBS-Java 1.84
