### ISSUE TITLE
PBS needs to support imp.ext.gpid

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2088]
Related to https://github.com/prebid/Prebid.js/issues/7367

The OpenRTB location for GPID is imp.ext.gpid. Prebid Server filters imp.ext for valid bidders except for a list of "reserved" strings: all, context, data, general, prebid, or skadn

We need to add "gpid" to the list of reserved words ASAP.

**Comment by SyntaxNode** [comment]
Shouldn't be a problem. Could you please point me to the spec for the imp.ext.gpid extension? Is this a standard IAB thing?

**Comment by bretg** [comment]
It's not yet a formal IAB extension, but several of our publishers have received notice from TradeDesk that this parameter is soon to be required.

**Comment by bretg** [comment]
Here's the prebid.org doc -- https://docs.prebid.org/features/pbAdSlot.html#the-gpid

**Comment by bretg** [comment]
Released with PBS-Java 1.80

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.188.0.
