### ISSUE TITLE
Pubmatic usersync doesn't work on http website

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#21]
I run my test page on http, prebid server endpoint is http too. I send bid request and receive usersync field in response

    {
        "bidder": "pubmatic",
        "no_cookie": true,
        "usersync": {
            "url": "https://ads.pubmatic.com/AdServer/js/user_sync.html?predirect=http://localhost:8000/setuid?bidder=pubmatic&uid=",
            "type": "iframe"
        }
    }

Usersync url is https, and when https iframe tries to redirect back to http page I get Mixed Content error. The issue can be fixed it seems by removing protocol from usersyncURL

In pubmatic.go line 145:
usersyncURL := "//ads.pubmatic.com/AdServer/js/user_sync.html?predirect="

**Comment by bokelley** [comment]
Updated in https://github.com/prebid/prebid-server/pull/15

**Comment by asweeney86** [comment]
Should be fixed in latest release
