### ISSUE TITLE
OpenRTB support: Rubicon adapter

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#210]
Now that #196 has landed, the `/openrtb2/auction` endpoint is (technically) live. This deprecates `/auction`, and moves the project towards #150.

The next step is to update existing adapters to support it. Documentation can be found [here](https://github.com/prebid/prebid-server/blob/master/docs/developers/add-new-bidder.md). I'm not sure whether it's easier for you to create a new struct or add functions to your existing one. Both are equally sensible as far as I'm concerned.

@bretg @DucChau This issue is for updating the Rubicon adapter. Please let me know if you have questions (or, if you figure things out, submit a PR to the docs to clarify things)

**Comment by bretg** [comment]
acknowledged - someone should start on this next week

**Comment by smartbidder1** [comment]
Rubicon adapter need a password, where do I get one?
