### ISSUE TITLE
hb_size vs hb_pb

### ISSUE THREAD

**Issue by Outrajous** [prebid/prebid-server#2113]
Hi all, newbie and noobie here to learn more about prebid. Hopefully a simple question. 

To check an SSPs internal wins/bids placed going into the client's ad server for discrepancies, we ask clients to send an ad server report by the key-value "hb_pb_partner" to compare against. 
This also gives us the bid value, but I am just looking for impressions bids are placed on. 
However, I've got a report with "hb_size_partner" instead. Would this also provide the bid on impressions? of course, I won't get the bid value, which is fine for my use case. I hope this makes sense.  

Thanks
Raj

**Comment by hhhjort** [comment]
If you are only interested if an SSP bid on an auction, then "hb_size_partner" can work. It will only be populated if the SSP submits a bid. (It is populated by the size of the ad the SSP bid with.) However it is not as reliable for 2 reasons. First is that it is a potentially optional parameter (the adserver does not normally use this key/value in determining the outcome of an auction). As such, prebid could be configured to not send it in certain circumstances. I do not think it likely that a publisher would go through the trouble of configuring this to be only sometimes on, I do not see a valid use case for this worth the effort.

The second issue is that GAM, at least, will only record key/value pairs if both the key and value are predefined before the auction. If an SSP should bid with a non-standard ad size, this key/value would not be recorded into the reports, and thus appear as if they did not bid. I would not expect this to happen often, but feels like it would be a more common occurrence than the configuration work in the first issue. As such, hb_size_partner may be useful in your case, but could potentially underreport the number of bids from each SSP. "hb_pb_partner" could also potentially underreport for some reasons, but in the case where "hb_pb_partner" does not report, it is impossible for the SSP to win the auction. An SSP could potentially win an auction in the case that "hb_size_partner" does not report for that auction.

Does this answer your question?

**Comment by Outrajous** [comment]
Many thanks, hhhjort, it does answer my question and more.
