### ISSUE TITLE
Initial question about Prebid Server

### ISSUE THREAD

**Issue by ramonsza** [prebid/prebid-server#2123]
We are starting with prebid server trying to make a request using the rtbhouse adapter but all the answers are coming as noBid, the server has no errors in the generated logs

**Comment by bretg** [comment]
@ramonsza - you should add the "ext.prebid.debug" flag to the request as described in the troubleshooting guide https://docs.prebid.org/troubleshooting/pbs-troubleshooting.html

If the request is going to the bidder endpoint, then it's not an issue with Prebid Server -- you would need to work with that bidder to determine why:
- incorrect parameters (placement, etc)
- missing parameters (ID, device info, etc)
