### ISSUE TITLE
Listen to unix socket instead of tcp ?

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#2147]
Is there currently a way to make prebid-server listen to a unix socket instead of tcp port ? My prebid-server isn't exposed but behind a app acting as a proxy to build the openrtb request send to prebid-server, so using unix socket could avoid me to reach tcp limits.

**Comment by bretg** [comment]
@matthieularere-msq - can you please elaborate on this request?

- Prebid Server is HTTP, which is TCP.
- Why can't you just raise the TCP limit? Or lower the keepalive?
- Would HTTP2 connection pooling be a solution?
 
Sounds like you have a server running on the same box and can assume a same-box connection to PBS?

**Comment by matthieularere-msq** [comment]
Indeed, it's a same-box connection to PBS.
I can try fine tune TCP but at the end the issue could reappear later as a limit would remain. That's why I thought about unix socket.
HTTP2 could worth a try. Apart from using http2 package would it requires a lot of code changes ?

**Comment by bretg** [comment]
One of the engineers will have to weigh in on whether there's much work to support HTTP2 inbound for PBS-Go and/or PBS-Java. That seems like the easiest approach here, IMO.

**Comment by SyntaxNode** [comment]
@matthieularere-msq So you are looking to use HTTP over Unix Sockets?

There is not currently an option to listen on Unix Sockets, but I don't see a reason why not to give the Host an option. Are you interested in putting up a PR for this?

I found an [example here](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74) for how to bind to Unix Sockets in Go. Looks simple. The appropriate place to implement this in PBS-Go is: https://github.com/prebid/prebid-server/blob/2ac9d20db8667cf75a5e891e73e049d0e80eb4ea/server/server.go#L96

You would need to pass the configuration down to those calls (one for admin endpoints and another for the main endpoints). Are you using Prometheus? I haven't looked into how to add Unix Socket support on that endpoint.

I'm also cool with using HTTP2. I think PBS-Go already has support for HTTP2 incoming connections if you'd like to give it a try.

**Comment by matthieularere-msq** [comment]
@SyntaxNode Thanks, I'll try to see if I manage to make unix socket work, if so I'll submit a PR.

I've tested pbs-go with http2 but it's not supported:
`$ curl -I --http2-prior-knowledge http://localhost:8000/openrtb2/auction
curl: (16) Error in the HTTP2 framing layer`

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.208.0 by community contributor @mediasquare-alexandre.

To use this feature, set the `unix_socket_enable` configuration value to "true" and  optionally change the `unix_socket_name` configuration default value from `prebid-server.sock` to a value of your choosing. Enabling Unix Sockets will disable the TCP endpoint, as we don't foresee a use case where both would be used.

**Comment by SyntaxNode** [comment]
@bretg Does PBS-Java plan on adding a similar feature?

**Comment by bretg** [comment]
Maybe VertX already supports it. Adding @SerhiiNahornyi to confirm

**Comment by bretg** [comment]
Done in PBS-Java 1.91
