### ISSUE TITLE
Support new meta field: DemandSource

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2157]
Prebid.js metadata has been expanded to include a new field `DemandSource`. This maps to seatbid.bid.ext.prebid.meta.demandsource in ORTB2

While 'NetworkName' is a Bidder-specific network/DSP name, 'DemandSource' is a Bidder-specific business entity used for bid adapters that can 'white-label' other sources.

For both PBS-Go and PBS-Java, please add DemandSource as an allowed value in seatbid.bid.ext.prebid.meta coming from the adapters and update the relevant documentation.

**Comment by SyntaxNode** [comment]
> 'DemandSource' is a Bidder-specific business entity used for bid adapters that can 'white-label' other sources.

How is that different from a publisher provided alias?

**Comment by bretg** [comment]
It's basically a bidder-supplied alias. Yes, another layer of multiplexing. Apparently bids from the grid bidder can come from several actual sources.

**Comment by SyntaxNode** [comment]
PBS-Go already supports DemandSource metadata. We just need to update the docs.

**Comment by SyntaxNode** [comment]
Documentation has merged.
