### ISSUE TITLE
Rubicon calls setuid on prebid.adnxs.com event when endpoint is different

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#22]
I get the following response from my prebid server

{
        "bidder": "rubicon",
        "no_cookie": true,
        "usersync": {
            "url": "https://pixel.rubiconproject.com/exchange/sync.php?p=prebid",
            "type": "redirect"
        }
    }

Usersync url says nothing about the callback domain. And when prebid calls that usersync url it always calls https://prebid.adnxs.com/pbs/v1/setuid?bidder=rubicon&uid= even when I run prebid server locally and changed the endpoint accordingly. I guess adnxs.com url is hardcoded on rubicon's side.

**Comment by bokelley** [comment]
I'll make the usersync URLs configurable so that it's not tied to the defaults.

**Comment by bokelley** [comment]
See latest push in https://github.com/prebid/prebid-server/pull/15

**Comment by asweeney86** [comment]
This should be fixed in the latest release

**Comment by dmitriyshashkin** [comment]
It is now possible to use different usersync URLs, but it's not quite clear how to specify custom callback url for rubicon. I wasn't able to find any documentation from rubicon on how to do the user sync. I've sent an email to rubicon support, but mb this information should be included into prebid-server documentation. What would be even better if there was no need to specify callback url manually, but instead it would be passed to rubicon just the way it happens with other bidders.

**Comment by bokelley** [comment]
I agree with your point, but that's the pixel structure that Rubicon has provided to date. Please feel free to reach out to them to suggest they have a more flexible format in the future.

**Comment by dmitriyshashkin** [comment]
I guess it should be reflected as a warning in the docs somewhere.
Rubicon is unable to keep up with the pace of innovations prebid has set! :-)

**Comment by mkendall07** [comment]
@bretg
Do you know if Rubicon supports the preferred pixel syncing format (query string redirect)?

**Comment by bretg** [comment]
Forwarded this issue internally.
