### ISSUE TITLE
Update Pubmatic adapter contact info

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#220]
I recently merged #209, which adds emails for the maintainers of each adapter.

@PubMatic-OpenWrap, please update the `adapters/pubmatic/info.yaml` file with a contact email. We'll use this to get in touch if project changes require major changes to all the existing adapters.

**Comment by PubMatic-OpenWrap** [comment]
Hi @dbemiller, 
We have updated contact information for PubMatic Adapter #222.

**Comment by dbemiller** [comment]
Awesome. Thanks for the quick response time!
