### ISSUE TITLE
StoredBidResponse update

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2210]
I've been working with storedbidrequests more often and found there's an unreasonably difficult challenge in creating them because they currently have to match the 'impid' of the incoming request.

I propose update PBS' handling of storedbidrequests to ignore the impid supplied and instead create/overwrite seatbid.bid.impid with the value that matches the incoming request.

Example request:
```
{
  imp: [{
    id: "abc123",
    ext: {
       prebid: {
           storedbidresponse: [
               { "bidder": "rubicon", "id": "1001-testbid-300x250", "replaceimpid":true }
           ],
           bidders: {
               rubicon: { ... }
           }
       }
    },
    ...
}
```

When PBS reads the DB entry for 1001-testbid-300x250, PBS-core should modify the value in the following way if the flag is present:

1. loop through the seatbid[] array
2. Loop through the bid[] arrray
3. for each seatbid.bid, if replaceimpid is true, create or overwrite the impid value with the imp.id from the original request. (e.g. in the above example, "abc123"). Note that replaceimpid is true if not specified.

 
## Debug output

I also propose adding a debug warning to note that the bidder's response was not actually from the bidder. The debug log currently leads one to believe a request was actually made to the bidder's endpoint:
```
    "ext": {
        "debug": {
            "httpcalls": {
                "rubicon": [
                    {
                        "uri": "https://exapi-rpprebidserver-us-east.rubiconproject.com/a/api/exchange?tk_sdc=us-east",
                        "requestbody": "{...}",
                        "responsebody": "{...}",
 ```
If possible, it would be ideal to have the debug logs overwrite the requestbody.
```
    "ext": {
        "debug": {
            "httpcalls": {
                "rubicon": [
                    {
                        "uri": "https://exapi-rpprebidserver-us-east.rubiconproject.com/a/api/exchange?tk_sdc=us-east",
                        "requestbody": "PBS: not sent to endpoint due to stored bidbidresponse override",
                        "responsebody": "{...}",
 ```
If that's not easy, minimally, add a warning to the bottom of the file:
```
ext.warnings.rubicon: [{ message: "request not sent to endpoint due to stored bidbidresponse override" }]
```

**Comment by bretg** [comment]
Discussed in PBS committee. We added the 'replaceimpid' flag and approved for development.

**Comment by VeronikaSolovei9** [comment]
Hi Bret, I know Stored bid responses are not yet enabled in PBS, but here is how it works: 
Imp id for input request always present in corresponding stored bid response. This is not optional, but if it has to be - I'll add `replaceimpid` option. 

In debug log we can see what request was "real" and what was not. Real request have all http calls data like url, headers, request and response. While stored bid responses have response only and a note it was a stored bid response:

```
    "uri": "",
    "requestbody": "Stored bid response for impression id: 1_0",
    "requestheaders": null,
    "responsebody": "{ ....response body here... }"
```

**Comment by VeronikaSolovei9** [comment]
After today's release stored bid and auction responses available in PBS. 
Here is an imp.ext example to test it:
```
"ext": {
                
                "telaria": {
                    "seatCode": "123"
                },
                "openx": {
                    "unit": "123",
                    "delDomain": "test.openx.net"
                },
                "prebid": {
                    "bidder": {
                        "appnexus": {
                            "placementId": 123
                        }
                    },
                    "storedbidresponse": [
                        {
                            "bidder": "appnexus",
                            "id": "d3fa8c49-c36a-e2a5-a1fe-1f90afa27b93"
                        },
                        {
                            "bidder": "telaria",
                            "id": "d3fa8c49-c36a-e2a5-a1fe-1f90afa27b93"
                        },
                        {
                            "bidder": "openx",
                            "id": "bc75546d-2e09-83d0-8231-5ca89894707b"
                        }
                    ]
                }
            }
```

**Comment by bretg** [comment]
@VeronikaSolovei9 - is `replaceimpid` done in PBS-Go?

We just released it for PBS-Java in 1.92

**Comment by VeronikaSolovei9** [comment]
Added PR https://github.com/prebid/prebid-server/pull/2313, now in draft mode, need to fix and add unit tests, but functionality of replaceImpId is working already.

**Comment by VeronikaSolovei9** [comment]
PR is merged, please confirm if this issue can be closed
