### ISSUE TITLE
Random selection of stored responses for testing

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-server#2212]
## Motivation 

Simulate the real sequence of bid responses in order to test mobile SDK.

## Objectives

Provides the ability to set several response options so the PBS returns one of them for each bid request randomly. 

## Example 

To support the multiformat ad unit we would like to make a bid request that will randomly return:
- Banner ad as a winning bid
- Video ad as a winning bid
- No bids

We want to repeat the same request and test the behavior respectively to the randomly received response. So we will be sure that SDK works properly in a real-life scenario.

In order to achieve it, we would like to provide three respective `storedauctionresponse` entries in the bid request and allow PBS to return one of them in the bid response. 

## Proposed solution

Introduce a boolean property for the bid request - `randomresponse`.

If the value of this flag is `true`, the PBS should use only one entry from `storedauctionresponse` or `storedbidresponse` arrays.

## Alternative Client-Side solution

Such behavior could be achieved on the client-side, by providing the different stored responses for each request. 

This solution has several negative aspects: 
- adding the test-purpose code to the release SDK code and public API.
- adding a dependency on the test code to the behavior. So such a setup won’t guarantee real-life behavior.

But if you think that such a feature might be helpful not only for the SDK integration scenario, the best place for its implementation is PBS.

**Comment by bretg** [comment]
After considering the potential implementations and several internal discussions, I'm going to close the general "Dynamic Stored Req" issue and re-open this one, focusing it as a test feature.

**Comment by bretg** [comment]
A minimally invasive solution (from a server-perspective) would be to only support the feature for storedrequests. e.g. say that there are 3 stored responses set up: resp1, resp2, and resp3.
 
Here's a proposed syntax:
```
imp[].ext: {
        "prebid": {
          "storedrequest": { "test-ids": ["resp1","resp2","resp3"] }
        }
}
```

Then at the front of PBS processing, if it sees imp.ext.prebid.storedrequest or ext.prebid.storedrequest without an `id` attribute, it would look for a `test-ids` attribute and randomly choose one of the items in the array.

Seems like any solution would require some kind of SDK support, so is this one acceptable @YuriyVelichkoPI ?

**Comment by bretg** [comment]
Talked with Yuriy and came to understand this proposal would be much better if the storedresponse supported the array.

1) Mobile app testers can set up a single config ID, e.g. "random-stored-response-set-1"
2) The Prebid Server host company can publish a set of stored requests that contain stored responses that have an array. e.g.

```
ext.prebid: {
    "storedauctionresponse": { "test-ids": ["top-resp1","top-resp2","top-resp3"] }
}
```
or
```
imp[].ext: {
        "prebid": {
          "storedauctionresponse": { "test-ids": ["imp-resp1","imp-resp2","imp-resp3"] }
        }
}
```
3) PBS-core would see ext.prebid.storedauctionresponse or imp.ext.prebid.storedauctionresponse . If that object contains an `id` field, it just loads the object from the storedresponses db/file keyed to the id.
4) If that object doesn't contain an `id` field and does contain `test-ids`, PBS-core would:
    1. confirm that `test-ids` is an array and each element is a string. If not, it's an error. Put in the debugging output "invalid storedresponse content for storedrequest ____".
    2. else, PBS-core picks a random array element and uses that as if an `id` had been passed

**Comment by YuriyVelichkoPI** [comment]
Hi @bretg ! The above approach is what we would like to have!

**Comment by bretg** [comment]
Spoke with Yuriy again. We're going to withdraw this request for the time being.
