### ISSUE TITLE
PBS KVPs for deals

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2214]
Supporting deal targeting is currently inconsistent across Prebid.js, SDK, and AMP.

I've added a note to https://docs.prebid.org/prebid-server/features/pbs-deals.html to describe the difference, but we should discuss whether a new PBS behavior is warranted. I think it may be. This is somewhat related to the PBJS issue https://github.com/prebid/Prebid.js/issues/8130 , but I don't think we need major surgery on PBS.

Here are the current KVP controls in PBS:

- ext.prebid.targeting:
    - includewinners - flag for whether seatbid.bid.ext.prebid.targeting is generated for the winning KVPs
    - includebidderkeys - flag for whether seatbid.bid.ext.prebid.targeting is generated for non-winning KVPs
    - includeformat - flag for whether seatbid.bid.ext.prebid.targeting.hb_format, hb_format_BIDDER are generated
    - preferdeals - flag for controlling PBS decisioning: by default, it's the highest bid that wins, but if this is true, the highest deal will beat out non-deals.
- ext.prebid.adservertargeting: supports arbitrary KVPs https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#custom-targeting-pbs-java-only

## Proposed new KVP flag: alwaysincludedeals

PBS could support a ext.prebid.targeting.alwaysincludedeals that corresponds to the Prebid.js [alwaysIncludeDeals](https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-targetingControls) flag.

If true, then PBS-core would generate seatbid.bid.ext.prebid.targeting.hb_*_BIDDER values for all bids with a dealid. This is independent of which other ext.prebid.targeting flags are present.

We would also update the pbsBidAdapter to set this flag to true when the corresponding PBJS flag is set.

**Comment by bretg** [comment]
approved in committee

**Comment by bretg** [comment]
Released with PBS-Java 1.89. Updated auction endpoint docs.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go v2.8.0.
