### ISSUE TITLE
Global KVPs

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2223]
The HighFivve team has a use case where they want PBS to be able to inject targeting (KVPs) at the global level, rather than at the impression level. Specifically the use case is for AMP.

Here's the proposal, which is implemented in https://github.com/prebid/prebid-server-java/pull/1730/files

1. We've defined a new ORTB extension on the bid response: ext.prebid.targeting
2. Modules can add whatever they want to this object
3. The object is passed back to the client (PBJS, SDK) to be used there as desired
4. The AMP response-generating code looks at ext.prebid.targeting and injects values seen there

Assuming the community agrees to this new extension, we would take the following steps:
1. Document the extension
2. Open the conversation with the PBJS and SDK teams about whether ext.prebid.targeting would serve a use case for ad server targeting for them.

**Comment by bretg** [comment]
Discussed in committee:
- if there's a collision in targeting, the targeting defined in the bid should take precedence.
- we should discuss minimizing the number of keys sent to the ad server. e.g. pbs_keys="k1:v1&k2:v2&..."

**Comment by bretg** [comment]
Since the extra keys are optional at this point, and not produced by anything except a private module, we're going to let the issue of how many keys are sent to the ad server be the concern of future projects.

**Comment by hhhjort** [comment]
To be clear, by "global" you mean extra key/values set outside the normal ones generated from the bids by core PBS based on the prebid "targeting" flags? "Global" as in "across all imps" doesn't mean much in the AMP use case which is locked to 1 imp. :)

**Comment by bretg** [comment]
Right - "global" as in "not in the imp object"

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.241.0.
