### ISSUE TITLE
test java server locally

### ISSUE THREAD

**Issue by kachok1213** [prebid/prebid-server#2227]
Hi
How can I test the java server locally?
I followed the instructions, cloned proj ,built with mvn, and its running and looks ok
then i sent /status and got 200 - ok till here its all looks good
then i tried /auction with the sample in prebid , and getting the following error:
Error occurred while populating bid request: Host is not defined or can not be derived from request

i guess its because im on localhost, i had another problem before with the request ip, but x-forwarded-for fixed it
however, x-forwarded-host not worked.
any help? thanks a lot !

**Comment by SyntaxNode** [comment]
This sounds to me like a configuration issue.

PBS-Java has it's own GitHub repository at https://github.com/prebid/prebid-server-java which is likely best for this sort of question. I'll also mention @bretg to see if he can point you in the right direction.
