### ISSUE TITLE
How to add new adapters to old prebid installation

### ISSUE THREAD

**Issue by GenarC** [prebid/prebid-server#2230]
Hi, we want to addnew adapters to our custom prebid server. How should we proceed to add new adapter support. The ad networks we wanted to add is not present in prebid serve adapter folder. Just coppying the new adapters  enough or are there any files need to be changed for the support?

**Comment by bretg** [comment]
Sorry @GenarC , we cannot support Prebid Servers that have been forked from the open source code and diverged into custom sub-species. 

That said, I'm not sure what your question really is:

1) If you need to create adapters for endpoints that don't already exist, the documentation is here -- https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html . 

2) If you need to add an adapter that exists in a more recent open source version of the server, I think what you need to do is:
a) port your custom changes to a recent version of Prebid Server
b) consider submitting changes to the open source that make your customization easier or even unnecessary.

**Comment by bretg** [comment]
@GenarC - closing this out. Please re-open with a refined question as needed. Thanks.
