### ISSUE TITLE
Just installed prebid-server and it asks for a configuration file that is not documented anywhere

### ISSUE THREAD

**Issue by musikele** [prebid/prebid-server#2231]
Once installed pbs, by following all steps, it asks for a gdpr setting in order to work.

This step is not easily findable, I had to dig into the code and I can't imagine anyone not proficient with go to understand what to do. 

Please add a step in the README with the required configuration, at least to make it start.

**Comment by SyntaxNode** [comment]
Yes, exactly. It's been on our list and I've bumped it's priority based on this issue. I agree it's a problem. This is actually a duplicate issue from https://github.com/prebid/prebid-server/issues/1897, so I'm going to close this thread. Please look at that issue for details on configuring the gdpr default value.
