### ISSUE TITLE
bidder-specific user.data issue

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2234]
Over in PBJS issue https://github.com/prebid/Prebid.js/issues/7918 @wqi1972 reported what is actually a PBS bug.

Here's a test request. Note that ext.prebid.bidderconfig specifies user.data, but user.data doesn't exist at the top level.
```
{
    "id": "e37155be-77b5-4ca8-852a-58b4e6822451",
    "source": {
        "tid": "8045e521-858a-4b37-8817-9ea1aefe20ce"
    },
    "tmax": 1000,
    "imp": [
        {
            "ext": {
                "data": {
                    "adserver": {
                        "name": "gam",
                        "adslot": "/19968336/header-bid-tag-0"
                    },
                    "pbadslot": "/19968336/header-bid-tag-0"
                },
                "gpid": "/19968336/header-bid-tag-0",
                "grid": {
                    "uid": 1
                }
            },
            "id": "div-gpt-ad-1460505748561-0",
            "banner": {
                "format": [
                    {
                        "w": 300,
                        "h": 250
                    },
                    {
                        "w": 300,
                        "h": 600
                    }
                ]
            }
        }
    ],
    "test": 0,
    "ext": {
        "prebid": {
            "auctiontimestamp": 1647412648319,
            "targeting": {
                "includewinners": true,
                "includebidderkeys": false
            },
            "channel": {
                "name": "pbjs",
                "version": "v6.16.0-pre"
            },
            "debug": true,
            "bidderconfig": [
                {
                    "bidders": [
                        "grid"
                    ],
                    "config": {
                        "ortb2": {
                            "user": {
                                "data": [
                                    {
                                        "name": "permutive.com",
                                        "segment": [
                                            {
                                                "id": "pcrprs1"
                                            },
                                            {
                                                "id": "pcrprs2"
                                            },
                                            {
                                                "id": "ppam1"
                                            },
                                            {
                                                "id": "ppam2"
                                            },
                                            {
                                                "id": "1000001"
                                            },
                                            {
                                                "id": "1000002"
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    }
                }
            ]
        }
    },
    "site": {
        "publisher": {
            "id": "1001"
        },
        "page": "http://localhost:9999/integrationExamples/gpt/gdpr_hello_world.html?pbjs_debug=true",
        "ref": "http://localhost:9999/integrationExamples/gpt/gdpr_hello_world.html?pbjs_debug=true"
    },
    "device": {
        "w": 1700,
        "h": 642
    }
}
```
This works in PBS-Java, but gets a nice clear error message in PBS-Go: `Invalid request: incorrect First Party Data for bidder grid: User object is not defined in request, but defined in FPD config`.

This was not the intention. I've updated the [PBS First Party Data document](https://docs.google.com/document/d/1I2eS40yMYJCgz8XvFljf4f59bEPsbWTrUpnD7a7uJEg/edit#) to make the desired behavior clear. Section 2.1 req 7a now says:

```
If the attribute defined in ext.prebid.bidderconfig.config.ortb2 doesn't exist in the original ORTB object, it should be created for the specified bidder(s).
```

**Comment by SyntaxNode** [comment]
@bsardo and @VeronikaSolovei9 will look into this for PBS-Go.

**Comment by bretg** [comment]
This was discussed in the committee last week. There was a proposal to allow creating the User object, but not App or Site since it would always invalidate the request.

Unfortunately I don't agree -- behavior should be consistent: either PBS creates the object or it doesn't. My take is that invalid ext.prebid.bidderconfig.config.ortb2 is invalid.

i.e. 
- if it's an app request and ext.prebid.bidderconfig.config.ortb2.site exists - PBS will reject the request. This is in fact a strange invalid request and an error is appropriate.
- if ext.prebid.bidderconfig.config.BLAH is specified, PBS will create that field, but it will later get dropped due to ORTB schema validation

**Comment by bretg** [comment]
I don't feel the FPD logic should be doing the validation if that's what you're saying. Rather, I would keep the FPD logic simple (i.e. create destination objects as needed) and let downstream validations do their thing.

**Comment by bsardo** [comment]
@bretg sorry if I confused you. It seems like we're into the implementation details now. If we ignore those details for a second and just look at things at a system level, I believe the question is whether the following requests are considered valid or invalid. Our team believes these two requests should be considered invalid:

Request 1 (no app/site in base request but one of them is in `bidderconfig`):
```
{
    "ext": {
        "prebid": {
            "bidderconfig": [{
                "bidders": ["appnexus"],
                "config": {
                    "ortb2": {
                        "site": {
                            "page": "prebid.org"
                        }
                    }
                }
            }]
        }
    }
}
```

Request 2 (app or site in base request with the other in `bidderconfig`):
```
{
    "app": {
        "publisher": { "id": "test"},
        "page": "prebid.org"
    },
    "ext": {
        "prebid": {
            "bidderconfig": [{
                "bidders": ["appnexus"],
                "config": {
                    "ortb2": {
                        "site": {
                            "page": "prebid.org"
                        }
                    }
                }
            },{
                "bidders": ["rubicon"],
                "config": {
                    "ortb2": {
                        "app": {
                            "episode": 6
                        }
                    }
                }
            }]
        }
    }
}
```

If you agree, then I believe that means that every bidder request will have either site or app in it and the base request the bidder request was derived from will have had that same root element (site or app) defined in it.

As for implemention, this can be handled in various ways.
In PBS-Go, we chose to extract FPD and validate it against the base request after the base request has already been validated. We chose this path in an effort to optimize for performance so we can fail fast if there are obvious problems in the base request, effectively skipping all of the FPD extraction which would have been unnecessary. In that case, we never end up creating app or site in a bidder request.
I definitely see the implementation you're suggesting as well where you handle all validation after bidder requests have been constructed with site or app objects having been created from the `bidderconfig`.
We can continue chatting about these details if you think they are important here but I'm not sure these details matter for the sake of our discussion.

Brian

**Comment by SyntaxNode** [comment]
@bretg Are we good here?

**Comment by bretg** [comment]
I agree:
- that the original base request ought to specify either site or app.
- that something ought to validate ORTB after merging in the bidderconfig

not only could such merging introduce the other of app/site, but it could also introduce invalid ORTB. e.g. site.blahblah.

**Comment by bsardo** [comment]
@VeronikaSolovei9 we are in agreement that either site or app should be present in the base request. If neither or both are provided it should result in an error. That is the current PBS-Go behavior so no change is required.

However, please update PBS-Go such that requests received containing `ext.config.bidderconfig.ortb2.user` but missing `user` in the base request no longer result in the aforementioned error. Instead, in this scenario, the bidderconfig `user` object should become the root `user` object in the bidder requests for the relevant bidders.
