### ISSUE TITLE
Discuss validating US-Privacy string

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2236]
We had an issue where a CMP was passing PBS a long and invalid regs.ext.us_privacy field.

Would like to get feedback on whether PBS should be validating the us_privacy string. Trying to keep up with likely future changes in valid formats is something I'd rather avoid.

But we could build in a compromise approach. Something like: if us_privacy starts with a "1", then expect 3 Y/N chars afterwards. If it doesn't start with a number, filter it. Anything else, let it through.

That would solve this particular data quality problem, but we'll have to decide whether it's going to be a hard-reject on invalid string or just removing the value. In general, hard-reject is our philosophy, but with live apps already on it, that might not be tenable. The behavior could be host-company configurable.

In fact, host-company configuration might be a way to handle the likelihood of future changes. e.g. we could support configurable validation regexes?

**Comment by SyntaxNode** [comment]
> Would like to get feedback on whether PBS should be validating the us_privacy string.

PBS enforces CCPA and therefore needs to validate and parse the string.

> But we could build in a compromise approach. Something like: if us_privacy starts with a "1", then expect 3 Y/N chars afterwards. If it doesn't start with a number, filter it. Anything else, let it through.

This is the current approach, at least for PBS-Go. If the CCPA string is invalid it will be removed form the request by PBS-Core and a warning is emitted back to the publisher. The warning is:

```
"warnings": {
    "general": [{
        "code": 10001,
        "message": "CCPA consent is invalid and will be ignored. (request.regs.ext.us_privacy must contain 4 characters)"
    }]
}
```

**Comment by bretg** [comment]
Both PBS-Go and PBS-Java already validate. The stray strings our exchange is seeing must be coming from elesewhere.
