### ISSUE TITLE
Request to use http.ProxyFromEnvironment as Proxy in custom http.Transport.

### ISSUE THREAD

**Issue by spanwp** [prebid/prebid-server#2245]
In Go, the default http.Transport uses http.ProxyFromEnvironment as value for Proxy field. This allows using a proxy defined in the HTTP_PROXY or HTTPS_PROXY environment in the entire application.

https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/net/http/transport.go;l=43
```
// DefaultTransport is the default implementation of Transport and is
// used by DefaultClient. It establishes network connections as needed
// and caches them for reuse by subsequent calls. It uses HTTP proxies
// as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and
// $no_proxy) environment variables.
var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	DialContext: defaultTransportDialContext(&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}),
	ForceAttemptHTTP2:     true,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
```

Unfortunately, in the prebid-server code base, there are three customs http.Client with custom http.Transport with blank Proxy field. So there is no option to use this app with an external proxy. E.g. from behind NAT. 

Clients without a configured proxy field: 
- generalHttpClient - https://github.com/prebid/prebid-server/blob/master/router/router.go#L131
- cacheHttpClient - https://github.com/prebid/prebid-server/blob/master/router/router.go#L141
- https://github.com/prebid/prebid-server/blob/master/pbs/usersync.go#L34

Is there any reason why the http.Transport uses a blank Proxy field?

If you want I can make PR with change like this:
- router/router.go
![obraz](https://user-images.githubusercontent.com/104571800/168229687-14f602c0-d2db-406b-b6e8-b860bfcb4967.png)
- pbs/usersync.go
![obraz](https://user-images.githubusercontent.com/104571800/168229823-e16062d8-a869-4e75-9b54-d1a78a0bc47e.png)

**Comment by mansinahar** [comment]
AFAIK, I don't think there was any specific reason for not adding this. We just probably didn't come across this use case so far but I can see how this can be useful so you're welcome to open up a PR for the same :)

**Comment by spanwp** [comment]
@mansinahar Thank you for your response. There is PR: https://github.com/prebid/prebid-server/pull/2251

**Comment by SyntaxNode** [comment]
@bretg Does this also apply to PBS-Java? Do you need to do something special to use the host defined proxy?

**Comment by spanwp** [comment]
@SyntaxNode @bretg Ok, my pull request got successfully merged yesterday. Can we close this issue now? Thanks.

**Comment by bretg** [comment]
Discussed in committee. With respect to PBS-Java, the expectation is that anyone who wanted to use a proxy could configure VertX to do so. If someone in the future tries this and it doesn't seem to work, please open an issue over in the PBS-Java repo. https://github.com/prebid/prebid-server-java/issues
