### ISSUE TITLE
Consent string is always empty

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-server#2250]
Hello folks!

I am trying to get the consent string from the Prebid Mobile SDK. As far as I know there are a few ways to set the consent string on the mobile app. I can either do this
```
TargetingParams.setSubjectToGDPR(true)
TargetingParams.setGDPRConsentString("BOMyQRvOMyQRvABABBAAABAAAAAAEA");
```
or this
```
PreferenceManager.getDefaultSharedPreferences(applicationContext).edit().apply {
            putInt("IABTCF_gdprApplies", 0)
            putString("IABTCF_TCString", "COwK6gaOwK6gaFmAAAENAPCAAAAAAAAAAAAAAAAAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw" )
            apply()
        }
```

Did I get the concept right? How do I retrieve these values on the server side? I have tried:
```
func getHuaweiAdsReqConsentInfo(request *huaweiAdsRequest, openRTBRequest *openrtb2.BidRequest) {	
	if openRTBRequest.User != nil && openRTBRequest.User.Ext != nil {
		var extUser openrtb_ext.ExtUser
		if err := json.Unmarshal(openRTBRequest.User.Ext, &extUser); err != nil {
			fmt.Errorf("failed to parse ExtUser in HuaweiAds GDPR check: %v", err)
			return
		}
		request.Consent = extUser.Consent
		log.Println(request.Consent)
	}
}
```
But the consent is always empty. How do I get them?

**Comment by mansinahar** [comment]
@clho40 I don't have much knowledge about the Prebid Mobile SDK so I can't say much about how the user consent is supposed to be set in there. I'd recommend asking that on the Prebid Mobile SDK github. As far as retrieving the consent value on the server side, the above code snippet does look like right to me. If you're seeing this set to always empty then please check the outgoing request from Prebid Mobile SDK to Prebid Server and make sure that the consent string is properly set in there. If it is properly set in there and you still see it being empty on the server side then we can help dig further to figure out what's going on.

**Comment by SyntaxNode** [comment]
You should be aware that PBS will remove an invalid consent string from the request and emit a warning. You can run the a debug auction and check the response to see if this is happening. PBS will only accept TCF2 consent strings for GDPR. You can use https://consentstringdecoder.com/ and http://iabtcf.com/#/decode to verify the consent string if valid.

We take great care to ensure our TCF 2.0 parser works well, but if you can verify the consent string is correct by the sites above and notice that PBS is emitting an invalid consent string warning - please let us know as it may very well likely be a bug in our parser.

**Comment by clho40** [comment]
@mansinahar Thanks for your info! I will get back to you once I have more details

@SyntaxNode Thanks for your input! It's great to know that PBS will remove an invalid consent string. I have checked my consent string using the tools you've shared, and it's a valid consent string. However I am still not able to get it on the server.

Can you please tell me how do I "run a debug action"?

**Comment by SyntaxNode** [comment]
There are no logs printed by PBS for the request. Due to the volume and scale of programmatic bidding, that level of logging would be overwhelming. Please follow the directions in the link, we prefer to use the `ext.prebid.debug` flag. The response you receive will now include a debug object with a lot more information and a view of the requests composed to each adapter.

If you don't find anything obvious, then if you could please share a sample request we can look into it further.

**Comment by clho40** [comment]
@SyntaxNode Here's the openrtb2.BidRequest I receive from the SDK
```
{"id":"c4daec19-2e00-483c-9a75-d48514c4b6f6","imp":[{"id":"c4daec19-2e00-483c-9a75-d48514c4b6f6","banner":{"format":[{"w":320,"h":50}],"api":[3,5,6,7]},"displaymanager":"prebid-mobile","displaymanagerver":"2.0.0","secure":1,"ext":{"bidder":{"publisherid":"xxx","signkey":"yyy","keyid":"1","slotid":"zzz","adtype":"banner"},"prebid":{"storedrequest":{"id":"test_imp_banner"}}}}],"app":{"name":"PrebidMobile","bundle":"com.prebid.mobile.javatest","ver":"1.0","publisher":{"id":"test_req"},"ext":{"prebid":{"source":"prebid-mobile","version":"2.0.0"}}},"device":{"ua":"Mozilla/5.0 (Linux; Android 11; xxx Build/xxx; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36","geo":{"lat":12.23,"lon":1.23,"type":1},"lmt":0,"ip":"11.111.11.11","make":"HUAWEI","model":"xxx-xxx","os":"Android","osv":"11","h":2700,"w":1228,"pxratio":3.375,"language":"en","carrier":"xx - xx","mccmnc":"111-11","connectiontype":3},"user":{"ext":{"data":{"oaid":["8ad653cb-f1d6-4c59-a8f0-fbf36ca16435"]}}},"test":1,"at":1,"source":{"tid":"c4daec19-2e00-483c-9a75-d48514c4b6f6","ext":{"omidpn":"Prebid","omidpv":"2.0.0"}},"regs":{"ext":{"gdpr":0}},"ext":{"prebid":{"cache":{"bids":{"returnCreative":null},"vastxml":null},"channel":{"name":"app","version":""},"storedrequest":{"id":"test_req"},"targeting":{"pricegranularity":{"precision":2,"ranges":[{"min":0,"max":20,"increment":0.1}]},"includewinners":true,"includebidderkeys":true,"includebrandcategory":null,"includeformat":false,"durationrangesec":null,"preferdeals":false}}}}
```

The problem is that the gdpr flag is still 0, and there's no consent string. I suppose this is a problem on the mobile sdk side. I have raised a ticket here https://github.com/prebid/prebid-mobile-android/issues/458

**Comment by SyntaxNode** [comment]
> I suppose this is a problem on the mobile sdk side.

That's what it looks like based on this sample request. I'm going to close this ticket. Please open a new ticket in this project is the Prebid Mobile SDK team finds an issue on our side.
