### ISSUE TITLE
PBS vs EP requests & responses 

### ISSUE THREAD

**Issue by IdoBenDavid** [prebid/prebid-server#2260]
Hi Guys,

I wanted to know if there is any difference in the requests & responses that we are getting between EP & PBS?

For example- Working with the same DSP, once through EP and once through PBS.
the requests & responses should be the same? or are there any other parameters that I should be aware of when using PBS?

thanks in advance!

**Comment by IdoBenDavid** [comment]
Hi @mansinahar , 
EP = Endpoint

Trying to understand if there is any diff in the req & response between both methods (Prebid & Endpoint RTB)

Thanks!

**Comment by SyntaxNode** [comment]
@IdoBenDavid We do not understand which endpoint you are referring to. Is your question regarding a specific bidder?
