### ISSUE TITLE
Listening to the win and imp events from Prebid Mobile SDK

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-server#2270]
Related issue: https://github.com/prebid/prebid-mobile-android/issues/474

According to the Prebid Mobile SDK personnel ([YuriyVelichkoPI](https://github.com/YuriyVelichkoPI),
_Starting with version 2.0.1 Prebid SDK will support sending win and imp events at the respective moments of the ad lifecycle. So you can listen to these events on PBS. I'd suggest asking the PBS team about how to do it._

How do we listen to these events on the server side? Can someone point me in the right direction?

Many thanks!
CL

**Comment by mansinahar** [comment]
@clho40 Prebid Server supports an `event` endpoint that can listen to `win` and `imp` events and can then make this information available via its analytics support. So if you want to be able to listen to this event on the Prebid Server side, it will depend on which Prebid Server are you using, like a self-hosted one or one that's hosted by another company like Magnite or Appnexus, for example, and if that Prebid Server has analytics support enabled.

If you're using a self-hosted Prebid Server, you can enable that yourself. For example, here are the analytics specific config options for PBS-Go: https://github.com/prebid/prebid-server/blob/14631ec6f294edb7f04178195bab3c461096a3c2/config/config.go#L412 

You'd also need to make sure that your publisher account has analytics enabled as well on the Prebid Server that you're using.

**Comment by bretg** [comment]
If events are enabled in PBS, it will emit URLs for seatbid.bid.ext.prebid.events.win and seatbid.bid.ext.prebid.events.imp

I've started the conversation with the Mobile team about whether it makes sense for the rendering library to hit these URLs at the appropriate times.

**Comment by bretg** [comment]
So overall, I think this is more an issue for the SDK -- PBS is already able to emit and listen to the events. 

There just has to be an analytics adapter capable of dealing with the events.

Am going to close this issue on the server side -- the mobile team will open a feature tracking issue if they agree to integrate into the SDK
