### ISSUE TITLE
Add tid to the list of codes that are not bidders

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2307]
Related to https://github.com/prebid/Prebid.js/issues/8543

We need to add 'tid' to the list of reserved words that PBS doesn't attempt to consider a bidder. (the other words are currently: all, context, data, general, prebid, and skadn)

This is fairly urgent because publishers are starting to use imp.ext.tid now, and PBS is rejecting it.

**Comment by bretg** [comment]
bid adapter docs updated

**Comment by SyntaxNode** [comment]
This was implemented in PBS-Go 0.217.0 via a community contribution.

**Comment by Net-burst** [comment]
@bretg There is also a `gpid` field as per this issue: https://github.com/prebid/prebid-server/issues/2088

**Comment by bretg** [comment]
done with PBS-Java 1.94
