### ISSUE TITLE
prebid analytics adapter

### ISSUE THREAD

**Issue by rumanali123** [prebid/prebid-server#2309]
I am successfully created our own analytics adapter.but i want to test locally first than create a pull request to prebid.
can any one please tell me how can i test our own analytics adapter

**Comment by rumanali123** [comment]
no no i actually adding a new analytics adapter in prebid analytics.
so i want to test it first then create pull request to prebid.
so my question is that how can i test our analytics adapter

**Comment by bretg** [comment]
> so my question is that how can i test our analytics adapter

I've answered that to the best of my ability above. You need to provide more a more detailed question if you're looking for something different.

**Comment by rumanali123** [comment]
we want send analytic data to specific url using analytic adapter api
we write the code in module now we need to test the modules.their is any way to test the module or we need to create pull request to prebid and submit the module

**Comment by rumanali123** [comment]
What do you mean by server?? We are not using PBS-Java server. we are using prebidjs client side functionality. 

To be clear, what we have done so far while creating an Analytics Module

1.	Created a branch in prebidjs fork repository. (e.g. feature/exAnalyticsAdapter)
2.	Build and test


Now are actually looking for build and test of our branch somehow before to create pull request for prebidjs team review. We also added unit test a JS file under test/spec/modules in our branch

Please help us regarding it or send some useful links we are using following url https://docs.prebid.org/dev-docs/integrate-with-the-prebid-analytics-api.html

**Comment by bretg** [comment]
For the record, it's kinda confusing when you ask a **Prebid.js** analytics adapter question in the **prebid-server** github repo. Analytics adapters also exist server-side.

But anyhow, testing a JS adapter is easier than testing server. Just make your changes in your local repo, gulp build the modules you need, copy the resulting prebid.js to your local web server directory, and test away.
