### ISSUE TITLE
Problems with ext.prebid.bidderconfig processing on https://ib.adnxs.com/openrtb2/prebid

### ISSUE THREAD

**Issue by TheMediaGrid** [prebid/prebid-server#2311]
Hello! There is problem with processing ext.prebid.bidderconfig data on https://ib.adnxs.com/openrtb2/prebid endpoint. When we send the same request on https://prebid.adnxs.com/pbs/v1/openrtb2/auction , we can see bidderconfig data in user.data array, which was sent to our adapter endpoint. But when we send the same request on https://ib.adnxs.com/openrtb2/prebid endpoint , we dont receive bidderconfig data on our adapter endpoint.

**Comment by hhhjort** [comment]
ib.adnxs.com/openrtb2/prebid is the Xandr premium PBS frontend, which does some pre-processing to enable the premium features before passing it on to the standard PBS. One of these preprocessing tasks is to pull stored requests from the Xandr client UI, which should host all the prebid configs. Being passed configs in on the request was not a major use case, and request level bidderconfigs came in after the front end was written, so I can see how it could be missed. I will look into what it will take to get it supported.

**Comment by PDigginsXandr** [comment]
Hi @TheMediaGrid Could you confirm which mutual customers are leveraging this and what they're trying to accomplish through the bidderconfig settings?

**Comment by TheMediaGrid** [comment]
Hi @PDXandr and @hhhjort 
It's for Mail Metro, they are passing Permutive segments from the Permutive RTD adapter and since Permutive RTD adapter uses biddersettings- it doesn't work for them. As a result MediGrid isn't receiving the Permutive segments and we can't enable spend against that data. So it's pretty critical. Just an FYI that for regular prebid by xandr it does work the way it should and we have publishers using this functionality.

**Comment by TheMediaGrid** [comment]
Hi @hhhjort @PDXandr do you have a timeline for this fix?

**Comment by TheMediaGrid** [comment]
Ok, sure, please use abalashoyu@iponweb, and I will cc the other folks as needed

**Comment by SyntaxNode** [comment]
This host specific issue has been moved to email. Closing since this doesn't relate to the open source project.
