### ISSUE TITLE
Implement Programmatic Guaranteed (PG)

### ISSUE THREAD

**Issue by AlexBVolcy** [prebid/prebid-server#2312]
After analyzing this previous issue, https://github.com/prebid/prebid-server/issues/1015, we decided to close that issue as everything in the issue was implemented besides Programmatic Guaranteed. And given that PG is a big feature to implement, it made more sense to create an issue for it alone. So this isn't a new request, but there never was an issue for PG by itself, so we made one.

We couldn't find a spec for PG after looking through issues from PBS-Go and even PBS-Java, so the only info we can provide is the white paper for PG, which details everything related to this new feature.

https://docs.prebid.org/prebid-server/features/pg/pbs-pg-idx.html

**Comment by SyntaxNode** [comment]
PBS-Java is removing the Programmatic Guaranteed feature in the upcoming 3.0 major release due to lack of traction. As a result, closing the issue to add this to PBS-Go.
