### ISSUE TITLE
eidpermissions Exposed to Bidders

### ISSUE THREAD

**Issue by PDXandr** [prebid/prebid-server#2321]
Please confirm if eidpermissions are intended to be passed along to bidders.  I would think publishers would not want that information exposed as it informs bidders which competitors the publisher is using, and which have access to first-party data.

Example of eidpermissions here but this does not confirm the behavior: https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#post-openrtb2auction

In testing at Xandr, request to bidders included:

`{\"eidpermissions\":[{\"source\":\"intTestSource2\",\"bidders\":[\"pubmatic\",\"appnexus\"]}]}`

**Comment by bretg** [comment]
Good call @PDXandr . Here's the [table of all the various extensions and whether bidders should see them](https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#prebid-server-ortb2-extension-summary) -- both teams should review all of them. Have opened an internal ticket for the PBS-Java team.

**Comment by PDXandr** [comment]
Apologies for missing that clarification at the bottom of the documentation @bretg .  @SyntaxNode let me know if you need anything else for the Go side.

**Comment by SyntaxNode** [comment]
Looks like the entire `eidpermissions` should not be sent to the bidder.

We'll work on this for PBS-Go. I agree with removing everything in ext.prebid and imp.ext.prebid unless specifically allowed. This looks to currently be:
- `imp[].ext.prebid.bidder` (only their value)
- `imp[].ext.prebid.is_rewarded_inventory`
- `ext.prebid.integration`
- `ext.prebid.channel`
- `ext.prebid.debug`
- `ext.prebid.currency.rates`
- `ext.prebid.currency.usepbsrates`
- `ext.prebid.interstitial`
- `ext.prebid.multibid` (only their value)
- ext.prebid.auctiontimestamp
- ext.prebid.options. echovideoattrs

**Comment by SyntaxNode** [comment]
Fixed in PBS-Go 0.222.0.

**Comment by bretg** [comment]
Moving to https://github.com/prebid/prebid-server/issues/2383. That one is a broader general review of ext.prebid and what's sent to bidders including EIDs.
