### ISSUE TITLE
Empty request.ext.prebid Object

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#2344]
PBS-Go will generate an empty `request.ext.prebid` json object in outgoing bid requests if none was specified or none are passed through to the bidder. This is not a new behavior.

Is there a purpose to it? Is it an intentional downstream signal? . or has it become an unintentional signal?

PBS-Java does not have this behavior, leading me to believe it's safe to remove this object from the request if its' empty. It was called out during the Prebid Server PMC that both PBS-Go and PBS-Java send out a version header to all bidders as a formal signal of originating from the Prebid ecosystem.

**Comment by bretg** [comment]
Discussed in committee. We think this issue may be moot when https://github.com/prebid/prebid-server/issues/1739 is implemented, since ext.prebid will always exist.

**Comment by bretg** [comment]
Going to close this issue as resolved with #1739... there will always be something in ext.prebid.
