### ISSUE TITLE
auction issues

### ISSUE THREAD

**Issue by amitAdnimation** [prebid/prebid-server#2363]
HI
I deployed server to azure ACI , look like its all set up and responding, but when auction called the response is without "seatbid" attr
 and "nbr":2
i dont understand whats the issue , addinng screenshots
request:
![image](https://user-images.githubusercontent.com/104294963/187373445-aa0d253f-2eae-49bd-bc43-90a3c52b4261.png)

response : 
![image](https://user-images.githubusercontent.com/104294963/187373565-4a1d1074-a13e-44f3-8981-0ba9f3ceb205.png)

![image](https://user-images.githubusercontent.com/104294963/187373691-28a5116c-2c57-4f7f-955d-a1ca205b3917.png)

live site response :
{id: "946dad66-4877-48c9-bcaf-0356e9165c1e", source: {tid: "8dde7168-69b9-48d9-91e1-79760ba96fe3",…},…}
device: {w: 1125, h: 929}
h: 929
w: 1125
ext: {,…}
prebid: {auctiontimestamp: 1661842509424, targeting: {includewinners: true, includebidderkeys: false},…}
auctiontimestamp: 1661842509424
channel: {name: "pbjs", version: "v7.9.0"}
name: "pbjs"
version: "v7.9.0"
debug: true
schains: [{bidders: ["appnexus", "criteo"],…}]
0: {bidders: ["appnexus", "criteo"],…}
bidders: ["appnexus", "criteo"]
schain: {ver: "1.0", complete: 1, nodes: [{asi: "******", sid: "********", hp: 1}]}
targeting: {includewinners: true, includebidderkeys: false}
includebidderkeys: false
includewinners: true
id: "946dad66-4877-48c9-bcaf-0356e9165c1e"
imp: [{instl: 1, ext: {tid: "22396e37-c9a6-4dc0-bc91-ec8f0602c988",…},…}]
0: {instl: 1, ext: {tid: "22396e37-c9a6-4dc0-bc91-ec8f0602c988",…},…}
banner: {format: [{w: 336, h: 280}, {w: 300, h: 250}]}
ext: {tid: "22396e37-c9a6-4dc0-bc91-ec8f0602c988",…}
data: {adserver: {name: "gam", adslot: "/339474670,22723530920/*****/****_Interstitial"},…}
gpid: "/339474670,22723530920/*****/****_Interstitial"
prebid: {bidder: {appnexus: {use_pmt_rule: false, placement_id: 27179123},…}}
bidder: {appnexus: {use_pmt_rule: false, placement_id: 27179123},…}
appnexus: {use_pmt_rule: false, placement_id: 27179123}
criteo: {networkId: 7314, publisherSubId: "*****.com"}
tid: "22396e37-c9a6-4dc0-bc91-ec8f0602c988"
id: "/339474670,22723530920/*****/ROR_Interstitial"
instl: 1
secure: 0
site: {publisher: {id: "1", domain: "*****.com"}, page: "https://*****.com/",…}
source: {tid: "8dde7168-69b9-48d9-91e1-79760ba96fe3",…}
test: 0
tmax: 300
user: {ext: {eids: [{source: "criteo.com", uids: [{,…}]}]}}

**Comment by SyntaxNode** [comment]
NBR is set to 2 (invalid request) only when there are no bidders. Please ensure the bidders you've selected are enabled in your Prebid Server instance. If that looks good, perhaps your default privacy settings are causing an issue. Do you have `gdpr.default_value` set to `1`?

**Comment by amitAdnimation** [comment]
gdpr.default_value
that solved it , thx!!!
