### ISSUE TITLE
Prebid server Java 

### ISSUE THREAD

**Issue by rumanali123** [prebid/prebid-server#2369]
we are working on PBS java.We host our server on aws and its working fine.We check the status of server.
when we implement s2s in prebid then bid send to auction in server but we recieve empty bid from server.
http://serverendpoint/openrtb2/auction
when we check post request to this endpoint we receive bid data but seatbid is empty
Right now we haven’t add any database configuration

**Comment by bretg** [comment]
@rumanali123 - there's no way we can debug a deployment with this little information.

Here's what I recommend:
1) pass in test:1 on the request
2) look at the outbound HTTP requests to the bid adapters that are placed on ext.debug.httpcalls
3) if there aren't any outbound requests, look for error messages further down.

If you don't have an account DB setup, make sure you haven't configured settings.enforce-valid-account to true. 

If you want more detailed help, you have to give us a full debug request/response trace and/or an endpoint with a test request.

**Comment by rumanali123** [comment]
can you please tell me where we can find “full debug request/response trace” on server we are using NGIXN server on port 5000

**Comment by bretg** [comment]
It's in the JSON response from PBS. ext.debug.

It's difficult to help you debug a problem so vague. You need to provide us your full test request and test response. We might then need the config files and/or an endpoint that we can hit from the outside.

**Comment by rumanali123** [comment]
This is console log for our prebid page
<img width="1440" alt="Screenshot 2022-09-09 at 5 49 59 PM" src="https://user-images.githubusercontent.com/108808183/189359675-59606c7f-ebfa-495e-8729-4233d35f7d2b.png">

Request send to the auction:
	{
    "prebid": {
        "auctiontimestamp": 1662727192027,
        "targeting": {
            "includewinners": true,
            "includebidderkeys": false
        },
        "channel": {
            "name": "pbjs",
            "version": "v6.29.0"
        },
        "debug": true,
        "cache": {
            "vastxml": {
                "returnCreative": false
            }
        }
    }
}

Receive request from auction:
	{"id":"4644521e-9bab-4e76-8984-fbf31f843d80","seatbid":[],"cur":"USD","nbr":0,"ext":{"debug":{"resolvedrequest":{"id":"4644521e-9bab-4e76-8984-fbf31f843d80","imp":[{"id":"300x250","banner":{"format":[{"w":300,"h":250}]},"ext":{"data":{"pbadslot":"300x250"},"prebid":{"bidder":{"improvedigital":{"placementId":22747501}}}}}],"site":{"domain":"localhost","page":"http://localhost/prebid_server_test.html","ref":"http://localhost/prebid_server_test.html","publisher":{"id":"22696859215"},"ext":{"amp":0}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","ip":"182.185.173.106","h":796,"w":559},"test":0,"at":1,"tmax":3000,"cur":["USD"],"source":{"tid":"d216585d-36a4-491b-a4a4-333898f816b7"},"ext":{"prebid":{"debug":1,"targeting":{"pricegranularity":{"precision":2,"ranges":[{"max":20,"increment":0.1}]},"includewinners":true,"includebidderkeys":false},"cache":{"vastxml":{"returnCreative":false}},"auctiontimestamp":1662727192027,"channel":{"name":"pbjs","version":"v6.29.0"},"pbs":{"endpoint":"/openrtb2/auction"},"server":{"externalurl":"http://localhost:8080","datacenter":"local"}}}}},"responsetimemillis":{},"tmaxrequest":3000,"prebid":{"auctiontimestamp":1662727192027}}}


Our server Url:
	http://adzspecprebidserver-env.eba-6v55fpfe.eu-north-1.elasticbeanstalk.com


This is our clied side code:
<html>

<head>
    <link rel="icon" type="image/png" href="/favicon.png">
    <script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
    <script async src="prebid_both.js"></script>

    <script>
        var div_1_sizes = [
            [300, 250]
        ];
        var PREBID_TIMEOUT = 1000;
        var FAILSAFE_TIMEOUT = 1000;
        var adUnits = [{
            code: '300x250',
            mediaTypes: { banner: { sizes: [[300, 250]] } },
            bids: [
                {
                    bidder: 'improvedigital',
                    params: {
                        placementId: id
                    }
                }]
        }
        ];
        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];
        // ======== DO NOT EDIT BELOW THIS LINE =========== //
        var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];
        googletag.cmd.push(function () {
            googletag.pubads().disableInitialLoad();
        });

        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];


        pbjs.que.push(function () {
            pbjs.setConfig({
                "ortb2": {
                    "test": 1
                },
                debug: true,
                improvedigital: { usePrebidSizes: true },
                s2sConfig: {
                    adapter: 'prebidServer',
                    testing: true,
                    endpoint: "http://adzspecprebidserver-env.eba-6v55fpfe.eu-north-1.elasticbeanstalk.com/openrtb2/auction",
                   
                    enabled: true,
                    accountId: 'accountId',
                    bidders: ['improvedigital'],

                    timeout: 3000,
                    extPrebid: {
                        cache: {
                            vastxml: { returnCreative: false }
                        },
                    }

                }
            });
            pbjs.addAdUnits(adUnits);
            pbjs.requestBids({
                bidsBackHandler: initAdserver,
                timeout: PREBID_TIMEOUT
            });

        });

        function initAdserver() {
            console.log("init run hwa hy");
            if (pbjs.initAdserverSet) return;
            pbjs.initAdserverSet = true;
            googletag.cmd.push(function () {
                pbjs.que.push(function () {
                    pbjs.setTargetingForGPTAsync();
                    googletag.pubads().refresh();
                });
            });
        }
        // in case PBJS doesn't load
        setTimeout(function () {
            console.log("prebid didnot load");
            initAdserver();
        }, FAILSAFE_TIMEOUT);

        googletag.cmd.push(function () {
            googletag.defineSlot('/unitCode/Adzspectestad1', div_1_sizes, 'div1').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
        googletag.cmd.push(function () {
            googletag.display('div1');
        });
    </script>
</head>

<body>
    <h2>Basic Prebid.js Example</h2>
    <h5>Div-1</h5>
    <div id='div1'>
        <script type='text/javascript'>


        </script>
    </div>
    <br>

</body>

</html>

**Comment by bretg** [comment]
Much better. Thanks.

The actual request you're sending is shown in the response as the "resolved request". it's

```
{
    "id": "4644521e-9bab-4e76-8984-fbf31f843d80",
    "imp": [
        {
            "id": "300x250",
            "banner": {
                "format": [
                    {
                        "w": 300,
                        "h": 250
                    }
                ]
            },
            "ext": {
                "data": {
                    "pbadslot": "300x250"
                },
                "prebid": {
                    "bidder": {
                        "improvedigital": {
                            "placementId": 22747501
                        }
                    }
                }
            }
        }
    ],
    "site": {
        "domain": "localhost",
        "page": "http://localhost/prebid_server_test.html",
        "ref": "http://localhost/prebid_server_test.html",
        "publisher": {
            "id": "22696859215"
        },
        "ext": {
            "amp": 0
        }
    },
    "device": {
        "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
        "ip": "182.185.173.106",
        "h": 796,
        "w": 559
    },
    "test": 0,
    "at": 1,
    "tmax": 3000,
    "cur": [
        "USD"
    ],
    "source": {
        "tid": "d216585d-36a4-491b-a4a4-333898f816b7"
    },
    "ext": {
        "prebid": {
            "debug": 1,
            "targeting": {
                "pricegranularity": {
                    "precision": 2,
                    "ranges": [
                        {
                            "max": 20,
                            "increment": 0.1
                        }
                    ]
                },
                "includewinners": true,
                "includebidderkeys": false
            },
            "cache": {
                "vastxml": {
                    "returnCreative": false
                }
            },
            "auctiontimestamp": 1662727192027,
            "channel": {
                "name": "pbjs",
                "version": "v6.29.0"
            },
            "pbs": {
                "endpoint": "/openrtb2/auction"
            },
            "server": {
                "externalurl": "http://localhost:8080",
                "datacenter": "local"
            }
        }
    }
}
```
Note that you're invoking only the `improvedigital` bidder. However, your server only has the rubicon bidder enabled. See this admin URL:

http://adzspecprebidserver-env.eba-6v55fpfe.eu-north-1.elasticbeanstalk.com/info/bidders?enabledOnly=true

So the first step is to enabled the improvedigital bidder... in https://github.com/prebid/prebid-server-java/blob/master/src/main/resources/bidder-config/improvedigital.yaml, you need to set `adapters.improvedigital.enabled: true`

**Comment by rumanali123** [comment]
We enabled the improve digital bid adapter. You can see from this url
http://adzspecprebidserver-env.eba-6v55fpfe.eu-north-1.elasticbeanstalk.com/info/bidders?enabledOnly=true
but our issue didn't resolve.

This is our request:
{
    "prebid": {
        "auctiontimestamp": 1662902594924,
        "targeting": {
            "includewinners": true,
            "includebidderkeys": false
        },
        "channel": {
            "name": "pbjs",
            "version": "v7.15.0"
        },
        "debug": true,
        "cache": {
            "vastxml": {
                "returnCreative": false
            }
        }
    }
}
This is our response:
{"id":"39fbf6b9-798a-410a-b262-1ce95b4510c9","seatbid":[],"cur":"USD","nbr":0,"ext":{"debug":{"resolvedrequest":{"id":"39fbf6b9-798a-410a-b262-1ce95b4510c9","imp":[{"id":"300x250","banner":{"format":[{"w":300,"h":250}]},"ext":{"tid":"7b1888d8-6d69-4c30-b57e-0a6e0527aa6e","data":{"pbadslot":"300x250"},"prebid":{"bidder":{"improvedigital":{"placementId":22747501}}}}}],"site":{"domain":"localhost","page":"http://localhost/prebid_server_test.html","publisher":{"id":"22696859215","domain":"localhost"},"ext":{"amp":0}},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","ip":"162.255.45.45","h":738,"w":429},"test":1,"at":1,"tmax":3000,"cur":["USD"],"source":{"tid":"77f254c1-b6c1-4f21-98ce-d95906331d6e"},"ext":{"prebid":{"debug":1,"targeting":{"pricegranularity":{"precision":2,"ranges":[{"max":20,"increment":0.1}]},"includewinners":true,"includebidderkeys":false},"cache":{"vastxml":{"returnCreative":false}},"auctiontimestamp":1662902594924,"channel":{"name":"pbjs","version":"v7.15.0"},"pbs":{"endpoint":"/openrtb2/auction"},"server":{"externalurl":"http://localhost:8080","datacenter":"local"}}}}},"responsetimemillis":{},"tmaxrequest":3000,"prebid":{"auctiontimestamp":1662902594924}}}
This is console image
<img width="1440" alt="Screenshot 2022-09-11 at 6 37 12 PM" src="https://user-images.githubusercontent.com/108808183/189530538-770014d0-5859-43ff-824b-432ccbbab4a5.png">
