### ISSUE TITLE
Click event reporting back to adapters

### ISSUE THREAD

**Issue by GenarC** [prebid/prebid-server#2373]
When a user clicks an ad from the prebid mobile application, it goes to the click url, but to register the click, we need to call click event url. Is this implemented in the prebid-mobile-sdk? If yes, where and how should I check it? My network console report does not get click reports

**Comment by SyntaxNode** [comment]
This is the Prebid Server project. There are different teams working on the Prebid Mobile SDKs.

 For questions regarding the Mobile SDK, it's better to open an issue in https://github.com/prebid/prebid-mobile-android or https://github.com/prebid/prebid-mobile-ios.

**Comment by bretg** [comment]
Hi @GenarC - Prebid doesn't currently support the recording of clicks in any way in any platform.

Click tracking would be in the creative as entered in the DSP and/or ad server.
