### ISSUE TITLE
Invalid POST data received from prebid server

### ISSUE THREAD

**Issue by rcheptanariu** [prebid/prebid-server#2379]
On SOME requests, even though the request coming from prebid server has
**EncodingType: 'application/json;charset=utf-8'**

when parsing the POST data and decoding with utf-8, it looks like jibberish and cannot be parsed into parameters:
**?      ?|?_O?8???k?@h??W??m
(?U???6?j;??w_?,h%V??????????K?Yi?M]?1:?hY?T???!71?#Uuj#L?m??&F
?~?Eh??*F??1?h??Fh?D?x?>??Z????1:?h?9? Fy???s|??	/?Q??i/?{?&?g?^???(\?s?Q\9?1:?Nh?u?:??[??px8.?-.2=d?m???X?
?1e
??Y?1??K??f?3?K????y?)??X?l
?o6???8??>h,?B?N?kQ?*?S09????;???
?0??e?
#h~??@?|?W?m??	%s???FO????e?? 7`?8??`?@??f??(??'W#>??X_.G??????;|???=yK?[?><uLn???\???"^??????.:??????lv??>x???????/??NG]?=??u?$7Y?N*??$??F???f?O ?~?S?VQ(W?+?@
?9?_???<-C??B?P????-H
 "??	?	? ? ?i$!?? *?`?N
4???"?z?X??,C????	??<????V?b?H????7??E-??????M?	O  ????A??**  

The request should look like this (it works on most requests we receive): 
**'{"BidParamsJson":"{\"PlacementIds\":[\"invibes_slateamp\"],\"BidVersion\":\"4\",\"Properties\":{\"invibes_slateamp\":{\"Formats\":[{\"w\":300,\"h\":250},{\"w\":336,\"h\":280},{\"w\":250,\"h\":250},{\"w\":320,\"h\":100},{\"w\":320,\"h\":50}],\"ImpId\":\"some-impression-id\"}}}","Location":"https://publisher.com/article-page","Lid":"","IsTestBid":false,"Kw":"","IsAmp":true,"Width":"","Height":"","GdprConsent":"CPfPdAAPfPdAABcAIBFRCgCgAP_AAH_AAATIIDwOAABAAKAAeABWADIANAAcABAACQAFUALAAtABjADQANQAeAA-gCIAJMATABNACeAFuALwAvwBhAGIANkAbgBvgDkAOcAdwB4AD5AIAAhABMQCkAKUAXAA4gB6AD9AIGAQgAigBHQCdAE8AKuAVkAuoBgQDRAGvANoAfUBHoCXgE_gKaAXmAxcBjIDkwHUAQHBAeBMAA8ACoAGQAOAAgABIADGAGgAagA8AB9AEQARQAmABPADEAG8AOYAfgBCACYAFKAP0AgYBCACKAEWAI6AVcAuoBgQDRAGvANoAeQBHoCmgF5gMEgcmBygAAA","Gdpr":true,"Bvid":"","InvibBVLog":false,"VideoAdDebug":false}'**

Tried to decode the requests with multiple encoding types but none produce any results

**Comment by bretg** [comment]
That looks like gzipped data @rcheptanariu . Invibes is one of the bid adapters that self-declared support for receiving gzipped data.

https://github.com/prebid/prebid-server/blob/be5deb6403bc10f2ee270c27df38c1444ad6eb71/static/bidder-info/invibes.yaml

```
endpointCompression: "GZIP"
```

Perhaps there's an issue where PBS-Go isn't setting the `Content-Encoding: gzip` header?

**Comment by rcheptanariu** [comment]
You are correct, we were having a bug decoding the gzip content.

Many thanks!
