### ISSUE TITLE
The consent_string, gdpr_applies, consent_type and addtl_consent query parameters are being sent through /AMP endpoint but not forwarded to the bidders, the request.user object isn't present in the request

### ISSUE THREAD

**Issue by snigel-nelson** [prebid/prebid-server#2387]
## Description of the Issue

The requests sent from AMP pages, more specifically from <amp-ad> elements to my prebid-server through the AMP endpoint contains the query parameters **consent_string**, **consent_type**, **gdpr_applies** and **addtl_consent** that I need to add to the request forwarded to the SSPs.
The problem is that the request sent to the bidders doesn't contain the consent string, the `request.user.ext.consent` parameter is not present in the request. Since the consent string is mandatory in some geo locations and some bidders also demand this can cause some bidders to make fewer bids or stop at all, or another kind of legal problem.

 ### Context

I'm using a custom version of prebid-server (PBS) to allow publishers that have AMP pages with <amp-ad> elements to send requests through **RTC callouts** to my PBS and monetize their pages.
I'm using the following configuration in my <amp-ad> elements to send requests to my PBS through its AMP endpoint:

`rtc-config="{"urls": ["https://prebid-server/openrtb2/amp?tag_id=stored-request&curl=CANONICAL_URL&consent_state=CONSENT_STATE&consent_string=CONSENT_STRING&gdpr_applies=CONSENT_METADATA(gdprApplies)&addtl_consent=CONSENT_METADATA(additionalConsent)&consent_type=CONSENT_METADATA(consentStringType)"]}"` 

I was using PBS version **v0.214.0** and by using the flag `debug=1` I could confirm the consent string was being added to the resolved request and sent to the bidders, like this:

**v0.214.0**
`"resolvedrequest": {
            "id": "2916ae43-6cd9-47fb-a87a-b78ca532cd56",
            "imp": [(...)],
            "site": {
                "domain": "www.domain.com",
                "page": "https://www.domain.com/",
                "publisher": {
                    "id": "1234"
                },
                "ext": {
                    "amp": 1
                }
            },
            "device": {
                "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                "ipv6": "ipv6"
            },
            "user": {
                "ext": {
                    "consent": "valid_TCF_2.0_Consent_String"
                }
            },
            "test": 1,
            "at": 1,
            "tmax": 400,
            "cur": ["EUR"],
            "source": {
                "tid": "37f101b5-32f4-4769-baa7-37882bb0d865",
                "ext": {
                    "schain": {
                        "ver": "1.0",
                        "complete": 1,
                        "nodes": [{
                                "asi": "asi",
                                "sid": "1234",
                                "domain": "domain.com",
                                "hp": 1
                            }
                        ]
                    }
                }
            },
            "ext": {
                "prebid": {
                    "cache": {
                        "bids": {
                            "returnCreative": null
                        },
                        "vastxml": null
                    },
                    "channel": {
                        "name": "amp",
                        "version": ""
                    },
                    "targeting": {
                        "pricegranularity": {
                            "precision": 2,
                            "ranges": [{
                                    "min": 0,
                                    "max": 20,
                                    "increment": 0.1
                                }
                            ]
                        },
                        "includewinners": true,
                        "includebidderkeys": true,
                        "includebrandcategory": null,
                        "includeformat": false,
                        "durationrangesec": null,
                        "preferdeals": false
                    }
                }
            }
        }
 }
`

And the request sent from my PBS to any bidder would be like this:

**v0.214.0**
`"requestbody": {
    "id": "2916ae43-6cd9-47fb-a87a-b78ca532cd56",
    "imp": [(...)],
    "site": {
        "domain": "www.domain.com",
        "page": "https://www.domain.com/",
        "publisher": {
            "id": "1234"
        },
        "ext": {
            "amp": 1
        }
    },
    "device": {
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
        "ipv6": "ipv6"
    },
    "user": {
        "buyeruid": "caf17bfe5f928f70f8a512a5",
        "ext": {
            "consent": "valid_TCF_2.0_Consent_String"
        }
    },
    "test": 1,
    "at": 1,
    "tmax": 400,
    "cur": ["EUR"],
    "source": {
        "tid": "37f101b5-32f4-4769-baa7-37882bb0d865",
        "ext": {
            "schain": {
                "ver": "1.0",
                "complete": 1,
                "nodes": [{
                        "asi": "asi",
                        "sid": "1234",
                        "domain": "domain.com",
                        "hp": 1
                    }
                ]
            }
        }
    },
    "ext": {
        "prebid": {
            "cache": {
                "bids": {
                    "returnCreative": null
                },
                "vastxml": null
            },
            "channel": {
                "name": "amp",
                "version": ""
            },
            "targeting": {
                "pricegranularity": {
                    "precision": 2,
                    "ranges": [{
                            "min": 0,
                            "max": 20,
                            "increment": 0.1
                        }
                    ]
                },
                "includewinners": true,
                "includebidderkeys": true,
                "includebrandcategory": null,
                "includeformat": false,
                "durationrangesec": null,
                "preferdeals": false
            }
        }
    }
}
`
So the request sent to the bidder has a valid JSON structure and the bidders respondes with valid bids.

This worked fine when I was using PBS version **v0.214.0**. Since I updated to use the version **v0.227.0** the consent string isn't added anymore. I'll share with you the `resolvedrequest`  and the `requestbody` objects built and sent by the updated version of PBS.

**v0.227.0**
`"resolvedrequest": {
	"id": "c3b7eb87-e8f4-4b9f-90f9-a1be91afb0a0",
	"imp": [(...)],
	"site": {
		"domain": "www.domain.com",
		"page": "https://www.domain.com/",
		"publisher": {
			"id": "1234"
		},
		"ext": {
			"amp": 1
		}
	},
	"device": {
		"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
		"ip": "ipv4"
	},
	"test": 1,
	"at": 1,
	"tmax": 400,
	"cur": ["EUR"],
	"source": {
		"tid": "d1a40ea8-33b1-492a-8b76-54f74bb470ac",
		"ext": {
			"schain": {
				"ver": "1.0",
				"complete": 1,
				"nodes": [{
						"asi": "asi",
						"sid": "1234",
						"domain": "domain.com",
						"hp": 1
					}
				]
			}
		}
	},
	"ext": {
		"prebid": {
			"cache": {
				"bids": {
					"returnCreative": null
				},
				"vastxml": null
			},
			"channel": {
				"name": "amp",
				"version": ""
			},
			"targeting": {
				"pricegranularity": {
					"precision": 2,
					"ranges": [{
							"min": 0,
							"max": 20,
							"increment": 0.1
						}
					]
				},
				"includewinners": true,
				"includebidderkeys": true,
				"includebrandcategory": null,
				"includeformat": false,
				"durationrangesec": null,
				"preferdeals": false
			}
		}
	}
}
`

And the request sent from my PBS to any bidder is:

**v0.227.0**
`"requestbody": {
    "id": "c3b7eb87-e8f4-4b9f-90f9-a1be91afb0a0",
    "imp": [(...)],
    "site": {
        "domain": "www.domain.com",
        "page": "https://www.domain.com/",
        "publisher": {
            "id": "1234"
        },
        "ext": {
            "amp": 1
        }
    },
    "device": {
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
        "ip": "ipv4"
    },
    "test": 1,
    "at": 1,
    "tmax": 400,
    "cur": ["EUR"],
    "source": {
        "tid": "d1a40ea8-33b1-492a-8b76-54f74bb470ac",
        "ext": {
            "schain": {
                "ver": "1.0",
                "complete": 1,
                "nodes": [{
                        "asi": "asi",
                        "sid": "1234",
                        "domain": "domain.com",
                        "hp": 1
                    }
                ]
            }
        }
    },
    "ext": {
        "prebid": {
            "channel": {
                "name": "amp",
                "version": ""
            }
        }
    }
}
`

The necessary query parameters are being added to the request and correctly sent to my PBS. 

`
https://adserv.com/pbs/v1/openrtb2/amp?
tag_id=stored-request&
curl=https%3A%2F%2Fwww.domain.com%2F&
consent_state=1&
consent_string=valid_TCF_2.0_Consent_String
gdpr_applies=true&
addtl_consent=1~39.43.46.55.61.70.83.89.93.108.117.122.124.131.135.136.143.144.147.149.159.162.167.171.192.196.202.211.218.228.230.239.241.259.266.272.286.291.311.317.322.323.326.327.338.367.371.385.389.394.397.407.413.415.424.430.436.440.445.449.453.482.486.491.494.495.501.503.505.522.523.540.550.559.560.568.574.576.584.587.591.733.737.745.780.787.802.803.817.820.821.829.839.864.867.874.899.904.922.931.938.979.981.985.1003.1024.1027.1031.1033.1034.1040.1046.1051.1053.1067.1085.1092.1095.1097.1099.1107.1127.1135.1143.1149.1152.1162.1166.1186.1188.1201.1205.1211.1215.1226.1227.1230.1252.1268.1270.1276.1284.1286.1290.1301.1307.1312.1345.1356.1364.1365.1375.1403.1415.1416.1419.1440.1442.1449.1455.1456.1465.1495.1512.1516.1525.1540.1548.1555.1558.1564.1570.1577.1579.1583.1584.1591.1603.1616.1638.1651.1653.1665.1667.1677.1678.1682.1697.1699.1703.1712.1716.1721.1725.1732.1745.1750.1765.1769.1782.1786.1800.1808.1810.1825.1827.1832.1837.1838.1840.1842.1843.1845.1859.1866.1870.1878.1880.1889.1899.1917.1929.1942.1944.1962.1963.1964.1967.1968.1969.1978.2003.2007.2008.2027.2035.2039.2044.2046.2047.2052.2056.2064.2068.2070.2072.2074.2088.2090.2103.2107.2109.2115.2124.2130.2133.2137.2140.2145.2147.2150.2156.2166.2177.2183.2186.2202.2205.2216.2219.2220.2222.2225.2234.2253.2264.2279.2282.2292.2299.2305.2309.2312.2316.2322.2325.2328.2331.2334.2335.2336.2337.2343.2354.2357.2358.2359.2366.2370.2376.2377.2387.2392.2394.2400.2403.2405.2407.2411.2414.2416.2418.2425.2427.2440.2447.2459.2461.2462.2465.2468.2472.2477.2481.2484.2486.2488.2492.2493.2496.2497.2498.2499.2501.2510.2511.2517.2526.2527.2532.2534.2535.2542.2544.2552.2563.2564.2567.2568.2569.2571.2572.2575.2577.2583.2584.2595.2596.2601.2604.2605.2608.2609.2610.2612.2614.2621.2628.2629.2633.2634.2636.2642.2643.2645.2646.2647.2650.2651.2652.2656.2657.2658.2660.2661.2669.2670.2677.2681.2684.2686.2687.2690.2695.2698.2707.2713.2714.2729.2739.2767.2768.2770.2772.2784.2787.2791.2792.2798.2801.2805.2812.2813.2816.2817.2818.2821.2822.2827.2830.2831.2834.2836.2838.2839.2840.2844.2846.2847.2849.2850.2851.2852.2854.2856.2860.2862.2863.2865.2867.2869.2873.2874.2875.2876.2878.2880.2881.2882.2883.2884.2886.2887.2888.2889.2891.2893.2894.2895.2897.2898.2900.2901.2908.2909.2911.2912.2913.2914.2916.2917.2918.2919.2920.2922.2923.2924.2927.2929.2930.2931.2939.2940.2941.2942.2947.2949.2950.2956.2961.2962.2963.2964.2965.2966.2968.2970.2973.2974.2975.2979.2980.2981.2983.2985.2986.2987.2991.2993.2994.2995.2997.2999.3000.3002.3003.3005.3008.3009.3010.3012.3016.3017.3018.3019.3024.3025.3028.3034.3037.3038.3043.3045.3048.3052.3053.3055.3058.3059.3063.3065.3066.3068.3070.3072.3073.3074.3075.3076.3077.3078.3089.3090.3093.3094.3095.3097.3099.3100.3104.3106.3109.3112.3116.3117.3118.3119.3120.3124.3126.3127.3128.3130.3135.3136.3145.3149.3150.3151.3154.3155.3162.3163.3167.3172.3173.3180.3182.3183.3184.3185.3187.3188.3189.3190.3194.3196.3197.3209.3210.3211.3214.3215.3217.3219.3222.3223.3225.3226.3227.3228.3230.3231.3232.3234.3235.3236.3237.3238.3240.3241.3244.3245.3250.3251.3253.3257.3260.3268.3270.3272.3281.3288.3290.3292.3293.3295.3296.3300&
consent_type=2&
debug=1&
__amp_source_origin=http%3A%2F%2Fwww.domain.com
`

By looking at the requests we can see that the consent string is missing and the object `regs.ext.gdpr` isn't present.

## Tests

I've made some tests with both versions (0.214.0 and 0.227.0), using always the _debug_ flag and comparing the parameters`response.debug.httpcall.{bidder}.[i].requestbody` and `response.debug.resolvedrequest` and the object resolvedrequest.user doesn't exist. But the query parameters,  are being passed to our PBS, parsed but not forwarded.

## Possible causes

There were some changes merged in [v0.226.0](https://github.com/prebid/prebid-server/releases/tag/v0.226.0) that could somehow affect the way the final request or _resolved request_ is built after all Stored Imps and Stored Request are merged. It can be directly related to the [PR-2338](https://github.com/prebid/prebid-server/pull/2338)

## Expected behavior ##

The result I expected is the resolved request to have the `resolvedrequest.user.ext.consent` and the `resolvedrequest.regs.ext.gdpr:1` much similar to the one built by the endpoint _/openrtb2/auction_

## Questions ##

- If the parameters are being correctly passed in the URL sent to my PBS, and parsed, why are not added to the _resolvedrequest_ and sent to the bidders? 
(eg.: https://{...} &consent_string=CONSENT_STRING&account=ACCOUNT_ID&gdpr_applies=CONSENT_METADATA(gdprApplies)&addtl_consent=CONSENT_METADATA(additionalConsent)&consent_type=CONSENT_METADATA(consentStringType))

As usual, if you need more info just let me know.

I'll be looking forward for your reply.

Thanks,

Nelson

**Comment by guscarreon** [comment]
Hi Nelson,

Thanks for reaching out. From `v0.226.0` on an AMP reqiest that comes with the `consent_type` query field set to the value `2` needs that Prebid Server is configured with `gdpr.enabled` set to `true`, which is the default value. My guess is that probably your configuration on either on `pbs.yaml` or `pbs.json` sets this field to `false`:
```
{
    .
    .
  "gdpr": {
    "enabled": true,
    "default_value": 0
  },
    .
    .
}
pbs.json
```

```
   .
   .
gdpr:
  enabled: true
  default_value: 0
   .
   .
pbs.yaml
```

If this `gdpr.enabled` field is not explicitly set to `false` in Prebid Server's configuration, the following:
```
curl http://localhost:8000/openrtb2/amp\?tag_id\=9\&consent_type\=2\&gdpr_applies\=true\&consent_string\=CPdECS0PdECS0ACABBENAzCv_____3___wAAAQNd_X9cAAAAAAAA\&debug\=1
```
makes a locally running Prebid Server `v0.227.0` to effectively copy **a valid** TCF2 consent string to `user.ext.consent` and sets `regs.ext.gdpr` to `1`.
```
{
  "targeting": {},
  "debug": {
    "resolvedrequest": {
      "id": "b9c97a4b-cbc4-483d-b2c4-58a19ed5cfc5",
+-- 29 lines: "imp": [--------------------------------------------------------------
      "user": {
        "ext": {
          "consent": "CPdECS0PdECS0ACABBENAzCv_____3___wAAAQNd_X9cAAAAAAAA" //<-- copied consent string passed TCF2 validation
        }
      },
      "test": 1,
      "at": 1,
      "source": {
        "tid": "fc6c0ac2-3c03-4846-b14a-81c15aca0d89"
      },
      "regs": {
        "ext": {
          "gdpr": 1    //<-- set to 1
        }
      },
      "ext": {
+-- 26 lines: "prebid": {-----------------------------------------------------------
            "durationrangesec": null,
            "preferdeals": false
          }
        }
      }
    }
  }
}
```
Was this helpful? Am I missing something in regards to your question? Please let me know your thoughts

**Comment by snigel-nelson** [comment]
Hi @guscarreon 

Thank you for your fast reply. In fact, I don't have the `gdpr.enabled: true`, so this can be the reason why is not working. The sad part is that I looked at it and completely missed.
I've changed it and tested it again and I confirm that the resolved request has these 2 fields, just like the example you have in your answer above. The fields request.ext.debug.resolvedrequest.user.ext.consent and regs.ext.gdpr: 1 are now present in the request that will be sent to the bidders.

One question, though: When I use the request.test: 1 or request.ext.prebid.debug: true should not I see the list of objects: "ext": `request.debug.httpcalls`? Because I'm not getting it and I would like to inspect the `requestbody` to each SSP and respective `responsebody`

Thank you very much for all your support on this subject.
Cheers,
Nelson

**Comment by bsardo** [comment]
Hi @snigel-nelson,

If you have `gdpr.enabled: true` in your config and your request has `regs.ext.gdpr: 1`, the GDPR algorithm will be executed to determine whether you have consent to perform various activities. One of those activities that requires consent is sending a bid request and this activity involves purpose 2. If you don't have consent for any bidders, no bid requests will be sent so you won't see `httpcalls` in the debug output. I suspect this is what's happening. If you are able to share your example request with any sensitive info redacted or just share your consent string and the GVL IDs of the bidders in your example request I can help you figure out if this is the problem.

As for your second question regarding different geolocations, simply turning on `gdpr.enabled` in your host config will not make PBS enforce GDPR for all requests. You also need to send `regs.ext.gdpr: 1` in a request for GDPR to be enforced for that request so requests from different geolocations may or may not set this field.

I should also note that GDPR can be enforced if `regs.ext.gdpr` is omitted from the request but you have `gdpr.default_value: 1` in your host config.

Brian

**Comment by snigel-nelson** [comment]
Hi @bsardo,

Long time since the last time we interact. I hope everything is fine with you. 
Let me share with you some more info about this issue and the tests I've made. I performed some tests using AMP pages and some pages that have S2S HB implemented that send requests to my customized PBS. I'm using the following prebid-server version 0.227.0 and Prebid.js version 7.17.0.
So, in the PBS configuration file, **pbs.yaml**, I toggled the value of the `gdpr.enabled` parameter between true and false so that I could see what kind of response I was getting from PBS for both page types (AMP and standard with S2S). I will now present the results of these tests ordered by the value of `gdpr.enabled`: 

- `gdpr.enabled=true`
   1. S2S HB pages:
     - I've set the parameter `test:1`
     - I see `user.ext.consent` parameter in the resolved request and with the value correctly set 
     - I see the `regs.ext.gdpr: 1` in the resolved request	 
     - I don't see the `httpcalls` object being added to the resolved request
	 
   2. AMP pages:
     - I've set the parameter `test:1`
     - I see `user.ext.consent` parameter in the resolved request and with the value correctly set
     - I see the `regs.ext.gdpr: 1` in the resolved request	 
     - I don't see the `httpcalls` object being added to the resolved request	 
	 
- `gdpr.enabled=false`
   1. S2S HB pages:
     - I've set the parameter `test:1`
     - I see `user.ext.consent` parameter in the resolved request and with the value correctly set 
     - I see the `regs.ext.gdpr: 1` in the resolved request	 
     - I see the `httpcalls` object in the resolved request
	 
   2. AMP pages:
     - I've set the parameter `test:1`
     - I don't see `user.ext.consent` parameter being added to the resolved request and with the value correctly set
     - I don't see the `regs.ext.gdpr: 1` being added to the resolved request	 
     - I see the `httpcalls` object in the resolved request	 

One important remark, I'm using _Prebid.js v7.17.0_ on the standard HTML pages with S2S HB.
I'll share with you 2 files with the responses (AMP and S2S HB) from my PBS with the config parameter `gdpr.enabled=true` and some detailed info (Consent string and bidders used). You can see that consent was given to all the vendors. The files are in JSON to help.
- Debugged _response_ from a page using S2S HB (`gdpr.enabled`)
[Request_PBS_gdpr_enabled_s2s_HB.txt](https://github.com/prebid/prebid-server/files/9676038/Request_PBS_gdpr_enabled_s2s_HB.txt)
- Debugged _response_ from a AMP page (`gdpr.enabled`)
[Request_PBS_gdpr_enabled_AMP.txt](https://github.com/prebid/prebid-server/files/9676045/Request_PBS_gdpr_enabled_AMP.txt)


Regarding my 2nd question, I want to thank you for clarifying this. I'm using a CMP to set the `regs.ext.gdpr` parameter with the proper value (0 or 1) and then add it to requests sent to SSPs. However, I also want to thank you for mentioning that I can still apply the GDPR, in the case of omitting the _regs.ext.gdpr_, by configuring the `gdpr.default_value: 1`  in the **pbs.yaml** config file. I didn't recall this.

Thank for your help on this.

Best,
Nelson

**Comment by bsardo** [comment]
Hi @snigel-nelson,

Yes it's been a while 🙂. All is well here; I hope the same for you.

I'm having a hard time replicating your issue.

For right now I'm just focusing on your S2S HB request with `gdpr.enabled=true`. I took the resolved request from your `Request_PBS_gdpr_enabled_s2s_HB.txt` example and I'm sending it as is to a local PBS instance running v0.227.0 and I'm seeing `httpCalls`. I've tried playing with the config settings and I still always see `httpCalls`. I also checked your consent string, and yes, it appears to be valid and you are consenting to all of the purposes and vendors.

Can you do the following:
1. Provide the GDPR section of your config
2. Provide me with your request (not the resolved request) that you're sending
3. Check if you are seeing `httpCalls` if you send the resolved request defined in `Request_PBS_gdpr_enabled_s2s_HB.txt` as your incoming request.

Thanks,
Brian

**Comment by snigel-nelson** [comment]
Hi @bsardo,

All is well too, thanks. Sorry for the very late reply, I haven't gotten the chance to answer before. And this is a very important subject to me.
I've made the test you asked me, to send the resolved request defined in `Request_PBS_gdpr_enabled_s2s_HB.txt` and I'm still not getting the `httpcalls` object. I still don't understand why I'm not seeing the `httpcalls` object. 
Regarding the consent string, thank you for confirming that.

Now, I'll provide the information you requested.

1. The GDPR section of my **pbs.yaml**:
[PBS_cfg_GDPR_section.txt](https://github.com/prebid/prebid-server/files/9733224/PBS_cfg_GDPR_section.txt)
You can change the file extension if you want.
In this case the only parameter changed was `gdpr.enabled`

2. The request I'm sending from CS to my PBS. I tested this request by sending it to two PBS instances differing only on the config parameter gdpr.enabled=true (PBS_1) gdpr.enabled=false (PBS_2):
   - When I send to PBS_1 I get no `httpcalls` objects. I get a new parameter `"nbr": 2` and no `seatbids: []` object too, and this object is always present. I've tried with `test: 0/1`
   - When I send to PBS_2 I get `httpcalls` objects and all the other fields
   - The file with the request:    
     [Request_CS_to_PBS_gdpr_enabled_s2s_HB.txt](https://github.com/prebid/prebid-server/files/9733237/Request_CS_to_PBS_gdpr_enabled_s2s_HB.txt)
  
3. As I mentioned before, I sent the same request I provided to you (after correcting some JSON errors you probably had to) to the same 2 PBS instances of the previous point. the results were:
   - When I send to PBS_1 I get no `httpcalls` objects
   - When I send to PBS_2 I get `httpcalls` objects

The request had some info redacted, for privacy reasons but it was tested with the 2 PBS instances and it works.
I hope this info will help you to understand why this parameter (`gdpr.enabled`) makes the `httpcalls` object disappears and why it's important to have it enabled for AMP.

As usual, if you need anything else just let me know.
Thanks,
Nelson

**Comment by snigel-nelson** [comment]
Hi @bsardo ,

How’s everything? Do you have any news regarding this issue? Were you or maybe @guscarreon able to replicate the issue?
I’m a bit surprised because on my side I can replicate this issue as many times as I want by changing the _gdpr.enabled_ value in the _pbs.yaml_ file. Could it be any other parameter interfering with the _httpcalls_ object? 
As you said before, I only get the _httpcalls_ if I get any kind of response from the bidders, so can this parameter or another one block the sent of requests to the bidders?

If you need anything else or more info just let me know. Thank you for all your support.

Best,
Nelson

**Comment by bsardo** [comment]
Hi @snigel-nelson,

Sorry for the delay. There's quite a bit going on at the moment. I was finally able to reproduce your problem. Can you try adding the following to your config:
```
gdpr:
  timeouts_ms:
    init_vendorlist_fetches: 1000
    active_vendorlist_fetch: 1000
```
If you don't specify the timeout values they will default to 0 which should prevent the vendor list from being populated in the cache.
When I removed these from my config I started seeing  `"nbr": 2` and `httpCalls` was omitted from the response.

Hopefully that will resolve your problem. If not, I'm curious if your private custom build has made any modifications to the GDPR logic or the code in close proximity to where the GDPR logic is executed.

Brian

**Comment by snigel-nelson** [comment]
Hi @bsardo ,

No problem. Thank you for you support, it has been really great, and this is not an easy problem to solve, specially if you're busy solving other stuff.
Unfortunately, didn't see your mail before but I'll implement on Monday the `gdpr.timeouts_ms` as you say. Regarding my custom build I didn't implement any changes. I'm currently using the v.0230.0 and the only thing I've changed is the `pbs.yaml`. 
However, there is something that makes me a little uncomfortable or uneasy. If I don't want `gdpr` enforcement enabled then AMP will stop working, for S2S HB everything works fine and without  `gdpr.enabled: true`.
I'll test everything and get back to you as soon as possible.

Best,
Nelson

**Comment by snigel-nelson** [comment]
Hi @bsardo,

Only yesterday I got the chance to implement the solution you presented. Although, it's easy to implement I wanted to test and verify it several times, in testing, and production environments. I compared the same page using the 2 versions: standard HTML with **s2s HB** and **AMP**, as I explained previously. Of course, the requests are sent to the same PBS instance. This way I can verify the responses of PBS for **s2s HB requests** and for AMP pages.
**And it worked just fine.**
By adding the following configuration you suggested:
`gdpr:
    enabled: true
    timeouts_ms:
      init_vendorlist_fetches: 2000
      active_vendorlist_fetch: 2000
      `
I can now get the parameters I want in both page types (S2S HB, and AMP pages):
 
- I see `user.ext.consent` parameter in the resolved request and with the value correctly set
- I see the `regs.ext.gdpr: 1` in the resolved request
- I see the `httpcalls` object in the resolved request
- The consent string, gdpr, and buyeruid are being sent correctly to each bidder

Resuming, your solution worked, it was a question of enabling the GDPR and setting timeouts. The only problem I see is for some geolocations where there's no need for GDPR or I don't want to enforce it.

Once again, many thanks for your support on solving this.

All the best,

Nelson

**Comment by bsardo** [comment]
Hi @snigel-nelson,

I'm happy to hear the solution worked for you. I'm going to go ahead and close this issue now that it's fixed.

As for only enforcing GDPR for particular geolocations, with the available host and request controls, you should be able to come up with a networking architecture that allows you to meet the GDPR requirements of different geolocations. In order for GDPR to be enforced for a particular request, GDPR must be enabled at the host level and either the request must set `regs.ext.gdpr: 1` or the host must have configured `gdpr.default_value: 1` so GDPR is applied if `regs.ext.gdpr` is omitted from the request.

Brian
