### ISSUE TITLE
PBS-Java 1.98 uses wrong query param for TRUSTX bidder

### ISSUE THREAD

**Issue by TheMediaGrid** [prebid/prebid-server#2389]
Hi @bretg 

We noticed that since BuzzFeed upgraded to pbs-java 1.98 all the requests are going to the endpoint with sp=prebid query param (this param only works for Grid bidder). We need it to be changed back to sp=trustx ASAP. 

Can you please take a look?

**Comment by bretg** [comment]
@TheMediaGrid - there weren't any changes in 1.98 around endpoint, but there was restructuring in the bidder config. I've confirmed that trustx is being hit with sp=prebid and have opened a high priority internal ticket to resolve ASAP.

If you'd like we could remove the trustx bidder from the wrapper until resolved?

**Comment by bretg** [comment]
Ok - dug into this and found the issue it's not directly PBS-related. 

See:
- https://github.com/prebid/Prebid.js/issues/6336
- https://github.com/prebid/prebid-server/issues/2391
