### ISSUE TITLE
Review Account Resolution

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2395]
While reviewing the module infrastructure for the PBS-Go development of that feature, we started discussing the account ID resolution process and how it fits in with the "raw auction request" module hook.

Here's what's implemented in PBS-Java. Would like to review this process with the PBS-Go team for alignment.

1. look in site.publisher.id
2. look in app.publisher.id
3. if AMP, look for the 'account' parameter on the query string
4. If we still don't have the account ID and there's a top-level stored request (ext.prebid.storedrequest.id), query without the account ID qualifier. Note that this could happen before the "raw auction request" module hook.
4a. if there's more than one response, error at N% sampling with "Stored request processing failed: Multiple stored %ss found for id: %s but no account was specified." Log a stored_imps.missing metric.
4b. if there's only one response, look in the stored request body for site.publisher.id or app.publisher.id.
5. If still no account ID and it's required, error at N% sampling with existing "Unauthorized account id: %s" error.
6. Do the account config lookup.
7. Run any modules requesting the "raw auction request" hook
8. If a module changed the top-level stored request, do the stored request query again.

**Comment by SyntaxNode** [comment]
Thank you for opening this issue @bretg. It's good to check in on how PBS-Go and PBS-Java align on core functionality.

I've reviewed the PBS-Go code and can confirm this workflow is functionally the same. Details of the implementation are a bit different, as perhaps expected, but the end result is as described. Step 4a does not apply to PBS-Go as account ID qualifiers are not implemented for stored request lookup, as we expect hosts to use a guid. We plan to add the account id qualifier in the future when we rewrite the stored request retrieval code, or if a community contribution gets to it first.

However, I don't believe PBS-Go offers the same host logging behavior as defined in steps 4 and 5. Metrics are offered for the host but log entries are not emitted. The error message returned to the publisher might also be different, they are currently:

#### Account Blocked
> Prebid-server has disabled Account ID: %s, please reach out to the prebid server host.

#### Account Required + Not Provided
> Prebid-server has been configured to discard requests without a valid Account ID. Please reach out to the prebid server host.

#### Account Required + Not Found
> Prebid-server could not verify the Account ID. Please reach out to the prebid server host.

#### Account Found + Invalid JSON
> The prebid-server account config for account id \"%s\" is malformed. Please reach out to the prebid server host.

Note that these errors are non-json plaintext. I wouldn't be opposed to changing this in the future to always return a json object, but I fear this might break public folks using this API today.

> If a module changed the top-level stored request, do the stored request query again.

This is currently in progress for PBS-Go. It's important to note that while the account for the auction flow will be updated if changed by a module before the "Processed Auction Request " hook, it will not affect the modules program as that's locked before modules have a chance to change the request.

**Comment by bretg** [comment]
Resolved that account resolution is generally aligned.

Will open a separate issue to discuss the error messages that go back to the publisher.
