### ISSUE TITLE
lower tmax for bid adapters

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2398]
Prebid Server receives a `tmax` timeout parameter from the request or storedrequest. It enforces this value in the following way (at least in PBS-Java):

1. A timestamp is taken at the start of the request
2. Before calling the bidders, another timestamp is taken to find out how long PBS has had the request.
3. A timer is set for tmax-timeTakenSoFar-config(auction.timeout-adjustment-ms)
4. Bidders are called with the original request tmax
5. If the timer pops, any remaining bidder responses are abandoned

i.e. we're not giving adapters the actual amount of time they have.

We're seeing instances where Prebid.js records a Prebid Server timeout even though the slowest adapter was way less than the tmax they were given. e.g. if tmax is 1000 and the only adapter responds in 250ms, there's still a timeout. 

This is an expected scenario -- the network transit time between browser and PBS is one of the biggest expected consumers of the tmax period. Browser processing time is another chunk. 

Server-side bid adapters would like to be given a more clear idea about how much time they have to respond a request. Letting them know this might help them respond faster, e.g. not waiting for slower backend responses.

We propose adding a host-level configuration to PBS that causes it to build a buffer into the tmax sent to adapters:

auction.biddertmax.percent: 55.   // default 100%
auction.biddertmax.min: 200

First, PBS should decrease the tmax sent to the bidder by its internal processing time.

PBS would apply `percent` to the tmax and pass the results to each, capped at `max`. e.g. if tmax:1000 with the above config, bidders would see tmax:500. If request tmax was 500, bidders would see 275.

- if there's no incoming tmax, set it to auction.max-timeout-ms
- otherwise, cap the incoming to max auction.max-timeout-ms
- tmax(bidder)=(tmax(pbs)*biddertmax.percent)-internalProcessingTime
- floor the tmax to min auction.biddertmax.min

PBS would then also enforce this value -- setting the timer in step 3 above to this value instead.

It's noted that we could attempt to be more surgical and account for the time taken in PBS itself, but it's recognized that any `auction.biddertmax` value is a guess that makes such precision questionable. It's possible there could be future modules that optimize `auction.biddertmax` based on client geography, but that's a future project.

**Comment by bretg** [comment]
I'm told that at least in PBS-Java, auction.timeout-adjustment-ms is for internal PBS timeout only. It doesn't modify what's sent to the bidder. 

I prefer the proposal outlined above, and propose deprecating timeout-adjustment-ms... ignore it if auction.biddertmax isn't specified.

**Comment by bretg** [comment]
Discussed and approved in committee.

**Comment by bretg** [comment]
Discussed (at length) internally and have proposed revision to the algorithm.

### Core concepts 

- request_tmax: what the incoming request defines as tmax
- biddertmax_max: controls that upstream doesn't tell us ridiculous values
- biddertmax_min: it's not worth calling bidders and give them less time than this. (e.g. 150)
- biddertmax_percent: a lower number means more buffer for network delay. Host companies should set this to a lower value in regions where the network connections are slower.
-  tmax_upstream_response_time: the amount of time that PBS needs to respond to the original caller
processing_time: PBS's view of how long it's been since the start of the request up to the point where the bidders are called

There's an existing config value called auction.timeout-adjustment-ms that will be obsoleted, replaced by tmax_upstream_response_time

### Actionable values

Turns out the tmax sent to bidders isn't the only value PBS needs to care about. It also needs to set a timeout for the maximum amount of time it's willing to wait for bidders to respond.

- **bidder_tmax** - this is how long we tell the bidders they have to respond. The conceptual formula is: capped(request_tmax)*biddertmax_percent - processing_time - tmax_upstream_response_time ==> floored to the min.

- **enforced_tmax** - this is long we actually give them: capped(request_tmax)- processing_time - tmax_upstream_response_time ==> maxed to the bidder_tmax


So the full formulas would be:

**bidder_tmax**=max(calculated_tmax, biddertmax_min)=max((min(request_tmax,biddertmax_max)*biddertmax_percent)-processing_time - tmax_upstream_response_time, biddertmax_min)

**enforced_tmax**=max(calculated_enforcement,bidder_tmax)=max(min(request_tmax,biddertmax_max)-processing_time - tmax_upstream_response_time , bidder_tmax)

Here's a diagram of the flow aiming to highlight the various time periods:

![PBS tmax](https://user-images.githubusercontent.com/4412838/202569001-6c2314a2-9c28-4e97-9866-bc96a563914d.png)

And here's a spreadsheet with some sample values -- https://docs.google.com/spreadsheets/d/17BqmVvt5heJK2CxMdkdFrZ5PON-q2up5ItYzYFm5TFQ/edit#gid=0

**Comment by bretg** [comment]
Reviewed again internally and tweaked some working but not formulas. We agreed there are probably ways to improve this in the future:
- we could explore utilizing the auctiontimestamp. (if we trust that it's reliable)
- an optimization module that tracks response rates would be possible

**Comment by bretg** [comment]
Discussed in committee.
- We should document a minimum min. Some bid adapters may not accept requests with a tmax under a certain value.
- This likely is not the last word in `tmax`. There may be future enhancements to support per-bidder settings or perhaps per-account settings.

Ideally, publishers shouldn't have to worry about the timeout values -- this should be something the host company manages for them, but it may be useful to have overrides in the future.

**Comment by bretg** [comment]
Note: this proposal also deprecates the `auction.cache.expected-request-time-ms` config option, with the intention being that value is folded into tmax_upstream_response_time

**Comment by bretg** [comment]
Done with PBS-Java 1.108

**Comment by onkarvhanumante** [comment]
Done with PBS-GO v0.272.0

Created docs PR https://github.com/prebid/prebid.github.io/pull/4863/files to add instructions to assist PBS-GO hosts in configuring their PBS settings to align with this updated usage of tmax.

**Comment by SyntaxNode** [comment]
Thank you @onkarvhanumante.
