### ISSUE TITLE
I cant make the prebid-server to work.

### ISSUE THREAD

**Issue by photonx** [prebid/prebid-server#24]
I have created two examples: one that makes header bidding without prebid-server and a second one with it.
The first test without prebid-server works fine, but the second one doesn't.

At the first call of  the prebid-server auction url the response sends an url for user sync but prebid.js doesn't make the sync so i manually called the url returned by prebid-server/auction.

After i did this i receive from prebid-server auction this response

_{"tid":"c730e370-277c-4cb3-bd4b-ee44fed1d82e","status":"OK","bidder_status":[{"bidder":"appnexus","response_time_ms":35,"no_bid":true}]}_

This is the prebid-server config added at the second example:
        pbjs.setS2SConfig({
          accountId: '2d749ec2-6a1d-4205-bf6b-5dd8d41386f9',
          enabled: true,
          bidders: ['appnexus'],
          timeout: 1000,
          endpoint: 'http://devprebid.elasticad.net/auction'
        });

Another thing i saw is that you have to  add '/auction' to the endpoint in order to work. i'm not sure that this is intended or not.

I don't know if there is something wrong with the prebid-server or with my prebid.js configuration that the prebid server example doesn't work as expected.

Without PrebidServer
http://jsfiddle.net/photonx/ngdguvg8/

With PrebidServer
http://jsfiddle.net/photonx/L1n27nwx/

**Comment by mkendall07** [comment]
Are you running the latest code from master for prebid server? The user sync worked for me BTW on your example, and now receiving the same no bid response.

**Comment by photonx** [comment]
yes. today i updated it.

**Comment by mkendall07** [comment]
you can add `is_debug` true on the pbjs => pbs request (see [here](https://github.com/prebid/Prebid.js/pull/1195/files#diff-f2a56b559f3e1796f2dc4286cff5dbffR88) ).

Also you can add `?debug_member=${member}&dongle=${dongle}` to the `/openrtb2` endpoint to get the debug auction.

**Comment by photonx** [comment]
I have done the debug modification and the response from debug is that the auction is winning but the response from prebid-server remain the same no_bid:true.
{"tid":"4fa71a3e-824f-47e5-a718-ce0078637ecc","status":"OK","bidder_status":[{"bidder":"appnexus","response_time_ms":9,"no_bid":true,"debug":[{"request_uri":"http://ib.adnxs.com/openrtb2","request_body":"{"id":"4fa71a3e-824f-47e5-a718-ce0078637ecc","imp":[{"id":"doNotChange","banner":{"w":300,"h":250,"format":[{"w":300,"h":250}]},"ext":{"appnexus":{"placement_id":11397800}}},{"id":"doNotChange","banner":{"w":300,"h":250,"format":[{"w":300,"h":250}]},"ext":{"appnexus":{"placement_id":11397805}}}],"site":{"domain":"jshell.net","page":"http://fiddle.jshell.net/_display/"},"device":{"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","ip":"172.17.32.30"},"user":{"id":"1445660839455253952","buyeruid":"1445660839455253952"},"at":1,"tmax":1000,"source":{"fd":1,"tid":"4fa71a3e-824f-47e5-a718-ce0078637ecc"}}","status_code":204}]}]}

Here is the response from the debug response.

### Tag #0:	Auction 4962992511257319440 result: EXCLUSIVE
Winning bid (CPM) gross price: $1.0000
Winning bid (CPM) net price $1.0000, biased price $1.0000
Soft floor: $1.000
Final second price: $1.0000
Bid shading price: $1.0000
Bidder 2 Member 2579 creative 68869969 has the highest net bid: $1.000
Tag #1:	Auction 6447974757804636509 result: EXCLUSIVE
Winning bid (CPM) gross price: $1.0000
Winning bid (CPM) net price $1.0000, biased price $1.0000
Soft floor: $1.000
Final second price: $1.0000
Bid shading price: $1.0000
Bidder 2 Member 2579 creative 68870040 has the highest net bid: $1.000

**Comment by cinashp** [comment]
@photonx Did you manage to get this working? I am facing the same issue.

**Comment by bokelley** [comment]
Hi there - I think this might be because the IP getting passed to prebid server is in the private range. Could be because you're testing locally? AppNexus as a bidder will automatically reject IP addresses that are invalid. I'm going to close this b/c it's not a prebid server issue.

**Comment by vishalgarale** [comment]
I am also facing the same issue.

**Comment by bokelley** [comment]
@vishalgarale if you paste in the debug call we can take a look - can you check and make sure the IP is a real one?

**Comment by 465730396** [comment]
能给我一个完整的prebid 例子吗，为啥官方给的例子和源代码没法对应上去呢
Can you give me a complete prebid example, for the official example and the source code can't correspond?
