### ISSUE TITLE
Define how server-side adapters should pass fledge auction config

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2411]
Related to https://github.com/prebid/Prebid.js/issues/9080

We need to define how server-side adapters should pass fledge auction config. 

We're working out the PBS-PBJS protocol in the other issue. This one is for tracking how adapters specify the value.

**Comment by bretg** [comment]
Here's the format of the wire protocol as discussed in https://github.com/prebid/Prebid.js/issues/9080
```
{
  ext: {
    fledge: {
      auctionconfigs: [{
          impid: "123",
          bidder: "bidderA",
          config: { ... }
     },{
          impid: "123",
          bidder: "bidderB",
          config: { ... }
     }]
  }
}
```

So I think PBS-core will have the following responsibilities:
1. Pick up the fledge auctionconfig from wherever bid adapters are placing it
2. Make sure that bidders aren't submitting fledge auctionconfig for other bidders. (subject to the "multiple biddercode" rules)
3. Make sure that fledge auctionconfig is associated with a valid imp object

No need to validate the body of the fledge auctionconfig

I'm too fuzzy on the bid adapter interface to suggest the path-forward here. Need @SyntaxNode and @net-burst to weigh in on this aspect.

**Comment by bretg** [comment]
We discussed fledge in the PBJS committee. The JSON format is approved, but might change in the future if the IAB comes up with a different format.

The preference is that "bidder" is the biddercode that's in imp.ext.prebid.bidders... i.e. 'pubm_ss' rather than 'pubmatic'. Not clear to me this is available to bid adapters. 

If the bid adapter is aware of how it was invoked, then it should use that code. This might differ if the adapter is fronting other bidders, i.e. in "allowUnknownBidderCodes" mode. In that case, it seems that the adapter will need to return the best biddercode it has available.

**Comment by laurb9** [comment]
The bidder code could (and I would argue, should) be added by the framework. In PBS-Go bidders respond with a [structure](https://codinginadtech.com/prebid-live-tests/fledge/gpt-simple.html) that has Bids and Currency, we can leverage that to pass the auction config array.

I may have some bandwidth so I can look into implementing this once the prebid.js prebid-server adapter convention is sorted out.

**Comment by laurb9** [comment]
We should also discuss how the "auction environment" parameter `ae` should be passed. There are two options: 
- `imp.ext.ae`/`imp.ext.auction_environment` hoping to be eventually standardized, or 
- a prebid extension `imp.ext.prebid.ae` which is similar to how `is_rewarded_inventory` is passed, or
- bidder-specific extensions `imp.ext.prebid.<bidder>.ae` but that could turn out to be unnecessarily verbose in constructing the request as well as code, as it would need to be added to every ext/imp bidder contract.

**Comment by SyntaxNode** [comment]
Discussed in the Prebid Server Committee.

The bidder should pass the auction config to Prebid Server via the existing bid response data structure, which is TypedBid for PBS-Go and BidderBid for PBS-Java. PBS-Core will put it in the right spot.

We still need to work out the multi-bid scenario. How should this be handled in respect to bundling?

**Comment by SyntaxNode** [comment]
@laurb9 What is the Fledge "auction environment"?

**Comment by laurb9** [comment]
@SyntaxNode The auction environment is a numeric flag passed in the bid request, indicating that the client would accept a FLEDGE response for that imp. Originally it was spec-ed as a DSP parameter (`imp.ext.ae`=1) then we adopted the same form for SSP, so we can pass it through.

**Comment by bretg** [comment]
PBS will pass `imp.ext.ae` through. Is there any enforcement actions that should be taken -- like if imp.ext.ae:0, then don't accept fledgeauctionconfig?

**Comment by laurb9** [comment]
I have pushed [a proposal for PBS-Go](https://github.com/prebid/prebid-server/pull/2445) so we can discuss over it.

PBS does pass `imp.ext.ae` but due to historical usage of imp.ext.<bidder> for bidder parameters, other parameters like `is_rewarded_inventory` live in `imp.ext.prebid` instead. Open to move it back to `imp.ext.ae` and carve another bidder name exception, makes for less decoding if we want to validate impid.

Regarding bid passing - since the auction config structure shares nothing with a regular `Bid`, I defined the adapter contract in PBS-Go as `BidderResponse.FledgeAuctionConfig`, independent of `BidderResponse.Bids`. From there it is copied to a corresponding field in`pbsOrtbSeatBid` and collected into the response ext afterwards.

 I'll take a look at PBS-Java next.

**Comment by bretg** [comment]
My take is that adding an exception for `imp.ext.ae` is easy. Let's do that.

**Comment by bretg** [comment]
@laurb9 - where did `ae` come from? Found two docs on this, both defining `BidRequest.imp.ext.auction_environment`
- https://developers.google.com/authorized-buyers/rtb/fledge-origin-trial
- https://github.com/google/openrtb-doubleclick/blob/master/doubleclick-openrtb/src/main/protobuf/openrtb-adx.proto

**Comment by bretg** [comment]
We discussed in a meeting today and agreed this is ready-for-dev once we settle the `ae` request parameter.

Given that the references found so far are for auction_environment, but apparently that's not an official IAB extension. So we have several options:

1. Since there's not IAB-level approval, we should start off with imp.ext.prebid.ae and move it when the community settles
2. Since there's not IAB-level approval, just wait
3. Assume that Google's recommendation is going to stick - just use imp.ext.auction_environment

We also discussed tuning the response to push it down to ext.prebid and add 'adapter':
```
{
  ext: {
    prebid: {
      fledge: {
        auctionconfigs: [{
          impid: "123",
          bidder: "bidderA",     // adapterB was called with alias bidderA
          adapter: "bidderB",
          config: { ... }
       },{
          impid: "123",
          bidder: "bidderC",
          adapter: "bidderC",
          config: { ... }
       }]
     }
  }
}
```
PBS-core actions:
1. Pick up the fledge auctionconfig from (typedbid/bidderbid) 
4. Make sure that fledge auctionconfig is associated with a valid imp object
5. Generate combined ORTB for all submitted auctionconfig

**Comment by laurb9** [comment]
The DSPs we worked on early integrations with (DV360 and RTBHouse) used `imp.ext.ae` so we went with that in [Prebid.js](https://github.com/prebid/Prebid.js/pull/8716) and our corresponding backend, since those were the only implementations we were aware of.

FLEDGE is a trial and we can change the field name if it ends up standardized as something else.

**Comment by laurb9** [comment]
Regarding implementation, I think both PBS-Go and PBS-Java could use a clean and explicit mechanism to pass back response data that is independent of the stream of bids. There is no overlap between the fledge auction config fields and [TypedBid](https://github.com/prebid/prebid-server/blob/29dfd0bc551134a4bb1e4dd5bb7ef251870d6c81/adapters/bidder.go#L88-L104) or [BidderBid](https://github.com/prebid/prebid-server-java/blob/387f5f19b3da52d766815c3f300826c1be3ae4e8/src/main/java/org/prebid/server/bidder/model/BidderBid.java),which indicates to me that the auction config should be a different class.

Similar to Prebid.js, PBS-Go has a specialized [BidderResponse](https://github.com/prebid/prebid-server/pull/2445/files#diff-dd4cba00d8624aa0691f1e3457c9400b8b9beca6fc183c66686b3e4c479ea5cbR63-R65) as the contract with bidder adapters, so it took minimal changes to add the fledge config as I did in my [PR](https://github.com/prebid/prebid-server/pull/2445).

PBS-Java expects a `Result<List<BidderBid>>` from bidder adapters, `Result` is a generic template used for other purposes, so passing the metadata just for the bid responses will have a larger impact on the code here.

**Comment by bretg** [comment]
The Prebid.js committee resolved to use `imp.ext.ae` as the input parameter. 

> The request and response should both agree on whether they're in prebid or not

We also discussed this and decided it's not important for them to both be in prebid or not. For the record, here's the logic:
- imp.ext.ae: there's (supposedly) already some industry weight behind this parameter. It's a single value. Seems likely that the IAB will accept this recommendation.
- ext.prebid.fledge: this is very different. It seems unlikely that the IAB will accept this entire complex structure and we don't want to end up partly conflicting with their final recommendation. 

Marking this ready-for-dev.

**Comment by dmdabbs** [comment]
> apparently that's not an official IAB extension

Regarding `Imp.ext.ae` and IG auction signaling moving forward, see the proposed IG signaling in public comment:

PR: https://github.com/InteractiveAdvertisingBureau/openrtb2.x/pull/86
Public Comment Issue: https://github.com/InteractiveAdvertisingBureau/openrtb2.x/issues/83

**Comment by SyntaxNode** [comment]
We will open a new issue and implement the new signals as part of OpenRTB 2.6 202312.
