### ISSUE TITLE
Remove procbidresponse stage from module infrastructure

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2415]
We've discovered that the `procbidresponse` stage and `allprocbidresponses` stages are happening at the same place in the PBS workflow. Specifically, they are happening after all bid responses are in and/or timed out. So they're redundant, and allprocbidresponse is more useful in that it has better performance characteristics.

The team has determined that moving procbidresponse to a 'real-time' location (i.e. immediately after the bid response, before timeouts) would take non-trivial effort in refactoring. So I'm proposing we remove the `procbidresponse` for now, perhaps adding it back in the future if there's a module that needs it.

@muuki88 - you guys are the only ones I know who have created private modules. Any feedback?

**Comment by muuki88** [comment]
No objections from our end. We are using the following hooks

- `ProcessedAuctionRequestHook`
- `AuctionResponseHook`
- `RawAuctionRequestHook`

**Comment by bretg** [comment]
Done.
