### ISSUE TITLE
Prebid Server request diagnostic extension field

### ISSUE THREAD

**Issue by shahinrahbariasl** [prebid/prebid-server#2419]
Today there isn't an easy way to collect diagnostic data from Prebid Server requests to bidders. Being able to collect diagnostic info from PBS can help with better understanding PBS adapter integrations. It can also help with collecting diagnostic info to troubleshoot and test new feature. 

We would like to propose adding a new `Diag` field to the extension field in Prebid Server request to ad exchanges and bidders.

As a start, example general diagnostic information to be sent to bidders can be:

- client side and server side version
- Java vs Go version

Furthermore, we can expand on the above and let adapters add bidder specific key values to the `Diag` object. For example:
```
...
"ext": {
  "prebid": {
    "diag": {
      "pbjsv": "7.10.0",
      "pbsv": "0.225.1",
      "bidder": {
        "bidder_specific_key_1": "value1",
        "bidder_specific_key_2": "value2",
      }
    }
  }
}
```

This approach would let bidders to be able to decide what diagnostic fields they want to add to their adapters. To make sure random keys don't get inserted to the diag object, we can enforce validation through bidder configs and also enforce naming conventions for key names.

This idea is similar to diagnostic info that bidders can add to r.ext in their PBJS adapters.

**Comment by bretg** [comment]
@shahinrahbariasl - PBJS, SDK, and PBS versions are already sent to bidders. 

PBJS
```
ext.prebid.
            "channel": {
                "name": "pbjs",
                "version": "v7.19.0-pre"
            },
```
PBSDK
```
"app.ext.prebid": {
   "source":  "prebid-mobile"
   "version": "1.2.3"
}
```

PBS version and SDK version are placed in the x-prebid HTTP header as discussed in https://github.com/prebid/prebid-server/issues/2010 and documented at https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#http-headers

e.g.

```
x-prebid: prebid-mobile/1.2.3,pbs-java/1.64
```

Publishers and bid adapters can add whatever fields they'd like to site.ext.data, app.ext.data, user.ext.data, and/or bidder params.

This all seems sufficient for diagnostics. Please re-open if I've missed the point here and there's a use case not covered.
