### ISSUE TITLE
Add mediatype to PBS Response

### ISSUE THREAD

**Issue by dbridges12** [prebid/prebid-server#243]
Prebid.js is looking for the mediatype param in the PBS response - should be either video or banner. 

Excerpt from prebidServerBidAdapter.js that is expecting this response param:

```
if (bidObj.media_type === VIDEO) {
              bidObject.mediaType = VIDEO;
              if (bidObj.adm) {
                bidObject.vastXml = bidObj.adm;
              }
              if (bidObj.nurl) {
                bidObject.vastUrl = bidObj.nurl;
              }
            } else {
              if (bidObj.adm && bidObj.nurl) {
                bidObject.ad = bidObj.adm;
                bidObject.ad += utils.createTrackPixelHtml(decodeURIComponent(bidObj.nurl));
              } else if (bidObj.adm) {
                bidObject.ad = bidObj.adm;
              } else if (bidObj.nurl) {
                bidObject.adUrl = bidObj.nurl
              }
            }
```

Currently this generates a runtime error for video responses from pbserver.

**Comment by dbemiller** [comment]
Little bit confused, actually... the media type _is_ in the PBS response. See https://github.com/prebid/prebid-server/blob/master/pbs/pbsresponse.go#L18

Or are you talking about the OpenRTB endpoints here?

**Comment by mkendall07** [comment]
@dbridges12 
The prebid server adapter for Rubicon needs to set the media type. See here how the AppNexus adapter does it: https://github.com/prebid/prebid-server/blob/master/adapters/appnexus/appnexus.go#L210

**Comment by dbridges12** [comment]
perfect - thanks for pointing us in the right direction @mkendall07 @dbemiller
