### ISSUE TITLE
Review /status endpoint

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2431]
It's come to my attention that the Prebid SDK is depending on a particular value to come back from the /status endpoint.

Neither PBS-Go nor PBS-Java conform to what's documented at https://docs.prebid.org/prebid-server/endpoints/pbs-endpoint-status.html, though that page does specifically say "exact response can be configured with the status_response config option", so it's clear that the SDK should not have been relying on this in the first place.

That said, the committee should discuss a path forward here.

My proposal is to just update the documentation. Host companies should be able to define the status output any way they need to (e.g. for custom in-house monitoring services) and external parties (like the SDK) should not rely on a consistent response from any individual PBS.

But an alternate proposal would be to support a query string, e.g. "/status?format=text" that replies with a simple consistent result. e.g. "error" and "ok"

**Comment by SyntaxNode** [comment]
Could the SDK rely on the /status endpoint returning a 200 value and ignore the body?

**Comment by bretg** [comment]
Ok - HTTP 200 is enough to determine server status. Will update the documentation and close this issue.
