### ISSUE TITLE
Handle GZIP compression at the OpenRTB endpoints

### ISSUE THREAD

**Issue by sag-celejd** [prebid/prebid-server#2438]
The current endpoints do not seem to support any type of compression for incoming requests. Looking at the code naively e.g. in **auction.go**, a quick implementation looks somewhat simple: 

> Check the **Content Encoding** header in the **parseRequest** method and decompress if needed. Maybe even implement a gzip.Reader pool to keep GC pressure low.

Is there anything speaking against this approach - maybe I'm missing something.
I would be willing to prepare a pull request if this seems fine.

**Comment by SyntaxNode** [comment]
We support gzip compression for incoming requests. This feature is disabled by default. To enable it, set the `enable_gzip` config value to `true`.

**Comment by sag-celejd** [comment]
Thanks for the response.

Can you guys point me to where you actually handle incoming compressed requests in the code?
I'm only seeing that https://github.com/NYTimes/gziphandler is being used to gzip the response.

I am aware of **enable_gzip** but that only seems to be relevant for the bidder adapters.

Maybe I expressed myself poorly. I might be doing something wrong but what I'm saying is that e.g. a request like so does not seem to be supported:
`echo '{"foo": "bar"}' | gzip | curl -v -i --data-binary @- -H "Content-Encoding: gzip" --request POST https://foo.bar/openrtb2/auction`

**Comment by SyntaxNode** [comment]
> I'm only seeing that https://github.com/NYTimes/gziphandler is being used to gzip the response.

Huh. It seems I misremembered that the NYTimes handler just handles the response, not the request.

> I would be willing to prepare a pull request if this seems fine.

Sounds good to me. Please still utilize the `LimitedReader` so we have protection from large requests and from zip bombs.

**Comment by josepowera** [comment]
To support incoming GZIP compressed PBS requests would be also useful in:
-server 2 server traffic - in SSAI and DOOH applications.  
-in client side traffic to lower bandwidth (mobile) data transfer.

However gzip decompress could be also most probable done in loadbalancer before PBS.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.259.0.
