### ISSUE TITLE
Support For OpenRTB 2.6-202211

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#2442]
OpenRTB 2.x is changing to a monthly release cadence, as needed. The first monthly release will be for November 2022 with the version designation of "OpenRTB 2.6-202211". This so far includes
- DOOH (Digital Out Of Home) as a new inventory type alongside App and Site.
- GPP
- Imp-Level Exposure Time

The 2.6 spec is now available at https://github.com/InteractiveAdvertisingBureau/openrtb2.x with 2.6-202211 features represented as PRs.

We already have issue https://github.com/prebid/prebid-server/issues/2380 to cover the implementation details of GPP. The Imp-Level Exposure Time is likely just a new field we need to add (imp[].etime).

DOOH will require more effort since PBS has a fair amount of "if app, else site" logic. At a minimum we'll need to add and enforce a new `dooh` capability along side `app` and `site`. Adapters logic is likely fine if we keep `dooh` support disabled by default so adapters can still safely rely on their "if app, else site" logic. We'll need to find ad update those kind of checks in core functionality.

**Comment by SyntaxNode** [comment]
It doesn't look like `imp[].ext.tid` will be promoted to `imp[].tid` in this release.

**Comment by bretg** [comment]
The GPP work will be done as part of https://github.com/prebid/prebid-server/issues/2380

We need to wait for the IAB to finalize the dooh and etime fields before considering this ready-for-dev.

**Comment by minaguib** [comment]
The IAB [announced](https://iabtechlab.com/blog/dooh-integrated-into-openrtb/) on December 7th the finalization and release of the OpenRTB spec which includes DOOH support

**Comment by SyntaxNode** [comment]
Thank you @minaguib for your input on Digital Out Of Home (DOOH).

PBS-Go uses the [prebid/openrtb](https://github.com/prebid/openrtb) library which is the official continuation of  [mxmCherry/openrtb](https://github.com/mxmCherry/openrtb). The [prebid/openrtb](https://github.com/prebid/openrtb) library fully supports all OpenRTB 2.6-202211 fields including DOOH. However, Prebid Server is not yet aware of DOOH in the same way it is for App and Site. Let's consider this the kick off.

I'm working on this today for PBS-Go to determine exactly which areas of code are impacted.

Adapter code involving "site or app" will not be affected because each adapter already has to opt-in to support specific inventory types via the bidder configuration. Adapters will only receive requests for inventory types they support. When we add the DOOH inventory type all of the adapters will default to not supporting it.



 If an adapter is not configured for a specific inventory type, 

Adapters should continue to work perfectly fine as we add DOOH support due to the way capabilities are programmed. Each adapters needs to opt-in to which inventory type they support. Requests to their adapter which do not support this inventory type are filtered out.

**Comment by SyntaxNode** [comment]
OpenRTB 2.6-202211 was not yet finalized when this issue was created and there were a few unexpected changes. Here's the complete list:

- New Object: [request.dooh](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectdooh)
- New Object: [imp.qty](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectqty)
- New Field: imp.dt (timestamp when the item is estimated to be fulfilled)
- New Field: app.inventorypartnerdomain & site.inventorypartnerdomain (a domain to be used for inventory authorization)
- New Field: regs.gpp
- New Field: regs.gpp_sid

We have separate issues for tracking
- GPP (tracked by https://github.com/prebid/prebid-server/issues/2380)
- DOOH (tracked by https://github.com/prebid/prebid-server/issues/2532)

The only other remaining new field we haven't yet discussed is `inventorypartnerdomain` and if there is any logic for PBS to perform in relation.

**Comment by bretg** [comment]
resolved with PBS-Java 2.1
