### ISSUE TITLE
OpenRTB Support: Stored Requests by Account

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#245]
#207 added support for Stored Requests inside the OpenRTB `Imp`.

However, mobile requires a few key features to be stored server-side which _aren't_ inside the `Imp`. We need to expand Stored Request support to handle these:

- Price Granularity (inside `request.ext`. See #206)
- Auction timeout (inside `request.tmax`)

One very simple way to introduce this is by lifting the limitation that `ext.prebid.storedrequest.id` only lives on the `Imp`. If we allow it on the `Request` as well, then these two cases are covered.

However, this brings up a moderate complication regarding "nested" Stored Request data. What happens if:

- A Stored Request ID is included on the `Request` _and_ the `Imp`?
- The incoming HTTP request has an ID on the `Request`, but then the _stored data_ specifies another `Imp` with another Stored Request ID?

Besides introducing unclear behavior, there's also a tradeoff between flexibility and efficiency.

- Resolving nested IDs will require more than one JSON Merge
- Resolving nested IDs _from the stored data_ will require multiple trips to the DB/backend

Of course, we could resolve these with explicit options:

```
{
  "prebid": {
    "storedrequest": {
      "id": "20",
      "resolvenested": true
    }
  }
}
```

...but adding options is generally a bad idea unless there's no other way to get sensible behavior, so I'd like to avoid that if at all possible.

**Comment by dbemiller** [comment]
I have a few spare work cycles... so I'll start thinking about this in more detail.

**Comment by dbemiller** [comment]
I think the best plan is to:
1. Allow Stored Requests on the incoming BidRequest.
2. Only IDs present in the HTTP request will be resolved. Stored Request IDs inside Stored Request data will be ignored.
3. Document that Stored Request patches are applied in "undefined" order.

In practice, since we only support Stored Requests on `BidRequest` and `Imp`, (3) is equivalent to saying "If your Stored `BidRequest` contains an `imp` property, then Imp-level Stored Requests will be ignored.

This should be reasonably future-proof. If we need to support (2) sometime later, we can add support backwards compatibly. With the API above (where `resolvenested` defaults to `false`), we would then officially document that Stored Request patches will be applied in order from the top down.

**Comment by hhhjort** [comment]
We could easilly have multiple stored request IDs for a request with multiple Imps. Each stored request ID on an imp would just have the scope of that Imp. A stored request ID on the main request, outside of Imp should not modify any Imps (which ones should it modify anyway?) Keeping the stored requests IDs tightly scoped should help avoid confusion when setting up a stored config.

Should we be calling them stored configs rather than stored requests?
