### ISSUE TITLE
OpenRTB endpoint: Config settings not being added to adapter objects

### ISSUE THREAD

**Issue by sandraleon** [prebid/prebid-server#246]
Configuration settings, such as URI, are not being set in new openRTB endpoint. We're unable to retrieve config settings inside of MakeRequests function in adapters.

**Comment by dbemiller** [comment]
Thanks for pointing this out!

You're right. I made a tiny PR which makes the Config accessible at adapter construction time and sent it to you. Let me know if I'm missing something or it doesn't solve your problem.
