### ISSUE TITLE
Add support for Logging rejected bid scenarios using Prebid Analytics Module

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#2466]
There is no way today to log rejected bid information in Prebid Analytics Module. Introduction of this will help

1.  publishers to get insights around Loss Opportunity based on rejection reason
2. sending loss bid url notifications (lurl) to partners to get insights around why there bids lose the auction

**Proposal**
1. Log Pre-filtered Bids along with rejection reason
3. Log Bids which lose the auction with rejection reason
4. Use IAB's standard Loss Reason code - [Refer here](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/OpenRTB%20v3.0%20FINAL.md#list_lossreasoncodes)

**Comment by ShriprasadM** [comment]
@bretg we have already started on these changes. Please let me know Prebid's thoughts on this

**Comment by bretg** [comment]
@ShriprasadM - please post more detail about what you're planning on doing. We've been discussing something similar in https://github.com/prebid/prebid-server/issues/2367

Specifically, please let us know if the no-bid reasons discussed there would cover your desire for a "loss reason code"

**Comment by ShriprasadM** [comment]
@bretg : I could see #2367 is discussing around `no-bid` scenarios. There is difference between what we are implementing

As per my understanding
1. #2367 - comes into picture when either bidder not responds with bid or client (PBS here) time outs
2. Our proposal - comes into picture after bidder returns the bid

## Proposal - for Logging Rejected Bids on PBS Side (We are working on)
So, we introducing RejectedBids array within Analytics Auction Objects as follows
```go
// RejectedBid contains oRTB Bid object with
// rejection reason and seat information
type RejectedBid struct {
	RejectionReason int  // standard IAB Bid Loss Reason code
	Bid             *openrtb2.Bid
	Seat            string
}

// LoggableAuctionObject contains common attributes
type LoggableAuctionObject struct {    // Proposed Abstraction
	Context      context.Context
	Status       int
	Errors       []error
	Request      *openrtb2.BidRequest
	Response     *openrtb2.BidResponse
	RejectedBids []RejectedBid
}
```

Using `go auctionRequest. LoggableObject`, PBS auction module can update `RejectedBids` array when rejection happens. Today, PBS can reject the bids in following cases. Also mentioning mapped [IAB standard bid loss reason codes ](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/OpenRTB%20v3.0%20FINAL.md#list_lossreasoncodes)

| PBS Rejection | IAB Bid Loss Reason Code |
| ------------- | ------------- |
| Bid was Below Auction Floor | 100 |
| Bid was Below Deal Floor | 101 |
| Lost to Higher Bid | 102 |
| Lost to a Bid for a Deal | 103 |
| Category Mapping |  ? TBD. There is no standard Loss Reason Code IAB have for it. May be PBS can define its own error code |


## Proposal for Logging No Bid Scenarios on PBS 
```go
type NoBid struct {
	NoBidReason int 
	Bid         *openrtb2.Bid
	Seat        string
}

// LoggableAuctionObject contains common attributes
type LoggableAuctionObject struct {    // Proposed Abstraction
	Context      context.Context
	Status       int
	Errors       []error
	Request      *openrtb2.BidRequest
	Response     *openrtb2.BidResponse
	NoBids       []NoBid
}
```
Using `go auctionRequest. LoggableObject`, PBS auction module can update `NoBids ` array when either bidder responds with `nbr` or PBS interrupts the connection because of timeout. IAB have already defined list of [IAB no bid reason codes](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/OpenRTB%20v3.0%20FINAL.md#list--no-bid-reason-codes-)


## Updated Analytics Log Objects to enable auction module to update LoggableAuctionObject
```go
//Loggable object of a transaction at /openrtb2/auction endpoint
type AuctionObject struct {
	LoggableAuctionObject // Proposed refactoring
	Account   *config.Account
	StartTime time.Time
}

//Loggable object of a transaction at /openrtb2/amp endpoint
type AmpObject struct {
	LoggableAuctionObject  // Proposed refactoring
	AmpTargetingValues map[string]string
	Origin             string
	StartTime          time.Time
}

//Loggable object of a transaction at /openrtb2/video endpoint
type VideoObject struct {
	LoggableAuctionObject  // Proposed refactoring
	VideoRequest  *openrtb_ext.BidRequestVideo
	VideoResponse *openrtb_ext.BidResponseVideo
	StartTime     time.Time
}

// Enabled Auction Request to pass LoggableAuctionObject object
auctionRequest := exchange.AuctionRequest{
     LoggableObject:             &ao.LoggableAuctionObject,
}
```

**Comment by bretg** [comment]
> https://github.com/prebid/prebid-server/issues/2367 is discussing around no-bid scenarios

Not quite - it's a generic "non-bid" proposal that covers **everything that doesn't result in a seatbid**. See the table in https://github.com/prebid/prebid-server/issues/2367#issuecomment-1299097069 -- codes 300-355 cover response rejection.

Points to consider:
- both server- and client-side analytics adapters will have access to this more comprehensive result
- IAB loss codes 102 and 103 are not relevant -- PBS doesn't pick the winner
- we could add the 'Bid Below Deal Floor' scenario to the code list if desired

I believe @SyntaxNode is out this week, but would like to get his take before you guys get too deep into this.

**Comment by ShriprasadM** [comment]
Thanks @bretg for an update. Can you, @SyntaxNode and my team connect over our proposal when @SyntaxNode  is available, tomorrow (Friday) if possible?

**Comment by hhhjort** [comment]
Does PBS enforce any floors? I don't recall that it does, and a quick scan through the code I cannot find anything beyond basic validation such as required fields exist and bid prices are positive numbers. The targeting key code will prune bids from being used to generate the targeting keys, but the original bids should still be in the body of the bid response. If my memory of this is correct, analytics has access to all the bids, and should be able to replicate the targeting key logic if that is the bid rejection mechanism you are trying to log.

**Comment by ShriprasadM** [comment]
@hhhjort - Floors project is in progress. We (PubMatic) are working on it https://github.com/prebid/prebid-server/pull/2341

Around pruning of bids - 
1.  the original bids should still be in the body of the bid response - This is correct, expect for pre filtered bids - Floors Enforcement (In Progress), Category Mapping 
2.   analytics has access to all the bids - It don't have access to pre-filtered bids, because analytics is called in respective auction.go files. e.g.  [openrtb/auction.go](https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/auction.go#L154). That is what our proposal. To enable analytics has access to all the bids

**Comment by ShriprasadM** [comment]
@bretg  / @SyntaxNode : Please let us know when Can we connect around it.

**Comment by ShriprasadM** [comment]
@bretg / @SyntaxNode  : any update here

**Comment by bretg** [comment]
As discussed in our meeting, please update your proposal to utilize the `seatnonbid` concept and codes rather than separate loss, reject, and other codes.

For PBS-Java, we're going to phase this in:
- initially, PBS-core will only report a few higher level status codes
- the bid adapter interface will be expanded to be able to report seatnonbid codes
- over 1Q23, it will be capable of generating more specific seatnonbid codes

It would be great if Pubmatic could help build this out for PBS-Go.

**Comment by ShriprasadM** [comment]
@SyntaxNode : I have question around [object-nonbid](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/2c3bf2bb2bc81ce0b5260f2e82c59938ea05b74a/extensions/community_extensions/seat-non-bid.md#object-nonbid)

Use case
1. Bid got rejected because of  Below Floor
2. It will be represented by  `301 | Response Rejected - Below Floor`  error code as per your [proposal](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/2c3bf2bb2bc81ce0b5260f2e82c59938ea05b74a/extensions/community_extensions/seat-non-bid.md#object-nonbid)
3. So NonBid Object in this case would look like 
```go
{ 
   "impId" : "some_imp_id",
  "statuscode" : 301
}
```
4. Here, publisher is now interested in knowing what was the bid price associated with this bid. How can we represent this information `nonbid` object?
5. How do you see introducing `bid` object with `nonbid` instead. It will make it more generalise. Because, publisher may be interested in one more attributes and its values to determine why the bid was rejected

**Comment by bretg** [comment]
@ShriprasadM - I updated https://github.com/prebid/prebid-server/issues/2367 with a proposal to add ORTB bid fields to the nonbid object.

**Comment by ashishshinde-pubm** [comment]
We see following use-cases for which non-bid-status code not exist in the proposal. 

| Non Bid Status Code | Non Bid Reason | Use case |
|--------|--------|--------|
| 304 | Response Rejected - Below Deal Floor | If bid response of deal is rejected because the price of deal bid is less than price of floor deal |
| 305 | Response Rejected - Lost To Higher Bid | If bid response if rejected because bid lost to high price bid |
| 306 | Response Rejected - Lost To Deal Bid | If bid response if rejected because bid lost to deal bid | 
| 356 | Response Rejected - Invalid Creative (Advertiser Blocked) | If bid response is rejected because the bid is from the advertiser mentioned in the badv |
|357 | Response Rejected - Invalid Creative (Category Exclusion) | If bid is rejected for ad-pod because adding bid violets the Cross-Pod-IAB-Category-Exclusion-Percent |

**Comment by bretg** [comment]
- Below deal floor: Deal-specific floors are not currently supported in PBS. I suppose it wouldn't hurt to reserve the number 304, but it won't be set by PBS until the floors feature is enhanced.
- Losing, whether to higher or deal bid, is not determined in Prebid Server. PBS doesn't choose the winner - that's the job of the ad server. Because of this, there's no backflow of loss notification to bidders - why would analytics adapters want to know when the bidders themselves don't?
- 356: what's the difference between this (Advertiser Blocked) and 355 (Advertiser Exclusions)?
- Category Exclusion seems fine. Though again, it's unclear that Prebid Server can actually set this value -- maybe in long form or a future module though.

**Comment by bretg** [comment]
@SyntaxNode is minding the status code proposal...

**Comment by SyntaxNode** [comment]
I updated the [IAB extension proposal](https://github.com/InteractiveAdvertisingBureau/openrtb/pull/115) to include the new enum values we agreed upon. Please look there for the current "source of truth" for this spec.

**Comment by bretg** [comment]
@ShriprasadM - may we close this issue now that the seatnonbid issue is near completion?

**Comment by ShriprasadM** [comment]
Closing this issue, because mentioned requirements are now available in [Seat Non Bid](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/seat-non-bid.md) community extension.

**Comment by ShriprasadM** [comment]
Closing this issue, because mentioned requirements are now available in [Seat Non Bid](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/seat-non-bid.md) community extension.
