### ISSUE TITLE
Question about response json format from openrtb2/auction endpoint.

### ISSUE THREAD

**Issue by m4292007** [prebid/prebid-server#2471]
Hi, Team. 

I'm coding a prebid server bidder  follow  the guide in [https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html](docs.prebid.org).
I want to know the http response json format from openrtb2/auction in pbs.

1. I send http request to local pbs 
`curl --location --request POST 'http://localhost:8000/openrtb2/auction' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wva2JvcHBpbmcuY29tIiwiaWF0IjoxNjEwOTEwODU5LCJuYmYiOjE2MTA5MTA4NTksImV4cCI6MTY0MjQ0Njg1OSwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMSJ9fX0.ocSe6jlmO7m1laUxbpR51feXqTUv-5SZQm1cr-sgdgI' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "id": "123456789",
  "test": 0,
  "site": {
    "page": "mytest.org"
  },
  "imp": [{
    "id": "imp-12345",
    "banner": {
      "format": [{
        "w": 300,
        "h": 250
      }, {
        "w": 300,
        "h": 600
      }]
    },
    "ext": {
      "prebid": {
        "bidder": {
          "mytest": {
	         "adspaceid": "1234",
                       "pubid": "1234"
          }
        }
      }
    }
  }],
  "tmax": 500
}'

2. response from pbs is below
`
{
    "id": "123456789",
    "ext": {
        "warnings": {
            "general": [
                {
                    "code": 10002,
                    "message": "debug turned off for account"
                }
            ]
        },
        "responsetimemillis": {
            "mytest": 156
        },
        "tmaxrequest": 500,
        "prebid": {
            "auctiontimestamp": 1669636373472
        }
    }
}
`
I expect that same reponse json format in prebid.js's bidder adapter  like,
`
{
	"input": {
		"bidder": "mybidder",
		"params": {
			"inventoryCode": "mytest_Desktop_Article_580x327_1"
		}
	},
	"bidResponse": {
		"eventType": "bidResponse",
		"args": {
			"bidderCode": "mybidder",
			"width": 300,
			"height": 250,
			"statusMessage": "Bid available",
			"adId": "466d7d7ce3fc0d4",
			"requestId": "109685417bebf9d",
			"transactionId": "beda73d4-bb11-42de-b7b4-0afb864023f1",
			"auctionId": "4b714ce1-48e7-4431-806c-e43c495be125",
			"mediaType": "banner",
			"source": "client",
			"cpm": 0.033,
			"netRevenue": true,
			"ad": "<script>...</script>",
			"creativeId": "2711_76920_10845106",
			"dealId": "",
			"currency": "USD",
			"ttl": 300,
    ....
`

How can I modify code or configuration in pbs to get the above results?
Or 
Is the responses between pbjs from pbjs bidder and pbjs from pbs bidder is diffrent?

Thank you

**Comment by bretg** [comment]
Prebid Server is pure OpenRTB, so it won't look exactly like Prebid.js. Comments:

1. I suggest adding "test":1 to your input request and allowing debug. That will tell you more of what's happening inside.
2. You bid adapter supplies bid responses to PBS-core according to the API defined here https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html
3. Based on the response you received, my guess is that you haven't actually enabled the `mytest` adapter on your PBS instance.

**Comment by m4292007** [comment]
Thank you for your advice.
I'll do more check the my prebid bidder and relevant parameters.
