### ISSUE TITLE
Default to imp.secure:1

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2478]
Both PBS-Go and PBS-Java have pretty reasonable approaches to the imp.secure flag, but it's causing a problem.

Both platforms inject imp.secure:1 if called with HTTPS, but do nothing if called with HTTP.

We have a scenario where an upstream server (PSP in this case) is calling PBS with HTTP but the end client is secure. Since ORTB says specifically that the default for imp.secure is 0, the Magnite exchange assumes non-secure.

In this day and age, however, the ORTB default is out of step with reality, but it's far easier to change Prebid Server to make the default imp.secure be '1' than to get all exchanges to update their defaults.

Proposed algorithm:
1. For each imp, if the incoming request (or stored request) contains imp[].secure, leave it.
2. Otherwise, inject imp[].secure:1 before sending to adapters.

**Comment by bretg** [comment]
released with PBS-Java 1.107

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.244.0.
