### ISSUE TITLE
Add instance level enable_events config

### ISSUE THREAD

**Issue by shahinrahbariasl** [prebid/prebid-server#2479]
Currently events such as imp and win  can be enabled in Prebid Server using stored accounts (by setting `enable_events`) on accounts level. This requires a new stored account to be created for every new account. However we can move `enable_events` config to instance level. That way if hosting PBS, events tracking can be enabled/disabled for all accounts. 

More info:
PBS event handler checks for events being enabled: https://github.com/prebid/prebid-server/blob/5cc5da91f517b79b6b7d2182994bb57d38813918/endpoints/events/event.go#L108

**Comment by bretg** [comment]
@shahinrahbariasl - I'm ok with a host-level flag, but it would be overridden by account-level config. The order of precedence we use in PBS is

1. request-level params
2. account-level config
3. host-level config
4. hardcoded defaults

If you want to deviate from this convention for this use case, please explain the scenario

**Comment by ShriprasadM** [comment]
@bretg  we are working on https://github.com/prebid/prebid-server/issues/1725. As a part of this thing we have introduced events.enabled flag and planning to deprecate accounts.events_enabled flag (As per #3 - https://docs.google.com/document/d/1tH6I9Vho-_KaUIGNCMum9JwbxHDc0FyG2wD8T-h3wkY/edit mentioned here))

**Comment by shahinrahbariasl** [comment]
Hi @bretg and @ShriprasadM , I was thinking more like the other way which would be instance level flag taking precedence since the use case I'm trying to tackle is, when hosting PBS, we would want to enable events for all accounts without the need to update the existing stored accounts or create new ones. I had a draft PR which I just mentioned in this issue and the logic I was thinking was more like:
```
if !account.EventsEnabled && !e.Cfg.Event.Enabled {
		...
                // not enabled
		return
	}
```

If we want to make stored accounts override instance level, the current config is `enable_event` so I think that should be negated to have a config that disables events but that's a bit out of the scope that I was hoping for and also it would require changing the existing stored accounts. Or we could add a new field to stored account to disable events? but again, that'd be confusing with the existing `enable_event` account config.

With the above logic, in case someone needs to disable events for an account, they can then remove the instance level config and manage the events per account with stored accounts.

Let me know what you think or if I'm missing something.

**Comment by shahinrahbariasl** [comment]
Ok was able to make stored account override instance level by changing stored account event flag to *bool instead of bool so that we can distinguish between nil and false values: https://github.com/prebid/prebid-server/pull/2509

**Comment by bsardo** [comment]
@ShriprasadM I see you referenced #1725 above and I originally thought this issue and PR #2533 were related to that but it appears you're just looking to make a stopgap change by making an adjustment to a field (`accounts.events_enabled`) you intend to deprecate as part of the #1725 plan, is that correct?
