### ISSUE TITLE
Question: Understanding SupportDeals(PBS), PreferDeals (PBS), SupportDeals (PBS), dealPrioritization (PBJS), prioritizeDeals(PBJS)

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#2490]
@bretg / @SyntaxNode  / PrebidTeam , can you confirm if following understanding is correct?

| Use Case  | Should pass following params and configs in  PBS go | Should pass following params and configs  PB JS | Should use following keys in Ad Server Targeting  |
| ------------- | ------------- | ------------- | ------------- |
| Deal Prioritisation for Long Form Video (LFV) | <img width="313" alt="image" src="https://user-images.githubusercontent.com/9314645/206712606-ba2f5ad0-1329-4ceb-8658-cd85eaaae211.png"> https://github.com/prebid/prebid-server/issues/1174 | <img width="260" alt="image" src="https://user-images.githubusercontent.com/9314645/206712666-4dcfaf6e-7206-4181-9200-138832b14ebf.png"> https://docs.prebid.org/dev-docs/modules/adpod.html#cpm-adjustments-by-deal-tier-for-csai |  ```hb_pb_cat_dur``` https://docs.prebid.org/prebid-video/video-long-form.html#deal-support |
| Prefer Deals - In Prebid Auction only | ```ext.prebid.targeting.preferdeals: true``` https://github.com/prebid/prebid-server/issues/1355  https://github.com/prebid/prebid-server/pull/1528 | ```dealPrioritization: true``` https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html | ```hb_deal``` https://docs.prebid.org/adops/deals.html#deal-key-value-pairs |
| For LFV - To  Prefer and prioritise deals  |  ``` support deals = true,  preferdeals = true ``` |  ```priortizedeals:true, dealPrioritization:true``` | ```hb_pb_cat_dur``` |
| Prefer Non-LFV Prefer and prioritise deals |  ```preferdeals = true ``` | ```dealPrioritization:true``` |. ```hb_deal``` |

**Comment by ShriprasadM** [comment]
Thanks @bretg  for an update. @SyntaxNode  can you update on LFV part?

Another Question: What is the way one can prioritise the deals for non-lfv (banner, native) using existing flags, in both the cases server side and JS side? @bretg  / @SyntaxNode

**Comment by bretg** [comment]
> What is the way one can prioritise the deals for non-lfv (banner, native) using existing flags, in both the cases server side and JS side?

There's not a silver bullet here. 

1) PBJS - https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#configure-send-bids-control
```
pbjs.setConfig({
  sendBidsControl: {
    dealPrioritization: true
  }
});
```

2) PBS invoked from Prebid.js
```
pbjs.setConfig({
  s2sConfig: {
     ...
     extPrebid: {
         targeting: {
             preferdeals: true
         }
     }
  }
});
```
It wouldn't be impossible to have the PBS bid adapter add this logic when sendBidsControl. dealPrioritization is set.

3) PBS invoked from SDK

host company needs to add ext.prebid.targeting. preferdeals: true to the 'top-level' stored request

4) PBS invoked from AMP

host company needs to add ext.prebid.targeting. preferdeals: true in the AMP stored request

**Comment by ShriprasadM** [comment]
Thanks @bretg. 
1. Which targeting key, should be used to prioritise deals on GAM side in case of non-lfv format?

**Comment by bretg** [comment]
> Which targeting key, should be used to prioritise deals on GAM side in case of non-lfv format?

Not following the question @ShriprasadM .

Prebid.js sends the hb_deal (or hb_deal_BIDDER) key-value pair to GAM. That's it.

Prioritizing in GAM is in how you set up the line items. https://docs.prebid.org/adops/deals.html

**Comment by bretg** [comment]
What's left on this issue @ShriprasadM ?

**Comment by bretg** [comment]
Are we good here @ShriprasadM ?

Deal support on the /video endpoint is a separate thing, not related to deal support on the main /auction endpoint. The /video endpoint is deprecated.

**Comment by ShriprasadM** [comment]
Yes @bretg . Thanks.
