### ISSUE TITLE
OpenRTB Support: Metrics

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#250]
The `/openrtb2/auction` endpoints have no `go-metrics` yet.

We'll want to add these before the endpoints get used in any prod scenario, so that we can make sure that similar number & prices of bids are coming back as they do for the `/auction` endpoint.

**Comment by dbemiller** [comment]
This may overlap with #259, depending on the analytics design.

**Comment by hhhjort** [comment]
This is now in a PR: #275

**Comment by dbemiller** [comment]
Fixed in #275, which is now merged.
