### ISSUE TITLE
got errors running validate.sh

### ISSUE THREAD

**Issue by shunj-nb** [prebid/prebid-server#2551]
attached errors:
➜  prebid-server git:(master) ./validate.sh
endpoints/openrtb2/amp_auction_test.go:2013:53: missing ',' in composite literal
endpoints/openrtb2/amp_auction_test.go:2016:14: expected expression
endpoints/openrtb2/amp_auction_test.go:2023:14: expected expression
endpoints/openrtb2/amp_auction_test.go:2028:19: expected ';', found ':'
endpoints/openrtb2/auction_test.go:4806:51: missing ',' in composite literal
endpoints/openrtb2/auction_test.go:4809:12: expected expression
endpoints/openrtb2/auction_test.go:4814:4: expected operand, found '{'
endpoints/openrtb2/auction_test.go:4869:2: expected ';', found 'for'
endpoints/openrtb2/test_utils.go:1442:41: expected ';', found '['
endpoints/openrtb2/test_utils.go:1452:2: expected '}', found 'return'
endpoints/openrtb2/test_utils.go:1456:2: expected declaration, found 'return'
endpoints/openrtb2/test_utils.go:1502:53: expected type, found ','
endpoints/openrtb2/test_utils.go:1503:2: expected 'IDENT', found 'return'
endpoints/openrtb2/test_utils.go:1504:1: expected 'IDENT', found '}'
endpoints/openrtb2/test_utils.go:1506:1: missing ',' in parameter list
endpoints/openrtb2/test_utils.go:1511:2: expected declaration, found 'return'
endpoints/openrtb2/test_utils.go:1550:77: expected ';', found '{'
endpoints/openrtb2/test_utils.go:1561:5: expected declaration, found 'return'
endpoints/openrtb2/test_utils.go:1572:88: expected ';', found '{'
exchange/exchange_test.go:5093:105: expected ';', found '['
exchange/exchange_test.go:5094:2: expected declaration, found 'return'
exchange/exchange_test.go:5120:205: expected type, found ','
exchange/exchange_test.go:5121:6: expected type, found '.'
exchange/exchange_test.go:5122:2: expected declaration, found c
hooks/empty_plan.go:12:71: expected ';', found '['
hooks/empty_plan.go:13:2: expected declaration, found 'return'
hooks/hookexecution/execution.go:15:21: expected ']', found any
hooks/hookexecution/execution.go:22:20: expected ']', found any
hooks/hookexecution/execution.go:64:2: expected declaration, found rejected
hooks/hookexecution/execution.go:172:24: expected '(', found '['
hooks/hookexecution/execution.go:173:6: missing ',' in parameter list
hooks/hookexecution/execution.go:174:10: missing ',' in parameter list
hooks/hookexecution/execution.go:175:5: missing ',' in parameter list
hooks/hookexecution/execution.go:176:15: missing ',' in parameter list
hooks/hookexecution/execution.go:206:21: expected '(', found '['
hooks/hookexecution/execution.go:207:5: missing ',' in parameter list
hooks/hookexecution/execution.go:208:14: missing ',' in parameter list
hooks/hookexecution/executor.go:90:13: expected expression
hooks/hookexecution/executor.go:95:54: expected type, found ','
hooks/hookexecution/executor.go:96:3: expected 'IDENT', found 'return'

**Comment by SyntaxNode** [comment]
This project requires Go 1.18 and newer. The compilation failures you listed are all related to generics, so you likely have an older version of Go on your machine,

**Comment by shunj-nb** [comment]
I use the latest go version on mac
➜  prebid-server git:(master) go version
go version go1.19.5 darwin/amd64

**Comment by SyntaxNode** [comment]
I cannot reproduce the errors you reported using Go 1.19.5 on darwin/amd64. The errors are related to the use of generics which is supported by that compiler version. There must be something going on with your machine where a different compiler is being used instead.
