### ISSUE TITLE
send contextual data to bidders

### ISSUE THREAD

**Issue by shunj-nb** [prebid/prebid-server#2557]
looks like client segment data and contextual data is added to imp.ext.context.data
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java#L364

but in the latest server change, imp.ext.data is sent to some bidders instead of imp.ext.context.data
https://github.com/prebid/prebid-server/pull/2417

is there any sdk api filling imp.ext.data?

**Comment by bretg** [comment]
@shunj-nb - nothing should be going in `imp.ext.context`. I'll work with the SDK team to sort out where it's adding FPD.

Prebid Server as aligned with Prebid.js on the locations. https://docs.prebid.org/features/firstPartyData.html

**Comment by bretg** [comment]
Opened the issue with the SDK team. Closing this one.

**Comment by bretg** [comment]
@shunj-nb - the SDK team has a fix ready for this -- they'd like to get a sense of priority for whether they should push an SDK patch or whether they can wait until the end of the month for other fixes to be bundled into a release.
