### ISSUE TITLE
Index Exchange does't support Currency Module

### ISSUE THREAD

**Issue by dimention** [prebid/prebid-server#2613]
### Type of issue
Bug

### Description
Index Echange wrote to us: "we currently only support the following currencies: AUD, BRL, CAD, CHF, CNY, EUR, GBP, HKD, JPY, NZD, PLN, SEK, SGD, USD (but not the Prebid module)
Therefore, your bid request will get rejected if it contains another currency.
You can either append USD to the list of currencies in your bid requests or you can also not signal any currency at all, we will then default to USD."

### Steps to reproduce
Set adserver currency (in Prebid.js) to any other than supported by Index Exchange, and the bid request will get rejected on Prebid Server.

### Expected results
If adserver currency is not supported, return bids in USD

### Platform details
Prebid.js 7.27.0
Prebid Server (Go) 0.234.1

**Comment by bretg** [comment]
Adding @ix-prebid-support .

Currency support is supposed to be easy. Bidders can bid in whatever currency they wish, and Prebid.js/Server will convert it to whatever the publisher wants.

However, life isn't always that simple. It's come up before that some bidders don't want to deal with the inevitable finance discrepancies that happen when they bid in one currency and have to pay out in another. Some SSPs support billing on currency X while bidding in currency Y, but perhaps Index doesn't. That could be the reason for them to decline bidding in any but their supported currencies.

**Comment by dimention** [comment]
Hi @bretg , but what can be done to go around this issue? Lets say I want to change the currency that is sent to Prebid Server (as Prebid.js will take care of currency conversion anyways) without changing the adserver currency defined in Prebid.js. As I read in other issues, adding currency to oRTB object sent to Prebid Server won't work, because Currency Module overwrites it.

**Comment by bretg** [comment]
> what can be done to go around this issue?

IMO, you should talk to Index Exchange. If they don't want to deal with finance discrepancies, they might not appreciate workarounds.

> As I read in other issues, adding currency to oRTB object sent to Prebid Server won't work

I thank that was fixed a while back in https://github.com/prebid/Prebid.js/issues/7597

**Comment by bretg** [comment]
We discussed in the Prebid Server committee and agree this is an issue between publisher and adapter. We would advise @ix-prebid-support to update their bidder documentation to note their currency policy.
