### ISSUE TITLE
Stored auction response is returning empty string for bid.ext.prebid.type field

### ISSUE THREAD

**Issue by camrice** [prebid/prebid-server#2614]
When using a request with an `imp.storedauctionresponse.id`, the response will contain an empty `bid.ext.prebid.type` field, even if this field is included in the stored auction response. The response from Prebid Server will instead contain an empty string. Example response below:
```
{
    "bid": {
        ...
        "ext": {
            "appnexus": {
                "auction_id": 4567,
                "bid_ad_type": 3,
                "bidder_id": 2,
                "brand_id": 1
            },
            "origbidcpm": 0,
            "origbidcur": "USD",
            "prebid": {
                "meta": {
                    "adaptercode": "appnexus"
                },
                "type": "",
                "bidid": "af3a5b4b-25d8-4c50-8e72-d7fdf6535382"
            }
        }
    }
}
```

Initial findings below from @VeronikaSolovei9 :

The Prebid type field is present on stored bid responses because these responses will go through `MakeBids()` and will populate the field. In the case of using the Appnexus adapter and a stored auction response, there is a portion that gets missed in `appnexus.go` line 403:

```
bidResponse.Bids = append(bidResponse.Bids, &adapters.TypedBid{
						Bid:          &bid,
						BidType:      bidType,
						BidVideo:     impVideo,
						DealPriority: bidExt.Appnexus.DealPriority,
					})
```

This seems to be needed for the field to work with auction responses.

**Comment by VeronikaSolovei9** [comment]
Thank you Cameron, good finding!

**Comment by camrice** [comment]
Thank you for looking into this Veronika! I'll be in touch for any updates.

**Comment by VeronikaSolovei9** [comment]
Fix PR: https://github.com/prebid/prebid-server/pull/2615

**Comment by camrice** [comment]
Sorry for the late update, but I wanted to confirm that this is now working for our usage. Thank you!

**Comment by bretg** [comment]
Confirmed this is not a problem in PBS-Java.
