### ISSUE TITLE
PBS2.0: bidder contact email

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2626]
This issue tracks one of the [rules](https://docs.prebid.org/dev-docs/module-rules.html) that will be enforced starting with Prebid Server 2.0: bidders must have contact information registered that: (a) works and (b) is a group, not an individual.

 This rule is in place because we need to be able to contact adapter maintainers for various reasons: bug reports, platform changes, and periodic check-ins.

## No working contact info

The following adapters do not have working email aliases:

- [x] acuityads - @AcuityAdsIntegrations 
- [x] adtrgtme - @grakholsky 
- [ ] applogy - @IncSW 
- [x] appush - @nitzanappush 
- [x] brave - @thebraveio 
- [x] colossus - @HuddledMasses 
- [x] definemedia @dennisjay 
- [x] impactify - @thomasdseao 
- [ ] kubient - @mapcuk 
- [x] lunamedia
- [x] madvertise - @notmani 
- [x] medianet - @eshaanmangal 
- [ ] nanointeractive - @nanointeractive 
- [ ] ninthdecimal - @trchandraprakash 
- [x] smartadserver - @tadam75 
- [x] videoheroes - @videoheroes 
- [x] vidoomy - @abdollah-aghayan 
- [x] yeahmobi - @zhaojp
- [x] huaweiads - @clho40 

It's common that companies will set up a distribution group, then forget to allow it to receive external email. This may be the case for some of the entities in this list. Please confirm the contact email you have on file in your ADAPTER.yaml file in https://github.com/prebid/prebid-server/tree/master/static/bidder-info 

## Contact info that needs to be upgraded to a group contact

We can't accept the individual contact that exists for these adapters. Individuals move on to new roles, but Prebid is forever :-)

- [x] alkimi - @pro-nsk
- [x] definemedia - @dennisjay 

Please supply a distribution list like "support@example.com", "prebid@example.com", etc. After making sure that it works, please update your info file in https://github.com/prebid/prebid-server/tree/master/static/bidder-info (or, for alkimi, the PBS-Java equivalent)

**Comment by bretg** [comment]
Thanks to MediaNet for being the first to fix their bouncing contact email!

**Comment by videoheroes** [comment]
Hey Bretg, how we can confirm it ? just to reply to this mail ?

**Comment by grakholsky** [comment]
Hello, @bretg!

We don't have any emails from you. Can you resend it to us at info@adtarget.me?

**Comment by bretg** [comment]
@grakholsky - tried sending email again. Let me know if you received it. Here's the google group message showing that address may not be set up to accept email from the outside

<img width="1283" alt="Screen Shot 2023-03-13 at 9 25 01 AM" src="https://user-images.githubusercontent.com/4412838/224715105-a60fb190-ffd9-4b4f-99ec-ea421d0df433.png">

**Comment by bretg** [comment]
It works now - thanks @grakholsky

**Comment by bretg** [comment]
@videoheroes - did you receive the intro email. Google groups also shows a bouncing status for you guys
<img width="1295" alt="Screen Shot 2023-03-13 at 10 13 30 AM" src="https://user-images.githubusercontent.com/4412838/224727568-9661b33a-7757-42ba-a91a-04f63f1b8407.png">

**Comment by videoheroes** [comment]
Yes, I got it.

**Comment by SyntaxNode** [comment]
Impactify opened https://github.com/prebid/prebid-server/pull/2633 to change their email address, but the new one gives me a delivery error. I left a comment on their PR.

**Comment by pro-nsk** [comment]
Hello @bretg 
I've changed the contact email in alkimi adapter
https://github.com/prebid/prebid-server-java/pull/2232

**Comment by thebraveio** [comment]
Hi @bretg, we have actual domain here "support@thebrave.io", our managers using this address everyday to support partners

**Comment by bretg** [comment]
@thebraveio - did you receive the email I sent you on Feb 16? There was no response, and google groups tells me there's bounces to this address:

<img width="1274" alt="Screen Shot 2023-03-15 at 12 30 37 PM" src="https://user-images.githubusercontent.com/4412838/225377663-1299b211-358d-461a-90f0-d86c65e950ff.png">

**Comment by thebraveio** [comment]
Yes, we got 2 mails (welcome and group in gmail)

**Comment by doomontiu** [comment]
Hi @bretg,

Thanks for checking this point, I am the CTO at Vidoomy, can you resend it so I can validate with my partner who receives the emails, thanks in advance.

**Comment by bretg** [comment]
Email sent to vidoomy. It bounced last summer, and I did get email that the address was repaired, but might not have updated the spreadsheet. Let me know if you receive the email @doomontiu

**Comment by doomontiu** [comment]
@bretg received ! thanks for the update

![Screenshot 2023-03-23 at 18 42 19](https://user-images.githubusercontent.com/114927869/227294876-e3d60dee-1f4e-49dc-8e68-597c2ae6a2d0.png)

**Comment by bretg** [comment]
- AcuityAds has confirmed they're now monitoring the contact address
- SmartAdServer is now Equativ. Opened PRs in both repos to update

**Comment by bretg** [comment]
Heads up @IncSW, @nitzanappush, @mapcuk, @HuddledMasses, @nanointeractive, @trchandraprakash, @zhaojp -- please escalate within your organizations -- we need updated and working contact info or you adapter will be removed from Prebid Server 2.0 in September. Thanks.

**Comment by bretg** [comment]
Got confirmation from colossus about their updated contact info

**Comment by bretg** [comment]
Also - repinging @dennisjay for definemedia. We need a group address.

**Comment by bretg** [comment]
Prebid Server 2.0 is happening this month the following 8 bidders will not part of 2.0 unless they fix their contact email:

- applogy - @IncSW
- appush - @nitzanappush
- definemedia - @dennisjay
- kubient - @mapcuk
- nanointeractive - @nanointeractive
- ninthdecimal - @trchandraprakash
- yeahmobi - @zhaojp
- huaweiads - @clho40

I will also try the email on file one more time.

**Comment by bretg** [comment]
- the applogy.com domain is for sale. I'm going to assume that means we can remove their adapter in 2.0
- emailed the addresses on file for others. NanoInteractive, Huawei and Yeahmobi bounced. The others have not bounced, but they have not replied.

**Comment by bretg** [comment]
Got confirmation from Appush that their email is now working. Thanks!

**Comment by SyntaxNode** [comment]
Implemented in both PBS-Go and PBS-Java 2.0.
