### ISSUE TITLE
OpenRTB endpoint: Modified request object used in MakeBids calls

### ISSUE THREAD

**Issue by sandraleon** [prebid/prebid-server#264]
Current: Given a bidder adapter returns multiple requests from MakeRequests, MakeBids is being called with the last request object returned by MakeRequests.

Expected: Given a bidder adapter returns multiple requests from MakeRequests, MakeBids should be called with the corresponding request object for that response.

**Comment by dbemiller** [comment]
@sandraleon This was fixed in #256, correct?

**Comment by sandraleon** [comment]
@dbemiller yes, will close
