### ISSUE TITLE
Unable to put prebid tags on AMP testpage

### ISSUE THREAD

**Issue by noa-alook** [prebid/prebid-server#2656]
I'm trying to create a valid AMP page with prebid, 
when putting 
`<script async src="https://prebid.adnxs.com/pb.js"></script>`
 in the head
I keep getting this error message when putting the HTML in the AMP validator:
error message= "Custom JavaScript is not allowed"

how can I solve it?

**Comment by bretg** [comment]
Unclear how this is a Prebid Server issue, but here goes... the point of AMP is to reduce mobile web page latency, so it won't allow you to include arbitrary javascript on your page.

The only way to interact with Prebid via AMP is through RTC (Real Time Configuration). See https://docs.prebid.org/formats/amp.html
