### ISSUE TITLE
Support For OpenRTB 2.6-202303

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#2682]
The latest versions of OpenRTB 2.6 and AdCOM 1.0 were released today as [OpenRTB 2.6-202303](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/2.6-202303/2.6.md) and [AdCOM 1.0-202303](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/AdCOMv1.0-202303/AdCOM%20v1.0%20FINAL.md). Changes are:

- Impression Refresh Signals (`imp[].refresh` + `imp[].refresh.refsettings`)
Signals about ad slots being refreshed automatically. Aligns well with existing industry solutions.

- New Video Placement Enumeration (`imp[].video.plcmt`)
Replacement for `imp[].video.placement` with clearer descriptions and an [accompanying guidance documentation](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/implementation.md#710---updated-video-signals).

- Ext Support For Qty (`imp[].qty.ext`)
Oversight from last release when this object was added.

To support these new fields, Prebid Server should pass the signals to bidders and remove them as part of OpenRTB 2.6 -> 2.5 downgrade. The `placement` and `plcmt` enumerations are distinct and should not be mapped between each other. 

I do not believe Prebid Server needs to take special action on these fields.

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.251.0.

**Comment by bretg** [comment]
Done with with PBS-Java 1.119
