### ISSUE TITLE
prebid.adnxs.com is not responding

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#27]
Not sure if I should report this issue here, but it seems that prebid-server is down:

`$ ping prebid.adnxs.com`
PING prebid-ssl.northeurope.cloudapp.azure.com (13.74.186.28) 56(84) bytes of data.

--- prebid-ssl.northeurope.cloudapp.azure.com ping statistics ---
18 packets transmitted, 0 received, 100% packet loss, time 16999ms

**Comment by asweeney86** [comment]
Everything should be back to normal.  Closing for now, if you continue to see errors please re-open.
