### ISSUE TITLE
Investigate shaving the uids cookie

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2706]
Completely refactoring the uids cookie as described in https://github.com/prebid/prebid-server/issues/1985 is a large and delicate project. 

There's interest in seeing whether there's a way to shove a few more IDs into the uids cookie with something simple. e.g.

- trimming the timestamp
- compression
- adding another cookie

**Comment by bretg** [comment]
Discussed in committee:
- host company setting
- round the timestamp to the minute
- need to look into the bday field

Next step:
- investigate savings that could be with timestamp+brotli+uuencode
- discussing adding cookies as a followup
- define specific requirements: rounding rules, versions, behavior when PBS sees something it doesn't immediately understand

**Comment by SyntaxNode** [comment]
PBS-Go research usage of the Birthday field and cannot find any current usage. PBS doesn't read this value, it only writes it. Hosts may use this field, but we can't imagine for what purpose and find this use case negligible.

PBS-Java to confirm it's safe to remove the Birthday field.

**Comment by And1sS** [comment]
@SyntaxNode PBS-Java doesn't use this field too.

**Comment by SyntaxNode** [comment]
@And1sS Thank you for confirming. We'll proceed to remove the birthday field since it has no known usage.

**Comment by SyntaxNode** [comment]
Discussed in the Prebid Server Committee if rounding the timestamp to the minute could be a quick win.

PBS-Go uses RFC3339 encoding with second precision for the timestamp. Its invalid to encode a time with hours and minutes but without seconds using this specification. Rounding may still provide a benefit when paired with a compression algorithm to reduce space by lowering the entropy of the timestamp.

PBS-Java also follows RFC3339 encoding with milli-second precision. It might be a quick win for PBS-Java to reduce timestamps to second precision to save 4 characters per entry. Based on the examples in https://github.com/prebid/prebid-server/issues/1985, this would allow for one additional user sync to be stored.

Removing the birthday saves 40 characters for PBS-Go and 38 characters in PBS-Java. This is not enough savings to store an additional user sync, but it might allow one additional user sync in the right circumstance.

**Comment by bretg** [comment]
Setting 'ready-for-dev' assuming this issue tracks just the removal of the bday timestamp.

**Comment by bretg** [comment]
Released with PBS-Java 1.121
