### ISSUE TITLE
Rubicon cookie sync not working in local/custom prebid server

### ISSUE THREAD

**Issue by alexmrf** [prebid/prebid-server#272]
As far as i understand, in the cookie sync phase, when prebid-server detects that the user does not have a cookie relation between rubicon and the user makes a request to a rubicon endpoint:

`https://pixel.rubiconproject.com/exchange/sync.php?p=prebid`

This endpoint responds with a redirect:

`https://prebid.adnxs.com/pbs/v1/setuid?bidder=rubicon&uid=JBRTV4C7-14-59K4`

I guess that this redirect sets the user uid in the prebid-server but instead of sending it to my local prebid-server is sending it to the one hosted by adnxs.

**Comment by dbemiller** [comment]
@DucChau Does Rubicon's usersync endpoint accept a PBS domain somehow?

If so, you'll just need to overwrite the [default config value](https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L716). If not, Rubicon will need to make their endpoint more flexible before anything can be done in PBS.

**Comment by DucChau** [comment]
@alexmrf Rubicon Project supports the redirection. We require companies looking to do cookie syncing with us to register their redirect URL with us. After you register the URL we will hand you a key that you can use in the "p" parameter of the sync URL.

Example: 

1. you register http://www.foo.com/usersync with us
2. we tell you the key is "foo"
3. https://pixel.rubiconproject.com/exchange/sync.php?p=foo when called will set the uid and redirect to the URL you registered with us in step 1 (http://www.foo.com/usersync) with the uid

You can send an email to header-bidding@rubiconproject.com to register your redirect URL with us.

**Comment by dbemiller** [comment]
For now, how about `docs/developers/bidders/rubicon.md`?

Other bidders can put their own special instructions in similarly named files.

**Comment by alexmrf** [comment]
@DucChau Thank you very much! We will do so.

**Comment by DucChau** [comment]
I like `docs/bidders/rubicon.md` since I feel like it can be a catch all for all things exchange related...versus just developer centric notes.

**Comment by bretg** [comment]
Thanks @dbemiller
