### ISSUE TITLE
Account specific fetchRate to select source of floors

### ISSUE THREAD

**Issue by pm-jaydeep-mohite** [prebid/prebid-server#2755]
This proposal is for selecting source of floors i.e. fetched dynamically or from request req.ext.prebid.floors.

**Issue**

As per  floors feature PRD https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0, If floors data is fetched successfully then it should be used and due to this fetched floors data will get used for 100% of the requests. 
There is no option to use fetched floors data for limited requests (e.g. 50%) and static floors data from req.ext.prebid.floors for remaining requests (i.e. 50%)

**Proposal**

We can have account specific fetchRate  to select source floors from dynamically fetched data and from request.
Range of valid values can be 0 to 100, 0 means do not use fetched data and 100 means use fetched floors data for all the requests. 
Default value : 0

**Comment by bretg** [comment]
PRD updated with fetch.use-data-rate feature. https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0/edit#heading=h.yglzagui7gzp

**Comment by pm-jaydeep-mohite** [comment]
Can we have some field in floors JSON to control source of floors i.e. req.ext.prebid.floors.dataRate ? 

This would help in updating data rate through dynamically updated floors data, consume updated dataRate dynamically  and no need to update account config as per updated floors data. 

Having data-rate at account config and floors data would be same as existing enforceRate field.

**Comment by bretg** [comment]
@pm-jaydeep-mohite - sorry, I'm not following. You want both dataRate and fetchRate? This feature is already complicated as it is. Please simplify and propose a _minimal_ working solution for your use case.

**Comment by pm-jaydeep-mohite** [comment]
In current PRD version, we have dataRate which is account level config parameter.
and dataRate should be adjusted based on stability/confidence of dynamically fetched floors data generator. 
Suppose, if floors provider is confident to use dynamically fetched floors for 100% (from 5%) of traffic then floors provider can intimate in floors JSON than prebid server maintainer updating account config to change it to 100 (from 5). 
To avoid this manual process of updating dataRate in account configuration, we can have dataRate as part of floors data i.e. req.ext.prebid.floors.dataRate so that dynamically fetched floors can update this value based on confidence of floors provider. 

If the value of dataRate is not provided then default value 100  shall be considered to be backward compatible. 
Field dataRate should be considered only from dynamically fetched floors data  and in case of floors data provided in req.ext.prebid.floors, dataRate should be ignored

**Comment by bretg** [comment]
Thanks, but I'm going to push back on this as overly complicated.  If `fetchRate` is a publisher control that essentially indicates they don't fully trust the provider, then it doesn't make sense for the provider to be able to override that.

**Comment by bretg** [comment]
I'm going to challenge you a bit more on this. The feature doesn't seem useful to me.

I get why a publisher might want to ease into fetched data, but why would a floors provider say "Only use my data X% of the time." ? It seems similar to "skip rate". How would analytics know which data is used? How would a floors provider know when to change this value?

**Comment by bretg** [comment]
Very well. The analytics adapter could use ext.prebid.floors.location to tell whether 'request' or 'fetch' floors were used. 
- updated the [PRD](https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0/edit) to remove the account-level 'use-data-rate' and replaced it with data.useFetchDataRate
- updated the [published](https://github.com/prebid/prebid.github.io/pull/4643) "Schema 2" with the new optional data.useFetchDataRate

Please  review both documents to make sure this is what you want. Would prefer not to have make another round of changes here.

**Comment by bretg** [comment]
Can we close this issue @pm-jaydeep-mohite ?

**Comment by bretg** [comment]
Released with PBS-Java 3.15
