### ISSUE TITLE
Remove deprecated bid adapters

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2764]
These adapters known to be no longer in use and should be removed from PBS 2.0

- [ ] rhythmone
- [ ] engagebdr
- [ ] applogy

**Comment by SyntaxNode** [comment]
Discussed in Backlog Review that these adapters are safe to be removed prior to PBS 2.0.

**Comment by bretg** [comment]
Removed emx_digital from the list -- Cadent has made this an alias in PBS-Go, and will be doing so in PBS-Java 'soon'.

**Comment by bretg** [comment]
Fixed. Thanks @SyntaxNode . applogy.com is for sale.

**Comment by SyntaxNode** [comment]
Implemented in both PBS-Go and PBS-Java 2.0.
