### ISSUE TITLE
Support storedbidresponses mixed with live auctions

### ISSUE THREAD

**Issue by shunj-nb** [prebid/prebid-server#2801]
We found  storedbidresponse feature in this page https://github.com/prebid/prebid-server/issues/861.
 
Multiple Stored Bid Response IDs
In contrast, this approach lets some real auctions take place while some bidders have test responses that still exercise bidder code.

We tested with the below request and it doesn't work because of this validation https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/auction.go#L2333. What we want is returning the configured response for pubmatic and real auction for rubicon. Is there anything wrong with our request?
`{
  "banner": {
    "format": [
      {
        "w": 300,
        "h": 250
      },
      {
        "w": 300,
        "h": 600
      }
    ]
  },
  "ext": {
    "pubmatic": {
      "publisherId": "testid",
      "adSlot": "testid"
    },
    "rubicon": {
       "accountId": 1111,
      "siteId": 22222,
      "zoneId": 3333 
    },
    "prebid": {
     "storedbidresponse": [{
        "bidder": "pubmatic",
        "id": "configured_stored_imp_on_db"
     }]
    }
  }
}`

**Comment by bsardo** [comment]
Hi @shunj-nb,

The stored bid response feature doesn't exactly support what you're trying to do. You can't specify multiple bidders for the same impression expecting one of the bidders to return a stored response while the other results in a bid request. In this scenario, the presence of the stored bid response in the request takes precedence which means it will be the only bid response you receive.

However, you can specify multiple impressions where all of the bidders for a given impression are meant to either fetch a stored response or all are meant to result in bid requests.
For example, something like this might suffice:
```
{
    "banner": {
        "format": [{
            "w": 300,
            "h": 250
        }, {
            "w": 300,
            "h": 600
        }]
    },
    "ext": {
        "pubmatic": {
            "publisherId": "testid",
            "adSlot": "testid"
        },
        "prebid": {
            "storedbidresponse": [{
                "bidder": "pubmatic",
                "id": "configured_stored_imp_on_db"
            }]
        }
    }
},
{
    "banner": {
        "format": [{
            "w": 300,
            "h": 250
        }, {
            "w": 300,
            "h": 600
        }]
    },
    "ext": {
        "rubicon": {
            "accountId": 1111,
            "siteId": 22222,
            "zoneId": 3333
        }
    }
}
```

I hope that helps.

**Comment by bretg** [comment]
Discussed in committee:
- we agree that storedbidresponses should ideally be able to support a mix of debug and live auctions, but that this is fairly low priority
- storedauctionresponses are different - they contain bid responses from all bidders and therefore skip the live auction entirely

**Comment by bretg** [comment]
@shunj-nb - does the above answer your question? What is the use case for mixing debug and live auctions? This is very low priority from our current perspective.

**Comment by bretg** [comment]
Closing this enhancement request. You're welcome to submit a community contribution.
