### ISSUE TITLE
Vendor exceptions doesn't allow bidding for no GVLID bidder

### ISSUE THREAD

**Issue by balintvargha** [prebid/prebid-server#2809]
Dear Prebid Team!

According to the documentation we should be able to add bidders to the vendor exceptions list based on purpose to allow them to bid. We would like to do this with a bidder who has no gvlid. This is what we're trying to do:

    account_required: false

    gdpr:
     default_value: 1
     timeouts_ms:
      init_vendorlist_fetches: 5000
      active_vendorlist_fetch: 5000

     tcf2:
      purpose1:
       vendor_exceptions:
       - {bidder_name}
      purpose2:
       vendor_exceptions:
       - {bidder_name}
      purpose3:
       vendor_exceptions:
       - {bidder_name}
      purpose4:
       vendor_exceptions:
       - {bidder_name}
      purpose5:
       vendor_exceptions:
       - {bidder_name}
      purpose6:
       vendor_exceptions:
       - {bidder_name}
      purpose7:
       vendor_exceptions:
       - {bidder_name}
      purpose8:
       vendor_exceptions:
       - {bidder_name}
      purpose9:
       vendor_exceptions:
       - {bidder_name}
      purpose10:
       vendor_exceptions:
       - {bidder_name}

Is there something we are missing? Do we interpret the functional requirements incorrectly or is this something that has not yet been implemented? Or the most probable, are we messing something up? Thank you for your help in advance.

**Comment by bretg** [comment]
FYI - PBS-Java supports string bidder names in privacy.gdpr.purposes.[p1-p10].vendor-exceptions

**Comment by bsardo** [comment]
Hi @balintvargha, thanks for your patience. There is indeed a bug in PBS-Go regarding how bidders with no vendor ID are handled. For these types of bidders, if the bidder is entered as a vendor exception, they should pass the purpose.

I'll push up a fix shortly.

**Comment by bretg** [comment]
Adding @SyntaxNode since bsardo is on leave.

**Comment by SyntaxNode** [comment]
Fixed in PBS-Go 0.266.0. @balintvargha Please confirm the fix looks good to you.

**Comment by balintvargha** [comment]
Confirmed. Looks good to me! Thanks for the fix.
