### ISSUE TITLE
Bid adapter native response issue

### ISSUE THREAD

**Issue by PBDMSFT** [prebid/prebid-server#2812]
The native root object was removed from bid responses in native specifications 1.1 and 1.2, however, some bidders still include it in their responses even when using those versions of the spec.

Prebid Server should strip the native root object from bid responses before passing bids along.  We built handling for this in Xandr's platform but ideally it would be part of Prebid Server itself.

v1.0 https://iabtechlab.com/wp-content/uploads/2016/02/OpenRTB-Native-Ads-Specification-1_0-Final.pdf

v1.1 https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-Native-Ads-Specification-1-1_2016.pdf

v1.2 https://www.iab.com/wp-content/uploads/2018/03/OpenRTB-Native-Ads-Specification-Final-1.2.pdf

**Comment by mansinahar** [comment]
Thanks for bringing this up @PDXandr. Just to clarify it for others, the `native` root object being talked about here is the one in `bid.adm`. 

I agree that the situation mentioned here isn't ideal. However, I am hesitant to add code in Prebid Server to fix this as this violates openrtb native spec. I think this should rather be fixed at the bidder level. @PDXandr Do you happen to have a list of bidders that send ad markups with the root `native` object? If you do, we could contact them and request them to change this behavior on their end.

**Comment by PDXandr** [comment]
Thank you for the important clarification @mansinahar.  I agree with the approach of having bidders correct formatting on their end.  Unfortunately, I do not have a list of bidders sending requests out-of-spec but we can sync internally.

**Comment by bretg** [comment]
@PDXandr , @mansinahar , @SyntaxNode - would like to move forward on defining what to do here. 

1. Can you provide an explicit example of the problem and perhaps the pseudocode solution?
2. Even if it's not a full list of server-side adapters, one or two that exhibit the issue would be good.
