### ISSUE TITLE
Error "Post : unsupported protocol scheme" in IndexExchange bidder

### ISSUE THREAD

**Issue by yacota** [prebid/prebid-server#284]
In the auction response we can see the following error message 

```
{
"bidder": "indexExchange",
"ad_unit": "div-gpt-ad-1460505748561-0",
"error": "Post : unsupported protocol scheme \"\"",
"no_cookie": true,
"usersync": {
    "type": "redirect"
}
```
Any idea on how to proceed ?

**Comment by dbemiller** [comment]
Are you running your own Prebid Server deploy, or someone else's?

That looks like a Go error from an HTTP request to a bad endpoint. That would be determined by `adapters.indexExchange.endpoint` in your app config. My first guess would be that the URI might be missing a protocol, so Go's http client can't interpret it?

**Comment by yacota** [comment]
Yes, we are running our own Prebid Server. 
Maybe I am totally lost but by looking at https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L718 I can not see any adapters.indexExchange.endpoint. Are we supposed to add that endpoint ? How can we do that ?
Thanks!

**Comment by dbemiller** [comment]
yeah... apologies, our [config docs](https://github.com/prebid/prebid-server/blob/master/docs/developers/configuration.md) are very sparse at the moment.

Prebid Server uses [Viper](https://github.com/spf13/viper) to manage configs... but the specific question "how should we set the config?" depends heavily on your infrastructure.

The most common way nowadays is is probably through [environment variables](https://github.com/spf13/viper#working-with-environment-variables)... but honestly I don't have much experience with it. We use a Kubernetes [configmap](http://blog.kubernetes.io/2016/04/configuration-management-with-containers.html).

The most simple way would be to just define a `pbs.yaml` file in your project root:

```
adapters:
  indexExchange:
    endpoint: "http://path/to/index/endpoint"
```

If you have an endpoint for Index which can be made public for the project, definitely also feel free to submit a PR adding a `viper.SetDefault()` line for it.

**Comment by yacota** [comment]
Thanks for the feedback!
