### ISSUE TITLE
Automatically update publisher.id in the app object in the IX adapter

### ISSUE THREAD

**Issue by evll** [prebid/prebid-server#2849]
Indexexchange requires `app.publisher.id` or `site.publisher.id` to be equal to their `siteId` in bid requests. It's not feasible to adjust `publisher.id` specifically for IX, so, I assume for that reason, they have automatic updating of that field in their requests: https://github.com/prebid/prebid-server/blob/master/adapters/ix/ix.go#L103

The problem is that currently it only works for the `site` object. For mobile apps `site` is replaced with `app`, and the automatic updating no longer works. 

Please add support for `app.publisher.id` as well.

**Comment by bretg** [comment]
Adding @ix-prebid-support

**Comment by lcorrigall** [comment]
Thanks for raising this. I've talked with my team and we agree that our adapter should account for app. We're looking into it now. Thank you for submitting the PR as well. Unfortunately, it conflict with another PR we have raised but we will rework it if everything looks good for us on our API side.

**Comment by evll** [comment]
I see that some changes to the IX adapter have been merged recently, my PR is conflicting with master now, so I closed it. But let me know if I can help with delivering this change faster.

**Comment by bretg** [comment]
@lcorrigall or @ix-prebid-support - what's the status here?

**Comment by SyntaxNode** [comment]
@evll Does the linked change from IX resolve your issue?

**Comment by evll** [comment]
Yes, it does. Thank you
