### ISSUE TITLE
OpenRTB endpoint: support custom KVP values

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#289]
Feature:

Related to https://github.com/prebid/prebid-server/issues/288, the new OpenRTB endpoint needs to be able to accept custom ad server targeting from adapters and pass it through to the client

The primary use case is to support custom deal package targeting, but the feature is generic and could be used for other adapter-specific features.

Requirements:

1) Adapters need to know where to put the custom targeting on the response to the Prebid Server platform

2) The Prebid Server platform needs to accept these custom parameters and forward them in the response to the client. The platform shouldn't limit what the adapters send (e.g. don't limit the values to 40-characters).

3) As a future feature, we might want to add configurable controls around which adapters can supply custom targeting and even which targeting keys. But that's not needed for the initial cut at the feature.

**Comment by cirla** [comment]
I was digging around while working on #298 and it seems the adapters could just write directly to `bid.Ext.Prebid.Targeting` within their `MakeBids` implementations when constructing the `openrtb.Bid`s and the Prebid Server would need to be careful not to clobber existing values in the map (as happened in #288), e.g. [here](https://github.com/prebid/prebid-server/blob/2cb1103af54702d09e6376cb70948c0b9ad33189/exchange/exchange.go#L296).

**Comment by hhhjort** [comment]
Currently openRTB moves all `bid.Ext.*` that an adapter returns into `bid.Ext.bidder.*` in order to avoid clobbering anything there. To support this, we would need code that can carefully merge the needed fields from this back into the standard targeting block, or have the consumer (prebid.js?) know to look there for extra targeting keys. Not sure where the support should best be handled.

**Comment by SyntaxNode** [comment]
@bretg Revisiting this old issue. Do adapters still have a need to generate their own custom targeting keys beyond populating `response.bid[].ext.bidder`?

There hasn't been a follow-up to this for nearly 3 years, so I'm leaning towards considering this as not needed.

**Comment by patmmccann** [comment]
To "support custom deal package targeting"; one would think the bidder specific portion of the fpd / ortb2 config would be the place now?

**Comment by bretg** [comment]
I think this feature is still needed:

- targeting has to be in response.seatbid[].bid[].ext.prebid.targeting or the clients won't pass them to the ad server
- the other issue #2031 defines a publisher-level control, which is useful for those publishers that may want to control what gets sent

Closing this one as duplicate of the 2031
