### ISSUE TITLE
Rubicon responds with js as creative code. Prebid.js expects html/url

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#29]
I've got the following response from prebid-server. 

"bids": [{
        "bid_id": "26f3cbd58fb4bb",
        "code": "ad_cs_9493688_728_90",
        "creative_id": "3563776",
        "bidder": "rubicon",
        "price": 0.230999,
        "adm": "rubicon_cb = Math.random(); rubicon_rurl = document.referrer; if(top.location==document.location){rubicon_rurl = document.location;} rubicon_rurl = escape(rubicon_rurl);\nwindow.rubicon_ad = \"3450174\" + \".\" + \"js\"; window.rubicon_creative = \"3563776\" + \".\" + \"js\"; document.write(\"\\n\\n\"); rubicon_tag_code = \"%3cscript%20type=%22text/javascript%22%20src=%22https://pr.ybp.yahoo.com/ab/secure/true/imp/NA0gz5xIV5RA1_hBmpOHaeht06DqO-3uwFWAbdp6rlwC9DvRKwyDZAkacIV-Gr3FREiHzA0Deca3KihUQcVpKC5wSh9AvXjVGSMaGThhWebnTtt-Frxppd_a2uGfdUeXQUdZbErM30TPmhd9UI61ebzMhAm6odX9h_g5QVNgkBBRtKUjoMo_uFkN4dxtywDBTJwrfh0GG0Cg9551lxpMCf4qOlAV5ZoZ42Acw8riCArb5WXgtDdaqDJGT-GO4yYHP7nZltNXxAOhnQ5wSkWhIOOzs9dM3YegvvS6F1GFNsnMcYHzUg14hHbOSPKjWJIYJ0gJ3eMh13nXFEJvwz2EyZWPXeuvSCM3faZOidXMl-FIGYp1Z2wLwlx_sjT8_bw_K-wQvevLq64eaT8hzID8d6_nq-iO7DcQLz0qb8z46CcKoU06M1M6EiWRW0MF7X84OUmrOBQKl2gyvW1BXVqBmWgWDWzj3ZbNkjJ_ImYJeHg7SmuR2DkhskenWuGOB0CboUKFxHX-jSe0Ers1yILa_JZ1-lHpw3_nkA35Pu6pX1T1vPh2Nu0M3mZFwOGRVKuz1yBT0-6VX1Qxw2z4MEaEOJFH1BtwCKXC1hPRw3hRIG7TRdoD59ZshqtFavOwPQvrGkdkXHPwPFzqsfDqsXgXQ2KtjYmjgK2AOkUpjS4KhkH18haS1X3ImsgiucoqgzEB1BwyAiNpRa4tACwBWeWDvzAQQYFPPGOCh1m6wyF4JkzIwgzRKoVk7yQFlxhUhFiKtkOO3YliWd2OSLk6CqeogbQS_0I7HlqbUWza7xKSdnHkQZT5QpUoQAHu8vHmF57zKGbqDPX2EmjDWsbmbX39EwL-kik9pNetRwv84roDHa2E95f0yM7wKS_PhO-P55aoADSveP_qYLf3gYucsGfc3NIlwxOY2sAMCKPzcnmIA3k1Krbr3J8HUelz3AdTupld6DU8C_vRlHUgMOB652eryjHzpt4DzcFI/wp/E6103826DDE957DB%22%3e%3c/script%3e\"; rubicon_tag_code = rubicon_tag_code.replace(/##RUBICON_CB##/g,rubicon_cb); document.write(unescape(rubicon_tag_code)); document.write(\"<div style=\\\"height:0px;width:0px;overflow:hidden\\\"><script>(function(){var proto=\\'https:\\';try{proto=window.top.location.protocol;}catch(e){proto=(document.referrer===\\'\\'?\\'https:\\':document.referrer.split(\\'//\\')[0]);}var server=\\\"http://tap2-cdn.rubiconproject.com\\\";if(proto==\\\"https:\\\")server=\\\"https://tap-secure.rubiconproject.com\\\";document.write(\\'<iframe src=\\\"\\'+server+\\'/partner/scripts/rubicon/emily.html?pc=15178/93918&geo=na&co=us\\\" frameborder=\\\"0\\\" marginwidth=\\\"0\\\" marginheight=\\\"0\\\" scrolling=\\\"NO\\\" width=\\\"0\\\" height=\\\"0\\\" style=\\\"height:0px;width:0px\\\"></iframe>\\');})();<\\/script></div>\\n\");",
        "width": 728,
        "height": 90
    }]

As you can see adm field is js code. I'm not sure if there is any specification on acepted formats, but it seems to me that $$PREBID_GLOBAL$$.renderAd expects url or html code. As the result js code is inserted into the document and rendered as a text: https://ibb.co/epL735 (there are two banners on the page one under another).

I guess the easiest way is to wrap rubicon's response into "script" tags. But I'm not sure if rubicon always responds with js.

**Comment by mjacobsonny** [comment]
Looks like we will need to set `imp.banner.ext.rp.mime` to `"text/html"` on requests to Rubicon's bidder from Prebid Server.

**Comment by mjacobsonny** [comment]
Fix merged: https://github.com/prebid/prebid-server/pull/31
