### ISSUE TITLE
Adyoulike adapter user sync pixel causes popup message in Safari

### ISSUE THREAD

**Issue by mkarlov** [prebid/prebid-server#2919]
When prebid server loads usersync URL https://acdn.adnxs.com/prebid/universal-creative/load-cookie.html?max_sync_count=30 
and if it loads usersync pixels from bidder adapter Adyoulike https://github.com/prebid/prebid-server/blob/master/static/bidder-info/adyoulike.yaml the url prompts popup message in Safari browser. 

Example:
{
            "bidder": "adyoulike",
            "no_cookie": true,
            "usersync": {
                "url": "https://visitor.omnitagjs.com/visitor/isync?uid=19340f4f097d16f41f34fc0274981ca4&name=PrebidServer&gdpr=&gdpr_consent=&us_privacy=&url=https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dadyoulike%26gdpr%3D%26gdpr_consent%3D%26gpp%3D%26gpp_sid%3D%26f%3Db%26uid%3D%5BBUYER_USERID%5D",
                "type": "iframe"
            }
        },

To reproduce, paste the url in Safari. This causes bad user experience and complaints from website visitors.

**Comment by mkarlov** [comment]
Hi @bretg 

Attaching screenshots from my test and client live site.

<img width="1318" alt="Screenshot 2023-07-12 at 15 39 39" src="https://github.com/prebid/prebid-server/assets/139349119/e228187c-2a57-4f65-9d06-3d6ede9774bc">
<img width="976" alt="Screenshot 2023-07-12 at 15 41 50" src="https://github.com/prebid/prebid-server/assets/139349119/e06b1358-d0b1-4646-90a2-18f69b86dd4d">
![omni](https://github.com/prebid/prebid-server/assets/139349119/ab033fd5-484a-49bb-b683-98b4a2821d70)

**Comment by bretg** [comment]
Thanks. @SimonThevenot and @chrisg93 - I suspect this might have to do with your `isync` script not having a a content-type tag on the response. (?)

**Comment by SimonThevenot** [comment]
Hello @bretg @mkarlov. Thanks for raising this issue. Yep it seems we are missing a header, we'll take care of it as soon as possible, I'll keep you in touch

**Comment by SimonThevenot** [comment]
Hello @bretg @mkarlov 
This has been fixed, could you confirm that the behavior is now OK ? Thanks

**Comment by bretg** [comment]
@mkarlov - the isync script now returns a content-type. Am going to close this as resolved. Please re-open if needed.

**Comment by mkarlov** [comment]
Sorry for the late response, I was away for the last couple of weeks. The issue appears to be fixed now, thank you!
