### ISSUE TITLE
Add GET cache endpoint

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#292]
SSHB for Video is different than for mobile and display.

1) display isn't currently caching creatives so there's no need to link to the Prebid Cache server
2) mobile has a javascript component (pbm.js) which can be customized per installation

Video requires cache but doesn't have a javascript engine -- it needs to define the cached asset URL in the ad server. When there are multiple Prebid Cache servers spread across multiple geographic regions, a single DNS alias isn't ideal. e.g. AppNexus currently places the following URL in the ad server for a video player to retrieve the VAST creative:
```
https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_cache_id%%
```
Where prebid.adnxs.com is a proxy server AppNexus has that sits in front of both PBS and PBC

In order to make it easier for others to set up multi-region clusters without requiring a proxy server, we propose adding a new endpoint to Prebid Server. e.g.
```
https://prebid-server.rubiconproject.com/cache?uuid=%%pattern:hb_uuid%%
```
This endpoint does the following:
1) confirms the request contains a valid UUID
2) connects to the local cache server VIP to retrieve the asset
3) returns the asset (or an error) to the client

In otherwords, to retrieve the creative, the video player 

Other solutions to this problem have been considered:

1) Server could pass the whole cache URL -- this is a problem in DFP because the macro can't be placed by itself in the UI, which complains about invalid hostname.
2) The server could pass the 'region' as a separate variable -- this also doesn't work in DFP as the UI will complain about invalid hostname
3) Use a redirector in DFP to bypass these annoying checks -- this works, but is another moving part and slows the transaction
4) Use a DNS traffic management product that guarantees the browser will go to the same region for both prebid-server and prebid-cache -- this could work, but we're hesitant to add the requirement for such a service

The solution suggested here (the /cache endpoint) has the advantage of one fewer DNS lookups than the other solutions. The proxy solution is also just one DNS lookup, but is another moving part.

More details:
1) define a new endpoint on PBS:
```
/cache?uuid=%%PATTERN:hb_cache_id%%
```
2) when /cache is hit with a GET, validate that the uuid parameter is specified and exists? valid? (>= 30 chars, <= 50 chars?). If not, return HTTP 400
4) call out to the local Prebid Cache server to retrieve the creative
5) return the creative to the caller
6) any other HTTP method results in an error 405

**Comment by bretg** [comment]
@dbemiller - please confirm the URL design proposed here:
```
GET https://prebid-server.rubiconproject.com/cache?uuid=%%pattern:hb_uuid%%
```

**Comment by mkendall07** [comment]
I don't think we should do this as it adds a tight coupling to the cache on prebid. The reason we kept these components separate is because they have different performance characteristics and you're basically making them into 1 service by doing this.

Additionally, don't you need to know add the /put endpoint into PBS as well? What happens when on the client side, you cache a video bid to `https://<cache_domain>/pbc/put` and then DFP creative calls `https://<pbs_domain>/pbc/get` for the get?  The DNS caching would not guarantee it's going back to the right server since the hostname is different.

**Comment by dbemiller** [comment]
yeah... I'm balking at this myself. It's a good time not to be the PMC for the project :). I do trust @mkendall07's judgement a lot, though, so I'm inclined to agree.

If I were an engineer on the project over there, I would almost definitely suggest adding a proxy to each region to route the incoming requests instead.

From my point of view, the main issue is that these endpoints, as suggested, would be implemented _much_ better if they talked directly to the backends (aerospike, azure, memcache, etc). The fact that the calls go through Prebid Cache is an inconvenience. It just adds request latency, and complicates your deployments.

So I see the request here as: "let's make Prebid Server less opinionated about the network architecture of the companies deploying it."

To some extent I'm sympathetic to that. It's an open-source codebase. There are valid reasons why one deployable app is easier to work with. Startups and small publishers will find single-app deployments easier to work with.

...but as Matt pointed out, PBS and PBC have very different performance characteristics. As load increases, you'll be able to make _far_ more efficient use of your machines if you can deploy them separately.

My biggest criticism of this proposal is that it splits the difference between both architectures. The endpoints you're adding aren't useful for multi-app hosts, and the implementation isn't efficient for single-app hosts.

There's lots more I could say on the subject... but given that Matt's pretty strongly opposed for his own reasons, I'm not sure there's much need.
