### ISSUE TITLE
Split auction_test.go tests into files

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#295]
The [endpoints/openrtb2/auction_test.go](https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/auction_test.go) file embeds lots of JSON into strings, which has a few problems:

1. It's easy to typo a comma inside a string and have a valid request be rejected as "invalid" because of the typo.
2. When a test fails, it's difficult to tell which test case failed, or why.

These test cases should be migrated into `.json` files, like the [adapters](https://github.com/prebid/prebid-server/tree/master/adapters/appnexus/appnexustest/supplemental) do.

**Comment by cirla** [comment]
@dbemiller is this closed by https://github.com/prebid/prebid-server/pull/435?

**Comment by dbemiller** [comment]
No... different layer of the application, sadly.

There are still some tests in `auction_test.go` which handle Stored Request stuff: https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/auction_test.go#L497

It would be nice to clear those out into JSON files at some point too.
