### ISSUE TITLE
Prebid Server Deployment: Cache Duration and Request Limits

### ISSUE THREAD

**Issue by Shaharbad** [prebid/prebid-server#2964]
Hello everyone,

I'm preparing to deploy my own Prebid Server and have a few queries prior to initiating the process:

1. Can anyone provide details on the maximum duration for holding a bid in the cache?
2. What is the maximum limit of bid requests that can be stored in the cache simultaneously?
3. Is the primary functionality of the Prebid Server via "GET" requests or "POST" requests?

I appreciate your assistance in advance.

**Comment by SyntaxNode** [comment]
Hi. Thank you for your interest in deploying our project. To answer your questions:

1. It's common to use a 5 minute timeout for creatives which are expected to be rendered immediately and up to a 60 minute timeout for CTV video ads. The actual maximum duration for Prebid Cache depends on what you as the host configure. The default maximum is 60 minutes.
2. The maximum limit of bid requests that can be stored in the cache simultaneously depends on the capacity of your Prebid Cache backend database.
3. Prebid Server /auction requests must be POST and include an OpenRTB body whereas /amp requests must be GET and refer to a Stored Request.

**Comment by Shaharbad** [comment]
> Hi. Thank you for your interest in deploying our project. To answer your questions:
> 
> 1. It's common to use a 5 minute timeout for creatives which are expected to be rendered immediately and up to a 60 minute timeout for CTV video ads. The actual maximum duration for Prebid Cache depends on what you as the host configure. The default maximum is 60 minutes.
> 2. The maximum limit of bid requests that can be stored in the cache simultaneously depends on the capacity of your Prebid Cache backend database.
> 3. Prebid Server /auction requests must be POST and include an OpenRTB body whereas /amp requests must be GET and refer to a Stored Request.

Thank you for the answers! 
In my first question I meant to what is the longest amount of time the Prebid Cache tool can hold all the bid requests he got before he send them to the ad server, 60 minutes sound insane, is that the answer?

**Comment by bretg** [comment]
@Shaharbad 

> what is the longest amount of time the Prebid Cache tool can hold all the bid requests

Prebid doesn't impose a limit but your backend NoSQL DB might. Please note that Prebid Cache Server just a simple front-end to: Redis, Cassandra, Aerospike, Syclla, etc... you have to pick a backend database and decide how to configure it: how many hosts, how much storage, fault tolerance, etc.

If you're going to keep creatives around longer, you'll need more storage.
