### ISSUE TITLE
Host render script (pbm.js) in Open Source CDN

### ISSUE THREAD

**Issue by djsu** [prebid/prebid-server#297]

**Comment by whcemyesil** [comment]
I'd like to avoid using a CDN or any external source to fetch the script for each ad request. I'd like to include pbm.js manually in the ad server response. Whenever there is an update to pbm.js, I'd like to update my ad server response to include the new version. Is there any way to follow the release cycles of pbm.js? I couldn't find it on GitHub

**Comment by dbemiller** [comment]
I didn't have context on this issue, so I asked around prebid.org a bit. I learned:

1. `pbm.js` script is a legacy Prebid Mobile rendering script.
2. It's been deprecated in favor of the [Prebid Universal Creative](https://github.com/prebid/prebid-universal-creative)... but most publishers are probably still using it.

This doesn't seem to have anything to do with Prebid Server... so I'm going to close it. If people are still using `pbm.js` and care about this, please open issues in the most relevant project(s) for you:

- https://github.com/prebid/prebid-mobile-ios
- https://github.com/prebid/prebid-mobile-android

If the Prebid Universal Creative has bugs which prevent it from replacing pbm.js, please open an issue there instead:

- https://github.com/prebid/prebid-universal-creative
