### ISSUE TITLE
gdpr.default_value is required and must be specified

### ISSUE THREAD

**Issue by Vungle-GordonTian** [prebid/prebid-server#2974]
<img width="1090" alt="image" src="https://github.com/prebid/prebid-server/assets/115982294/dd1ab90b-578b-4ea8-9bfa-65efc244384f">
when I try to launch the Prebid Server using command ./prebid-server to do manual end to end test, I got this prompt.

Since all the ut are passed and I didn't change any config, why can't I launch the server successfully? Here's the PR link.https://github.com/prebid/prebid.github.io/pull/4757

**Comment by Vungle-GordonTian** [comment]
Already fixed.

**Comment by EMXDigital** [comment]
> Already fixed.

What is the fix?

**Comment by hajimurtaza** [comment]
> Already fixed.

What is the fix?

**Comment by Vungle-GordonTian** [comment]
> > Already fixed.
> 
> What is the fix?

I operate by following this thread and then everything works.
