### ISSUE TITLE
Establish clear guidelines on renaming adapters

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2976]
We've had a number of bid adapters rename themselves lately, and sometimes they do it abruptly in a way that causes PBS Host Companies a headache of losing connection.

We need to establish clear documented guidelines for how adapters can accomplish a rename smoothly. I think the [FAQ entry](https://docs.prebid.org/faq/prebid-server-faq.html#how-can-we-rename-our-bid-adapter) covers this mostly, but we should discuss how to highlight potential breaking changes for PBS host companies.

**Comment by SyntaxNode** [comment]
Which adapters renamed themselves abruptly?

**Comment by bretg** [comment]
The one I got a note about was yahoossp, but there have been others recently where I push back in documentation when they want to delete the old name rather than having the transition period.

**Comment by bretg** [comment]
Discussed in backlog:
- will discuss a yearly major in in the full committee
- update FAQ to note old names will stick around until major release
