### ISSUE TITLE
Will Prebid Server hide our super token from other bidders?

### ISSUE THREAD

**Issue by Vungle-GordonTian** [prebid/prebid-server#2977]
Liftoff will require publisher to send their super token through liftoff adapter for Prebid Server, we want Prebid Server to hide our super token from other bidders? Can this be satisfied?

**Comment by bretg** [comment]
What is a "super token" @Vungle-GordonTian ?

- The results of the [cookie sync process](https://docs.prebid.org/prebid-server/developers/pbs-cookie-sync.html) are not shared with other adapters -- only yours.
- Bid-adapter-specific parameters are only seen by your adapter. I see you have a bid parameter called bid_token - this will not be seen by others.

**Comment by Vungle-GordonTian** [comment]
> What is a "super token" @Vungle-GordonTian ?
> 
> * The results of the [cookie sync process](https://docs.prebid.org/prebid-server/developers/pbs-cookie-sync.html) are not shared with other adapters -- only yours.
> * Bid-adapter-specific parameters are only seen by your adapter. I see you have a bid parameter called bid_token - this will not be seen by others.

Yeah, exactly the bid_token, it's great if it will not be seen by other bidders.
