### ISSUE TITLE
Creating a stored request for testing video auction

### ISSUE THREAD

**Issue by Shaharbad** [prebid/prebid-server#2979]
Hey everyone, 
I'm trying to create a stored request in order to test a video auction but i cant seem to load the request by id,
In my root folder i added the request to `stored_requests/data/by_id/stored_imps/abc123.json`
with this data:
`{
  "id": "abc123",
  "banner": {
    "format": [
      {
        "w": 300,
        "h": 250
      },
      {
        "w": 300,
        "h": 600
      }
    ]
  },
  "ext": {
    "prebid": {
      "bidder": {
        "appnexus": {
          "placement_id": 12883451
        }
      }
    }
  }
}`

then I ran a POST request `http://localhost:8000/openrtb2/video` using this body:
` {
  "storedrequestid": "abc123",
  "podconfig": {
    "durationrangesec": [
      15,
      30
    ],
    "pods": [
      {
        "podid": 1,
        "adpoddurationsec": 60,
        "configid": "fba10607-0c12-43d1-ad07-b8a513bc75d6"
      },
      {
        "podid": 2,
        "adpoddurationsec": 60,
        "configid": "8b452b41-2681-4a20-9086-6f16ffad7773"
      }
    ]
  },
  "site": {
    "page": "https://www.foobar.com/1234.html"
  },
  "user": {
    "yob": 1982,
    "gender": "M",
    "buyeruids": {
      "appnexus": "unique_id_an"
    },
    "gdpr": {
      "consentrequired": false,
      "consentstring": ""
    }
  },
  "device": {
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.13 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2",
    "ip": "123.145.167.10",
    "devicetype": 1,
    "ifa": "AA000DFE74168477C70D291f574D344790E0BB11"
  },
  "includebrandcategory": {
    "primaryadserver": 1
  },
  "video": {
    "w": 640,
    "h": 480,
    "mimes": [
      "video/mp4"
    ],
    "protocols": [
      2,
      3
    ]
  },
  "content": {
    "episode": 6,
    "title": "episodeName",
    "series": "TvName",
    "season": "season3",
    "len": 900,
    "livestream": 0
  }
}`

but i get:
`Critical error while running the video endpoint:  Stored Request with ID="abc123" not found.`

I would appreciate your help and your patience since i'm new to prebid.
Thanks.

**Comment by VeronikaSolovei9** [comment]
There are 2 types of stored data you need to configure in order to make a video request work: stored video request and pod config id. 
Based on the description you provided you need to set up a file system fetcher for stored video request: "storedrequestid": "abc123". For this you need to modify your local config. You may have it in json, yaml or in config.go, here is the list of fields to modify:
```go
        v.SetDefault("stored_video_req.filesystem.enabled", false) --> should be true
	v.SetDefault("stored_video_req.filesystem.directorypath", "") --> should be "./stored_requests/data/by_id"
	v.SetDefault("stored_video_req.in_memory_cache.type", "none") --> should be "unbounded"
```
Note this stored data should have a video endpoint format, not impression format.
Note video endpoint will probably not work correctly with banner impressions.

Note in order to load pod config id you should have a `"stored_requests"` fetcher configured, similar to `stored_video_req`:
```go
        v.SetDefault("stored_requests.filesystem.enabled", true)
	v.SetDefault("stored_requests.filesystem.directorypath", "./stored_requests/data/by_id")
	v.SetDefault("stored_requests.in_memory_cache.type", "unbounded")
```

Note the data you have in pod[].configid should be in impression format, otherwise it will throw an unmarshal error. 

I understand it can be confusing. Please feel free to follow up with questions.

**Comment by SyntaxNode** [comment]
Thanks @VeronikaSolovei9. The trick here is that each endpoint has it's own stored requests backend.

**Comment by Shaharbad** [comment]
Thank you for the answer, however, I still can't figure it out.
I tested it before I submitted the issue with this pbs.yaml file:
```
status_response: "ok"

stored_requests:
  filesystem:
    enabled: true
    directorypath: "./stored_requests/data/by_id"
  in_memory_cache:
    type: "unbounded"

stored_video_req:
  filesystem:
    enabled: true
    directorypath: "./stored_requests/data/by_id"
  in_memory_cache:
    type: "unbounded"

gdpr:
  default_value: "0"
  timeouts_ms:
    init_vendorlist_fetches: 225000
    active_vendorlist_fetch: 225000

```
and it still says it can't find the id of the request.
could you please share an example for the files i will need to test the /openrtb2/auction endpoint + what body to send the POST request with so i can move forward with launching my prebid server.

Thanks

**Comment by VeronikaSolovei9** [comment]
About the video endpoint: 
I checked it on my local PBS with the yaml config you provided and it worked. 
May you please double check your filesystem setup:
1) Check your `PATH_TO_PBS/stored_requests/data/by_id/stored_requests/abc123.json` file is present and has this kind of content: 
```json
{
  "appendbiddernames": true,
  "podconfig": {
    "durationrangesec": [
      15,
      30
    ],
    "pods": [
      {
        "podid": 1,
        "adpoddurationsec": 60,
        "configid": "fba10607-0c12-43d1-ad07-b8a513bc75d6"
      }
    ]
  },
  "includebrandcategory": {
    "primaryadserver": 1,
    "publisher1": "9367"
  },
  "video": {
    "w": 640,
    "h": 480,
    "mimes": [
      "video/mp4"
    ],
    "protocols": [
      2,
      3
    ]
  },
  "pricegranularity": {
    "precision": 2,
    "ranges": [
      {
        "min": 0,
        "max": 10,
        "increment": 1
      }
    ]
  },
  "site": {
    "page": "test.com"
  }
}
```

2) Check your `PATH_TO_PBS/stored_requests/data/by_id/stored_requests/fba10607-0c12-43d1-ad07-b8a513bc75d6.json` file is present and has this kind of content (basically imp.ext with valid bidders config, can be more than one):
```json
{
  "ext": {
    "amx": { //<--- or other bidder
    }
  }
}
```  
3) Make sure your pbs.yaml is in the PBS project root directory.

Then run HTTP POST request to `localhost:8000/openrtb2/video`. You may have different port, check in your configs or add `port: 8000` to your pbs.yaml. Here is request body: 
```json
{
    "storedrequestid": "abc123"
}
```
Most probably you will have no bids back, but it's expected, you will need to modify `fba10607-0c12-43d1-ad07-b8a513bc75d6.json` file to include valid bidders with valid bidder parameters. But you will see empty response like this:
```json
{
    "adPods": []
}
```
that will indicate data was loaded successfully. 


About the auction endpoint:
Run HTTP POST to this endpoint: `localhost:8000/openrtb2/auction` with this request body: 
```json
{
    "id": "some-request-id",
    "imp": [
        {
            "id": "some-impression-id",
            "banner": {
                "format": [
                    {
                        "w": 600,
                        "h": 500
                    },
                    {
                        "w": 300,
                        "h": 600
                    }
                ],
                "w": 600,
                "h": 500
            },
            "secure": 1,
            "ext": {
                "amx":{}
            }
        }
    ],
    "site": {
        "page": "prebid.org",
        "ext": {
            "amp": 0
        }
    },
    "device": {
        "ua": "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25"
    },
    "at": 1,
    "tmax": 500
}
```
You will get an empty response here too because req.imp[].ext should have valid bidders with valid parameters. 

Optional: if you use Postman or similar tool to run requests, please add user-agent to request header, something like: 
`User-Agent` : `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36`


Hope this helps.

**Comment by Shaharbad** [comment]
> About the video endpoint: I checked it on my local PBS with the yaml config you provided and it worked. May you please double check your filesystem setup:
> 
> 1. Check your `PATH_TO_PBS/stored_requests/data/by_id/stored_requests/abc123.json` file is present and has this kind of content:
> 
> ```json
> {
>   "appendbiddernames": true,
>   "podconfig": {
>     "durationrangesec": [
>       15,
>       30
>     ],
>     "pods": [
>       {
>         "podid": 1,
>         "adpoddurationsec": 60,
>         "configid": "fba10607-0c12-43d1-ad07-b8a513bc75d6"
>       }
>     ]
>   },
>   "includebrandcategory": {
>     "primaryadserver": 1,
>     "publisher1": "9367"
>   },
>   "video": {
>     "w": 640,
>     "h": 480,
>     "mimes": [
>       "video/mp4"
>     ],
>     "protocols": [
>       2,
>       3
>     ]
>   },
>   "pricegranularity": {
>     "precision": 2,
>     "ranges": [
>       {
>         "min": 0,
>         "max": 10,
>         "increment": 1
>       }
>     ]
>   },
>   "site": {
>     "page": "test.com"
>   }
> }
> ```
> 
> 2. Check your `PATH_TO_PBS/stored_requests/data/by_id/stored_imps/fba10607-0c12-43d1-ad07-b8a513bc75d6.json` file is present and has this kind of content (basically imp.ext with valid bidders config, can be more than one):
> 
> ```json
> {
>   "ext": {
>     "amx": { //<--- or other bidder
>     }
>   }
> }
> ```
> 
> 3. Make sure your pbs.yaml is in the PBS project root directory.
> 
> Then run HTTP POST request to `localhost:8000/openrtb2/video`. You may have different port, check in your configs or add `port: 8000` to your pbs.yaml. Here is request body:
> 
> ```json
> {
>     "storedrequestid": "abc123"
> }
> ```
> 
> Most probably you will have no bids back, but it's expected, you will need to modify `fba10607-0c12-43d1-ad07-b8a513bc75d6.json` file to include valid bidders with valid bidder parameters. But you will see empty response like this:
> 
> ```json
> {
>     "adPods": []
> }
> ```
> 
> that will indicate data was loaded successfully.
> 
> About the auction endpoint: Run HTTP POST to this endpoint: `localhost:8000/openrtb2/auction` with this request body:
> 
> ```json
> {
>     "id": "some-request-id",
>     "imp": [
>         {
>             "id": "some-impression-id",
>             "banner": {
>                 "format": [
>                     {
>                         "w": 600,
>                         "h": 500
>                     },
>                     {
>                         "w": 300,
>                         "h": 600
>                     }
>                 ],
>                 "w": 600,
>                 "h": 500
>             },
>             "secure": 1,
>             "ext": {
>                 "amx":{}
>             }
>         }
>     ],
>     "site": {
>         "page": "prebid.org",
>         "ext": {
>             "amp": 0
>         }
>     },
>     "device": {
>         "ua": "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25"
>     },
>     "at": 1,
>     "tmax": 500
> }
> ```
> 
> You will get an empty response here too because req.imp[].ext should have valid bidders with valid parameters.
> 
> Optional: if you use Postman or similar tool to run requests, please add user-agent to request header, something like: `User-Agent` : `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36`
> 
> Hope this helps.

Thank you!
This did work for me, now I'm stuck on understanding the flow with using the /openrtb2/video method. (for now only for testing), could you share the flow of the requests when using such method? my end goal is to know the flow and test it we sample bid requests and bid responses locally.

From what I know the steps our somehing like:
1. Publisher's ad server → POST → /openrtb2/video
    * Request includes:
        * Ad unit ID
        * Video creative requirements
        * List of demand partners
2. Prebid Server → POST → /openrtb2/video
    * Request includes:
        * Ad unit ID
        * Video creative requirements
        * Publisher's bid floor
3. Demand partners → POST → /openrtb2/video
    * Response includes:
        * Bid price
        * Bid type
        * Bid currency
4. Prebid Server → POST → /cache
    * Request includes:
        * Ad unit ID
        * Video creative requirements
5. Publisher's ad server → GET → /cache
    * Request includes:
        * Ad unit ID
        * Video creative requirements
6. Prebid Server → GET → /cache
    * Response includes:
        * List of bids

**Comment by Shaharbad** [comment]
@VeronikaSolovei9

**Comment by VeronikaSolovei9** [comment]
Here is an approximate approach to use the video endpoint: 

1. Application requests a video stream
2. SSAI server sends an video request to PBS, specifying the pod requirements.
3. PBS runs an auction with all the Demand partners by relaying Open RTB requests to them.
4. PBS collects the bids, performs category translation for each bid (assuming competitive separation is enabled), stores the bids in the prebid cache.
5. PBS generates the key value pairs which comprises of price, category and duration and returns it as a part of the video response to the SSAI server. (hb_pb_cat_dur value)
6. SSAI sever parsers the kv pairs , appends it to the Ad server request url and makes the request.
7. Ad server returns the optimized pod.
8. SSAI server requests the creatives from prebid cache.
9. SSAI server stitches the content and ad 
10. SSAI server returns the stitched stream.

Note 1:  `video` endpoint will be deprecated soon. Instead consider using `auction` endpoint. 
Note 2:  this set up requires ad server line item to request VAST using redirect URL which is a Prebid Cache URL.

**Comment by Shaharbad** [comment]
> Here is an approximate approach to use the video endpoint:
> 
> 1. Application requests a video stream
> 2. SSAI server sends an video request to PBS, specifying the pod requirements.
> 3. PBS runs an auction with all the Demand partners by relaying Open RTB requests to them.
> 4. PBS collects the bids, performs category translation for each bid (assuming competitive separation is enabled), stores the bids in the prebid cache.
> 5. PBS generates the key value pairs which comprises of price, category and duration and returns it as a part of the video response to the SSAI server. (hb_pb_cat_dur value)
> 6. SSAI sever parsers the kv pairs , appends it to the Ad server request url and makes the request.
> 7. Ad server returns the optimized pod.
> 8. SSAI server requests the creatives from prebid cache.
> 9. SSAI server stitches the content and ad
> 10. SSAI server returns the stitched stream.
> 
> Note 1: `video` endpoint will be deprecated soon. Instead consider using `auction` endpoint. Note 2: this set up requires ad server line item to request VAST using redirect URL which is a Prebid Cache URL.

@VeronikaSolovei9 Thanks for the answer.
Would using /openrtb2/auction work on a long form video in ctv? (Roku, Fire Tv etc..)

**Comment by VeronikaSolovei9** [comment]
Yes. In the set up you described Ad Server is responsible for ad podding, not Prebid Server. In order to run a competitive separation you will need to add `req.ext.prebid.targeting.includebrandcategory` to your auction request:
```json
"includebrandcategory": {
   "primaryadserver": 1, //<-- Ad Server id for category translation. 1-Freewheel, 2-DFP/GAM
   "publisher": "",
   "withcategory": true
}
```

**Comment by Shaharbad** [comment]
> Yes. In the set up you described Ad Server is responsible for ad podding, not Prebid Server. In order to run a competitive separation you will need to add `req.ext.prebid.targeting.includebrandcategory` to your auction request:
> 
> ```json
> "includebrandcategory": {
>    "primaryadserver": 1, //<-- Ad Server id for category translation. 1-Freewheel, 2-DFP/GAM
>    "publisher": "",
>    "withcategory": true
> }
> ```

Thank you Veronika
