### ISSUE TITLE
Support cache ttl for audio and native 

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#2980]
PBS supports different cache lengths for mediatypes banner and video. Should we consider splitting this out to support native and audio?

In considering this for issue https://github.com/prebid/prebid-server/issues/2975, I realized that our cache length ought to be capped by the bidder's ORTB exp parameter. Perhaps we're already doing this?

**Comment by bretg** [comment]
Discussed in backlog meeting:
- agreed that extending cache length controls to native and audio makes sense. Just mediatypes, though, and DOOH is not a mediatype.
- Agreed that cache length should be capped by any `exp` parameter. Go and Java teams to look into whether this is already the case.

**Comment by SyntaxNode** [comment]
PBS-Go already allows default cache values to be defined for all media types (banner, video, audio, native) and the `exp` field is already taken into consideration during cache length calculation.

**Comment by bretg** [comment]
Discussed in committee

- Agreed on account level config: cache-ttl.{banner,video,audio,native}
- Hardcoded defaults should be
    - banner: 300
    - video: 1500
    - native: 300
    - audio: 1500

PBS-Java uses different config for banner/video that will be deprecated.

**Comment by bretg** [comment]
released with PBS-Java 3.16
