### ISSUE TITLE
IPv6 scrubbing

### ISSUE THREAD

**Issue by VeronikaSolovei9** [prebid/prebid-server#2981]
In PBS Java here is a function to scrub IpV6: https://github.com/prebid/prebid-server-java/blob/3ebefb8ccdb52e68bb604660fc9808b54a513536/src/main/java/org/prebid/server/auction/IpAddressHelper.java#L39
and here is a simple unit tests for it: https://github.com/prebid/prebid-server-java/blob/3ebefb8ccdb52e68bb604660fc9808b54a513536/src/test/java/org/prebid/server/auction/IpAddressHelperTest.java#L65

It works a little different from what we have in Go.
Go:
For the Ip = "1111:2222:3333:4444:5555:6666:7777:8888" func scrubIPV6Lowest32Bits will return "1111:2222:3333:4444:5555:6666:0:0". It makes sense, lowest 32 bits were changed to 0s.
Java:
For the Ip = "1111:2222:3333:4444:5555:6666:7777:8888" result is "1111:2222:3333:4400::"

In Ipv6 lowest 64 bits represent physical or device Mac address and upper 64 bits represent a network address.
Upper 48 bits represent global address and next 16 bits represent subnet id.
http://www.steves-internet-guide.com/ipv6-guide/
https://en.wikipedia.org/wiki/IPv6_address
It looks like PBS Java only leaves a global address and scrub a half of subnet id and device Mac address.

**Comment by SyntaxNode** [comment]
Discovered during unification of privacy enforcement rules. Looks like we missed this a while back. Placed on the PBS-Go's priority item list.

**Comment by hhhjort** [comment]
PR has merged
