### ISSUE TITLE
Notifing demand sources that content length is 2 hours

### ISSUE THREAD

**Issue by Shaharbad** [prebid/prebid-server#2994]
Hey everyone,
I'm planning on integrating with Prebid Server soon but I have a question.
I know that Prebid server will send bid requests to demand sources, using a post request with body that includes the length of the source, but let's say that the source is a 2 hour movie that needs preroll and 2 post rolls, how can i make sure that the bid requests won't be expired?

(I accidentally closed the previous issue)

**Comment by bretg** [comment]
You can pass `$.imp[n].exp` as a signal to the bidders. This is an OpenRTB field with the definition "Advisory as to the number of seconds that may elapse between the auction and the actual impression."

Please recall that the Prebid Server protocol is mostly OpenRTB. Whether bidders read any given field is up to them. 

> (I accidentally closed the previous issue)

You didn't close it, I did. Closing this one too. :-). Open new ones as needed.

**Comment by Shaharbad** [comment]
> You can pass `$.imp[n].exp` as a signal to the bidders. This is an OpenRTB field with the definition "Advisory as to the number of seconds that may elapse between the auction and the actual impression."
> 
> Please recall that the Prebid Server protocol is mostly OpenRTB. Whether bidders read any given field is up to them.
> 
> > (I accidentally closed the previous issue)
> 
> You didn't close it, I did. Closing this one too. :-). Open new ones as needed.

I'm sorry but i didnt expressed the question as i should have, here is my question:
If I have a bid request for a 2 hour movie in Roku for example, for a preroll and a postroll, how can i make sure that the winning bid response i got from one of my demand partners will still play as the postroll and won't be expired? i'd assume it probably will still be visible on the screen but will i get payed for it if its after 2 hours since it won?

And lastly, as we talked about /video gets deprecated soon, will it be smarter to work with /auction for now until the /video features come to /auction? (again, could you please clarify I would be able to use it to get ad pods in CTV env like Roku, FireTv etc..)?

Thank you

**Comment by Shaharbad** [comment]
> > how can i make sure that the winning bid response i got from one of my demand partners will still play as the postroll and won't be expired?
> 
> You can't guarantee this.
> 
> I recommend reconsidering your architecture and calling the ads closer to the time of display. If you can't do that, then you need to work closely with your bidders to make sure they understand and respect the `imp.exp` field. Maybe you can limit your bidder set to those that confirm this.
> 
> > will it be smarter to work with /auction for now
> 
> If you don't need Prebid Server's category mapping and competitive exclusion features, yes, that sounds like a good move.

Thanks again.
