### ISSUE TITLE
imp[].prebid VS imp[].bidder in bid adapter tests

### ISSUE THREAD

**Issue by kamilmclearcode** [prebid/prebid-server#3010]
I'm creating my own bid adapter, and I have a problem with getting consistent results between running it and sending a request VS doing similar request in json tests.

Some code snippets:
```go
func (a *adapter) MakeRequests(request *openrtb2.BidRequest, requestInfo *adapters.ExtraRequestInfo) ([]*adapters.RequestData, []error) {
        // ...
	for _, imp := range request.Imp {
		ext, err := parseExt(imp.Ext)
                // ...
        }
        // ...
}

func parseExt(ext json.RawMessage) (*openrtb_ext.ImpExtMyBidder, error) {
	var bext adapters.ExtImpBidder
	err := json.Unmarshal(ext, &bext)

	// ...
	var adsExt openrtb_ext.ImpExtMyBidder
	err = json.Unmarshal(bext.Bidder, &adsExt)
	
	// ...
	return &adsExt, nil
}
```

If my request POSTed to the adapter looks like this:
```json
{
    ...,
   "imp": [{
     ...,
     "ext": {
         "prebid": {
            "bidder": {
                "mybidder": {
                    "param1": "value"
                }
            }
         }
     }
   }],
   ...
 }
```
It DOES work and I'm getting proper response, however, when I define a json for testing with the same way of passing imp[].ext, the result in tests is:
`MakeRequests had wrong request count. Expected 1, got 0`.

I tried debugging it, and this `bext adapters.ExtImpBidder` contains fields:
```go
type ExtImpBidder struct {
	Prebid *openrtb_ext.ExtImpPrebid `json:"prebid"`

	// Bidder contain the bidder-specific extension. Each bidder should unmarshal this using their
	// corresponding openrtb_ext.ExtImp{Bidder} struct.
	//
	// For example, the Appnexus Bidder should unmarshal this with an openrtb_ext.ExtImpAppnexus object.
	//
	// Bidder implementations may safely assume that this JSON has been validated by their
	// static/bidder-params/{bidder}.json file.
	Bidder json.RawMessage `json:"bidder"`
        // ...
}
```
So in tests, while debugging, I can see that `bext.Bidder` is `nil`, and `bext.Prebid.Bidder` is there, and contains my params.
When debugging this code in actually running pbs, I can see it the other way around - `bext.Prebid` is `nil`, and `bext.Bidder` has my params. And it happens somewhere around here - https://github.com/prebid/prebid-server/blob/4b7dba0ab6a675a1dff0d3bbf86abec0e3e84534/exchange/utils.go#L570 - it moves contents of `Ext.Prebid.Bidder["mybidder"]` to `Ext.Bidder`.
This however DOES NOT happen when running tests.

Documentation here: https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html says
> Publishers will provide extra information using an OpenRTB 2.5 Bid Request Extension, preferably at request.imp[].ext.prebid.bidder.{bidder} but also supported at request.imp[].ext.{bidder}. Prebid Server will validate the publisher information based on your schema and relocate the data to request.imp[].ext.bidder, regardless of your bidder name or the publisher’s chosen location.
So I thought I can try the other syntax, but it also doesn't work consistently.

Sending a request like this:
```json
{
    ...,
   "imp": [{
     ...,
     "ext": {
            "bidder": {
                    "param1": "value"
            }
     }
   }],
   ...
 }
```
Causes http error 400 and following response: `Invalid request: request.imp[0].ext.prebid.bidder contains unknown bidder: bidder. Did you forget an alias in request.ext.prebid.aliases?`, but it does pass in the tests.
I don't think that setting aliases is the way to go here, is it?

Can anyone confirm that I'm doing everything as I should, and it is how it is, requests in tests should be a little different than those going to the actual server, or please help me finding my mistake :)

**Comment by SyntaxNode** [comment]
There is a difference between the bid request you POST to the /auction endpoint and the request you use in adapter tests.

For the /auction endpoint, the preferred location for bidder parameters is `imp.ext.prebid.bidder.BIDDERCODE`. The older location `imp.ext.BIDDERCODE` is still understood by Prebid Server and upgraded by core logic to the preferred location. Prior to sending the bid request to a bidder, information about other bidders is removed and the location of bidder parameters is normalized to `imp.ext.bidder`.  It's at this location that adapters are expected to read their parameters.

For the adapter tests, the request represents the final state after processing by core logic, since adapter tests are validating the adapter code and not Prebid Server core logic. Therefore, your tests should use `imp.ext.bidder`.

Example /auction POST bidder parameters:
```
{
  "imp": [
    {
      "ext": {
        "prebid": {
          "bidder": {
            "mybidder": {
              "param1": "value"
            }
          }
        }
      }
    }
  ]
}
```

Example adapter test bidder parameters:
```
{
  "imp": [
    {
      "ext": {
        "bidder": {
          "param1": "value"
        }
      }
    }
  ]
}
```

**Comment by kamilmclearcode** [comment]
Thanks a lot for quick response and thorough explanation :)
That basically confirms my findings, the only mistake I made was trying to pass params in POST request via `imp.ext.bidder` instead of `imp.ext.BIDDERCODE`. 
But I'm happy it all works as designed.
Thanks again!
