### ISSUE TITLE
Bidder info endpoint: base adapter option

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3079]
The /info/bidders endpoint returns all known adapter names including aliases. In order to help maintain the list of Go/Java adapters, I'd like to have an option on that endpoint to constrain the output to actual (base) adapters, ignoring aliases. Suggestion:

```
/info/bidders?baseAdaptersOnly=true
```

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.275.0.

**Comment by SyntaxNode** [comment]
@bretg Looks like this is implemented in PBS-Java as well? I'll leave it open for confirmation.

**Comment by bretg** [comment]
confirmed
