### ISSUE TITLE
Server-side renderer url metadata

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3085]
This is the server side of PBJS issue https://github.com/prebid/Prebid.js/issues/10434

@ccorbo has proposed a solution that server-side adapters specify `seatbid[].bid[].ext.rendererurl`.

I would counter-propose that this field should go in `seatbid[].bid[].ext.prebid.meta.rendererUrl` , adding this field as `.RendererUrl` alongside `.NetworkID`, etc. 

Note: we added rendering fields for the SDK in https://github.com/prebid/prebid-server/issues/2908

**Comment by ccorbo** [comment]
Thanks Bret, your proposed location sounds goods to me. I can raise a PR to add this field.

**Comment by bretg** [comment]
@ccorbo - could you open a docs PR against https://github.com/prebid/prebid.github.io/blob/master/prebid-server/developers/add-new-bidder-go.md to show the new RendererUrl meta field option?

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.274.0.

**Comment by bretg** [comment]
resolved with PBS-Java 2.2
