### ISSUE TITLE
Prebid.Meta not being fully returned

### ISSUE THREAD

**Issue by ccorbo** [prebid/prebid-server#3101]
When testing out passing through rendererUrl as part of `seatbid[].bid[].ext.prebid.meta.rendererUrl`, which was completed in https://github.com/prebid/prebid-server/pull/3087. I noticed that everything in prebid.meta was being dropped outside of adaptercode.

For example I have a mock response set up with the following seatbid[].bid[].ext:
<img width="586" alt="image" src="https://github.com/prebid/prebid-server/assets/19716777/b0af57a1-c0d1-4feb-a4e1-5d6a547c9664">

For the response, rendererUrl is dropped and only adaptercode is returned in ext.prebid.meta.
Example bid[].ext response:
<img width="346" alt="image" src="https://github.com/prebid/prebid-server/assets/19716777/7eef8019-21d1-4b00-a97f-a92244cd02f3">

This looks to be because the adapter code is being created / set in  prebid.meta before the bid ext is being created. So it never enters this block https://github.com/prebid/prebid-server/blob/master/exchange/exchange.go#L1306

I created a Draft PR with an example of a fix. I would like confirmation that this is actually an issue, and that this approach is appropriate before I go updating all the tests. Want to make sure I'm not missing something obvious.
PR: https://github.com/prebid/prebid-server/pull/3100

Example bid[].ext response with changes in PR running locally:
<img width="611" alt="image" src="https://github.com/prebid/prebid-server/assets/19716777/ff818f62-2e68-4a1a-b357-39af7f599287">

**Comment by bretg** [comment]
Closing this issue as resolved with PR: https://github.com/prebid/prebid-server/pull/3100
