### ISSUE TITLE
cache / external_cache configuration not being applied

### ISSUE THREAD

**Issue by bevenio** [prebid/prebid-server#3175]
Hey 👋

Whenever i try to configure both the cache service (host/scheme/query) and the external cache (host/scheme/path) in either the _pbs.yaml_ or by setting _env variables_ during startup of the server neither of those are set. Also there is no error appearing, telling me what is misconfigured. When it is just the cache config (without external cache) everything works.

> Commit: 13607862cf00ca1a721067772315368eada972ce

pbs.yaml example: 
``` 
cache:
  host: some-service.some-namespace.svc
  scheme: http
external_cache:
  host: some-external-url.com
  scheme: https
  path: /cache
``` 

The logs during startup look something like this, basically empty:
``` 
I1003 08:09:02.308627       7 structlog.go:42]   	cache.scheme: 
I1003 08:09:02.308635       7 structlog.go:42]   	cache.host: 
I1003 08:09:02.308708       7 structlog.go:42]   	cache.query: 
I1003 08:09:02.308716       7 structlog.go:33]   	cache.expected_millis: 10
I1003 08:09:02.308722       7 structlog.go:33]   	cache.default_ttl_seconds.banner: 0
I1003 08:09:02.308726       7 structlog.go:33]   	cache.default_ttl_seconds.video: 0
I1003 08:09:02.308730       7 structlog.go:33]   	cache.default_ttl_seconds.native: 0
I1003 08:09:02.308734       7 structlog.go:33]   	cache.default_ttl_seconds.audio: 0
I1003 08:09:02.308742       7 structlog.go:42]   	external_cache.scheme: 
I1003 08:09:02.308753       7 structlog.go:42]   	external_cache.host: 
I1003 08:09:02.308761       7 structlog.go:42]   	external_cache.path: 
``` 

Is this a bug or intentional behaviour? Unfortunately i did not find anything about this in the docs.

Additional information:
When i overwrite the config defaults in the _config/config.go_ file, everything works as expected.

**Comment by SyntaxNode** [comment]
That's strange behavior. I can't reproduce the issue on the master branch head.

I used the following pbs.yaml:

```
cache:
  host: some-service.some-namespace.svc
  scheme: http
external_cache:
  host: some-external-url.com
  scheme: https
  path: /cache
```

and receive the following logs at startup:

```
I1003 09:48:52.418286   44381 structlog.go:42]   	cache.scheme: http
I1003 09:48:52.418291   44381 structlog.go:42]   	cache.host: some-service.some-namespace.svc
I1003 09:48:52.418296   44381 structlog.go:42]   	cache.query: 
I1003 09:48:52.418301   44381 structlog.go:33]   	cache.expected_millis: 10
I1003 09:48:52.418308   44381 structlog.go:33]   	cache.default_ttl_seconds.banner: 0
I1003 09:48:52.418313   44381 structlog.go:33]   	cache.default_ttl_seconds.video: 0
I1003 09:48:52.418318   44381 structlog.go:33]   	cache.default_ttl_seconds.native: 0
I1003 09:48:52.418323   44381 structlog.go:33]   	cache.default_ttl_seconds.audio: 0
I1003 09:48:52.418331   44381 structlog.go:42]   	external_cache.scheme: https
I1003 09:48:52.418336   44381 structlog.go:42]   	external_cache.host: some-external-url.com
I1003 09:48:52.418342   44381 structlog.go:42]   	external_cache.path: /cache
```

I verified with the debugger that the proper configuration is applied. 

YAML files are white space sensitive. Perhaps you have subtle issue in the whitespace formatting? Or perhaps there is an issue is a surrounding config section which is confusing the parser?

**Comment by bevenio** [comment]
I see, it actually a whitespace problem.. thank you.
So it is expected behaviour to parse as much as possible and ignoring everything that does not respect the yaml format?
