### ISSUE TITLE
Allow User IDs to be passed explicitly

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#320]
## Motivation

Right now, the only way to pass different User IDs for each Bidder is through the Cookie.

Since cookies are sent by the browser automatically, this can't be used to store them manually somewhere (e.g. `localStorage` in `prebid.js`) so they can be sent explicitly in the request.

## Proposal

Allow `bidrequest.user.ext.prebid` to support the following:

```
{
  "buyeruids": {
    "appnexus": "abc",
    "rubicon": "def"
  }
}
```

For any defined `buyeruids` values, the core auction logic would use these values to populate the `request.user.buyeruid` field before forwarding them to the Bidder. It would also delete the `request.user.ext.prebid.buyeruids` field during preprocessing, so that info intended for one Bidder doesn't leak into the others.

If the user's request defines both `request.user.buyeruid` _and_ `request.user.ext.prebid.buyeruids`, we'll return a 400. If defined, `request.user.ext.prebid.buyeruids` will take precedence over the Cookie values. This will be consistent with how we treat other "implicitly populated" fields (user-agent, IP, etc.)

**Comment by bretg** [comment]
Spoke with some folks here. We're fine with this enhancement. We suggest that the DigiTrust user.ext.digitrust should be considered separately from the new bidrequest.user.ext.prebid.buyeruids field. Adapters that support DigiTrust will read both.

**Comment by bretg** [comment]
Pieter points out that an extended ID structure exists in OpenRTB 3. Most importantly, it allows for IDs to be an object, not just a string. 

https://iabtechlab.com/wp-content/uploads/2017/09/OpenRTB-3.0-Draft-Framework-for-Public-Comment.pdf
```
"user": {
 "id": "aaa",
 "buyerid": "xxx",
 "eids": [
 {
 "source": "x-device-vendor-x.com",
 "uids": [
 { "id": "yyy", "atype": 1 },
 { "id": "zzz", "atype": 1 },
{ "id": "DB700403-9A24-4A4B-A8D5-8A0B4BE777D2", "atype": 2 } ]
 },
 {
 "source": "digitru.st",
 "uids": [
 {
 "id":
"IPl4zj44Rhez/VyNE83bYfoz59H5GCIQrfCdAVyN51zcsme0faoH/qfLBijMQEazqGewX
TZsMwMfZqwne8x4eAVeNmAx7iPpk7bpGYp71GUZyysbEEReDYEMJ2hNSldGTT9UExI62Hv
XuBM16X121r0i8Tko2Bps84tQFWb4lJeun/nRzYwj3ehUGjkE3UOxvHoplNqA43n25pRjg
UkUVTR6i/UBWwD4C9dN0bXALC+grpTVLv5Vl4PJ4ir7twHLLow539N3ETb0cHt8GN+VweH
Bc2dGmqUTNQxGUZxBA21omEmotXpfqRKrHUo4fm/O9NFgYRN6W8LaCy3USy8dPQ==",
 "atype": 1,
 "ext": {
 "keyv": 4
 }
 } ]
 },
```

**Comment by dbemiller** [comment]
Both sound good to me.

That's good to know about 3.0. If/when we add support for it, we'll definitely have to re-evaluate what belongs in the `ext` vs. what can be supported by the official spec.

**Comment by hhhjort** [comment]
We should also keep an eye on the 3.0 spec and try to implement what we do for 2.x to be as close to that as practical so we minimize work when moving to 3.0.
