### ISSUE TITLE
Make Cookie TTLs configurable

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#326]
Right now, the TTL on synced User IDs is hardcoded: https://github.com/prebid/prebid-server/blob/master/pbs/usersync.go#L146

For some reason, we need to set a different TTL (I didn't get the details, but @mkendall07 has them)... so we plan to make this configurable.

**Comment by hhhjort** [comment]
I am finding 2 different hard coded TTLs, the one mentioned above and  https://github.com/prebid/prebid-server/blob/master/pbs/usersync.go#L409 which is set to 14 days. Should we be unifying them both to a single TTL?

**Comment by mkendall07** [comment]
No, we should leave the individual TTLs at 14 days and can be left in the code for now.

The uids cookie should be configurable.
