### ISSUE TITLE
Invalid request: Stored Request with ID="xxxxxx" not found.

### ISSUE THREAD

**Issue by maxacademind1** [prebid/prebid-server#3263]
Hi, My local server version was [v0.274.0](https://github.com/prebid/prebid-server/releases/tag/v0.274.0) and i update to [v2.0.0](https://github.com/prebid/prebid-server/releases/tag/v2.0.0). i was able to get ad in old version, but cant in V2.0.0 with same request. it always returns 400 status code and 
Invalid request: Stored Request with ID="xxxxx" not found.
Invalid request: Stored Imp with ID="yyyyy" not found.

**Comment by SyntaxNode** [comment]
The error messages sound like it cannot connect with the Stored Request data store. If you were using the deprecated "postgres" config, you will need to migrate to the new "database" config. Please see the "{stored_requests/stored_video_req/stored_responses}.postgres" section of the [Prebid Server 2.0 announcement issue](https://github.com/prebid/prebid-server/issues/3068), linked to from the release notes.

**Comment by maxacademind1** [comment]
> The error messages sound like it cannot connect with the Stored Request data store.
> 
> If you were using the deprecated "postgres" config, you will need to migrate to the new "database" config. Please see the "{stored_requests/stored_video_req/stored_responses}.postgres" section of the [Prebid Server 2.0 announcement issue](https://github.com/prebid/prebid-server/issues/3068), linked to from the release notes.

thanks for the quick answer. Yes the issue was db config files. Now i uptaded it and it works fine.

**Comment by SyntaxNode** [comment]
I'll update the release notes later to call that change out better. Glad that's all it was.
