### ISSUE TITLE
IPv6 not recognized in XFF header

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3277]
It was reported that our exchange has never received an IPv6 address from any Prebid Server -- not our own PBS, not anyone else running a PBS and using the rubicon adapter, whether PBS-Go or PBS-Java.

We took a dump of our traffic and found very few XFF headers that contain IPv6. Here's one... modified to maintain anonymity
```
X-Forwarded-For: 2001:0DB9:3a80:6b95:6085:2cae:4e36:4923, 170.177.241.107
```

The original algorithm for IPv6 defined in https://github.com/prebid/prebid-server/issues/1332 seems to allow for the case of IPv6 addresses in the XFF header. But when I try this from the command line, only the IPv4 address gets sent through to the bidder in PBS-Java

Would like to confirm this is an issue in PBS-Go as well and if so, determine whether that was on purpose or if somehow both just missed that part of the original issue.

**Comment by SyntaxNode** [comment]
Verified this is not an issue in PBS-Go. With the above example, PBS-Go sets `device.ipv6` to `2001:0DB9:3a80:6b95:6085:2cae:4e36:4923`.

**Comment by Net-burst** [comment]
This is weird. I also verified that PBS-Java correctly sets the `device.ipv6` (but masks the value to `2001:db9:3a80:6b95::`)

**Comment by SyntaxNode** [comment]
Strange. @bretg how did you perform your test?

**Comment by bretg** [comment]
Ok, closing this. Fun that the only two IPv6 addresses that came into our PBS (out of 25k) were bogus/private.
