### ISSUE TITLE
content-type is text/plain - should be application/json

### ISSUE THREAD

**Issue by mark34** [prebid/prebid-server#328]
the response from [PBS]/openrtb2/auction endpoint currently contains the header: 
```
Content-type: text/plain
```
but this is a json response so it should be
```
application/json
```
- Or is there a valid reason for this?
You would normally respond with application/json because it's the agreed content-type for this content and all clients look for this; eg. it allows clients (eg. Postman) to format the response in a user-friendly way.

**Comment by dbemiller** [comment]
I don't think there's a valid reason. Just a bug/overlooked. Thanks for filing the issue!
