### ISSUE TITLE
Http Analytics Adapter

### ISSUE THREAD

**Issue by steffenmllr** [prebid/prebid-server#3281]
We implemented a buffering http analytics adapter - similar to the pubstack adapter but with event filtering -  that uses prebid data for media analytics and user studies / research in the german market.

As many Prebid server hosts require an official integration, I was wondering if you accept PRs for other analytics adapters?

Furthermore, considering we might not be the only ones with this use-case, has there ever been a plan for a generic HTTP analytics adapter?

**Comment by bretg** [comment]
@steffenmllr - we would certainly accept PRs for other analytics adapters, including generic adapters.

The committee is not likely to build one since the main engineering teams involved don't require a generic adapter.

**Comment by muuki88** [comment]
Follow up issue #3388
