### ISSUE TITLE
Ubuntu tests fail

### ISSUE THREAD

**Issue by mark34** [prebid/prebid-server#330]
Hi guys 

I pulled the latest version of prebid-server onto ubuntu 17.10 and ran the tests using ``` go test ```
This gives the error: 

```
./pbs_light_test.go:490: t.Helper undefined (type *testing.T has no field or method Helper)
FAIL    github.com/prebid/prebid-server [build failed]
```

git log shows latest commit : e9b7bd634d781fd8d001374c76c30a97ad600907 

The server seems to run though.

**Comment by dbemiller** [comment]
Sounds like an issue with your Go version. We're designed to run with 1.9, which added that function: https://golang.org/doc/go1.9#test-helper
