### ISSUE TITLE
Open project issue

### ISSUE THREAD

**Issue by DharmikAnghan** [prebid/prebid-server#3334]
hello everyone,
I am trying to open a demo project in that is on it https://github.com/prebid/prebid-mobile-android . when i go in runing stat then a GitHash show error

here is build.gradle file :

apply from: '../android.gradle'
apply from: '../publisher.gradle'
apply from: '../tests.gradle'

android {
    def getGitHash = { ->
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }

    defaultConfig {
        buildConfigField "String", "GitHash", "\"${getGitHash()}\""
        buildConfigField "String", "VERSION", "\"${versionName}\""
        buildConfigField "String", "OMSDK_VERSION", "\"${omSdkVersion}\""
    }
}

dependencies {
    implementation project(":omsdk-android")

    implementation 'androidx.annotation:annotation:1.5.0'

    implementation 'com.google.android.gms:play-services-base:18.1.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.15.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.15.1'

    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
}  

error is:
 error: unclosed string literal
  public static final String GitHash = "Microsoft Windows [Version 10.0.19045.3693]

**Comment by SyntaxNode** [comment]
Why are you asking about the Prebid Android SDK in the Prebid Server repository? There are different teams working on the different Prebid projects. You'll likely get a better response asking this in the https://github.com/prebid/prebid-mobile-android project, Many of us have never built the Android SDK and cannot help resolve build issues.

**Comment by bretg** [comment]
Please re-open over in the android repo
