### ISSUE TITLE
Example pbs.yaml with parameters and recommended values

### ISSUE THREAD

**Issue by sunilchelaramani** [prebid/prebid-server#3357]
Anyone can publish pbs.yaml with parameters and its recommended values. Would be great if also have comments for each parameters like you have config.yaml under prebid-cache

**Comment by bretg** [comment]
We're aware that host company documentation can be improved. Will add this specific request to the overall tracking ticket https://github.com/prebid/prebid-server/issues/2076

In the meantime, perhaps this in-progress PR https://github.com/prebid/prebid-server/pull/3326 might help?
