### ISSUE TITLE
Deals are not working as expected in case of aliased bidder

### ISSUE THREAD

**Issue by Pubmatic-Supriya-Patil** [prebid/prebid-server#3362]
As a part of PR(https://github.com/prebid/prebid-server/pull/3218), new function call NormalizeBidderName is made before calling updateHbPbCatDur (pwtpb_cat_dur) and inside ReadDealTiersFromImp. In case of aliase bidder, its not working as expected. In the bid response from bidder, winning bids contains bidder name as aliase bidder and we are comparing it with core bidder name.So if the bidder is not present in core bidder name list then function is returning from that place without processing anything.

**Comment by gargcreation1992** [comment]
@Pubmatic-Supriya-Patil Requesting you to please share the sample request and response, highlighting the expected behaviour if possible.

**Comment by Pubmatic-Supriya-Patil** [comment]
As per my observation  "pwtpb_cat_dur": "apnx6_50s" is the expected in the bid response under targtting but I am getting                     "pwtpb_cat_dur": "9.00_50s" . Bid category is not getting updated with bidder code because that aliase bidder is not in the list of corebidder. 
Please refer below code where bidderFound is returning false so its not updating category with bidder name.

`func applyDealSupport(bidRequest *openrtb2.BidRequest, auc *auction, bidCategory map[string]string, multiBid map[string]openrtb_ext.ExtMultiBid) []error {
	errs := []error{}
	impDealMap := getDealTiers(bidRequest)

	for impID, topBidsPerImp := range auc.winningBidsByBidder {
		impDeal := impDealMap[impID]
		for bidder, topBidsPerBidder := range topBidsPerImp {
			bidderNormalized, bidderFound := openrtb_ext.NormalizeBidderName(bidder.String())
			if !bidderFound {
				continue
			}
			maxBid := bidsToUpdate(multiBid, bidderNormalized.String())
			for i, topBid := range topBidsPerBidder {
				if i == maxBid {
					break
				}
				if topBid.DealPriority > 0 {
					if validateDealTier(impDeal[bidderNormalized]) {
						updateHbPbCatDur(topBid, impDeal[bidderNormalized], bidCategory)
					} else {
						errs = append(errs, fmt.Errorf("dealTier configuration invalid for bidder '%s', imp ID '%s'", string(bidder), impID))
					}
				}
			}
		}
	}

	return errs
}
`

**Comment by gargcreation1992** [comment]
@Pubmatic-Supriya-Patil openrtb_ext.NormalisedBidderName [function loops](https://github.com/prebid/prebid-server/blob/fb5e8492da15733e9035adfc54029bcb9494944e/openrtb_ext/bidders.go#L525-L532) through coreBidderNames. It may seem looking at the code that aliased bidders are not being set in coreBidderNames as it is not being set explicitly. 
However, Aliased bidders are being set in the [coreBidderNames](https://github.com/prebid/prebid-server/blob/fb5e8492da15733e9035adfc54029bcb9494944e/openrtb_ext/bidders.go#L20-L21) on server startup when we load [BidderInfos](https://github.com/prebid/prebid-server/blob/df072ff78891c49a2e011dcb7dcb2f5f0d9c6d7f/config/bidderinfo.go#L262-L263). So, the issue that you have mentioned may be unlikely due to call to NormalisedBidderName because aliased bidder names are being returned. Therefore requesting you to provide sample request and response.

**Comment by Pubmatic-Supriya-Patil** [comment]
Please refer this request.
` {
                "allimps": 1,
                "at": 1,
                "badv": [
                    "ford.com"
                ],
                "bapp": [
                    "com.foo.mygame"
                ],
                "bcat": [
                    "IAB1-1",
                    "IAB1-2"
                ],
                "bseat": [
                    "nike",
                    "puma"
                ],
                "cur": [
                    "USD"
                ],
                "device": {
                    "carrier": "VERIZON",
                    "connectiontype": 2,
                    "devicetype": 1,
                    "didmd5": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "didsha1": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "dnt": 0,
                    "dpidmd5": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "dpidsha1": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "flashver": "1.1",
                    "geo": {
                        "accuracy": 10,
                        "city": "Mumbai",
                        "country": "Ind",
                        "ipservice": 1,
                        "lat": 72.6,
                        "lon": 72.6,
                        "metro": "Mumbai",
                        "region": "Maharashtra",
                        "regionfips104": "MAHA",
                        "type": 1,
                        "utcoffset": 120,
                        "zip": "123456"
                    },
                    "h": 768,
                    "hwv": "10x",
                    "ifa": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "ip": "192.0.2.1",
                    "js": 1,
                    "language": "en",
                    "lmt": 0,
                    "macmd5": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "macsha1": "EA7583CD-A667-48BC-B806-42ECB2B48606",
                    "make": "Apple",
                    "mccmnc": "310-005",
                    "model": "iPhone X",
                    "os": "iOS",
                    "osv": "10",
                    "ppi": 4096,
                    "pxratio": 1.3,
                    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
                    "w": 1366
                },
                "ext": {
                    "prebid": {
                        "aliases": {
                            "appnexus-1": "appnexus",
                            "pubmatic2": "pubmatic"
                        },
                        "bidadjustmentfactors": {
                            "appnexus-1": 0.9,
                            "pubmatic": 0.9
                        },
                        "bidderparams": {
                            "pubmatic": {
                                "wiid": "9879d39f-a5a4-404f-826c-2d30c857af54"
                            }
                        },
                        "debug": true,
                        "floors": {
                            "enforcement": {
                                "enforcepbs": true
                            },
                            "fetchstatus": "none",
                            "location": "noData"
                        },
                        "macros": {
                            "[PLATFORM]": "2",
                            "[PROFILE_ID]": "19191",
                            "[PROFILE_VERSION]": "1",
                            "[UNIX_TIMESTAMP]": "1702981476",
                            "[WRAPPER_IMPRESSION_ID]": "9879d39f-a5a4-404f-826c-2d30c857af54"
                        },
                        "returnallbidstatus": true,
                        "server": {
                            "datacenter": "",
                            "externalurl": "//ow.pubmatic.com",
                            "gvlid": 0
                        },
                        "supportdeals": true,
                        "targeting": {
                            "includebidderkeys": true,
                            "includebrandcategory": {
                                "primaryadserver": 0,
                                "publisher": "",
                                "skipdedup": true,
                                "translatecategories": false,
                                "withcategory": false
                            },
                            "includewinners": true,
                            "mediatypepricegranularity": {},
                            "pricegranularity": {
                                "precision": 2,
                                "ranges": [
                                    {
                                        "increment": 0.5,
                                        "max": 100,
                                        "min": 0
                                    }
                                ]
                            }
                        },
                        "transparency": {
                            "content": {
                                "pubmatic": {
                                    "include": true,
                                    "keys": [
                                        "title"
                                    ]
                                }
                            }
                        }
                    }
                },
                "id": "1559039248176",
                "imp": [
                    {
                        "bidfloor": 1,
                        "bidfloorcur": "USD",
                        "displaymanager": "PubMaticSDK",
                        "displaymanagerver": "PubMaticSDK-1.0",
                        "exp": 1,
                        "ext": {
                            "data": {
                                "pbadslot": "/43743431/DMDemo"
                            },
                            "prebid": {
                                "bidder": {
                                    "appnexus-1": {
                                        "dealtier": {
                                            "mindealtier": 4,
                                            "prefix": "apnx"
                                        },
                                        "placementId": 234234
                                    },
                                    "pubmatic": {
                                        "adSlot": "/43743431/DMDemo@0x0",
                                        "dealtier": {
                                            "mindealtier": 5,
                                            "prefix": "pubdeal"
                                        },
                                        "publisherId": "5890",
                                        "wiid": "9879d39f-a5a4-404f-826c-2d30c857af54",
                                        "wrapper": {
                                            "profile": 19191,
                                            "version": 1
                                        }
                                    }
                                }
                            },
                            "tid": "faeff1e7-cd42-4857-b356-35506fdb6a35"
                        },
                        "id": "28635736ddc2bb2",
                        "iframebuster": [
                            "1"
                        ],
                        "instl": 1,
                        "pmp": {
                            "deals": [
                                {
                                    "at": 1,
                                    "bidfloor": 1,
                                    "bidfloorcur": "USD",
                                    "id": "123",
                                    "wadomain": [
                                        "WD1",
                                        "WD2"
                                    ],
                                    "wseat": [
                                        "IAB-1",
                                        "IAB-2"
                                    ]
                                }
                            ],
                            "private_auction": 1
                        },
                        "secure": 0,
                        "tagid": "/43743431/DMDemo",
                        "video": {
                            "api": [
                                1,
                                2
                            ],
                            "battr": [
                                5,
                                6,
                                7
                            ],
                            "companiontype": [
                                1,
                                2,
                                3
                            ],
                            "delivery": [
                                2
                            ],
                            "h": 360,
                            "linearity": 1,
                            "maxbitrate": 2000,
                            "maxduration": 50,
                            "maxextended": 10,
                            "mimes": [
                                "video/3gpp",
                                "video/mp4"
                            ],
                            "minbitrate": 1000,
                            "minduration": 10,
                            "placement": 5,
                            "playbackend": 1,
                            "playbackmethod": [
                                1
                            ],
                            "pos": 7,
                            "protocols": [
                                2,
                                3,
                                5,
                                6
                            ],
                            "sequence": 1,
                            "skip": 1,
                            "skipafter": 10,
                            "skipmin": 5,
                            "startdelay": 1,
                            "w": 280
                        }
                    }
                ],
                "regs": {
                    "ext": {
                        "gdpr": 1,
                        "us_privacy": "1YNN"
                    }
                },
                "site": {
                    "cat": [
                        "IAB1-5"
                    ],
                    "content": {
                        "album": "Action",
                        "artist": "GeorgeLucas",
                        "cat": [
                            "IAB1-1",
                            "IAB1-2"
                        ],
                        "contentrating": "MPAA",
                        "context": 1,
                        "embeddable": 1,
                        "episode": 1,
                        "genre": "Action",
                        "id": "381d2e0b-548d-4f27-bfdd-e6e66f43557e",
                        "isrc": "2",
                        "keywords": "ActionMovies",
                        "language": "en",
                        "len": 12000,
                        "livestream": 1,
                        "prodq": 1,
                        "producer": {
                            "cat": [
                                "IAB1-5",
                                "IAB1-6"
                            ],
                            "domain": "producer.com",
                            "id": "123",
                            "name": "GaryKurtz"
                        },
                        "qagmediarating": 1,
                        "season": "Season3",
                        "series": "StarWars",
                        "sourcerelationship": 1,
                        "title": "StarWars",
                        "url": "http://www.pubmatic.com/test/",
                        "userrating": "9-Stars",
                        "videoquality": 1
                    },
                    "domain": "ebay.com",
                    "id": "123",
                    "keywords": "Cloths",
                    "mobile": 1,
                    "name": "EbayShopping",
                    "page": "http://ebay.com/inte/automation/s2s/pwt_parameter_validation_muti_slot_multi_size.html?appnexus_deal_priority=6&appnexus_video_fixedbid=10&videobid=4&cat=IAB20-3",
                    "pagecat": [
                        "IAB1-5"
                    ],
                    "privacypolicy": 1,
                    "publisher": {
                        "cat": [
                            "IAB1-5"
                        ],
                        "domain": "publisher.com",
                        "id": "5890",
                        "name": "Test Publisher"
                    },
                    "ref": "http://ebay.com/home",
                    "search": "NewCloths",
                    "sectioncat": [
                        "IAB1-5"
                    ]
                },
                "source": {
                    "fd": 1,
                    "pchain": "pchaintagid",
                    "tid": "1559039248176"
                },
                "tmax": 193234,
                "user": {
                    "buyeruid": "45067fec-eab7-4ca0-ad3a-87b01f21846a",
                    "customdata": "StarWars",
                    "data": [
                        {
                            "ext": {},
                            "id": "StarWars",
                            "name": "StarWars"
                        }
                    ],
                    "ext": {
                        "consent": "CO66E0oO66E1fAfZXBDEA6CsAP_AAH_AAAigGktf_X_fb2vj-_599_t0eY1f9_63v-wzjheNs-8Nyd_X_L4Xv2MyvB36pq4KuR4ku3bBAQdtHOncTQmRwIlVqTLsb02Mr7NKJ7LEmlsbe2dYGH9vn9XT_ZKZ70_____7_3______77_-b_4Gktf_X_fb2vj-_599_t0eY1f9_63v-wzjheNs-8Nyd_X_L4Xv2MyvB36pq4KuR4ku3bBAQdtHOncTQmRwIlVqTLsb02Mr7NKJ7LEmlsbe2dYGH9vn9XT_ZKZ70_____7_3______77_-b_4BQMACAtoKABAW0HAAgLaEgAQFtCwAIC2hoAEBbQ8ACAtoiABAW0TAAgLaKgAQFtA"
                    },
                    "gender": "M",
                    "geo": {
                        "accuracy": 10,
                        "city": "Mumbai",
                        "country": "India",
                        "ipservice": 1,
                        "lat": 72.6,
                        "lon": 72.6,
                        "metro": "Mumbai",
                        "region": "Maharashtra",
                        "regionfips104": "MAHA",
                        "type": 1,
                        "utcoffset": 120,
                        "zip": "123456"
                    },
                    "id": "45067fec-eab7-4ca0-ad3a-87b01f21846a",
                    "keywords": "Movies",
                    "yob": 1990
                },
                "wlang": [
                    "EN"
                ],
                "wseat": [
                    "nike",
                    "puma",
                    "reebok"
                ]
            }`

**Comment by VeronikaSolovei9** [comment]
It can be related to the `alternatebiddercodes`. Do you use "groupm" when you see this issue?

**Comment by pm-nilesh-chate** [comment]
@gargcreation1992 I don't think you statement holds true for soft aliases. Did we drop support for soft aliases?, If not, we would need to fix this issue

**Comment by bretg** [comment]
The video endpoint is deprecated. If you guys want to open a PR to fix an issue, fine, but the committee will not prioritize any work on this when the goal is to implement podding/etc in the main auction endpoint.

**Comment by bretg** [comment]
Discussed in committee. This is larger than the video endpoint. We agreed that the way this should look in targeting is:

- hb_bidder=ALIASCODEINORIGINALCASE
- hb_bidder_ALIASCODEINORIGINALCASE=ALIASCODEINORIGINALCASE
- hb_deal_ALIASCODEINORIGINALCASE=123

**Comment by bsardo** [comment]
It appears as though the targeting casing has always used the original casing specified in the request for core bidders and soft aliases so I don't see a problem there. However, a bug was introduced in v2.1.0 preventing deals from being applied to soft aliases.

**Prior to the PBS-Go v2.1.0 release:**
- Deals were applied for registered bidders (core bidders and hardcoded aliases) and soft aliases if they had a case **sensitive** match with the name of a bidder specified in the impression.

**As of the v2.1.0 PBS-Go release:**
- Deals are applied to responses for registered bidders (core bidders and hardcoded aliases) if they have a case **insensitive** match with the name of a bidder specified in the impression
- Soft aliases never have deals applied to them (this is a bug)

**Going forward:**
- Deals should be applied for registered bidders (core bidders and hardcoded aliases) if they have a case **insensitive** match with the name of a bidder specified in the impression
- At a minimum, deals should be applied to soft aliases if they have a case **sensitive** match with the name of a bidder specified in the impression (this was the original behavior prior to the v2.1.0 release). We could expand this so the match is **insensitive** but that could be a future enhancement as it might take a bit more work.

As of this morning, there will be a general discussion soon on the deal tiers feature to evaluate whether it is still needed, and if so, to document the expected behavior. In that case, I suggest moving forward with the case **sensitive** compare on soft aliases while maintaining the current **insensitive** compare for registered bidders.

**Comment by bretg** [comment]
Closed with #3391
