### ISSUE TITLE
Rubicon user sync

### ISSUE THREAD

**Issue by dzesm** [prebid/prebid-server#3435]
Could you please provide explanation on how to integrate Rubicon user sync (PBS Java), as it seems that we have had a bit of miscommunication and our development is stuck in place.

First, we contacted Rubicon and sent them our cookie sync domain to register:  https://prebid.test.domain.com/cookie_sync 
They answered that this is not a correct domain and instead they expect something like this:

https://openrtb.domain.com/api/cookie?partnerId=word-rubicon&userId=$UID (an example).

Also, they said:
"_There are two fundamental steps, below is an example:
 
1) the seller calls our sync endpoint (multi-sync.html?p=word&endpoint=us-east)
2) the URL that the seller sent us is called and we see that the userid parameter is populated with our userid"

But these endpoints already have p key.

Yet, in their documentation it says 
p | Partner key assigned by Rubicon Project, identifying Partner.
endpoint | Exchange API calling data center for user. Value must be one of: “us-east”, “us-west”, “eu” or “apac”.

And in Prebid Server documentation there is this:

If you are utilizing Magnite’s managed service, there’s an extra args parameter:

`<amp-iframe width="1" title="User Sync"
  height="1"
  sandbox="allow-scripts allow-same-origin"
  frameborder="0"
  src="https://GET_URL_FROM_MAGNITE_ACCOUNT_TEAM/prebid/load-cookie.html?endpoint=rubicon&max_sync_count=5&source=amp&args=account:MAGNITE_ACCOUNT_ID">
  <amp-img layout="fill" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" placeholder></amp-img>
</amp-iframe>`

where it clearly says that the URL should be provided by Magnite.

What are we supposed to send as an endpoint, to get a valid endpoint back? We cannot send our cookie_sync endpoint and they expect an endpoint which has partnerId already, but at the same time it is clearly stated that this must be provided by themselves to us.

Username and password we got.

Can you help to clarify this in more detail, please? Thank you.

**Comment by bretg** [comment]
@dzesm - What are you actually trying to do? Your message suggests two possible goals:

1) You're trying to set up a Prebid Server of your own and add rubicon as a bidder
2) You're using Magnite's managed service and want to get usersync working for AMP

These are two very different tasks. I'll comment on both of them:

### Setting up your own PBS

First, please review the general cookie-sync documentation at https://docs.prebid.org/prebid-server/developers/pbs-cookie-sync.html

Rubicon differs from most other adapters in that they're not an open redirector. Here's how it works.

A) In your Prebid Server, you will enter something like the following as the usersync endpoint:

```
https://pixel.rubiconproject.com/exchange/sync.php?p=PARTNERCODE&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&gpp={{gpp}}&gpp_sid={{gpp_sid}}
```
They will provide you the partner code (the 'p' parameter)

B) What you need to provide is the exact runtime domain where you're going to be running your Prebid Server. I agree with them that "https://prebid.test.domain.com/cookie_sync" is suspicious. It should be something like

```
https://prebid-server.mydomain.com/setuid?bidder=rubicon&uid=UID&...
```

Then what happens at runtime is:

1) the browser creates the img pixel and fetches it
2) pixel.rubiconproject.com redirects to your Prebid Server's /setuid endpoint

### AMP

Ok, so then you bring up the AMP load-cookie.html instructions. Note that this has nothing to do with setting up rubicon usersync for your own PBS. If you're a Magnite customer using their Prebid Server, then you can utilize the load-cookie.html instructions on the Prebid.org page. They'll provide the missing details.

If you're trying to figure out how to get AMP sync working on your own Prebid Server, that's a different story. Let us know.

**Comment by bretg** [comment]
@dzesm - I'm going to close this issue. Let me know if this didn't get worked out.
