### ISSUE TITLE
Additional DSA validations

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-server#3438]
Here are some we're looking at in JS when DSA is required:

1. If regs.ext.dsa.pubrender exists and is 2, response adrender should not  = 1
1. If regs.ext.dsa.pubrender exists and is 0, response adrender must = 1
1. regs.ext.dsa.pubrender does not exist, don't do these validations

Also, there are field length validations not defined with the original passthrough requirements. The `paid` and `behalf` response fields should have not more than 100 chars or the response should be rejected.

In any case:
- add an entry in ext.prebid.warning when in debug mode
- use seat nonbid code 305 as the reject reason (305 "Response Rejected - Privacy")

**Comment by bretg** [comment]
I think we need to define new [seat non-bid codes](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/seat-non-bid.md).

Maybe
- 310 "Response Rejected - DSA render mismatch"
- 311 "Response Rejected - DSA consent mismatch"

**Comment by bretg** [comment]
This would be the first instance doing a legal basis check on the bid response. The Go and Java teams will have to look into the impact.

**Comment by bretg** [comment]
Opened PR for the IAB seatnonbid code file to propose code 305 to cover rejecting responses for privacy reasons. https://github.com/InteractiveAdvertisingBureau/openrtb/pull/163

**Comment by bretg** [comment]
As discussed in committee yesterday, pulled the legal basis check out into a separate issue https://github.com/prebid/prebid-server/issues/3508 and made the remaining items here ready-for-dev

**Comment by bsardo** [comment]
> Opened PR for the IAB seatnonbid code file to propose code 305 to cover rejecting responses for privacy reasons. [InteractiveAdvertisingBureau/openrtb#163](https://github.com/InteractiveAdvertisingBureau/openrtb/pull/163)

@bretg just to clarify, I assume we will use 305 if any of the DSA validation checks fail including if the DSA object is required but not present on the bid, is that correct?
I only ask because we previously chose 300 for the required validation check and I also see mention above of possibly proposing two other new codes, 310 and 311, be created.

**Comment by bretg** [comment]
@bsardo - we settled on 305 in the PMC last week. Removed references to the others

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go v2.9.0. We're using seat non-bid code 300 for now and will change it to 305 when that's accepted by the IAB.

**Comment by bretg** [comment]
released with PBS-Java 3.2
