### ISSUE TITLE
Invalid request format: "bidder" query param is required

### ISSUE THREAD

**Issue by dzesm** [prebid/prebid-server#3451]
After calling cookie_sync endpoint from client side and then generating iframe / image based on type, the server calls setuid endpoint. However, even though in the payload there is obviously a bidder parameter, the response still shows an error - _Invalid request format: "bidder" query param is required_.

Screenshots:

![payload](https://github.com/prebid/prebid-server/assets/68564914/c93fd911-0e8b-4a04-9a39-0c7210b57619)
![response](https://github.com/prebid/prebid-server/assets/68564914/070fd4f4-7782-451b-90a2-e60416a2f083)

And this happens for each bidder. Do you know what could be the problem here?

**Comment by SyntaxNode** [comment]
What is your role in the cookie sync process. Are you a publisher or a bidder?

**Comment by SyntaxNode** [comment]
Could you please share the URL generated by the cookie sync endpoint?

**Comment by SyntaxNode** [comment]
Ah, gotcha. I was looking at the wrong part of the url. I'm curious what server is producing the "Invalid Request Format" error. If you posted the exact output of your cookie sync endpoint, the browser should try to redirect to `prebid.test.domain.com` and fail.
