### ISSUE TITLE
`gofmt -l .` fails in the repo root due to `.semgrep/adaptor` files.

### ISSUE THREAD

**Issue by dmitris** [prebid/prebid-server#3475]
`gofmt -l .` prints "spurious" (non-actionable) messages and the command fails with error status code 2 - which becomes a problem with CI setups that use `gofmt` to do verification of the proper Go code formatting. Is there anything that can be done to avoid that error?

Reference from when these semgrep .go files were added:
https://github.com/prebid/prebid-server/pull/2965#issuecomment-1653022800
> The *.go files are added as unit tests for semgrep rules.

/cc @Sonali-More-Xandr

**Comment by onkarvhanumante** [comment]
> `gofmt -l .` prints "spurious" (non-actionable) messages and the command fails with error status code 2 - which becomes a problem with CI setups that use `gofmt` to do verification of the proper Go code formatting. Is there anything that can be done to avoid that error?
> 
> Reference from when these semgrep .go files were added: [#2965 (comment)](https://github.com/prebid/prebid-server/pull/2965#issuecomment-1653022800)
> 
> > The *.go files are added as unit tests for semgrep rules.
> 
> /cc @Sonali-More-Xandr

@dmitris , could run `make format` command from project root folder to format go files

https://github.com/prebid/prebid-server/blob/b200357f116b7c5ece866bf21f5c62e002787b0a/Makefile#L34-L35

Refer this https://github.com/prebid/prebid-server/issues/2925#issuecomment-1639007202 comment, if you want to format any specific file.
