### ISSUE TITLE
The `ext.prebid.bidid` field is often absent

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-server#3476]
## Background

We host a PBS GO v.2.0.0 and build analytics reports from the data collected by a custom analytic adapter. Earlier, we noticed the duplication of the `bid.id` field for some bidders. In order to build proper reports, we switched the `generate_bid_id` config property to `true`. 

## Current Behavior 

A lot of bid responses don't contain the `ext.prebid.bidid` objects. 

There are cases
    - all bids in the response contain the `bidid` 
    - all bids in the response don't contain the `bidid` 
    
Requests are from the same site. 

## Expected behavior 

The `ext.prebid.bidid` object is present in all bids if  `generate_bid_id` is `true`.

**Comment by SyntaxNode** [comment]
Confirmed end-to-end tests on the request endpoints looks good with proper event support. I'll check if there's anything specific to analytics adapters next.

In the meanwhile, please verify your configuration is correctly enabling the generate bid id feature. When Prebid Server starts up, you should see the following in the log:

```
I0212 12:47:29.342581    2258 structlog.go:39]   	generate_bid_id: true
```

**Comment by YuriyVelichkoPI** [comment]
Hi @SyntaxNode !

Thanks for working on it. I'm terribly sorry, but it looks like it was a wrong query due to the time shifts. And I saw the data from the period of time before switching the flag on. Double-checking the later days, I didn't find the empty `bidif` field. 

I'm closing the issue.

**Comment by SyntaxNode** [comment]
Glad it was something simple in the end. No worries.
