### ISSUE TITLE
User sync Issue introduced by PR 2948

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#3477]
I've just found an issue introduced by this PR : https://github.com/prebid/prebid-server/pull/2948 :+1: 

https://github.com/prebid/prebid-server/blob/969313298bb4e644f672c5f9007ccb6245520e5a/usersync/syncer.go#L129

By using `bidderName` it makes that if the usersync key has a different value, then request sent to the bidder won't have any value for the User.BuyerUID openrtb field. 
It happens that this is precisely the case for appnexus adapter which use `adnxs` as a key. It makes that user sync for this bidder no longer works.

**Comment by SyntaxNode** [comment]
PR https://github.com/prebid/prebid-server/pull/2948 accounts for the change from syncer key to bidder name by swapping the `syncersByKey` function for `syncersByBidder`. The syncer key is still used in the Prebid Server cookie, thus no change is necessary for the BuyerID lookup.

I tested this flow to ensure it's working as intended and could not find an issue. Are you experiencing a problem?

**Comment by SyntaxNode** [comment]
@matthieularere-msq This functionality appears to be working correctly. Please confirm if you're seeing an issue in production.

**Comment by matthieularere-msq** [comment]
I happened to have an issue with my setuid endpoint, I guess it was caused by a merge issue with my fork.
