### ISSUE TITLE
Fresh install not allowed to build - ./pbs_light.go:65:15: undefined: metrics

### ISSUE THREAD

**Issue by gustavonecore** [prebid/prebid-server#348]
Hey guys, I was able to get it run my local go stuff with glide
But when I tried the validate script after installing the dependencies on **master** branch
I got this FAIL message, I think is related to the **./pbs_light.go:65:15: undefined: metrics**

```
➜  prebid-server git:(master) ✗ ./validate.sh 
# github.com/prebid/prebid-server
./pbs_light.go:65:15: undefined: metrics
FAIL	github.com/prebid/prebid-server [build failed]
ok  	github.com/prebid/prebid-server/adapters	0.041s
?   	github.com/prebid/prebid-server/adapters/adapterstest	[no test files]
ok  	github.com/prebid/prebid-server/adapters/appnexus	0.079s
ok  	github.com/prebid/prebid-server/adapters/audienceNetwork	0.087s
ok  	github.com/prebid/prebid-server/adapters/conversant	0.063s
ok  	github.com/prebid/prebid-server/adapters/indexExchange	0.052s
ok  	github.com/prebid/prebid-server/adapters/lifestreet	0.057s
ok  	github.com/prebid/prebid-server/adapters/pubmatic	0.070s
ok  	github.com/prebid/prebid-server/adapters/pulsepoint	0.060s
ok  	github.com/prebid/prebid-server/adapters/rubicon	0.090s
?   	github.com/prebid/prebid-server/cache	[no test files]
ok  	github.com/prebid/prebid-server/cache/dummycache	0.028s
ok  	github.com/prebid/prebid-server/cache/filecache	0.035s
ok  	github.com/prebid/prebid-server/cache/postgrescache	0.036s
ok  	github.com/prebid/prebid-server/config	0.031s
ok  	github.com/prebid/prebid-server/endpoints/openrtb2	0.035s
ok  	github.com/prebid/prebid-server/exchange	0.047s
ok  	github.com/prebid/prebid-server/openrtb_ext	0.034s
ok  	github.com/prebid/prebid-server/pbs	0.029s
ok  	github.com/prebid/prebid-server/pbs/buckets	0.028s
ok  	github.com/prebid/prebid-server/pbsmetrics	0.026s
?   	github.com/prebid/prebid-server/prebid	[no test files]
ok  	github.com/prebid/prebid-server/prebid_cache_client	0.046s
?   	github.com/prebid/prebid-server/ssl	[no test files]
ok  	github.com/prebid/prebid-server/stored_requests	0.012s
ok  	github.com/prebid/prebid-server/stored_requests/backends/db_fetcher	0.033s
ok  	github.com/prebid/prebid-server/stored_requests/backends/empty_fetcher	0.011s
ok  	github.com/prebid/prebid-server/stored_requests/backends/file_fetcher	0.010s
ok  	github.com/prebid/prebid-server/stored_requests/caches/in_memory	0.022s
ok  	github.com/prebid/prebid-server/usersync	0.018s
```

I'm missing something?

This is my *env*

```
➜  prebid-server git:(master) ✗ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/onecore/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/29/szv4mjbs3rsbl9zjy90v3sgc0000gn/T/go-build036931192=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

```

I reviewed that file, and looks like it's not imported from anywhere that **metrics** struct.
Btw, this is my first time with go

**Comment by dbemiller** [comment]
hmm... our environments are basically identical. I removed my `~/go` directory, recreated it, followed [our installation steps](https://github.com/prebid/prebid-server#installation) exactly, and it validated fine.

To be honest, this is my first Go project too, so... the issue could be on either one of our ends.

Two candidates come to mind, but.... neither one seems very likely:

- Different Go installations (I'm on 1.9.3 installed via Homebrew)
- Glide cache files (not likely, because glide is supposed to follow the `glide.lock` file

Let me know if you can find more info.

**Comment by gustavonecore** [comment]
Thanks for the insight @dbemiller 
I'll try it a fresh install again and let you know!
Cheers!

**Comment by gustavonecore** [comment]
Alright @dbemiller ,the fresh install was the trick, server is running now!
I think might be related to some wrong env vars that I configured manually after go installation.
Anyway, thanks man!

**Comment by gustavonecore** [comment]
@dbemiller Is there any possibility to reach your personal email to ask some advices to integrate this to an existing custom Ad-server?

**Comment by dbemiller** [comment]
I emailed you. The spam I get from companies scraping old github commits for emails is 👎 as it is.

In all honesty: you may get better advice by opening another Issue about it. I doubt you're the only person trying to do this, and someone else may see the thread and give you answers which I can't.
