### ISSUE TITLE
`go vet ./...` gives lots of output for 'struct literal uses unkeyed fields' issues

### ISSUE THREAD

**Issue by dmitris** [prebid/prebid-server#3481]
running `go vet ./...` in the rebid-server repo root produces over 100 lines of output, all like this:
```
amp/parse.go:76:8: github.com/prebid/prebid-server/v2/privacy/ccpa.ConsentWriter struct literal uses unkeyed fields
amp/parse.go:88:9: github.com/prebid/prebid-server/v2/privacy/ccpa.ConsentWriter struct literal uses unkeyed fields
amp/parse_test.go:287:21: github.com/prebid/prebid-server/v2/privacy/ccpa.ConsentWriter struct literal uses unkeyed fields
amp/parse_test.go:297:21: github.com/prebid/prebid-server/v2/privacy/ccpa.ConsentWriter struct literal uses unkeyed fields
amp/parse_test.go:307:21: github.com/prebid/prebid-server/v2/privacy/gdpr.ConsentWriter struct literal uses unkeyed fields
amp/parse_test.go:332:21: github.com/prebid/prebid-server/v2/privacy/ccpa.ConsentWriter struct literal uses unkeyed fields
```
The full dump is in [gist](https://gist.github.com/dmitris/e024506a96a0444e5d813bd8abb0a6d8).  Do we not use the keyed fields out of principle, or would you consider a change to fix them?  The problem with this is if a CI setup tries to enforce `go vet` compliance on a copy of this repo (possibly combined with custom patches), it fails and stops the build.

Here's Rob Pike's opinion on unkeyed fields: https://groups.google.com/g/golang-nuts/c/Ub1GMMrfgFc/m/4SIWMRRgEQAJ.

**Comment by SyntaxNode** [comment]
> Do we not use the keyed fields out of principle

Nope. It's an intentional part of the design.

> Would you consider a change to fix them? 

Sure. If you have the time, go for it. I think you'll find a lot of the violations in table driven tests. I suggest not doing it all on one PR to make reviews easier. The GitHub UI doesn't scale well to a large number of files changed.

**Comment by SyntaxNode** [comment]
Thank you @dmitris for your contributions to fix this issue.
