### ISSUE TITLE
NET / GROSS Bid adjustments

### ISSUE THREAD

**Issue by gramorris** [prebid/prebid-server#350]
#237 mentions NET revenue in a bid response, I'm wondering if this instead needs to be applied to the bid request. I'm specifically looking at the AMP implementation at the moment where all bid adjustments need to be done on the server. 

In our case we have very few bidders that return NET bids and so in order to equalise the bids we would have to apply the rev share. The reason I'd like control on the bid request is that we, in some cases, apply additional adjustments to bidders where we see discrepancies (could be currency or delivery issues). We also have bidders who return a NET bid but have additional 'ad serving charges' applied to invoices so any NET bid returned in the bid response would still need further adjustment.

**Comment by dbemiller** [comment]
Yeah. This is definitely on the roadmap... but not the immediate one. I'd definitely be willing to look over a more detailed proposal (including APIs) and accept PRs which implement this, though.

Off the top of my head, I think the adjustments belong somewhere in that `request.ext.prebid` structure. Two criteria which come to mind offhand are:

1. Different bid adjustments should be allowed on different aliases for the same Bidder.
2. Bid adjustments should play nicely with the upcoming Currency conversions: see #280 and #281

**Comment by gramorris** [comment]
Is there any documentation on how to debug during development and how we could simulate bid responses?

I did have some contact with Rubicon this week who intimated they might be working on a solution to this although as our only partner who we'd need this for it could be that their solution is just to send NET bids.

I also started this as the currency work looked like it was in hand but that appears to have stalled so that might be a better use of resources as we need that to get Appnexus running.

**Comment by dbemiller** [comment]
If they're working on this feature, it should be assigned to someone so we don't accidentally duplicate work.@bretg please do that if so.

I poked through prebid.js a bit, and this feature might actually be a bit tricky. According to [the prebid.js docs](http://prebid.org/dev-docs/examples/adjust-price.html), the javascript looks something like this:

```
pbjs.bidderSettings = {
      appnexus: {
        bidCpmAdjustment : function(bidCpm){
          // adjust the bid in real time before the auction takes place
          return bidCpm * 0.85;
        }
      }
    };
```

Unfortunately, the `function` API allows arbitrary code, which can't be passed to the server in JSON. I also dipped through the prebid.js history trying to find some discussions on why `function` was chosen here, but I didn't see any.

So the big question I have is:

> How much flexibility does the API need in order to satisfy the most complex legitimate use case?

For example, it seems to me like your use-cases could be covered by something like:

```
{
  "ext": {
    "prebid": {
      "bidadjustmentfactors": {
        "appnexus": 0.76,
        "rubicon": 0.89,
        ...
      }
    }
  }
}
```

This would also satisfy the code sample from prebid.js above.

However, that would be a terrible API if there are also legitimate use-cases out there for a flat adjustment. For example,"reduce every bid from {bidder} by .2".

The more "types" of adjustments, and the more flexible they need to be to support all the use-cases, the more complex it becomes.

In the extreme case, where the server needs to match javascript's _function_-level flexibility, we'd have to do something crazy like this:

```
{
  "ext": {
    "prebid": {
      "bidadjustments": {
        "appnexus": {
          "operation": "subtract",
          "minuend": {
            "operation": "multiply",
            "factors": [0.76, "bid"]
          },
          "subtrahend": 0.2,
        ...
      }
    }
  }
}
```

...but I really hope that's not the case.

**Comment by mjacobsonny** [comment]
@dbemiller -- I don't know of any specific use-cases that require complex arithmetic or operations beyond multiplication.  In any event, the real flexibility from the (float) => float function in JS is the ability to customize beyond hard-coded numeric manipulation.  For example, being able to read from a publisher-hosted file that is regularly updated with, say, average discrepancies across bidders.  As it's probably not possible to replicate this function-level flexibility in Prebid Server, the multiplicative coefficient is probably sufficient.

Unless anyone can propose other legitimate use-cases that require the flexibility above.

**Comment by dbemiller** [comment]
Awesome... thanks for the feedback.

Currency conversions definitely will exist someday. That actually gives us some extra incentive to limit this to a multiplication factor. If we built more complicated transforms here, then we'd have to worry about whether to apply them before or after the currency conversions.

Since multiplication is commutative, though, limiting bid adjustments to conversion factors would be a major simplicity win.

**Comment by dbemiller** [comment]
Ok... I'm going to start development on this. Will be implementing the above:

```
{
  "ext": {
    "prebid": {
      "bidadjustmentfactors": {
        "appnexus": 0.76,
        "rubicon": 0.89,
        ...
      }
    }
  }
}
```
