### ISSUE TITLE
Question about endpoint

### ISSUE THREAD

**Issue by krdzo** [prebid/prebid-server#3538]
Hello.
We want to add new adapter to PBS. Our bidding server works by having a different endpoint for app and site requests.
The adapter will support both site and app requests but we would like to have a dynamic URL that depends on the type of request we received. 
The url will be something like `https://{{.HOST}}.bidding-server.com/openrtb2/` where `{{.HOST}}` will be changed by `app` or `web` depending on which field is populated `request.App` or `request.Site`.

Can we do something like this in our adapter or is this not allowed?

**Comment by bretg** [comment]
@krdzo - Given that you were kind enough to ask this question, you might be aware of the conversation at https://github.com/prebid/prebid-server/issues/2612#issuecomment-1826789118

 The part about dynamic hostnames that bothers us is the unlimited nature -- one adapter could force PBS to do thousands (millions) of DNS lookups if it depends on a request parameter that can be abused.

But if I understand it correctly, what you're asking for here is exactly 2 DNS names. Something like:

https://site-reqs.bidding-server.com
https://app-reqs.bidding-server.com

Assuming this is coded in such a way that the adapter strictly controls the existence of exactly two endpoints, this would be fine.

**Comment by krdzo** [comment]
@bretg Thank you for the answer, I tried to search trough the issues but missed the one that you linked.

Yes you understood this correctly. We will only have two endpoints and they will be fixed.
