### ISSUE TITLE
Panic in Bid Adjustment

### ISSUE THREAD

**Issue by linux019** [prebid/prebid-server#3543]
I have added an account in "stored_request"
```
{
  "id": "someid",
  "name": "name",
  "disabled": false,
  "debug_allow": true,
  "cache_ttl": {
    "banner": 600,
    "video": 3600,
    "native": 3600,
    "audio": 3600
  },
  "events": {
    "enabled": true
  },
  "bidadjustments": {
    "mediatype": {
      "banner": {
        "rubicon": {
          "rule1": [
            {
              "adjtype": "type1",
              "value": 2,
              "currency": "USD"
            }
          ]
        }
      }
    }
  }
}
```
With request to `/openrtb2/auction` which doesn't have set up bid adjustment in pbjs the server panics at 
https://github.com/prebid/prebid-server/blob/14fcbb780bc649da67d927a834b425872de35ffb/bidadjustment/build_rules.go#L73 because `extPrebid.BidAdjustments = nil`

```
2024/02/26 14:07:48 http: panic serving [::1]:46572: runtime error: invalid memory address or nil pointer dereference
goroutine 157 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1868 +0x13d
panic({0x1647800?, 0x20f1ee0?})
        /usr/lib/go/src/runtime/panic.go:920 +0x290
github.com/prebid/prebid-server/v2/bidadjustment.merge(0xc000225810, 0xc00defa6f0)
        .../prebid-serve/bidadjustment/build_rules.go:73 +0x20e
github.com/prebid/prebid-server/v2/bidadjustment.Merge(0xc000225810, 0xc00defa6f0)
        .../prebid-serve/bidadjustment/build_rules.go:42 +0x5d
github.com/prebid/prebid-server/v2/exchange.(*exchange).HoldAuction(0xc00049d000, {0x1a5e048, 0xc0005450a0}, 0xc00023b500, 0xc00f924000)
        .../prebid-serve/exchange/exchange.go:329 +0x1778
github.com/prebid/prebid-server/v2/endpoints/openrtb2.(*endpointDeps).Auction(0xc008af86c0, {0x1a5b0d0, 0xc00893d240}, 0xc00524d700, {0x7f7bb17878d0, 0xc008930db0, 0x7f7bb17878d0})
        .../prebid-serve/endpoints/openrtb2/auction.go:263 +0x145f
github.com/prebid/prebid-server/v2/router.log400AndResponseBody.func2({0x1a5afe0, 0xc000495880}, 0xc00524d700, {0x0, 0x0, 0x0})
        .../prebid-serve/router/router.go:184 +0x423
```

It can be fixed by adding more validation on the incoming `ext.prebid` but I'm not sure should server ignore bid adjustment from the incoming request and take in account rules from the accounts in "stored_requests"
The malformed or incorrect request can cause a panic in PBS

**Comment by bretg** [comment]
Thanks for the bug report @linux019 - I think you mean that you created this as an account config -- this isn't ORTB so isn't a stored request.

But more helpfully, I looked back over the [original issue](https://github.com/prebid/prebid-server/issues/2085) and have some comments on the syntax:

```
  "bidadjustments": {
    "mediatype": {
      "banner": {
        "rubicon": {
          "rule1": [    // the third level is supposed to be a dealID, not a rule. This shouldn't cause a panic, but this block would only apply to a deal with ID "rule1".
            {
              "adjtype": "type1",  // this is invalid. "adjtype must be cpm, multiplier, or static". Am guessing this is the cause of the panic.
              "value": 2,
              "currency": "USD"
            }
          ]
        }
      }
    }
  }
```
Changing the adjtype may resolve the panic?

Apparently we neglected to document this feature on docs.prebid.org, so this issue will track fixing the panic and adding the docs.

**Comment by linux019** [comment]
> adjtype": "type1",  // this is invalid. "adjtype 

It doesn't help. The code expects non-empty Bidadjustments object
https://github.com/prebid/prebid-server/blob/14fcbb780bc649da67d927a834b425872de35ffb/bidadjustment/build_rules.go#L73

The panic doesn't occur if payload has empty "bidadjustments" object.
```
{
    // ...
    "ext": {
        "prebid": {
             "bidadjustments": {},
         }
    },
}
```
If presence of "bidadjustments" object should doesn't matter for PBS I can write a simple fix to remove the panic in case of absence of `ext.prebid.bidadjustments` in the payload

**Comment by bretg** [comment]
Thanks. Odd bug - seems like one that would have been discovered in testing or prod long ago. Looking forward to a analysis from @bsardo

**Comment by SyntaxNode** [comment]
Thank you @linux019 for opening a PR to fix it. Closing this issue as the fix is imminent.
