### ISSUE TITLE
Discrepancy between documentation and code For  Improve Digital bidder

### ISSUE THREAD

**Issue by AvinashKapre** [prebid/prebid-server#3583]
As per the documentation of [ Improve Digital ](https://docs.prebid.org/dev-docs/pbs-bidders.html#improvedigital) bidder, bid params mentioned are ```placementId``` and ```publisherId``` as required, however in [adapter code ](https://github.com/prebid/prebid-server/blob/master/static/bidder-params/improvedigital.json) either ```placementId``` or both ```publisherId``` and ```placementKey``` is required. there is nothing mentioned about the ```placementKey``` in the documentation.

**Comment by bretg** [comment]
Thanks @AvinashKapre - I sent email to the the maintainer address on file. Also pinging @jbartek25 .

I suspect the solution is a docs update, but will need to let them confirm this.

**Comment by jbartek25** [comment]
Documentation is correct. Improve Digital started requiring both placementId and publisherId and this was communicated with all our customers. However, we can't reflect it in the adapter schema just yet until all customers start providing publisherId. At the same time, once the schema update is ready, we will also deprecate placementKey. The current schema works fine with placementId+publisherId combination as this is satisfied by the first condition https://github.com/prebid/prebid-server/blob/master/static/bidder-params/improvedigital.json#L40

Unless there are other concerns, this issue can be closed.

**Comment by bretg** [comment]
Thanks for the quick response @jbartek25 . Maybe a comment in the schema?

@AvinashKapre - did you notice this due to a problem?

**Comment by AvinashKapre** [comment]
Hi @bretg, got the comment from @jbartek25 this issue can be closed.
