### ISSUE TITLE
Best approach to integrate Prebid into existing Ad-server

### ISSUE THREAD

**Issue by gustavonecore** [prebid/prebid-server#359]
Hi guys, I'm currently working on an API responsible to manage several ad-networks, this API is largely used from like 2 years by a mobile App, so our current stack is pretty good on scaling and adding new ad networks to the existing list.

So, the flow is like this:

1. Mobile App call our API to get a list of available networks.
2. API using an internal balancer selects the right ad network (using some admin configurations) and return that info to the APP.
3. APP get the network from the response, and uses the related SDK to call the proper AD and show it into the Ad View.
4. APP call some API endpoints to notify when the Ad was viewed and impressed.

Following this scenario, how looks like a proper approach to use Prebid?

From my understanding, Prebid needs to know the full list of ad networks to make the proper ad bidding auctions calls, so in that way I need to setup my existing networks in Prebid, e.g: mopub/admob/airfind and so on?

For the last ones, I don't see adapters for those, I need to create them?
Any comment will help!

Regards.

**Comment by dbemiller** [comment]
It sounds like our goals are exactly the same, to me. We both want to aggregate demand from as many sources as possible, so that publishers can run an auction and pick the highest bid.

In our case, there are Prebid Mobile libraries for [iOS](https://github.com/prebid/prebid-mobile-ios) and [Android](https://github.com/prebid/prebid-mobile-android) which interact with Prebid Server to display ads in the App.

If you want to use Prebid, it sounds to me like we should collaborate. You're correct that we need Adapters for any demand sources which aren't in the project already. We'll definitely welcome PRs if you want to contribute some to the project! Docs can be found here: https://github.com/prebid/prebid-server/blob/master/docs/developers/add-new-bidder.md

**Comment by gustavonecore** [comment]
@dbemiller
- How do you code a new adapter?.. I mean, if I want to integrate Network X, how I need to define the bidding process stuff for them if they are the responible for creating his own rules ... I'm confused on that point. 
- If my current stack it's responsible to bring a selected list of networks (using custom rules that we have defined) and then choose one and get the Ad using the vendor SDK. How prebid could fit in this architecture? It's possible or should I need to re-structure the entire flow to include Prebid an his auctions processes?

**Comment by dbemiller** [comment]
Network X needs to have a public endpoint which Prebid can reach somehow. The adapter code in Prebid Server is just responsible for transforming one of the requests to `/openrtb2/auction` in Prebid Server into a request that their endpoint understands, and then transforming one of the responses from their endpoint into one which Prebid Server understands.

>  it's responsible to bring a selected list of networks (using custom rules that we have defined) and then choose one and get the Ad using the vendor SDK. How prebid could fit in this architecture?

There are really two ways to use Prebid Server (that I know of).

1. You could make the client code (JS, Mobile SDK, etc) call Prebid Server directly, and then add an adapter for your server to this project. In effect you would become a source of ads, and Prebid Server would run the auction with your bids alongside everyone else's.

2. You could host Prebid Server locally and use it to get extra demand, and then return those bids alongside your own.

Given that you choose which ad networks to call based on custom rules you've defined, it sounds like (2) may more likely be the architecture you're looking for.

**Comment by dbemiller** [comment]
Please note also that there's a prebid code of conduct around "wrappers". : http://prebid.org/wrapper_code_of_conduct.html

We expect anyone using Prebid Server in this way to uphold those principles for a fair auction.

**Comment by gustavonecore** [comment]
Thanks for the insight @dbemiller 
I'll read the doc!
And yes, the second approach is the best suit for our current stack.

Just a quick question. Do we still need an account in the prebid website (where you configure your json setups, here: `https://prebid.adnxs.com` ) or that should be installed locally too (because I searched that inside the prebid server and it doesn't have those views..)?
If not, what are the constraints to use that service? is there any api key access to use it? or some api rate limit rule in there?

Best Regards and thanks agains for your help

**Comment by gustavonecore** [comment]
Thanks @dbemiller 
I think that I found what I was searching for, the bidder param configuration files.
That's the main goal of that prebid website, just to create those files.

Best regards!
