### ISSUE TITLE
access to slack

### ISSUE THREAD

**Issue by Abramovic** [prebid/prebid-server#36]
I tried joining https://redditadops.slack.com/ but it looks like you need a ranker.com email. What's the best way to join the slack group?

**Comment by bokelley** [comment]
I think I can invite you - email me at bokelley at appnexus dot com

**Comment by Abramovic** [comment]
thanks, I just sent you an email!

**Comment by Abramovic** [comment]
got the invite. thanks again!

**Comment by yassineadissa** [comment]
Hello Could you invite me too ?  I'll send an email . 
Many thanks !
