### ISSUE TITLE
Focus ORTB downgrade to 2.5 on ext fields only

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3613]
As learned in https://github.com/prebid/prebid-server/issues/3609, bid adapters have pretty much ignored the email we sent in January asking them to work towards supporting ORTB 2.6... only 4 of 200 adapters has declared support for 2.6 in PBS-Java.

There are two types of changes:

- `ext` fields moving. These are the main problems. It's likely that many adapters are not capable of recognizing regs.gdpr when they expect it on regs.ext.gdpr. 
- new fields. e.g. plcmt, gpp. These should be ignored by adapters if they can't deal with them.

So facing the reality of the situation, this issue proposes changing what was defined in https://github.com/prebid/prebid-server/issues/2139 . We're going to change the "downgrade to 2.5" process to focus the downgrade process on the ext fields only. All fields new to ORTB 2.6 will passed through to bidders. If they choke, the adapter will need to be updated.

Here are the `ext` field behaviors:

- move source.chain to source.ext.schain
- move user.eids to user.ext.eids
- move regs.gdpr to regs.ext.gdpr
- move regs.us_privacy to regs.ext.us_privacy
- move user.consent to user.ext.consent.
- **copy** imp[].rwdd to imp.ext.prebid.is_rewarded_inventory - note that this is a copy and not a move. Send both fields through to bidders. This is because rwdd is a new field for ORTB, is_rewarded_inventory was a Prebid-specific thing, and the value is short so doesn't add many bytes.

**Comment by SyntaxNode** [comment]
Fully implemented in PBS-Go v3.0.0.
