### ISSUE TITLE
Default timeout for AMP requests

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#365]
Default timeout on the AMP side of a request is 1000 ms. We should set a default timeout of 900 or 950 ms on the stored request if none is supplied to insure we can get our response back in time.

**Comment by mkendall07** [comment]
Spoke to Brad over at AMP and they are going to add a default token for passing through the timeout value specified on the client side or default timeout.

So you can expect to receive a timeout value on the request like this:
<endpoint>?tag_id=123459&timeout=<timeout_ms>

**Comment by hhhjort** [comment]
That would be useful. Should also probably set the prebid timeout to be less than this if given a larger one.

**Comment by cirla** [comment]
I think this can be closed with https://github.com/prebid/prebid-server/pull/416 and https://github.com/prebid/prebid-server/pull/441 merged.
