### ISSUE TITLE
GDPR - attempting to pass data into user.ext.consent returns error

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/prebid-server#371]
**Context/Problem** 

As part of the GDPR spec for prebid.js, I need to pass an encoded user string into the pbs request object through the field `user.ext.consent`.  Currently, when I'm attempting to pass a value in this field, pbs is returning the following error:
`Invalid request format: request.user.ext should not be an empty object.`

When I looked into the code, I traced this error back to `auction.go:400-403`:
```
if userExt.DigiTrust == nil {
				// Make sure that user.ext is not empty.
				if userExt.Prebid == nil {
					return errors.New("request.user.ext should not be an empty object.")
```

It seems like only two potential values are accepted in the `user.ext` field; `Prebid` and `DigiTrust`.  

**Request**
Can we alter the validation logic and/or add support for the `user.ext.consent` field as well?

**Additional info**
For reference, below is a copy of my request object that erred out:
```
{"id":"660b2341-50d2-45bb-9594-82abd8ae1b50","site":{"publisher":{"id":"a3de7af2-a86a-4043-a77b-c7e86744155e"}},"source":{"tid":"660b2341-50d2-45bb-9594-82abd8ae1b50"},"tmax":1000,"imp":[{"id":"/19968336/header-bid-tag-0","ext":{"appnexus":{"placementId":10433394}},"banner":{"format":[{"w":300,"h":250},{"w":300,"h":300}]}},{"id":"/19968336/header-bid-tag1","ext":{"rubicon":{"accountId":1001,"siteId":113932,"zoneId":535510}},"banner":{"format":[{"w":300,"h":250}]}}],"test":1,"user":{"ext":{"consent":"BOJ5g/KOJ5g/KABAB8AAAAAZ+A=="}}}
```

**Comment by dbemiller** [comment]
I'll go fix this... I tend to make APIs restrictive until proven otherwise :). Sounds like I got a little over-eager here.
