### ISSUE TITLE
Prebid Adapter Issue

### ISSUE THREAD

**Issue by Privir** [prebid/prebid-server#3716]
I am facing the issue that the bidder does not exist how do I resolve this issue?
Please help to resolve this issue.

**Comment by bretg** [comment]
Sorry @Privir - gonna need more detail than that. Are you using someone else's production Prebid Server and getting the warning or are you trying to spin one up yourself and not seeing a particular adapter?

I believe that PBS-Go has most adapters enabled by default but not all. e.g. rubicon must be specifically set to `disabled: false` in the YAML (static/bidder-info/BIDDER.yaml). PBS-Java doesn't enable any bidders by default... set them to `enabled: true` in the application.yaml.

**Comment by bretg** [comment]
@Privir - have you solved your issue?

**Comment by Privir** [comment]
Yes
