### ISSUE TITLE
Metrics resets when restarting the server

### ISSUE THREAD

**Issue by sergiosrax** [prebid/prebid-server#372]
I'm having an issue that all metrics going to influxdb goes back to 0 when turning off and on the server.

![image](https://user-images.githubusercontent.com/33044447/36815576-0529c0b6-1c90-11e8-96e4-c6e9e7b8416b.png)

Query for the graph: SELECT DERIVATIVE(max("count"), 5m) AS "requests" FROM "metrics"."autogen"."prebid.requests.meter" WHERE time > now() - 1h GROUP BY time(5m) FILL(0)

Query: SELECT max("count") AS "requests" FROM "metrics"."autogen"."prebid.requests.meter" WHERE time > now() - 1h GROUP BY time(5m) FILL(0)

date,requests
2/27/2018 4:55:00 PM,1
2/27/2018 5:00:00 PM,1
2/27/2018 5:05:00 PM,1
2/27/2018 5:10:00 PM,3
2/27/2018 5:15:00 PM,4 <- I pushed some changes that rebuild the application and so restarted the app
2/27/2018 5:20:00 PM,1
2/27/2018 5:25:00 PM,1

What I'm expecting is either when doing GetOrRegisterMeter it starts with the already saved data for the registry or at least restart each time the data is sent to influx.

Does anyone has a suggestion on this?

**Comment by dbemiller** [comment]
That would be... difficult. `go-metrics` (the library used to capture & export these metrics) stores things in memory, so they will definitely reset from 0 after an app restart.

Seems like the only way to work around this is to write them somewhere persistent as the app shuts down, and then read them & initialize the metrics with those values when it starts back up again.

That's got plenty of issues too, though. Besides being complicated, it's not fault tolerant in the event of unexpected shutdowns. I also googled a very little bit and couldn't find anyone discussing this issue in `go-metrics` or anywhere related to time series DBs... which makes me think that it's not a problem people are generally interested in solving.

Do you mind if I ask what your use-case is? There may be better tools than go-metrics/influx to get them.

**Comment by sergiosrax** [comment]
HI @dbemiller 

I'm actually using normal instance of Prebid Server, I did some tweaks to match my use case but nothing big and nothing directly into the metrics usage.

And yes I also google it and haven't found a ticket mentioned this, but I think is a bit strange to get the metrics restarted once the app restart but is also true that once released is not expected to have many changes on the instance, what I suspect is that I don't have the right queries.

But also I think makes a bit more sense is that each at the end of the tick cycle it automatically restart the tick value, but not sure if really good nor the way to do it.

At the end I want to know values of the metrics for reporting, that reporting won't be used to charge but more for monitoring and comparing data

**Comment by dbemiller** [comment]
@sergiosrax hey, sorry about the late reply.

I think there's a bit of a misunderstanding about how to use and interpret go-metrics here. The metrics you're looking at use Meters, which are documented [here](http://metrics.dropwizard.io/4.0.0/manual/core.html#man-core-meters) (go-metrics is a Go port of this Java library).

> Meters measure the rate of the events in a few different ways. The mean rate is the average rate of events. It’s generally useful for trivia, but as it represents the total rate for your application’s entire lifetime (e.g., the total number of requests handled, divided by the number of seconds the process has been running), it doesn’t offer a sense of recency. Luckily, meters also record three different exponentially-weighted moving average rates: the 1-, 5-, and 15-minute moving averages.

If you're trying to get a QPS measurement using data averaged over the last 5 minutes, you'd want something more simple, like this:

> SELECT "m5" FROM "prebid.requests.meter"

The "m5" is a weighted average of the counts over the last 5 minutes, with extra weight given to more recent data points. It's calculated by the code, so you don't have to worry about calculating it in your Influx queries. There's also an "m1" and "m15" for 1-minute and 15-minute averages.
