### ISSUE TITLE
server status

### ISSUE THREAD

**Issue by rajeshb10** [prebid/prebid-server#3721]
Error Message : {"description":"Server status is not ok!","status":"SERVER_STATUS_WARNING"}

**Comment by SyntaxNode** [comment]
This is an open source project which is hosted by other companies. Prebid does not host its own servers. Please contact the company you're using to host Prebid Server. If this is instead a bidder issue, please reach out to the bidder with their contact information in the /static/bidder-info/<bidder>.yaml file.

**Comment by rajeshb10** [comment]
Logs for SDK not initialized

Error Message : {"description":"Server status is not ok!","status":"SERVER_STATUS_WARNING"} 
 this the error message appears when open my app in android device

**Comment by SyntaxNode** [comment]
You may contact the creator of the app if you're having a problem. We cannot help you here. This is an open source project, not affiliated with any host or any app.

**Comment by rajeshb10** [comment]
I/flutter (23623): PrebidFlutterPlugin AdInstanceManager >>>>>Ad with id `6` is not available for onFailedToShowFullScreenContent
I/flutter (23623): Banner Ad failed to load: SDK internal error: WinnerBid is null when executing onPrebidSdkWin.
is this errors are causing from server side ?
