### ISSUE TITLE
Stop hard-failing on unknown imp.ext values

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3735]
One of the RTD modules starting putting data on imp.ext, and PBS is choking on it. 

This isn't right... imp.ext should be for everyone to use... PBS shouldn't assume that every value in that ext must be a bidder to the point where it hardfails.

Instead, if an unknown value in imp.ext is found, PBS should do the following:

1. If imp.ext.prebid.bidder exists, then do nothing. The requestor has moved to the new syntax where bidders are in imp.ext.prebid and there's no need to check imp.ext anymore. Let it through.
2. If imp.ext.prebid.bidder doesn't exist, then it's ok to **warn** about unknown values, but the request should otherwise proceed.

Note: we already make exceptions for many imp.ext values: ae, all, context, data, general, gpid, prebid, skadn, and tid. We can keep these special cases to reduce the number of warnings emitted.

Test cases:

1. Add imp.ext.foo and imp.ext.prebid.bidder.appnexus to the request. There should be no warnings. imp.ext.foo should be passed to bidders.
2. Add imp.ext.foo and imp.ext.appnexus to the request. There should be a warning about an unknown bidder "foo". imp.ext.foo should be passed to bidders.
3. Add imp.ext.gpid and imp.ext.appnexus to the request. There should be no warnings. imp.ext.gpid should be passed to bidders.

**Comment by Slind14** [comment]
One option might be adding it to the list of reserved names but that is an inclusive list:

https://github.com/prebid/prebid-server/blob/7702a78118cf56ebf2a4e998f4757b01640ef404/openrtb_ext/bidders.go#L251

**Comment by bretg** [comment]
> adding it to the list of reserved keys

I suppose that would be faster, but I'd like to fix this once and for all

**Comment by bretg** [comment]
This is a high priority because imp.ext.igs is now a thing.

**Comment by vraybaud** [comment]
Hey, gentle bump
Please do we have any update about this issue ? 
We want to use Fledge with PBS but it looks like it's not possible with latest version of paapi PBJS module because of `imp.ext.ae` being replaced by `imp.ext.igs.ae`.

**Comment by bretg** [comment]
Released with PBS-Java 3.9

**Comment by bretg** [comment]
I pinged the PBS-Go team with a reminder. It might get done sooner if a community member was willing to port it to Go from PBS-Java...

**Comment by bsardo** [comment]
There's already a PR open for PBS-Go. #3878 addresses this. We're actively reviewing it.

**Comment by bretg** [comment]
Released with PBS-Go 3.3
