### ISSUE TITLE
sdk internal error

### ISSUE THREAD

**Issue by rajeshb10** [prebid/prebid-server#3739]
SDK internal error: WinnerBid is null when executing onPrebidSdkWin.}

**Comment by bretg** [comment]
@rajeshb10 - any particular reason you opened this in the Prebid Server repo rather than one of the Prebid SDK repos?

I suggest moving this to https://github.com/prebid/prebid-mobile-ios/issues or https://github.com/prebid/prebid-mobile-android/issues
