### ISSUE TITLE
Bidder for beachfront.com

### ISSUE THREAD

**Issue by muncha** [prebid/prebid-server#375]
I'm building a A bidder for beachfront.com

This is for the openrtb2/auction endpoint only. The legacy methods will return, but don't do anything. I'm currently testing against prebid.js #2102 for banner and video. I still have all the test cases to write.

**Comment by dbemiller** [comment]
cool! Thanks for letting us know.

Just FYI: if you don't want to support the legacy methods, then you don't need to implement them on your adapter. You can just register the MisconfiguredAdapter, found [here](https://github.com/prebid/prebid-server/blob/master/adapters/legacy.go#L79) directly into the legacy exchange, found [here](https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L774)

**Comment by dbemiller** [comment]
@muncha any update on this?

**Comment by muncha** [comment]
Sorry - I missed that update request! 
I'm actually getting stuff together right now to put in a pull request.

**Comment by muncha** [comment]
I'm at 85.0% coverage right now. I'll have that to > 90%  shortly and I should be able to put in the request tomorrow.

**Comment by muncha** [comment]
I've got my pull request in - #538.

(fingers crossed)

**Comment by dbemiller** [comment]
This was merged and released. Closing.
