### ISSUE TITLE
no winning bid

### ISSUE THREAD

**Issue by rajeshb10** [prebid/prebid-server#3756]
loadAdError: There is no winning bid in the bid response.

**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by bretg** [comment]
@rajeshb10 - you sound like a developer... you have to understand this isn't nearly enough to identify a problem. I'm going to close this issue. You can open a new one with an appropriate level of detail:

- What are you trying to do?
- What version of PBSDK and Prebid Server are you using?
- Why do you think this is a Prebid Server problem? You haven't provided any evidence there's a problem. In fact, from almost no detail at all, this sounds more like an app rendering issue than a Prebid problem. If you have evidence that this is a PBS problem, we need an example JSON request and response.
- But 99% chance a `loadAdError` is a problem with how you've implemented PBSDK in your app or how you've set up line items in your ad server. Both of which are difficult, but are not problems for this repository.

Assuming this is indeed a mobile rendering issue, you can open an issue in https://github.com/prebid/prebid-mobile-ios or https://github.com/prebid/prebid-mobile-android, but they are going to need a lot of detail as well -- post everything you can: what integration method, what ad server, how you've structured your line items, maybe even the actual app code you've written to integrate and render.
