### ISSUE TITLE
Prebid Server OpenRTB bid requests for AMP

### ISSUE THREAD

**Issue by Xoben** [prebid/prebid-server#376]
Anyone know how to setup an amp config on prebid server?
When I test the placement via this link https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=11111

I get the following error message

Invalid request format: AMP requests require Targeting and Caching to be set
`{ "imp": [ { "ext": { "appnexus": { "placementId": 11111 } }, "banner": { "format": [ { "h": 250, "w": 300 }, { "h": 600, "w": 300 } ] }, "id": "imp-div-gpt-300x250_0" } ], "id": "div-gpt-300x250_0" }`

I can't seem to find any documentation on how to setup OpenRTB bid requests for AMP

https://prebid.adnxs.com/amp/

**Comment by mkendall07** [comment]
are you hosting your own prebid server?
The error I get is:
`Invalid request format: Stored Request with ID="11111" not found.`

**Comment by Xoben** [comment]
@mkendall07 sorry the correct link is https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=9114174

**Comment by dbemiller** [comment]
ahh, yes. It's exactly as the error message says: `Targeting` and `Cache` need to be set for AMP to work at all. Docs on Targeting are [here](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#targeting). It looks like docs on `cache` don't exist.

It also looks like you're missing a `site` argument, which OpenRTB requests require.

Try something like this instead:

```
{
  "id": "div-gpt-300x250_0",
  "site": {
	"page": "your-page.com"
  },
  "imp": [
    {
      "ext": {
        "appnexus": {
          "placementId": 9114174
        }
      },
      "banner": {
        "format": [
          {
            "h": 250,
            "w": 300
          },
          {
            "h": 600,
            "w": 300
          }
        ]
      },
      "id": "imp-div-gpt-300x250_0"
    }
  ],
  "ext": {
    "prebid": {
      "targeting": {
        "pricegranularity": "you must define this as {low, med, high, ...} -- depending on your DFP Ad Units"
      },
      "cache": {
        "bids": {}
      }
    }
  }
}
```

**Comment by dbemiller** [comment]
One more caveat: `prebid.adnxs.com` caches these payloads... so if you change it, it might take up to an hour before the cache clears.

To work around this, I recommend testing first by POST-ing it to `/openrtb2/auction` and making sure it works like you expect before you save it into the UI and test it through the `/openrtb2/amp` endpoint.

I'm going to make a quick PR to clarify that error message... I can definitely see how that's confusing.

**Comment by Xoben** [comment]
thanks for your response, how would I got about adding rubicon as a additional bidder, I've tried different ways but I continue to get an error message 

**Invalid request format: request.imp[0].ext.rubicon failed validation.
accountId: Invalid type. Expected: integer, given: stringsiteId: Invalid type. Expected: integer, given: stringzoneId: Invalid type. Expected: integer, given: string**

`{
    "imp": [{
        "ext": {
            "rubicon": {
                "zoneId": 80422,
                "siteId": 12263,
                "accountId": 7685
            },
            "appnexus": {
                "placementId": 9114174
            }
        },
        "banner": {
            "format": [{
                    "h": 250,
                    "w": 300
                },
                {
                    "h": 600,
                    "w": 300
                }
            ]
        },
        "id": "imp-div-gpt-300x250_0"
    }],
    "ext": {
        "prebid": {
            "cache": {
                "bids": {}
            },
            "targeting": {
                "pricegranularity": "auto"
            }
        }
    },
    "id": "div-gpt-300x250_0",
    "site": {
        "page": "your-page.com"
    }
}`

**Comment by dbemiller** [comment]
See the JSON spec: http://www.json.org/

Ints are not quoted, e.g. `80422`. Strings are quoted, e.g. `"80422"`.

Looks like your Rubicon params are failing validation because you're giving it ints while it expects strings, or perhaps vice versa.
