### ISSUE TITLE
Ability to turn off bidders

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#379]
Some installations of Prebid Server may not want to run all available bidder adapters.

Scenarios:
- installation of Prebid Server not approved to use one or more bidder adapters
- installation of Prebid Server has no customers interested in demand from one or more bidder adapters

Ideally, Prebid Server could be built without the full list of bidder adapters, but minimally an installation should be able to turn off requests for a given bidder adapter in the config.

If a bidder is requested that is not configured, an error should result. Ideally the error would be "adapter not active". This is different than when an unknown adapter is requested.

**Comment by dbemiller** [comment]
This seems like a good idea. My main concern is that it might confuse publishers if they switch PBS hosts and suddenly find that certain Bidders don't work.

To mitigate this, I'd add a few acceptance criteria.

1. The [bidder metadata](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/info/bidders/bidderName.md) endpoint should also return an `enabled: bool` property.

2. If a request includes some `imp.ext.{bidder}` (bidder params), then `{bidder}` should make no bids, and the auction should still work for the other bidders. Also: the `response.ext.errors.{bidder}` should include a message telling the publisher that this PBS host has disabled this bidder, and to call up the host company if they think that's an error.

Regarding (2), you can get this behavior easily by putting an instance of the [MisconfiguredAdapter](https://github.com/prebid/prebid-server/blob/master/adapters/legacy.go#L79) into the `adapter_map` with the appropriate error message.
