### ISSUE TITLE
Add targeting key value hb_env

### ISSUE THREAD

**Issue by jaiminpanchal27** [prebid/prebid-server#382]
Feature Request.

To detect request from mobile sdk, we have decided to add new targeting key value pair `hb_env` : `mobile-app`

Later on, if need be we can use this param with other environments like `amp`

**Comment by dbemiller** [comment]
Talked offline about this... the main motivation here is to support the Prebid universal creative. This would help unify the setup in DFP for publishers who use mobile, web, and AMP.
