### ISSUE TITLE
Document the list of supported adapters

### ISSUE THREAD

**Issue by kevinlisota** [prebid/prebid-server#385]
Tried to switch over to Prebid server today from client-side bidding. The configuration was simple, adding the server adapater and then configuring the s2sConfig object. (We used the AppNexus hosted server)

However, when I looked at the auction return information in the browser console, I realized that one of our bidders (Conversant) was working, and the others (onedisplay and onemobile from AOL) were returning an "unsupported bidder" message.

Two requests here.

Maybe I'm missing it, but there seems to be an opportunity to document which bidders support Prebid Server. The list is tiny compared to client-side Prebid. I think the authoritative answer is here: https://github.com/prebid/prebid-server/tree/master/adapters

The second request would be to output this error in the PBJS debug console. The regular debug console provided no information here, other to say that various bidders were called. And then it would show successful bids from the supported bidder. It was silent about the "unsupported bidder" error. It should show something obvious from the Prebid server response in the debug console. The only way I detected this error was to look at the response body returned to the browser from Prebid server.

**Comment by dbemiller** [comment]
Hey @kevinlisota 

> Maybe I'm missing it, but there seems to be an opportunity to document which bidders support Prebid Server.

We have some APIs for that. They're just JSON now... but in the future we hope to build human-readable docs from them. On the Appnexus hosted server, the URLs are:

- http://prebid.adnxs.com/pbs/v1/info/bidders is described by [this doc](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/info/bidders.md)

- http://prebid.adnxs.com/pbs/v1/info/bidders/appnexus (or any other bidder name) is described by [this doc](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/info/bidders/bidderName.md)

If those aren't clear, please let me know or file a PR to improve them.

> The second request would be to output this error in the PBJS debug console.

I definitely agree with your suggestion... but that's not really an issue with Prebid Server, exactly. Could you log a separate Issue (or open a PR) with PBJS?

**Comment by kevinlisota** [comment]
Those are clear, when you locate them. Something in the documentation that says "prebid server supports a subset of bidders, here is the list" seems in order. As a newbie to Prebid Server, I did not realize that the entire list of adapters wasn't available.

**Comment by dbemiller** [comment]
Yeah, I agree. That makes a lot of sense.
