### ISSUE TITLE
audienceNetwork - error bidrequest.site.publisher.id or bidrequest.app.publisher.id required for legacy bidders.

### ISSUE THREAD

**Issue by Xoben** [prebid/prebid-server#387]
When I run a auction via https://prebid.adnxs.com/pbs/v1/openrtb2/auction with this json I get the following response.  
[audienceNetwork](https://github.com/prebid/prebid-server/blob/master/static/bidder-params/audienceNetwork.json) bidder is only asking for placementId 
`{
    "imp": [{
        "ext": {
            "rubicon": {
                "zoneId": 80422,
                "siteId": 111346,
                "accountId": 7685
            },
            "appnexus": {
                "placementId": 12855392
            },
            "audienceNetwork": {
                "placementId": "205594686609874_353176358518372"
            }
        },
        "banner": {
            "format": [{
                    "h": 250,
                    "w": 300
                }
            ]
        },
        "id": "imp-div-gpt-300x250_1"
    }],
    "ext": {
        "prebid": {
            "cache": {
                "bids": {}
            },
            "targeting": {
                "pricegranularity": "auto"
            }
        }
    },
    "id": "div-gpt-300x250_1",
    "site": {
        "page": "townhall.com"
    }
}`

**Response:**  I redacted the seatbid object
`"ext": {
        "errors": {
            "audienceNetwork": [
                "bidrequest.site.publisher.id or bidrequest.app.publisher.id required for legacy bidders."
            ]
        },
        "responsetimemillis": {
            "appnexus": 44,
            "audienceNetwork": 0,
            "rubicon": 8
        }
    }`

can anyone help with this?

**Comment by dbemiller** [comment]
Yes. It's as the error message says... your request payload must include a `site.publisher.id` or `app.publisher.id` value.

For example:

```
{
  "id": "div-gpt-300x250_1",
  "site": {
    "publisher": {
      "id": "You need to define this to make Audience Network work."
    },
    "page": "townhall.com"
  }
}
```

If you have an account at https://prebid.adnxs.com, use your account ID. If not, then _probably_ any string should do (although that depends on how Audience Network's server interprets these IDs, of course).
