### ISSUE TITLE
Handle setting up config errors in adapters more elegantly

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#388]
One of our Mobile engineers tried to run an Audience Network auction locally. Since they don't define [a default config param](https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L729), it failed with an obtuse error message.

I improved this for Audience Network in #332, but... I believe we can handle this more generally, for all adapters, at a global level (e.g. the `exchange/adapter_map.go`).

**Comment by dmitriyshashkin** [comment]
Another case when this can be useful is when someone tries to use index exchange adapter without specifying the endpoint. Right now this doesn't produce any errors, the only clue that something might be wrong is `'uri': ''` in `httpcalls` part of the response. And it's not quite easy without diving deep into the code to understand what's wrong. By default indexexchange's endpoint is not defined, so anyone who tries to use index in self-hosted PBS will encounter this problem.
