### ISSUE TITLE
Prebid server not responding with all the values

### ISSUE THREAD

**Issue by Xoben** [prebid/prebid-server#395]
Here is my bid response
https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=12855392

Is there documentation for this?
Testing on our site we are noticing we are not getting all the values needed to render the ad
    `var adId = "--missing--";
    var cacheHost = "--missing--"; //maps to hb_cache_host
    var cachePath = "--missing";   //maps to hb_cache_path
    var uuid = "dd8d37d0-5cb6-4ad3-9406-16c20ec5d5ea";
    var mediaType = "";
    var pubUrl = "redacted";

    try {
        pbjs.renderAd(document, adId, {
            cacheHost: cacheHost,
            cachePath: cachePath,
            uuid: uuid,
            mediaType: mediaType,
            pubUrl: pubUrl
        });
    } catch (e) {
        console.log(e);
    }
    `
On DFP setup
var adId = "%%PATTERN:hb_adid%%";
    var cacheHost = "%%PATTERN:hb_cache_host%%";
    var cachePath = "%%PATTERN:hb_cache_path%%";
    var uuid = "%%PATTERN:hb_cache_id%%";
    var mediaType = "%%PATTERN:hb_format%%";
    var pubUrl = "%%PATTERN:url%%";

**Comment by hhhjort** [comment]
Is this still an issue after PR #380 went in?

**Comment by dbemiller** [comment]
Thanks for the report!

This looks like a combination of PBS feature requests and docs updates. Unfortunately I'll be gone for the next week or two, so I can't follow up on this as much as I'd like to.

Right now, the targeting params from PBS are listed [here](https://github.com/prebid/prebid-server/blob/master/openrtb_ext/bid.go#L66). They get applied to the Bids [here](https://github.com/prebid/prebid-server/blob/master/exchange/targeting.go#L30).

Your setup looks totally standard with the prebid.org docs: http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html

...but it looks like the params from the docs simply don't exist in the code.

**Comment by Guilemon** [comment]
How do we go about this for now, should we just remove
```html
var adId = "%%PATTERN:hb_adid%%";
var cacheHost = "%%PATTERN:hb_cache_host%%";
var cachePath = "%%PATTERN:hb_cache_path%%";
```
from our creative setup in dfp or there is another workaround for it

**Comment by hhhjort** [comment]
At this time you will have to replace cacheHost and cachePath with hardcoded values. We do intend to support dynamic cache URLs at some point in the future, but the exact form and time haven't been nailed down yet.

**Comment by Guilemon** [comment]
what about `hb_adid`? i couldn't find it in prebid-server response..should i use any value and it would work..?

**Comment by hhhjort** [comment]
In rendering an ad, you need either `hb_adid` (for rendering from the openrtb response) or `hb_cache_id`, for rendering from the cached ad. The universal creative will use the option that works best in whatever context it finds itself in. In the AMP case, only cache delivery is possible, so there is no need for `hb_adid`.

**Comment by bretg** [comment]
@Xoben and @Guilemon - reviewing old issues, believe this one's covered by 
 http://prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html

Please confirm. Thanks.

**Comment by SyntaxNode** [comment]
@Xoben Does the link provided by @bretg above resolve the issue for you?

**Comment by SyntaxNode** [comment]
This looks to be resolved since @bretg provided the documentation links. Please open a new issue if you still think there's missing docs.
