### ISSUE TITLE
Support Native version 1.2

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#399]
Our OpenRTB library has added Native 1.2 support: https://github.com/mxmCherry/openrtb/releases/tag/v10.0.0

Right now, our input validation only checks against Native v1.1. We should upgrade it to validate v1.2 fields as well. We'll also have to fix the other breaking changes in the mxmcherry library (mainly: `openrtb.RawJSON` got replaced with `json.RawMessage`)

ORTB spec for Native v1.2 is here: https://www.iab.com/wp-content/uploads/2018/03/OpenRTB-Native-Ads-Specification-Final-1.2.pdf

**Comment by muncha** [comment]
After doing my upstream pull into my working fork, I was unable to build because of the RawJSON part of this. For testing purposes, it worked for me to roll back mxmCherry/openrtb to:

https://github.com/mxmCherry/openrtb/commit/c426d335a3506bd009710ee7a6b5fcf943e45c91

**Comment by muncha** [comment]
After merging upstream master into my working fork, I was unable to build because of the RawJson change as well as:
endpoints/openrtb2/auction.go:337:30: undefined: request.ContextType
endpoints/openrtb2/auction.go:344:37: undefined: request.PlacementType

For testing purposes I'm getting around that for now by rolling back mxmCherry/openrtb to:
https://github.com/mxmCherry/openrtb/commit/2f6127d966dc46d16e90f71acc6b304177460723

**Comment by dbemiller** [comment]
@muncha this project doesn't use the latest version of the OpenRTB library yet. The `Gopkg.lock` file should tie it to the version it's intended to work with.

Did you follow the README while setting up PBS? https://github.com/prebid/prebid-server#installation

The `dep ensure` line should download the version which PBS is compatible with.

When this ticket is implemented, we'll bump the version in `Gopkg.toml` to 10.0.0, and then we'll have to fix PBS code because of the breaking changes you mentioned. See https://github.com/prebid/prebid-server/blob/master/Gopkg.toml#L57

**Comment by basantashah** [comment]
```github.com/prebid/prebid-server/openrtb_ext
# github.com/prebid/prebid-server/openrtb_ext
../../../../../Go/src/github.com/prebid/prebid-server/openrtb_ext/bidders.go:88:32: undefined: openrtb.RawJSON
../../../../../Go/src/github.com/prebid/prebid-server/openrtb_ext/bidders.go:138:70: undefined: openrtb.RawJSON```

I am still not able to fix this. `HELP`
