### ISSUE TITLE
Any examples of making "Audio" calls yet available?

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#4003]
just as in the title, looking for example of Audio calls, its mentioned in prebid server docs but cant find any examples etc?

**Comment by bsardo** [comment]
@spormeon are just referring to Prebid Server requests with the audio media type? There are a bunch of adapters that currently support it in both PBS-Go and PBS-Java.

Here is the PBS-Go list:
metax
smrtconnect
relevant digital
limelight digital
index exchange
improve digital
concert

**Comment by spormeon** [comment]
@bsardo  Thanks, but how do you make the calls? is it just setup a video adUnit but with mediaType: { Audio .  I can find/ see any docs anywhere that show how to set it up?

**Comment by bretg** [comment]
Interesting Q @spormeon . This isn't actually a Prebid Server question -- it's up to the client (Prebid.js or Prebid SDK) to create the ORTB.

I don't think it's possible in SDK right now. In Prebid.js, I think it would have to be done in the adunit. Maybe something like:

```
pbjs.addAdUnits({
    code: "test-div",
    ortb2Imp: {
        audio: {
           ... ORTB 2.6 audio fields ...
        }
    },
    // ...
});
```

I'm not sure PBJS is going to like an AdUnit without a mediaType. I'll ask the Audio committee to weigh in and work with the PBJS/Mobile committees to define how to do this.

**Comment by spormeon** [comment]
@bretg Ok thanks,  Pat moved it over to hear for some reason, I put it in PBJS to start

**Comment by bretg** [comment]
Are you looking to call for audio ads within a web page from PBJS?

**Comment by spormeon** [comment]
ye, just looking to give it a test, see how works, what happens etc at moment

**Comment by bretg** [comment]
So @patmmccann, I think this is partly a Prebid.js issue:

1. Does PBJS support mediaType audio in an adunit? Based on a search in the codebase, I think this is 'no'.
2. Does PBJS support adunits that are completely missing the mediatype?

**Comment by bretg** [comment]
Going to close this on the PBS side. Please open a Prebid.js issue if you'd like to have audio support there.
