### ISSUE TITLE
Need to add `secure:1` default for AMP ORTB configs

### ISSUE THREAD

**Issue by mkendall07** [prebid/prebid-server#402]
In case the ORTB config for the AMP endpoint doesn't have a `secure` field, we should default to `secure:1` since all AMP traffic must be secure. 

Alternatively we could detect with the incoming request protocol the same as the legacy endpoint does.

**Comment by hhhjort** [comment]
Do we want to make secure default for all OpenRTB requests, or just the AMP requests? I can imagine this applying to other OpenRTB cases.

**Comment by mkendall07** [comment]
No, there are cases you don't want to force HTTPS. HTTPS limits the demand you get back so only if the environment requires it should we set it to `1`
