### ISSUE TITLE
User sync might have a negative impact on revenue

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#41]
When user doesn't have advertisers cookies on prebid-server domain, instead of bids server responds with user sync url. And judging from google analytics data, this will happen a lot, for significant share of our pageviews there will be no bids, because users will have no advertisers cookies on prebid-server domain.

Of course when many publishers adopt prebid-server hosted on the same domain, this situation will became less common: user will get synced by one website using prebid server, and there won't be need to do that again on the other website. Though I'm not sure how much time it'll take prebid-server to gain sufficient popularity.

I might be missing something, mb the problem is not that significant as I imagine (I still haven't tested prebid server on production) or there is a better way to handle this. Still I would like to discuss the idea on how to alleviate this problem.

The way prebid server is integrated with prebid js, it seems to be quite simple to switch dynamically between client side and server side integration. So mb it would be a good idea to fallback to client side integration when the cookies are not synced. Possible solution:

1) While initializing prebid, check user's cookies on publisher's domain for a flag that says that cookies were synchronized.
2) If there is such flag, use prebid server, otherwise fallback to client side integration and do the user sync after the auction has ended. Then, set the cookies on publisher's domain so the next time the s2s integration would be used

Any feedback is appreciated. Coming from the publishers side I might be not have a sufficient understanding of how things work.

**Comment by mkendall07** [comment]
@dmitriyshashkin 
Sorry for not replying sooner on this. This is good idea, we are planning to add support for this.

**Comment by dmitriyshashkin** [comment]
So I guess the idea was implemented?) https://github.com/prebid/Prebid.js/pull/1485/commits/f37bda1bf04328c007ced234bbcb212037341bfe
