### ISSUE TITLE
Mobile banners on desktop and vice versa

### ISSUE THREAD

**Issue by AnniAdops** [prebid/prebid-server#4110]
Hi, 
We use same ad units across desktop and mobile, and use a size config to make sure mobile banners show on mobile devices and desktop banners on desktop, but our headerbidding set up somehow overrules the sizeconfig and viewport rules and show mobile size ex 320x320px on deskop topbanner ad unit. I think it is because we request all sizes for the ad unit and somehow we need build in, in our prebid config, which sizes to request on which devices. Any ideas on how to do that or can point to it in the documentation?

**Comment by AnniAdops** [comment]
mobile is web as well, no app

**Comment by bretg** [comment]
@AnniAdops - you posted this to the Prebid Server repo, but Prebid Server has no ability to deal with responsive sizes automatically -- there's no equivalent of the Prebid.js [Advanced Size Mapping module](https://docs.prebid.org/dev-docs/modules/sizeMappingV2.html) available for Prebid Server.

> show mobile size ex 320x320px on deskop topbanner ad unit

That's a Prebid.js configuration issue. Please see the Advanced Size Mapping module.

For Prebid Server, your mobile app needs to tell us which sizes are relevant. It's ok for your ad server line items to serve all the banner sizes, but the mobile app and Prebid.js need to be properly configured to tell bidders what sizes you want bids on.
