### ISSUE TITLE
Additional parameters for AMP RTC 

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#420]
AMP RTC supports a number of dynamic parameters that Prebid Server could/should support. Here's the URL that's been configured in AMP:

```
/openrtb2/amp?tag_id=REQUEST_ID&w=ATTR(width)&h=ATTR(height)&ow=ATTR(data-override-width)&oh=ATTR(data-override-height)&ms=ATTR(data-multi-size)&slot=ATTR(data-slot)&targeting=TGT&curl=CANONICAL_URL&timeout=TIMEOUT&adc=ADCID&purl=HREF'
```
Specifically, the following are desired for this release: w, h, ms, curl, slot, timeout:

- w add into the openrtb packet at imp.banner.format[0].w
- h add into the openrtb packet at imp.banner.format[0].h
- ms (multiple-sizes) - takes values like "970x90, 728x90". Parse sizes and add to imp.banner.format array
- curl add as site.page
- slot add as imp.tagid
- timeout add as tmax
- targeting - this one's bigger. It's for passing first party data in, but will be a separate issue.
- ow, oh, and purl are TBD - also for a separate issue

**Comment by bretg** [comment]
So we're implementing this on the Java side, and there's a details in the Go implementation that I'm not sure is quite right. Specifically, setting imp.banner.h and imp.banner.w

OpenRTB 2.5 recommends that the format be specified, and having both format and h/w be specified is unclear. The standard seems to say that h/w are only used if format isn't specified, but SSPs may have implemented that differently. I think it's cleaner to specify only the format object.

So this is what we're building into Java:

1) only imp.banner.format[] is ever set. Never imp.banner.w/h
2) if oh/ow is defined, they are set as imp.banner.format[0] and ms/w/h are ignored
3) else if ms is defined, it's used to set imp.banner.format[]
4) else use w/h define imp.banner.format[0]

**Comment by dbemiller** [comment]
> The standard seems to say that h/w are only used if format isn't specified

Where does it say that?

**Comment by bretg** [comment]
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf section 3.2.6: format is the `recommended` field.

```
Array of format objects (Section 3.2.10) representing the
banner sizes permitted. If none are specified, then use of the
h and w attributes is highly recommended.
```
And then both `w` and `h` say 
```
recommended if no format objects are specified.
```
It doesn't say what to do if both imp.banner.format[] and imp.banner.w/h are specified.

**Comment by bretg** [comment]
There's another edge case that our developer brought up -- we think that both `oh` and `ow` need to be defined or they should be ignored. For example, if `oh` is defined but not `ow`, and `ms` is also defined, what the heck do you do?

Because ms defines both height and width... do you override the height part of ms?  Unclear and/or non-sensical. Thoughts welcome.

**Comment by bretg** [comment]
After back-and-forth on slack and some research into what AMP does, here's where we are now...
```
if override is specified - it's the only one sent to DFP. If only one half is specified, the other half comes from the amp-ad
else if multi-size is specified, they're added to the base w/h
else just use base w/h

and in the PBS case:
these are the only sizes sent to the ad server, so no other sizes should be specified in the Prebid auction
therefore, these values should override whatever's in the format object.
```

**Comment by bretg** [comment]
Got some more clarification questions from the developer -- we came up with this:

1) Only imp.banner.format is ever set. Never imp.banner.h/w
2) If ow/oh specified, replace request.imp.banner.format.w/h
3a) if ow is specified but oh is missing, replace request.imp.banner.format with ow and h
3b) if oh is specified but ow is missing, replace request.imp.banner.format with oh and w
4)If both ow and oh are missing, fallback to ms and replace request.imp.banner.format array from it
5)If ms is not provided(or cannot be parse correctly) use w/h params to overwrite request.imp.banner.format.w/h
6a)If w is specified but h is missing, leave anything that's in the stored request, overwrite just format[0].w
6b)If h is specified but w is missing, leave anything that's in the stored request, overwrite just format[0].h
7) Otherwise, nothing is specified so leave request.imp.banner.format as it was in the stored request

**Comment by cirla** [comment]
Thanks for the very detailed requirements!

**Comment by dbemiller** [comment]
@cirla is super busy, so... I'm gonna go finish this up.

@bretg what's the rationale behind these?

```
If ms is not provided(or cannot be parse correctly) use w/h params to overwrite
request.imp.banner.format.w/h
If w is specified but h is missing, leave anything that's in the stored request, overwrite just format[0].w
If h is specified but w is missing, leave anything that's in the stored request, overwrite just format[0].h
```

It seems very odd to me that the entire `format` array is overwritten if `w/h` both exist, but only the dimension in the first element is overwritten if just one of `w` or `h` exist.
