### ISSUE TITLE
Lifestreet adapter certificate issues

### ISSUE THREAD

**Issue by cirla** [prebid/prebid-server#423]
Requests via the Lifestreet adapter are resulting in the following error: `"Post https://prebid.s2s.lfstmedia.com/adrequest: x509: certificate is valid for *.lfstmedia.com, lfstmedia.com, not prebid.s2s.lfstmedia.com"`.

The certificate should be updated to be valid for `*.s2s.lfstmedia.com`.

**Comment by cirla** [comment]
@Lifestreet

**Comment by Lifestreet** [comment]
Thank you. We are looking into it.

**Comment by Lifestreet** [comment]
Should be fixed now.
