### ISSUE TITLE
Analytics test create a file: analytics/test-20180402

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#434]
In master now, an `analytics/test-20180402` file gets created whenever you run the unit test suite. This shouldn't happen.

Looks like this was introduced by #418. @cindyhere33 could you take a look? There are some ideas for working with the filesystem in tests here:

- https://stackoverflow.com/questions/16742331/how-to-mock-abstract-filesystem-in-go
- https://medium.com/@flaqueEau/how-to-cleanly-test-files-in-go-af025bfcd9d3

**Comment by cindyhere33** [comment]
uh oh! yes I'm on it!
