### ISSUE TITLE
support for use_pmt_rule field in pbjs to pbs request

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/prebid-server#442]
In PBJS we are going to support passing a payment rule boolean flag in the ortb request to pbs.  The flag will be stored under `Request.imp.ext.appnexus.use_pmt_rule` and will only be passed by the `appnexus` bidder.  

As part of the requirements for this change, there is a need of support in pbs to pass along this field.  For reference, below is a snippet taken from the original ticket (see RAD-1955).
> If Prebid Server receives this flag from the AppNexus bidder params, Prebid Server should send the appropriate value on the AppNexus OpenRTB bid request as described in ROR-209.

Can someone investigate to see if this field wold be already passed along, and if not - add the needed support?

**Comment by hhhjort** [comment]
PR #412 added in support for `use_pmt_rule` into the AppNexus adapter

**Comment by jsnellbaker** [comment]
Ok - thanks for confirming it's already implemented.
