### ISSUE TITLE
Bid Adjustment Factors not working in AMP requests

### ISSUE THREAD

**Issue by gramorris** [prebid/prebid-server#452]
Hey @dbemiller 

We've had the bid adjustment factors implemented on the AppNexus server for a week but have seen no effect in the cpm's being recorded at DFP. I've included a bid request below and I've checked that the AppNexus server has implemented a version with the bid adjustments in by triggering an error by inserting a negative adjustment.

We've included some currency conversion in there so the factors are quite large so we definitely should've seen them taking effect. The cpm's have actually risen slightly, no doubt due to increase demand through the month.

`{
    "imp": [
        {
            "ext": {
                "sovrn": {
                    "tagId": "325628"
                },
                "rubicon": {
                    "sizes": [
                        43
                    ],
                    "siteId": 175784,
                    "accountId": 17606,
                    "zoneId": 849556
                },
                "brealtime": {
                    "placementId": 8544376
                },
                "oftmedia": {
                    "placementId": 12861428
                },
                "appnexus": {
                    "placementId": 12185389
                }
            },
            "banner": {
                "format": [
                    {
                        "h": 50,
                        "w": 320
                    }
                ]
            },
            "id": "imp-id"
        }
    ],
    "ext": {
        "prebid": {
            "targeting": {
                "pricegranularity": "low"
            },
            "cache": {
                "bids": {}
            },
            "bidadjustmentfactors": {
                "sovrn": 0.73,
                "rubicon": 0.8,
                "brealtime": 0.66,
                "oftmedia": 0.62,
                "appnexus": 0.64
            },
            "aliases": {
                "oftmedia": "appnexus",
                "brealtime": "appnexus"
            }
        }
    },
    "id": "imp-id-id",
    "site": {
        "page": "site-url-here.com"
    }
}`

**Comment by gramorris** [comment]
Thanks. I can verify that. Could there be something at the AMP endpoint? I tried adding it to an AMP request but got an error that the placementId couldn't be verified.

On the AMP side it just takes the targeting params and passes them in to DFP I can't imagine a situation where it could reverse the bid adjustments.

**Comment by dbemiller** [comment]
hmm... I tested locally, and all the bid adjustments do _seem_ to be working. However, I did notice some other (unintended) behavior which could be affecting AMP.

If you want to reproduce it:

- Run Prebid Cache locally, and set it to use an in-memory cache
- Run Prebid Server locally, and configure it to point to your local Prebid Cache instance
- Define `stored_requests/data/by_id/storedrequests/amp.json` in this project to be that request I listed above
- Run `GET http://localhost:8000/openrtb2/amp?tag_id=amp`

I get the following response:

```
{"targeting":{"hb_bidder_double":"double","hb_bidder_half":"half","hb_bidder_normal":"normal","hb_cache_id_double":"558b1570-5e70-4e1e-9b49-ec88ca403f34","hb_cache_id_half":"30109212-c66a-4d3a-a297-f70ef59c7cfa","hb_cache_id_normal":"ce737993-03b5-4c83-bf67-c8384f1d4f80","hb_creative_loadtype":"html","hb_pb_double":"1.00","hb_pb_half":"0.20","hb_pb_normal":"0.50","hb_size_double":"300x250","hb_size_half":"300x250","hb_size_normal":"300x250"}}
```

The targeting keys do look like I'd expect, given the bid adjustments... however, the "winning" keys (like `hb_pb`) aren't there at all. This definitely might affect prices in DFP

If you add this to `request.ext.prebid`, you'll start seeing them:

```
"targeting": {
  "winners": true
}
```

Will cause the same request to produce:

```
{"targeting":{"hb_bidder":"double","hb_bidder_double":"double","hb_bidder_half":"half","hb_bidder_normal":"normal","hb_cache_id":"a5f8b44a-07aa-49df-9086-33f0d337f25d","hb_cache_id_double":"a5f8b44a-07aa-49df-9086-33f0d337f25d","hb_cache_id_half":"190422fe-cfd5-4f1b-9962-2c41233ee91d","hb_cache_id_normal":"01e10b48-ae37-428e-801a-01a5b716c12e","hb_creative_loadtype":"html","hb_pb":"1.00","hb_pb_double":"1.00","hb_pb_half":"0.20","hb_pb_normal":"0.50","hb_size":"300x250","hb_size_double":"300x250","hb_size_half":"300x250","hb_size_normal":"300x250"}}
```

**Comment by gramorris** [comment]
We are setup to use send all bids so in our case I don't think this would be causing our issue. I've amended one set of tags to adjust all bids by 0.01 to see what happens and I've also split off a set of AMP specific tags at AppNexus so I can get a before and after eCPM just to be sure. 

I guess it's possible it's something at AppNexus so we could try the Rubicon server. I'll update once I've got more info.

**Comment by dbemiller** [comment]
I chatted with my colleague who "owns" the AMP config Prebid sample ad, and got him to replace it with the request I listed above. The only difference is that the `normal` alias doesn't exist, since the APN UI requires plain-old `appnexus` to be a bidder.

You can access this one yourself with `GET https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=10433394`

```
{"targeting":{"hb_bidder_appnexus":"appnexus","hb_bidder_double":"double","hb_bidder_half":"half","hb_cache_id_appnexus":"874921ff-f514-40e4-a161-cd79e0f33751","hb_cache_id_double":"fadb6f96-14d2-4312-a8de-a2e2fc6e219f","hb_cache_id_half":"8edb4899-64f5-453a-aa85-7021092dcc95","hb_creative_loadtype":"html","hb_pb_appnexus":"0.50","hb_pb_double":"1.00","hb_pb_half":"0.20","hb_size_appnexus":"300x250","hb_size_double":"300x250","hb_size_half":"300x250"}}
```

You can also run `GET https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=10433394&debug=1` and check`debug.resolvedrequest` in the output to confirm that the saved config is what we think it is.

Not really sure where else to point you from here.... everything seems like it's working :/

**Comment by gramorris** [comment]
No probs, I'll dig in further. It would be great if the cpm's we're seeing are genuine as they're a little too good to be true :)

Thanks for checking up, I will feed everything back in here. And, I wasn't aware of the debug flag, that'll help enormously.

**Comment by gramorris** [comment]
I've seen a request back out from our placements now, with the debug flag on, and verified that the adjustments are working. Sorry @dbemiller for seemingly wasting your time. The best reasoning I've got for why our average cpm's aren't showing the adjustments is that they're being masked by the fact we have to use the low pricegranularity until the custom granularity comes in.

I'm happy for this to be closed. I'm going to keep investigating as the cpms are still a little to good to be true so if anything crops up I'll update.

**Comment by dbemiller** [comment]
No worries! "too good to be true" and "seems to be working" sounds like great news for us :)
