### ISSUE TITLE
Not minified version of amp user-sync iframe

### ISSUE THREAD

**Issue by alexmrf** [prebid/prebid-server#460]
I would like to see a not minified version of the [amp user-sync iframe](https://acdn.adnxs.com/prebid/amp/user-sync/load-cookie.html). 

Would it be possible?

Thanks!

**Comment by jaiminpanchal27** [comment]
We minify this module https://github.com/prebid/prebid-universal-creative/blob/master/src/cookieSync.js using gulp task and place it in https://github.com/prebid/prebid-universal-creative/blob/master/resources/load-cookie.html

**Comment by alexmrf** [comment]
Thank you very much! :)
