### ISSUE TITLE
When request is proxied to prebid-ssl.northeurope.cloudapp.azure.com wrong X-Real-Ip is set

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#47]
When I query prebid-server, request goes to prebid.adnxs.com and then it gets redirected to prebid-ssl.northeurope.cloudapp.azure.com . For some reason prebid proxy adds wrong X-Real-Ip header (11.244.1.1). As the result prebid server erroneously uses what I suppose to be datacenter's ip as my own. Here is the response I get from prebid's debug page https://prebid.adnxs.com/pbs/v1/ip

User Agent: Type: Browser
Name: Chrome
Version: 58.0.3029
OS: GNU/Linux
OSVersion: 0.0.0
Security: Unknown security
Mobile: false
Tablet: false<p>IP: 11.244.5.1</p><p>Port: 32994</p><p>Forwarded for: 11.244.1.1</p><p>X-Forwarded-Host: [prebid.adnxs.com]</p><p>Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8]</p><p>Accept-Language: [en-US,en;q=0.8,ru;q=0.6]</p><p>X-Real-Ip: [11.244.1.1]</p><p>X-Forwarded-For: [11.244.1.1]</p><p>X-Forwarded-Proto: [https]</p><p>Cache-Control: [max-age=0]</p><p>Upgrade-Insecure-Requests: [1]</p><p>User-Agent: [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36]</p><p>Accept-Encoding: [gzip, deflate, sdch, br]</p>

The wrong ip is also passed in device section of RTB request and as the result I see ads targeted to US only (while my ip is European).

This happens only for european IPs and doesn't happen when I query prebid.adnxs.com from US-based ip. In the latter case, my ip is passed correctly in X-Real-Ip header.

**Comment by bokelley** [comment]
I poked around - this issue appears to be from the way our Azure cluster in Europe is set up; it's not properly handling source IP routing. I've flagged it for our sysadmin team to dig into, and taken the EMEA cluster offline until it's resolved.

**Comment by dbemiller** [comment]
Closing because this is stale...

Prebid Server is no longer hosted on Azure, and at present is not deployed to a cluster in Europe at all.
