### ISSUE TITLE
App config values aren't used as expected

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#475]
To reproduce:

1. Define a `pbs.yaml` file which _doesn't_ include an entry for `status_response: "stuff"`
2. Build PBS and set the environment variable with `export PBS_STATUS_RESPONSE=something`
3. Run `GET localhost:8000/status`

Expected:

- The `/status` endpoint should return "something".

Observed:

- A 204 is returned because the config value was empty.

------------------------------------------------------------

Even more unusual: define a `pbs.yaml` which _does_ include an entry for `status_response: "something-else"`

Restart the PBS app. Now the `PBS_STATUS_RESPONSE` environment variable will be in effect.

**Comment by hhhjort** [comment]
I have been looking into this, and it seems that Viper needs to either have a default value hardcoded, or the parameter to appear in the config file for Viper to find it and place it in the struct when it does its unmarshal. It won't look at the environment variables for parameters that only appear in the struct, but not in the configuration otherwise.

**Comment by dbemiller** [comment]
ahh... that actually makes lots of sense.

It's generally considered "good practice" for an app to ship with defaults for every config option. That way newcomers to the project can run a "hello world" version right out of the box.

It sounds like the `viper` devs knew that, so they built their library assuming that default values existed in the project somewhere first.

I think we should either:

1. Add `setDefault` calls in the code
2. Commit a sample `config-defaults.yaml` file with all the possible properties to the project, and make sure `viper` knows about it (but still lets `pbs.yaml` and all the other config places override it)

My preference would be for (2), because it would double as good documentation. Either one would be a valid fix for this issue though.

**Comment by hhhjort** [comment]
Unfortunately it seems that Viper is only set up read a single config file at a time. We might be able to configure it too look for the example config, unmarshal that, and then reconfigure it to look for the real file, and then unmarshal that. I suspect that it would behave as any normal JSON unmarshal, where things not found in the second file would simply keep their values that were set previous to the second unmarshal call.

However I have a feeling this would be a bad solution. The example config file is a good idea to have in any case, as it makes for good documentation. However, actually having the binary read it may be bad. People won't expect that the a program's behavior to be negatively impacted if they delete the example config when they have a "production" config, but in this case they would not be able to set the `status_response` from environment variable if they did not include it in their production config.

Also, considering the example config file, we have a lot of options that are optional. Given our `mulit*` objects, the product may work if we actually defined everything in the file, the normal expectation is that the example will be a "typical" config with the other options commented out. Commenting out the other options would defeat the purpose of doing the two pass config file read of course.

**Comment by jameslinjl** [comment]
@hhhjort @dbemiller any ideas on what the timeline for resolving this might be?
