### ISSUE TITLE
Null and empty values in responses

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#476]
While testing the differences between PBS-Go and PBS-Java, our QA noticed that PBS-Go returns empty and null objects while PBS-Java doesn't

e.g.
- in PBS-Go, `/auction` response bid object will have field `hb_cache: ""` whereas in PBS-Java it will be absent
- `digitrust: null` in PBS Go is not there in PBS Java

Was this a deliberate design feature in PBS-Go?  One could argue that explicit nulls do carry information that a missing attribute doesn't. This might be useful in debugging.

One could also argue that the extra characters aren't going to be used by clients in either case and that any debug value could be constrained to `test` mode.

**Comment by dbemiller** [comment]
nah.... I can't think of any good reason for those.

Prebid.js almost certainly doesn't care either way (because of how falsey values work in JS)... but Prebid Mobile definitely might. I'd welcome a PR which removes them, but we should make sure PBM won't crash if we do.

**Comment by dbemiller** [comment]
Haven't heard back... so I'm assuming this isn't causing any substantive problems.

If it is, let me know. I definitely agree that these "empty values" shouldn't make it out into the response.
