### ISSUE TITLE
How to view logs of the prebid-server ?

### ISSUE THREAD

**Issue by sanndeepg** [prebid/prebid-server#498]
I do not see any request logging on the hosted machine.
I need my server to record logs of request received and other server related loggings

**Comment by dbemiller** [comment]
Logs are written by `glog`: https://gist.github.com/heatxsink/7221ebe499b0767d4784

You can configure how (and where) it logs with flags like these: https://github.com/golang/glog/blob/master/glog.go#L42

We may not be logging exactly what you need, though. If so, feel free to add it.
