### ISSUE TITLE
GDPR and Prebid.js

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#501]
**Disclaimer**: I'm a software engineer, not a lawyer. This is not intended as legal advice, and concerned parties should check with their legal counsel.

# Summary
I don't believe that Prebid Server is GDPR-ready for host companies. I believe we can make it compliant before the May 25 deadline.

Publishers will need to update Prebid.js versions once some issues in those projects are fixed (see below)

# Concerns

Prebid Server uses a Cookie to store the user's ID for each Bidder. A summary of GDPR and Cookies can be found [here](https://eugdprcompliant.com/cookies-consent-gdpr/).

Prebid Server has two endpoints involved in cookie syncing: `/cookie_sync` and `/setuid`. Docs about these can be found at:

- [Technical details](https://github.com/prebid/prebid-server/blob/master/docs/developers/cookie-syncs.md)
- [/cookie_sync API](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/cookieSync.md)
- [/setuid API](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/setuid.md)

Specifically, the `/setuid` endpoint writes to the Cookie of the Prebid Server host company, which I believe is a GDPR liability for them.

# How does Prebid.js use these?

`Prebid.js` calls the `/cookie_sync` URL [during the call to `setConfig`](http://prebid.org/dev-docs/get-started-with-prebid-server.html#step-4-configure-s2s-bidder-adapters), unless the `syncEndpoint` is undefined in that payload.

These syncs occur in the source code [here](https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L99).

# Compliance

The IAB [includes a spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/URL-based%20Consent%20Passing_%20Framework%20Guidance.md) for passing consent strings through HTTP Services. Given the May 25 deadline, we plan to support a subset of their guidelines for now.

Specifically, we plan to add optional `gdpr` and `gdpr_consent` query params to `/cookie_sync` and `/setuid`. If given, these endpoints will be no-ops unless the Prebid Server Host company has the user's consent to save cookies. If not present, the host company will be able to configure PBS so that the code _allows_ all syncs, or _prevents_ all syncs.

For May 25, Prebid Server will also avoid syncs with Bidders who don't have consent for ad personalization. In the future Bidders may be allowed to override this behavior if their usersync endpoints are GDPR-aware.

In the future, we will add support for GeoIP lookup services to PBS. However, we do _not_ expect this to be done by May 25. Any help designing or building GeoIP support more quickly are welcome.

For code changes, the plan is to:

1. Enhance the `Usersyncer` so that Bidders can identify themselves as one of the [global vendors](https://vendorlist.consensu.org/vendorlist.json) (#502)
2. Add some app config params so that host companies can also identify themselves as one of the global vendors, and configure whether PBS should take a "safe" (sync nothing) or "risky" (sync everything) strategy if the `gdpr` params aren't present (#505)
3. Update the Prebid.js GDPR module to forward the `gdprApplies` and `vendorConsents` string during cookie syncs with Prebid Server. (https://github.com/prebid/Prebid.js/pull/2530)

# What does this mean for me?

## Prebid.js Publishers

Make sure you're using Prebid.js 1.11 or later (see https://github.com/prebid/Prebid.js/issues/2516), and include the GDPR module in your build.

Check with the company hosting your Prebid Server instance to see how they're setting the GDPR config options from #503 in production.

If you don't like their policy, or this ticket _doesn't_ get closed before May 25, you can take a "safe" approach by changing your `s2sConfig.syncEndpoint` to be undefined. This will prevent cookie syncs altogether.

## Prebid Server Host Companies

[Register as a GDPR vendor](https://register.consensu.org/) and update your app config per when releasing #505. Make sure you're running the newest tag of PBS in production come May 25.

## Bidders

If you're already on the [global vendor list](https://vendorlist.consensu.org/vendorlist.json), check #502 and make sure that the ID added to your `Usersyncer` is in fact the right one.

If not, [register as one](https://register.consensu.org/) and then submit a PR updating your `Usersyncer` in the project. If you fail to do this, your cookie sync rate _will_ go down as PBS host companies deploy GDPR-aware code.

If your Sync endpoint accepts GDPR consent info, you may also want to submit a PR to forward them. The consent params are passed to the Usersyncers in #517.

# Out of scope

These are out of scope for now, because they're simply too big to finish by May 25. They'll likely be scheduled for the future though. If you're interested in contributing, please speak up!

1. If the `gdpr` query flag is undefined, we should do a GeoIP lookup to find out if the request is coming from the EU. Since there are many GeoIP services out there, this will probably be another module like the Metrics or Stored Request backends.

2. Some publishers intend to claim a [Legitimate Interest](https://www.gdpreu.org/the-regulation/key-concepts/legitimate-interest/) with adtech vendors in their [pubvendors.json](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/pubvendors.json%20v1.0%20Draft%20for%20Public%20Comment.md) file. This will not be supported for this ticket.

**Comment by bretg** [comment]
Thanks for posting this Dave. Talking with folks here, a couple of things to add:

1) In order to set a cookie on a user's device, the PBS host needs to verify that its vendor ID has consent for Purpose 1: Information storage and access. i.e. Rubicon (vendor 52) will need consent for Purpose 1 in order for our PBS cluster to set the uids cookie. This implies that each PBS cluster will need to know its vendor ID, so another config entry.

2) It's recommended that we keep an audit trail of evidence showing that the PBS host domain had consent to set the cookie.

The minimum data needed for the audit trail is:
- Referrer at the time of the most recent update.
- Timestamp of the most recent update.
- Consent data used

Assuming other Prebid Org members agree on the need for this cookie-setting audit trail,  we could add a `storageConsent` field to the uids cookie. e.g.
```
{"uids":{},"tempUIDs": {
   "conversant":{"uid":"AQELI475hpdBEAINlLKNAQEBAQE",
           "expires":"2018-05-11T17:44:49.295088824Z"},
    "rubicon":{"uid":"JGH0YUU7-3-7VNU",
          "expires":"2018-05-21T18:42:21.613000000Z"}
  },
  "bday":"2018-04-27T17:44:49.224158879Z", 
  "storageConsent":{"time": "2018-04-11T17:44:49", "gdprApplies": true,
          "gdprConsent":"SFS2S1SR74EWRK390", 
          "referrer":"https://somewhere.com/some/path.html}, "checksum": "4DZ8I1"}
}
```
