### ISSUE TITLE
GDPR cookie sync configuration

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#503]
This issue is for adding GDPR support to the Prebid Server config. For an overview of GDPR support in Prebid Server, see #501

# Requirements

Prebid Server host companies must be able to:

1. Identify themselves as one of the members of the [global vendors list](https://vendorlist.consensu.org/vendorlist.json)
2. Define how Prebid Server should behave if the Request doesn't carry any GDPR info in it.

# Working design

We plan to add the following config options:

```
gdpr:
  host_vendor_id: 23
  usersync_if_ambiguous: true
```

If these are undefined, we will assume that the publisher doesn't care about GDPR and continue to sync users all the time.

If defined:
- `host_vendor_id` must be an integer > 0 which identifies the Prebid Server host company in the Global Vendors List.
- `usersync_if_ambiguous` will determine whether or not usersyncs are done if the incoming request has no `gdpr` info.

`usersync_if_ambiguous` is optional, and will be treated as `false` if `host_vendor_id` is defined.

See #504 for changes to the core logic in the endpoints.

**Comment by bretg** [comment]
LGTM
