### ISSUE TITLE
AMP user sync mixed content

### ISSUE THREAD

**Issue by adamleslie** [prebid/prebid-server#509]
We've noticed a number of user syncs being initialised for Prebid in AMP via RTC are not secure - this is throwing up mixed content errors.

Samples:

http://prebid-match.dotomi.com/prebid/match?rurl=https%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3Dconversant%26uid%3D

http://sync.e-planning.net/um?uidhttps%3A%2F%2Fprebid.adnxs.com%2Fpbs%2Fv1%2Fsetuid%3Fbidder%3Deplanning%26uid%3D%24UID

To clarify, these are observed from PrebidAppNexus RTC vendor.

**Comment by dbemiller** [comment]
That makes sense... thanks for the report.

Probably the simplest fix is just to use `https` everywhere now, as long as these sync endpoints support it. User syncs don't happen until after the auction anyway, when the pages are pretty much loaded... so there's no real reason not to.

Plus the whole web is moving in that direction anyway.
