### ISSUE TITLE
Support turning off debug/test flag by account

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#510]
There is some information in a PBS request that a publisher might want to keep private. Any bid biases would be the most likely example, it could hurt business relations if the bidders can see how they are being biased in relation to other bidders. Possibly even the list of bidders enabled could be deemed sensitive, but unless a bidder rarely bids it will show up in the non-debug data anyway. Aliases could mask the bidders though. Currently this information can be hidden in the stored request, so it doesn't ever become visible in the viewer's browser. However the initial PBS request can be captured, and then replayed with debug turned on. This will return the resolved request, exposing everything hidden in the stored request.

Do note that with prebid.js (without prebid server), there is no possibility of hiding this information, since all the data must end up on the browser one way or another. It is only with prebid server we can even consider hiding this information.

At some point we will want to review what we return in the debug, and potentially restrict the contents to preserve the privacy of data that publishers do not wish to advertise. One solution would be to define a secret token that must be included to get the full debug dump, perhaps excluding the resolved request completely. Or some other method to restrict the debug information, such as a private debug instance of the server, where the public instance is configured to disallow debugging the resolved request.

**Comment by laurb9** [comment]
With prebid-server, hiding this information can give an advantage to the host... which can also be one of the bidders.

**Comment by hhhjort** [comment]
That is true. I don't have a good solution, mostly submitted the issue as a warning that the possibility exists. Hopefully the publisher trusts their host, otherwise they should probably be looking elsewhere.

**Comment by SyntaxNode** [comment]
Is there anything actionable we can do for this situation, or should we close out the issue?

**Comment by hhhjort** [comment]
We might come up with a solution some day, but I primarily created this ticket as a "fair warning" to users. Perhaps we should put something in the documentation?

**Comment by SyntaxNode** [comment]
@bretg Let's talk about this at the next PBS Committee meeting. I think the root issue here is malicious use of the debug functionality in running an auction.

**Comment by bretg** [comment]
We discussed in committee and agreed that being able to disable the debug/test flag by account would be sufficient to provide a solution to any accounts that have a sensitivity to revealing their bidders, adjustment params, or anything else in a stored request.

Changing the title of this issue.

**Comment by SyntaxNode** [comment]
@bretg 

1. Could we please use the new flag "debug-allow" instead? I think it would be easier to expand in the future to other debug related features if they arise.
2. I suggest the warning as follows to better match the error format. We previously discussed and approved using the term "general" for non-bidder specific errors.
```
{
  "ext": {
    "warnings":  {
      "general": [{code: 10001, message: "debug turned off for bidder biddername"}]
    }
  }
}
```

**Comment by SyntaxNode** [comment]
Merged proposal with https://github.com/prebid/prebid-server/issues/1650.
