### ISSUE TITLE
appnexus does not support randomKey parameter

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#52]
Appnexus bidder allows to pass random key-value pairs to enhance buy-side targeting: http://prebid.org/dev-docs/bidders.html#appnexus (see randomKey).

Here is the bids section from request payload that was sent to prebid-server:
```
"bids": [{
    "bidder": "appnexus",
    "params": {
       "placementId": 10876685,
    "is_refresh": "false"
  },
  "bid_id": "1555b68f1fadef"
}],
```
And here is request body that was sent by appnexus server side adapter as part of rtb request:
```
{
    "id": "f6abc016-4bdd-4c37-9bdd-653abda9815a",
    "imp": [{
        "id": "ad_cs_2010299_728_90",
        "banner": {
            "w": 728,
            "h": 90,
            "format": [{
                "w": 728,
                "h": 90
            }, {
                "w": 970,
                "h": 250
            }]
        },
        "secure": 1,
        "ext": {
            "appnexus": {
                "placement_id": 10876685
            }
        }
    }],
    "site": {
        "domain": "%removed%",
        "page": "%removed%"
    },
    "device": {
        "ua": "%removed%",
        "ip": "%removed%"
    },
    "user": {
        "id": "9141190353768996862",
        "buyeruid": "9141190353768996862"
    },
    "at": 1,
    "tmax": 1000,
    "source": {
        "fd": 1,
        "tid": "f6abc016-4bdd-4c37-9bdd-653abda9815a"
    }
}
```

As you can see custom "is_refresh" parameter was not passed in rtb request.

**Comment by bokelley** [comment]
Yeah, we need to add support for that. Where would you expect the `is_refresh` param to show up in the RTB request?

**Comment by dmitriyshashkin** [comment]
Where appnexus ad server expects them. We use these custom values to target our direct sales campaigns through segments/query string targeting https://wiki.appnexus.com/display/console/Query+String+Targeting+via+Placement+Tags+and+Segments 

As it's appnexus-specific it should probably be in impression extension object. Appnexus docs regarding the rtb request don't have anything about random keys / keywords: https://wiki.appnexus.com/display/adnexusdocumentation/Outgoing+Bid+Request+to+Bidders#OutgoingBidRequesttoBidders-ImpressionExtensionObject 

If some new object must be added to make it work, I guess "keywords" (as these random keys are called in Appnexus AST) will be a good choice.

**Comment by bokelley** [comment]
Keywords is now live in PBS; I believe PBJS now needs to be updated to send them properly.

**Comment by dbemiller** [comment]
@dmitriyshashkin could you open an Issue to the `Prebid.js` project for this, if you're still interested in it?

As bok said, `Keywords` are supported by the Appnexus adapter in Prebid Server now.
