### ISSUE TITLE
Travis Build failure on go version go1.9

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#526]
While building our new oath adaptor codebase, one of the build jobs(one building on go version 1.9) is failing: Attaching the build job link below. 
https://travis-ci.org/prebid/prebid-server/builds/382830737
The failing build job(Job #2211.1) doesn't list  any exact reason for failure also.

You can see the build is done successfully on go1.10.1 version as per the Travis build log on the same link. 
I tried the same build command  on my local for both go versions (go version go1.9.6 darwin/amd64 and go version go1.10.1 darwin/amd64 ) and is able to successfully build on both.

**Comment by dbemiller** [comment]
very interesting...

Are you sure you're running `./validate.sh --nofmt --cov`? This fails for me consistently on go1.9.3.

I don't get debug output either, which is very frustrating. However, running `./validate.sh` (with _no_ `--nofmt` flag) does make a formatting fix to `usersync/usersync.go`

**Comment by dbemiller** [comment]
#527 fixes the issue with bad debugging output.

**Comment by smithaammassamveettil** [comment]
Yes, I tried those 2 commands
  ./validate.sh (without --nofmt flag)

also
  ./validate.sh --nofmt  --cov

Both are successfull on my local

**Comment by dbemiller** [comment]
Bizarre... it looks like you've got it fixed now though.

Fair to close this?

**Comment by smithaammassamveettil** [comment]
Yes,
looking at your comment above "*However,
running ./validate.sh (with no --nofmt flag) does make a formatting fix to *
*usersync/usersync.go"*, I did some cleanups in this file, which helped to
fix the issue.

Thanks for pointing out this.

Also it will be great to have the reason listing clearly in the build
failure log. Hope your other PR will do that. Thanks!
