### ISSUE TITLE
Add bid cache errors to the response

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#540]
In the [cache bids](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#cache-bids) docs, we say:

> Clients _should not assume_ that these keys will exist, just because they were requested

The code works as documented... but recently I've heard from a few people who are confused about _why_ the `hb_cache_id` doesn't exist. It could be:

1. Cache call timed out
2. Cache call failed on the network
3. Cache returned a failure response
4. `hb_pb` was 0.00 with the price granularity, so [we didn't cache it](https://github.com/prebid/prebid-server/issues/199)

This is especially confusing with AMP, where the setup won't work unless the bid made it into the cache successfully. In debug mode, callers will see a seemingly valid bid, but no targeting keys.

We should return a `response.errors.prebid` whenever `cache.bids` was true and `hb_cache_id` is _not_ set on the winning bid, and make sure that these errors show up in the AMP response too.

**Comment by hhhjort** [comment]
Should we perhaps invalidate any bids on AMP requests where the cache call failed? I don't think the AMP environment has the flexibility to verify the existence of `hb_cache_id` and adjust the targeting parameters appropriately.

**Comment by dbemiller** [comment]
it does :)... that's actually how this issue surfaced: https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/amp_auction.go#L143

Someone thought it was a bug in the AMP endpoint... so the goal here is to make it clearer for them.
