### ISSUE TITLE
Question on UserSync params

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#546]
Type: Question

Description:
When implementing the UserSync ,
foreg: for brightroll adapter, did something like below

return &syncer{
   familyName: "brightroll",
  gdprVendorID: 25, //oath vendor Id
  syncEndpointBuilder: resolveMacros(syncEndUrl),
  syncType: SyncTypeRedirect,
}

What is the significance of familyName here? 
As per document listed at https://vendorlist.consensu.org/vendorlist.json, gdprVendor name is "oath" for gdprVendorID 25 which we used in our brightroll server adapter . 
But as you see above in the syncer call, familyName value is given as "brightroll", not "oath". I had given the biddername or adaptername here as familyname. So my question here is what is the significance of 'familyName', whether it should match with gdprVendorName ? Or it can be adaptername?

**Comment by dbemiller** [comment]
You're good. That has nothing to do with GDPR, and should be the adapter name.

I actually updated the docs on this earlier today because I noticed they were unclear: https://github.com/prebid/prebid-server/pull/544/files#diff-43523b5b25a2a8e9788128e648c9c2ceL12It

**Comment by smithaammassamveettil** [comment]
Great..Thanks for letting me know that.

I have one more question on usersync url.
We are configuring our usersync url as

*http://ea
<http://ea>st-bid.ybp.yahoo.com/sync/appnexuspbs?gdpr={{gdpr}}&euconsent=
<http://st-bid.ybp.yahoo.com/sync/appnexuspbs?gdpr={{gdpr}}&euconsent=>{{gdpr_consent}}*
&url=
http://prebid.adnxs.com/setuid?bidder=brightroll&gdpr={{gdpr}}&gdpr_consent={{
gdpr_consent}}&uid=$UID


For GDPR support, we need to pass 'gdpr' and 'euconsent' fields to our
system. So I have given the URL as above. But looks like the
'syncer.resolveMacros' method is not updating those field values even if I
have given the same syntax representation which the method looking to
replace. and it is happening for appnexus usersync url given under
parameter 'url' in the same url.

Can you please let me know how can we make it happen to pass those fields
in the above URL?

**Comment by dbemiller** [comment]
@smithaammassamveettil can this be closed? It looks like you fixed it in #562.

**Comment by smithaammassamveettil** [comment]
Yes, we can close it now
