### ISSUE TITLE
Enhancement: Add error checking on AMP Stored Request to UI

### ISSUE THREAD

**Issue by aneuway2** [prebid/prebid-server#548]
**Current State**
For AMP users who are inputting their stored request in prebid server, there is only basic syntax checking when editing/inputting the stored request

To check if the request is valid, the user has to setup their AMP page and attempt to make a request.

If there is an error, prebid server returns a server error code. The user then needs to load that URL in the browser to review what the specific error is. e.g:

```
Invalid request format: request.imp[0].ext.appnexus failed validation.
key: key is required

Invalid request format: request.imp[0].ext.appnexus failed validation.
keywords: Invalid type. Expected: array, given: object
```

**Enhancement**
When in the edit screen, provide an option for the user to test/validate the stored request AND/OR dynamically test the content of the input from the schemas located in https://prebid.adnxs.com/pbs/v1/bidders/params

**Comment by hhhjort** [comment]
The UI where you would input stored requests is not part of Prebid Server. It is up to the host of a PBS instance to put together some means of managing stored requests, so this would be a host specific request.

It might be an idea to enhance Prebid Server with some sort of endpoint to assist in testing potential stored requests, but I am not sure what that would look like exactly.
