### ISSUE TITLE
[CI] Travis CI to publish binaries in releases

### ISSUE THREAD

**Issue by benjaminch** [prebid/prebid-server#549]
Hey there,

Is there any plan / previous discussions regarding publishing binaries in releases tags?
In my opinion, it would help everyone plugged into prebid server to setup continuous integration tests in house.

https://docs.travis-ci.com/user/deployment/releases/

What do you think?

Cheers,
Benjamin

**Comment by benjaminch** [comment]
Alright ! 
I will try to have a look to this one then.
Thanks

**Comment by dbemiller** [comment]
yep yep. My experience with docker has been _really_ positive. Would definitely recommend it.

If you still think binaries would be useful though, circle back and we can see what we can do.

**Comment by benjaminch** [comment]
Thing is, on our end, if we can avoid relying on Docker and have directly binaries it's better. This way, we are sure that the app is in the expected state and have just to pull and deploy it from the latest release and then launch our integration tests.
In my experience, Docker is really nice as well but can be tricky when we need to know how the Docker container was built.

Anyways, I drafted a PR for this purpose it works on my end (in our fork). We would just need to update the Github encrypted token so Travis can publish sources in releases in Github and changing the branches on which you want to publish binaries.

**Comment by dbemiller** [comment]
Alrighty, that's totally fine. For what it's worth, there is [a Dockerfile](https://github.com/prebid/prebid-server/blob/master/Dockerfile) in this repo, so you _can_ see exactly how it's built :).

...but you're right, certain info (like "which Go version was used to compile the binary?") does get lost. And I can also understand not wanting to rely on Docker.

Which branch has the changes in your fork?

**Comment by benjaminch** [comment]
Oh, I just pushed the PR: on our Fork, the branch is https://github.com/criteo-forks/prebid-server/tree/publishing-releases-binaries

Let me know what you think.
Cheers

**Comment by dbemiller** [comment]
hmm... so I released version 0.32.0 today, and the binaries didn't show up in the release note.

Any idea why not? I triggered the release with:

```
git tag 0.32.0
git push origin 0.32.0
```

on the `master` branch

**Comment by benjaminch** [comment]
It seems it appears a bit after, but to me, it seems that binaries are there !
https://github.com/prebid/prebid-server/releases

![image](https://user-images.githubusercontent.com/1393795/41297873-6aba2ef8-6e60-11e8-9e09-a5f14f8a0b56.png)

**Comment by dbemiller** [comment]
d'oh! haha you're right. Sorry about that... I jumped the gun, but I see it now too :).

Fair to close this now?

**Comment by benjaminch** [comment]
Yes !
Thanks a lot for this one :)
