### ISSUE TITLE
Use reflection to log Configuration values

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#561]
Right now, we log the app config manually. This is prone to fall out of sync as we add/move properties around.

As suggested by [this comment](https://github.com/prebid/prebid-server/pull/560#pullrequestreview-128445961), it would be awesome if we could add a tag and log these via reflection.

> ExternalURL string `mapstructure:"external_url" log:"true"`

**Comment by hhhjort** [comment]
I would suggest log everything by default and maintain a blacklist for things like passwords which should not be logged. Saves on having to add `log:"true"` to everything.

**Comment by dbemiller** [comment]
Reopening this because I found a bug on startup

```
I0618 10:43:40.944168    6530 structlog.go:38]   	adapters: <map[string]config.Adapter Value>
```

**Comment by hhhjort** [comment]
I missed that we had map types. Will get on that.
