### ISSUE TITLE
Appnexus PBS ads are failing on https site (returning http script)

### ISSUE THREAD

**Issue by khatibda** [prebid/prebid-server#569]
We have an https site and are running appnexus demand through appnexus PBS endpoint.  The ad property in the bid response object has an http: script but our site is https:, so we're getting a javascript error on any ad that wins and attempts to render:

![image](https://user-images.githubusercontent.com/1466555/41501837-c2bfebe4-7160-11e8-964e-919a6bfdab08.png)

**Comment by khatibda** [comment]
you can see the bid response holding an ad with http here

![image](https://user-images.githubusercontent.com/1466555/41501846-fd334f28-7160-11e8-8966-d0a3dfb99442.png)

**Comment by dbemiller** [comment]
Hey @khatibda, what's the `secure` flag set to inside your `imp` in the request? https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf#page=18

That's supposed to indicate whether or not you require `https` ads.

**Comment by khatibda** [comment]
i don't see any references to "secure" in the request.  can send you a test page offline.

we are not explicitly declaring anything either.

**Comment by dbemiller** [comment]
Gotcha. That's probably the problem.

For now, you'll need to set `"secure": 1` in your imps. Standard OpenRTB treats "undefined" as "`http` ads are ok".

I opened #570 to make it behave more intuitively moving forward.
