### ISSUE TITLE
/openrtb2/auction should infer `secure` state of Imps from request

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#570]
According to [the OpenRTB spec](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf#page=18), `request.imp[i].secure` is:

> Flag to indicate if the impression requires secure HTTPS URL creative assets and markup, where 0 = non-secure, 1 = secure. If omitted, the secure state is unknown, but non-secure HTTP support can be assumed.

As a general rule, /openrtb2/auction does "infer" properties as long as they're not specified by the request. For example, it fills out the request with IP addresses, domain, user agent, auction type, etc, based on the HTTP headers, connection info, and the fact that it knows that it's a header bidding library.

I think we should do the same for `secure` status. If omitted, we can use the protocol of the request to infer whether or not to require `https` creatives.

**Comment by dbemiller** [comment]
@bretg let me know what you think about this. I saw some discussion about thee legacy endpoint in https://github.com/prebid/Prebid.js/pull/1655.

**Comment by benjaminch** [comment]
@dbemiller do you mean secure should be filled, if absent, using page URL if it contains https VS http ? 
If so, I think it's a pretty good idea !

**Comment by dbemiller** [comment]
Fixed by #572.
