### ISSUE TITLE
[sovrn] winning bids in DFP but nothing reported to Sovrn Dashboard.

### ISSUE THREAD

**Issue by mercuryyy** [prebid/prebid-server#574]
Sovrn s2s adapter is winning bids in DFP but nothing is reported in Sovrn's dashboard.

I told Sovrn of this issue about a month ago.
At the time i found out about it we of course removed sovrn from our stack.

I checked today again and this issue is still there.

Can someone from Sovrn please comment on this matter, Publishers who switch to Sovrn s2s by the time they notice could lose 100$'s to 1000$'s in revenue as we did.

Should be noted not to use Sovrn s2s adapter in prebid docs or address the issue. 

@dbemiller
@rachelrj
@benjaminch

**Comment by dbemiller** [comment]
I forwarded this issue to Sovrn too.

I understand this is frustrating... but frankly, this is the first time anyone has brought it up publicly. I don't see any issues about this bug, so we didn't know anything needed action.

> Should be noted not to use Sovrn s2s adapter in prebid docs or address the issue.

I think we could do this. My main concern is that the `prebid.org` repo is inconvenient to maintain, so docs fall out of date very easily.

How would you feel about the following strategy?

- Add a label for "adapter bugs" in this project
- Add a widget to the PBS page on prebid.org which searches for bidder-specific bugs. When run, it would link to a GitHub search for open issues.

**Comment by mercuryyy** [comment]
Great Idea i changed the title, but i think im not able to add labels to this thread. 

Hopefully Sovrn can address the issue soon.

**Comment by mercuryyy** [comment]
Still no work from Sovrn?

**Comment by rachelrj** [comment]
We are fixing this now @mercuryyy. Apologies for the delay. I'll update this thread once complete (the change might solely be on our end).

**Comment by mercuryyy** [comment]
Hi @rachelrj Any update?

**Comment by mercuryyy** [comment]
@rachelrj ping?

**Comment by rachelrj** [comment]
We made most of the updates to our system internally. Also just submitted this PR: https://github.com/prebid/prebid-server/pull/629. I think we should be g2g after that.

**Comment by mercuryyy** [comment]
@rachelrj winning bids html creative that come from sovrn over s2s are not encoded correctly resulting in the ad not being recorded.

**Comment by aprakash-sovrn** [comment]
@mercuryyy are you able to confirm if that has been fixed for you guys?

**Comment by dbemiller** [comment]
Closing b/c no response, and it's _probably_ fixed.
