### ISSUE TITLE
Client connecting to S2S adapter failing

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#575]
Problem:
One of our publishers is trying to test S2S adapter(brightroll) using Prebid.js version 0.34.1 
By following the documentation here https://github.com/prebid/prebid.github.io/pull/834/files,  they are using endpoint/requestURL  https://prebid.adnxs.com/pbs/v1/openrtb2/auction, And also 
passing all custom params and bidder details in Request payload, something like this : 
{"account_id":"XXX","tid":"XXXX","max_bids":1,"timeout_millis":1000,"url":"xxx","prebid_version":"0.23.1","ad_units":[{"code":"div-gpt-ad-919604695-1","sizes":[{"w":728,"h":90},{"w":970,"h":250},{"w":970,"h":90},{"w":468,"h":60},{"w":1800,"h":600}],"bids":[{"bidder":"brightroll","params":{"publisherName":"adthrive","slot":229},"bid_id":"15adcac0bc90f8"}],"transactionId":"43c7e84a-25f6-4c9a-85d1-fc85d7dc2457"},.......]}

But receiving "400 Bad Request" and error message as  "Invalid request: request missing required field: "id" "

Question:
1. Not sure what is this missing required field "id"?
2. Client is using Prebid.js version 0.34.1 from their test page, which they were using for client side adapter calls before. Just updated the endpoint to /openrtb2/auction and updated the brightroll required custom parameters to test S2S bidder calls. But receiving some msising required field error. Brightroll bidder has only "publisherName" as the required field. No such "id" field required for the adapter. Is there anything else which Prebid Server is expecting while making an /openrtb2/auction call?
3. Is it because the client has to use the latest Prebid.js build to connect to S2S adapter? If so, which version?
4. Any other reason for this issue? 

Please advise

**Comment by dbemiller** [comment]
yeah, Prebid.js 0.x versions aren't really supported at all anymore. I'm pretty sure `/openrtb2/auction` was never implemented there. They'll have to upgrade to Prebid.js 1.x to call you.

My recommendation would be:

1. Wait for https://github.com/prebid/Prebid.js/pull/2743 to get merged, and the next 1.x release (they happen every 2 weeks). It's a super important bugfix.
2. Set `s2sconfig.timeout` to be the same as their client-side auction timeout. If they don't define a client-side auction timeout, they should use `3000` milliseconds. That works around another PBJS bug described by [this comment](https://github.com/prebid/Prebid.js/issues/2648#issuecomment-397664676).

Then upgrade to the latest 1.x version.

**Comment by smithaammassamveettil** [comment]
@dbemiller Thanks for your response.

I updated Publisher on that and we can wait till the your PR is done to
start an end to end testing.

One concern I received from publisher side when I asked them to take latest
Prebid.js version build is as follows:
*"**I can pull the latest, but in reality it’s not that easy, because most
pubs doesn’t want to update to prebid 1.xx yet, in part because some major
bidders are still not fully ready yet. *
*So I recommend to make your bidder backward compatible if this truly
should be the issue.**"*

So looks like they are unsure about whether they can make a move to 1.x.x
version immediately. Please advise.

**Comment by smithaammassamveettil** [comment]
One more thing, I hope the Prebid.js 1.x.x. version will support both client side adapter calls along with server side adapter calls as well. Please confirm.

**Comment by smithaammassamveettil** [comment]
Also I just noticed that this  prebid/Prebid.js#2743 got merged. Should we wait for anything else to take latest Prebid.js for testing?

**Comment by dbemiller** [comment]
As a _very_ rough estimate, we see ~2/3 of our prebid impressions being served through 1.x, with ~1/3 being served through 0.x.

**Comment by smithaammassamveettil** [comment]
Thanks @dbemiller for your responses. 
I hope Prebid 1.x version is 0.x version plus openRTB support for S2S right? I mean it will do both client side full fledged auctioning which it has before PLUS bid calls and auctioning through S2S adapter as well.

Please confirm.

**Comment by dbemiller** [comment]
Yes, that is correct.

**Comment by smithaammassamveettil** [comment]
One of our publishers  updated their test page with the latest prebid version. However, it doesn’t seem to work correctly. They don’t see the s2s call being initiated
Please find below their testpage:
http://sprudeln.com/brightroll.html

Can you please check the way they are calling brightroll adapter is correct or not? Please advise

**Comment by dbemiller** [comment]
You'll probably get better answers there in the [Prebid.js](https://github.com/prebid/Prebid.js/issues/new) repo.

If there's no server call, then the issue can't be a Prebid Server one. The community over there is more active, and many people there are more familiar with debugging publisher pages than I am.

**Comment by dbemiller** [comment]
For what it's worth: I set a breakpoint on the `requestBids()` call:

![screen shot 2018-06-22 at 3 17 58 pm](https://user-images.githubusercontent.com/27972385/41795088-923f8096-762f-11e8-84e2-d2bb86682f28.png)

and don't see any `bidders` defined in the `s2sconfig`:

![screen shot 2018-06-22 at 3 18 25 pm](https://user-images.githubusercontent.com/27972385/41795098-9c1a4fd8-762f-11e8-8937-fa5cf242c016.png)

So.... that strikes me as a bit suspicious.

**Comment by smithaammassamveettil** [comment]
I see, thanks for looking into it. 
They tried some fixes on their side and made progress. Now receiving some other error

I also enabled debug mode. It looks like “bidsBackHandler” is not defined. 

![image001](https://user-images.githubusercontent.com/39389834/41800183-49b3e1d8-7629-11e8-8995-0d3669b70956.png)

**Comment by smithaammassamveettil** [comment]
Please discard my above comment

**Comment by dbemiller** [comment]
ok... should we close this, then? Or are there any other outstanding issues?

**Comment by smithaammassamveettil** [comment]
We havn't successfully finished our client testing yet. Lets keep it open for couple of days, in case if we have to troubleshoot or need any help from your side for any issues. Thanks!

**Comment by hhhjort** [comment]
Seems like enough time has passed to close this now?

**Comment by smithaammassamveettil** [comment]
Sure, We are good now. please close it. Thanks
