### ISSUE TITLE
rubicon produces error on non-standard size

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#59]
We have an ad unit with multiple sizes: 300x250 and 300x610. We have some demand for 300x610 in appnexus, but most of the time this ad unit works as normal 300x250. It works with pbjs, but inside the prebid server rubicon adapter produces an error that says that 300x610 is not supported.

As all bidders get the same list of sizes, it's not possible to disable 300x610 just for rubicon or use it just for appnexus. So it would be nice if rubicon adapter could just filter-out those sizes that it doesn't support.

**Comment by asweeney86** [comment]
This shouldn't be hard to support, but I imagine you would like to somehow get notified of this.  We we likely want to also modify our response back to the client + prebid.js.

**Comment by dmitriyshashkin** [comment]
If rubicon quietly ignored unsupported sizes it would be absolutely sufficient for me. At least as a temporary fix. And I'm not sure if it is a good idea to pass a warning that I can do nothing about.

Another thing I've noticed is that it seems that rubicon adapter is ignoring sizes param http://prebid.org/dev-docs/bidders.html#rubicon I've though that I could use it to pass a different list of sizes to rubicon. On the client side if this parameter is specified, the unit's sizes are being ignored, but as I understood from rubicon.go it's not the case for the server side adapter.

**Comment by bokelley** [comment]
See PR #60 for proposed fix

**Comment by dmitriyshashkin** [comment]
Throw error only if no legitimate sizes specified? Yes, that's exactly what I had in mind.

**Comment by bokelley** [comment]
OK - fix is merged and pushed to prebid.adnxs.com for testing
