### ISSUE TITLE
[Question] Multiple bidder endpoints support

### ISSUE THREAD

**Issue by benjaminch** [prebid/prebid-server#593]
Hello guys,

I am wondering how prebid-server is usually setup. Is there multiple instances (like one per continent) or is it usually one instance WW?

In my understanding, the prebid-server will be called via JS or SDK from client side directly. Is there any mechanism in place to hit the closest server?

If so, it would be interesting for a bidder to be able to specify several endpoints depending on the continent the prebid-server is running.
I am not sure if the server is location-aware or not. 

Also, does one instance is serving publishers / users spread across on several continents?

I would be happy to hear more about how existing servers are usually setup.

Thanks !

**Comment by hhhjort** [comment]
There is nothing inside PBS to handle geo-routing, but then again once you have connected to a particular instance of PBS, it is too late to route the connection to a "closer" instance. In general, this is a problem solved at the DNS level, where at the time of the DNS lookup a determination of the "closest" instance of PBS can be made, and the external IP for that instance (or cluster) can be delivered in the DNS response.

As for multiple instances of PBS, there is no problem. Each request is independent of all other requests, there is no state or session that needs to be preserved. The only thing that all the instances need access to is the set of stored requests. This updates rarely on the time frame of prebid requests, so a little lag getting updates out to all instances is not generally fatal. So there are no issues with running multiple clusters, either in a datacenter for load balancing, or across datacenters to support local connections.

I have not done any sort of survey of how people have set up PBS, so I cannot comment on how it is usually done. We run PBS in 4 datacenters worldwide, so not quite 1 per continent. :) I feel the question will really come down to is the decrease in latency worth the expense of extra instances across the world. If you currently only have one datacenter, I strongly suspect that the latency will not be worth the expense in setting up extra datacenters, and setting up a geo-aware DNS system. But if you already run multiple datacenters, it should not be that difficult to set up some distributed instances to at least test how much latency you can shave off, and then determine if a full distributed deployment is worth it to you.

**Comment by benjaminch** [comment]
Thanks for your answer @hhhjort.

Regarding 

> There is nothing inside PBS to handle geo-routing, but then again once you have connected to a particular instance of PBS, it is too late to route the connection to a "closer" instance

I was more thinking about, once on the PBS instance, just trying to use the nearest DC (from the PBS instance) to call the bidder.
I'll see if there is a way to setup a global bidder URL distributing requests to the closest DC.

Another use case, would possibly be to load balance requests in case one endpoint is long to respond, maybe the traffic can be shifted to the second one, but I think it's another use case.

**Comment by hhhjort** [comment]
You can set up your PBS config per-instance, so you can specify the "closest" bidder endpoint on each instance.

As for failover, this would require a lot of work and restructuring the code to support. It is also more properly supported on the bidder side, where they would provide a URL that has the failover built in to their infrastructure, rather than coming up with some sort of ad hoc failover we might code up ourselves.

**Comment by benjaminch** [comment]
Thanks @hhhjort, works for me, just wanted to know if some setups like that where out already.

I am closing this one then, thanks again :)
