### ISSUE TITLE
AMP endpoint hides errors even in debug mode

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#616]
So currently the response for amp endpoint includes 1) targeting 2) http calls 3) resolved request. Errors received from adapters are passed to the `AmpAuction` function but ignored. 

Which makes debugging extremely difficult, there is no way to understand what exactly went wrong. The only hint is the absence of the query to one of the bidders in the HTTP calls list. The two possible workarounds for a publisher I see right now are 1) compile your own PBS instance and add some glog.Info calls 2) send request to openrtb2/auction endpoint with the mention of the stored request used for amp. Both solutions are rather cumbersome and require good technical knowledge.

I would suggest adding a new section to the amp endpoint's response that would contain all the errors that happened during the auction.

**Comment by dbemiller** [comment]
Sounds like a great idea.
