### ISSUE TITLE
Prebid 1.x support concurrent requests for server and client

### ISSUE THREAD

**Issue by AskRupert-DM** [prebid/prebid-server#627]
I had been previously using/testing a legacy prebid.js version (0.34.x) that included the prebid server adaptor and was able to call various bidders that supported both client and server side calls concurrently. 

However, since moving to 1.1x am finding I can no longer do this so wanted to check if its still possible to run bidders concurrently both client and server side so a side by side comparison can be made on bid response/match and fill rates.
 
Is this still possible to do with latest prebid versions (ie run a bidder both server and client side) ?

**Comment by mkendall07** [comment]
The same bidder was never supported both client and server side at the same time AFAIK. So no, you can switch but you cannot run concurrently with the same bidder.

**Comment by AskRupert-DM** [comment]
Thanks for the response - so if you want to run a bidder concurrently (server/client) side is the workaround to use an alias for the alternative ? The testing module allows you to switch requests between server and client side but you can really use that for a like for like comparison in terms of match and fill rates ?

**Comment by AskRupert-DM** [comment]
![client-and-server-prebid-anx](https://user-images.githubusercontent.com/35333377/42964683-ae1cdac8-8b8f-11e8-8663-84fcd3e26e9a.png)

Here's a grab showing a network request for appnexus going both via the client (last 'prebid' request shown in the grab) and my s2s endpoint (/auction in the grab) - other bidders only seem to allow you to switch whereas I'm sure I previously saw them work concurrently with a legacy version of prebid but no longer have those testpages to re-check...

Based on your previous response whilst its not something thats previously been supported (concurrent ly running bidders both client / server side) -  publishers would want to run server and client side so that match/fill rates can be compared more accurately rather than using a percentage sample of inventory which the testing module provides -  is there a custom workaround we could use to do this (such as aliasing adaptors for the server-side calls) or a specific reason why this would never be supported or recommended ?

**Comment by dbemiller** [comment]
I'm not an expert on Prebid.js, but I believe it _should_ work if you define an alias and send one server-side.

If that doesn't work, I think you should move this question/conversation over to the Prebid.js issues. Prebid Server is definitely capable of handling concurrent requests... so there aren't any action items for this project/codebase.
