### ISSUE TITLE
IndexExchange vs ix

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#657]
For PBJS 1.0, IndexExchange changed the name of their PBJS adapter to `ix`.

This is causing compatibility issues with calling PBS via the prebidServerBidAdapter. Two specific issues:

1) 'ix' isn't recognized on the Prebid Server side
2) the `siteId` parameter is defined on the client side, but the server expects `siteID`

**Comment by dbemiller** [comment]
A few related tickets redirect here... so linking these comments for visibility:
- https://github.com/prebid/Prebid.js/issues/3044#issuecomment-422952684
- https://github.com/prebid/Prebid.js/pull/2916#issuecomment-426264997

I've heard nothing about this personally... but technically, according to the docs we don't even support 0.x anymore: http://prebid.org/dev-docs/bidders.html

At this point it should be safe to just make the breaking change and rename the Index adapter to `ix`.

**Comment by akira28** [comment]
Seems that they are working on it on their fork: https://github.com/indexexchange/prebid-server/commit/aeb02bb78714f297ffc027174afb2a30a220e922

**Comment by dbemiller** [comment]
This has been merged & should be resolved now.
