### ISSUE TITLE
PreBid Server Installation

### ISSUE THREAD

**Issue by jsmith1007** [prebid/prebid-server#659]
We are a niche Media Company wanting to implement Prebid Server and are looking for available experts to assist or build an environment.  It would be hosted as an AWS server or other similar. 

We are ready to move forward if you're available.  
Thanks
Jason
jason.smith@cleanmedia.net
859-536-5648

**Comment by dbemiller** [comment]
GitHub Issues are for reporting bugs and suggesting/discussing feature designs... not recruiting/hiring.

**Comment by jsmith1007** [comment]
My apologies, I didn’t mean to misuse the system. 

 

Thanks

Jason

 

 

Jason Smith

Business Development

CleanMedia.net

859-536-5648

 

e:  <mailto:jason.smith@cleanmedia.net> jason.smith@cleanmedia.net
