### ISSUE TITLE
Need to tighten respecting the context on requests

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#669]
A bug recently surfaced where a request could hang after an adapter panic (#668 ). We should add some additional code to make sure we eventually close the connection if the context expires. Basically review the critical path and see where else we can check the context for expiry to prevent similar issues from occurring.

**Comment by SyntaxNode** [comment]
In reviewing this old issue, we can't seem to find any potential problems with the current codebase. The httpclient is created in `exchange/bidder.go#doRequestImpl` and looks to properly handle error cases.
