### ISSUE TITLE
Has anyone run Prebid Server in a Windows Server environment?

### ISSUE THREAD

**Issue by Wade-McDaniel** [prebid/prebid-server#670]
I'm having trouble getting Prebid Server to run on a Windows Server environment.

I was able to build prebid-server.exe, but when I try to run it it looks like prebid-server is erroring on the backslash path deliminators Windows uses, so it can't find any of it's dependencies.

> PS C:\Users\wade\go\src\github.com\prebid\prebid-server> .\prebid-server.exe
> F0906 08:57:42.188572   45292 pbs_light.go:693] Failed to create the bidder params validator. Failed to load json schema at C:\Users\wade\go\src\github.com\prebid\prebid-server\static\bidder-params\adform.json: open C:%5CUsers%5Cwade%5Cgo%5
> Csrc%5Cgithub.com%5Cprebid%5Cprebid-server%5Cstatic%5Cbidder-params%5Cadform.json: The system cannot find the file specified.
> goroutine 1 [running]:
> github.com/prebid/prebid-server/vendor/github.com/golang/glog.stacks(0xc000292400, 0xc000316000, 0x16e, 0x1da)
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/vendor/github.com/golang/glog/glog.go:769 +0xdb
> github.com/prebid/prebid-server/vendor/github.com/golang/glog.(*loggingT).output(0x1176aa0, 0xc000000003, 0xc0000d2370,
> 0x10db301, 0xc, 0x2b5, 0x0)
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/vendor/github.com/golang/glog/glog.go:720 +0x324
> github.com/prebid/prebid-server/vendor/github.com/golang/glog.(*loggingT).printf(0x1176aa0, 0x3, 0xb9a9ec, 0x30, 0xc0004
> 7de18, 0x1, 0x1)
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/vendor/github.com/golang/glog/glog.go:655 +0x152
> github.com/prebid/prebid-server/vendor/github.com/golang/glog.Fatalf(0xb9a9ec, 0x30, 0xc00047de18, 0x1, 0x1)
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/vendor/github.com/golang/glog/glog.go:1148 +0x6e
> main.serve(0x0, 0x0, 0xc000063180, 0x0, 0x0)
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/pbs_light.go:693 +0x3c5
> main.main()
>         C:/Users/Wade/go/src/github.com/prebid/prebid-server/pbs_light.go:643 +0x1ed

Any suggestions? 
Thank you!

**Comment by dbemiller** [comment]
I have not tried it on windows... but the error message comes from here: https://github.com/prebid/prebid-server/blob/master/openrtb_ext/bidders.go#L98

The function is called from here: https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L691

which uses this string constant: https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L80

Sounds like it might work if you sanitize it? Try this: https://golang.org/pkg/path/filepath/#FromSlash

I don't have a windows machine, or I'd test it myself. If it works, submit a PR and we'll be happy to merge it.

**Comment by Wade-McDaniel** [comment]
Thanks for the help, @dbemiller !

I'm giving it a shot, but I've never even heard of go before yesterday, so I'm having some trouble.

I changed this line: https://github.com/prebid/prebid-server/blob/master/pbs_light.go#L691
to this line (after adding "path/filepath" in the import section at the top of that file):
`paramsValidator, err := openrtb_ext.NewBidderParamsValidator(filepath.FromSlash(schemaDirectory))`
and ran `go clean . ` and then `go build .` again, but the error remains the same.

I don't want to bother you, but how would you go about debugging this? Do you use something like Visual Studio Code so you can see what filepath.FromSlash(schemaDirectory) is outputting?

**Comment by dbemiller** [comment]
Kind of outdated, but... I actually usually just do println debugging :x. So something like:

```
platformPath := filepath.FromSlash(schemaDirectory)
glog.Warningf("platformPath is:  %s", platformPath);
paramsValidator, err := openrtb_ext.NewBidderParamsValidator(platformPath)
```

Run  with `--logtostderr=1` to make it print the output.

**Comment by Wade-McDaniel** [comment]
Just in case anyone else reads this thread, I figured I'd report that I gave up on getting Prebid Server to run under Windows Server. We have a Linux box that I'm going to run this off of. It doesn't have a lot of horsepower, hardware-wise, but I'm guessing the resource-load of Prebid Server is fairly small.

Thanks for the help here!
