### ISSUE TITLE
Prebid AMP drop off

### ISSUE THREAD

**Issue by adamleslie** [prebid/prebid-server#680]
Hi,

We've noticed a substantial decline in our RTC vendor prebidappnexus revenue as of 09/13.

As we're observing this across two different domains (and Prebid server instances) with no corresponding releases on our side we believe that this is potentially a change that was made to the product around this time.

Are you able to confirm?

Revenue is down ~70% across our domains and this is not aligned with our traffic or being influenced by some other setup in our stack as far as we're concerned.

May be related to this #678 also as we're seeing similar behaviour on the FE (consistent no targeting values w/ no responses from AppNexus)

CC @mkendall07 @mjacobsonny @dbemiller @hhhjort

**Comment by hhhjort** [comment]
We have rolled back the AppNexus instance to 0.42.0 to see if that resolves the issue, and determine if the update is the cause or if there is something else.

Are you seeing this on just AMP pages, or both AMP and non-AMP?

Only thing we can think of at this time is #658, which filters out some PI information from the requests if proper consent is not provided. AMP does not currently support generating an IAB consent string, so all prebid server requests from AMP are essentially consentless. The revenue drop my be in response to bidders being less willing to bid without this info.

**Comment by adamleslie** [comment]
Reviewing our traffic for AMP specifically: ~70%

I can also confirm filtering AMP AppNexus revenue for US only (as a sample) shows revenue as stationary/unimpacted.

Any other questions LMK - happy to help.

**Comment by hhhjort** [comment]
Would your bidders simply not bid at all without any user data being sent? The `user.buyerid` will be dropped without GDPR consent.

**Comment by adamleslie** [comment]
Looks that way.

This is what we're seeing in the APN UI for Metro filtered to UK geo:

![image](https://user-images.githubusercontent.com/17123120/45626302-16c28c00-ba87-11e8-8556-9495dddc7e21.png)

This is what we're seeing for Rubicon filtered for UK geo:

![image](https://user-images.githubusercontent.com/17123120/45626391-5be6be00-ba87-11e8-9f21-3964d61301c2.png)

**Comment by adamleslie** [comment]
Real time data showing spend returning:

![image](https://user-images.githubusercontent.com/17123120/45627252-73bf4180-ba89-11e8-87fa-9abf173a8130.png)

**Comment by dbemiller** [comment]
That looks pretty clear to me... thanks for the report!

One last question: could you give us your placement ID?

**Comment by adamleslie** [comment]
Sure mate, here are all the placement IDs we use for AMP:

MOL: 11609642, 11609643, 11609645, 11609652
Metro: 11160521, 11160522, 11160540, 12682951, 11160550

Again, thanks for the quick resolution on this.

**Comment by dbemiller** [comment]
Re-opening this for now because it's still an issue we have to investigate & deal with.

Other PBS hosts should know not to release `0.43.x` if they have EU users to worry about.

**Comment by hhhjort** [comment]
We will want to reinstate the GDPR code at some point, as we can't simply ignore the GDPR. We have a PR in place to make a concession to AMP(#681 ), but the real fix is to get AMP to properly support sending GDPR consent.

**Comment by adamleslie** [comment]
Yeah, that's fair - I think this is blocked on the following ticket:

https://github.com/ampproject/amphtml/issues/17742

If you need me to review my numbers after any releases LMK.

**Comment by dbemiller** [comment]
We looked through some your placements' data and think #682 will solve the problem. Some of the incoming requests (to Appnexus' servers) had IPs like `123.456.78.000`, which is how PBS was anonymizing IP addresses if consent didn't exist, and Appnexus wasn't bidding on it. For at least one request, we switched it to `123.456.78.0` and it got bids again.

There may be other problems too, of course... but this is a pretty significant one.

We'll leave another comment on this ticket when we release it as a patch so you can keep an eye on things.

**Comment by adamleslie** [comment]
I remembered that Prebid in-app is a function of Prebid server - reviewing the numbers it looks like this was in scope for this issue also:

![image](https://user-images.githubusercontent.com/17123120/45691011-8dc35780-bb4f-11e8-8659-e35437061df3.png)

It's worth noting that we should be passing consent for these calls. Just confirming this needs to be in scope for whatever changes you're making/testing.

Placement ID for this is 12796058

**Comment by hhhjort** [comment]
We have pushed out a new version, please keep an eye on performance. Thanks

**Comment by adamleslie** [comment]
Morning @hhhjort ,

This change appears to have broken things again:

![image](https://user-images.githubusercontent.com/17123120/45749656-39c67a80-bc04-11e8-90bc-5047f2f6b5ca.png)

**Comment by hhhjort** [comment]
We have rolled back Prebid Server again while we investigate a little deeper.

**Comment by hhhjort** [comment]
A quick look at a sample of requests from you in that time period suggests the issue might not be GDPR filtering this time. Are you seeing the drop across more bidders than AppNexus? Has the rollback recovered the numbers?

**Comment by adamleslie** [comment]
Seeing spend return for AppNexus:

![image](https://user-images.githubusercontent.com/17123120/45754795-85812000-bc14-11e8-8019-0c83e3eadb1a.png)

Rubicon has a 6 hour lag on reporting but does appear to be broken since around the same time:

![image](https://user-images.githubusercontent.com/17123120/45755396-39cf7600-bc16-11e8-81fe-cff310f77a20.png)

**Comment by adamleslie** [comment]
Confirming revenue levels are holding at normal levels after the last change for AppNexus bidder as a sample.

Best,
Adam

**Comment by hhhjort** [comment]
Seems that all is good.
