### ISSUE TITLE
Having trouble getting Prebid Server to respond to GETs

### ISSUE THREAD

**Issue by Wade-McDaniel** [prebid/prebid-server#691]
Greetings,

I'm sorry to have to ask for help getting Prebid Server running again, but I am at a loss for how to debug why prebid-server isn't responding to requests on port 8000

- I've opened a tcp hole in the firewall for port 8000
- ps aux | grep prebid-server shows that prebid-server is running
- netstat -anp | grep 8000 shows that prebid-server is listening on tcp 127.0.0.1:8000
- httpd isn't listening to port 8000, just 80 and 443

...but when I try to GET http://myprebidserver.com:8000/openrtb2/amp?tag_id=my_tag_id per https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/amp.md I just get timed-out

**Questions:**

1. Where does prebid-server write it's logs to so I can see if it's even seeing my GET requests?
2. The directory /openrtb2/ doesn't actually exist on the disk; does that matter, or does prebid-server just parse the path as it sees fit?

Thanks again for the help here!

**Comment by hhhjort** [comment]
By default prebid server logs to standard out. The paths don't matter, prebid parses the path without reference to any directory structure.

Not sure why you would get a timeout on the request, the logic must be getting stuck somewhere outside of where we are checking for the context to expire. The logs will probably shed some light on this.

**Comment by dbemiller** [comment]
Actually... you might need to run with `./prebid-server --logtostderr=1` to see logs in the terminal.

There are lots of reasons why the request might not make it through the network... I'm probably not too helpful there. To narrow it down, though, you could try sending a request to `localhost:8000` on the same machine that's running PBS.

**Comment by Wade-McDaniel** [comment]
logtostderr definately outputs more info. But in both cases the only thing that looks like an error is this:
```
E0920 18:21:58.708340   20443 facebook.go:284] No facebook partnerID specified. Calls to the Audience Network will fail. Did you set adapters.facebook.platform_id in the app config?
E0920 18:21:58.708448   20443 facebook.go:284] No facebook partnerID specified. Calls to the Audience Network will fail. Did you set adapters.facebook.platform_id in the app config?
```

also, I see something about an Admin server starting on port 6060, but I haven't opened a hole in the firewall for that.

when i run curl http://myprebidserver.com:8000/ I get a page back immediately, so I bet my ISP has a firewall between my machine here in my office and myprebidserver.com. So false alarm - sorry about that!
