### ISSUE TITLE
Prebid Server Appnexus registration form

### ISSUE THREAD

**Issue by Ars3nik** [prebid/prebid-server#695]
Hi all, the prebid server appnexus registration form doesn't work, it yield about some requiered field that has been filled.

https://prebid.adnxs.com/apply/

Same for you ?
Tks

**Comment by hhhjort** [comment]
You should contact your AppNexus account manager to resolve the issue. This space is for the open source project, not for supporting extra software beyond the scope of this project.

**Comment by mkendall07** [comment]
The issue is you have to select the checkmark for "Subscribe to mailing list".
