### ISSUE TITLE
AMP override height and width

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#698]
Followup to issue #420. 

Found https://github.com/ampproject/amphtml/issues/5156 which says
```
The override-width and override-height parameters are the size of ad unit as configured in DFP. 
(Normally the ad width and ad height are the same as the ad unit size, but this is a “native” ad, 
and can render at any size.) In this case, GPT returns an iframe sized at 2x200; this is a 
“transport” iframe, and not intended to be visible.
```
But our documentation at https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/amp.md#query-parameters says:
```
If present, these will override parts of your Stored Request.

ow, oh, w, h, and/or ms will be used to set request.imp[0].banner.format if request.imp[0].banner is present.
```

I think the correct behavior should be that Prebid Server ignores `ow` and `oh`... believe they're meant to be sent to DFP and not affect the size of the bids.

**Comment by hhhjort** [comment]
My initial reading of the AMP issue lead me to conclude you were correct, but now I believe the current behavior is correct. The initial bug report has a nice expected/actual example that helps clarify what is supposed to happen:

```The example on this sample page is a bit awkward because the creative is a normal banner/ static image at 300x250, but the expected outcome is for it to render at 500x100. Rendering a 300x250 image at 500x100 looks visually wrong, but regardless the example demonstrates the problem.```

Expected result:
```<amp-ad 
    width="500" 
    height="100" 
    data-override-width="300" 
    data-override-height="250" 
    type="double-click"
    data-slot="/35096353/amptesting/image/static" 
    class="-amp-element -amp-layout-fixed -amp-layout-size-defined -amp-layout" id="AMP_1"
    style="width: 500px; height: 100px;">```

So the expected result is to be given an ad sized to the override size, and then AMP resizes it to the "plain" sizes.

**Comment by bretg** [comment]
Ok - closing then. It appears that the original issue solved this adequately.
