### ISSUE TITLE
jsonpatch.MergePatch silently failing in processStoredRequests() in endpoints/openrtb2/auction

### ISSUE THREAD

**Issue by afsheenb** [prebid/prebid-server#700]
Hello,

I'm testing stored requests with the http endpoint at the moment, and running into a subtle bug that's stopping me from continuing my tests.

Defined in my pbs.yaml:

```stored_requests:
  http:
    endpoint: http://test-http.testdomain.com:8081/reqs
    amp_endpoint: http://test-http.testdomain.com:8081/reqs?amp=true
  in_memory_cache:
    ttl_seconds: 300 # 5 minutes
    request_cache_size_bytes: 107374182 # 0.1GB
    imp_cache_size_bytes: 107374182 # 0.1GB
```

A test request and response sent to the `http://test-dev.testdomain.com:8081/reqs` endpoint:

curl request:

```
curl "http://test-http.testdomain.com:8081/reqs?imp-ids=\[\"imp1\"\]"
``` 
Response:
```
{"imps": {"imp1": "{ \"banner\": { \"format\": [ { \"w\": 300, \"h\": 250 } ] }, \"ext\": { \"appnexus\": { \"placementId\": \"123456\" } } }"}}
```

So far so good. If I were to send a test request to my prebid-server instance with the following payload:

```
curl 'http://test-pbs.testdomain.com/openrtb2/auction' --data-binary '{ "id": "test-request-id", "imp": [ { "id": "test-imp", "ext": { "prebid": { "storedrequest": { "id": "imp1" } } } } ], "site":{"page":"http://demo.the-test-prebid-page.com"}}'`
```

I would expect the data returned by the `http://test-http.testdomain.com:8081` endpoint to be merged with the data in the test request. However, it's failing to merge, and instead I'm receiving this error:

```
Invalid request: request.imp[0] must contain at least one of "banner", "video", "audio", or "native"
```
...because the `banner` key is in the stored request that's failing to be merged.

 I've confirmed that the issue is happening with jsonpatch.Mergepatch by adding the following lines in the processStoredRequests() function to print out the json being merged:

```        // Apply any Stored Imps, if they exist. Since the JSON Merge Patch overrides arrays,
        // and Prebid Server defers to the HTTP Request to resolve conflicts, it's safe to
        // assume that the request.imp data did not change when applying the Stored BidRequest.
        for i := 0; i < len(impIds); i++ {
                resolvedImp, err := jsonpatch.MergePatch(storedImps[impIds[i]], imps[idIndices[i]])
                if err != nil {
                        return nil, []error{err}
                }
                printStoredImp, _ := json.Marshal(storedImps[impIds[i]])
                fmt.Println("Stored Imp:")
                fmt.Println(string(printStoredImp))

                printStoredImpIndice, _ := json.Marshal(imps[idIndices[i]])
                fmt.Println("Imp Id Index:")
                fmt.Println(string(printStoredImpIndice))

                printResolvedImp, _ := json.Marshal(resolvedImp)
                fmt.Println("Resolved Imp:")
                fmt.Println(string(printResolvedImp))

                imps[idIndices[i]] = resolvedImp
```

Compiling with these lines added and sending a test request, I see the following logged:

Stored Imp:
```
"{ \"banner\": { \"format\": [ { \"w\": 300, \"h\": 250 } ] }, \"ext\": { \"appnexus\": { \"placementId\": \"123456\" } } }"
```
Imp Id Index:
```
{"id":"test-imp","ext":{"prebid":{"storedrequest":{"id":"imp1"}}}}
```
Resolved Imp:
```
"eyJleHQiOnsicHJlYmlkIjp7InN0b3JlZHJlcXVlc3QiOnsiaWQiOiJpbXAxIn19fSwiaWQiOiJ0ZXN0LWltcCJ9"
```
So - `storedImps[impIds[i]]` holds our stored request data in JSON format, successfully retrieved from our HTTP endpoint;  `imps[idIndices[i]]` holds the data for the imp[i] object sent in the request, but `resolvedImp` is set to `eyJleHQiOnsicHJlYmlkIjp7InN0b3JlZHJlcXVlc3QiOnsiaWQiOiJpbXAxIn19fSwiaWQiOiJ0ZXN0LWltcCJ9`, which is just the base64 encoded JSON string `{"ext":{"prebid":{"storedrequest":{"id":"imp1"}}},"id":"test-imp"}`.

Even though the JSON for the stored Imp seems to be valid, and no error is thrown during the jsonpatch.MergePatch() call, the JSON apparently isn't being merged successfully, and instead the MergePatch() is silently failing. 

I've tried removing the quotes from the JSON object returned by the HTTP endpoint with no change; I'm not sure if there's a snafu with the format that the stored request is in (which appears to be valid JSON), or if this is a bug of some sort. 

Please advise.

Thanks,

--afsheenb

**Comment by afsheenb** [comment]
Update: if I add the imp.banner object to my test request, I'm able to get a bit farther, but still fail with an error:

curl request: 

```
curl 'http://test-pbs.testdomain.com/openrtb2/auction' --data-binary '{ "id": "test-request-id", "imp": [ { "id": "test-imp","banner": { "format": [{ "w": 300, "h": 250 }, { "w": 300, "h": 600 }] }"ext": { "prebid": { "storedrequest": { "id": "imp1" } } } } ], "site":{"page":"http://demo.the-test-prebid-page.com"}}'
```

response:

```
Invalid request: Invalid JSON Patch
```

curl request and response returned from stored request HTTP endpoint for the imp id that I'm trying to merge:

```
curl "http://test-http.testdomain.com:8081/reqs?imp-ids=\[\"imp1\"\]"
```
```
{"imps": {"imp1": "{\"imp\": [{\"ext\":{\"appnexus\":{\"placementId\":123456}}]}"}}```
```

**Comment by afsheenb** [comment]
With that  last discovery, I suppose this ticket can be divided into two questions:

1) Is it expected for it to be necessary to have the `imp.banner` object present in the client request that's merged in with a partially stored request? The absence of the `imp.banner` object leads to a validation error.

2) What exactly is a valid JSON response to a request for an imps object sent to a Stored Requests HTTP API endpoint?  From https://github.com/prebid/prebid-server/blob/master/stored_requests/backends/http_fetcher/fetcher.go#L18-L38 I see:

```
// NewFetcher returns a Fetcher which uses the Client to pull data from the endpoint.
//
// This file expects the endpoint to satisfy the following API:
//
// GET {endpoint}?request-ids=["req1","req2"]&imp-ids=["imp1","imp2","imp3"]
//
// This endpoint should return a payload like:
//
// {
//   "requests": {
//     "req1": { ... stored data for req1 ... },
//     "req2": { ... stored data for req2 ... },
//   },
//   "imps": {
//     "imp1": { ... stored data for imp1 ... },
//     "imp2": { ... stored data for imp2 ... },
//     "imp3": null // If imp3 is not found
//   }
// }
//
//

```

What specifically should be inside the `{ ... stored data for imp1 ... }`, and why does trying to merge a response of `{"imps": {"imp1": "{\"imp\": [{\"ext\":{\"appnexus\":{\"placementId\":123456}}]}"}}` result in a `Invalid request: Invalid JSON Patch` error being returned?

**Comment by hhhjort** [comment]
1. It is not expected that the `imp.banner` object exists. 

2. Looks like you had the correct stored request object initially:
```
{"imps": {"imp1": "{ \"banner\": { \"format\": [ { \"w\": 300, \"h\": 250 } ] }, \"ext\": { \"appnexus\": { \"placementId\": \"123456\" } } }"}}
```
But in your last example your datastore was returning:
```
{"imps": {"imp1": "{\"imp\": [{\"ext\":{\"appnexus\":{\"placementId\":123456}}]}"}}
```
Which really does not make sense. It looks like some mashup of the actual stored request response, and the payload you are delivering to the `/openrtb2/auction` endpoint that is supposed to reference the stored imp. 

The `Invalid request: Invalid JSON Patch` error is being triggered by the second stored imp request payload above: `"{\"imp\": [{\"ext\":{\"appnexus\":{\"placementId\":123456}}]}"` not actually being valid JSON. Expanding it into JSON, it looks like:
```
{
	"imp": [{
			"ext": {
				"appnexus": {
					"placementId": 123456
				}
			}]
	}
```
which is missing one `}` before the `]`.

**Comment by dbemiller** [comment]
Looks like your Stored Request payload is a JSON object encoded into a string:

```
"imp1": "{ \"banner\":  ..."
```

The JSON Merge code expects an object:

```
"imp1": {"banner": { ... }
```

That would definitely make the JSON merge misbehave.

**Comment by afsheenb** [comment]
Strike my last, got it working just now - after the JSON was fixed there were two separate problems in the  client request being sent. 

Thanks so much for your help @hhhjort and @dbemiller, cheers!
