### ISSUE TITLE
Where to set {{gdpr}} value?

### ISSUE THREAD

**Issue by Guilemon** [prebid/prebid-server#719]
I want to set gdpr for cookie sync as 0 but it is always defaulting to 1.

In prebid-server config, no gdpr related configs are set currently. also tried adding `Regs.Ext.gdpr=0` in stored_request but still while usersync, getting url as `serverurl/setuid?bidder=biddername&gdpr=1&gdpr_consent=&uid=someuidvalue`. 

I'm implementing this in amp pages. Also, it is self hosted prebid server

**Comment by dbemiller** [comment]
The `{{gdpr}}` macros are populated using the `gdpr` property in the `/cookie_sync` request: https://github.com/prebid/prebid-server/blob/master/docs/endpoints/cookieSync.md#sample-request

AMP pages don't send gdpr/consent info in their cookie sync requests. They're working on it. See https://github.com/ampproject/amphtml/issues/15653

You can set `gdpr.usersync_if_ambiguous` to `true` in your app config if you want to treat "no GDPR info given" as "safe to usersync."

**Comment by Guilemon** [comment]
Thanks for clarifications. The usersync error got fixed after setting `gdpr.usersync_if_ambiguous` to `true`.
Thanks. closing this now.

**Comment by amaurybrisou** [comment]
May I ask if gdpr/consent_string can now be sent from an amp page ? I can't find how to build my amp-iframe url to send these values to /cookie_sync endpoint.

Thank you
