### ISSUE TITLE
Validating Usersyncs

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#733]
# Symptom

There's a bug with Beachfront on the Appnexus deploy right now. To reproduce, send this request:

```
{
  "bidders": ["beachfront"],
  "gdpr": 0
}
```

to `https://prebid.adnxs.com/pbs/v1/cookie_sync`. You'll see this response:

```
{
    "bidder_status": [
        {
            "bidder": "beachfront", 
            "no_cookie": true, 
            "usersync": {
                "type": "redirect", 
                "url": "142"
            }
        }
    ], 
    "status": "no_cookie"
}
```

The `url` here is obviously invalid.

# Root cause

In Prebid Server, Usersync URLs are generally configurable. For most syncs, good defaults are defined in [the config](https://github.com/prebid/prebid-server/blob/master/config/config.go#L355)... but not always. In this case, Beachfront doesn't define a default.

Since these URLs are in the Config, there's no way to bad ones with automated tests. That's why this bug went undiscovered for so long.

# Proposed Feature

We shouldn't return syncs that won't work. It's bad for client-side performance, and attempting them doesn't add any value. It also confuses anyone looking at the devtools in their browser, since these failed requests show up as errors.

I suggest that we add some features to Prebid Server in stages to help mitigate this problem:

**Phase 1**: Ping every usersync URL periodically (maybe every 10-15 seconds? Should be configurable), and keep track of which ones are "working."

A "working" sync URL should either return a 2xx, or return a 3xx with a redirect back to Prebid Server at `/setuid` using the appropriate `bidder` param.

**Phase 2**: Make sure that `/cookie_sync` only returns syncs for bidders which we know to be "working."

**Phase 3**: Add an `/info/` URL that returns the current sync status of every Bidder as an API. This can be used to build docs/UIs that let publishers see whether user syncs are working in real time.

**Comment by muncha** [comment]
Thank you. I'll look into this.

**Comment by muncha** [comment]
Should I put in an issue related to correcting our sync behavior or is just a pull request OK?

**Comment by dbemiller** [comment]
just a pull request is ok
