### ISSUE TITLE
Prebid Server Transparency

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#757]
One of the desires that came out of the Prebid events this month is that some publishers would like better transparency into the auction logic of Prebid Server. While the code is open source, some people have rightly pointed out that hosted clusters of Prebid Servers could be altered by a hosting company and there would be no way to tell.

We've discussed this in the Prebid Server Committee and proposed that the server could support transparency efforts by optionally forwarding all bid information either in the bidResponse or to a separate transparency service. Currently detailed bid info is only available when the debug flag is set, and it's only available in the bid response, not as a separate feed. The publisher (or a delegated 3rd party) could collect and cross-reference information from various parties involved in the transaction and highlight discrepancies.

For example, PBS could log key bids received and any transformations applied to them. Something like:

```
{
   app: {},
   device: {}, 
   site: {}, 
   timestamp: "2018-11-30 12:00:00.736 UTC-500",
   bidsReceived: [
      {
          pbsImpressionId: "11111",
          bidder: "bidderA",
          bidStatus: "success",
          bidderBidId: "834fafee-fe2f-40cb-a6c9-58369067d9d5",
          originalBid: 2.22,
          currency: "USD",
          mediaType: "banner",
          size: { width: 300, height: 250 },
          creativeId: "3333333",
          bidTransformations: {
              currencyConversion: 0.88,
              bidAdjustment: 0.95
          }
          modifiedBid: 1.86,
          priceGranularityBucket: 1.80,
          winningBidFlag: 0
      },
      {
           pbsImpressionId: "11111",
           bidder: "bidderB",
           bidStatus: "noBid",
           ....
      },
      {
         ... other bidders and other impressions ...
      }
   ]
}
```
(actual format and fields TBD)

With this data, if the publisher (or 3rd party service) has access to log-level data from `bidderA`, they could verify the bid was for $2.22 by joining on bidderBidId and/or timestamp/device/site/app information. Likewise, if they have access to data from `bidderB`, they could verify the No-Bid status.

If this general approach is accepted as valuable by the community, some proposed high level requirements:

1) Each account should be able to specify in Prebid Server config whether it wants to utilize the auction transparency feature. Account is defined as site.publisher.id or app.publisher.id
2) Each account should be able to specify a sampling rate for how often they want to verify auctions. e.g. 0.1% of auctions. Minimum sample rate should be 0.001%. Default should be 100%.
3) Each account should optionally be able to specify a URL where Prebid Server should post the JSON auction transparency results.
4) Each account should optionally be able to specify whether they want to have the transparency results directly inside the Prebid Server bid responses. In this case, the bid response doesn't need site/app/device info because we can assume the client has it, and will log whatever's needed to join with other log sources.
5) This feature is driven by server-side config, not request or stored-request parameters. The Prebid Server hosting company should be allowed to decide which accounts may utilize this feature, and place any conventional limits they wish on the sampling rate. Posting this data does result in a cost to the Prebid Server hosting company, who may wish to impose fees or minimum traffic levels.
6) Prebid Server should first respond to the bid before posting the transparency results to the optional URL.
7) Prebid Server should log to the metric service how many transparency results are posted sucessfully and in error by account ID. It should be possible for administrators to generate operational alerts so errors can be investigated.
8) Prebid Server should optionally support placing the transparency results in a log file that can be retained for later proof of fidelity. Again, it would be up to the Prebid Server hosting company whether it wants to bear the expense of creating, maintaining, and possibly distributing log files.

If these high level requirements are accepted as a reasonable solution to the use case, we'll assign a technical team to define and refine the details of the protocol.

Let the discussion begin.

**Comment by hhhjort** [comment]
This ties in with issue #745 which would separate the PBS prebid debug behavior from the `test` flag which would tell bidders not to bill on anything delivered through that request. This is to allow publishers to debug on an actual live auction rather than having the bidders go through a potentially altered auction logic intended for debugging. The use case and problem to solve are different, but what is happening under the hood is very similar so we should have some coordination between the two issues to avoid duplicating work.

**Comment by SyntaxNode** [comment]
@bretg Let's discuss at the next Prebid Server Committee meeting. We now have https://github.com/prebid/prebid-server/issues/745 implemented and the information is available to analytics modules if someone wants to build something like a validation service. Host companies could also work with third party auditors to confirm there are no changes to their bidding logic from the open source variant.

Considering we haven't talked about this for 2 years, I'm assuming this is no longer a concern.

**Comment by bretg** [comment]
Discussed in Prebid Server Committee. We feel this can be addressed by analytics adapters and audits.

Closing.
