### ISSUE TITLE
Add video support to prebid server

### ISSUE THREAD

**Issue by alinetskiy** [prebid/prebid-server#76]
1. Prebid server will support mixed media types within one ad unit.
2. PBS Request will be augmented in the following way:
         a. PBSAdUnit structure will have MediaTypes field added. The field is to be an array of enumerated type with the two values: “banner” and “video”. The array can have 1 or 2 elements of the type, repeating elements ignored. (So, it can be [“banner”], [“video”] or [“banner”, “video”]). For backward compatibility if the field is absent, it will be treated as [“banner”].
         b. A new filed Video will be added to PBSAdUnit. It will be either a reference to PBSVideo data structure, which will hold the parameters for Video (TBD) or NIL.
3. The routine which converts PBSRequest into a generic OpenRTB request will be augmented in the following way:
         a. A new Boolean parameter “singleMediaTypeImp” will be added to the signature. If the parameter is true, for each media type (“banner” or “video”) a separate “Imp” element will be generated. Otherwise the Imp element will have data for both media types
         b. The routine will check submitted data to match the required media types; in case of mismatch (“video” media type is present, but the Video data structure is missing) the request should fail.
         c.  The routine will add Video data to OpenRTB request as specified above.
4. If necessary, PBSResponse will be adjusted to include video-related data.

**Comment by bokelley** [comment]
On 3a, it appears that some bidders can not only not handle multi-media-type Imp objects, they can't handle multiple Imp objects in the same request. See the facebook and rubicon adapters as examples. I think that means we may need to add this to the loop in those adapters where we create the requests array, and the call to make the openrtb object should have a "media types" parameter which would be either all of them (if the adapter can handle it) or a single type. This will result in a separate call to the adapter for each configured media type.

**Comment by bokelley** [comment]
Also, let's make sure that we're thinking about the SDK and what it needs here. And how to make this incredibly easy to set up so the publisher gets video for free and doesn't have to think about it.

**Comment by mkendall07** [comment]
>so the publisher gets video for free and doesn't have to think about it.
Not sure I know what you mean. The pub will need to at least ad `video` to the supported media types on the adUnit in pbjs. After that it should "just work". Let me know if you thinking something else.

**Comment by bokelley** [comment]
Yeah, that's a reasonable start.

**Comment by mkendall07** [comment]
Example request:

```
{
	"account_id": "<ID>",
	"tid": "c7ad5e5b-2d8c-48e4-84ba-fb0538dd3c23",
	"max_bids": 1,
	"timeout_millis": 1000,
	"secure": 0,
	"url": "http://ap.localhost:9999/integrationExamples/s2s_instream_video.html",
	"prebid_version": "0.32.0-pre",
	"ad_units": [{
		"code": "/19968336/header-bid-tag-0",
		"sizes": [{
			"w": 640,
			"h": 480
		}],
		"bids": [{
			"bidder": "appnexus",
			"params": {
				"placementId": 9333431
			},
			"bid_id": "18ce65d53c30cf"
		}],
		"transactionId": "7cd0c0ae-3049-47cc-ad82-68ecf04bb7ab",
		"video": {
			"mimes": ["video/mp4"],
			"protocols": [1, 2, 3, 4, 5, 6, 7, 8],
			"playbackmethod": [2]
		}
	}],
	"is_debug": true
}
```

Example response:
```
{
	"tid": "c6d2a512-20fa-4fc2-82a3-ebf50e2b4fe7",
	"status": "OK",
	"bidder_status": [{
		"bidder": "appnexus",
		"response_time_ms": 117,
		"num_bids": 1
	}],
	"bids": [{
		"bid_id": "1d8e7b3cc94a51",
		"code": "/19968336/header-bid-tag-0",
		"creative_id": "53228341",
		"media_type": "video",
		"bidder": "appnexus",
		"price": 5,
		"nurl": "http://nym1-ib.adnxs.com/ab?e=wqT_3QLiB6DiAwAAAwDWAAUBCIuvyc8FEIyIrIHw4_feXhiGzf_Mv6uq8F4qLQkAAAECCBRAEQEHNAAAFEAZAAAA4HoUFEAhERIAKREJoDC31bkEOL4HQL4HSAJQteawGViFkUFgAGiRQHiMuwSAAQGKAQNVU0SSBQbwUJgBAaABAagBAbABALgBA8ABA8gBAtABCdgBAOABAPABAIoCO3VmKCdhJywgMTE5Nzc3NiwgMTUwOTA1NDM0Nyk7dWYoJ3InLCA1MzIyODM0MTYeAPCckgLxASFaRFB4eHdqLXJOUUdFTFhtc0JrWUFDQ0ZrVUV3QURnQVFBUkl2Z2RRdDlXNUJGZ0FZQjVvQUhBZWVNS2hCSUFCSG9nQndxRUVrQUVCbUFFQm9BRUJxQUVEc0FFQXVRSHpyV3FrQUFBVVFNRUI4NjFxcEFBQUZFREpBU0JBbWV2NUZPNF8yUUVBQUFBQUFBRHdQLUFCQVBVQgUPKEpnQ0FLQUNBTFVDBRAETDAJCPBETUFDQU1nQ0FPQUNBT2dDQVBnQ0FJQURBWkFEQUpnREFhZ0RfcXpVQnJvRENVNVpUVEk2TXpZd01BLi6aAi0hS0FteXBnNvQAyGhaRkJJQVFvQURvSlRsbE5Nam96TmpBd9ICdzc3MTg5MTUsNzg2OTkzOSw2OTkxODU2LAUICDYwLAUIBDczBQgIOTQ4AQgsMjAyNCw3MzIzOTgxAQgMNDA1OAUICDM1MAEICDYwNAUYCDYwNQ0IBDc3CRgAOAkg8GY0ODDYAugH4ALH0wHqAkRodHRwOi8vYXAubG9jYWxob3N0Ojk5OTkvaW50ZWdyYXRpb25FeGFtcGxlcy9zMnNfaW5zdHJlYW1fdmlkZW8uaHRtbPICEQoGQURWX0lEEgcxMTk3Nzc2BRQIQ1BHBRQYMzI1NDMwNwEUCAVDUAET8JMIMTM5NjQ5MjaAAwGIAwGQAwCYAxSgAwGqAwDAA5AcyAMA2AMA4AMA6AMA-AMDgAQAkgQJL29wZW5ydGIymAQAogQMMjQuMTE1LjcyLjMxqASf7wSyBA4IARAAGIAFIOADMAA4ALgEAMAEAMgEANIECU5ZTTI6MzYwMNoEAggA4AQA8AS15rAZiAUBmAUAoAX_____BQOwAaoFJGM2ZDJhNTEyLTIwZmEtNGZjMi04MmEzLWViZjUwZTJiNGZlN8AFAMkFaX1M8D_SBQkJAAAAAAAAAADYBQHgBQE.&s=a6b896bfa44dc4b58db0ef707a762c5b9889244b&referrer=http%3A%2F%2Fap.localhost%3A9999%2FintegrationExamples%2Fs2s_instream_video.html&pp=${AUCTION_PRICE}&",
		"width": 1,
		"height": 1,
		"response_time_ms": 117
	}]
}
```

**Comment by mkendall07** [comment]
this is implemented now.
