### ISSUE TITLE
code 999: Bid "XXXXX" does not contain a positive 'price'

### ISSUE THREAD

**Issue by kangw3n** [prebid/prebid-server#783]
"ranges": [
                        {
                            "max": 5,
                            "increment": 0.01
                        },
                        {
                            "max": 8,
                            "increment": 0.05
                        },
                        {
                            "max": 20,
                            "increment": 0.5
                        }
                    ],

my pricegranularity as above

**Comment by dbemiller** [comment]
This is an issue with the Bidders--not your price granularity. They're sending back a bid whose price is 0, which PBS doesn't consider to be a valid bid.

**Comment by kangw3n** [comment]
Thanks for saving my day!
We just told our bidders to reset those prices.
