### ISSUE TITLE
Prebid Server is responding no_bid.

### ISSUE THREAD

**Issue by vishalgarale** [prebid/prebid-server#79]
We have two ad unit slots, one having valid AppNexus placement id, another having invalid AppNexus placement id. When a call goes to Prebid Server it returns no_bid for all ad units.

Eg. Consider adunit1 and adunit2, valid Appnexus placement id APNX1 (5823300), invalid Appnexus placement id APNX2 (5823302).

If we call like
AdUnit1 - APNX1
AdUnit2 - APNX1

Prebid server responded with valid bids.

If we call like
AdUnit1 - APNX1
AdUnit2 - APNX2

Prebid server responded with invalid bids.

What is Prebid servers internal implementation? If one platform does not give bid then will it return no bid?

**Comment by bokelley** [comment]
I think that's actually on the AppNexus side, not the PBS side, since PBS doesn't know which placements are valid or not. Can you try it with debug=1 set so you can see the actual call made to AppNexus?

**Comment by mkendall07** [comment]
If the 2nd adUnit config is invalid, AN most likely doesn't return any bids. Make sure you setup is correct. Also debug output (see above) is helpful in troubleshooting.

**Comment by vishalgarale** [comment]
@mkendall07 All our configs are valid (valid Appnexus placement ids). The Prebid server gives no-bid when any one of placements in a platform (eg. Appnexus) returns no-bid for any single ad unit. To check you can send cURL request to Prebid Server individual and then a combination of above tags I have given in issue description.

**Comment by mjacobsonny** [comment]
@vishalgarale -- The request containing both placement IDs is failing because those placements belong to different AppNexus seller members.  AppNexus will reject any request which contains placements belonging to more than one member.  Also, Placement ID 5823302 is inactive and belongs to an inactive seller member.  Can you please make sure you are passing the correct placement IDs.
