### ISSUE TITLE
Prebid Server account showing Requests Per Second and Bids Per Second in minus

### ISSUE THREAD

**Issue by vishalgarale** [prebid/prebid-server#80]
In Prebid Server account (https://prebid.adnxs.com/account/) Requests Per Second and Bids Per Seconds showing in minus values.

![rpm_in_minus_censored](https://user-images.githubusercontent.com/9536053/27946724-a045a644-6310-11e7-8d2a-970bfcc154ce.jpg)

**Comment by bokelley** [comment]
@mkendall07 this is grafana weirdness again. I wonder if we are configuring it wrong...

**Comment by dbemiller** [comment]
We found the root cause. There are two instances of prebid-server deployed, but the data for the (cumulative) bid & query counts are intermingled.

We're working on a fix now. In the meantime, those metrics are (obviously) not reliable--even if they're showing up positive for you.
