### ISSUE TITLE
dep issues with buger/jsonparser & mxmCherry/openrtb while building under go1.10.1, python 2.7 & dep 0.5.0

### ISSUE THREAD

**Issue by BZSky** [prebid/prebid-server#840]
while deploying on CENTOS, go1.10.1, dep 0.5.0, stumbled with dep issues with these packages: 

[[constraint]]
  | branch = "master"
  | name = "github.com/buger/jsonparser"
[[constraint]] |  
  | name = "github.com/mxmCherry/openrtb"
  | version = "~10.0.0"

Had to add a source for both to get them to resolve (for jsonparser reverted to this source: https://github.com/prebid/prebid-server/commit/fc3dddcf9a5f576cbd4e5c42f3fe14b8a598e44a#diff-836546cc53507f6b2d581088903b1785)

**Comment by bretg** [comment]
@benjaminch - can you confirm this one?

**Comment by benjaminch** [comment]
Hello guys !
As a matter of fact, prebid-server project supports the last two Golang versions. As of today it's 1.11 and 1.12 as stated in the docs.
Some third parties might have lost compatibility.
@BZSky can you try deploy it with 1.11 or later ?
Thanks
