### ISSUE TITLE
Need to verify any issue with cookie sync and user info passing in bid request

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#849]
Hi @hhhjort, @josephveach,

Can anyone please confirm whether you are receiving cookie sync redirect url from "brightroll" bidder correctly? We are seeing a few issues in cookie sync match rate with our publisher. So would like to verify you on the match data you are building up on your side currently for us. Are you able to receive cookies from us and able to send the matched user's info in buyeruid in bid request? Please let us know

Thanks
Smitha

**Comment by smithaammassamveettil** [comment]
A few questions to clarify on that as well :- 
1. Please confirm the URL to call you for cookie sync is this:
Encoded: https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24%7BUID%7D

The above URL after decoding is 
https://ib.adnxs.com/prebid/setuid?bidder=brightroll&gdpr=0&gdpr_consent=&uid=**${UID}**

2. While redirecting, the user cookie (for eg: 1234) should be passed as 
https://ib.adnxs.com/prebid/setuid?bidder=brightroll&gdpr=0&gdpr_consent=&uid=**1234**

**Comment by Aadeshp** [comment]
It doesn't seem like the brightroll usersync pixel is returning a 302 redirect to `ib.adnxs.com/prebid/setuid` back to the browser
https://imgur.com/a/mdszst1

**Comment by smithaammassamveettil** [comment]
Thanks for verifying and confirming it.  Can we keep this ticket open for couple of days? I am doing a fix for that. Ref: PR :https://github.com/prebid/prebid-server/pull/852
Would like to verify this after the fix.

**Comment by smithaammassamveettil** [comment]
@Aadeshp Looks like now we are doing a 302 to prebid server ib.adnxs.com/prebid/setuid. Can you please confirm and let us know if you see any issues/abnormalities in cookie match setup with us(brightroll)?

@hhhjort  Is this(ib.adnxs.com) going to be Prebid server domain for cookie sync call always? We would like to add your domain to a  whitelist at our side to avoid any fraud redirects.

**Comment by hhhjort** [comment]
Yes, this is a permanent setup, or at the very least there are no plans to change it into anything else.

**Comment by smithaammassamveettil** [comment]
Thanks for confirming @hhhjort 
A few more questions to confirm please- 
1 ) Will it be url encoded always?https%3A%2F%2Fib.adnxs.com%2Fprebid%2Fsetuid%3Fbidder%3Dbrightroll%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID
2) The url will be on https(secure) always?

**Comment by hhhjort** [comment]
No plans to change anything about the usersyncs on our instance.

**Comment by smithaammassamveettil** [comment]
Thanks.
