### ISSUE TITLE
Default currency should be configurable

### ISSUE THREAD

**Issue by cheung-chifung** [prebid/prebid-server#869]
We are going to run PrebidServer in Japan, our service mainly use `JPY`, but also want to support `USD` in the future.
I'll appreciate if we can change the default currency from `USD` to a configurable one, which can let me use `JPY` by default and use `USD` in the future with the currency converter.

**Comment by benjaminch** [comment]
Hello @cheung-chifung, depending what the core team thinks here, it should be doable pretty easily and I will be able to provide such mechanics in the light of #280 

Cheers

**Comment by benjaminch** [comment]
Thinking about it, we might want to double check that. I think by default, in Open RTB,  if not set currency is considered as `USD`.
It's totally doable but  we should document heavily the impacts of changing the default currency on prebid's side.

![image](https://user-images.githubusercontent.com/1393795/57128427-ace7c000-6d93-11e9-9927-ee20105556f1.png)
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf (page 28)

**Comment by bretg** [comment]
PBS-Java implemented the ability for host companies to set their default currency as specified in https://github.com/prebid/prebid-server/issues/280

> we should document heavily the impacts of changing the default currency on prebid's side

I agree there's not enough PBS-specific info, but basically it's the same as done on Prebid.js -- http://prebid.org/dev-docs/modules/currency.html

0) PBS polls a currency conversion file every N minutes
1) if the 'adServerCurrency' is different than the bid currency, the conversion rate is used to convert bids
2) Prebid Server has deprecated the default pricegranularity buckets (low,med,high,auto,dense) anyhow, so if the originator wants PBS to supply the targeting, they need to provide it. For Yen, we recommend using a custom pricegranularity.
