### ISSUE TITLE
Improvement: Poll vendorlist.json URL less Frequently

### ISSUE THREAD

**Issue by Grantimus9** [prebid/prebid-server#874]
The IAB's Global Vendor List (https://vendorlist.consensu.org/vendorlist.json) is updated only once a week, on Thursdays. The IAB Europe (who pays the CDN bill) has repeatedly requested vendors to poll it less frequently because it's not updated. 

Examples: 
version 139 published 2019-03-21T16:00:21Z
version 140 published 2019-03-28T16:00:18Z
version 141 published 2019-04-04T16:00:18Z 

Proposal: 
Prebid server should poll the IAB URL once a day at most.

**Comment by bretg** [comment]
Sorry for the delay - opened a ticket to get this done for PBS-Java
