### ISSUE TITLE
update interstitial size support

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#877]
## Type of issue
Feature improvement

## Description
The initial design implementation for improved interstitial support per #755 has several drawbacks and limitations that can either be improved or revised.

 In an effort to keep size handling server-side and conform to OpenRTB norms, I am proposing one or both of two possible solutions below. Ideal case would be both would be used in conjunction:

1. Storage Requests: Use stored requests for size eligibility based on request attributes
2. Size Inferred By Exchange: Keep wminperc / hminperc, do not use static size list and allow Exchanges to infer size(s) based on request attributes

## Proposal Stored Requests
The idea behind this proposal is based on the following goals:
- Control of ad selection is placed in the hands of the Publisher
- Controls of ad configuration are set server-side
- Publishers will have control if they wish to monetize full size interstitials with or without additional sizes
- Exchanges can enforce limits

**Design**
The publisher would pre-define a list of all possible sizes they wish to be allowable for interstitials in the Store Requests DB associated to one stored request:

```"id": "inst-alt-sizes", 
    "imp": [
        {
            "banner": {
                "format": [
                    {
                        "h": 250, 
                        "w": 300
                    }, 
                    {
                        "h": 480, 
                        "w": 320
                    }, 
                    {
                        "h": 50, 
                        "w": 320
                    }, 
                    {
                        "h": 50, 
                        "w": 300
                    },
                    {
                        "h": 240, 
                        "w": 320
                    }, 
                    {
                        "h": 100, 
                        "w": 320
                    }
                ]
            }, 
            "ext": {
                "rubicon": {
                    "accountId": 123, 
                    "siteId": 456, 
                    "zoneId": 7777
                }
            }, 
            "id": "1"
        }
    ]
}
```

In the request will contain logic indicating it's a full screen (format object with w: 320, h:480 in this case), the interstitial flag ("instl":1) and a stored request ("id":"inst-alt-sizes"

Request logic
```
{
	"imp": [{
		...
		"banner": {
			"format": [{
				"w": 320,
				"h": 480
			}],
                 "instl":1
		},
		"ext": {
			"prebid": {
				"storedrequest": {
					"id": "inst-alt-sizes"
				}
			}
		}
	}],
	"device": {
		...
		"w": 411,
		"h": 659,
		"pxratio": 3.5,
		"prebid":{
			"interstitial": {
				"minwidthperc": 50,
				"minheightperc": 40
			}
		}
	}
}
```
- In the above example, any ad whose width is greater than 206 **AND** height is greater than 264 is eligible. To deduce the size of the request payload above, no additional sizes meet this criteria. 320x480 is treated as a special size to signal full screen and will be eligible regardless of minwidthper or minheightperc
- minwidthper and minheightperc will reduce the full list of eligible sizes in the stored request to be placed in the internal interface to the Exchanges
- Furthermore, each exchange can determine if they want to enforce a max number of sizes, or allow specific eligible sizes.
-- Use case here would be if 10 sizes were eligible, the Exchange can select a limited subset of sizes it wants to take in for auction and order them
- Use the following logic to signal full screen interstitial as defined by OpenRTB standards:
-- use format sizes 1024x768 (landscape) or 768x1024 (portrait) for tablets
-- use format sizes 320x480 (portrait) or 480x320(landscape) for mobile devices

## Proposal Size Inferred By Exchange
This proposal can work in conjunction above with the absence of a stored request or as a standalone solution (not having a stored request). 

The flow would be as follows:

- Request comes to Prebid Server as follows
```{
	"imp": [{
		...
		"banner": {
			"format": [{
				"w": 320,
				"h": 480
			}],
                 "instl":1
		}
	}],
	"device": {
		...
		"w": 411,
		"h": 659,
		"pxratio": 3.5,
		"prebid":{
			"interstitial": {
				"minwidthperc": 50,
				"minheightperc": 40
			}
		}
	}
}
```

- The absence of a storage ID **AND** presence of the interstitial object with either minwidthperc and / or minheightperc populated will signal Exchange to infer size on their own or pass on alternate sizes
- Each Exchange will perform the handling of what sizes it wishes to monetize based on request attributes

## Other information

This feature was originally coded in the following PR: https://github.com/prebid/prebid-server/pull/797/files

**Comment by hhhjort** [comment]
I am not sure what exactly you are proposing here. The solution in #755 was built as an alternative to the publisher explicitly populating the list of allowed sizes. There is nothing preventing the publisher from still doing this, all the `interstitial` object does is create a list of sizes given the min percentages and the device or supplied maximum size. Could you describe better what you solution supplies beyond either submitting the list of sizes or using the `interstitial` object to have PBS generate a list of sizes?

**Comment by bszekely1** [comment]
Correct, this design is flawed and should not be built. That is why it's closed. it's an extremely stale issue at this point.
