### ISSUE TITLE
First Party Data support

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#879]
[This is the Prebid Server side of https://github.com/prebid/Prebid.js/issues/3687]

## Updates

This issue has been somewhat significantly modified since the original post

1. More detail mapping the sources of the OpenRTB attributes. Providing a reference for how FPD works end-to-end. 
2. Normalize some OpenRTB attributes. We found that real-world FPD already coming in is not always in an expected form.
3. No need for imp[].ext.context.ATTRIBUTE. There aren’t any OpenRTB attributes here. Everything should go in imp[].ext.context.data.ATTRIBUTE.
4. Expand AMP first party data processing.
5. Clarify that errors in validating FPD should not cancel the auction. Prebid Server is normally pretty hard-nosed about rejecting “bad” data, but there’s a lot of FPD already flowing out there.

## Description

The goal is to provide a standard way for the page to supply first party data and control which bidders have access to it.

A number of adapters support taking key/value pairs as arguments, but they're all different. e.g.

- Rubicon takes `keywords`, `inventory` and `visitor` parameters
- AppNexus takes `keywords` and `user`
- OpenX takes `customParams`
- Index takes `firstPartyData`
- etc.

## Proposal

See https://docs.google.com/document/d/1I2eS40yMYJCgz8XvFljf4f59bEPsbWTrUpnD7a7uJEg/edit

**Comment by bretg** [comment]
Re-opening this issue to track two updates to the PBJS issue https://github.com/prebid/Prebid.js/issues/3687:

1) Support for bidder-specific config in the OpenRTB (ext.prebid.bidderconfig)
2) AMP support

**Comment by SyntaxNode** [comment]
@bsardo will be implementing this feature for PBS-Go.

**Comment by mansinahar** [comment]
This was implemented and released in PBS-Go as part of [0.183.0](https://github.com/prebid/prebid-server/releases/tag/v0.183.0)

**Comment by bretg** [comment]
Closing!
