### ISSUE TITLE
Set Prebid Server Cookie With SameSite=None and Secure

### ISSUE THREAD

**Issue by mike-chowla** [prebid/prebid-server#900]
With Google announcement last week that cookies will default to first party only starting with Chrome 76, Prebid Server needs to set its uid cookie with SameSite=None so that it's still available since requests to Prebid Server are usually in a third party context.

https://web.dev/samesite-cookies-explained

**Comment by Ethreal** [comment]
> cookies will default to first party only 
Actually not, in 76 Chrome appears flag that sets `SameSite=Lax` if this flag IS ON, which IS NOT by default.

**Comment by bretg** [comment]
We also need to consider adding the `secure` flag to PBS cookies. I'm told that the `cookies-without-same-site-must-be-secure` flag will be enabled by default in Chrome in Feb 2020.

See https://web.dev/samesite-cookies-explained/

**Comment by mercuryyy** [comment]
@bretg looks like new chrome is already flagging it, can someone please revisit this issue?

**Comment by bretg** [comment]
You're right @mercuryyy - I see this warning:
```
A cookie associated with a resource at <URL> was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`.
```
This patch is nearly done on the PBS-Java side. Adding @hhhjort to cover PBS-Go.
