### ISSUE TITLE
What would prevent vendors paid impression beacon from firing

### ISSUE THREAD

**Issue by itolu94** [prebid/prebid-server#927]
Over the past couple of months, I've been trying to get a Prebid Server instance up and running.  I got the parameters for each bidder,  setup the server to work with Prebid Cache, and setup user sync.  At this point, I would expect everything to work... but that's not the case.  One bidder is picking up our traffic and we're getting ad responses back but we aren't seeing  paid impressions.   At the same time, another bidder is not picking up any of our traffic.  

I'm fairly new to prebid and would appreciate any feedback.  I've provided a sample stored request.  

```json
{
  "id": "FOO_AMP_300x250_1",
  "site": { "page": "https://www.foobar.com", "publisher": { "id": "foo" } },
  "ext": { "prebid": { "targeting": { "priceGranularity": "dense" } } },
  "imp": [
    {
      "id": "FOO_AMP_300x250_1-imp",
      "banner": { "format": [{ "w": 300, "h": 250 }] },
      "ext": {
        "appnexus": { "placement_id": 1234567 },
        "rubicon": { "accountId": 1234, "siteId": 12345, "zoneId": 1234567 }
      }
    }
  ]
}
```

**Comment by hhhjort** [comment]
What is calling prebid server? You have prebid.js on your page configured to use prebid server, or some other client system interfacing with prebid server?

**Comment by itolu94** [comment]
We've configured our AMP pages to callout our Prebid Server.

**Comment by itolu94** [comment]
As of right now I think it's related to Prebid Cache because we're seeing ad responses from our Prebid Server but are not getting any impression or revenue.   

Can I get some clarification on Prebid Cache.  How does AMP know where to retrieve the ad from?   Looking at Prebid Server response, I don't see anything related to Prebid Cache being included.

**Comment by hhhjort** [comment]
The creative you deliver to the amp page for prebid ads will have to know the domain name of your cache server, but the UUID to identify the content to pull is provided as a targeting key/value pair.

**Comment by itolu94** [comment]
Ahhh.  Our AdOps team used the default [html creative](http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#html-creative). 
`
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
<script>
var ucTagData = {};
ucTagData.adServerDomain = "";
ucTagData.pubUrl = "%%PATTERN:url%%";
ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
try {
ucTag.renderAd(document, ucTagData);
} catch (e) {
console.log(e);
}
</script> 
`
Would we replace the ucTagData.adServerDomain to match the cache server?   

I also saw a creative in #860 that included other parameters.
`
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
    <script>
      var ucTagData = {};
      ucTagData.adServerDomain = "";
      ucTagData.pubUrl = "%%PATTERN:url%%";
      ucTagData.adId = "%%PATTERN:hb_adid_BIDDERCODE%%";
      ucTagData.cacheHost = "%%PATTERN:hb_cache_host%%";
      ucTagData.cachePath = "%%PATTERN:hb_cache_path%%";
      ucTagData.uuid = "%%PATTERN:hb_cache_id_BIDDERCODE%%";
      ucTagData.mediaType = "%%PATTERN:hb_format_BIDDERCODE%%";
      ucTagData.env = "%%PATTERN:hb_env%%";
      ucTagData.size = "%%PATTERN:hb_size_BIDDERCODE%%";

      try {
        ucTag.renderAd(document, ucTagData);
      } catch (e) {
        console.log(e);
      }
    </script>
`
Do we need to use one of these?

**Comment by bretg** [comment]
The creative needs to match the line item targeting. i.e. if the line item is targeted to hb_pb_BIDDER, then the creative attached to that line needs to refer to hb_adid_BIDDER.

The title of this issue refers to an impression beacon not firing. If the creative wasn't correct, you wouldn't be visually seeing the ad either -- so if you're seeing the expected ad but not getting any tracking, that's a separate issue.

**Comment by bretg** [comment]
@itolu94 - is this issue resolved?
