### ISSUE TITLE
Prebid Server COPPA Support

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#929]
Copy of https://github.com/prebid/Prebid.js/issues/3852 - Prebid Server would implement #5 below

## Type of Issue
Feature

## Description
Several bidders have ways for prebid users to pass the COPPA flag, but Prebid.js hasn't specified a standard way to specify it such that all bid adapters can access it.

## Proposal

This doesn't fit into the First Party Data `context` framework because the COPPA flag is always public and should be known to all adapters, while other first party data might be limited to a certain set of bidders.

So the proposal is

1) Declare a configuration convention for the publisher to signal PBJS about COPPA content:
```
pbjs.setConfig({coppa: true});
```
2) PBJS Core gets updated to set the COPPA flag on the bid request object

3) Each adapter supporting COPPA would then be updated to check for the bid request object

4) The Prebid Server Bid Adapter will be updated to pass this value to PBS as regs.coppa=1 when true.

5) Prebid Server will pass regs.coppa (0 or 1) to adapters and will always (not configurable) cause the PBS core to enforce COPPA rounding of IP address and removal of ID as suggested in the OpenRTB standard:

- device.ifa, device.macsha1, device.macmd5, device.dpidsha1, device.dpidmd5, device.didsha1, device.didmd5
- Truncate ip field - remove lowest 8 bits.
- Truncate ipv6 field - remove lowest 32 bits.
- Remove geo.lat, geo.lon. geo.metro, geo.city, and geo.zip
- Remove user.id, user.buyeruid, user.yob, and user.gender

6) Update prebid.org with a page that dynamically lists the COPPA-supporting adapters based on the .md file similar to what we do for GDPR.

7) Define how COPPA flag gets sent in the SDK and then added to the OpenRTB as regs.coppa.

**Comment by mansinahar** [comment]
@bretg in the openrtb spec I see the recommendation to remove `Device.DIDMD5` and `Device.DIDSHA1` but I see a couple more fields to be removed from the `Device` object recommended here. Curious to know why we wanna remove those additional fields also

**Comment by bretg** [comment]
Hi @mansinahar - yeah, after discussing with Prebid.org legal counsel, we decided to remove _all_ IDs. The OpenRTB reference was just a recommendation.

**Comment by mansinahar** [comment]
I see! Thank you @bretg

**Comment by bretg** [comment]
FYI - this is done for PBS-Java

**Comment by mansinahar** [comment]
PRs created for this: #973 and https://github.com/prebid/prebid.github.io/pull/1413

**Comment by mansinahar** [comment]
I believe this can be closed now. Any objections @bretg ?

**Comment by bretg** [comment]
Implemented on both PBS-Go and PBS-Java. Closing.
