### ISSUE TITLE
Unique endpoint for each publisher

### ISSUE THREAD

**Issue by radubarbos** [prebid/prebid-server#939]
I'm working on a new adaptor  for onemobile but our endpoint is unique for each publisher.
Based on the current config validation I have to set a default endpoint.
What is the best approach that will be accepted.
1) Set a dummy URL endpoint
or
2) Change the config validation to allow empty default endpoints

**Comment by hhhjort** [comment]
I suppose setting a dummy endpoint may be the best option.

**Comment by hhhjort** [comment]
Actually I might suggest setting the config to be a "default" endpoint that will be used when the adapter can't work out the proper publisher endpoint.

**Comment by radubarbos** [comment]
I see. I changed the config tests with custom config that provides by adapter endpoints but I can't open a PR because the validation fails. Is it because I'm missing the default config entries?

**Comment by bretg** [comment]
@radubarbos - what do you mean the validation fails -- unit tests? Which test specifically?

**Comment by oath-jac** [comment]
This can be closed. We agreed to disable our adapter by default if we don't have default endpoints URLs.
