### ISSUE TITLE
Invalid request: json: cannot unmarshal number 933.3333333333334 into Go struct field BidRequest.tmax of type int64

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#946]
i'm getting this error using prebid 2.21.0,  is it a known issue or is it my side that something is wrong?
Invalid request: json: cannot unmarshal number 933.3333333333334 into Go struct field BidRequest.tmax of type int64

**Comment by hhhjort** [comment]
The clue is right there : `BidRequest.tmax of type int64`. The openRTB spec defines `tmax` as an integer, so trying to specify a timeout of 933.3333333333334 msec is not valid.

**Comment by spormeon** [comment]
ah ha, bingo,  i know whats wrong then.  Thanks alot
