### ISSUE TITLE
GDPR consent string into AMP RTC vendor callouts

### ISSUE THREAD

**Issue by adamleslie** [prebid/prebid-server#953]
This ticket is to replace the following ticket which was in the incorrect repo and to ensure this doesn't drop off.

https://github.com/prebid/prebid.github.io/issues/1303

We're now successfully passing the consent_string to Prebid server via a custom_URL integration using the web documentation to pass the fields as we think they're expected by Prebid server, however our discussions with our exchanges shows these fields are not making it into the bid requests.

We are assuming that some work is needed to fix this.

Sample page: https://www.google.com/amp/s/metro.co.uk/2019/06/27/love-islands-lucie-donlan-doubles-tommy-fury-friendship-islanders-call-behaviour-10080741/amp/

Sample RTC callout:
https://prebid.adnxs.com/pbs/v1/openrtb2/amp?tag_id=11160550&w=320&h=50&ow=&oh=&ms=&slot=%2F5765%2FMetro%2FMetro.co.uk%2Fprod%2Fentertainment%2Famp-ad-sticky&targeting=%7B%22article%22%3A10080741%2C%22rtc%22%3A1%7D&curl=https%3A%2F%2Fmetro.co.uk%2F2019%2F06%2F27%2Flove-islands-lucie-donlan-doubles-tommy-fury-friendship-islanders-call-behaviour-10080741%2F&timeout=1000&adcid=ODpsb7RRq9rWvYtxaz9oZcxTXvrwRHwdYP-h1468WlZRvzw6KOXxJRhQR7R-CCQ3&purl=https%3A%2F%2Fmetro-co-uk.cdn.ampproject.org%2Fv%2Fs%2Fmetro.co.uk%2F2019%2F06%2F27%2Flove-islands-lucie-donlan-doubles-tommy-fury-friendship-islanders-call-behaviour-10080741%2Famp%2F%3Famp_js_v%3D0.1%26usqp%3Dmq331AQFKAGgAQo%253D%23origin%3Dhttps%253A%252F%252Fwww.google.com%26prerenderSize%3D1%26visibilityState%3Dvisible%26paddingTop%3D32%26p2r%3D0%26horizontalScrolling%3D0%26csi%3D1%26aoh%3D15616543144718%26viewerUrl%3Dhttps%253A%252F%252Fwww.google.com%252Famp%252Fs%252Fmetro.co.uk%252F2019%252F06%252F27%252Flove-islands-lucie-donlan-doubles-tommy-fury-friendship-islanders-call-behaviour-10080741%252Famp%252F%26history%3D1%26storage%3D1%26cid%3D1%26cap%3DnavigateTo%252Ccid%252CfullReplaceHistory%252Cfragment%252CreplaceUrl&gdpr_consent=BOa71ZYOa71ZYAbABBENA8-AAAAbN7_______9______9uz_Gv_r_f__33e8_39v_h_7_-___m_-3zV4-_lvR11yPA1OrfIrwFhiAw&__amp_source_origin=https%3A%2F%2Fmetro.co.uk

**Comment by bretg** [comment]
So we just need to copy the AMP gdpr_consent query string parameter to `user.ext.consent`. Will make this happen on the PBS-Java side. @hhhjort, please open an item for PBS-Go?

@adamleslie - are you willing to share with the community how to implement a custom_URL integration?

**Comment by adamleslie** [comment]
Hi @bretg,

It's worth noting the custom_URL method was just used to try and force the consent string into Prebid server, however the current endpoint is not able to ingest this from how I understand it. Either allowing the consent_string to be ingested via a custom_URL or altering [the vendor configuration](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/callout-vendors.js#L62) are acceptable solutions, although the latter will apply to all publishers using the RTC vendor + amp-consent v2 without us having to share any detail. To confirm though, we are willing to share a working method once we have one.

I'm not sure which option is preferred for Prebid as some change is needed from individual publishers to activate the AMP CMP which passes the consent string (v2) - Prebid server will need to function with and without the consent_string.

Happy to jump on a call and run through if you have any further questions or concerns.

Best,
Adam

**Comment by bretg** [comment]
Sounds like the Prebid Server changes are likely to be simple -- look for gdpr value(s) in the AMP query string and jam them into the stored request before sending on the the adapters.

But before we build it, I'd like to solidify the recommended approach. Not familiar with `custom_url`. It's understood that pubs will need to make changes -- but what scope of changes? Will send you email offline to see if we can chat next week.

**Comment by bretg** [comment]
Update - this has been implemented in PBS-Java: it just looks for gdpr_consent in the AMP arguments and copies to user.ext.consent. Next step is to document how to set this up in AMP.

**Comment by bretg** [comment]
Assigning to @hhhjort for PBS-Go implementation.

**Comment by hhhjort** [comment]
Ahh, missed closing this out, this is in Go as well.
