### ISSUE TITLE
Add playerSize to video response 

### ISSUE THREAD

**Issue by sumit116** [prebid/prebid-server#955]
Feature Required: Add `playerSize` to video response if its there in request payload.

Request Url: `https://prebid.adnxs.com/pbs/v1/openrtb2/auction`

What is playerSize?
- the dimensions (height and width) provided in an adUnit of mediaType video.

sample request payload - 
```
{
    imp: [{
        video {
            playerSize: [[640, 480]]
        }
    }]
}
```

Desired Response:
```
{
seatBid: [{
    bid: [{
       playerHeight: 640,
       playerWidth: 480
    }]
}]
}
```

Note: playerSize is optional in request payload.

**Comment by hhhjort** [comment]
This breaks the openrtb 2.5 spec (https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf)  `playerSize` does not appear to be an attribute of the `video` object and neither `playerHeight` and `playerWidth` are properties of the `bid` object. The `ext` field exists in all these objects to contain custom properties without breaking the openrtb spec.

Also, what is the use case where the client would not be able to reference the request at the time it gets the response?

**Comment by sumit116** [comment]
We dont need `playerSize` from the response anymore. It can be handled from the request only, hence closing this issue.
