### ISSUE TITLE
Prebid Server /openrtb2/video Example

### ISSUE THREAD

**Issue by clutzer** [prebid/prebid-server#961]
I've attempted to get the /openrtb2/video endpoint working and run into some roadblocks, both technical and cognitive.  It would be beneficial to have a working example of this endpoint to help ensure that Prebid Server is configured correctly, and what the format of stored requests supporting adpods might look like.

**Comment by mansinahar** [comment]
@clutzer Maybe this might help: http://prebid.org/prebid-server/endpoints/openrtb2/video.html

**Comment by bretg** [comment]
@mansinahar - I think the doc needs to be clarified as to the difference between the `storedrequestid` and the `pod.configid`. Examples of what's stored in the DB for those two scenarios would help.
