### ISSUE TITLE
Need contact info for several adapter maintainers

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#971]
We're trying to compile an email distribution list for all Prebid Server adapter maintainers. We're doing pretty well so far but haven't been able to confirm several addresses. So I'm adding in the github handles for people who touched these adapters:

- 33across - headerbidding@33across.com has not responded (@thomas-33across)
- adtelligent - hb@adtelligent.com has not responded. (@aradilov)
- unruly - prodev@unrulymedia.com bounces (@lewismoore10100)

Please update your maintainer email addresses in https://github.com/prebid/prebid-server/tree/master/static/bidder-info

thanks

**Comment by Nistenf** [comment]
Hi @bretg, the eplanning address is correct and should be working right now, but we have not received anything. Could you resend (with copy to "desarrollo at e-planning.net", if possible) to verify please?

**Comment by bretg** [comment]
Thanks @Nistenf - removed e-planning from the list

**Comment by jbartek25** [comment]
Hi @bretg. I've submitted a [PR](https://github.com/prebid/prebid-server/pull/977) to have Improve Digital contact email updated in the PBS adapter. I'll be updating Prebid client shortly with a bigger bunch of changes so will update contact email there later.

**Comment by bretg** [comment]
Thanks @jbartek25.
