### ISSUE TITLE
/openrtb2/auction samples aren't working

### ISSUE THREAD

**Issue by lockland** [prebid/prebid-server#995]
I've tried to do a request using postman and those samples on this [link]( https://github.com/prebid/prebid-server/tree/master/endpoints/openrtb2/sample-requests/valid-whole/exemplary) and the server returned an error to me with that message: **Invalid request: request missing required field: "id"**

**Comment by Jobeso** [comment]
If you take the object that is in `requestPayload` as your body it is working.

```json
{
    "id": "some-request-id",
    "site": {
      "page": "prebid.org"
    },
    "imp": [
      {
        "id": "some-impression-id",
        "banner": {
          "format": [
            {
              "w": 300,
              "h": 250
            },
            {
              "w": 300,
              "h": 600
            }
          ]
        },
        "ext": {
          "appnexus": {
            "placementId": 10433394
          }
        }
      }
    ],
    "tmax": 500
  }
```

**Comment by lockland** [comment]
I have already tried it and it works. Thank you.

**Comment by mansinahar** [comment]
@lockland I will close this one as you've confirmed that it works. Thanks @Jobeso!

**Comment by lockland** [comment]
Ok, but shouldn't you guys fix the sample struture?
I think other ones will try to use those samples because they are mentioned on the entrypoint docs and the example won't work as they were written. That is the problem I've quoted here.
