### ISSUE TITLE
Move to Go modules?

### ISSUE THREAD

**Issue by benjaminch** [prebid/prebid-server#998]
Hello there !

Now that prebid-server supports Go 1.11 and later, what do you think about introducing Go Modules support?
It has clear advantages including the Go setup.
I think it's not really a small dev but worth it IMO.
Here's the reference for it: https://blog.golang.org/using-go-modules

As far as I know, impacted parts of the projects will be:
- Documentation
- Docker setup
- CI setup
- Maybe tests script

What do you guys think about it?

I can definitely start working on it if you want :)

Cheers

**Comment by mansinahar** [comment]
@benjaminch That'd definitely be good to have and if you're interested, sure go ahead and work on it. I will assign this issue to you. Thanks so much :)

**Comment by benjaminch** [comment]
Hey @mansinahar, yes please assign it to me I will be happy to tackle this one ;)
Cheers !

**Comment by SyntaxNode** [comment]
Would you consider this completed now since https://github.com/prebid/prebid-server/pull/1052 was merged?

**Comment by benjaminch** [comment]
Yes ! Thanks a lot !
